### ISSUE TITLE
Support for ordering by nested related fields in OrderingFilter

### ISSUE THREAD

**Issue by forgingdestiny** [encode/django-rest-framework#1005]
Example of usage would be sorting by a nested related object.

Nested representation:

``` javascript
{
    'username': 'george',
    'email': 'george@example.com'
    'stats': {
        'facebook_friends': 560,
        'twitter_followers': 4043,
        ...
    },
},
{
    'username': 'michael',
    'email': 'michael@example.com'
    'stats': {
        'facebook_friends': 256,
        'twitter_followers': 120,
        ...
    },
},
...
```

One option is to support the django orm double underscore notation __ for related models.

Ex. `?ordering=stats__facebook_friends` would sort by facebook_friends.

Currently ordering only works for fields of the particular model specified in queryset.

https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/filters.py#L125

**Comment by eldamir** [comment]
Where do you import `RelatedObject` from? Does not seem to be available to me

```
Django==1.8.5
djangorestframework==3.2.3
```

**Comment by xordoquy** [comment]
@eldamir django.db.models.related.RelatedObject

**Comment by eldamir** [comment]
`ImportError: No module named 'django.db.models.related'`

**Comment by xordoquy** [comment]
ah, seems it's been removed from 1.8, see https://code.djangoproject.com/ticket/21414

**Comment by eldamir** [comment]
Thanks for the tip :+1: . The link let to the fix. This works

```
from django.core.exceptions import FieldDoesNotExist
from django.db.models.fields.related import ForeignObjectRel
from rest_framework.filters import OrderingFilter


class RelatedOrderingFilter(OrderingFilter):
    """
    Extends OrderingFilter to support ordering by fields in related models
    using the Django ORM __ notation
    """
    def is_valid_field(self, model, field):
        """
        Return true if the field exists within the model (or in the related
        model specified using the Django ORM __ notation)
        """
        components = field.split('__', 1)
        try:
            field, parent_model, direct, m2m = \
                model._meta.get_field_by_name(components[0])

            # reverse relation
            if isinstance(field, ForeignObjectRel):
                return self.is_valid_field(field.model, components[1])

            # foreign key
            if field.rel and len(components) == 2:
                return self.is_valid_field(field.rel.to, components[1])
            return True
        except FieldDoesNotExist:
            return False

    def remove_invalid_fields(self, queryset, ordering, view):
        return [term for term in ordering
                if self.is_valid_field(queryset.model, term.lstrip('-'))]
```

**Comment by GuillaumeCisco** [comment]
Did not have the problem with the last version of django rest framework :)

**Comment by jpipas** [comment]
Just a note - in Django > 1.10 a couple of the methods have changed 

Specifically you'll have to change the following:

`field, parent_model, direct, m2m = model._meta.get_field_by_name(components[0])`
to
`field = model._meta.get_field(components[0])`

and the signature for `remove_invalid_fields` has changed to:

` def remove_invalid_fields(self, queryset, ordering, view, request):`

Which results in the final working version for Django > 1.10:
```python
class RelatedOrderingFilter(OrderingFilter):
    """
    Extends OrderingFilter to support ordering by fields in related models
    using the Django ORM __ notation
    """
    def is_valid_field(self, model, field):
        """
        Return true if the field exists within the model (or in the related
        model specified using the Django ORM __ notation)
        """
        components = field.split('__', 1)
        try:

            field = model._meta.get_field(components[0])

            # reverse relation
            if isinstance(field, ForeignObjectRel):
                return self.is_valid_field(field.model, components[1])

            # foreign key
            if field.rel and len(components) == 2:
                return self.is_valid_field(field.rel.to, components[1])
            return True
        except FieldDoesNotExist:
            return False

    def remove_invalid_fields(self, queryset, fields, view, request):
        return [term for term in fields if self.is_valid_field(queryset.model, term.lstrip('-'))]
```

**Comment by peeomid** [comment]
Above code will have issue with OneToOneField, adding a fix for that:

**Comment by filiperinaldi** [comment]
field.rel and field.rel.to will raise a deprecation warning on Django >= 1.10. They are now respectively:
* field.remote_field
* field.model

**Comment by apiraino** [comment]
@tomchristie considering this patch has been lingering (and being constantly updated) in this issue for 4 years (we have been using this in production since last year), could it be suitable for a PR and merged into DRF (yes, backed up by a proper set of unittests)?

Just my .2 cents

**Comment by xiangge** [comment]
This patch works to me, can we merge it to the release versions?

**Comment by xordoquy** [comment]
As said earlier, either make it a 3rd party (prefered) or it needs a proper PR with tests and documentation.

**Comment by apiraino** [comment]
@filiperinaldi I think that in Django >= 1.10 `field.rel.to` becomes `field.related_model`. Here's the latest version of the patch that passes our unittests.

n.b. We are using Django 1.11 so ymmw

```
class RelatedOrderingFilter(filters.OrderingFilter):
    """

    See: https://github.com/tomchristie/django-rest-framework/issues/1005

    Extends OrderingFilter to support ordering by fields in related models
    using the Django ORM __ notation
    """
    def is_valid_field(self, model, field):
        """
        Return true if the field exists within the model (or in the related
        model specified using the Django ORM __ notation)
        """
        components = field.split('__', 1)
        try:
            field = model._meta.get_field(components[0])

            if isinstance(field, OneToOneRel):
                return self.is_valid_field(field.related_model, components[1])

            # reverse relation
            if isinstance(field, ForeignObjectRel):
                return self.is_valid_field(field.model, components[1])

            # foreign key
            if field.remote_field and len(components) == 2:
                return self.is_valid_field(field.related_model, components[1])
            return True
        except FieldDoesNotExist:
            return False

    def remove_invalid_fields(self, queryset, fields, ordering, view):
        return [term for term in fields
                if self.is_valid_field(queryset.model, term.lstrip('-'))]
```

**Comment by apiraino** [comment]
Ok people, for the 4th birthday of this issue, I decided to give it a try and hack together an external package to be installed alongside DRF in order to support this useful ordering.

I'll be working on it in the following days to finish the job (namely I need to properly package and factor the code, refine testing and ensure support for actively supported Django versions). Contributions are welcome, of course!

Cheers

**Comment by rpkilby** [comment]
ref #5533.

**Comment by rpkilby** [comment]
@halfnibble - I believe this was fixed in #5533. 

cc @carltongibson

**Comment by jsmedmar** [comment]
Sorry, now I understand. By default it will only work if the related ordering parameter is included in `ordering_fields`. But for a more general solution the patch is still required.

**Comment by Liamw0403** [comment]
Hi there, I am relatively new to DRF and was looking for a way to add ordering to my order fields without exposing the structure of our database. For example, if I wanted to look for z, I would need to write x__y__z, and passing that into the endpoint as a parameter exposes the structure. Is this what I am looking for if I only wanted to say z and have the function check to see if it is a related field in the ORM?

**Comment by rpkilby** [comment]
You could subclass `SearchFilter` and override `get_search_terms`. Something like...

```python
class CustomSearchFilter(SearchFilter):
    def get_search_terms(self, request):
        terms = super().get_search_terms()
        term_map = {
            'z': 'x__y__z',
        }
        return [term_map.get(t, t) for t in terms]
```

**Comment by Liamw0403** [comment]
@rpkilby Thank you so much! This is exactly what I was looking for. I appreciate the help.

**Comment by blodter** [comment]
Here's a solution I put together that's similar to @rpkilby's, just a bit more dynamic. Dunno how kosher it is, though:
`class OrderRelatedFieldsMixin(filters.OrderingFilter):
	_max_related_depth = 3
	
	def retrieve_all_related_fields(self, fields: List[models.Field], depth: int = 0) -> List[tuple]:
		valid_fields = []
		if depth > self._max_related_depth:
			return valid_fields
		for field in fields:
			if field.related_model:
				rel_fields = self.retrieve_all_related_fields(field.related_model._meta.get_fields(), depth + 1)
				for rel_field in rel_fields:
					valid_fields.append((
						f'{field.name}__{rel_field[0]}',
						f'{field.verbose_name if hasattr(field, "verbose_name") else field.name} {rel_field[1]}'
					))
			else:
				valid_fields.append((field.name, field.verbose_name if hasattr(field, 'verbose_name') else field.name))
		return valid_fields
	
	def get_valid_fields(self, queryset: models.QuerySet, view, context: dict = None) -> List[tuple]:
		valid_fields = getattr(view, 'ordering_fields', self.ordering_fields)
		if not valid_fields == '__all_related__':
			if not context:
				context = {}
			valid_fields = super().get_valid_fields(queryset, view, context)
		else:
			valid_fields = [
				*self.retrieve_all_related_fields(queryset.model._meta.get_fields()),
				*[(key, key.title().split('__')) for key in queryset.query.annotations]
			]
		return valid_fields`

**Comment by blodter** [comment]
Here's a solution I put together:

```python
class RelatedOrderingFilter(filters.OrderingFilter):
	_max_related_depth = 3
	
	@staticmethod
	def _get_verbose_name(field: models.Field, non_verbose_name: Union[str, list]) -> str:
		if isinstance(non_verbose_name, list):
			non_verbose_name = non_verbose_name[0]
		return field.verbose_name if hasattr(field, 'verbose_name') else non_verbose_name.replace('_', ' ')
	
	def _retrieve_all_related_fields(
			self,
			fields: Tuple[models.Field],
			model: models.Model,
			depth: int = 0
	) -> List[tuple]:
		valid_fields = []
		if depth > self._max_related_depth:
			return valid_fields
		for field in fields:
			if field.related_model and field.related_model != model:
				rel_fields = self._retrieve_all_related_fields(
					field.related_model._meta.get_fields(),
					field.related_model,
					depth + 1
				)
				for rel_field in rel_fields:
					valid_fields.append((
						f'{field.name}__{rel_field[0]}',
						self._get_verbose_name(field, rel_field[1])
					))
			else:
				valid_fields.append((
					field.name,
					self._get_verbose_name(field, field.name),
				))
		return valid_fields
	
	def get_valid_fields(self, queryset: models.QuerySet, view, context: dict = None) -> List[tuple]:
		valid_fields = getattr(view, 'ordering_fields', self.ordering_fields)
		if not valid_fields == '__all_related__':
			if not context:
				context = {}
			valid_fields = super().get_valid_fields(queryset, view, context)
		else:
			valid_fields = [
				*self._retrieve_all_related_fields(queryset.model._meta.get_fields(), queryset.model),
				*[(key, key.title().split('__')) for key in queryset.query.annotations]
			]
		return valid_fields

````

Then I add this to wherever I want to be able to order by all related fields:
```python
filter_backends = (RelatedOrderingFilter,)
ordering_fields = '__all_related__'
```

**Comment by Hamifthi** [comment]
Does this utility add to the rest package by default finally or not?

**Comment by oesah** [comment]
So another way how you can do it is defining the nested ordering explicitly:

```python
class MyModelViewSet(viewsets.ModelViewSet):
    queryset = MyModel.objects.all()
    serializer_class = MyModelSerializer
    filter_backends = [OrderingFilter]
    ordering_fields = [field.name for field in MyModel._meta.get_fields()] + [
        "foreignkey__title"
    ]
```

I haven't tested it with a related key, so not sure if that will work. But for ForeignKeys on your model, this will work.
