### ISSUE TITLE
Model defaults ignored on empty text field or empty boolean field.

### ISSUE THREAD

**Issue by ZeaQQ4Ug** [encode/django-rest-framework#1101]
My tables has boolean fields like below.

```
enabled = models.BooleanField(default=True)
```

and save it using a serializer in a view class without passing the enabled field in the request.

```
serializer = SomeSerializer(data=request.DATA)
        if serializer.is_valid():
            object = serializer.save()
```

the result is `object.enabled == False`.

I've updated the framework to version 2.3.8 then the issue started occurring. Everything works fine in 2.3.7.

Affected versions >= 2.3.8

**Comment by kulbirs** [comment]
Default values are not saving. I'm using `djangorestframework (3.3.2)`.

**Comment by i-s-o-g-r-a-m** [comment]
@kulbirs take a look at this open issue where we are talking about the problem (I too am still seeing it) -- adding your voice might help get it fixed: https://github.com/tomchristie/django-rest-framework/issues/3788

**Comment by mikelindelsee** [comment]
Just ran into the issue as well.  As a (hopefully) temporary fix, I'm setting the default value to true in my serializer.  E.g.,

`boolean_field = serializers.BooleanField(default=True)`

But this really feels like a hack.  If I ever change the default setting in the model, I'll have to remember that I need to change the serializer too.

**Comment by littlehome-eugene** [comment]
I'm facing the same bug with 3.3.3

**Comment by priyanka03thakur** [comment]
https://github.com/encode/django-rest-framework/pull/5038

I am trying right now to see if this resolves issue. Hope this helps !!

Priyanka

**Comment by gbcgit** [comment]
djangorestframework==3.7.1

        response = client.post(
            '/api/v1/items/',
            {'title': 'blah_title',
                      'description': 'blah_description'})

Notice, not sending the field 'open'

Had to this to get my test to pass - Item.open = True by default

class Meta:
    extra_kwargs = {'open': {'default': True}}

**Comment by Diaga** [comment]
djangorestframework>=3.10.1,<3.11.0

Encountered the same problem. 
The boolean field was set to default to true in models.py, however, when the request was sent to create the object, the object was created with boolean field set to false.

**Comment by Sarctiann** [comment]
I have the same problem on version 3.11.0

**Comment by xordoquy** [comment]
that's the way boolean field send by HTML work. Specification says that if it's not set it should be considered as `False` and therefore it won't use the default.

**Comment by felixpk** [comment]
Is there any workaround?
`is_active` is not part of the request, but I want it to be active by default.

Why can you define the default value of `models.BooleanField` in the first place?

**Comment by xordoquy** [comment]
> Why can you define the default value of models.BooleanField in the first place?

Because it works with anything except html forms.

> Is there any workaround?

Sure and the cool thing is it's [already documented](https://www.django-rest-framework.org/api-guide/fields/#nullbooleanfield)

**Comment by amikrop** [comment]
This still happens to me (3.12.1). httpie sending no data results in a True value, self.client.post sending no data results in False.

**Comment by xordoquy** [comment]
@amikrop which is consistent with previous comments. httpie sending json by default as opposed to self.client.post.

**Comment by amikrop** [comment]
That's right, adding `data=json.dumps(my_dict), content_type='application/json'` to `self.client.post` made it work.
Btw, if I don't explicitly add the `json.dumps` part myself I get a JSON parse error. If I understand correctly, https://docs.djangoproject.com/en/3.1/topics/testing/tools/#django.test.Client.post says if it sees a json content type it serializes the data automatically, but I guess that's a difference between django test client and drf test client, and could be another issue.
