### ISSUE TITLE
permission_classes is not checked for create requests

### ISSUE THREAD

**Issue by a70babat** [encode/django-rest-framework#1103]
when a POST request is sent, has_object_permission(self, request, view, obj) method will be called, but no matter the result is, object will be created.

**Comment by aicioara** [comment]
I had a similar dilemma. Reading this thread, the decision makes sense. Reading https://stackoverflow.com/a/29884278/3374785 gave me a workaround, but it looks really ugly. In particular, logic which should belong together is split in different parts of the code.

@tomchristie What are the best practices to do this sort of permissions as of 2019?

**Comment by xordoquy** [comment]
@aicioara still doesn't make sense to check `has_object_permission` with `obj` being None. It's just the same as `has_permission`.
