### ISSUE TITLE
JavaScript for prettyfiyng JSON in HTML browsable API freezes for large loads of data

### ISSUE THREAD

**Issue by honzajavorek** [encode/django-rest-framework#1137]
I had a JSON result with 1600 and more results. The page became quite unresponsible and after a while my Firefox asked me to kill the prettyfying script. In other browsers it took 10 minutes to load or so (Firefox apparently knows when to suggest JS killing :-) ).

**Comment by mlavin** [comment]
I'm seeing this problem from a slightly different direction. I have a small paginated list of objects. However, one of the fields in the serializer is a `MultiPolygonField`. When you put any real world shape in the number of points can get very large causing `prettyfy` to grind to a halt. If there has been any progress not noted in this case I'd love to hear about it.

**Comment by tomchristie** [comment]
@mlavin Nothing I'm aware of, no.

**Comment by carltongibson** [comment]
Argh! Wow! Here's one from the archive. :-)

I never got to writing the code for this but a simple wrapper around the call to `prettyPrint()` in `rest_framework/static/js/default.js` should fix it...

```javascript
var body_length = $('.response-info .prettyprint').text().length;
if (body_length < SOME_NUMBER) {
  prettyPrint()
} else {
  console.log("Not pretty printing body of length " + body_length);
}
```

**Comment by mlavin** [comment]
I'm going to do some investigation to see if there a solution which doesn't involve disabling the highlighting.

**Comment by tomchristie** [comment]
Perform the highlighting in a web worker maybe?

**Comment by mlavin** [comment]
http://prismjs.com/ claims to do just that but a quick test on my data crashed my browser which is far worse than prettify being slow. highlight.js has support for HTTP highlighting but haven't tried it out yet.

The other option would be to highlight on the server with Pygments http://pygments.org/demo/1145701/ but I would hate to add another dependency.
