### ISSUE TITLE
URLField validator override

### ISSUE THREAD

**Issue by dangusev** [encode/django-rest-framework#1210]
in rest_framework/fields.py:

```
class URLField(CharField):
    type_name = 'URLField'
    type_label = 'url'

    def __init__(self, **kwargs):
        kwargs['validators'] = [validators.URLValidator()]
        super(URLField, self).__init__(**kwargs)
```

Because of this code, validators of URLField cannot be overrided and for do this, I need to inherit the URLField class. Maybe it better should look like this?

```
class URLField(CharField):
    type_name = 'URLField'
    type_label = 'url'

    def __init__(self, **kwargs):
        if not 'validators' in kwargs:
            kwargs['validators'] = [validators.URLValidator()]
        super(URLField, self).__init__(**kwargs)
```

Sorry for my bad english)

**Comment by aehlke** [comment]
This has regressed

**Comment by carltongibson** [comment]
@aehlke Please open a new issue or a PR with a test case showing the change in the behaviour. Thanks.

**Comment by aehlke** [comment]
I investigated but couldn't figure out the new way validators work, so I'm just subclassing now.
