### ISSUE TITLE
Getting started issues.

### ISSUE THREAD

**Issue by qooleot** [encode/django-rest-framework#1249]
I'm a new user to django-rest-framework and ran into several issues, so I thought I'd post them here to see if any pieces of the quickstart docs should be updated to help others avoid the same.

1) A quick first backwards-incompatible django change to consider updating for a new-users focused quickstart:

On django 1.6 the first line of the home page example blows up:

from django.conf.urls.defaults import url, patterns, include

needs to be:

from django.conf.urls import url, patterns, include

2) The framework doesn't seem to work with django-admin.  

I took the basic poll site with django 1.6 (I also tried 1.5.5 and ran into the same issues) with py3.3.2 and pip installed the framework, updated the settings.py as per home page, and completely overrode the urls.py with what was on the home page of django-rest-framework.

At first, everything didn't work due to:

In template /home/taras/Envs/django1/lib/python3.3/site-packages/rest_framework/templates/rest_framework/form.html, error at line 9

Could not resolve URL for hyperlinked relationship using view name "permission-detail". You may have failed to include the related model in your API, or incorrectly configured the `lookup_field` attribute on this field.

I tested in another browser where I was not logged into django-admin as an admin beforehand, and that worked perfectly.

I also tried this on another site, leaving the main urls.py file with /admin/ urls intact and had the same issue.

I tried changing the default permissions thinking that might be somehow related to:

'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAdminUser',),

 and the non-logged browers got a correct json message saying credentials were not provided, and still a stack trace on the other.

Any help with #2 would be great, and let me know if you need additional info.  Thanks!

**Comment by cabello** [comment]
I just started integrating django-rest-framework with an existent project and I am facing similar issues when following the quick start guide, I've added views for Users, Permissions, Groups but I am not sure what other relationships need to be properly configured in order for the `HyperlinkedModelSerializer` to work. For now I just settled for `ModelSerializer`, even though there are no links is a good way to get a fresh start. :)

**Comment by TristanBBQ** [comment]
Hi guys, not sure if there is another issue for that, but I'm having similar issues as @cabello - As soon as I try change my serializer to extend HyperlinkedModelSerializer, I get the error :/

**Comment by mcastle** [comment]
An easy fix:

```
from django.contrib.auth.models import User


class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        exclude = ('user_permissions',)
```

**Comment by bcoover** [comment]
Ok, I have a full and valid fix, add the following

Serializers:
`
from django.contrib.auth.models import Permission
class PermissionSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = Permission`

Views:
`
class PermissionViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows permissions to be viewed or edited.
    """
    queryset = Permission.objects.all()
    serializer_class = serializers.PermissionSerializer
`

Urls:
`
router.register(r'permission', PermissionViewSet)
`
