### ISSUE TITLE
Serializer fields with required=False should be added to model validation exclusions.

### ISSUE THREAD

**Issue by variable** [encode/django-rest-framework#1257]
I explained the problem in Stackoverflow http://stackoverflow.com/questions/19780731/django-cms-framework-serializer-field-required-false

I propose to make the change to truly respect the required=False parameter in serializer fields.

**Comment by darrenbates** [comment]
This bug is back in the latest version.

**Comment by xordoquy** [comment]
@darrenbates code has changed a lot since. If you have an issue feel free to open a new bug with a failing test case to demonstrate the problem.

**Comment by yellowcap** [comment]
Just for reference: the `required` and `allow_blank` argument seems to have no effect on `ModelSerializer` fields, if `unique_together` constraints are set on the corresponding model, see https://github.com/encode/django-rest-framework/issues/4456

**Comment by g-rd** [comment]
ip = serializers.IPAddressField(protocol='both', required=False, allow_blank=True)
also set on model and I get:
    "ip": [
        "This field may not be null."
    ],
Any ideas ?
