### ISSUE TITLE
Bulk create - ModelSerializer with many=True not possible?

### ISSUE THREAD

**Issue by eamonnfaherty** [encode/django-rest-framework#1304]
I am posting the following:
    [{
        "given_name": "zz", 
        "middle_name": "zz", 
        "last_name": "zz"
    },
    {
        "given_name": "zz", 
        "middle_name": "zz", 
        "last_name": "zz"
    }]

to a generics.ListCreateAPIView view which has a ModelSerializer as its serializer.

There does not seem to be an easy way to make many=True and all my attempts of slotting it in somehow are failing.  

How can I do a bulk create using a ModelSerializer and a ListCreateAPIView? There does not seem to be any examples in the docs.  Is this not possible?

**Comment by philippeluickx** [comment]
For reference (as this is 3rd google result): https://github.com/miki725/django-rest-framework-bulk
