### ISSUE TITLE
how to disable throttle while running tests?

### ISSUE THREAD

**Issue by robbyt** [encode/django-rest-framework#1336]
I've written several tests for my new API, but I've started getting 429 errors while my tests are running. What is the best way to disable throttling during tests? Should the API test utilities assist with disabling throttling?

**Comment by saurabh0719** [comment]
@xordoquy your answer worked for me.
I just added this line; myview.throttle_classes = () in the setUp() function of my test class.

**Comment by ku113p** [comment]
if you are use cache for throttle, you may change cache on `DummyCache`

if used `default` cache:

- settings.py
`CACHES = {"default": {"BACKEND": "django.core.cache.backends.dummy.DummyCache"}}`
or
- decorator for test methods/classes
`@override_settings(CACHES={"default": {"BACKEND": "django.core.cache.backends.dummy.DummyCache"})`

**Comment by Chhunneng** [comment]
> @xordoquy your answer worked for me. I just added this line; myview.throttle_classes = () in the setUp() function of my test class.

Even I don't to use view, am I still need to execute `myview.throttle_classes = ()`?
