### ISSUE TITLE
ImproperlyConfigured regular expression on DefaultRouter (format suffixes)

### ISSUE THREAD

**Issue by jrvidotti** [encode/django-rest-framework#1337]
While running the tutorial (part 6), I got an error after implementing DefaultRouter on my urls.py:

```
ImproperlyConfigured: "^users/(?P<pk>[^/]+)/\.(?P<format>[a-z0-9]+)\.(?P<format>[a-z0-9]+)$" is not a valid regular expression: redefinition of group name 'format' as group 3; was group 2
```

The format suffixes are duplicated in regex. My urls.py is pretty basic:

```
router = DefaultRouter()
router.register(r'tasks', views.TaskViewSet)
router.register(r'users', views.UserViewSet)

urlpatterns = patterns('',
    url(r'^', include(router.urls)),
    url(r'^auth/', include('rest_framework.urls', namespace='rest_framework')),
)
```

On DefaultRouter, setting include_format_suffixes to False solved the problem. Is there a bug or I'm doing something wrong?

Python 3.3
Django 1.6.1
Django REST Framework 2.3.10

**Comment by deepak1725** [comment]
Thank you !! @jrvidotti

**Comment by ccw33** [comment]
I met the same question,thank you

**Comment by 1wq2** [comment]
You are my savior, thanks

**Comment by kotAPI** [comment]
damn, you're a legend, even stackoverflow didn't have the solution!

**Comment by MenilikBelay** [comment]
Or you can write format_suffix_pattern before adding (appending) router.urls to urlpatterns

**Comment by sssunda** [comment]
Really thank you!!

**Comment by nottheswimmer** [comment]
2020, happened to me too lol

**Comment by cybercandyman** [comment]
Same here, you save my time !

**Comment by stfenjobs** [comment]
same here ,  if  DEBUG = True

**Comment by abbasegbeyemi** [comment]
Just commented to remind you that you are a hero @jrvidotti!

**Comment by Chengetanaim** [comment]
format_suffix_pattern was the problem, thanks @jrvidotti

**Comment by i3Ammar** [comment]
thx
