### ISSUE TITLE
Different permissions for detail and list views in a viewset

### ISSUE THREAD

**Issue by j0hnsmith** [encode/django-rest-framework#1365]
There doesn't seem to be a way to have different permissions for list and detail views in a ViewSet. My use case is that I have a users api that exposes email addresses, I only want admins to be able to list all users, users should only be able to access their own user.

Perhaps there could be class variables such as `permission_classes_list` and `permisssion_classes_detail` or something like that.

**Comment by jmtoung** [comment]
@tomchristie 
Hi Tom,
In your answer above on Jan 20, 2014, you said:
> @j0hnsmith For your particular use case I'd recommend a filter class, that returns all users for admin access, and only returns the requestee's user for non-admin access.

By "filter class", do you mean filtering the get_queryset() as described below?
http://www.django-rest-framework.org/api-guide/filtering/

**Comment by rpkilby** [comment]
@jmtoung I assume he means a [custom filter backend](http://www.django-rest-framework.org/api-guide/filtering/#custom-generic-filtering).

**Comment by xordoquy** [comment]
> If it cannot be implemented it should be mentioned in the docs.

http://www.django-rest-framework.org/api-guide/permissions/#djangoobjectpermissions

> Note: If you need object level view permissions for GET, HEAD and OPTIONS requests, you'll want to consider also adding the DjangoObjectPermissionsFilter class to ensure that list endpoints only return results including objects for which the user has appropriate view permissions.

**Comment by trollfred** [comment]
I must be blind, thank you!

**Comment by xordoquy** [comment]
no, you are not. Would welcome some improvements such as including links to that section from the others so it's more obvious.

**Comment by djpeach** [comment]
> You already have the IsSelfOrAdmin permission class.

What? Did this used to exist? I certainly can't find it..
