### ISSUE TITLE
FileField representations should return URLs, not paths.

### ISSUE THREAD

**Issue by flisky** [encode/django-rest-framework#1368]
FileField (and the ImageField) only show its name currently, rather than the storage url.

AFAIK, name is the string stored in the db; path is the MEDIA_ROOT + name; url is the MEDIA_URL + name.

Only found the [same question](https://groups.google.com/forum/#!topic/django-rest-framework/qQQEqXX82zo) on the ML. I think it would be convenient if we made this change. 

Any thought on this?

**Comment by escaper01** [comment]
just pass **request** to your serializer and you are good to go
`serializer = ReviewSerializer(data=data, context={'request': request})`
![image](https://github.com/encode/django-rest-framework/assets/40900032/75736234-7165-44b9-bc14-85f68d7f89a9)
