### ISSUE TITLE
Turning off pagination

### ISSUE THREAD

**Issue by kaygorodov** [encode/django-rest-framework#1390]
Hello all,

I don't know it is a bug or a documentation omission.

We can notice in the documentation:
"Note that using a paginate_by value of None will turn off pagination for the view."

But if we use in settings `PAGINAGE_BY` and `PAGINGATE_BY_PARAM`, for example:

```
'PAGINATE_BY': 25,
'PAGINATE_BY_PARAM': 'limit'
```

and if we have the following view:

```
class MyList(generics.ListAPIView):
    # turn off pagination
    paginate_by = None
    queryset = MyEntity.objects.all()
    serializer_class = MySerializer
```

due to this code:
(from generics.py):

```
def get_paginate_by(self, queryset=None):
    ....
    if self.paginate_by_param:
        try:
            return strict_positive_int(
                self.request.QUERY_PARAMS[self.paginate_by_param],
                cutoff=self.max_paginate_by
            )
        except (KeyError, ValueError):
            pass
    return self.paginate_by
```

If we make request to this view with param limit (it's specified as PAGINATE_BY_PARAM), the pagination would work.

```
GET /myentity/ pagination doesn't work. (GOOD)
GET /myentity/?limit=10 pagination works (BAD. Even though we set paginate_by=None in the view pagination works)
```

In order to achieve turning off pagination for all requests, we also have to set paginate_by_param = None:

```
class MyList(generics.ListAPIView):
    # turn off pagination
    paginate_by = None
    paginate_by_param = None  # added to turn off pagination for requests that contain paginate_by_param
    queryset = MyEntity.objects.all()
    serializer_class = MySerializer
```

Or of course, we can achieve it by changing the code in generics.py

**Comment by Aldarn** [comment]
Correct me if i'm wrong but this method now seems invalid? The documentation still states setting `paginate_by = None` will disable pagination, however this didn't work for me.

For anyone coming across this issue, after looking at the DRF code the solution for the latest version is to set `paginator = None` instead.

**Comment by xordoquy** [comment]
@Aldarn can you open an issue about where the documentation still refers to paginate_by ?
This has change in 3.2.x and shouldn't be used any longer.

**Comment by pcompassion** [comment]
http://djangorestframework.readthedocs.org/en/latest/api-guide/pagination/

`Note that using a paginate_by value of None will turn off pagination for the view.`
