### ISSUE TITLE
QUERY_PARAMS empty when running tests, after Upgrading to 2.3.13 

### ISSUE THREAD

**Issue by hagsteel** [encode/django-rest-framework#1461]
After upgrading from 2.3.12 to 2.3.13 the QUERY_PARAMS are always empty.

```
class MyViewSet(viewsets.ReadOnlyModelViewSet):
    ...

    def get_queryset(self):
        a_param = self.request.QUERY_PARAMS.get('foo')
        if a_param == 'bar':
            ...
```

Has the functionality changed around this? I saw nothing in the release notes.

**NOTE** This only affects testing

**Comment by egomezsumma** [comment]
> As this issue only affects the tests I've changed the title of this issue. Feel free to close it as it's probably not too important as test can be rewritten to use the data param.
> 
> use:
> 
> ```
> APIClient().get('url', data={'foo': 'bar'})
> ```
> 
> instead of:
> 
> ```
> APIClient().get('url?foo=bar')
> ```

This is not a solution, im using a PUT request, and those cant have url param (indeed the param is json with list in it)
