### ISSUE TITLE
Model ManyToMany field is not updated while using PUT/PATCH methods

### ISSUE THREAD

**Issue by pySilver** [encode/django-rest-framework#1556]
I believe there is a bug in `rest_framework.serializers.ModelSerializer#save_object` method. 

Exactly here:

``` python
if getattr(obj, '_m2m_data', None):
    for accessor_name, object_list in obj._m2m_data.items():
        setattr(obj, accessor_name, object_list)
    del(obj._m2m_data)
```

This code behaves like it should while creating object with m2m field – setattr adds value to a proper property, so while serializing data client gets correct, *_actual_ state of saved object.

However if one tries to update existing object with non-empty state of m2m field setattr fails to replace it's value (however data is being saved thankfully to `django.db.models.fields.related.ReverseManyRelatedObjectsDescriptor#__set__` thats can be checked by refreshing object from db), as a result client gets incorrect, **old** state of saved object.

**Comment by chrismcband** [comment]
It looks like this issue is still present in 3.0.3, for instance, in a user serializer update method, attempting to update the groups, does actually save to the database, but the response returned still shows the old groups:
```python
def update(self, instance, validated_attrs):
    new_groups = validated_attrs.get('groups')
    for group in new_groups:
        instance.groups.add(group)
    instance.save()
    # below is needed to reflect the group changes in the response
    # instance = User.objects.get(id=instance.id)

    return instance
```

**Comment by tomchristie** [comment]
@chrismcband Want to narrow this down to the simplest possible reproducing case you can and open it as an issue?

**Comment by chrismcband** [comment]
Will do, I created a simple example with users and groups and couldn't reproduce it, so had a look at my project code again and saw the only different was my viewset was using prefetch_related('groups') in the queryset.

**Comment by chrismcband** [comment]
@tomchristie issue is here #2442

**Comment by harshilpatel** [comment]
This hasn't been resolved yet ?
I'm still not able to save a  manytomany in v3.4.7

**Comment by xordoquy** [comment]
@harshilpatel please refrain from using passive agressive tone.
If you are not able to save a many to many, it's an issue on your side.
This issue is about values being returned and requires the developers to explicitly return the new values

**Comment by tomchristie** [comment]
@harshilpatel - Echoing @xordoquy here. We can act on specific actionable examples, not general "something's not working". And yes, you can perfectly well update many to many relationships with REST framework.

**Comment by pySilver** [comment]
@tomchristie i just wanted to ask, why wouldnt we use my solution until we find something better? At least it would solve existing issue...

**Comment by tomchristie** [comment]
@pySilver If there's something that needs resolving then it probably needs a new issue and a clear description.

This thread starts prior to the 3.0 serializer redesign, so it's not clear *exactly* what aspects are still at issue. We *don't* have a "save_object" method any more, and the m2m handling is not the same as the code listed in the opening comment.

Very happy to help resolve any outstanding issues, but let's be clearer about what they are.

**Comment by pySilver** [comment]
Okay, I will check the current state of issue an make a pr (from my experience this issue still exists)

**Comment by pySilver** [comment]
From what I can tell this ticket should be closed since its not an issue any more.
```./runtests.py TestIntegration.test_pk_update``` covers this scenario.

**Comment by autobiographysimultaneou** [comment]
@xordoquy https://altitude63.github.io/pepswKguA0TZeUdUTy3cqqYd/
