### ISSUE TITLE
Specifying different serializers for input and output

### ISSUE THREAD

**Issue by foresmac** [encode/django-rest-framework#1563]
I find that, particularly when it comes to POST methods, that I often need a different serializer for input than for output. E.g., for a a particular model I may need only two or three input values, but the server will calculate/retrieve/whatever some additional values for fields on the model, and all those values need to get back to the client.

So far, my method has been to override `get_serializer_class()` to specify a separate input serializer for the request, and then override `create()` to use a different serializer for my output. That pattern works, but it took me some time to figure it out because the docs don't  really suggest that option; the assumption that the generic APIViews are built around is that you specify one serializer and that is used for both input and output. I agree this generally works in the common case, but using my method breaks a little bit of the CBV magic. In particular, it can be difficult to troubleshoot if you make a mistake specifying a custom output serializer.

I propose two solutions:
1. Build a consistent way to optionally specify different input and output serializers, or
2. Add some additional documentation explaining the presumption that one serializer is intended for input _and_ output, and best practices for overriding that in the case that the default behavior doesn't suit your use case.

**Comment by jjlorenzo** [comment]
This is what I'm using, got some ideas from here and implement a simple solution that works for my case for now, I'll love if this could be formally implemented.

I'm using a nested router, under a `practice` resource, so I had `practice_pk` on `kwargs`

Sorry, for name clashing, since naming objects is difficult to me, I tend to put the same name under another module, I'll later refactor the example with all parts.

``` python
class ModelViewSet(viewsets.ModelViewSet):
  @property
  def _lookup_attrs(self):
    return {key.replace('pk', 'id'): value for key, value in six.iteritems(self.kwargs)}

  def get_queryset(self):
    return super(ModelViewSet, self).get_queryset().filter(**self._lookup_attrs)

  def perform_create(self, serializer):
    attrs = self._lookup_attrs

    # set `updated_by` to the current user if it was declared as `read_only`
    if 'updated_by' in serializer.fields and serializer.fields['updated_by'].read_only:
      attrs.update({'updated_by_id': self.request.user.pk})

    serializer.save(**attrs)


class ConsentFormTemplate(ModelViewSet):

  queryset = models.ConsentFormTemplate.objects.all()

  serializer_class = serializers.ConsentFormTemplate


class ConsentFormTemplate(serializers.ModelSerializer):

  class Meta:

    model = models.ConsentFormTemplate

    fields = [
      'id',
      'name',
      'practice',
      ....
      'updated_by',
    ]

    read_only_fields = [
      'id',
      'practice',
      ....
      'updated_by',
    ]

```

``` python
router_v2 = SimpleRouter()
# top level resources
router_v2.register(Practice.prefix, Practice.viewset)

router_v2_practice = NestedSimpleRouter(parent_router=router_v2, parent_prefix=Practice.prefix, lookup=Practice.lookup)
# every resource registered under `router_v2_practice` will be prefixed with practices/<practice_pk>/
router_v2_practice.register(ConsentFormTemplate.prefix, ConsentFormTemplate.viewset)

api_urls_v2 = [
  # url('', include(router_v2.urls)),
  url('', include(router_v2_practice.urls)),
]
```

``` python
Resource = namedtuple(
  typename='Resource',
  field_names='prefix viewset base_name lookup'
)
# http://stackoverflow.com/questions/11351032/named-tuple-and-optional-keyword-arguments/18348004#18348004
Resource.__new__.__defaults__ = (None, None)

ConsentFormTemplate = Resource(prefix=r'consent-form-templates', viewset=views.ConsentFormTemplate)
```

**Comment by cyclecycle** [comment]
The answer I came here to find turned out to be:

If `read_only` doesn't provide the control you need and you want to customise the input or output validation logic, you should override `to_internal_value()` or `to_representation()`, respectively. 

In this case, you'd use `to_internal_value()` to customise the generation of the `validated_data` from whatever the client provides. If the subsequent call to `YourModel.objects.create(**validated_data)` doesn't work, you can then override `create()`.

**Comment by frenetic** [comment]
Im trying to tackle this issue right now.
Im going to give a try to this package - https://github.com/vintasoftware/drf-rw-serializers.

**Comment by naderalexan** [comment]
Your approach seems logical, why not just make a mixin out of it and re-use it. Something along the lines of:

```
from rest_framework import status
from rest_framework.response import Response


class DifferentOutInViewsetSerializers:
    """
    Mixin for allowing the use of different serializers for responses and
    requests for update/create
    """
    request_serializer_update = None
    response_serializer_update = None

    request_serializer_create = None
    response_serializer_create = None

    def get_serializer_class(self):
        if self.action == 'update':
            return self.request_serializer_update
        elif self.action == 'create':
            return self.request_serializer_create
        return super().get_serializer_class()

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        self.perform_create(serializer)

        response_serializer = self.response_serializer_create(
            instance=serializer.instance)

        headers = self.get_success_headers(response_serializer.data)
        return Response(
            response_serializer.data,
            status=status.HTTP_201_CREATED, headers=headers)

    def update(self, request, *args, **kwargs):
        partial = kwargs.pop('partial', False)
        instance = self.get_object()
        serializer = self.get_serializer(instance, data=request.data, partial=partial)
        serializer.is_valid(raise_exception=True)
        self.perform_update(serializer)

        if getattr(instance, '_prefetched_objects_cache', None):
            # If 'prefetch_related' has been applied to a queryset, we need to
            # forcibly invalidate the prefetch cache on the instance.
            instance._prefetched_objects_cache = {}

        response_serializer = self.response_serializer_update(
            instance=serializer.instance)
        return Response(response_serializer.data)
```

**Comment by Moulde** [comment]
I find myself in need of this as well, but in my case it's not for POST requests, but a GET request that returns a bunch of non-modal objects, and I need a bunch of filter parameters that are not directly related to the fields on the objects.

I'm not sure if i'm doing something weird or missing something entirely, as I can't be the first to have an endpoint that is not model CRUD and needs to generate the documentation from the endpoint?

I can just retrieve the arguments from the request object, but I'm trying to have my API be self-documenting by using the API documentation generator in drf, or the drf-yasg package, hence my reason for wanting to use the serializers for specifying the parameters.
Is there another way to describe the endpoint parameters besides serializers?

Sorry if this is not within the scope of this issue.

**Comment by frenetic** [comment]
Previously I said I was going to use https://github.com/vintasoftware/drf-rw-serializers.
After 6 months using it, it has been really helpful. For most problems stated here, this library will help.

@Moulde Take a look at the lib Im using. If it does not suit you, try implementing the method `get_serializer_class` - http://www.django-rest-framework.org/api-guide/generic-views/#get_serializer_classself.

**Comment by foresmac** [comment]
@frenetic This seems to solve a problem that `get_serializer_class’ can already solve most of the time. What @moulde (who presents a slightly different use-case than I previously mentioned) is that there are times when you want/need to use different serializers for the Request vs the Response. And being able to take advantage of automatic documentation is an important consideration for this in my mind, outside of the desire to avoid boilerplate code in this case.

**Comment by Moulde** [comment]
Yes, basically I think DRF has less than ideal support for non-modal views, where you want to use a serializer to describe the interface, so that the automatic documentation can be generated.
An example could be a endpoint for filtering/searching (external) non-modal data.

**Comment by joshowen** [comment]
> there are times when you want/need to use different serializers for the Request vs the Response

This was a big reason to use https://github.com/limdauto/drf_openapi (when it was still maintained).  It would be awesome if it was possible to differentiate request and response schemas in django-rest-framework.  There are a lot of times we're extending another api which has these requirements.

**Comment by matthewarmand** [comment]
I do think that having `APIView` support for different serializers for input and output would be a killer feature. It might even be easy to implement; for example a parameter could be supplied to `get_serializer` so that `get_serializer_class` knows the context (input vs output). This seems like it'd be fairly unobtrusive, and would allow for apps needing this functionality to follow the usual advice of "override `get_serializer_class`".

In the absence of that, I wanted to highlight a couple current `django-rest-framework` features I didn't see in this thread that might help someone else coming through here later on. If it's workable for you to include all your desired input and output fields into one `Model`, you can use a [`ModelSerializer`](https://www.django-rest-framework.org/api-guide/serializers/#modelserializer) to specify [read-only](https://www.django-rest-framework.org/api-guide/serializers/#specifying-read-only-fields) and [write-only](https://www.django-rest-framework.org/api-guide/serializers/#additional-keyword-arguments) fields such that you effectively get different input and output schemas.
(Versions: djangorestframework 3.10.3, Django 2.2.5, Python 3.7.4)

So a `Model` like this:
```python
from django.db import models

class ThingModel(models.Model):
    input_field = models.CharField()
    output_date = models.DateTimeField()
    output_id = models.IntegerField()
    output_string = models.CharField()
```

And a `Serializer` like this:
```python
from rest_framework import serializers
from .models import ThingModel

class ThingSerializer(serializers.ModelSerializer):
    class Meta:
        model = ThingModel
        fields = [
            "input_field",
            "output_date",
            "output_id",
            "output_string",
        ]
        read_only_fields = [
            "output_date",
            "output_id",
            "output_string",
        ]
        extra_kwargs = {"input_field": {"write_only": True}}
```

Will produce the following OpenAPI docs when `generateschema` is used:
```yaml
...
  /urlpath/:
    post:
      operationId: CreateThing
        parameters: []
        requestBody:
          content:
            application/json:
              schema:
                properties:
                  input_field:
                    type: string
                    write_only: true
                required:
                - input_field
        responses:
          '200':
            content:
              application/json:
                schema:
                  properties:
                    output_date:
                      type: string
                      format: date-time
                      readOnly: true
                    output_id:
                      type: integer
                      readOnly: true
                    output_string:
                      type: string
                      readOnly: true
                  required: []
          description: ''
```

This helps when you want one endpoint, within the context of a single method (eg `POST`), to have different input and output schemas, if the whole object can be expressed as a `Model`. It'd be great to have similar functionality without having to use a `ModelSerializer`.

**Comment by fronbasal** [comment]
What is the "state of the art" solution for this problem? Was there any progression since 2014?

**Comment by matthewarmand** [comment]
@fronbasal We've been accomplishing this with `Serializer`s by using `write_only=True` and `read_only=True` on each serializer `Field` as appropriate. I'm not sure what the generated Swagger docs look like for that, but it does accomplish different schemas for input and output to a sufficient extent for our purposes.

I'm not sure whether the maintainers have a different/better solution in mind

**Comment by fronbasal** [comment]
@matthewwithanm All right, thank you very much!

**Comment by michaelhenry** [comment]
@fronbasal I have come up with a simple solution, just pass the model to another serializer

here is the example

```python

def create(self, request):
    serializer = InputSerializer(data=request.data)
    output_serializer = None
    if not serializer.is_valid():
        return Response(
             {'errors': serializer.errors},
            status=status.HTTP_400_BAD_REQUEST)
    try:
        output_serializer = OutputSerializer(serializer.save())
    except Exception as e:
        raise ValidationError({"detail": e})
    return Response(output_serializer.data, status=status.HTTP_201_CREATED)
```

Cheers

**Comment by fronbasal** [comment]
@michaelhenry thats a really clever solution! Love it.

**Comment by fechnert** [comment]
@cyclecycle

> If `read_only` doesn't provide the control you need, and you want to customize the input or output validation logic, you should override `to_internal_value()` or `to_representation()`, respectively.

Thank you, just saved my day. I have the use case where i want to display more data of the owner of an object while retrieving it, but only give the owner's id while creating new entries.

This was rather tedious to accomplish, because using nested serializers (even whith providing all of the required data) raises the following AssertionError:

```
AssertionError: The `.create()` method does not support writable nested fields by default.
```

So instead i had to overwrite `to_internal_value()` to act like the given data for the **request** contains the user instance, but for the **response** contains the nested owner information.

<details>
  <summary><strong>See code for implementation details</strong></summary>

```python
class OwnerSerializer(serializers.Serializer):
    """Serializer for the related/nested owner information"""

    id = serializers.UUIDField()
    username = serializers.CharField()

    def to_internal_value(self, data):
        if not isinstance(data, str):
            raise ValidationError("This value needs to be the owners UUID")

        return User.objects.get(id=data)


class SomeModelSerializer(serializers.ModelSerializer):
    """The actual model with a relation to a user as owner"""

    owner = OwnerSerializer()

    class Meta:
        model = SomeModel
        fields = [
            'title',
            'owner',
            ...
        ]
```
  
</details>

The request to create a new object can look like this:

```json
{
    "title": "Some title",
    "owner": "9c3faee7-2ce1-4b86-a58c-45f70a042125"
}
```

While the response contains all desired nested information about the related owner after creation

```json
{
    "title": "Some title",
    "owner": {
        "id": "9c3faee7-2ce1-4b86-a58c-45f70a042125",
        "username": "some_user0815"
    }
}
```

**Comment by ulgens** [comment]
I'd recommend an even cleaner way:

```
    def create(self, request, *args, **kwargs):
        # self.get_serializer_class() returns the correct serializer for writing
        input_serializer = self.get_serializer(data=request.data)  
        input_serializer.is_valid(raise_exception=True)
        self.perform_create(input_serializer)

        output_serializer = ReadSerializer(input_serializer.instance)
        headers = self.get_success_headers(output_serializer.data)
        return Response(output_serializer.data, status=status.HTTP_201_CREATED, headers=headers)
```

**Comment by sshishov** [comment]
Can we include the work done in `drf-rw-serializers` into the core of viewsets at least? It would be great to distinguish between read and write and at the same time if this distinguish is not needed, we can fallback to `get_serializer_class` which will fallback to `serializer_class` attribute by default.

People are adding a lot of workarounds here just to solve the issue with data and to generate proper OpenAPI schemes.
Also it would be great for DRF core to include "filter serializers" for proper scheme generation and "error serializers" as currently all of this should be done by hands, for instance in `drf-spectacular`

**Comment by PawelRoman** [comment]
> I'd recommend an even cleaner way (for view layer):
> 
> ```
>     def create(self, request, *args, **kwargs):
>         # self.get_serializer_class() returns the correct serializer for writing
>         input_serializer = self.get_serializer(data=request.data)  
>         input_serializer.is_valid(raise_exception=True)
>         self.perform_create(input_serializer)
> 
>         output_serializer = ReadSerializer(input_serializer.instance)
>         headers = self.get_success_headers(output_serializer.data)
>         return Response(output_serializer.data, status=status.HTTP_201_CREATED, headers=headers)
> ```

I believe the above example is the best approach. For reusability, it's even better to wrap it up as CustomCreateModelMixin just to avoid repeating exactly the same code in all views where we need it. The ReadSerializer class can be obtained by temporarily changing self.action to 'retrieve' and calling get_serializer_class(). It's a hack but will work and will always make POST method return object formatted exactly as in the GET method.  

There are other things to consider as well, such as we may need to manually call get_queryset() to reload the object from DB before passing it to the output serializer, because our output serializer may expects some annotated fields or other custom stuff defined in view's get_queryset()

**Comment by tam-yeshiva** [comment]
> > I'd recommend an even cleaner way (for view layer):
> > ```
> >     def create(self, request, *args, **kwargs):
> >         # self.get_serializer_class() returns the correct serializer for writing
> >         input_serializer = self.get_serializer(data=request.data)  
> >         input_serializer.is_valid(raise_exception=True)
> >         self.perform_create(input_serializer)
> > 
> >         output_serializer = ReadSerializer(input_serializer.instance)
> >         headers = self.get_success_headers(output_serializer.data)
> >         return Response(output_serializer.data, status=status.HTTP_201_CREATED, headers=headers)
> > ```
> 
> I believe the above example is the best approach. For reusability, it's even better to wrap it up as CustomCreateModelMixin just to avoid repeating exactly the same code in all views where we need it. The ReadSerializer class can be obtained by temporarily changing self.action to 'retrieve' and calling get_serializer_class(). It's a hack but will work and will always make POST method return object formatted exactly as in the GET method.
> 
> There are other things to consider as well, such as we may need to manually call get_queryset() to reload the object from DB before passing it to the output serializer, because our output serializer may expects some annotated fields or other custom stuff defined in view's get_queryset()





https://stackdev.space/questions/update-the-http-status-code-of-a-django-class-based-view-response-when-the-form-is-invalid

**Comment by kevinrenskers** [comment]
I ran into the wish of being able to specify different serializers for the input and output of POST and PUT requests, so drf-rw-serializers seemed kinda perfect. But I also need to be able to specify different serializers for different actions, for example list versus retrieve: the list has a simpler representation of the model, whereas retrieve has the full version. 

Here's my solution (also available in [blogform](https://www.loopwerk.io/articles/2025/drf-action-serializers/)):

```python
# mypy: ignore-errors

from rest_framework import mixins, permissions, status, viewsets
from rest_framework.generics import GenericAPIView
from rest_framework.response import Response

# Generic views


class ActionSerializerGenericAPIView(GenericAPIView):
    def get_action_serializer(self, method):
        assert hasattr(self, "action"), "View must have an `action` attribute"

        result = (
            getattr(self, f"{self.action}_{method}_serializer_class", None)
            or getattr(self, f"{self.action}_read_serializer_class", None)
            or getattr(self, f"{self.action}_serializer_class", None)
            or getattr(self, f"{method}_serializer_class", None)
            or getattr(self, "read_serializer_class", None)
            or getattr(self, "serializer_class", None)
        )

        assert result is not None, (
            f"{self.__class__.__name__} should either include one of `{self.action}_{method}_serializer_class`, `{self.action}_read_serializer_class`, `{self.action}_serializer_class`, `{method}_serializer_class`, `read_serializer_class`, and `serializer_class` attribute, or override the `get_serializer_class()` method"
        )

        return result

    def get_serializer_class(self):
        method = "read" if self.request.method in permissions.SAFE_METHODS else "write"
        return self.get_action_serializer(method)


# Mixins


class ActionSerializerCreateModelMixin(mixins.CreateModelMixin):
    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        self.perform_create(serializer)

        response_serializer = self.get_action_serializer("read")(
            instance=serializer.instance,
            context=self.get_serializer_context(),
        )

        headers = self.get_success_headers(response_serializer.data)
        return Response(response_serializer.data, status=status.HTTP_201_CREATED, headers=headers)


class ActionSerializerUpdateModelMixin(mixins.UpdateModelMixin):
    def update(self, request, *args, **kwargs):
        partial = kwargs.pop("partial", False)
        instance = self.get_object()
        serializer = self.get_serializer(instance, data=request.data, partial=partial)
        serializer.is_valid(raise_exception=True)
        self.perform_update(serializer)

        if getattr(instance, "_prefetched_objects_cache", None):
            # If 'prefetch_related' has been applied to a queryset, we need to
            # forcibly invalidate the prefetch cache on the instance.
            instance._prefetched_objects_cache = {}

        response_serializer = self.get_action_serializer("read")(
            instance=serializer.instance,
            context=self.get_serializer_context(),
        )
        return Response(response_serializer.data)


# ViewSets


class ActionSerializerGenericViewSet(viewsets.ViewSetMixin, ActionSerializerGenericAPIView):
    pass


class ActionSerializerReadOnlyModelViewSet(
    mixins.RetrieveModelMixin, mixins.ListModelMixin, ActionSerializerGenericViewSet
):
    pass


class ActionSerializerModelViewSet(
    ActionSerializerCreateModelMixin,
    mixins.RetrieveModelMixin,
    ActionSerializerUpdateModelMixin,
    mixins.DestroyModelMixin,
    mixins.ListModelMixin,
    ActionSerializerGenericViewSet,
):
    pass
```

I'd also like to point out https://github.com/AlexisMunera98/rest-framework-actions, which does the same as my solution, and is 5 years old. The downside with that project though is there's no serializer fallback logic, so you always end up having to specify 6 different serializers in every ModelViewSet, even when the write serializer for the create and update actions are the same, or if you don't care about different input and output serializers.

Bonus: if you’re using [drf-spectacular](https://drf-spectacular.readthedocs.io/) to document your API, then the following code will make sure that the correct serializers are used for the input and output.

```python
from drf_spectacular.openapi import AutoSchema


class ActionSerializerAutoSchema(AutoSchema):
    def get_request_serializer(self):
        if self.method.lower() in {"post", "put", "patch"}:
            if hasattr(self.view, "get_action_serializer"):
                return self.view.get_action_serializer("write")
        return super().get_request_serializer()

    def get_response_serializers(self):
        if not hasattr(self.view, "get_action_serializer"):
            return super().get_response_serializers()

        method = self.method.lower()

        if method == "post":
            return {
                "201": self.view.get_action_serializer("read"),
            }
        elif method in {"put", "patch"}:
            return {
                "200": self.view.get_action_serializer("read"),
            }

        return super().get_response_serializers()
```

Simply add the following to settings.py and it’s automatically used:

```python
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "path.to.ActionSerializerAutoSchema",
}
```
