### ISSUE TITLE
Context of parent overwrites context of children

### ISSUE THREAD

**Issue by ianfp** [encode/django-rest-framework#1577]
I have these serializers:

``` python
class ParentSerializer(serializers.Serializer):
    feature = ChildSerializer(many=True, context=dict(type='feature'))
    shadow = ChildSerializer(many=True, context=dict(type='shadow'))
    edge = ChildSerializer(many=True, context=dict(type='edge'))
    footprint = ChildSerializer(many=True, context=dict(type='footprint'))

class ChildSerializer(serializers.ModelSerializer):
    def from_native(self, data, files):
        assert 'type' in self.context
        # ...
```

The assertion in `ChildSerializer` fails because the `initialize()` method of `Field` overwrites the context of the child with that of the parent. Couldn't they be merged instead?

**Comment by pySilver** [comment]
@tomchristie what was the reason to change this behavior in 3.x? Context used to be propagated to child serializers in 2.x and seems that it's no longer true for 3.x :/

**Comment by tomchristie** [comment]
Use `self.root.context` if needed.
