### ISSUE TITLE
Can't put null date

### ISSUE THREAD

**Issue by diadzine** [encode/django-rest-framework#1625]
Hi there!

I got some data containing a date equals to null from GET resquest response:

```
'{"id": 1, "status": 1, "date_start": null, "date_end": null, "price": "150"}'
```

After a change in those data (i.e. price), I send it via PUT request and it failed with an error 400 BAD REQUEST. I got this in response:

```
{'date_end': [u'Date has wrong format. Use one of these formats instead: YYYY[-MM[-DD]]'],
  'date_start': [u'Date has wrong format. Use one of these formats instead: YYYY[-MM[-DD]]']}
```

In my models.py:

```
date_start = models.DateField(blank=True, null=True)
date_end = models.DateField(blank=True, null=True)
```

In my serializers.py:

```
date_start = serializers.DateField(required=False)
date_end = serializers.DateField(required=False)
```

**Comment by awais786** [comment]
@tomchristie This issue appears when you pass invalid date like 31st Feb.

**Comment by rpkilby** [comment]
@awais786, a `null` date is not the same as an invalid date.
