### ISSUE TITLE
APIException serialized by the pickle module

### ISSUE THREAD

**Issue by protyagov** [encode/django-rest-framework#1626]
It would be nice to make APIException serializeable. This would allow such exception to be passed between servers. For example, you might have DRF running as one service and have different service for say celery workers dedicated to long running tasks. If exception is raised on the worker side I would like pass it back to DRF for further actions, such as presenting it to user.
Currently it is not possible. 

According to celery web site

_A rarely known Python fact is that exceptions must conform to some simple rules to support being serialized by the pickle module._

_Tasks that raise exceptions that are not pickleable will not work properly when Pickle is used as the serializer._

_To make sure that your exceptions are pickleable the exception MUST provide the original arguments it was instantiated with in its .args attribute. The simplest way to ensure this is to have the exception call Exception.**init**._

Currently **init** for API Exception looks like 

```
#!python

    def __init__(self, detail=None):
        self.detail = detail or self.default_detail
```

Changing it to the following fixes the issue according to my tests:

```
#!python

    def __init__(self, detail=None):
        self.detail = detail or self.default_detail
        Exception.__init__(self, self.detail)
```

**Comment by johnhuffsmith** [comment]
We ran into this issue as well.  In our case, raising a ValidationError (or a subclass of it) within a celery job kills the entire celery process.  This is such a simple fix to prevent a ton of potential pain.  Would be great to have DRF Exceptions support standard pickling functionality.

**Comment by tomchristie** [comment]
Happy to see a PR that calls `super()` in `APIException.__init__`, sure.

**Comment by thomasmatecki** [comment]
Hey @johnhuffsmith 👋 .

**Comment by hosseinmp76** [comment]
> Happy to see a PR that calls `super()` in `APIException.__init__`, sure.
@tomchristie Is it still relevant to create this PR? In the current main, this is still missing. I would like to create the PR in case this is still relevant.
