### ISSUE TITLE
'RelationsList' object has no attribute 'save'

### ISSUE THREAD

**Issue by kid143** [encode/django-rest-framework#1650]
When saving the serialized object using the model serializer's "save" method, it gives AttributeError saying: "'RelationsList' object has no attribute 'save'". Does the framework support saving by serializers nested more than 2 depth?

My serializer definition is as follows:

``` python
class IrritantRecordSerializer(serializers.ModelSerializer):
    irritant = serializers.PrimaryKeyRelatedField()

    class Meta:
        model = IrritantRecord
        fields = ("irritant", "result", "reflect_time")

class PlayRecordSerializer(serializers.ModelSerializer):
    irritant_info = IrritantRecordSerializer(many=True)

    class Meta:
        model = PlayRecord
        fields = ("irritant_info", "round", "accuracy", "reflect_time")


class GameRecordSerializer(serializers.ModelSerializer):

    user = UserPrimaryKeyRelatedField()
    game = serializers.PrimaryKeyRelatedField()
    play_info = PlayRecordSerializer(many=True)

    class Meta:
        model = GameRecord
        fields = ("user", "game", "level", "play_info")
```

The json parse seems okay and the validation is okay, but when saving GameRecord model, it just keep saying that error, and the traceback shows the error occurs when saving IrritantRecord list. It seems the irritant_info field is not treated as a list. Is this a bug or is there any solutions for my work?

**Comment by sonu628** [comment]
@kannor worked for me too +1
