### ISSUE TITLE
Submitting a read_only field in PUT/PATCH should return 400

### ISSUE THREAD

**Issue by foresmac** [encode/django-rest-framework#1655]
I've got a field in my serializer marked as `read_only`. When I try to submit a change for that field using a PATCH request, I get the correct behavior—the field on the model is not updated. However, I get a `200` response, and not an expected `400 BAD REQUEST`. If the field is read only, trying to set it via PUT/PATCH should result in a `400`.

**Comment by OJFord** [comment]
Just ran into this as well, I suppose the cleanest alternative is a custom 'no change' validator. Would be nice if something like `{'read_only': True, 'read_only_errors': True}` were possible.

**Comment by bary12** [comment]
It's been a few years since this issue was posted. Is there a workaround nowdays?

**Comment by xordoquy** [comment]
The only workaround I can foresee is to override you view's `update`, check if if `partial is True` and `serializer.validated_data is {}` in which case you could return a 400.

**Comment by RomanKhudobei** [comment]
@dmugtasimov thank you.
I came up with something like this:
```python
class StrictReadOnlyFieldsMixin:
    """Raises error if read only fields passed to input data"""
    default_error_messages = {
        'read_only': _('This field is read only')
    }

    def validate(self, attrs):
        attrs = super().validate(attrs)

        if not hasattr(self, 'initial_data'):
            return attrs

        # collect declared read only fields and read only fields from Meta
        read_only_fields = {
            field_name for field_name, field in self.fields.items() if field.read_only
        } | set(getattr(self.Meta, 'read_only_fields', set()))

        received_read_only_fields = set(self.initial_data) & read_only_fields

        if received_read_only_fields:
            errors = {}
            for field_name in received_read_only_fields:
                errors[field_name] = serializers.ErrorDetail(self.error_messages['read_only'], code='read_only')

            raise serializers.ValidationError(errors)

        return attrs
```

**Comment by sur0g** [comment]
I came here because my test regarding response_code failed with `code == 200`— such weird behavior.
Ideally, I would like to declaratory (not imperatively) define read-only fields validation, which then should raise 400 BadRequest.
200 OK is counterintuitive.

Consider this example:
`
class ProductSerializer(serializers.ModelSerializer):
    class Meta:
        model = Product

        fields = (
            "name",
            "share_slug",
        )
        read_only_fields = (
            "share_slug",
        )
`
Then I use PATCH to update _only_ the `share_slug`.
`
PATCH /products/1/
{
  "share_slug": "some-slug"
}
`
Instead of getting 400 BadRequest, I get 200 OK. Then I assume that slug _was updated_, but in fact, it remains the same.

**Comment by vitofly** [comment]
The workaround I am using is to check the read-only field in the "to_internal_value" method
`
def to_internal_value(self, data):
    if '<read_only_field_name>' in data:
        raise serialisers.ValidationError({'<read_only_field_name>': 'This field is read-only.'})
    return super().to_internal_value(data)
`

**Comment by ChrisGibb** [comment]
@RomanKhudobei  thanks for your snippet

I added a check for hidden fields 

```
...
... if field.read_only or isinstance(field, HiddenField)
...
```
