### ISSUE TITLE
Allow more than one slug field to be deserialized jointly

### ISSUE THREAD

**Issue by cancan101** [encode/django-rest-framework#1666]
For example if I have countries and states and I want to send:
country=USA and state=HI 
and have them deserialized using something like:

```
state = State.objects.get(country='USA', state='HI')
```

Right now the solution is to introduce a new slug field to the model, call it `state_country_slug` and then use:

```
state = serializers.SlugRelatedField(slug_field='state_country_slug')
```

This requires adding a new field to the model, seeming unnecessarily.

**Comment by jha929** [comment]
Do we have this multi-slug-field feature in the latest DRF now?
