### ISSUE TITLE
Nested Writable Object with this Name already exists

### ISSUE THREAD

**Issue by 9gix** [encode/django-rest-framework#1682]
I'm trying to create a nested writable on a single object. I got this working on a many to many from this https://github.com/tomchristie/django-rest-framework/pull/1457. 

But because in m2m there is no checking on whether the related objects is already exists by the previous object, which can cause a duplicate object created on its related field, hence I have to do it one by one for each objects.

So I tried to create a single object, hoping that it would update its relationship. But got a validation errors instead. Here's an example

```
class Fruit(models.Model):
    name = models.CharField(max_length=10, unique=True)

class Stall(models.Model):
    name = moels.CharField(max_length=10)

class FruitSerializer(serializers.ModelSerializer):
    class Meta:
        model = Fruit

class StallSerializer(serializers.ModelSerializer):
    fruit = FruitSerializer()
    class Meta:
        model = Stall

# Let's update our shop with an existing fruits
serializer = StallSerializer(stall, data={'name': 'Old Shop', 'fruit':{'id': 1, 'name': 'Banana'}})
serializer.is_valid() # True


# Let's create a new shop, with existing Fruits
serializer = StallSerializer(data={'name': 'My New Shop', 'fruit':{'id': 1, 'name': 'Banana'}})
serializer.is_valid() # False
serializer.errors # {'fruit': [{'name': 'Fruit with this Name already exists'}]}
```

**Comment by nithinmurali** [comment]
I am facing the same issue on DRF v3.0.

**Comment by nithinmurali** [comment]
According to this [post](https://medium.com/django-rest-framework/dealing-with-unique-constraints-in-nested-serializers-dade33b831d9),  this is because of the unique validator of the anme field  created by the ModelSerializer. So the solution is to remove the validator by  

```
class FruitSerializer(serializers.ModelSerializer):
    class Meta:
        model = Fruit
        fields = '__all__'
        extra_kwargs = {
            'name': {'validators': []},
        }
```

**Comment by piedrucci** [comment]
Thanks so much @nithinmurali , this one works for me!
Greetings

**Comment by BuMo41** [comment]
thank you from the bottom of my heart, this was the fix I was looking for

**Comment by urekmazinx** [comment]
thank u so much u saved me from a lot of problems but any explain why it is working

**Comment by baikov** [comment]
@nithinmurali  omg... U r awesome! Thx a lot!

**Comment by subham73** [comment]
@nithinmurali thankssssssss a lotttttt,
