### ISSUE TITLE
Adding write_only=True to a field will break html field prepopulation for update.

### ISSUE THREAD

**Issue by freak3dot** [encode/django-rest-framework#1699]
I have some fields that should only show on a create or update html form. The best way I found to exclude these fields from a list/retrieve is to specify the field as write_only=True. This works well for create/list/retrieve but breaks the html form in the browseable api for update. The html field is not prepopulated with the current value.

I believe the offending code to be here:
https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/fields.py#L336

``` python
    def field_to_native(self, obj, field_name):
        if self.write_only:
            return None
        return super(WritableField, self).field_to_native(obj, field_name)
```

**Comment by tuky** [comment]
may I bring this up again as still being an issue? https://www.django-rest-framework.org/api-guide/fields/#write_only states:

> Set this to True to ensure that the field may be used when updating or creating an instance, but is not included when serializing the representation.

So imo the docs are not really clear, whether this is intentional. The current behavior might be desirable for private fields like passwords. But I'd argue, there are also real use cases for write only fields being prefilled in update forms. Here is an example, that shows the effects in the `BrowsableAPIRenderer`. As you can see in the rendered HTML, the prefilled `value` of the write only `first_name` is empty:

```python
class UserSerializer(serializers.ModelSerializer):
    first_name = CharField(write_only=True)
    last_name = CharField(write_only=False)>

    class Meta:
        model = User
        fields = ['first_name', 'last_name']

>>> user = User.objects.first()
>>> user.last_name
'l'
>>> user.first_name
'f'

>>> s = UserSerializer(user)
>>> s.to_representation(user)
OrderedDict([('last_name', 'l')])

>>> r = renderers.BrowsableAPIRenderer()
>>> r.accepted_media_type = ''
>>> print(r.render_form_for_serializer(s))



  
    <div class="form-group ">
  
    <label class="col-sm-2 control-label ">
      First name
    </label>
  

  <div class="col-sm-10">
    <input name="first_name" class="form-control" type="text"  value="" >

    

    
  </div>
</div>

  

  
    <div class="form-group ">
  
    <label class="col-sm-2 control-label ">
      Last name
    </label>
  

  <div class="col-sm-10">
    <input name="last_name" class="form-control" type="text"  value="l" >

    

    
  </div>
</div>

  

```

**Comment by tuky** [comment]
@tomchristie would it be possible to reopen this based on my comment above? Cheers!

**Comment by xordoquy** [comment]
I don't see any reason a `write_only=True` field should be prepopulated. Would it be, it would be the same as showing it through the API, wouldn't it ?

**Comment by tuky** [comment]
The motivation from our side is to have a "clean" API reduced as much as possible. We don't need to read some fields, but still be able to write them. When using the browsable API, it would be nice to update resources without having to look up the values of these fields, if I don't want to change its value. (we're not really using the browsable API, but we are reusing its capability to generate these update forms.)
