### ISSUE TITLE
[Serializer] Cannot use QuerySet Iterator

### ISSUE THREAD

**Issue by ArTiSTiX** [encode/django-rest-framework#1721]
I am using DRF to provide both API (mostly paginated resources) but also export large data files (not paginated resources).

I am confronted to performance issues. I made many optimizations (prefetch_related, and others) and found many articles dealing with large database perfs using a queryset iterator (Model.objects.all().iterator()).

It seems that DRF don't use it, has no options for using it, and can't accept this iterator as a queryset (as it is a generator, and does not contain the same information as the queryset Object).

Is it planned, or considered to improve performance of large DB serialization ?

**Comment by rhunwicks** [comment]
I'm currently doing this with `djangorestframework==3.1.1`:

```python
class GeneratorListSerializer(serializers.ListSerializer):
    """
    Return data as a generator instead of a list
    """

    def to_representation(self, data):
        """
        List of object instances -> List of dicts of primitive datatypes.
        """
        # Dealing with nested relationships, data can be a Manager,
        # so, get a queryset from the Manager if needed
        # Use an iterator on the queryset to allow large querysets to be
        # exported without excessive memory usage
        if isinstance(data, models.Manager):
            iterable = data.all().iterator()
        elif isinstance(data, query.QuerySet):
            iterable = data.iterator()
        else:
            iterable = data
        # Return a generator rather than a list so that streaming responses
        # can be used
        return (self.child.to_representation(item) for item in iterable)

class MyModelSerializer(serializers.ModelSerializer):

    class Meta:
        model = MyModel
        list_serializer_class = GeneratorListSerializer

class MyViewSet(ModelViewSet):
    queryset = MyModel.objects.all()
    serializer_class = MyModelSerializer
```

In theory the real `ListSerializer` could also be updated to using the `QuerySet.iterator()` method, and/or to return a generator rather than a list. I don't know if there would be any downside to doing that, but it works for my use case, which is largely XML exports using `StreamingHttpResponse`

**Comment by tomchristie** [comment]
Routers will try to automatically determine the name of the model to use in the urls and view names. When that's not possible (as in this case where the .model attribute is no longer accessible) you need to use 'basename=' when registering the viewset with the router.

**Comment by rhunwicks** [comment]
But by changing `to_representation` to use the iterator and leaving the `queryset` attribute on the `ViewSet` unchanged, shouldn't the routers work as expected?

**Comment by tomchristie** [comment]
Yup that'd work too :)

**Comment by rhunwicks** [comment]
I'd be cautious about changing to use `QuerySet.iterator()` by default, but I can't see any downside to using a generator comprehension instead of a list one - i.e.

```python
return (self.child.to_representation(item) for item in iterable)
```

instead of the current:

```python
return [
    self.child.to_representation(item) for item in iterable
]
```

Assuming all the tests run, would you be interested in a PR?

**Comment by tomchristie** [comment]
Sure, yup.

**Comment by rhunwicks** [comment]
Another issue is that even if we return an iterator from `to_representation` the problem is that `data` is then creating a `ReturnList` which forces it to be evaluated. Ideally, it would be better if `ReturnList` would accept any iterator rather than extending `list`.

**Comment by aschriner** [comment]
@rhunwicks or @tomchristie 
i'd really like to have a solution for using generators for serializer data - have you gotten any further in implementing this?  i might try to pick up where you left off if not

**Comment by tomchristie** [comment]
This isn't on my list at the moment, no.

**Comment by theromis** [comment]
@rhunwicks want to say thank you you saved my production on 500 meg digital ocean vm
