### ISSUE TITLE
ChoiceField should serialize the human-readable form in to_native

### ISSUE THREAD

**Issue by aop** [encode/django-rest-framework#1755]
Currently the ChoiceField serializes to_native through its base class which causes it to return the first of the choice tuple. This is what Django does. There should be an option to use the "get_FOO_display"-function type of behaviour (https://docs.djangoproject.com/en/dev/ref/models/instances/#django.db.models.Model.get_FOO_display) to get ChoiceFields to serialize the human-readable form in native.

**Comment by Tjorriemorrie** [comment]
I would also prefer the readable form of choices. Giving an integer back makes me go "wtf does that mean"?

Matching input vs output is irrelevant; only the business requirement should be considered.

At least add an argument to the ChoiceField to overwrite label over key for the return value. If you want to return the key value then the value object should be returned as a nested object with its properties, but single field representations can just as well be the label thereof.

**Comment by tomchristie** [comment]
Pull requests to set this as an option would be considered. Not particularly motivated to push this on the core team otherwise.

**Comment by hacknaked** [comment]
I use [django-enumfields](https://github.com/hzdg/django-enumfields/) with a custom DRF field for this:

### models.py

```python

from enum import Enum
from django.db import models
from enumfields import EnumIntegerField

class GeoModel(models.Model):

    class LocationType(Enum):
        ROOFTOP = 1
        RANGE_INTERPOLATED = 2
        GEOMETRIC_CENTER = 3
        APPROXIMATE = 4
        UNRESOLVED = 5

    location_type = EnumIntegerField(
        enum=LocationType,
        default=LocationType.UNRESOLVED
    )
    ...
```

### fields.py

```python
from rest_framework import serializers


class EnumField(serializers.ChoiceField):
    def __init__(self, enum, **kwargs):
        self.enum = enum
        kwargs['choices'] = [(e.name, e.name) for e in enum]
        super(EnumField, self).__init__(**kwargs)

    def to_representation(self, obj):
        return obj.name

    def to_internal_value(self, data):
        try:
            return self.enum[data]
        except KeyError:
            self.fail('invalid_choice', input=data)

```

### serializers.py
```python

from rest_framework import serializers
from . import fields
from . import models

class GeoModelSerializer(serializers.ModelSerializer):

    class Meta:
        model = models.GeoModel

    location_type = fields.EnumField(enum=models.GeoModel.LocationType)
```

**Comment by PJCAfonso** [comment]
Thanks man a easy way to solve my problem...

**Comment by swapnil2911** [comment]
Using the get_foo_display() along with custom serializer method field worked for me.

## models.py

```
class Test(models.Model):
    CATEGORY_CHOICES = [
        ('A', "Choice-A"),
        ('B', "Choice-B"),
        ('C', "Choice-C")
    ]

    category = models.CharField(max_length=1, choices=CATEGORY_CHOICES, verbose_name="Category")
```


## serializers.py

```
class TestSerializer(serializers.ModelSerializer):
    category = serializers.CharField(source='get_category_display')
    class Meta:
        model = Test
        fields = (
            'category'
        )
```

**Comment by MrCordeiro** [comment]
I kind of agree with @tomchristie: as a principle, the output and the input of an API should match (regardless of business requirements).

So the solution I suggest is to create a **second**, read only field, just for the display value. Example:

```python
class UserSerializer(serializers.ModelSerializer):
    gender_display_value = serializers.CharField(
        source='get_gender_display', read_only=True
    )

    class Meta:
        model = User
        fields = (
            "username",
            "email",
            "first_name",
            "last_name",
            "gender",
            "gender_display_value",
        )
```

That way I keep a consistent API's signature and don't have to override DRF's fields and risk mixing up Django's built-in model validation with DRF's validation.

The output will be:

```json
{
  'username': 'newtestuser',
  'email': 'newuser@email.com',
  'first_name': 'first',
  'last_name': 'last',
  'gender': 'M',
  'gender_display_value': 'Male'
}
```
