### ISSUE TITLE
Remove `filter_backend`.

### ISSUE THREAD

**Issue by lovelydinosaur** [encode/django-rest-framework#1775]
This was [placed on the deprecation path in 2.3](http://www.django-rest-framework.org/topics/2.3-announcement#deprecated-attributes), in favor of the more flexible `filter_backends`.

It will move from "pending deprecation" to "deprecated" in 2.4.

It needs to be removed in 3.0.

**Comment by Bouke** [comment]
Just got bitten by a bug where I was using `FILTER_BACKEND` in the settings, which didn't raise a warning/notice when upgrading to DRF 3.0. After changing the field to `DEFAULT_FILTER_BACKENDS` and converting to a tuple/list, it worked fine. While the upgrade path was rather easy, a heads-up would've been helpful.
