### ISSUE TITLE
Make related fields on ModelSerializer respect `limit_choices_to`

### ISSUE THREAD

**Issue by pipermerriam** [encode/django-rest-framework#1811]
The django `ForeignKey` fields support the keyword argument [`limit_choices_to`](https://docs.djangoproject.com/en/dev/ref/models/fields/#django.db.models.ForeignKey.limit_choices_to), which when present, limits the available choices available by default when a `ModelForm` is created.

The serializer fields that represent relationships do not respect this keyword argument.  I propose they should.

If accepted, it appears the place to do this would be in `rest_framework.relations.RelatedField` in the `initialize` method.  Open to alternative suggestions on where/how to implement this.

**Comment by mishu-** [comment]
This is open since 2014. I just ran into the same problem. What is a definite answer on how to solve this?

**Comment by xordoquy** [comment]
Someone needs to step in and update #1843

**Comment by sergiomb2** [comment]
DRF should respect limit_choices_to , is not so uncommon limit a FK to is_active=True the solution provide in #3605 , worked for me i.e. override class PrimaryKeyRelatedField(RelatedField):
with my custom queryset seems that work : 


class CustomForeignKey(serializers.PrimaryKeyRelatedField):
    def get_queryset(self):
        return Table.objects.filter(is_active=True)
