### ISSUE TITLE
Partial=True Not Working #949 #972

### ISSUE THREAD

**Issue by lnhubbell** [encode/django-rest-framework#1830]
Sorry to bring this up again, but I don't think the issue is quite resolved. The offered solution, setting blank=True in the model, seems to be a workaround rather than a desired state. The purpose of partial=True, is stated as: "You can use the partial argument in order to allow partial updates." So if I have a database entry that is full, but I want to update one ore two of the entries, then I can use the partial argument. However, in order to do this I have to set every other field in the database to blank=True, which is a problem because these fields are not optional, they are simply not being updated at this time. 

Sorry if this comes across as beating a dead horse, I assure you, that isn't my intention!

**Comment by kasir-barati** [comment]
It is really annoying. Here is my code:

# `views.py`
```py
class GetUpdateDeleteWatchList(APIView):
    def patch(self, req: Request, id: int,):
        """
        I could not use same serializer for update. I tried:
            - MovieSerializer(data=req.data, required=False)
            - MovieSerializer(data=req.data)
        """
        serialized_request_body = MovieSerializer(data=req.data, partial=True)
        serialized_request_body.is_valid(raise_exception=True)
        
        print(serialized_request_body.data)
        # ....
```

Here is the req: 
![image](https://user-images.githubusercontent.com/73785723/177335666-0f6cd6bd-d5ce-4b02-a226-ac78d7c765b2.png)

# `serializers.py`
```py
from rest_framework import serializers
from rest_framework.serializers import FileField
from ..models import Movie


class MovieSerializer(serializers.ModelSerializer):
    class Meta:
        model = Movie
        read_only_fields = ('id', 'file_name',)
        fields = ['id', 'name', 'description', 'active', 'file_name']
```
And this is the error:
![image](https://user-images.githubusercontent.com/73785723/177335881-300d71d5-1666-41bc-84ff-384c36f1c326.png)
When I try to `print(serialized_request_body.data)` it blow up.

@tomchristie @lnhubbell @xordoquy I novice in Django please help me to know what I did wrong.
