### ISSUE TITLE
Allow option for conflicts in validation to result in `409`, not `400`.

### ISSUE THREAD

**Issue by foresmac** [encode/django-rest-framework#1848]
I know this was [brought up before](https://groups.google.com/forum/?fromgroups=#!searchin/django-rest-framework/409/django-rest-framework/uAwWho5uoLk/49RiIPizzMgJ), but I have to disagree with the rationale that otherwise valid input that fails because of a unique constraint should return a `400 Bad Request`.

The [RFC cited](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html) in the above thread notes that `400` should be reserved for malformed syntax; i.e. keys that aren't used or values that aren't the correct format. A `409` suggests a conflict, i.e. though an email address may be properly formatted, it conflicts with an existing entry in the database because that particular field is required to be unique. While agree with the idea that attempting to `POST` to create an entity with conflicting data is a "bad request", `409` is a more specific error code to return for a conflict to to uniqueness constraints.

Regardless of that issue, however, is the fact that `409` is a _de facto_ standard response when otherwise valid input conflicts with uniqueness constraints. While we could simple override every HTTP method on every view class that would require us to return `409`s instead of generic `400`s for uniqueness checks, we would also have to override our serializers, resulting in more and more complex code when in all other respects we would be able to use the existing generic API views with little to no modifications. The other solution—maintaining our own fork of DRF—is even less palatable.

If some DRF users prefer the `400` only responses for data validation, perhaps a solution to to offer a way to set whether `400`s or `409`s are returned for conflicts.

**Comment by cancan101** [comment]
@tomchristie What ever came of your braindump in the most recent comment? It looks like 400s are raised right now with no easy way of changing that out. Further I think some of the issues you raise about DB errors are still present in #3876.

**Comment by tomchristie** [comment]
No further work here to discuss. Somewhat related to #3775.

**Comment by veeraipuvi** [comment]
how to i fix it
