### ISSUE TITLE
Add `BinaryField`.

### ISSUE THREAD

**Issue by tomchristie** [encode/django-rest-framework#1855]
A serializer `BinaryField` which is mapped to from Django's BinaryField model class (present from 1.6 onwards)

**Comment by hnarayanan** [comment]
I am beginning to work on this one.

**Comment by hnarayanan** [comment]
This requires a bit more thought but I've begun work on this, and will continue at: https://github.com/hnarayanan/django-rest-framework/tree/drf-binary-field .

I think there are two possible ways such a field might be used:

1. The client locally encodes some binary data into a unicode string and sends it along with incoming JSON.

2. The client uploads a binary file (similar to a FileField), which the server converts to a base64 blob representation (to be stored in the db). This could be something like 

“image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA8YAAACcCAYAAAC9bLLNAAAMF…”

Note that this contains enough information (mime type, encoding, data), such that on retrieval, one can reconstruct the original file being represented. This specific format is inspired by [how images are encoded in html/css](https://css-tricks.com/examples/DataURIs/).

In either case, the data is internally represented as a raw sequence of bytes, which is [what Django stores in the database](https://docs.djangoproject.com/en/1.7/ref/models/fields/#binaryfield).

Does this make sense? Any feedback on this thought process will be most appreciated.

**Comment by tomchristie** [comment]
For the purposes of this ticket I think just (1) is suitable, at least as the first pass.
It may be that we also want to allow these field types to support (2), but I'd treat that as secondary.
I think it'll also be worth us having a dedicated section in the docs on file upload as there's a whole bunch of client considersations / design decisions that users need to make there.

**Comment by tomchristie** [comment]
Closing this off given the lack of interest in the ticket.

**Comment by dfrankow** [comment]
fyi i needed this feature. i'll try to hand-code something for my particular field.

**Comment by iMerica** [comment]
This would definitely be helpful. Please re-open the ticket.

**Comment by xordoquy** [comment]
If you need this, feel free to move forward with it. We'll consider PR based on their own merit. Until such PR, we'll keep this closed because we are not going to work on it.

**Comment by dfrankow** [comment]
Good call.

I ended up storing things with a Base64 field I got from a different project. Then I ended up putting the data into S3 instead. So, I won't have a PR for this.

**Comment by eriklesbr** [comment]
@dfrankow Como conseguiu realizar?

**Comment by dfrankow** [comment]
@eriklesbr No me recuerdo. Ya no estoy trabajando en eso.

**Comment by Ou7law007** [comment]
Is this coming anytime soon?
