### ISSUE TITLE
unicode QUERY_PARAMS are being improperly decoded in test client

### ISSUE THREAD

**Issue by outofculture** [encode/django-rest-framework#1891]
In my api tests, a url with query params sent as `q=%E2%85%AF%E2%84%A1%E2%84%A0%CF%8D%E2%83%8E%CF%8B` should get turned into QUERY_PARAMS of `{u'q': u'\u216f\u2121\u2120\u03cd\u20ce\u03cb'}` but the value is instead getting turned into unicode string `u'\xe2\x85\xaf\xe2\x84\xa1\xe2\x84\xa0\xcf\x8d\xe2\x83\x8e\xcf\x8b'`, which, in python 2, is a little tricky\* to decode. Thankfully, this looks to only be a bug in the handling of tests; the same query played against my server is decoded properly.

I upgraded from 2.3.9 to 2.4.2 recently and my tests started failing for unicode searches. Downgrading fixes the problem, bisecting points to commit `0e677e9dd178ae7a0250829729a666b54f4eac61`, but I'm not sure what it's doing wrong.

\* `''.join([chr(ord(c)) for c in QUERY_PARAMS['q']]).decode('utf-8')`

**Comment by muhammad-ammar** [comment]
I am seeing this with `django 1.8.5` and `DRF 3.2.3`. The fixed mentioned above is no longer working.

**Comment by xordoquy** [comment]
Dropping the milestone as we don't have a failing test case.

**Comment by tomchristie** [comment]
Closing this off on the assumption that it's out of date.
