### ISSUE TITLE
Improvements to admin interface.

### ISSUE THREAD

**Issue by tomchristie** [encode/django-rest-framework#1904]
![eab7360c162be3782834ee6e274c5ffd_large](https://cloud.githubusercontent.com/assets/647359/4418050/85cb7d96-455b-11e4-8950-5189e1b6014d.jpg)

The basics of the admin interface have now been merged and will be released in an upcoming 3.2 version. Various incremental improvements to follow. Right now the interface isn't really intended for overriding - we need to change that so that it's easy to modify the behavior and get it working for more than just simple API use cases.
- [ ] Clean up detail vs list pages and templates (extend base)
- [ ] Documentation on overriding.
- [ ] Don't always just include the format in outgoing URLs - only do so on defined links in browsable API.
- [ ] Actions and naming of buttons etc (Inc ensuring internationalized), also clean modal overriding.
- [ ] Messages on edit operations.
- [ ] Strip 'format' for the main HTML representation.
- [ ] Form modals to only include the name part of hyperlinks in select elements.
- [ ] SlugRelatedField should hyperlink.
- [ ] Update Heroku example
- [ ] Filters in HTML.
- [ ] Document the HTML form API. (Possibly with eg nesting and/or list support)

**Comment by auvipy** [comment]
hope to see it in 3.4?

**Comment by tomchristie** [comment]
Most likely, yes.
