### ISSUE TITLE
APIRequestFactory does not use DRF's Request class.

### ISSUE THREAD

**Issue by chuckharmston** [encode/django-rest-framework#1928]
APIRequestFactory currently returns `WSGIRequest` objects, as it inherits from Django's inbuilt `RequestFactory` class.

```
>>> from rest_framework.test import APIRequestFactory
>>> type(APIRequestFactory().get('/'))
<class 'django.core.handlers.wsgi.WSGIRequest'>
```

I would expect it to return instances of DRF's `Request` class, instead. It's not clear if this was intentional or not, but it does make it difficult to write unit tests for e.g. permissions code that takes advantage of some of the features that `Request` provides that `WSGIRequest` does not.

**Comment by kumar303** [comment]
This code shifted around, here's a more stable link to the example: https://github.com/tomchristie/django-rest-framework/blob/d54c67d79d0f5661ef33d860efe80a4272e22b3e/rest_framework/views.py#L311

To restate the problem: this discrepancy means there are subtle things your tests *cannot* cover and that can lead to subtle bugs. For example, in the test suite ``request.POST`` is identical to ``request.DATA`` but in production ``request.POST`` is empty.
