### ISSUE TITLE
Ability to permission related fields

### ISSUE THREAD

**Issue by cancan101** [encode/django-rest-framework#1935]
Right now I am using this mixin for my Viewsets in which I want to limit the the values a related view can take on to those that the user is permissioned to. In other words this extends the `filter_backends` and `permission_classes` concept to the related fields:

``` python
class SecuredFieldMixin(object):
    """
    Filters the queryset for a related field to those items the user has permissions for
    """

    def get_serializer(self, *args, **kwargs):
        parent = super(SecuredFieldMixin, self).get_serializer(*args, **kwargs)
        for secured_field in self.secured_fields:
            if secured_field in parent.fields:
                parent.fields[secured_field].queryset = self.filter_queryset(parent.fields[secured_field].queryset)

        return parent
```

Right now the mixin applies this filtering to the fields listed in `secured_fields`.

It seems like having this permisioning/ filtering is valuable. Is this the best way to implement the logic? Does it make sense to add this to the core DRF?

**Comment by gabn88** [comment]
By the way, although the elegance of the method described here. It is not working anymore, parent.fields does not exist anymore and became parent.child.fields. Also it does not play nice with user defined Filtersets.

**Comment by gabn88** [comment]
I got it working in the end, but it does not limit POST requests. So no go for me.
