### ISSUE TITLE
Browseable API does not allow setting BooleanField to False which defaults to True

### ISSUE THREAD

**Issue by flibbertigibbet** [encode/django-rest-framework#1952]
Booleans which default to false can be set to true by checking the browser form box; however, booleans which default to true are always true when created through the browser form, regardless of the state of the form checkbox.

I've created a small demo project for testing the behavior of boolean fields [here](https://github.com/flibbertigibbet/test-drf-booleans).

Perhaps the best behavior might be to display a checked box by default for boolean fields which default to true, then set the field to false if the box is unchecked on the form.

**Comment by bhodges** [comment]
Hello,

I'm using v3.0.3 and am still seeing this issue or at least a variant in the browseable api.  

For example:

Editing an existing record where the boolean is already set to true (RetrieveUpdateDestroyAPIView):

*  Unchecking the checkbox removes the 'checked' attribute, but the value remains true, there is no onclick event to set the value attribute to false.  I tried manually setting the value to false in the form, but as the checked attributed is then not set, the record does not get updated when I PUT.

I think switching from a checkbox for booleans to a dropdown list might be a good option instead.  I quickly threw together an override for rest_framework/horizontal/checkbox.html to render a select element, and it seems to work great in all scenarios. Options could be 'True', 'False' and '', the latter might be useful if a NullBooleanField is in use (null=True for the model field).
