### ISSUE TITLE
FormResource does not support MultiValueField

### ISSUE THREAD

**Issue by max-arnold** [encode/django-rest-framework#197]
FormResource validation fails on MultiValueField.  It does not understand sub-fields ("This field does not exist") and requires base field name to be present in form data.

**Comment by jpmckinney** [comment]
ChoiceField is not the same as MultiValueField. ChoiceFIeld requires `choices`. MultiValueField does not.

**Comment by jpmckinney** [comment]
In case anyone else ends up here: You can use ListField: https://www.django-rest-framework.org/api-guide/fields/#listfield
