### ISSUE TITLE
Exclude User.password field when serialized by depth=1

### ISSUE THREAD

**Issue by erikcw** [encode/django-rest-framework#1984]
I just noticed that if you set the `depth` option to >= 1 and the model has a foreign key to `django.contrib.auth.models.User`, the `password` field is included in the output.  It's hashed, but it would still be best to exclude this field.

**Comment by rbtsolis** [comment]
Thank You, you help me :) and i have a ManyToMany relations, i share with us my code for ManyToMany :) with Django Rest Framework:

class UserSerializer(serializers.ModelSerializer):

    class Meta:
        model = User
        exclude = (
            'password', 'last_login', 'is_superuser', 'email',
            'gender', 'verify_code', 'created_on', 'is_active',
            'is_staff', 'groups', 'user_permissions', 'courses'
        )


class ResponseCommentSerializer(serializers.ModelSerializer):

    user_response = UserSerializer()

    class Meta:
        model = ResponseComment
        fields = '__all__'
        depth = 1


class CommentSerializer(serializers.ModelSerializer):

    user = UserSerializer()
    response = ResponseCommentSerializer(many=True, read_only=True)

    class Meta:
        model = Comment
        fields = '__all__'
        depth = 2

**Comment by mrParabol** [comment]
What is the depth? Many thanks for your help.

**Comment by rbtsolis** [comment]
> What is the depth? Many thanks for your help.

@mrParabol "Depth" is to show the detail data of your relations, for example if you have a user relation in your model and if you don't have depth you can only show the user id, but if you need the "relation detail" you need add depth, you can try it with a relation, if you need show more than 1 relation, add depth=(**number of relations to show**)

**Comment by CHARANREDDY-learntocode** [comment]
@rbtsolis I will be very happy if you tell me how to exclude fields that are in one depth level, for a clear explanation, I want to remove id field in tools and technology. thanks. 
![image](https://user-images.githubusercontent.com/60844662/112977607-e12cac80-9173-11eb-9618-cbe2b35d6831.png)

**Comment by mohamadmotaghi** [comment]
Did anyone find a solution to this problem ?

**Comment by chadleong** [comment]
> @rbtsolis I will be very happy if you tell me how to exclude fields that are in one depth level, for a clear explanation, I want to remove id field in tools and technology. thanks.
> ![image](https://user-images.githubusercontent.com/60844662/112977607-e12cac80-9173-11eb-9618-cbe2b35d6831.png)

Anyone has any idea how to do this ?

**Comment by oruchkin** [comment]
> > @rbtsolis I will be very happy if you tell me how to exclude fields that are in one depth level, for a clear explanation, I want to remove id field in tools and technology. thanks.
> > ![image](https://user-images.githubusercontent.com/60844662/112977607-e12cac80-9173-11eb-9618-cbe2b35d6831.png)
> 
> Anyone has any idea how to do this ?

Have you solved it? Im on this problem too right now

**Comment by chadleong** [comment]
> > > @rbtsolis I will be very happy if you tell me how to exclude fields that are in one depth level, for a clear explanation, I want to remove id field in tools and technology. thanks.
> > > ![image](https://user-images.githubusercontent.com/60844662/112977607-e12cac80-9173-11eb-9618-cbe2b35d6831.png)
> > 
> > 
> > Anyone has any idea how to do this ?
> 
> Have you solved it? Im on this problem too right now

I solved it by simply specifying the field that I want to how instead of using `__all__` in the fields

e.g.

```
 class Meta:
        model = Technology
        fields = ['name']
```

**Comment by oruchkin** [comment]
> 
found solution here
https://stackoverflow.com/questions/71015915/how-to-exclude-fields-that-are-in-one-depth-level-with-drf/71016571#71016571
