### ISSUE TITLE
Document how to handle permissions and filtering for related fields.

### ISSUE THREAD

**Issue by tomchristie** [encode/django-rest-framework#1985]
Currently relationships do not automatically apply the same set of permissions and filtering that are applied to views. If you need permissions or filter on relationships you need to deal with it explicitly.

Personally I don't see any good ways of dealing with this automatically, but it's obviously something that we could at least do with documenting better.

Right now my opinion is that we should try to come up with a simple example case and document how you'd deal with that explicitly. Any automatic code for dealing with this should be left for third party package authors to handle. This allows other contributors to explore the problem and see if they can come up with any good solutions that could potentially be included in core.

In the future this issue might get promoted from 'Documentation' to 'Enhancement', but unless there's any concrete proposals that are backed up by a third part package then it'll stay in this state.

**Comment by LennyLip** [comment]
Please, read this, seems, it is related topic. How can we separate filtering related fields of Meta (ModelSerializer) for OPTIONS method and a POST or PUT method? 

https://groups.google.com/forum/#!topic/django-rest-framework/jMePw1vS66A

If we set model = serializers.PrimaryKeyRelatedField(queryset=Model.objects.none()), then we can't save current object with related model instanse, because sealizer PrimaryKeyRelatedField "queryset used for model instance lookups when validating the field input".

**Comment by dustinfarris** [comment]
Using `get_fields` is a simple approach that works for me.  Example of a use-case where a user may have multiple blogs, and an entry must belong to one of those blogs:

```python
class EntrySerializer(serializers.ModelSerializer):

    class Meta:
        model = Entry

    def get_fields(self):
        fields = super(NoteSerializer, self).get_fields()
        user = self.context['request'].user
        fields['blog'].queryset = Blog.objects.filter(owner=user)
```

**Comment by dustinfarris** [comment]
This seems to work:

```python
class BlogSerializer(serializers.ModelSerializer):
    
    entries = serializers.SerializerMethodField()

    class Meta:
        model = Blog

    def get_entries(self, obj):
        queryset = obj.entries.all()
        if 'request' in self.context:
            queryset = queryset.filter(author=self.context['request'].user)
        serializer = EntrySerializer(queryset, many=True, context=self.context)
        return serializer.data
```

**Comment by gabn88** [comment]
@dustinfarris That makes it a read-only field... but it does work.

**Comment by jerel** [comment]
Ran into an issue that seems related to this thread. When a filtering backend (Django Filter in my case) is enabled the browsable API adds a `Filters` button to the interface and as far as I can tell that dropdown does not respect the queryset set on the field. It seems to me like it should.

Example:
``` python
class Item(models.Model):
    project = models.ForeignKey(Project)

class ItemSerializer(serializers.ModelSerializer):
    def __init__(self, *args, **kwargs):
        request = kwargs.get('context', {}).get('request')
        self.fields['project'].queryset = request.user.project_set.all()
        super(ItemSerializer, self).__init__(*args, **kwargs)

```
Limits the "add a new Item" form's dropdown to the correct projects but all projects in the db show in the `Filters` dropdown.

**Comment by fibbs** [comment]
nailgun's approach has worked pretty well for me, but only for One-to-Many relations. Now, I have one model where my relationship is a ManyToManyField. In this case, the Mixin approach doesn't work. Any idea how to solve it for these?

**Comment by brk0v** [comment]
@fibbs  change nailgun's approach by adding following:

```python
            if isinstance(field, serializers.ManyRelatedField):
                method_name = 'filter_%s' % name
                try:
                    func = getattr(self, method_name)
                except AttributeError:
                    pass
                else:
                    field.child_relation.queryset = func(field.child_relation.queryset) 
```

**Comment by macolo** [comment]
Apparently somebody contributed a clean solution to this and its now possible without hacking init methods: https://medium.com/django-rest-framework/limit-related-data-choices-with-django-rest-framework-c54e96f5815e

I wonder why this thread has not been updated / closed?

**Comment by xordoquy** [comment]
that someone being me ;)
Good point, I'm going to close this as #3605 already adds something about that in the documentation.
We'll still be considering further improvement to that part if someone can come with something.

**Comment by gabn88** [comment]
It is great that the `get_queryset()` method now exists for RelatedFields. It would be awesome to have it for nested Serializers too though!

**Comment by xordoquy** [comment]
Probably. Want to go ahead with that ? :)

**Comment by Lcstyle** [comment]
Wow... amazing, if this is documented, can you please point me in the right direction?  Ttook me a long time to figure this one out!

Here's a summary of my issue for edification:

For this example, my model names are "deployedEnvs" and "Host".
deployedEnvs contains a Foreign key to the Host model (i.e. many deployedEnvs can point to the same host).  I needed the serializer to display the fqdn field of HOST rather than the PK for the host (I used slug related field for that which was pretty simple).  I also needed when creating a deployedEnv entry (POST), to be able to specify the host by looking up the FK value for the relevant HOST by FQDN field.  Example: create deployedEnv with field host (set to matching fqdn of relevant host object) by looking up the PK for the Host object with the match host.fqdn field.  

Unfortunately I couldn't limit the returned results in the drop down bar to just choices for host objects which are owned by the current user.

Here's my fix code adapted to use slugRelatedField
```
class UserHostsOnly(serializers.SlugRelatedField):
	def get_queryset(self):
		user = self.context['request'].user
		queryset = Host.objects.filter(owner=user)
		return queryset

class deployEnvSerializer(serializers.ModelSerializer):
	host = UserHostsOnly(slug_field='fqdn')
```

I'm about 5 books into Django ( I can list them all if you'd like), and none of the reference texts show how to work with this particular area / functionality of the Framework.  At first I thought I was doing something wrong, am I?  Is there a better way to do what I am trying to do?  Feel free to contact me OOB so I don't end up fudging up the comments for this issue.  Thanks to all for taking the time to read my comment (as a django newbie, this was really hard to figure out).

**Comment by mcspud** [comment]
Each `Field` in DRF (including `Serializers` themselves) have 2 core methods for serializing data in and out (ie between JSON and Python types):

1. `to_representation` - data going "out"
2. `to_internal_value` - data coming "in"

Going off the rough outline of the models you've provided, below is an outline of how RelatedFields work, with SlugRelatedField being a specialised version:
```python

class UserHostsRelatedField(serializers.RelatedField):
    def get_queryset(self):
        # do any permission checks and filtering here
        return Host.objects.filter(user=self.context['request'].user)

    def to_representation(self, obj):
        # this is the data that "goes out"
        # convert a Python ORM object into a string value, that will in turn be shown in the JSON
        return str(obj.fqdn)
    
    def to_internal_value(self, data):
        # turn an INCOMING JSON value into a Python value, in this case a Django ORM object
        # lets say the value 'ADSF-1234'  comes into the serializer, you want to grab it from the ORM
        return self.get_queryset().get(fqdn=data)
```

In reality, you normally want to put a bunch of checks in either the `get_queryset` or `to_internal_value` methods, for things like security (if using something like `django-guardian` or `rules`) and also to make sure the actual ORM object exists.

A more complete example might look like this

```python
from rest_framework.exceptions import (
    ValidationError,
    PermissionError,
)
class UserHostsRelatedField(serializers.RelatedField):
    def get_queryset(self):
        return Host.objects.filter(user=self.context['request'].user)

    def to_representation(self, obj):
        return str(obj.fqdn)
    
    def to_internal_value(self, data):
        if not isinstance(data, str):
            raise ValidationError({'error': 'Host fields must be strings, you passed in type %s' % type(data)})
        try:
            return self.get_queryset().get(fqdn=data)
        except Host.DoesNotExist:
            raise PermissionError({'error': 'You do not have access to this resource'})
```

**Comment by macolo** [comment]
In regards to what @cancan101 wrote some time ago:

> Ran into an issue that seems related to this thread. When a filtering backend (Django Filter in my case) is enabled the browsable API adds a Filters button to the interface and as far as I can tell that dropdown does not respect the queryset set on the field. It seems to me like it should.

This is still true as far as I can see. This can be remedied via a custom `Filterset` field for the foreignkey field that is leaking data, but @tomchristie  I still think this should be solved 'automatically' and the filter modelchoice should respect the `get_queryset` method of the custom field declaration in the serializer.

In any case it would need additional documentation.

I am documenting below how to solve this via a custom filter set:

Sample Workentry Model:
```
class WorkEntry(models.Model):
   date = models.DateField(blank=False, null=True, default=date.today)
   who = models.ForeignKey(User, on_delete=models.CASCADE)
   ...
```

Base model view set:
```
class WorkEntryViewSet(viewsets.ModelViewSet):
   queryset = WorkEntry.objects.all().order_by('-date')
   # only work entries that are owned by request.user are returned
   filter_backends = (OnlyShowWorkEntriesThatAreOwnedByRequestUserFilterBackend, ...)
   # 
   filter_fields = (
      # this shows a filter dropdown that contains User.objects.all() - data leakage!
      'who',
   )
   filter_class = WorkentryFilter
```

Custom FilterSet (overrides `filter_fields` via filter_class in the base model's view set)
```
class WorkentryFilter(FilterSet):
    """
    This sets the available filters and filter types
    """
    # foreignkey fields need to be overridden otherwise the browseable API will show User.objects.all()
    # data leakage!
    who = ModelChoiceFilter(queryset=who_filter_function)

    class Meta:
        model = WorkEntry
        fields = {
            'who': ('exact',),
        }
```

queryset callable as documented here: http://django-filter.readthedocs.io/en/latest/ref/filters.html#modelchoicefilter
```
def who_filter_function(request):
    if request is None:
        return User.objects.none()
   # this solves the data leakage via the filter dropdown
   return User.objects.filter(pk=request.user.pk)
```

**Comment by Lcstyle** [comment]
@macolo 

take a look at this code:

Does this not fix the data leakage issue you are referring to?  My search fields are present in the browsable api, but yet the results are still limited to the queryset filtered by owner.

```
class HostsViewSet(DefaultsMixin, viewsets.ModelViewSet):
	search_fields = ('hostname','fqdn')
	def get_queryset(self):
		owner = self.request.user
		queryset = Host.objects.filter(owner=owner)
		return queryset
```

**Comment by macolo** [comment]
@Lcstyle I am not trying to filter the hosts, I am trying to filter instances of a related field (for example the owners of a host)

**Comment by rrauenza** [comment]
Looking at #3605 I see this can also be done with a custom serializer for the field -- let's use CEO instead of Employee of the Month:

```
 class CEOField(serializers.PrimaryKeyRelatedField):                 
                                                                                  
      def get_queryset(self):                                                     
          company_id = None                                                     
          view = self.context.get('view', None)                                   
          if view and isinstance(view, mixins.RetrieveModelMixin):                
              obj = view.get_object()                                             
              if isinstance(obj, Company):                                      
                  dashboard_id = obj.id                                           
          return Employee.objects.filter(company_id=company_id)           
```

This is designed specifically to return no objects for selection unless we're looking at a specific company.  In other words, a new company couldn't have a CEO until it had employees, which you can't have until the Company is created.

**Comment by coffeepy** [comment]
Hey guys, what am i missing on this? It doesnt get_queryset gets called when i try to override it?

**Comment by robwa** [comment]
I looked for a clean queryset filtering solution without having to add a field class or modifying the field in `__init__()`. I found a solution based on `get_extra_kwargs()` which also works with the browsable API:

```py
class MyModelSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = MyModel
        fields = ["my_field"]

    def get_my_field_queryset(self):
        user = self.context["request"].user
        return MyModel.objects.filter(owner=user)

    def get_extra_kwargs(self):
        kwargs = super().get_extra_kwargs()
        kwargs["my_field"] = {"queryset": self.get_my_field_queryset()}
        return kwargs
```

I thought that it would be really nice to eliminate the boilerplate code in `get_extra_kwargs()` either by looking for `get_<field>_queryset()` methods per default (like validation does) or allowing method names in the `queryset=` parameter of a `RelatedField`. But AFAIR both has been suggested above or in related issues.

**Comment by mherrmann** [comment]
This is such a great solution @robwa <3

**Comment by word-spacing-compensator** [comment]
Here’s the answer you need https://lnkr.fun/c31e66f
