### ISSUE TITLE
collectstatic can't find glyphicons when using ManifestStaticFilesStorage

### ISSUE THREAD

**Issue by defrex** [encode/django-rest-framework#2008]
With the latest 3.0 (https://github.com/tomchristie/django-rest-framework/archive/version-3.0.zip), I got the following when I collectstatic:

```
ValueError: The file 'rest_framework/fonts/glyphicons-halflings-regular.eot' could not be found with <django.contrib.staticfiles.storage.ManifestStaticFilesStorage object at 0x7f5955ef7f28>.
```

Django 1.7 comes with `ManifestStaticFilesStorage`, a staticfiles storage backend that puts a hash of the file in the filename when you run collectstatic. As part of this process, it introspects CSS files no modify any external files references. For that reason, every `@import` needs to be a files Django's collectstatic can access. I believe that is the problem here.

**Comment by aDramaQueen** [comment]
Hi, I think I found the root of this problem with v.4.1
![grafik](https://user-images.githubusercontent.com/52710085/190991638-20ec47f5-8ba9-4df2-bed9-dccbab5d6a25.png)

**Comment by aDramaQueen** [comment]
Quick & dirty workaround for current Django REST (v.3.13.1) with Django 4.1+:

1. Download ["bootstrap.min.css.map v.3.4.0"](https://www.cdnpkg.com/twitter-bootstrap/file/bootstrap.min.css.map/)
2. Download ["bootstrap-theme.min.css.map v.3.4.0"](https://www.cdnpkg.com/twitter-bootstrap/file/bootstrap-theme.min.css.map/)
3. Save these files within your project
4. Subclass from ManifestStorage & copy missing files to your static directory
```python
class WorkaroundFilesStorage(ManifestFilesMixin, StaticFilesStorage):

    def post_process(self, *args, **kwargs):
        missing_files = {'.../path/to/bootstrap-theme.min.css.map', '.../path/to/bootstrap.min.css.map'}

        for missing_file in missing_files:
            shutil.copyfile(missing_file, Path(settings.STATIC_ROOT, 'rest_framework', 'css', missing_file.split('/')[-1]).resolve())
        return super().post_process(*args, **kwargs)
```
5. Redirect to this new Storage in your settings.py
```python
STATICFILES_STORAGE = 'full.canonical.name.to.WorkaroundFilesStorage'
```
