### ISSUE TITLE
ModelSerializer requiring fields set to blank/null=True in the Model. (DRF3)

### ISSUE THREAD

**Issue by jarrodb** [encode/django-rest-framework#2017]
Just verifying this was an intended change from 2.4 -> 3.0 that now requires specifying a null value for resource creation when Model fields contains blank=True and null=True (without default=<value>) since the ORM will handle it:

models.py

``` python
class Test(models.Model):                                                       
    name = models.CharField(max_length=255)                                     
    description = models.TextField(blank=True, null=True)
```

``` python
class TestSerializer(serializers.HyperlinkedModelSerializer):                   
    class Meta:                                                                 
        model = Test                                                            
        fields = ('url', 'name', 'description')                                 


class TestViewSet(viewsets.ModelViewSet):                                       
    queryset = Test.objects.all()                                               
    serializer_class = TestSerializer    
```

```
(drf30)$ curl -H 'Accept: application/json; indent=4' -X POST -d "name=whatsup" http://127.0.0.1:8000/tests/ 
{
    "description": [
        "This field is required."
    ]
}
```

**Comment by nibudd** [comment]
I am experiencing this problem with a float field

**Comment by sebitoelcheater** [comment]
why is this closed? @tomchristie

**Comment by xordoquy** [comment]
@sebitoelcheater according to the issue's history, this looks like this was fixed.

**Comment by tstirrat15** [comment]
@jarrodb I think this is because of the difference between `required` and `allow_blank` - if you set `required=False` on the serializer, then the serializer doesn't require the key to be present. Otherwise, the serializer is going to be looking for all of the fields declared within the serializer, whether they're blank or not.

**Comment by tstirrat15** [comment]
Relevant docs: http://www.django-rest-framework.org/api-guide/fields/#required
