### ISSUE TITLE
More documentation on source='*' for Serializer fields

### ISSUE THREAD

**Issue by cancan101** [encode/django-rest-framework#2032]
Right now the docs for the special value just say:

> The value source='*' has a special meaning, and is used to indicate that the entire object should be passed through to the field. This can be useful for creating nested representations. (See the implementation of the PaginationSerializer class for an example.)

And as far as the `PaginationSerializer`, the entire [implementation is just this](https://github.com/tomchristie/django-rest-framework/blob/b106ebd2c0a19107f12d5b87cfbe0083aaaa60b9/rest_framework/pagination.py#L77).

What exactly does the `*` do and what would happen in the case of `PaginationSerializer` if it were omitted?

**Comment by ssbrewster** [comment]
More examples are always useful but would you then want to add an example for each of the serializer field core arguments (currently there is an example for the style argument only)?

**Comment by tomchristie** [comment]
@ssbrewster If someone wants to take it on, then yes. Otherwise, not a huge priority.
