### ISSUE TITLE
Architecture overview docs.

### ISSUE THREAD

**Issue by DavidMuller** [encode/django-rest-framework#2085]
I've found myself digging through the source code of rest_framework a lot to really get a grasp on how DRF processes a requests; sometimes I'm unsure of who calls what.

Tasty pie has an [excellent writeup on the its general flow from request to response flow for a simple GET request](http://django-tastypie.readthedocs.org/en/latest/resources.html#flow-through-the-request-response-cycle):

> - The Resource.urls are checked by Django’s url resolvers.
> - On a match for the list view, Resource.wrap_view('dispatch_list') is called. wrap_view provides basic error handling & allows for returning serialized errors.
> - Because dispatch_list was passed to wrap_view, Resource.dispatch_list is called next. This is a thin wrapper around Resource.dispatch.
> - dispatch does a bunch of heavy lifting. It ensures:
>   - the requested HTTP method is in allowed_methods (method_check),

DRF has excellent documentation for many of its individual components; it would be tremendously helpful if DRF had a page that outlined, generally, how the package works.  What is the general flow of the innards--how does DRF process a typical request --> response?

Thanks @tomchristie for such an excellent package!

**Comment by tomchristie** [comment]
Closing this off as stale
