### ISSUE TITLE
Test template rendering performance for HTMLRenderer.

### ISSUE THREAD

**Issue by tomchristie** [encode/django-rest-framework#2093]
Eg, like so: https://github.com/gregmuellegger/django-floppyforms/blob/master/benchmark.py

It'd be interesting to check both Jinja and Django templates for the HTMLRenderer, and also benchmark against Django's built in form rendering.

**Comment by rpkilby** [comment]
Closing in favor of #5614, which is a benchmarking/performance meta issue.
