### ISSUE TITLE
django-rest-framework: serializer from DATA don't update model ID

### ISSUE THREAD

**Issue by StErMi** [encode/django-rest-framework#2114]
I've also posted on stackoverflow to gather help faster: http://stackoverflow.com/questions/27076918/django-rest-framework-serializer-from-data-dont-update-model-id

I've a simple serializer like this:

``` python
    class CategoryCreationSerializer(serializers.ModelSerializer):

        class Meta:
            model = Category
```

Category has an id field (Django primary key) and I don't get why the Serializer is not updating it.

Scenario: I've a BlogPost with a given category. I'm updating the BlogPost with a different Category (already created on the database). So the POST request will have all the BlogPost information with the new Category JSON object with the updated id:

``` json
    {
        "id": 1,
        "title": "My first blog post",
        "category": {
            "id": 3,
            "name": "Techology"
        }
    }
```

The problem is that when I'm doing this:

``` python
    category_data = data.get('category')
        if category_data is not None:
            category_serializer = CategoryCreationSerializer(data=category_data)
            if category_serializer.is_valid():
                blog_post.category = category_serializer.object
```

inside category title will be updated but the id field will be NONE.
Can you explain me why? 

Cheers, Emanuele.

**Comment by aj07mm** [comment]
I did all this:
models.py
```
# -*- coding: utf-8 -*-
from django.db import models


class Address(models.Model):
    id = models.PositiveIntegerField(primary_key=True)
    country = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    city = models.CharField(max_length=50)

```
serializers.py
```
class AddressFormSerializer(serializers.HyperlinkedModelSerializer):

    id = serializers.IntegerField()

    class Meta:
        model = Address
        fields = tuple(Address._meta.get_all_field_names())

```

views.py

```
if address_serializer.is_valid():
                address_serializer.save() #*** IntegrityError: UNIQUE constraint failed: ana_address.id
```

@tomchristie

**Comment by xordoquy** [comment]
@aj07mm, the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!

**Comment by rangerg** [comment]
I have eve found a good answer in this Forum, should be close
