### ISSUE TITLE
Need more examples about nested resources.

### ISSUE THREAD

**Issue by BrickXu** [encode/django-rest-framework#2125]
Hi all,

I'm using DRF in our project now, and I found there was few exmaples to show how to define nested resources with router, and I try drf-nested-router but it's not very suitable for us.

Fortunately, we found a simple way to deal with nested resources, no more 3rd packages.

Sorry for my poor english :), I think use code to show it will be easy.

The URL we want:

```
/components/  <-- component list
/components/{pk}  <-- one component, query by pk
/components/{pk}/contacts  <-- contacts list of this component, the component from pk
/components/{pk}/contacts/{contact_pk}/  <-- one contact of this compnent, from contact_pk & component pk.
```

And this is my code

``` python
router.register(r'components', component_views.ComponentViewSet)
router.register(r'components/(?P<gc_id>[^/.]+/contacts', component_views.ComponentContactViewSet)
```

It extends the parent resource url, and DRF will process it very well, no need to hack router.

Anyway, I hope these would help you if you're dealing with nested resources.

**Comment by learner010** [comment]
I would love to see this information in documentation too. The available packages for nested routers have limitations and looks kind of hack. The solution provided @BrickXu  is simple and elegant.
