### ISSUE TITLE
Document form styles for field classes.

### ISSUE THREAD

**Issue by lovelydinosaur** [encode/django-rest-framework#2138]
Including, but not necessarily limited to:
- Textarea vs input for string inputs.
- Radio vs select for choices, and for relations.
- Ensure boolean fields support choice styles.

Primarily documentation, but may also include some development work on finalizing the API.

**Comment by tomchristie** [comment]
Pushing all further HTML specific stuff to 3.2.0.

**Comment by pnovotnak** [comment]
+1 how do I make textareaz?

**Comment by jpadilla** [comment]
@pnovotnak The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!

To answer your question, if you look under [Core Arguments](http://www.django-rest-framework.org/api-guide/fields/#core-arguments) in the Serializer Fields docs you can find more about the `style` attribute.
