### ISSUE TITLE
Use `HTML JSON form` style for nested HTML forms.

### ISSUE THREAD

**Issue by lovelydinosaur** [encode/django-rest-framework#2148]
We support nested HTML form submissions for eg. forms with nested children.

We should drop the current style of indexing the we use and instead adopting this draft proposal as the nesting style... http://www.w3.org/TR/html-json-forms/

> User agents that implement this specification will transmit JSON data from their forms whenever the form's enctype attribute is set to application/json. During the transition period, user agents that do not support this encoding will fall back to using application/x-www-form-urlencoded. This can be detected on the server side, and the conversion algorithm described in this specification can be used to convert such data to JSON.

This would also pre-emptively give us support for JSON submissions using HTML forms if the draft does become adopted.

**Comment by tomchristie** [comment]
Pushing all further HTML specific stuff to 3.2.0.

**Comment by tomchristie** [comment]
Our current ad-hoc approach is handled here... https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/utils/html.py

**Comment by sheppard** [comment]
See #2682 for a potential implementation.
