### ISSUE TITLE
Remember submitted JSON data in web browseable API when using POST method

### ISSUE THREAD

**Issue by jonancm** [encode/django-rest-framework#2150]
**Affected functionality**

When you use the web browseable API to test some views that inherit from `APIView` and thus the "schema" of the JSON data is not known to Django REST Framework, the framework shows a form to input some arbitrary JSON (_raw data form_):

![screenshot](https://cloud.githubusercontent.com/assets/4405268/5214588/49a3cc38-7616-11e4-90dc-c3a7c956d0f5.png)

When inheriting from any of the generic views or generic view mixins, Django REST Framework will instrospect the model fields to auto-populate the JSON dictionary in this raw data form, and will also render an _HTML form_ with a separate input widget for each model field:

![screenshot](https://cloud.githubusercontent.com/assets/4405268/5216828/e501f500-7630-11e4-847d-3f57dc3b239a.png)

**Description of the issue**

As of version 2.3.13 of Django REST Framework, which is the latest version I've tried, when I enter some JSON into the raw data form of an `APIView` and submit the form, the next page (results page) doesn't remember the JSON data I submitted, neither as a read-only value rendered on the page, nor as editable data in the raw data form.

In addition, when the view inherits from the generic API views or mixins, the JSON dictionary that is generated when auto-populating the raw data form after submitting it is again the default value generated when auto-populating the form. So, if I submit this JSON data in order to search/filter/retrieve some objects (i.e. instances of Django models):

![screenshot](https://cloud.githubusercontent.com/assets/4405268/5216846/298ed0ee-7631-11e4-9af0-e2b1e0cdc8a1.png)

when the result page is rendered, the data I submitted is not shown, but the default value is shown instead:

![screenshot](https://cloud.githubusercontent.com/assets/4405268/5216828/e501f500-7630-11e4-847d-3f57dc3b239a.png)

Because of this, if I wanted to repeat the query in a different browser window/tab or modify parts of the query, I would have to enter all the values of the JSON fields again.

_Note: It seems that the HTML form does remember the submitted values, but the raw data form doesn't._

**Suggested solution (feature request)**

For the web browseable API to be more convenient and easier to use, it is desirable that the submitted form data be shown when rendering the results page, as this would enable users to copy & paste the data to make a new request in a different browser window/tab, or to amend the submitted request without having to manually fill in all JSON fields again.

This could be done either by rendering a read-only copy of the submitted JSON dictionary somewhere on the results page that can be copied & pasted, or rather by populating the raw data form with an editable version of the submitted JSON data, so that it can be directly edited in the form.

**Comment by youneschaoui** [comment]
It would be so great to have that I express the same need
