### ISSUE TITLE
Link from Serializers docs to Validation discusion re using `read_only` and `unique_together`

### ISSUE THREAD

**Issue by carltongibson** [encode/django-rest-framework#2164]
I create a barebones `ModelSerializer` for a model with a required `ForeignKey` to `User`. Intending to set the relation in `perform_create` I add the field to the `read_only_fields` Meta attribute. 

If I do nothing else I get an AssertionError as the auto generated field is:

```
PrimaryKeyRelatedField(read_only=True, required=True)
```

OK. Rightly this doesn't make sense. 

But I here need to declare the `PrimaryKeyRelatedField` in order to set `required=False` manually. Better would be that setting `read_only=True` makes `required=False`.

No problem at all putting a test together for this. I haven't looked re a fix.

**Comment by lgandras** [comment]
Why doesn't UniqueTogetherValidation check if values are null? Null by definition is a non-known value. null <> null. Duplicated null entries are completely valid, semantically speaking. I have a situation where I can't insert a row with null unique-together values. Can this issue be reopened?

**Comment by lgandras** [comment]
Ok, I managed to solve it using *default=None*. I know the documentation says fields with *default* are the exception to the implicit required field validator, but it is not obvious at all that setting *default=None* allows the value to bypass the *UniqueTogetherValidator* (i realised that reading the code). It would be a nice add-on to the documentation :)

**Comment by adamdonahue** [comment]
I know this is old, but what is the correct approach here?

I have a related field (foreign key) that was set in a read_only_fields.  I made it part of unique_together on that model and now I'm getting the AssertionError above.  But I want this field to be returned but not writable by the user on serialization.  (It's already set and shouldn't change.)  I can't figure out the correct approach here.  Help?

@tomchristie

**Comment by tomchristie** [comment]
@adamdonahue - Lets take this off the issue fracker. Best thing would be to expand on your issue more fully on the discussion group, and then drop a link to it here.

**Comment by rtindru** [comment]
@tomchristie Seconding @adamdonahue comment. We had a model and with two ForeignKeys and a Serializer that was meant to return these values but not allow writing into them. Our implementation was simple, put these fields in `read_only_fields` of the serializer. Later, went went on to add a `UniqueTogether` validator on the Model for these two fields. Now the DRF serializer throws an `AssertionError`. How do I handle this requirement with DRF?

**Comment by xordoquy** [comment]
> Why shouldn't a read_only field imply required=False?

In the case of a `UniqueTogether` constraint, if one field is read only and the other one is writable you need to have both fields in order to validate. 

> How do I handle this requirement with DRF?

Remove the `UniqueTogether` validator.

**Comment by nathanielcompton** [comment]
@adamdonahue did you ever follow through with a discussion?
@rtindru  any more insight?

**Comment by adamdonahue** [comment]
@nathanielcompton I honestly don't remember.  I can't even remember the context, but I believe I worked around it.  Thanks for following up.
