### ISSUE TITLE
Better catching of error cases in `.update` and `.create`.

### ISSUE THREAD

**Issue by brianhv** [encode/django-rest-framework#2202]
When I do a PUT through the API browser to a view whose serializer contains a source property:

``` python
last_name = serializers.CharField(source='user.last_name')
```

I receive the following error:

```
Cannot assign "{'first_name': u'first', 'last_name': u'last'}": "ContactInfo.user" must be a "User" instance
```

I've created a [bare-bones django project that reproduces the error](https://github.com/brianhv/drfissue). Of particular note are the [serializers](https://github.com/brianhv/drfissue/blob/master/drftest/drftest/readonly/serializers.py) and the [model](https://github.com/brianhv/drfissue/blob/master/drftest/drftest/readonly/models.py).

Relevant excerpt of IRC conversation leading to this ticket:                   

```
<BrianHV> if you clone the repo, install the stuff in the requirements.txt (just django
          1.6 and DRF 3), set up a user, and use admin to create a ContactInfo for the
          user, you should be able to reproduce
<BrianHV> I'm testing through the API browser, btw.
<kevin-brown> Yeah, I think I know what is happening
<kevin-brown> `validated_data` is being (correctly?) generated as a nested dictionary,
              and that's being assigned to the `user` parameter directly
<kevin-brown> If you can open a ticket explaining that it works in DRF 2.4, that'd be
              helpful
<kevin-brown> In DRF 2.4, it would traverse the relation and assign the properties
              directly
```

**Comment by jonathan-golorry** [comment]
I noticed this is closed but I'm still getting the exact same error response.

It's also a little annoying that I can't even remove the attribute during validation or creation and then run super().create.

**Comment by tomchristie** [comment]
> I can't even remove the attribute during validation

Use `validate` if you want to modify what ends up in `.validated_data`

**Comment by jonathan-golorry** [comment]
Yeah, I looked at things a bit closer and realized it was storing the attribute in `attrs` and `validated_data` according to the source path, not the name of the attribute. I suppose that makes sense, I just didn't expect it.

I'm still curious as to why I wasn't getting the new exception though.
