### ISSUE TITLE
Object-level validation not working on ModelSerializer

### ISSUE THREAD

**Issue by calina-c** [encode/django-rest-framework#2252]
I'm having an object with a min and a max field, which I need to validate on a class level. However, several methods don't work. I tried:
- adding the method validate(self, data) in the serializer, raising an exception directly
- adding a new class with _ _ call_ _ that raises the same exception, adding it as a validator in Meta

Field level validators work. The issue appears both at editing with PUT and creating with POST.

**Comment by xingheng** [comment]
Reopen this.

I found the object validation not working with custom `validate(self, data)` in the serializer class, after digging into the `is_valid` method inside, I found the object validation method should be `run_validation(self, data)`, this works for me.

So, why does the [documentation](https://www.django-rest-framework.org/api-guide/serializers/) not update for this? Or am I wrong?

Django 2.2 with DRF 3.10

**Comment by xordoquy** [comment]
It's not called likely because some previous steps have failed before it can call `validate`.
As far as I can tell, documentation is correct as it is.
If you think there's an issue with the documentation you'll need to be more specific about the issue.

**Comment by frankdilo** [comment]
I confirm that my custom `validate` method is not being called with a `serializers.ModelSerializer`, with no other steps failing before.

**Comment by Tobeyforce** [comment]
> I confirm that my custom object-level `validate` method is not being called with a `serializers.ModelSerializer`, with no other steps failing before.

Are you actually calling is_valid on it? It won't run if you don't :)

**Comment by amithuu** [comment]
def run_validation(self, data):
        if data['max_years_experience'] < data['min_years_experience']:
            raise serializers.ValidationError({'message': 'max_years_experience cannot be less than min_years_experience'})
        else:    
            return super().validate(data)
            
            yes this is run_validation()..
            thanks @xingheng

**Comment by amithuu** [comment]
`def run_validation(self, data):
        if data['max_years_experience'] < data['min_years_experience']:
            raise serializers.ValidationError({'message': 'max_years_experience cannot be less than min_years_experience'})
        else:    
            return super().validate(data)`
            
            run_validation() works
            thanks @xingheng

**Comment by CodeChanakyaa** [comment]
> Sorry, closing this since it was a misunderstanding. Non-field errors appear only if per-field validators pass. I wasn't aware of that previou

> Sorry, closing this since it was a misunderstanding. Non-field errors appear only if per-field validators pass. I wasn't aware of that previously.

Hey, but you said previously that its happening with object level validation

**Comment by CodeChanakyaa** [comment]
> Sorry, closing this since it was a misunderstanding. Non-field errors appear only if per-field validators pass. I wasn't aware of that previously.

Hey, but you said previously that its happening with object level validation

**Comment by DarkhanShaga** [comment]
> I confirm that my custom object-level `validate` method is not being called with a `serializers.ModelSerializer`, with no other steps failing before.

It is probably because you call it without parenthesis, and you probably have __init__ in it. You need to call it like that ExampleValidator() and there should be no __init__ in it, only __call__.
