### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'max_length'

### ISSUE THREAD

**Issue by davidmir** [encode/django-rest-framework#2264]
This error happens when I'm going to serialize the model. Why? Will be for the class has the type auth_models.AbstractBaseUser?

**Comment by shacker** [comment]
This happened to me (with DRF 3.0.1) because 

```
year = models.SmallIntegerField(null=True, blank=True, max_length=4)
```

Removing max_length from the model field and migrating made DRF happy. Not clear from the Django docs whether I was misusing max_length there or not - seems reasonable for a "year" field.

**Comment by molecular** [comment]
Hm, I'm getting this on a DateTimeField

Documentation states that "required" is a core attribute for all Fields, so it should be accepted by DateTimeField, no?

**Comment by xordoquy** [comment]
There's a warning in Django that tells you not to use max_length with `IntegerField` but at the same time, it's a valid argument - understand, it won't crash if you provide it.
Weird.

**Comment by xordoquy** [comment]
Maybe we should support it or make a clear error message if we face it.
