### ISSUE TITLE
Queryset based on request

### ISSUE THREAD

**Issue by stevelacey** [encode/django-rest-framework#2292]
I am just upgrading to DRF 3.0, and I am pretty much there.

One thing for the upgrade docs / helping me... how do I contextualise the queryset now required for related fields to the request?

At ViewSet level, for the results, remains easy:

``` py
    def get_queryset(self):
        if self.request.user.is_staff:
            queryset = Book.objects.all()
        else:
            queryset = self.request.user.library.books.all()

        return queryset
```

But when customising the choices for a relation in a serializer:

``` py
    book = SlugRelatedField(queryset=Book.objects.all(), slug_field='isbn')
    #                                    ^ how request here? lambda... magic?
```

**Comment by stevelacey** [comment]
@tomchristie is there any better approach for this yet? I am running into a bunch of issues caused largely by requiring the request in serializers – e.g. django-rest-swagger wants to access the fields for introspection and doesn't pass a context along

**Comment by tomchristie** [comment]
> e.g. django-rest-swagger wants to access the fields for introspection and doesn't pass a context along

In which case I'd suggest overriding `get_serializer` instead, and modifying the field at that point.
That way it's happening in the context of a view, rather than implicitly requiring `request` in the context.
