### ISSUE TITLE
Serializer .to_representation() doesn't call field.to_representation() for attributes of value None

### ISSUE THREAD

**Issue by metaljoe** [encode/django-rest-framework#2299]
Not sure if this is a bug/feature/other but I have a situation with an "is_deleted" field in my serializer that takes a source deleted_datetime field from the model. The field is set to NULL/None when the item is not deleted, and a datetime when deleted. The API shows is_deleted as True (datetime set) or False (when NULL).

However, the Serializer .to_representation only calls the field .to_representation when the attribute is not None. This means is_deleted comes back as either True or None.

I've had to override the get_attribute method in the field to call the field's parent get_attribute and then map accordingly, but this doesn't feel right as I'm doing the same work as the .to_representation method.

Am I missing the obvious? It's been a long week already! :-)

**Comment by GonzaloRizzo** [comment]
I would like to reopen this issue since I think that it would be a nice feature to have and right now I'm migrating an old codebase to DRF and I have a field were `None` needs more parsing.

I think that a good solution is to have an attribute on Field that defaults to `False` and you can override it to force the call of `to_representation`

If you like the idea I'll start working on a PR

**Comment by xordoquy** [comment]
@GonzaloRizzo I don't think it's up to the serializer to do that work. I believe that's part of the business / service layer (could be merged within the model layer) to provide the informations.

**Comment by dz0** [comment]
What about `BooleanField` -- it kind of explicitly states that does **not** support null/None, but
will alow null in serialization, demo:
```py
class S(Serializer):
    bf = BooleanField(required=False, read_only=True)

class example:
    bf = None  # I expect it to become **False**

s = S(instance=example)  
assert s.data['bf'] == False # Fails, because {'bf': None} 
```

For me it looks like a bug..

**Comment by tomchristie** [comment]
Don’t do that.

**Comment by dz0** [comment]
not intentionally, but subquery'ing, sth like
```py
Person.objects.annotate(is_occupied=Subquery(
        Event.objects.
            .filter(bookable=OuterRef('pk'))
            .values('occupied')[:1],
        output_field=BooleanField()
    )
)
```
when none events found, gives None...

I can/will cast now, but docs could mention this behaviour (at least in "strict" BooleanField topic) 
Thanks

**Comment by oxfn** [comment]
I also think this is unexpected behavior to skip `to_representation` for `None` values. `None` is also value like any other value, and skipping it breaks the idea of customized field. For example I have 

    class UserSerializer(serializers.ModelSerializer):
        country = CustomCountryField(Country, CountrySerializer)

and I want to use this serializer for read and write, so `SerializerModelField` does not fit this case as it does not support `set_field_name`. Besides, the main reason to customize this field in my case is to set fallback value `{}` on read if `country` is `None`.

At least this "optimization" can be made configurable like `skip_empty=False`.
I can implement this improvement if you guys agree with this idea
