### ISSUE TITLE
Requesting guidance on re-implementing `allow_add_remove=True` on nested serializers

### ISSUE THREAD

**Issue by RossRogers** [encode/django-rest-framework#2304]
Might it be possible to get pointers to the new data structures and the internals that I'll need to crawl in order to get `allow_add_remove=True` behavior in `update()` and `create()` of a serializer?  `validated_data` doesn't have any model instance information so one can't figure out if this is an existing object or it needs to be created or what have you.

The serializer's `self` reference has the `data` field, but I'm leery of crawling through all the internal fields of serializer that aren't explicitly presented through the `update()` interface.

Could I get a little guidance?

**Comment by RossRogers** [comment]
Tom,

If you haven't already implemented this, can we iterate on a specification of the behavior of nested serializers?  Here is a rough draft:


C.R.U.D. for nested serializers
===============================

One-to-One and Foreign Key Fields
---------------------------------

### PUT/POST/PATCH behavior of nested One-to-One/ForeignKey objects

If the object has a non-NULL primary key field (`id`/`url`/`pk_id`), then it is assumed to exist and will be updated.

If the object does _not_ have a primary key, then a new object is created for that nested field.  

This is done recursively.  Each _nested_ level is evaluated on its own.  The original object is still processed as a non-nested object:

* PUT updates if primary key field exists, else validation error. 
* PATCH updates or creates depending on primary key field existence/non-existence, respectively.
* POST creates a new object, regardless of primary key field presence.


### DELETE behavior with nested One-to-One/ForeignKey objects


When a DELETE is issued on an object with nested objects, the nested objects are _not_ deleted explicitly.  Instead, the configuration of cascading deletes as specified by the model's [cascading delete options](https://docs.djangoproject.com/en/1.8/topics/db/queries/#deleting-objects) is implicitly invoked.


ManyToMany and ForeignKey Field `related_name` nested list objects
------------------------------------------------------------------

There is ambiguity with respect to updating a nested serializer's model's `ManyToMany` field or or a field specified by another model's field that is a `ForeignKey`'d to the original model having a `related_name` parameter.  Specifically, what to do when a nested object _within_ a list, is not sent to the server, whereas it is currently present in the database.

### POST 

Creating an object with lists of nested objects has no ambiguity, and whether to update or create the nested object simply depends on primary key field existence or non-existence, respectively.

### PUT

When nested lists of objects are `PUT`'d to the server, then it is assumed that the list is complete.  If an object no longer exists in the list, then that relationship is destroyed.

### PATCH

When nested lists of objects are `PATCH`'d to the server, then it is assumed that the list may be partial.  Any objects which are no longer present in the list are *not* deleted.  Removal from the list must be done with the `PUT` request.

**Comment by tomchristie** [comment]
On a quick pass over that all sounds about right, yes.
