### ISSUE TITLE
Documentation Error in Tutorial 6

### ISSUE THREAD

**Issue by epicserve** [encode/django-rest-framework#2306]
After completing Tutorial 6, when trying to create a new snippet I get the following ...

```
Request Method: POST
Request URL:            http://127.0.0.1:8000/snippets/
Django Version: 1.7.1
Exception Type: IntegrityError
Exception Value:    NOT NULL constraint failed: snippets_snippet.owner_id
```

I'm using DRF 3.0.2

**Comment by ydaniels** [comment]
This is still not working with perform_create in tutorial #4

**Comment by xordoquy** [comment]
@ydaniels "not working" isn't actionable.

**Comment by crasker** [comment]
facing the same problem, using the `preform_create` method and got the same error

looks like it happened again

**Comment by xordoquy** [comment]
@crasker if you have the same error, make sure you did the step "Updating our serializer" before testing the API.

**Comment by crasker** [comment]
![image](https://cloud.githubusercontent.com/assets/3174573/23016848/01733b50-f473-11e6-8d18-10ae0544c0e1.png)
@xordoquy

is this right？Thank you！

**Comment by goingeast** [comment]
I am following the tutorial and get same error.

**Comment by xordoquy** [comment]
The final steps are available [here](https://github.com/encode/rest-framework-tutorial)
This issue likely means that you skipped a step at some point.

**Comment by Alechan** [comment]
To everyone stuck on Tutorial 4:

That stage of the tutorial is missing the "perform_create" that is added later, which passes the owner to the serializer. By default, the serializer doesn't "receive" the owner because it is not set in the POST request. The SnippetList class at Tutorial 4 should be:

```
class SnippetList(generics.ListCreateAPIView):
    queryset = Snippet.objects.all()
    serializer_class = SnippetSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]

    def perform_create(self, serializer):
        serializer.save(owner=self.request.user)

```
