### ISSUE TITLE
404 page in theme has hardcoded nav.

### ISSUE THREAD

**Issue by tomchristie** [encode/django-rest-framework#2313]
See: https://github.com/tomchristie/django-rest-framework/blob/master/docs_theme/404.html#L64

Possibly also see https://github.com/tomchristie/mkdocs/issues/77 may not be as simple as adding the nav in.

**Comment by adrienbrunet** [comment]
This one can be closed, right ?

**Comment by tomchristie** [comment]
Yup. Thanks!
