### ISSUE TITLE
I got some errors: TypeError: __init__() got an unexpected keyword argument 'style'

### ISSUE THREAD

**Issue by no13bus** [encode/django-rest-framework#2339]
I use this example(http://www.django-rest-framework.org/tutorial/1-serialization/) and when I go to this Chapter `Working with Serializers`,  I type this `from snippets.serializers import SnippetSerializer`, it have some errors:

``` python
TypeError: __init__() got an unexpected keyword argument 'style'

TypeError: __init__() got an unexpected keyword argument 'allow_blank'
```

My django version is 1.6.5

**Comment by z-image** [comment]
Sounds like following 3.0 tutorial, but using django rest framework 2.4.
