### ISSUE TITLE
Update to 3.0.2 breaks Django REST Swagger

### ISSUE THREAD

**Issue by maxleonov** [encode/django-rest-framework#2344]
Hi, I'm a big fan of Django Django REST framework and really excited to upgrade to newest version, but there's an issue...

I figured out that after upgrade to Django Django REST framework 3.0.2, API Docs (Django REST Swagger) don't work anymore.

When I open <SITE>/docs/api-docs/api , I see that an exception has been thrown:

> Exception Type: AssertionError
> Exception Value: 'LabelViewSet' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
> Exception Location:   /home/max/.virtualenvs/nlp-rest/local/lib/python2.7/site-packages/rest_framework/generics.py in get_serializer_class, line 189

Django Version: 1.7.1
Django REST Swagger Version: 0.2.6
Python Version: 2.7.6

![assertionerror 2014-12-23 12-43-59](https://cloud.githubusercontent.com/assets/1827485/5536901/8374641e-8aa1-11e4-9c71-0ec13e553f7f.png)

**Comment by martyzz1** [comment]
I'm running into this same problem, but I'm not using a ModelViewSet

**Comment by martyzz1** [comment]
For others running into this, I think it is possible for swagger to fix this. the issues is that the swagger code asks for the serializer class before checking if it should ignore it due to swagger's docstring configuration....

Will raise an issue on swagger

**Comment by xordoquy** [comment]
@martyzz1 please do. Thanks for investigating on that issue.

**Comment by martyzz1** [comment]
https://github.com/marcgibbons/django-rest-swagger/issues/351
