### ISSUE TITLE
Lists in HTML forms

### ISSUE THREAD

**Issue by xordoquy** [encode/django-rest-framework#2483]
The 3.0 release notes mentioned that:
"Nested lists of HTML forms are not yet supported, but are planned for 3.1."

I may have missed a point but can't find a bug related to this at the moment.

**Comment by tomchristie** [comment]
Yup thanks for raising the issue - this *is* on the roadmap.
I'm thinking we should push the HTML stuff (including this) into 3.2.0 (possibly with the admin in 3.3.0. Given that 3.1.0 currently has:

* Versioning.
* Pagination API improvements (including cursor pagination, limit/offset pagination and support for header based pagination styles.)
* Pre-provided translations.
* ModelSerializer fields API.
* Support for 1.8 and various additional fields. (Okay some of that's already in 3.0.4, but if we add the remaining 1.8 field types it'd make for a nice solid release feature set.)

Seems like there's enough there that we oughta push on with getting that all released. More than happy to reconsider if anyone disagrees. Until then re-milestoning this as 3.2.0.

**Comment by xordoquy** [comment]
I'd really love to tackle this one.
What about I come with a naive implementation of it ?

**Comment by tomchristie** [comment]
Welcome to. As it stands Iid otherwise be looking at this for 3.3 (Get a passable admin out the door early)

**Comment by xordoquy** [comment]
What's the planed timeframe for 3.2 ?

**Comment by tomchristie** [comment]
> What's the planed timeframe for 3.2 ?

I'll be off on paternity leave for a couple of weeks, imminently. I'd suggest we plan for end of July as the *latest* date. That's plenty of time to get a functioning admin in. Ideally a little sooner. Getting the admin interface in and usable has to be my priority right now, so I think most stuff that's milestoned will actually be 3.3, to follow ~2 months later (so end sept).

That'll close off the kickstarter funding and I'd suggest we simply focus on ongoing maintainance after that, possibly even with a formal feature freeze, at least until the issue list is nicely manageable.

Sound okay?

**Comment by xordoquy** [comment]
@tomchristie perfect. I'll try to push more effort with the bug fixing so you can focus on it.
I'll also start working on this one

**Comment by tomchristie** [comment]
@xordoquy Thanks! Closing of anything that's even remotely out of our current scope also a good plan.

**Comment by jamesbeith** [comment]
I'm investigating the idea of using DRF as a replacement for ModelForm in a traditional style Django project so this is something I'm certainly interested in.

**Comment by sheppard** [comment]
Is this related to #2148/#2682?

**Comment by mikofski** [comment]
I've made a small start at this, at least for single child lists, but it wouldn't yet work for nested lists of lists. But if called recursively, I think it might work.

I listed it on #2566 - basically I replace `ListField.get_value()` method with a custom list field that catches the `QueryDict` output, splits it, then uses the child's `to_representation()` method to cast it to the desired type.

**Comment by tomchristie** [comment]
Given other functionality priorities I don't particularly want this to block the 3.4.0 - removing the milestone for now.

**Comment by rvanlaar** [comment]
I believe this issue can be closed. The Django List Field is now supported and it's working for me.

**Comment by xordoquy** [comment]
@rvanlaar thanks for spotting this :)

**Comment by johnthagen** [comment]
@tomchristie @xordoquy What is the supported way to deal with the "Lists are not currently supported in HTML input." issue for nested serializers? Based on other issues I read, I thought maybe [html-json-forms](https://github.com/wq/html-json-forms) was the solution, but that doesn't seem to work. Only Raw JSON input seems to work.

The issue, is that if I want to test uploading a file as well as a nested serializer in the same serializer, there doesn't seem to be a way through the provided Web API. Raw JSON can't do the file, and the HTML form can't do the nested JSON.

**Comment by rpkilby** [comment]
#5702 disabled `ListField` and `DictField` in the browsable API as they require custom javascript/HTML widgets in order to be functional. That said, those fields still support form data - you just can't test it with the browsable API. I'm not sure how well they work with nested data though.
