### ISSUE TITLE
Improve nested objects in HTML forms.

### ISSUE THREAD

**Issue by frifri** [encode/django-rest-framework#2485]
**Edit** from @tomchristie: Updated title from 'DictField validation fail when using multipart content-type.'

---

Hey!

I just installed 3.0.4 and played around with the new `DictField`. It works pretty well using raw JSON. POST/PUT/PATCH requests always fail when using the browsable API with the following error:

```
"Expected a dictionary of items but got type `list`"
```

The value I send via the Browsable API form is:

![screen shot 2015-01-28 at 5 16 14 pm](https://cloud.githubusercontent.com/assets/714794/5950615/6b0197d0-a711-11e4-9c9f-7675cef99955.png)

Here is my model:

``` python
class Album(BaseGuidebookModel):
    name = HStoreField(validators=[validate_languages])

    def __unicode__(self):
        return self.name
```

Here is my serializer:

``` python
class AlbumSerializer(serializers.ModelSerializer):
    url = relations.HyperlinkedIdentityField(view_name='album-detail')

    class Meta:
        model = Album
```

Am I doing anything wrong?
Also, the initial value of a DictField is `[]` shouldn't it be `{}`?

**Comment by tomchristie** [comment]
Yeah we don't yet support HTML form input for DictField - we need to make that clear.

**Comment by thedrow** [comment]
How would you represent dictionaries in HTML?
A flat dictionary can be represented with a table but what about nested dictionaries?
The UI will become messy if the dictionary is very nested.

**Comment by zabracks** [comment]
My guess would be that you'd have some sort of an accordion-style form -- keeps the child at full-width (or close to it) with the rest of the HTML form, but adds a border and/or background to differentiate.

**Comment by jerzyk** [comment]
That was partially fixesd in c3425accdedb64e99238619f8f740bb547b2ecef

**Comment by KayLuke** [comment]
It seems the fix in c3425ac broke HTTP posts. This doesn't work anymore. The result is an empty field. Works in 3.2.3 but not 3.2.4

```
curl .... -d dict_field.key1=val1
```

**Comment by skolsuper** [comment]
+1 can confirm this is broken in 3.3.2.  Specifically, `field.get_value(data)` with `field.field_name == 'my_list'` and `data == {'my_list': ["{'foo':'bar'}", "{'baz':'qux'}"]}` returns an empty list.

**Comment by xordoquy** [comment]
The next step for this would be to have a case that can be added to the test suite and demonstrates the issue.

**Comment by tomchristie** [comment]
Given other functionality priorities I don't particularly want this to block the 3.4.0 - removing the milestone for now.

**Comment by wenzhihong2003** [comment]
can write a demo how to used DictField in serializer?
I can't find where is my code wrong. 
this is my code 

```python
from rest_framework import serializers
from django.http.request import QueryDict

class MyDictSerializer(serializers.Serializer):
    profile = serializers.DictField()


d = QueryDict("profile.username=example&profile.email=wen66@126.com")

ser = MyDictSerializer(data=MultiValueDict({'profile': d}))

ser.is_valid()
print(ser.validated_data['profile'])
```
It will print `{}`. But I think it will print 
```json
{'username': 'example', 'email': 'wen66@126.com'}
```

**Comment by frifri** [comment]
@wenzhihong2003 I am not quite sure what the context of this code is but If you want to keep using a `QueryDict` for `d`, you will have to drop the `MultiValueDict` and cast `d` as an actual `dict`.

Something like this will work:

```python
from rest_framework import serializers
from django.http.request import QueryDict

class MyDictSerializer(serializers.Serializer):
    profile = serializers.DictField()


d = QueryDict("profile.username=example&profile.email=wen66@126.com")

ser = MyDictSerializer(data={'profile': dict(d)})

ser.is_valid()
print(ser.validated_data['profile'])
```

**Comment by wenzhihong2003** [comment]
@frifri , thanks for your code. good luck!

**Comment by unclewizard** [comment]
A quick workaround that worked for me is:

```
class MyDictField(serializers.DictField):
    def get_value(self, data):
        return super(MyDictField, self).get_value(data).dict()
```

Then use MyDictField in place of DictField in the serializer.

**Comment by carltongibson** [comment]
I'm going to de-milestone this. We'll reassess after v3.7.
