### ISSUE TITLE
Improve handling of hidden fields in `HTMLFormRenderer.render_field`

### ISSUE THREAD

**Issue by carltongibson** [encode/django-rest-framework#2582]
Follow-up from #2580.

As per @tomchristie's [comment there](https://github.com/tomchristie/django-rest-framework/pull/2580#issuecomment-75213341):

> ...at some point we'll want to figure out a nice way to do this without using quirky private API...

The [offending line is here](https://github.com/tomchristie/django-rest-framework/pull/2580/files#diff-acb883ee0c042314f361a94aa00e5424R308):

``` python
        if isinstance(field._field, serializers.HiddenField):
             return ''
```

**Comment by tomchristie** [comment]
Thanks @carltongibson!
