### ISSUE TITLE
Field error is silenced

### ISSUE THREAD

**Issue by cool-RR** [encode/django-rest-framework#2635]
I had a field like this: 

```
book = rest_framework.fields.ReadOnlyField(source='cook',)
```

`book` was misspelled as `cook`, but instead of getting an error for that field not existing, the request ran, except the response didn't include a `book` key for the entries.

**Comment by tomchristie** [comment]
Fields with `required=False` end up also being optional in the output.
Suggested fix for this might be for us to only make them optional in the output with dict type inputs.
Object type inputs should always be required.

**Comment by alex-hutton** [comment]
Is this actually a problem of `serializers.to_internal_value()` silently disregarding fields in the payload which are not writable fields?

Presumably @cool-RR was submitting a payload with a `book` field, and the serializer was silently ignoring it as `book` was not a field defined on the serializer. If the unsupported field had been added to errors (eg `errors['book'] = 'This is not a supported field.'`) then this may have alerted him to the problem sooner.
