### ISSUE TITLE
Updates for ModelSerializer API docs.

### ISSUE THREAD

**Issue by catskul** [encode/django-rest-framework#2646]
Saw the announcement and looks like some great improvements. Thanks!

http://www.django-rest-framework.org/api-guide/serializers/

https://github.com/tomchristie/django-rest-framework/blob/master/docs/api-guide/serializers.md :1017

"Customizing the default fields"
Makes reference to a part of the 3.0 which has now been updated in 3.1.

**Comment by xordoquy** [comment]
Needs some hint on the new way to do it.

**Comment by xordoquy** [comment]
Fields to be documented (https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/serializers.py#L992
):

 - build_relational_field
 - build_nested_field
 - build_property_field
 - build_url_field

Noting that they return two-tuples of class and kwargs dict
And that they're a usful point if you want to build a generic ModelSerializer subclass that behaves in a slightly diff way throughout you app
Also highlighting that it may be considered advananced usage, and that users may want to simply rely on explicitly listing fields on serializer classes as an alternative

**Comment by tomchristie** [comment]
Out of date. We have documentation for those hooks now.
