### ISSUE TITLE
raise_errors_on_nested_writes doesn't allow list of Model Objects

### ISSUE THREAD

**Issue by cancan101** [encode/django-rest-framework#3192]
`raise_errors_on_nested_writes` throws an error if there is unhanded nested serialization on writes. It currently [checks for this if the data item is a "dict or a list"](https://github.com/tomchristie/django-rest-framework/blob/6e3ba202af01eee14665d97585c0ca6228c6622a/rest_framework/serializers.py#L701). I think this check should actually be a: "dict or a list _of dicts_".

As it is written down, I cannot write:

``` python
    def create(self, validated_data):
        tag_data = validated_data.pop('tags')
        validated_data['tags'] = self.fields.get('tags').create(tag_data)
        return super(MySerializer, self).create(validated_data)
```

I suggest changing the linked linked of code to:

``` python
(isinstance(validated_data[key], dict) or (isinstance(validated_data[key], list)
                                           and any(isinstance(x, dict) for x in validated_data[key])))
```

**Comment by tomchristie** [comment]
I think there's a valid issue to address here (but maybe not obviously *exactly* how to resolve) but first...

Don't use `super` there, write the method explicitly, and it'll be much more obvious. We do a whole bunch of additional checking in the default implementation that you simply don't need. So...

    def create(self, validated_data):
        # Typically, aim for something more like this...
        tag_data = validated_data.pop('tags')
        validated_data['tags'] = Tag.objects.create(tag_data)
        return MyObject.objects.create(validated_data)

The `MyObject.objects.create(...)` is essentially *all* that the default method implementation does, with the single proviso that any m2m relationships are set after that.

Coming back to the point tho...

Yes, there are clearly valid lists that we could handle automatically, and in fact also dicts too (I suspect we'll bump into those more as folks use JSONField more commonly) - not clear how we should handle those, but *may* be that we actually have to check the fields on the serializer for subclasses of `Serializer`, and tally those up against the validated_data

**Comment by cancan101** [comment]
I actually am fine with calling to the `super` and having it do those additional checks and handle the m2m relationship, which this is. I have just made the list of dicts (data on the wire) into a list of models so the check would pass with the patch above.

**Comment by auvipy** [comment]
as the issue is 5 years+ Old and django+DRF have evoled a lot in the meantime, what would be the current resolution of the issue?

**Comment by tomchristie** [comment]
Answering that question.
