### ISSUE TITLE
Easily add/validate etags.

### ISSUE THREAD

**Issue by schinckel** [encode/django-rest-framework#32]
Django has an awesome etag/condition/last_modified decorator. It doesn't work with the d-r-f class-based views, as you cannot decorate 'get' with them. Because get returns an object that is not an http response, there is no way to add the etag header to the response.

I would like to see a way to do this from within d-r-f. I'm thinking something along the lines of an overridable method on a resource, or a view (or a mixin) that can be used to generate the etag.

The other way of doing it in django is to use the middleware, but it cannot shortcut running the body of the view altogether like the decorator can.

**Comment by mbox** [comment]
Unfortunately the default implementation and documentation on the Etag functionality in drf-extensions is simply wrong and dangerously buggy. It changes the Etag if the *request* changes, not if the *response* changes. Which is exactly what you want for server-side caching, and exactly what you don't want for an Etag.

**Comment by xordoquy** [comment]
@mbox the best thing would be to open an issue about this on drf-extensions or if you think it's a DRF "core" issue open on here. Please note that a failing test would be a good start for us to look at the issue.

**Comment by pkainz** [comment]
@mbox @xordoquy 
I just submitted a PR to drf-extensions (https://github.com/chibisov/drf-extensions/pull/171) that allows optimistic concurrency control for manipulating resources via the DRF API. It's using a semantic hash of all object fields and I included a test app for demonstration purposes. It has been tested against DRF>=3.3.x and django>=1.9 with Python 2.7, 3.4, 3.5.

**Comment by jozo** [comment]
Just a note for the future readers - I've created small package to use conditional decorators from Django together with DRF. So if you are interested:
https://github.com/jozo/django-rest-framework-condition
