### ISSUE TITLE
Show meaningful error when `filter_fields` is not a list or tuple

### ISSUE THREAD

**Issue by kumar303** [encode/django-rest-framework#3240]
With a view set that looks roughly like this:

```
class TransactionViewSet(mixins.RetrieveModelMixin, GenericViewSet):
    queryset = Transaction.objects.all()
    filter_fields = ('some_field')
```

I see this traceback when making a GET request:

```
Traceback (most recent call last):
  File "/opt/rh/python27/root/usr/lib64/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  ...
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/rest_framework/generics.py", line 179, in filter_queryset
    queryset = backend().filter_queryset(self.request, queryset, self)
  File "/srv/solitude/solitude/filter.py", line 22, in filter_queryset
    .filter_queryset(request, queryset, view))
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/rest_framework/filters.py", line 62, in filter_queryset
    filter_class = self.get_filter_class(view, queryset)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/rest_framework/filters.py", line 52, in get_filter_class
    class AutoFilterSet(self.default_filter_set):
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django_filters/filterset.py", line 171, in __new__
    raise TypeError("Meta.fields contains a field that isn't defined "
TypeError: Meta.fields contains a field that isn't defined on this FilterSet
```

The error is that the tuple was coded wrong. It should be `filter_fields = ('some_field',)` or it should be a list.

I know this is a common mistake in Python but the error message is pretty confusing and didn't help me at all during the embarrassing amount of time I spent tracking it down. A string is still iterable but it wouldn't be sane to pass in a string for this value. I think it would be a quick win to check if `filter_fields` is a list or tuple and show a more meaningful error to help developers track down the problem.

**Comment by kumar303** [comment]
I guess if nothing else you could close this bug and let it live on as a google egg :)

**Comment by xordoquy** [comment]
I guess we could set an assert to make sure we have a list / tuple / iterable at some point to avoid this.

**Comment by kumar303** [comment]
a string would still be iterable:
````
>>> filter_fields = ('some_field')
>>> iter(filter_fields)
<iterator object at 0x105c48310>
````
^ no exception

**Comment by xordoquy** [comment]
@kumar303 This is a usual issue with strings yeah but I still think we should allow iterable - other than strings ;)

**Comment by kumar303** [comment]
right, anything but strings should be allowed: lists, tuples, generators...

**Comment by ugurunver** [comment]
Maybe it would be helpful to use six.string_types while validating filter_fields. I think, you can raise a useful exception message even if you consider that 'filter_fields' is invalid.

**Comment by rpkilby** [comment]
Hi all, the `DjangoFilterBackend` has been moved to the django-filter packge. If this is still an issue, please open a new ticket over there.
