### ISSUE TITLE
File fields not displaying correctly in edit form of admin and api browser.

### ISSUE THREAD

**Issue by mcastle** [encode/django-rest-framework#3264]
The edit field shows `No file selected`, even if there's a file associated with the object.

**Comment by kevin-brown** [comment]
I _think_ this is caused by the browser, you generally can't pre-load file fields in HTML forms with a value.

**Comment by mcastle** [comment]
The browser should still be able to do what Django Admin does, which is to provide a link to the url of the file.

**Comment by tomchristie** [comment]
Agree that it does sound like there's scope for improvement.
Some simple screenshots of both the django admin behavior and the browsable API behavior would help make this ticket more obvious.

**Comment by mcastle** [comment]
Sure. The browsable API, admin format, currently looks like this:

<img width="620" alt="screen shot 2015-08-12 at 10 44 50 am" src="https://cloud.githubusercontent.com/assets/3880707/9228717/5a7a2194-40df-11e5-972e-6a95fa4c8f6a.png">

The browsable API, api format, currently looks like this:
<img width="479" alt="screen shot 2015-08-12 at 10 47 49 am" src="https://cloud.githubusercontent.com/assets/3880707/9228800/b30ba33c-40df-11e5-9e99-1290eee140de.png">

A suggestion is to echo the Django Admin:
<img width="535" alt="screen shot 2015-08-12 at 10 45 27 am" src="https://cloud.githubusercontent.com/assets/3880707/9228720/5cba292c-40df-11e5-9fec-d44d0bbb4664.png">

**Comment by tomchristie** [comment]
Yup, I can get behind that.

**Comment by mcastle** [comment]
Cool!
