### ISSUE TITLE
has_object_permission with function based views

### ISSUE THREAD

**Issue by Miserlou** [encode/django-rest-framework#3269]
Apparently, there is no way to use has_object_permission with function based views that use the @api_view decorator.

Ideally, there should be a way to do this, but if that won't be provided, then the docs should be reflected to indicate that CBVs and FBVs are not functionally equal in this regard.

**Comment by xordoquy** [comment]
I think this is already mentioned in the [documentation](http://www.django-rest-framework.org/api-guide/permissions/#custom-permissions):

> Note: The instance-level has_object_permission method will only be called if the view-level has_permission checks have already passed. Also note that in order for the instance-level checks to run, the view code should explicitly call .check_object_permissions(request, obj). If you are using the generic views then this will be handled for you by default.

**Comment by Miserlou** [comment]
But you _cant_ call ".check_object_permissions(request, obj)", which the instructions tell you to do. That's exactly what I want the ability to do.

**Comment by xordoquy** [comment]
Right

**Comment by viniciuschiele** [comment]
I think the function based view could receive by parameter the view instance.

e.g:

```python
@api_view(bind=True) # bind=True means that the view instance should be passed by parameter
def add_user(self): # self is the view instance
      self.check_object_permission(obj)
````

**Comment by xordoquy** [comment]
@viniciuschiele this won't happen. You should go with generic class based views if you need that.

**Comment by tomchristie** [comment]
I think for now we should simply document that they don't support automagic 
 object level permissions, and that any object level perms checking should be done explicitly instead, raising PermissionDenied
