### ISSUE TITLE
Nested ListField serializer errors should include object reference

### ISSUE THREAD

**Issue by erikcw** [encode/django-rest-framework#3274]
When validation errors happen in nested ListField serializers -- an OrderedDict is returned for the ListField containing the nested errors.  However, it doesn't indicate which object in the list caused the error.  

For example, my nested serializer has a URLField, if I pass in a list of 10 objects -- the error doesn't indicate which of the 10 objects contains the error.  

``` python

class ChildSerializer(serializers.Serializer):
   url = serializers.URLField()
   uuid = serializers.UUIDField()
   other_fields = serializers.CharField() # many more...

class MySerializer(serializers.ModelSerializer):
    # my_nested_list_field is a JSONfield on the Django model
    my_nested_list_field = serializer.ListField(child=ChildSerializer())

data = {#other fields...,
            'my_nested_listfield': [
           {"url": "some invalid url", "other_fields": "MANY"},
           {"url": "http://www.google.com/", "other_fields": "MANY"},
            #9 (n) more dicts...
            ]
}

x = MySerializer(data=data)
x.is_valid()

x.errors
{'my_nested_listfield': OrderedDict([('url', [u'Enter a valid URL.'])])}
# did this error occur in dict #1, #5, #10????  Start trawling through the list looking for the bad URL...
```

Nested errors should probably contain some metadata to indicate which item(s) failed validation so that useful errors can be displayed to the client.

Something like:

``` python
{'my_nested_listfield': OrderedDict([('url', [u'Enter a valid URL.'] "_meta_ref": "OBJECT_123")])}
# Oh, I see, the error occured on OBJECT_123 -- this will be quick and easy to debug
```

Where `_meta_ref` is generated by an overrideable method on the child serializer.  It could default to the object `url` -- but in this case I would use an internal id that is meaningful to my application, like the `uuid`

**Comment by tomchristie** [comment]
Get the general idea of this, but not clear what a nice way to do this would be.

**Comment by rpkilby** [comment]
Hi @erikcw - would #5655 solve this for you?

**Comment by rpkilby** [comment]
This is a fairly old issue, but I think this use case is generally covered by #5655. In short, there won't be an object `_meta_ref` (it's not exactly clear what that value should be). Instead, errors will be a dict of errors, keyed by the failing value's index (or in the case of `DictField`, the value's key). For example:

```python
>>> class MySerializer(serializers.ModelSerializer):
        field = serializer.ListField(child=serializers.IntegerField())
>>> s = MySerializer(data={'field': [1, 2, 'foo'']})
>>> s.is_valid()
False
>>> s.errors
ReturnDict([('field', {2: ['A valid integer is required.']})])
```
