### ISSUE TITLE
Docs on reasons for using Django REST framework vs Django

### ISSUE THREAD

**Issue by tomchristie** [encode/django-rest-framework#3281]
As per https://twitter.com/pydanny/status/633129209045479424

**Comment by tomchristie** [comment]
I've put together some muddled comments here: https://www.reddit.com/r/django/comments/3h9oj8/what_really_are_the_differences_between_django/cu5pzu9

**Comment by SalahAdDin** [comment]
:+1:

**Comment by pydanny** [comment]
Here's another request: https://www.facebook.com/groups/python.django/permalink/974382939279619/

I should track them here to motivate myself to formalize @tomchristie's thoughts into real docs.

**Comment by tomchristie** [comment]
Thanks @pydanny! Please do yup!

**Comment by tomchristie** [comment]
Going to close this off as stale.
Our homepage does an okayish job of this, and we don't have a clear "we should update *this* bit of page" to work against. Happy to consider suggestions, tho. Could be re-opened at a later date.
