### ISSUE TITLE
PageNumberPagination without count

### ISSUE THREAD

**Issue by eloycoto** [encode/django-rest-framework#3307]
Hi, 

PageNumberPagination works well when the table it's small, but when the table it's big and the amount of result are big django.core.paginator.Paginator always make count for the full queryset.

https://github.com/django/django/blob/master/django/core/paginator.py#L86

Cursor pagination works great, but orderingFilter will be lost and it's not useful at all in our case. 

Any way to clean this count property from the PageNumberPagination? 

Regards.

**Comment by tomchristie** [comment]
We've got plenty of scope for customizing pagination classes.
No reason for someone to not take this on as a third party package, or to progress this issue with an example of the most minimal way to override the existing behaviour by subclassing the pagination class.
