### ISSUE TITLE
Better documentation interlinking.

### ISSUE THREAD

**Issue by curtisforrester** [encode/django-rest-framework#3322]
Feedback: Per your request for feedback, one thing that I still do is try to click a red text code item in the docs to navigate to the API for it. For example, it would be nice for the **APIView** to link to the details.

![screen shot 2015-08-24 at 9 36 22 am](https://cloud.githubusercontent.com/assets/5033139/9441452/255f05c4-4a44-11e5-8ef0-98d8b0a04156.png)

**Comment by tomchristie** [comment]
Difficult for us to do right now, but certainly would be an improvement, yup.

**Comment by curtisforrester** [comment]
I understand. I also understand I need to stop compulsively clicking them :) *"Doctor doctor it hurts when I bang my head against the wall..."*

**Comment by jezeniel** [comment]
Hi guys, are you still aiming to do this? I could help out on this one.
