### ISSUE TITLE
AdminRenderer does not correctly link to detail page if Serializer is not HyperlinkedModelSerializer

### ISSUE THREAD

**Issue by cancan101** [encode/django-rest-framework#3338]
If the `Serializer` in the view is `ModelSerializer` rather than a `HyperlinkedModelSerializer`, the arrow link to the detail page does not work (it just points to the list page).

![screen shot 2015-08-27 at 15 56 35](https://cloud.githubusercontent.com/assets/647359/9523952/506e03f4-4cd4-11e5-9487-1c34ec8a86bd.png)

**Comment by tomchristie** [comment]
Milestoning to consider. May well be that we *only* support the admin fully with hyperlinks, since we're need them when rendering the interface.

**Comment by carltongibson** [comment]
I'm going to de-milestone for now. We can reassess after 3.7
