### ISSUE TITLE
AdminRenderer breaks with nested objects

### ISSUE THREAD

**Issue by parisk** [encode/django-rest-framework#3340]
Attempting to render an API resource with nested objects with the AdminRenderer results in broken HTML. While I am not sure what should be the actual output of an embedded resource in such a rendering, I believe that we could use the str representation of the embedded serializer.
### Broken admin view

![screenshot 2015-08-27 17 53 04](https://cloud.githubusercontent.com/assets/1188592/9523967/251bc31a-4ce5-11e5-8fa9-c9e3cd4f2cb7.png)
### Browserable API view

![screenshot 2015-08-27 17 53 29](https://cloud.githubusercontent.com/assets/1188592/9523984/30816f3e-4ce5-11e5-944d-f81b36d653d8.png)
### serializers.py

``` python
from invoices import models
from rest_framework import serializers


class InvoiceItemSerializer(serializers.HyperlinkedModelSerializer):

    class Meta:
        model = models.InvoiceItem
        fields = (
            'id', 'url', 'invoice', 'description', 'price', 'discount'
        )
        extra_kwargs = {
            'url': {'view_name': 'invoice-item-detail'}
        }


class InvoiceSerializer(serializers.HyperlinkedModelSerializer):

    item_listing = serializers.HyperlinkedIdentityField(
        view_name='nested-invoice-item-list',
        read_only=True,
        lookup_field='id',
        lookup_url_kwarg='invoice_id'
    )

    class Meta:
        model = models.Invoice
        fields = (
            'id', 'url', 'time', 'customer', 'status', 'price', 'currency',
            'transaction_id', 'other_info', 'item_listing'
        )
```

**Comment by dursk** [comment]
Yeah, something odd is going on here. Was playing around with it a bit myself. This code:

##### serializers.py
```python
class AuthorSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = Author


class BookSerializer(serializers.HyperlinkedModelSerializer):
    author = serializers.HyperlinkedIdentityField(
        view_name='author-detail',
    )

    class Meta:
        model = Book
```

Renders correctly in the browsable API:

<img width="1169" alt="screen shot 2015-10-25 at 12 31 48 pm" src="https://cloud.githubusercontent.com/assets/5231538/10716597/7137b850-7b14-11e5-80cd-5ff224306328.png">

But when using the `AdminRenderer`, it's displaying the related `Author` object as a `Book` object (although the underlying link is correct).

<img width="1073" alt="screen shot 2015-10-25 at 12 34 07 pm" src="https://cloud.githubusercontent.com/assets/5231538/10716608/c0de4ff4-7b14-11e5-8894-f81113c65b2f.png">

**Comment by rocktavious** [comment]
+1 want to know more and how to fix

**Comment by xordoquy** [comment]
You are likely missing a representation of your model (meaningful __str__)

**Comment by auvipy** [comment]
In that case is this issue really a valid bug?

**Comment by carltongibson** [comment]
I'm going to close this as stale. Happy to re-open if this comes up again and we can pin down the issue a bit further.
