### ISSUE TITLE
Improve Documentation for format in Renderer

### ISSUE THREAD

**Issue by cancan101** [encode/django-rest-framework#3387]
1. [The docs](http://www.django-rest-framework.org/api-guide/renderers/) show a confusing `.` as the prefix for the format. For example:

> .format: `'.html'`

whereas the class has:

``` python
class TemplateHTMLRenderer(BaseRenderer):
...
    format = 'html'
```
1. The docs don't give a suggestion as to what should `format` be set to when the `media_type = 'image/*'` or `*/*`.

**Comment by tomchristie** [comment]
1. Sounds like it needs a docs pull request, yup.
2. What change would you suggest here? Either you'll need a custom conneg class, in order to handle multiple possible format extenstions, or you could use something generic, eg `.img`
