### ISSUE TITLE
update documentation with options view method since version-3.2

### ISSUE THREAD

**Issue by mikofski** [encode/django-rest-framework#3489]
The documentation topic, [documenting your api](https://github.com/tomchristie/django-rest-framework/blob/3.2.4/docs/topics/documenting-your-api.md) describes overriding the `metadata` view method as described in the [version 3.0 updates notes](https://github.com/tomchristie/django-rest-framework/blob/3.2.4/docs/topics/3.0-announcement.md). However since commit f4b1dcb167be0bbdaae2cc2a92f651536896dc16 I think this method has been changed to `options`.

Here is a patch:

```
--- documenting-your-api.md.orig    2015-10-12 14:52:15.036110300 -0700
+++ documenting-your-api.md 2015-10-12 14:52:45.168944300 -0700
@@ -81,11 +81,11 @@

 You can modify the response behavior to `OPTIONS` requests by overriding the `metadata` view method.  For example:

-    def metadata(self, request):
+    def options(self, request):
         """
         Don't include the view description in OPTIONS responses.
         """
-        data = super(ExampleView, self).metadata(request)
+        data = super(ExampleView, self).options(request)
         data.pop('description')
         return data
```

**Comment by jpadilla** [comment]
There's definitely something valid here but I think we should probably update that section. So it is possible to change what the view's [`options()`](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/views.py#L471) does; by default it'll do the metadata dance.

So to correct that example we could do something like:

```python
def options(self, request, *args, **kwargs):
    """
    Don't include the view description in OPTIONS responses.
    """
    meta = self.metadata_class()
    data = meta.determine_metadata(request, self)
    data.pop('description')
    return data
```

Thoughts?
