### ISSUE TITLE
Can a GPG key or fingerprint be added for the project?

### ISSUE THREAD

**Issue by micahhausler** [encode/django-rest-framework#3548]
Can you all add a GPG key or fingerprint (or a list of the contributors' keys fingerprints) to the README and `docs/index.md`?

**Comment by xordoquy** [comment]
Out of curiosity, what would it bring ? Do you have any link on why we should do that ?

**Comment by micahhausler** [comment]
Assurance that only the intended recipients read the message. 

Django, for one, does it. https://docs.djangoproject.com/en/1.8/internals/security/#reporting-security-issues

As does Python https://www.python.org/news/security/

While Rest Framework isn't as broadly used as Django or Python, it still is a widely used project. Just looking at pypi, DRF has 38% as many the downloads in the last month as Django. (314189/815013)

**Comment by tomchristie** [comment]
Great idea, yup.

Also...

> Just looking at pypi, DRF has 38% as many the downloads in the last month as Django.

Wow.

**Comment by foresmac** [comment]
Noice.

**Comment by tomchristie** [comment]
@micahhausler Best pointers on where to start?

**Comment by micahhausler** [comment]
Check out [gpg tools](https://gpgtools.org/) for OS X, or [gpg4win](http://www.gpg4win.org/) for windows.

GPG tools for OS X also integrates with OS X's built-in mail application, so if you use that it is an easy interface. 

Once you have created a key, you'll push it up to a key server, and it'll get synced to the global SKS list:
you'll be able to view your keys at (just for example) keyserver.ubuntu.com, pgp.mit.edu, etc. 

After you publish a key, all you need to do for people to find it is announce your key's fingerprint in a known place.

One site that some people use to also verify their key is https://keybase.io/. I believe there are people on that site you are familiar with (https://keybase.io/freakboy3742 among others) I'll go ahead and send you an invite, but you're not at all obligated to use it.

One other feature is that other people can 'sign' your key to verify that it belongs to you. The GPG tools (for OS X) interface for this is very simple.

If you need any further explanation, please let me know. I'm happy to help!

**Comment by xordoquy** [comment]
Note for the release process:
> You may sign your uploads with GPG using the "--sign" argument to "python setup.py upload".

https://pypi.python.org/security

**Comment by jpadilla** [comment]
https://keybase.io/jpadilla

**Comment by micahhausler** [comment]
Also may be of interest: signing git tags https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work

**Comment by xordoquy** [comment]
Note to update the release process with twine:
http://python-packaging-user-guide.readthedocs.org/en/latest/distributing/#upload-your-distributions

**Comment by brainwane** [comment]
Speaking of [Twine](http://twine.readthedocs.io/): I'm one of its maintainers. I was checking out [the libraries.io usage list for twine](https://libraries.io/pypi/twine/usage) and happened to notice that your `requirements.txt` file specifies an old version. The new version of Twine is 1.10.0. If there's we can do to make your upgrade path easier, please mention it here or file an issue?

**Comment by carltongibson** [comment]
@brainwane It's probably quicker all round  for you to just open a PR with the proposed change (here and on other repos you're commenting on). But yes, again, updating is no problem I think.
