### ISSUE TITLE
Document integration with Django's caching framework.

### ISSUE THREAD

**Issue by jmagnusson** [encode/django-rest-framework#370]
As requested by @tomchristie. `django-rest-framework` can use Djangos internal caching mechanism to cache API responses. Document how it can be enabled for DRF (basically it works just like it would in a vanilla Django view, but it might be worth letting people know that DRF supports it).

**Comment by xordoquy** [comment]
@tomchristie any tip on where we should put that ? May be a new entry in the topics ?

**Comment by tomchristie** [comment]
@xordoquy Most likely, yes.

**Comment by adamn** [comment]
It seems like this small [cache documentation](http://www.django-rest-framework.org/api-guide/throttling/#setting-up-the-cache) is sufficient to close this ticket.

**Comment by tomchristie** [comment]
@adamn That's a different aspect to the intent of this ticket.
