### ISSUE TITLE
Class-based Validator with set_context - not thread safe 

### ISSUE THREAD

**Issue by AbstractVisions** [encode/django-rest-framework#3713]
set_context method in Validation class - change internal state of callable instance in process.
DRF Field class override **deepcopy** for create shared "validators".
It means, that validators must be a ThreadSafe, but with set_context it is not so... 

---

Note from @tomchristie: See also #3863, #3870

**Comment by xordoquy** [comment]
At first sight I'll second this analysis.
Validators do hold the instance while not copied which means that they indeed aren't thread safe.

**Comment by xordoquy** [comment]
Test case for the above issue (test_validators.py):

    def test_is_thread_safe(self):
        from rest_framework.validators import UniqueValidator

        class UniquenessSerializer(serializers.ModelSerializer):
            username = serializers.CharField(max_length=100, validators=[UniqueValidator(queryset=UniquenessModel.objects.all())])

            class Meta:
                model = UniquenessModel

        data2 = {'username': 'other'}
        serializer2 = UniquenessSerializer(data=data2)
        data1 = {'username': 'existing'}
        serializer1 = UniquenessSerializer(data=data1)
        assert not serializer1.is_valid()
        assert serializer2.is_valid()
        validator1 = serializer1.fields['username'].validators[0]
        validator2 = serializer2.fields['username'].validators[0]
        assert isinstance(validator1, UniqueValidator)
        assert isinstance(validator2, UniqueValidator)
        assert id(validator1) != id(validator2)
        assert validator1.instance != validator2.instance

**Comment by AbstractVisions** [comment]
This feature used in UniqueValidator's and could make problems in some cases...
I think the simplest decision to exclude a mutable status - to make context injection in the functional style instead of assignment of properties. Same decision  is close to Django ideology 
For support of backward compatibility when using set_context it is possible to use as "self" every time the new created simple object and a binding its properties with descriptors.
If it is actual, I could prepare a concept of decision

**Comment by AbstractVisions** [comment]
The little strange test...
Django validators shall be immutabel and can quite be identical in different objects

**Comment by xordoquy** [comment]
I don't think the context can be passed in a functional style.
I know it's more like what Django does but at the same time it makes things way harder for forms and fields for example.
Need to think again about this.

A few things to note:
- Validators are isolated as long as they are automatically extracted from the model constraints.
- Django validators are thread safe

The only possible case where this could be an issue is for a DRF explicitly set validator.

**Comment by AbstractVisions** [comment]
Indeed...ok. Then two simple ways seem:
1. __good__. set_context return the dict of context, that pass in `__call__` method of Validator as addition parametr `context=...`.  Pros - thread safe, Cons - that may be  some backward compatibility issues
2. __bad__. create another "ugly hack" in `__deepcopy__` method of DRF Field class: 
    if specific validator has a set_context attribute, then  use native `deepcopy` to it instead of sharing.
   And add to doc's anything like that: Validators with set_context mast be able to use 'deepcopy'

**Comment by skyjur** [comment]
> 1. good. set_context return the dict of context, that pass to __call__ method of Validator as addition parameter context=.... Pros - thread safe, Cons - that may be some backward compatibility issues. Backward compatibility problem can be solved with desctiptors

For me having "set_context/get_context" seems to be unecesary more complicated compared to passing serializer instance directly to validator function

**Comment by tomchristie** [comment]
Tempting.

**Comment by carltongibson** [comment]
I'm going to de-milestone this for now. We can reassess after 3.7. 

(Obviously to see a solution...)

**Comment by auvipy** [comment]
not to make any unnecessary noise here (which I am infamous of), can we expect issues leveled as a bug in DRF to get some priority in DRF 3.11.x series? Is there any way that needs help? Coding, Developers time, sponsors? what are the blocker for them?

**Comment by tomchristie** [comment]
Will look into this as part of #6172

**Comment by rpkilby** [comment]
Closing, as this looks like it's superseded by #5760 (which is addressed by #6172).
