### ISSUE TITLE
Adding "rest_framework" to settings.py changes translations of gettext

### ISSUE THREAD

**Issue by guettli** [encode/django-rest-framework#3735]
In django the string "This field is required." gets translated to the german string "Dieses Feld ist zwingend erforderlich."

As soon as I add "rest_framework" to the settings.py the german string changes to "Dieses Feld ist erforderlich."

The german word "zwingend" is missing.

You don't need to understand the german words.

But why does this happen?

Here is the django po file translation:

https://github.com/django/django/blob/master/django/conf/locale/de/LC_MESSAGES/django.po#L611

Where does the other translation come from?

I could not find a po-file in the repo of django-rest-framework

Why does this sentence get translated twice? One time in django, one time in the rest-framework?

**Comment by xordoquy** [comment]
The Django translation engine doesn't take into account strings that are already translated as part of another application.
Translations are managed by Transifex.
Thanks for the report, we will see if we can avoid translating strings that are already part of the Django package.

**Comment by xordoquy** [comment]
The string in question is there:
https://www.transifex.com/django-rest-framework-1/django-rest-framework/viewstrings/#de/djangopo/39237465?q=This%20field%20is%20required

**Comment by claudep** [comment]
One possible workaround (completely untested): create a `django_trans("My string")` utility which simply returns ugettext(string).

**Comment by guettli** [comment]
@claudep In my case _('...') returns the translation from the rest-framework. But I would like to get the translation from django. I guess ugettext(string) works the same: the rest-framework translation gets returned. I guess I am missing something. How to create `django_trans()`?

**Comment by claudep** [comment]
My suggestion was not for your code, but for rest-framework itself, so the string wouldn't be extracted in DRF translation catalogs.
