### ISSUE TITLE
Customizing Browseable API when using AdminRenderer - missing docs on using admin.html

### ISSUE THREAD

**Issue by scholtalbers** [encode/django-rest-framework#3795]
The docs at http://www.django-rest-framework.org/topics/browsable-api/#customizing describe that one should create an api.html template to customize the browseable api. However, when using the AdminRenderer the template admin.html needs to be used/customized. This is missing from the docs.

**Comment by rocktavious** [comment]
+1

**Comment by tomchristie** [comment]
We might consider proactive docs pull requests.
