### ISSUE TITLE
Use Pandoc to publish RestructuredText to PyPI

### ISSUE THREAD

**Issue by pydanny** [encode/django-rest-framework#3817]
A little call out to Pandoc during the `publish` setup.py command would mean this:

![screen shot 2016-01-08 at 6 49 35 pm](https://cloud.githubusercontent.com/assets/62857/12213963/abb63344-b638-11e5-9882-11d13fe809af.png)

would look more like: 

![screen shot 2016-01-08 at 6 50 59 pm](https://cloud.githubusercontent.com/assets/62857/12213970/cdad432a-b638-11e5-95a8-36323af1d04a.png)

If this is something wanted, I'm more than happy to make the pull request.

**Comment by jpadilla** [comment]
I'd be ok if we just had moved our `README.md` to reStructuredText instead. That file only changes when a new version is released.

**Comment by tomchristie** [comment]
@pydanny sounds good. I'd probably rather see/review that first, before considering using .rst for the README

**Comment by mblayman** [comment]
As reported in #4012, the pandoc reST output is not rendering properly on PyPI. PyPI doesn't really report these errors easily so here is some output that can hopefully help resolve the problem. On other projects, when I've resolved any errors from rst2html, the page starts to render properly on PyPI.

```bash
python setup.py --long-description | rst2html.py > /dev/null
<stdin>:110: (WARNING/2) Cannot analyze code. Pygments package not found.
<stdin>:145: (WARNING/2) Cannot analyze code. Pygments package not found.
```
Installing Pygments made the errors go away.

**Comment by xordoquy** [comment]
@mblayman We already have a fix for that, see the related issues list.

**Comment by mblayman** [comment]
I ran the above command from the stable branch that includes the merged PR referenced in issues list. I did some triage and thought this might be new information.

My apologies if you were already aware of this.
