### ISSUE TITLE
Raising ValidationError from Serializer.to_internal_value() with error message(s) as list causes ValueError

### ISSUE THREAD

**Issue by ryochiji** [encode/django-rest-framework#3864]
``` python
>>> from rest_framework.serializers import Serializer
>>> from rest_framework.exceptions import ValidationError
>>> class FooSerializer(Serializer):
...   def to_internal_value(self, data):
...     raise ValidationError(['foo error'])
... 
>>> foo = FooSerializer(data={})
>>> foo.is_valid(raise_exception=True)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/altschool/vishnu-backend/lib/python2.7/site-packages/rest_framework/serializers.py", line 221, in is_valid
    raise ValidationError(self.errors)
  File "/usr/local/altschool/vishnu-backend/lib/python2.7/site-packages/rest_framework/serializers.py", line 509, in errors
    return ReturnDict(ret, serializer=self)
  File "/usr/local/altschool/vishnu-backend/lib/python2.7/site-packages/rest_framework/utils/serializer_helpers.py", line 20, in __init__
    super(ReturnDict, self).__init__(*args, **kwargs)
  File "/Users/ryochiji/.pyenv/versions/2.7.8/lib/python2.7/collections.py", line 52, in __init__
    self.__update(*args, **kwds)
  File "/usr/local/altschool/vishnu-backend/lib/python2.7/_abcoll.py", line 566, in update
    for key, value in other:
ValueError: too many values to unpack
```

This seems to happen because `Serializer.errors` passes [`self._errors` to ReturnDict](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/serializers.py#L506) without type-checking the way [`ListSerializer.errors` does](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/serializers.py#L678).

**Comment by laz2** [comment]
Breaking changes in usage [self.errors](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/serializers.py#L221) instead self._errors (as is in previous versions).
Possible fix: move [value = self.to_internal_value(data)](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/serializers.py#L557) under try-except to proper exception converting.

PS. May i raise ValidationError from to_internal_data?

**Comment by laz2** [comment]
Original [to_internal_value](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/serializers.py#L567) always raises exception in dict-format:
`
raise ValidationError({
    api_settings.NON_FIELD_ERRORS_KEY: [message]
})
`

**Comment by maryokhin** [comment]
This should probably at least be mentioned in the docs somewhere?

**Comment by mikeengland** [comment]
I'm also experiencing this issue. Raising a validation error inside to_internal_value throws the same exception as above. This can be handled outside to_internal_value so it isn't a blocker by any means.

**Comment by practual** [comment]
This issue can also be seen if you pass `data=None` to a serializer, e.g.:
```
class MySerializer(serializers.Serializer):
    name = serializers.CharField()

    class Meta:
        fields = ('name',)

serializer = MySerializer(data=None)
serializer.is_valid()
serializer.errors
>>> ValueError: too many values to unpack (expected 2)
```

I believe this error could be avoided by wrapping `self.validate_empty_values(data)` with a check for `self.parent` to determine whether the serializer is nested or not. If the serializer is not nested, it should raise the error as a non-field error.

**Comment by carltongibson** [comment]
I'm going to de-milestone for now. We can reassess after v3.7

**Comment by rpkilby** [comment]
Hi all, I've opened #5466 with a docs clarification. In short, the recommended approach is:

- Override `.validate()` when you want  to perform object-level validation. You can raise `ValidationError('msg')` and `ValidationError(['msg 1', 'msg 2'])` as expected.
- Override `.to_internal_value()` when you need to alter *how* data is deserialized. If deserialization fails, it's expected that you raise a `ValidationError` with a dictionary mapping field names / `settings.NON_FIELD_ERRORS_KEY` to a list of error messages.

**Comment by tomchristie** [comment]
#5466 Is a good start, but I think we want to restructure that slightly.

The opening paragraphs for that section might be the right place make your validate vs to_internal_value point, tho I'm open to discussion here.
