### ISSUE TITLE
Branch management

### ISSUE THREAD

**Issue by xordoquy** [encode/django-rest-framework#3916]
I'm a bit annoyed with the current branch management with DRF at the moment.

I'd like to drop master for the stable branch.

What I have in mind is and basing myself on 3.3.2 being the latest stable:
- master becomes the base branch for the next minor release (say 3.4.0) with new features & deprecation.
- create a "stable" 3.3.x branch which will be used for all the micro release (bug fixes only).
- have an exploratory 4.x branch for the next major if any.

The major advantage is that we will improve a lot stability by keeping the current stable release restricted to bug fixes and have new micro for new features.
The major concern will be it'll require a bit more work to back port things

**Comment by tomchristie** [comment]
Might be a good idea, yes.

**Comment by jpadilla** [comment]
Interesting. Would love to understand a bit more about the problem with the current setup and how this improves it?

**Comment by xordoquy** [comment]
Use case example: #3915 where it was proposed to drop Django 1.7 support.
Can't merge this in master yet it's not a good things to postpone those PR until they are totally out of date.

Another point that annoys me a lot is small changes going into micro releases where it should be in micro.

**Comment by carltongibson** [comment]
In the past we did it the other way, so #3915 would go against a `3.4` release branch: I'm sure it's just different ways of holding it, but, does that not work?

**Comment by xordoquy** [comment]
The downside of having an dev branch that isn't master is that we'll loose time asking people to do a PR against X.Y branch instead of master.
On the other hand, merging things into master and cherry picking bug commits to the stable branch will be simpler IMHO.

**Comment by carltongibson** [comment]
Fine. _It's easier_ is perfect. Is there a way of bootstrapping this without (you) having to do a whole load of work? (A quick tag, and "from now...")

**Comment by xordoquy** [comment]
@carltongibson we would simply need a branch - say 3.3.x - in which fixes will be backported. Other things remains unchanged.

**Comment by carltongibson** [comment]
Ah, sorry, yes — so the concern is the ongoing work, not the set up. I understand.

It's hard keeping track of such things, time wise. But yes, it seems like a good idea.

**Comment by jpadilla** [comment]
Got it, we'd probably need to document this well for contributors, maintainers and other release managers.

**Comment by xordoquy** [comment]
@jpadilla indeed, good point.

**Comment by auvipy** [comment]
can be closed IMHO
