### ISSUE TITLE
Sort API Guide 

### ISSUE THREAD

**Issue by morenoh149** [encode/django-rest-framework#4220]
I see the API Guide on the site is sorted by most important (?).
Seeing as this is the primary way to peruse the docs I'd suggest sorting the items alphabetically.
<img width="227" alt="screen shot 2016-06-23 at 3 37 18 pm" src="https://cloud.githubusercontent.com/assets/587438/16317378/dce6f55e-3958-11e6-923d-6032f837b1e6.png">

Unless there is another place the api is documented.

**Comment by tomchristie** [comment]
See also #4112.

**Comment by tomchristie** [comment]
I'm not sure the right thing to do. 
I would *like* a logical grouping, rather than simply alphabetical, but as the list has grown it's becoming less feasible. It may even be that we need another tier of depth to the menu now.
We could just go alphabetical, but that loses structure to my mind (Eg views & generic views, routers & viewsets, parsers & renderers, auth & perms & throttles, filtering & pagination)

**Comment by morenoh149** [comment]
come up with 5 section titles. Just pick a number.

**Comment by tomchristie** [comment]
Sorry, didn't quite understand the comment. Example?

**Comment by morenoh149** [comment]
1. views
1. routers
1. renderers
1. authentication
1. pagination

**Comment by tomchristie** [comment]
Sure. Adding another tier isn't super easy tho - would need some template re-jigging at the very least, and attention to ensuring it works okay on mobile.

**Comment by tomchristie** [comment]
An alternative way to address this might be to have a contents page that is easy to get to from anywhere else on the site, and gives a better overall view of the layout of different components.

**Comment by mikeengland** [comment]
As a techie, I'd love to see a filter box at the top as I often refer to different parts of the documentation. However, I understand that that may not be particularly design-friendly!

**Comment by audiolion** [comment]
The other issue is that the API Guide list is missing the bottom 5 bullets, it seems there is a max limit to the amount of <li>'s displayed in the menu, so `Testing`, `Settings`, etc. are missing from the menu.

I was real confused when I couldn't find a testing section, but found it when searching from the search bar at the top of the page

**Comment by tomchristie** [comment]
@audiolion - The scroll bar isn't always obvious (eg. chrome on mac it won't display but you can scroll.)

**Comment by jpadilla** [comment]
@tomchristie perhaps adding something subtle like this would help with that:

<img width="257" alt="screen shot 2017-03-20 at 6 28 43 pm" src="https://cloud.githubusercontent.com/assets/83319/24124644/178cf494-0d9b-11e7-8880-7b752ffa0bc0.png">

**Comment by audiolion** [comment]
ha, well TIL, had no idea that was scrollable (and yep, chrome on mac)

**Comment by morenoh149** [comment]
consider, the principle of least surprise.
