### ISSUE TITLE
Multi Database support for CreateView

### ISSUE THREAD

**Issue by nyssance** [encode/django-rest-framework#449]
Need sharding Database by user_id, django routes not support

my solution is override save in MySerializer

def save(self)
    self.object.save(using='db_%d' % (self.object.user_id % 4))
    return self.object

Maybe add a using arg for CreateView?

**Comment by ryanwilsonperkin** [comment]
@tomchristie @nypisces what are your thoughts on re-opening old issues vs. creating new ones? I want to respect your time and help create a useful issue.

We make extensive use of Django Rest Framework but are building all of our applications to be multi-database by default now. I am looking to see if you have any thoughts on how this functionality could be added, or if I can help out by providing a PR. I'm personally new to the framework, but help to support a lot of code that uses it.

Thanks!

**Comment by tomchristie** [comment]
@ryanwilsonperkin You should probably prefer opening a new issue and referencing related ones in the description.
