### ISSUE TITLE
Add realtime server and client support

### ISSUE THREAD

**Issue by tomchristie** [encode/django-rest-framework#4557]
- Realtime server support. (ie. nice integration layer over django channels)
- Realtime client support. (python client lib, JS client lib, command line client)

**Comment by auvipy** [comment]
drf-channels <3

**Comment by stunaz** [comment]
worth looking at https://github.com/django/channels/pull/544

**Comment by tomchristie** [comment]
@stunaz 👍

**Comment by mikhuang** [comment]
https://github.com/linuxlewis/channels-api seems interesting (I haven't seen it mentioned in the DRF Google Group or on the repo). Is the plan for realtime support in line with this app?

**Comment by singhravi1** [comment]
Hey Tom, are we ready to have realtime server in release 3.7.0?
Thanks.

**Comment by carltongibson** [comment]
I'm renaming and de-milestoning this for now. 

What we add in the end will depend on work going on right now in APIStar and Django Channels. Both projects are busy trying solve the underlying issues here. The patterns aren't yet clear enough for an Out-of-the-box solution in Django REST Framework. 

But it's coming. Have hope. 🙂 (Sorry no promises on timeframe. But "Have hope".) 

Best solution **right now** is probably to leverage Channels to build websocket consumers that return JSON responses you can consume on the client. This is still DIY-land but, as I say, we're still all working out the patterns. 

As ever, all concrete input welcomed.

**Comment by tomchristie** [comment]
@singhravi1 I do have some (broad) plans for better documentation & integration around using Django channels w/ REST framework, but no not yet - we're targeting Schema generation and API docs improvements for the 3.7 release.

**Comment by tomchristie** [comment]
> I'm renaming and de-milestoning this for now.

Going to close this issue off. Broad ideas for how we might improve things in this area, but this ticket isn't specific and actionable in it's current state.
