### ISSUE TITLE
FloatField should use the user current local to parse float value

### ISSUE THREAD

**Issue by kgeorgy** [encode/django-rest-framework#4584]
# FloatField should use the user current local to parse float value

The FloatField fail to parse float value with coma (ex. 17,456) which is used by some local float format (for example with French locale).

The problem with that is if you are using the TemplateHTMLRenderer, it will fill the html <input> field with a value with a coma, and that will cause an 'A valid number is required.' error when submitting the form.

I don't know if it is more a parser issue or a FloatField issue, or if we need to add a "localize" parameter to the FloatField like for the DecimalField.
## Steps to reproduce
- Set LANGUAGE_CODE = 'fr-ch' in the django project settings.
- Create a serializer with a FloatField, and make it point on an instance having a float value like 2.34.
- Render the serializer using an TemplateHTMLRenderer and {% render_form serializer %} in the template.
- Observe that the value in the input field is 2,34 (with a coma).
- Submit the form (be sure to call .is_valid() on the serializer in the processing view)
- You have an  'A valid number is required.' ValidationError.
## Expected behavior

The FloatField (or the parser?) should use the current context locale to parse the float value (at least for form encoded data).
## Actual behavior

The float value is rendered using the user locale when rendering template but not when parsing the float value.

**Comment by tomchristie** [comment]
Worth consideration.

**Comment by xordoquy** [comment]
Does Django form also handle that ?

**Comment by kgeorgy** [comment]
According to the django documentation (https://docs.djangoproject.com/en/1.10/ref/forms/fields/#floatfield) it seems that the FloatField of django forms has a "localize" parameter, so it should handle that case. But I haven't tested that yet.

**Comment by xordoquy** [comment]
I've seen that but haven't been able to make it work yet.

**Comment by kgeorgy** [comment]
I'll try to change the fields.py to handle IntegerField and FloatField like DecimalField, by adding a coerce_to_string and localize paramaters (probably I'll create a base NumberField to handle that, and then make Integer, Float and Decimal fields derive from that class). I'll post my progress here and when (if) it is mature enough, I'll do a pull request (never done that before, so your advices a welcome).

**Comment by xordoquy** [comment]
Since you mentioned French, any luck you're at pycon.fr this weekend ?

**Comment by kgeorgy** [comment]
@xordoquy Nop, I'm from Switzerland and it's a bit too far from me (at least just for a weekend) ;)

**Comment by carltongibson** [comment]
Closed by #4925
