### ISSUE TITLE
Turn off codecov `diffhit` checks.

### ISSUE THREAD

**Issue by tomchristie** [encode/django-rest-framework#4594]
It's nice having a total coverage report, but `codecov`'s diff hits are aren't always helpful and are marking some PRs that we want to accept as failed.

I've briefly looked into turning this off, but the settings are not totally obvious - I believe(?) this may be because they've moved to a new .yaml based system sometime after we originally setup the project settings, and our settings have not been automatically migrated into that.

**Comment by lwm** [comment]
A full example: https://github.com/codecov/support/wiki/Codecov-Yaml#full-yaml

**Comment by tomchristie** [comment]
👍  Shouldn't be hard to resolve.

**Comment by carltongibson** [comment]
Is this still live? [codecove is currently disabled](https://github.com/encode/django-rest-framework/commit/68d2020112d312c69b8407c42179e0f3e9d9baa0#diff-8bc9db6adba7208e25c96be322351063)

(Or, if not, what's the desired result? Comments but not failures? Failures for X, Y, Z?)

**Comment by tomchristie** [comment]
Thanks @carltongibson! :p
