### ISSUE TITLE
In 3.5, DefaultRouter root view does not work together with get_schema_view

### ISSUE THREAD

**Issue by tuffnatty** [encode/django-rest-framework#4616]
## Checklist
- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [?] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)
## Steps to reproduce

In 3.4, I used to do:

``` python
router = routers.DefaultRouter(schema_title='API Title')
...
urlpatterns = [                                                                                                                                               
    url(r'^restapi/', include(router.urls)), 
```

In 3.5, I have changed it (as per the documentation) to:

``` python
router = routers.DefaultRouter()
...
urlpatterns = [
    url(r'^restapi/$', get_schema_view(title='API Title')),
    url(r'^restapi/', include(router.urls)),
```
## Expected behavior

Request with `Accept: text/html` did return the DefaultRouter's root view with links to list views as Browsable API in 3.4.
Request with `?format=corejson` did return CoreAPI schema.
Request with `?format=json` did return the DefaultRouter's root view with links as plain JSON.
## Actual behavior

Request with `Accept: text/html` returns CoreAPI schema as a Browsable API.
Request with `?format=corejson` returns CoreAPI schema.
Request with `?format=json` returns `{"detail":"Not found."}`.

When I remove

```
    url(r'^restapi/$', get_schema_view(title='API Title')),
```

The DefaultRouter root view is returned as it should.

**Comment by tuffnatty** [comment]
Maybe it's the expected behaviour in the new version, but then it's not clear from the documentation how do I achieve both schema and root view at one URL depending on format requested.

**Comment by santiagomalter** [comment]
I have the same issue in 3.5.0.

**Comment by rocktavious** [comment]
I'm not saying the documentation shouldn't be fixed, but i did something like this to work around it.

```
from django.conf.urls import url, include
from django.views.generic import RedirectView
from rest_framework.schemas import get_schema_view
from rest_framework_swagger.views import get_swagger_view
from rest_framework_raml.renderers import RAMLRenderer, RAMLDocsRenderer

title = "My API"

base_schema_view = get_schema_view(title=title)

swagger_schema_view = get_swagger_view(
    title=title,
)

raml_schema_view = get_schema_view(
    title=title,
    renderer_classes=[RAMLRenderer, RAMLDocsRenderer]
)

urlpatterns = [

    url(r'^', include([
        url(r'^$', RedirectView.as_view(url='/api/swagger/')),
        url(r'base/$', base_schema_view),
        url(r'swagger/$', swagger_schema_view),
        url(r'raml/$', raml_schema_view),
        url(r'^core', include(core_router.urls)),
```

Hope this helps anyone thats gets stuck in the mean time.

**Comment by tomchristie** [comment]
Not sure what we want to do here - needs further review. Currently it's not really supported in the new style.

**Comment by rocktavious** [comment]
Would it be possible to have an option on the router to "enable scheme view" at some predetermined url like `/schema`? kinda like there is for disabling the root view?  Maybe it would also need configuration for setting the scheme view's kwargs or something too. IE Title, renderers, etc

**Comment by tomchristie** [comment]
> Would it be possible to have an option on the router to "enable scheme view" at some predetermined url like /schema

Not really no. That ends up giving two different ways around to do things but isn't actually any simpler than the existing option.

That the schema view ever existed on the router was a design mistake the first time around.

**Comment by milos-mandic** [comment]
You can't import get_schema_view from rest_framework.schemas anymore.
Bug?
