### ISSUE TITLE
Serialization of timedeltas should be consistent

### ISSUE THREAD

**Issue by nip3o** [encode/django-rest-framework#4665]
When serializing a `datetime.timedelta()`as part of a JSON-object, it is serialized as the total number of seconds. Support for this was introduced in #584. When using a `serializers.DurationField`, it is serialized as a `HH:MM:DD`-like string, as introduced in #2989.

This can be quite troublesome on the client, since different API:s will have different behaviour depending on their implementation. In my specific use-case we transform the data from the API into moment.js duration objects, and depending on API implementation this currently has to be done in different ways.

I realize this would be a breaking change, but I think it is worth to discuss.

**Comment by xordoquy** [comment]
You can still either override the JSONRenderer or create a custom duration field to make the output / input more consistent

**Comment by nip3o** [comment]
Yup, that is what I'm currently doing, I just fail to see the point of serializing the same data type in different ways by default.

**Comment by tomchristie** [comment]
We *could* change the default implementation of JSONEncoder to handle `timedelta` differently, but I'm not particularly convinced at the moment. It'd be a little more consistent, but I don't think there's any *absolute* requirement that the default representation for `DurationField` should also happen to be the same as the default represention of `datetime.timedelta` (yes, it'd be nicer, but I wouldn't consider it a bug - these are two different cases, which happen to have the same internal type)

**Comment by tomchristie** [comment]
> the point of

It's historical, rather than by design.

If we do consider a solution then I think we need to make it easy to switch between the different usage styles (Eg. introduce a setting for it)
