### ISSUE TITLE
_writable_fields in Serializer retrieves read only fields

### ISSUE THREAD

**Issue by vasofi** [encode/django-rest-framework#4666]
Hi,
the _writable_fields in the Serializer class decides if a field is writeable or not is this way:
if (not field.read_only) or (field.default is not empty)

This has caused an issue for us. I have a serializer with 3 nested fields that are defined as read only. So when I send the serializer to the client, these fields are not empty. When I want to update this object and send the data back to the server, these fields are again not empty. The fields are not changed, since it's read only, they just have the same data they had before.
But when I reach the validation point, because this fields are not empty, they are added to the writeable_fields list, even though they are defined as read only, like this:
offer = OfferSerializer(read_only=True)

In this case, when we tried to update the object we got this error:
The `.update()` method does not support writable nested fields by default.
Write an explicit `.update()` method for serializer...

**Comment by xordoquy** [comment]
I don't get your issue.
This only case where the field will be marked as writable is when you have a default value associated.
Sounds like you just need to pass the nested serializer value as an extra argument to the serializer.save instead.
Will consider reopening with an associated test case that highlight the issue as it's not clear to me where it actually is.

**Comment by danielkeller** [comment]
I'm having this issue with fields like

    year = serializers.IntegerField(source='tag.year', read_only=True, default=None)

The nested writes test complains about this field when it shouldn't.

`tag` is a nullable foreign key, so`default` is necessary to get `{"year": null}` in the output when tag is NULL (otherwise the year key is simply omitted).

**Comment by carltongibson** [comment]
@danielkeller I'm looking into this issue right now ([branch](https://github.com/carltongibson/django-rest-framework/tree/38/read_only+default), PR tomorrow).

Can you show me the error and the end of your traceback? All data is good.

**Comment by carltongibson** [comment]
I'm going to reopen this. It'll give me something to close. 🙂

**Comment by carltongibson** [comment]
Related: https://github.com/encode/django-rest-framework/pull/5708#issuecomment-355569737

**Comment by carltongibson** [comment]
Closed in #5886
