### ISSUE TITLE
Community & Operations Manager

### ISSUE THREAD

**Issue by tomchristie** [encode/django-rest-framework#4667]
Hi folks,

Wanted to let you all know that I'm starting to think about how we can grow the business that looks after REST framework development. At the moment I'm hoping to open up a 3 month position starting Jan 2017. Applications welcome.

More information here: http://www.encode.io/positions/community-and-operations-manager.html

**Comment by tomchristie** [comment]
Incidentally, I'm very open to thoughts & feedback on how we're handling the business side of this.

Building a open source company isn't well explored ground and I'd really appreciate your input on any aspect of this, either publically or privately.

**Comment by auvipy** [comment]
I am interested :)

**Comment by tomchristie** [comment]
Applications most welcome - tom@tomchristie.com

**Comment by auvipy** [comment]
I hope the application period is still open.

**Comment by tomchristie** [comment]
I plan on making a decision on how to progress by the end of next week, latest.

**Comment by tomchristie** [comment]
Given that @ossanna16 has been on board for a while now I think it's safe to say that we can close this issue off! 😄
