### ISSUE TITLE
Schema generation - prefer 'multipart' if file field exists

### ISSUE THREAD

**Issue by tomchristie** [encode/django-rest-framework#4732]
* If a FileField or ImageField exists on the view serializer.
* And all the other fields are primitive types.
* Then we should prefer "multipart" over "json", if it is available in the parser classes.

Refs: https://github.com/marcgibbons/django-rest-swagger/issues/573

**Comment by carltongibson** [comment]
@tomchristie Happy to roll this into 3.7. Not sure how you want it to look. 

https://github.com/encode/django-rest-framework/blob/d8da6bb29b53675f837c8873cf8fcde171a3aae1/rest_framework/schemas/inspectors.py#L369-L372

`get_encoding` doesn't take a fields param so do we add that or do the check at the callpoint...?

https://github.com/encode/django-rest-framework/blob/d8da6bb29b53675f837c8873cf8fcde171a3aae1/rest_framework/schemas/inspectors.py#L177-L180

What do you think? 

Is a check of... `not any(f in fields if not isinstance(f, OrderedDict)` going to cut it do you think? 
Ta!

**Comment by carltongibson** [comment]
I'm going to de-milestone this for now. We can review after v3.7

**Comment by ggjersund** [comment]
@carltongibson Does this expand into the auto generated and interactive API documentation? I'm looking to have a file field in the form, which it is currently lacking.

**Comment by rpkilby** [comment]
A couple of thoughts, 
- In general, I'm kind of -1 on magical behavior changes. e.g., what are the ramifications if an endpoint drops a non-primitive field? Would the change in preferred parser be a confusing change to users? Note: I don't really take advantage of schema generation, so my grasp on this is limited. This might be a trivial/non-concern.
- In some cases, I've used a `Base64EncodedFileField`, which inherits `FileField`, but doesn't leverage the multipart media type. How would this be accounted for?

**Comment by NANASHI0X74** [comment]
This issue is also affecting me currently.
Maybe it would be an option to have a get_parser_classes method I could override akin to get_serializer_class that I can override on a viewset?

**Comment by auvipy** [comment]
closing as not planned for now
