### ISSUE TITLE
Inconsistent time serialization

### ISSUE THREAD

**Issue by ikloecker-mevis** [encode/django-rest-framework#4749]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
The implementation of time serialization in ISO-8601 format is not consistent in the codebase.
In https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/fields.py#L1284 microseconds are included in the serialized value
In https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/utils/encoders.py#L41 only milliseconds are

This is basically the same issue as #4255 except for time instead of datetime.

## Expected behavior
I would expect a consistent implementation between the different serialization of time _and_ datetime, i.e. all of them should include microseconds.

## Actual behavior
See "Steps to reproduce"

**Comment by tomchristie** [comment]
Yup seems clear. Milestoning for 3.7 so we can make to make the change against a major version (given that it'll change the API output)
