### ISSUE TITLE
Inconsistent "field required" errors with ManyRelatedField

### ISSUE THREAD

**Issue by pchiquet** [encode/django-rest-framework#4975]
## Checklist

- [*] I have verified that that issue exists against the `master` branch of Django REST framework.
- [*] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [*] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [*] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [*] I have reduced the issue to the simplest possible case.
- [*] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Create a simple ModelSerializer with a ManyRelatedField, with no `required` parameter, such as:

    class UserSerializer(serializers.ModelSerializer):
       groups = serializers.StringRelatedField(many=True, queryset=...)
       ...

Then **`groups` field is required or not depending on the input data format**:
- `groups` is required when sending json object to create a User (for example, from the "Raw Data" tab on the API test page with 'application/json' as input media type)
- `groups` is not required when using form data as input (for example, from the "HTML form" tab on the API test page)

## Expected behavior
The behavior should be consistent and should not depend on the input data format.

## Actual behavior
ManyRelatedField is required or not depending on the input data format.

**Comment by xordoquy** [comment]
I believe this is a consequence of the inability for forms to provide null data.
I need to think a bit about the effects of forcing the required parameter when it comes to forms.

**Comment by pchiquet** [comment]
`field.get_value(data)` (called in Serializer.to_internal_value) returns:
- empty when data is a dictionary
- [] when data is a QueryDict

Adding `required=False` to ManyRelatedField options fix the issue: 

    class UserSerializer(serializers.ModelSerializer):
      groups = serializers.StringRelatedField(many=True, required=False, queryset=...)
      ...

**Comment by tomchristie** [comment]
Closing as per #4976.
