### ISSUE TITLE
Document include_docs_urls / get_docs_view / get_schemajs_view

### ISSUE THREAD

**Issue by xordoquy** [encode/django-rest-framework#4980]
I think we can now safely add:

- include_docs_urls
- get_docs_view
- get_schemajs_view

to the documentation.
Can take care of it if there's no objections.

**Comment by carltongibson** [comment]
I just realised I duplicated this in #5449 — closing that. 

> Can take care of it if there's no objections.

None at all. 😀

**Comment by vimarshc** [comment]
@carltongibson Does this entail documenting `documentation.py` or `documenting-you-api.md`.

**Comment by carltongibson** [comment]
@vimarshc `documentation.py`. 👍
