### ISSUE TITLE
OrderingFilter should not accept an arbritrary number prefixed - characters for validating fields.

### ISSUE THREAD

**Issue by hvdklauw** [encode/django-rest-framework#4989]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

- Create a ViewSet with an OrderingFilter and add a field to order on (field_name)
- Call the viewset with `?ordering=--field_name`

## Expected behavior
No ordering to be applied

## Actual behavior
Throws a 500 error because --field_name is passed to the queryset because over [here](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/filters.py#L268) an lstrip is done instead of just removing the first - character before validation.

**Comment by tomchristie** [comment]
Any chance you could include the error traceback - it's not obvious to me on first sight what the issue is here.

**Comment by xordoquy** [comment]
@tomchristie the thing is the value minus lstrip('-') is matched against existing fields but it passed as it is to the queryset. Result being that:

- "--field_name".lstrip('-') -> field_name which is valid
- .order_by('--field_name') is not valid

**Comment by vimarshc** [comment]
Hey guys,

Wanted to contribute to the test cases. 
Wanted to know if the expected behaviour mentioned in @hvdklauw above is correct. 

And by that logic can we add an arbitrary number of hyphens?

**Comment by xordoquy** [comment]
@vimarshc iirc, the current logic is to discard invalid ordering fields. To keep consistent I believe that "--field_name" should be simply discarded.
