### ISSUE TITLE
JSONField not rendered properly in DRF browsable API HTML form

### ISSUE THREAD

**Issue by hommel** [encode/django-rest-framework#4999]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
    -   73ad88eaae2f49bfd09508f2dcd6446677800a26
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
    -   #4135: webform-input parsed as string (PR: #4565)
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Expected behavior

Assuming:
- a valid JSON object is stored in postgreSQL as a django `models.JSONField` and 
- that data is serialized using DRF's serializers.JSONField, 

then that data should render as a JSON object in DRF browsable API (particularly because the serializer requires input to be valid JSON for POST/PUT/PATCH methods)

## Actual behavior

Data renders as native python in DRF browsable API form field (e.g. single quotes, uppercase booleans)

![instance_view_html](https://cloud.githubusercontent.com/assets/1246469/24063790/5ac9358a-0b1e-11e7-80bd-2021bbdc8723.png)

Note that the "Raw data" view of the input section renders the data correctly as JSON.

![instance_view_raw](https://cloud.githubusercontent.com/assets/1246469/24063901/dea9db3e-0b1e-11e7-9d51-0d1aa1f7d9e2.png)

## Steps to reproduce

```bash
(venv)vagrant@vm:/vagrant/src/app$ python -V
Python 3.4.3
(venv)vagrant@vm:/vagrant/src/app$ psql -V
psql (PostgreSQL) 9.6.2
```

```
# requirements.txt
Django==1.10.6
psycopg2==2.7.1
-e git+git@github.com:tomchristie/django-rest-framework.git@73ad88eaae2f49bfd09508f2dcd6446677800a26#egg=djangorestframework-origin/HEAD
```

```python
# models.py

from django.db import models
from django.contrib.postgres.fields import JSONField


class Foo(models.Model):

    name = models.CharField(max_length=24)
    data = JSONField()
```

```python
# serializers.py

from rest_framework import serializers

from jsontest import models


class FooSerializer(serializers.HyperlinkedModelSerializer):

    name = serializers.CharField(max_length=24)
    data = serializers.JSONField()

    class Meta:
        model = models.Foo
        fields = ('url', 'name', 'data')
```

```
>>> from jsontest.models import *
>>> f = Foo()
>>> f.name = 'created via shell'
>>> f.data = {'input': 'native dict', 'bar': True}
>>> f.save()
>>> f.id
1
```

**Comment by xordoquy** [comment]
Thanks for reporting.
I gave it a try and yeah, this is reproduced.

**Comment by aleehedl** [comment]
I'm still experiencing this bug.
