### ISSUE TITLE
Unclear URL value in API Documents

### ISSUE THREAD

**Issue by COCOLMAN** [encode/django-rest-framework#5002]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

```
# root/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework.documentation import include_docs_urls


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^post/', include('post.urls')),
    url(r'^docs/', include_docs_urls(title='My API title'))
]

```

```
# post/urls.py

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^create/$',  views.PostCreate.as_view(), name='post-create')
]

```

The url to create the post is `<domain>/post/create/`

## Expected behavior

![2017-03-18 17 20 35](https://cloud.githubusercontent.com/assets/22088047/24070410/3776ba7a-0c00-11e7-847d-7689ca77ee2c.png)

 ( This screen comes up when you replace to `url (r' ^/ $ ', views.PostCreate.as_view (), name =' post-create ')` . )

## Actual behavior

![2017-03-18 17 21 04](https://cloud.githubusercontent.com/assets/22088047/24070366/635e8dda-0bff-11e7-99ff-e8e23c646a20.png)

`create` under the `create`
Is this intended?
Although there is '/ post / create /' below.
in my think this is unclear expression of information.

I think it's a good idea to display the value of all the paths in url.(or namespace)
<Domain> / post / create / -> post-create

**Comment by carltongibson** [comment]
If you want to customise the keys used to structure the schema `coreapi.Document` you need to subclass `SchemaGenerator` and override `get_keys` to return the values you want: 

https://github.com/encode/django-rest-framework/blob/2befa6c3160a48b9eb9cc63292bd43b540a5b4d5/rest_framework/schemas/generators.py#L360-L371

Would be happy to look at a PR suggesting a change to the defaults here, but short of a concrete suggestion I cannot say whether we'd be inclined to take it or not.
