### ISSUE TITLE
Coreapi explicite argument decorator

### ISSUE THREAD

**Issue by AlexBaranowski** [encode/django-rest-framework#5039]
Hi,
I tried to get answer on Google Group discussion [here.](https://groups.google.com/forum/#!topic/django-rest-framework/rEztNTpFBgQ)

## Steps to reproduce
Very simple view like
```python
class SetPassword(APIView):
    parser_classes = (parsers.JSONParser,)
    renderer_classes = (renderers.JSONRenderer, renderers.CoreJSONRenderer)

    def post(self, request, pk=None):
        pass
        """
        this view reads request.data['password'] then set password.
        """
```

## Expected behavior
There should be decorator - or something similar that allow to override coreapi passed arguments explicit.
Like 
```python
class SetPassword(APIView):
    parser_classes = (parsers.JSONParser,)
    renderer_classes = (renderers.JSONRenderer, renderers.CoreJSONRenderer)
    
    @core_api_args(['user_id', 'password'])
    def post(self, request, pk=None):
        pass
        """
        this view reads request.data['password'] then set password.
        """
```

## Actual behavior
In CoreApi this view looks like set_password: create(id) - there is no explicit information about password, etc. So in order to use it properly there must be argument `validate=False`, passed to CoreAPI invoking this method.

**Comment by rpkilby** [comment]
Hi @AlexBaranowski - I'm not incredibly familiar with coreapi, but I would assume that it inspects the `serializer_class` to generate the schema. From the google groups discussion, you were using a `detail_route` instead of a separate view class. You can override the `serializer_class` in the `detail_route` options if you choose to do so.

eg,
```python

class SetPassword(APIView):
    serializer_class = PasswordSerializer
    ...

# or

class UserAPI(viewsets.ModelViewSet):
    queryset = User.objects.all().filter(is_active=True)
    serializer_class = UserSerializer  # Your standard user data serializer

    @detail_route(methods=('post',), serializer_class=PasswordSerializer)
    def set_password(self, request, pk=None):
        ...
```

Let me know if that helps.

**Comment by xordoquy** [comment]
Hi,

coreapi schema generation requires the view to have a `get_serializer` so it shouldn't be working with `APIView`.
I read your google group discussion and I'm afraid I didn't get your point.
