### ISSUE TITLE
Disable validation on serializer completely (nested)

### ISSUE THREAD

**Issue by bryanph** [encode/django-rest-framework#5046]
I am looking for a way to disable validation on a serializer in a nested way.
For example wth this code:

```
class SerializerTwo(serializers.Serializer):
    value_two = serializers.CharField()

class SerializerOne(serializers.Serializer):
    value_one = serializers.CharField()
    nested_value = AnotherSerializer(required=False)

```

I want to be able to post data of the form
```
{
    value_one: "abc",
    value_two: {
          // this shouldn't matter
    }
}
```

And not receive any validation errors no matter on how I set up the validation. I want this because I wrote my own validation methods that are shared with another part of the codebase. Hence, I don't want DRF interfering with that flow.

**Comment by tomchristie** [comment]
Don't use a serializer for the nested field. Use a DictField, or something else that reflects a more lenient set of validation constraints.

**Comment by Lonyless** [comment]
this helped me a lot! thank you!

**Comment by Lonyless** [comment]
> Don't use a serializer for the nested field. Use a DictField, or something else that reflects a more lenient set of validation constraints.

this helped me a lot! thank you!

**Comment by Lonyless** [comment]
> I am looking for a way to disable validation on a serializer in a nested way.
> For example wth this code:
> 
> ```
> class SerializerTwo(serializers.Serializer):
>     value_two = serializers.CharField()
> 
> class SerializerOne(serializers.Serializer):
>     value_one = serializers.CharField()
>     nested_value = AnotherSerializer(required=False)
> ```
> 
> I want to be able to post data of the form
> 
> ```
> {
>     value_one: "abc",
>     value_two: {
>           // this shouldn't matter
>     }
> }
> ```
> 
> And not receive any validation errors no matter on how I set up the validation. I want this because I wrote my own validation methods that are shared with another part of the codebase. Hence, I don't want DRF interfering with that flow.
override run_validation, there you can see the real content of validated_data before django put its hands on it

**Comment by anjayluh** [comment]
@Lonyless care to share how to override run_validation?

**Comment by Lonyless** [comment]
class MySerializer(serializers.ModelSerializer):

    def run_validation(self, data):
        print(data) //<- your data before the validation
        validated_data = super().run_validation(data=data)
        return validated_data

**Comment by Lonyless** [comment]
> @Lonyless care to share how to override run_validation?

`
class MySerializer(serializers.ModelSerializer):

def run_validation(self, data):
    print(data) //<- your data before the validation
    validated_data = super().run_validation(data=data)
    return validated_data
`

**Comment by Lonyless** [comment]
> @Lonyless care to share how to override run_validation?

`
class MySerializer(serializers.ModelSerializer):

    def run_validation(self, data):
        print(data) //<- your data before the validation
        validated_data = super().run_validation(data=data)
        return validated_data
`
