### ISSUE TITLE
Pagination duplicate QuerySet evaluation in Django 1.11

### ISSUE THREAD

**Issue by debnet** [encode/django-rest-framework#5048]
## Checklist

- [X] I have verified that that issue exists against the `master` branch of Django REST framework.
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [X] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [X] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

Create a simple ModelViewSet against a model and configure APIs to use PageNumberPagination.

```python
class UserViewSet(viewsets.ModelViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
```

## Expected behavior

QuerySet of the viewset executed only once.

![image](https://cloud.githubusercontent.com/assets/634832/24696101/9fe122a8-19e8-11e7-80a6-359cf7017d51.png)

## Actual behavior

QuerySet is actually evaluated and executed two times due to Django internal check of ordered results.

![image](https://cloud.githubusercontent.com/assets/634832/24696088/9499da98-19e8-11e7-862c-91e574096441.png)

## Explanation

The issue is due to a new control for ordering added in Django 1.11 paginator.

```python
    def _check_object_list_is_ordered(self):
        """
        Warn if self.object_list is unordered (typically a QuerySet).
        """
        if hasattr(self.object_list, 'ordered') and not self.object_list.ordered:
            warnings.warn(
                'Pagination may yield inconsistent results with an unordered '
                'object_list: {!r}'.format(self.object_list),
                UnorderedObjectListWarning
            )
```
_django/core/paginator.py - l. 104_

## Workaround

Subclassing PageNumberPagination and overriding the Django behaviour:

```python
class CustomPageNumberPagination(PageNumberPagination):
    def paginate_queryset(self, queryset, request, view=None):
        self.django_paginator_class._check_object_list_is_ordered = lambda s: None
        return super().paginate_queryset(queryset, request, view=view)
```

**Comment by rpkilby** [comment]
Hi @debnet - It seems like the answer here is to use an ordered query instead of circumventing the ordering check.

I assume the following works as expected?

```python
class UserViewSet(viewsets.ModelViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.order_by('id')
```

**Comment by debnet** [comment]
In this case, yes, but it's a shame Django tries to dump the data of the QuerySet when it wasn't ordered...

But it's clearly developer side to provide when possible a `.order_by()` when using paginator.

**Comment by xordoquy** [comment]
The thing is without order clause, you have no way to guarantee that every data will be delivered.
The ordering may change in the middle of the pages leaving the dataset in a totally inconsistent state.
I'm going to close this.
Thanks for raising this @debnet as I'm sure we'll get some reports about it.

**Comment by tuky** [comment]
I just stumbled upon this and find the `_check_object_list_is_ordered` quite useless. It does not catch random ordering (use `'?'` as in https://docs.djangoproject.com/en/1.11/ref/models/options/#django.db.models.Options.ordering). So I can prevent a warning about unordered lists by using random ordering... wtf?!
