### ISSUE TITLE
ApiClient and AcceptHeaderVersioning

### ISSUE THREAD

**Issue by TZanke** [encode/django-rest-framework#5049]
I am using the `AcceptHeaderVersioning` and like to write some tests. At the moment i do it this way:

`.put(url, **{'HTTP_ACCEPT': 'application/json; version=1'})`

But i would like to write the code like this

`.put(url, format='json', version='1')`

Whats the correct way atm? I could not find anything related to testing a `AcceptHeaderVersioning` Api.

**Comment by xordoquy** [comment]
Hi, the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!

**Comment by tomchristie** [comment]
Aside: There's no extra little helper that we provide, no.
