### ISSUE TITLE
Exclude include tag

### ISSUE THREAD

**Issue by COCOLMAN** [encode/django-rest-framework#5050]
See the django 1.11 Release Notes..

> Silencing exceptions raised while rendering the {% include %} template tag is deprecated as the behavior is often more confusing than helpful. In Django 2.1, the exception will be raised.

I think DRF should cull '{% include %}'.

**Comment by xordoquy** [comment]
What's the alternative ? Why should DRF do that ?

**Comment by COCOLMAN** [comment]
This is because there are 'include tags' in the html files that make up the API Document.

For example `rest_framework / templates / rest_framework / docs / link.html`

**Comment by xordoquy** [comment]
I think we should rather fix the exceptions rather than discarding the {% include %} tags.
This change will just make included templates more strict and robust so it should be for the best.
