### ISSUE TITLE
Changing attributes in request.data is throwing an AttributeError on Django 1.11

### ISSUE THREAD

**Issue by rodxavier** [encode/django-rest-framework#5056]
## Checklist
- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
In Django 1.11's release notes, the following is noted:

> For consistency with non-multipart requests, MultiPartParser.parse() now leaves request.POST immutable. If you’re modifying that QueryDict, you must now first copy it, e.g. request.POST.copy().

Now, trying to alter request.data is throwing `AttributeError: This QueryDict instance is immutable`.

Typical use cases for altering request.data would be adding in computed attributes such as created_by or updating fields dependent on other fields.

## Expected behavior
We should still be able to change `request.data`

## Actual behavior
`request.data` is throwing `AttributeError: This QueryDict instance is immutable`.

**Comment by tomchristie** [comment]
If you want to modify data, create a copy.

In the example of created_by, either have a default on the model field, or pass extra arguments to serializer.save(...) that'll get passed through without requiring validation.

Allowing request.data to be modified isn't necessary and promotes something I consider a bit of an anti-pattern.

**Comment by rodxavier** [comment]
Thanks for the quick turnaround @tomchristie.

I would like to know how you would approach this when using the mixins, namely the CreateMixin and UpdateMixin. It seems like the mixins will be pretty much useless since you'll need to fully override the `create()` or `update()` methods since the serializer initialization uses request.data?

**Comment by tomchristie** [comment]
It's fine to initialize the serializer with `request.data` - you'd typically want to overide `perform_create`/`perform_update`. Adding extra keyword arguments to `serializer.save()`, eg... `serializer.save(created_at=...)` is a good way to add in extra data. If you really *do* need to override that data that the serializer uses *during validation* then I'd suggest eg. overriding `get_serializer`, so that you clone `request.data` and then mutate that. However it's unlikely that you need to do that since you *don't* actually want to validate stuff that the framework is providing. Just validate the user input.

**Comment by rubendv** [comment]
I'd like to point out that when using the DRF APIClient in tests, request.data is a normal dict, not a QueryDict. So this issue was only visible for us when using the real API and not while running our tests.

**Comment by rubendv** [comment]
Disregard that last comment, our tests are using application/json, not multipart.
