### ISSUE TITLE
Issue with get_rendered_html_form signature

### ISSUE THREAD

**Issue by parisk** [encode/django-rest-framework#5057]
Hello!

I am in the process of upgrading Django REST Framework from version 2 to 3.6 in a production application and in the process of debugging I ran into this quite interesting error, when I tried to access a Browserable API viewset:

```
TypeError at /api/internal/users
get_rendered_html_form() takes exactly 4 arguments (5 given)
```

The interesting part is that there is **no code of our application in this exception**. Also, based in [`get_rendered_html_form`](https://github.com/encode/django-rest-framework/blob/de9a8c4811efccc7f6ab3ae2cd36cef7f9f4ea59/rest_framework/renderers.py#L444) nothing should be going wrong (I have attached the local variables at this point below).

Any idea why and how might this be happening. If we identify the issue, I am more than happy to put up a PR for fixing this, if applicable.

## DRF-related packages version
```
Django==1.8.2
djangorestframework==3.6.2
drf-compound-fields==1.0.0
django-rest-framework-mongoengine==3.3.1
```

## Screenshot
![image](https://cloud.githubusercontent.com/assets/1188592/24789269/1c97801c-1b6a-11e7-85e6-e56613ff7453.png)

## Local vars
<details>
<pre>
paginator	
None
raw_data_put_form	
None
csrf_header_name	
u'X-CSRFToken'
accepted_media_type	
u'text/html'
response_headers	
OrderedDict([('Allow', 'GET, OPTIONS'), ('Content-Type', u'application/json'), ('Vary', 'Accept')])
renderer_content_type	
u'application/json'
renderer_cls	
<class 'common.renderers.BrowsableAPIRenderer'>
renderer_context	
{u'args': (),
 u'indent': 4,
 u'kwargs': {},
 u'request': <rest_framework.request.Request object at 0x7f0c1feb5c10>,
 u'response': <rest_framework.response.Response object at 0x7f0c1feb5fd0>,
 u'view': <users.views.UserViewSet object at 0x7f0c1feb5a10>}
self	
<common.renderers.BrowsableAPIRenderer object at 0x7f0c1feb5cd0>
request	
<rest_framework.request.Request object at 0x7f0c1feb5c10>
raw_data_put_or_patch_form	
None
raw_data_patch_form	
None
renderer	
<rest_framework.renderers.JSONRenderer object at 0x7f0c1fe6b390>
raw_data_post_form	
None
csrf_cookie_name	
'csrftoken'
data	
[OrderedDict([('username', u'paris'), ('email', u'pariskasidiaris@gmail.com'), ('password', u'bcrypt_sha256$$2b$12$IKQQrg8DMgRS..oQVoa6A..hW/xI7gbkjHSJErTdXmUYbscUmWZw6'), ('created', '2017-04-06T20:27:22.307000'), ('status', u'created'), ('plan', u'free'), ('project_limit', 5), ('settings', OrderedDict([('console_height', 200), ('console_visible', True), ('file_explorer_visible', True), ('file_explorer_width', 200), ('editor', OrderedDict([('auto_complete', True), ('on_keystroke', True), ('display_args', True), ('auto_save', False), ('font_size', 14), ('indent_with_spaces', True), ('auto_close_brackets', True), ('auto_close_tags', True), ('show_invisibles', False), ('show_trailing_space', False), ('line_wrapping', True), ('tab_size', 4), ('theme', u'rubyblue'), ('show_ruler', False), ('ruler_position', 80), ('keymap', u'default'), ('lint', OrderedDict([('css', True), ('html', True), ('js', True), ('python', True), ('enabled', True)])), ('emmet', True)])), ('single_click_open', False)])), ('meta', OrderedDict([('utm_source', u''), ('utm_medium', u''), ('utm_campaign', u''), ('referrer', u''), ('account_deletion_reason', None)])), ('is_verified', True), ('last_workspace', u'null')])]
response	
<rest_framework.response.Response object at 0x7f0c1feb5fd0>
view	
<users.views.UserViewSet object at 0x7f0c1feb5a10>
</pre>
</details>

**Comment by tomchristie** [comment]
Can't see the problem on first glance here.
Are you able to narrow this down to a small reproducible example case?

**Comment by parisk** [comment]
Yeah, I know it's quite strange. I will try to reproduce it though and will post an update.

**Comment by xordoquy** [comment]
My feeling is that either the compound field or the mongo thing may interfere here.

**Comment by tomchristie** [comment]
Going to close this off for now until we've got something more isolated to work against.
