### ISSUE TITLE
APIRequestFactory doesn't respect version

### ISSUE THREAD

**Issue by ghost** [encode/django-rest-framework#5061]
## Checklist

- [x ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

Create a APIRequestFactory, the AcceptHeaderVersioning on the latest version will throw an error in my tests with a 406. On the older versions of the framework my tests worked fine. I fixed this by manually setting the Accept headers.

## Expected behavior

For it to work like it did in 3.1 where I could pass it the view directly for the response with our the versioning crash.

## Actual behavior

It throws a versioning error.

**Comment by tomchristie** [comment]
If you're using accept header versioning then you will need to explicitly set the accept header on the client. Not sure what the change in behavior will have been but the current behavior sounds fairly reasonable to me.
