### ISSUE TITLE
AttributeError: 'Request' object has no attribute 'accepted_renderer'

### ISSUE THREAD

**Issue by sergiomb2** [encode/django-rest-framework#5068]
## Checklist

- [X] I have verified that that issue exists against the `master` branch of Django REST framework.
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [X] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [X] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

After googling and verified that several errors stops in this line 
https://github.com/encode/django-rest-framework/blob/master/rest_framework/request.py#L384
when the error is in other place 
instead reraise an error that doesn't explain the problem, I just replace with pass and I got the real errors . 

some examples:  
https://github.com/aschn/drf-tracking/issues/38 
https://www.google.pt/search?q=AttributeError%3A+%27WSGIRequest%27+object+has+no+attribute+%27accepted_renderer%27&ie=utf-8&oe=utf-8&client=firefox-b&gfe_rd=cr&ei=ysTrWKuOGfSJ8QeUo4rgCQ

**Comment by xordoquy** [comment]
I'm going to close this as we don't have enough actionable content here.

> 'WSGIRequest' object has no attribute 'accepted_renderer'

usually means someone is using a Django `Request` where Django REST framework expected its own `Request`.

I'll reconsider this issue if there's a clear test case to demonstrate it.

**Comment by sergiomb2** [comment]
Fair enough , I don't know the solution but what I'm trying point out is the error message don't have nothing with the problem I can provide one example: 

```
from rest_framework.negotiation import DefaultContentNegotiation
import logging

class IgnoreClientContentNegotiation(DefaultContentNegotiation):

    logger = logging.getLogger(__name__)
    def select_renderer(self, request, renderers, format_suffix):
        """
        Select the first renderer in the `.renderer_classes` list.
        """
        # logger = logging.getLogger(__name__)
        # Allow URL style format override.  eg. "?format=json
        format_query_param = self.settings.URL_FORMAT_OVERRIDE
        format = format_suffix or request.query_params.get(format_query_param)
        logger.error("adsl %s %s e o format = %s" % (format_query_param,
        request.query_params.get(format_query_param), format))

        if format is None:
            return (renderers[0], renderers[0].media_type)
        else:
            return DefaultContentNegotiation.select_renderer(self, request, renderers, format_suffix)
```
I can see the correct message ( During handling of the above exception (name 'logger' is not defined), another exception occurred:  ) when I put pass in exception .  
when as is I got the  message : During handling of the above exception ('WSGIRequest' object has no attribute 'accepted_renderer'), another exception occurred:

**Comment by xordoquy** [comment]
Then it's likely you defined a custom exception handler that doesn't return a DRF response in which case you have two exceptions that you have to fix and feels consistant with the exposed behavior here.

**Comment by sergiomb2** [comment]
I don't think that I add any  custom exception handler, I just follow tutorial this example is very strait forward ... ( http://stackoverflow.com/a/43343963/778517 ) 
BTW  in this snippet [1] BaseContentNegotiation should be replaced by DefaultContentNegotiation ... 

Thanks for the replies 

[1] http://www.django-rest-framework.org/api-guide/content-negotiation/#setting-the-content-negotiation
