### ISSUE TITLE
Recommended improvement to default metadata creation (minor)

### ISSUE THREAD

**Issue by bcoover** [encode/django-rest-framework#5069]
As I was working with metadata to add some custom stuff, I noticed that the (very helpful) `action` section was missing on my read-only models. Even for read-only models, it is very helpful to have the data types documented in OPTIONS, so consumers of the API can know what data to expect. To work around this, I had to override `determine_actions` to change:

https://github.com/encode/django-rest-framework/blob/master/rest_framework/metadata.py#L80

from:
        `for method in {'PUT', 'POST'} & set(view.allowed_methods):`

to:
        `for method in {'PUT', 'POST', 'GET'} & set(view.allowed_methods):`

Per this, I am just recommending that this be the default.

**Comment by tomchristie** [comment]
I think if we were going to make any further changes to the default OPTIONS implementation it'd need to be in line with some existing standard. We get plenty of requests to modify it in different ways, and if really rather see eg third party packages take those alternative renderings on, unless we've got a clear standard to work against for the default case.
