### ISSUE TITLE
Options/Schema/Metadata in documentation?

### ISSUE THREAD

**Issue by bcoover** [encode/django-rest-framework#5070]
I have searched but I am not able to find anything about this... I am not sure if this is an issue, or by design, but the awesome functionality of the "OPTIONS" button in browsable API, is not available in the documentation pages (which are also awesome BTW). It would be VERY helpful to have ALL of that data, especially field `type` available in the documentation (I see that Parameter name and Description are already there).

Just to be clear, I am referring to the separate auto-created docs pages (which I believe are COREAPI). It would make the documentation pages more useful if they included ALL of the details about the fields, or at least the ability to enable them. Specifically I am referring this this (from OPTIONS), here is the `actions` section of the OPTIONS data for a given view:

    "actions": {
        "GET": {
            "url": {
                "type": "field",
                "required": false,
                "read_only": true,
                "label": "Url"
            },
            "is_active": {
                "type": "boolean",
                "required": false,
                "read_only": false,
                "label": "Is active",
                "help_text": "Enable/Disable"
            },
            "name": {
                "type": "string",
                "required": true,
                "read_only": false,
                "label": "Name",
                "help_text": "Enter a unique name",
                "max_length": 254
            },
            "description": {
                "type": "string",
                "required": false,
                "read_only": false,
                "label": "Description",
                "help_text": "Expanded description of the item",
                "max_length": 254
            },
            "note": {
                "type": "string",
                "required": false,
                "read_only": false,
                "label": "Note",
                "help_text": "Additional notes"
            }
        }
    }

## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.

**Comment by tomchristie** [comment]
Totally fair question, but I'm not currently planning to include an interactive model for `OPTIONS` responses.

OPTIONS is different to the other handled methods in that it doesn't reflect an interaction with the server, but rather returning metadata about it. OPTIONS requests are not exposed to the client libraries, and we won't be exposing them in the docs either.
