### ISSUE TITLE
Improve nested serializer in API documentation

### ISSUE THREAD

**Issue by jpadilla** [encode/django-rest-framework#5072]
## Steps to reproduce

```python
class ASerializer(serializers.Serializer):
    name = serializers.CharField()


class BSerializer(serializers.Serializer):
    name = serializers.CharField()
    animal = ASerializer()
```

## Expected behavior

Expose parameters from nested serializers. A custom `docs/link.html` template allowed me to expose at least one level pretty easy by doing:

```
{% for field in link.fields|with_location:'form' %}
<tr>
  <td class="parameter-name"><code>{{ field.name }}</code>{% if field.required %} <span class="label label-warning">required</span>{% endif %}</td><td>{% if field.schema.description %}{{ field.schema.description }}{% endif %}</td>
  {% if field.schema.properties %}
    {% for name, nested_field in field.schema.properties.iteritems %}
      <tr><td class="parameter-name" style="padding-left: 25px;"><code>{{ name }}</code>{% if nested_field.required %} <span class="label label-warning">required</span>{% endif %}</td><td>{% if nested_field.schema.description %}{{ nested_field.schema.description }}{% endif %}</td></tr>
    {% endfor %}
  {% endif %}
</tr>
{% endfor %}
```

<img width="514" alt="screen shot 2017-04-11 at 11 35 09 am" src="https://cloud.githubusercontent.com/assets/83319/24917607/b657141c-1eab-11e7-89e9-cc61cb5bcebb.png">

[Stripe's API Reference](https://stripe.com/docs/api#create_customer) handles this pretty nice and I think is something we could look up to for reference.

![stripe-api](https://cloud.githubusercontent.com/assets/83319/24917727/14381338-1eac-11e7-884d-3ca09def96e0.gif)

## Actual behavior

<img width="524" alt="screen shot 2017-04-11 at 11 34 59 am" src="https://cloud.githubusercontent.com/assets/83319/24917385/04e27c08-1eab-11e7-88d4-20fb5f09eb1f.png">

**Comment by tomchristie** [comment]
Yup, agreed.

**Comment by jpadilla** [comment]
@tomchristie I'll be taking a stab at a first iteration in the next couple of days. Have also been thinking about how we could also improve the actual interact form, right now you get a textarea with a `{}`. Might be interesting to treat nested serializer as a form group there as well. Thoughts?

**Comment by tomchristie** [comment]
> Might be interesting to treat nested serializer as a form group there as well.

100% yes. Awkward, in the same way that it's awkward for us to do in the browsable API, but at least in this case we'd be marshalling it into JSON by the time we're actually making the request.

**Comment by MohamedShawky** [comment]
Hey @jpadilla

i need to create nested serializers 
can you help me?

**Comment by xxmatyuk** [comment]
Hi folks, 

yesterday I was frustrated facing this issue, and today came up with the solution. It's hacky now, but if you're okay with the approach, I'll come up with PR.

Normally, you should define all such kind of structures in one place, so what I did is simply walked through all the links, collected nested objects and stored them in schema's root under 'definitions' key. Later on, when encode._get_parameters is called, I simply check whether the field_type is object, and, if so, update schema with reference. 

Works fine. There're also a few cases that should been handled, e.g. an array of objects, of even arrays should be handled the same way, but the idea is to add definitions seems to be good.

**Comment by lucasmpaim** [comment]
+1

**Comment by kolanos** [comment]
@jpadilla Any updates on this issue?

**Comment by jpadilla** [comment]
@kolanos I'm not actively working on this at the moment.
