### ISSUE TITLE
Upgrade Demo app to 3.7

### ISSUE THREAD

**Issue by hassanshamim** [encode/django-rest-framework#5074]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
click http://restframework.herokuapp.com/

## Expected behavior
I was hoping to get a live example of the new interactive API documentation in 3.6.  Instead I just upgraded one of the simpler apps I had my computer.  Is this the end result of the [rest-tutorial](https://github.com/tomchristie/rest-framework-tutorial)?  If so that's already been upgraded to 3.5, just not deployed it seems.

## Actual behavior
Using DRF 3.1

**Comment by ka7eh** [comment]
Updated in https://github.com/tomchristie/rest-framework-tutorial/pull/34

**Comment by tomchristie** [comment]
Not really a version-specific thing, but milestoning to keep it towards to top of the pile.
Just needs to be re-deployed.

**Comment by carltongibson** [comment]
@tomchristie Any chance you could do a deploy for 3.7?

**Comment by carltongibson** [comment]
@tomchristie v.3.7.0 will be tagged at eb3d078a2cbda2d6e576cbfd773f153d1bdf5c5b

**Comment by carltongibson** [comment]
Moving this over to the tutorial repo: https://github.com/encode/rest-framework-tutorial/issues/41
