### ISSUE TITLE
How do you implement custom response?

### ISSUE THREAD

**Issue by daiyanze** [encode/django-rest-framework#5080]
I found that the DRF's return value could be various upon different occasions. So I want to make sure all my JSON return have "code" "message" or other values nested inside in order to keep consistency of my APIs.
For example:
#### Success
`
{"code": 1, "status": "success", "message": "", `
` "data": [{"id": 1, "name": "John Doe", "email": "johndoe@gmail.com"}]}
`
#### Error
`
{"code": -1, "status": "error", "message":"Something went wrong","data": [] }
`

The return will always have "code" "status" "message" "data" inside whatever the result would become. 

After looked up in Google but couldn't find any work-around over DRF. So I suppose everybody is redefining the APIViews or Mixins (get put post etc. ) to control the response. But I am not very sure if the return should be that widely different without a certain pattern. Or is it cool that DRF's JSON response could be directly adopted as a production case?

Hope to have some advice from you guys.
Thanks.

**Comment by xordoquy** [comment]
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!

**Comment by Xmas118** [comment]
Did you solve this?
