### ISSUE TITLE
Feature Request: Json and Yaml editor when posting

### ISSUE THREAD

**Issue by myrubapa** [encode/django-rest-framework#5090]
I think we (rest framework community) need good editor like (http://nodeca.github.io/js-yaml/ ) when add data 
![rest1](https://cloud.githubusercontent.com/assets/1535825/25302414/d4d3cbac-2756-11e7-97c5-e18b1c035a25.png)

**Comment by tomchristie** [comment]
I'd be receptive to pull requests adding a nice JSON editor, or to suggestions for JSON editors (the one linked appears to be a YAML editor, so I'm not sure if we'd want that) however I don't think this is something we're going to have on the immediate horizon unless someone takes it on externally.
