### ISSUE TITLE
Bad formatting at http://www.django-rest-framework.org/tutorial/7-schemas-and-client-libraries/#adding-a-schema

### ISSUE THREAD

**Issue by dilyanpalauzov** [encode/django-rest-framework#5091]
At http://www.django-rest-framework.org/tutorial/7-schemas-and-client-libraries/#adding-a-schema

the text "url(r'^schema/$', schema_view), ... ]" shall be marked as code.  This text follows "url(r'^schema/$', schema_view), ... ]", which is marked as code.

**Comment by jpadilla** [comment]
Closed via #5040. The docs will be rebuilt next time we release a new version.

**Comment by tomchristie** [comment]
Thanks @jpadilla!
