### ISSUE TITLE
http://www.django-rest-framework.org/api-guide/serializers/: clarify reversed relationships and __all__

### ISSUE THREAD

**Issue by dilyanpalauzov** [encode/django-rest-framework#5092]
At http://www.django-rest-framework.org/api-guide/serializers/ is written:

"You can also set the `fields` attribute to the special value ` '__all__'` to indicate that all fields in the model should be used."

This should be altered in "all fields in the model, except reverse relation, should be used."

**Comment by xordoquy** [comment]
We are in line with the Django documentation here.
Please note that reversed relations are not considered as a model's field as they are declared in another model.
