### ISSUE TITLE
RelatedField queryset argument should not be mandatory

### ISSUE THREAD

**Issue by dan-passaro** [encode/django-rest-framework#5095]
The `RelatedField` class and subclasses will fail to instantiate if `queryset=` is not provided or a `get_queryset()` implementation is not provided.

This implies that `RelatedField` itself does something with this attribute, when in fact it does nothing. It's entirely up to the subclass to make use of this method.

This is surprising.  As a new user I assumed that, perhaps, if the `queryset` argument is mandatory, `RelatedField` must have some validation of some sort that makes use of it. But that's not true. In my subclass, I was able to set `queryset` to e.g. `User.objects.none()`, and I was able to override `get_queryset()` to have `assert False is True` as the body, with no change in application behavior.  But if I simply left queryset out altogether, the app fails to run.

I see that the built-in subclasses of `RelatedField` all seem to use `get_queryset()` when doing lookups in the `to_internal_value()` method.  However, this is all something the subclasses have in common. Since it has no impact on `RelatedField` itself it should not be something that's required at that level of the API.

**Comment by tomchristie** [comment]
It's mandatory only if the relationship is writable (in which we need to have it in order to lookup the instances). If the field is read only it's not required.

**Comment by dan-passaro** [comment]
@tomchristie perhaps I'm reading the source of the class wrong but it doesn't appear to do any lookup either way. The subclasses do, but `RelatedField` itself will not.

**Comment by tomchristie** [comment]
You're right but it *is* a base class, not something you'd use by itself.

**Comment by dan-passaro** [comment]
The confusion comes in as a user of the base class. Docs suggest extending this class directly, and I did. I was surprised to find this argument was required even though it wasn't used anywhere. As I noted I was able to add `assert False is True` as an implementation so my code would run

**Comment by rpkilby** [comment]
The `queryset` argument is used for generating choices, just not during validation since `RelatedField` does not perform validation. 

A few possible improvements:
- Add a `method_overridden` check for `.to_representation()`.
- Add a `method_overridden` check for `.to_internal_value()` if the RelatedField is writable.
- Add docs to the fields class that more clearly indicates that it's a base class, and that the above methods should be overridden.
