### ISSUE TITLE
api-docs and app namespaces

### ISSUE THREAD

**Issue by dilyanpalauzov** [encode/django-rest-framework#5096]
We run the django-rest-framework app in a separate namespace, (called 'api'), so the code in `rest_framework/templates/rest_framework/docs/index.html` and `rest_framework/templates/rest_framework/docs/langs/javascript-intro.html`: `<script src="{%url 'api-docs:schema-js' %}' %}"></script>` does not work.  The correct spelling would be `{%url 'api:api-docs:schema-js'%}`

**Comment by tomchristie** [comment]
Make sure to include the schema at the top level of the routing.
You can still include the rest of the API inside a namespace.

**Comment by dilyanpalauzov** [comment]
I want to include the schema within the app, because it belongs there.

**Comment by dilyanpalauzov** [comment]
python -Wd manage.py runserver 0.0.0.9:80

/virtualenv/lib/python3.5/site-packages/rest_framework/documentation.py:50: RemovedInDjango20Warning: Specifying a namespace in django.conf.urls.include() without providing an app_name is deprecated. Set the app_name attribute in the included module, or pass a 2-tuple containing the list of patterns and app_name instead.
  return include(urls, namespace='api-docs')
