### ISSUE TITLE
Return 405 on disallowed verbs regardless of authentication status

### ISSUE THREAD

**Issue by jamesmallen** [encode/django-rest-framework#5101]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
1. Send a `DELETE` request to an `APIView` that has `permissions_classes` set, but no `delete` method.

## Expected behavior
1. Should receive `HTTP 405 Method not allowed`

## Actual behavior
1. Receive `HTTP 403` or `HTTP 401`

According to the [HTTP Decision Diagram](https://github.com/for-GET/http-decision-diagram) (not an RFC, but supposedly built according to the relevant RFCs), HTTP 405 should be returned if the method isn't allowed, even if the user is not authenticated. Due to the way Django dispatches views, it checks permissions and thus raises permissions-related errors before checking to see if the appropriate verb method exists.

I will attach a PR with a failing test shortly.

**Comment by tomchristie** [comment]
The design is intentional in that we want to mask as much information as possible if the request is not permitted.

**Comment by tomchristie** [comment]
Thanks for raising it tho, and stating the issue clearly! 😄

**Comment by jamesmallen** [comment]
@tomchristie I definitely appreciate the desire to mask information - however, `OPTIONS` requests still return the list of allowed methods, so this seems inconsistent.

**Comment by tomchristie** [comment]
Fair! I'd certainly consider removing them there.

**Comment by wojsamjan** [comment]
Probably similar issue.

generics.RetrieveDestroyAPIView

During tests (PUT & PATCH):
- logged in as normal user -> 403
- logged in as admin user -> 405

I would expect 405 for both, at least consistency (as you explained this behaviour as intentional)
