### ISSUE TITLE
Support Python3.6 and Django 1.11

### ISSUE THREAD

**Issue by zbing3** [encode/django-rest-framework#5108]
When to support Python3.6 and Django 1.11 ？

**Comment by atkawa7** [comment]
See https://docs.djangoproject.com/en/1.11/releases/1.11/

**Comment by xordoquy** [comment]
We should make a release that officially states those. Though Django 1.11 wasn't released Django REST framework 3.6 should support it.

**Comment by tomchristie** [comment]
We already list Django 1.11 in the README, but Python 3.6 was missing.
Needs a new docs build to push the changes to the site, too.
