### ISSUE TITLE
jython support ?

### ISSUE THREAD

**Issue by yishenggudou** [encode/django-rest-framework#5109]
DRF  support jython ?

**Comment by xordoquy** [comment]
Haven't hear about someone that did use it. Try to run the test suite under and see if that passes.

**Comment by rpkilby** [comment]
As far as officially supporting jython via the test suite, it doesn't look like travis has a jython [build](https://docs.travis-ci.com/user/languages/python/).

**Comment by xordoquy** [comment]
unrelated but we may add a peppy build :p

**Comment by yishenggudou** [comment]
I have successfully run on jython  and tomcat

**Comment by xordoquy** [comment]
@yishenggudou thanks for the feedback :)
