### ISSUE TITLE
Support MySQL JSON  Fields 

### ISSUE THREAD

**Issue by sergiomb2** [encode/django-rest-framework#5111]
as my $dayjob was looking support for mysql 5.7 with json fields , I tried 

```
https://pypi.python.org/pypi/django-jsonfield 
https://pypi.python.org/pypi/jsonfield
from rest_framework.serializers import JSONField
from django.contrib.postgres.fields import JSONField
https://pypi.python.org/pypi/django-mysql
```
and as asked the same feature for postgres [1] I asked for mysql 

Thanks 
[1] https://github.com/encode/django-rest-framework/issues/3170

**Comment by xordoquy** [comment]
Postgres support for JSON field has been made possible by Django supporting it.
Unless Django adds a support for a JSONField for MySQL, we won't add it to DRF.
You can still make it a 3rd party or integrate it "natively" in your project by doing something similar to:

    serializer_field_mapping[ModelJSONField] = JSONField

**Comment by sergiomb2** [comment]
JFTR : this is done with django-mysql and serializer was fixed some day ago [1], is not yet in any release.
 
[1] https://github.com/adamchainz/django-mysql/issues/353
