### ISSUE TITLE
customization of the login template

### ISSUE THREAD

**Issue by djangoliv** [encode/django-rest-framework#5120]
## Steps to reproduce
extend the login template of DRF (mylogin.html)
```
{% extends "rest_framework/login_base.html" %}
{% block branding %}
  <h3 style="margin: 0 0 20px;">My site</h3>
{% endblock %}
```
with urls.py:

```
urlpatterns = [
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^login', login, "mylogin.html", name='login'),
    url(r'^logout', logout, "mylogin.html", name='logout'),]
```
Go to http://127.0.0.1:8000/login/ and enter user with  wrong password

## Expected behavior
Stay on http://127.0.0.1:8000/login/

## Actual behavior
Go to http://127.0.0.1:8000/api-auth/login/ and loose my template extension.

Regards

**Comment by xordoquy** [comment]
The url order is wrong and you didn't provide the namespace.

Please note that the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!

**Comment by djangoliv** [comment]
Thanks for your answer.
