### ISSUE TITLE
BooleanField may return None

### ISSUE THREAD

**Issue by ziima** [encode/django-rest-framework#5124]
`BooleanField` according to its description should only work with `True` or `False` values. But in some cases, it can return `None` as a serialized value, thus returning data, which itself wouldn't validate.

## Steps to reproduce
```python
from rest_framework import serializers
from django.contrib.auth.models import User

class UserSerializer(serializers.ModelSerializer):
    password = serializers.BooleanField()
    class Meta:
        model = User
        fields = ('password',)

UserSerializer(User(password=None)).data
#>>> ReturnDict([('password', None)])
```
## Expected behavior
`BooleanField` should serialize values into either `True` or `False`. `None` should be serialized into `False`.

## Actual behavior
`BooleanField` serializes `None` into `None`.

**Comment by tomchristie** [comment]
The serializer fields validate user input, and will attempt to coerce outputs, but they don't strictly validate the instances you pass to them for output.

**Comment by ziima** [comment]
I don't want the `BooleanField` to validate the data, I just want it to coerce it correctly.

**Comment by tomchristie** [comment]
Understood. There's not a lot we can do about that easily, as we don't run the `to_representation` for the `None` case, but just pass that through as-is.

I'd suggest taking a look at why you have `None` values for something where the input should always validated as a boolean, and fix that.

**Comment by ziima** [comment]
There's nothing wrong with the models, we probably just hit unusual use case. We want a degraded API. While we have complete information about the user's authentication in database, we want to provide only information about the authentication methods user have set up, naturally for security reasons.

So we have models such as
```python
class Certificate(models.Model):
    user = models.OneToOneField(User)
    # ...data

class OneTimePassword(models.Model):
    user = models.OneToOneField(User)
    # ...data
```

I wanted to create a simple serializer, since I saw no problem in that
```python
class UserSerializer(serializers.ModelSerializer):
    certificate = serializers.BooleanField()
    otp = serializers.BooleanField()
    class Meta:
        model = User
        fields = ('certificate', 'otp')
```
but here comes my surprise, when the `BooleanField` returns `None` and not `False` for a users which don't have certificate or OTP set up.

I estimate the fix would help in design of any `has_<something>` field, since that's something that can come handy, but more over, the `BooleanField` wouldn't return type of data which itself wouldn't accept.
