### ISSUE TITLE
Extra Deprecation notice in release notes of 3.3

### ISSUE THREAD

**Issue by rvanlaar** [encode/django-rest-framework#5125]
The web application we wrote depended on "application/x-www-form-urlencoded". 
This was a documented feature: 

http://djangorestframework.readthedocs.io/en/latest/topics/browser-enhancements/

This is however deprecated since 3.3.0 per here:

http://www.django-rest-framework.org/topics/browser-enhancements/#browser-based-submission-of-non-form-content

However none of this is found in the release notes. The place where I look to see if I need to upgrade and change parts of my application.

I would like this notice to be in the deprecation list of on the 3.3 release notice.

**Comment by tomchristie** [comment]
I think I know what you're asking, tho I'm not totally sure. The `application/x-www-form-urlencoded` media type is still supported. Do you mean the content and content-type overriding that the browsable API supported (tunnelling JSON using form encoding)? If so then that gets a mention, here... http://www.django-rest-framework.org/topics/3.3-announcement/#deprecations

We could highlight it further, but 3.3 is a while back and we've not had this raised before, so I'm not particularly inclined to treat it as a priority.

**Comment by rvanlaar** [comment]
I meant the content overloading issue. Now that I've read the deprecations again I see that it's mentioned.
