### ISSUE TITLE
Nested Serializer

### ISSUE THREAD

**Issue by MohamedShawky** [encode/django-rest-framework#5136]
## Checklist

- [ ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [ ] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

**Comment by MohamedShawky** [comment]
which i have a model called Qusetion
and another model called Answer

class Qustion(models.Model):
user = models.ForeighnKey(User)
content = models.CharField(max_length=100)
title= models.CharField(max_length=100)

class Answer(models.Model):
question = models.ForeignKey(Question on_delete=models.CASCADE)
content = models.IntegerField()
date = models.TimeField()
user = models.ForeighnKey(User)

expected output like this

[
{
"id": 2,
"content": "this is first post comment",
"comment": [
{
"user": {
"id": 1,
"username": "m_mohamed",
},
"content": "this is first comment",
"date": "2017-05-14T21:40:48.123368Z"
}
],
"publish_user": {
"id": 2,
"username": "H_mohamed",
}

]

}

**Comment by xordoquy** [comment]
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions.
Please note that the more context you'll provide the more likely you'll get help.
Thanks!

**Comment by MohamedShawky** [comment]
@xordoquy  
thank you>
