### ISSUE TITLE
request.data has a memory leak

### ISSUE THREAD

**Issue by imdark** [encode/django-rest-framework#5146]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

1. create an api view like so:

I tested this with cpython 2.7 on a macOS 10.12.4 :

```
from __future__ import absolute_import, unicode_literals

from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response

@api_view(['POST'])
def memory_leak(request):
    request_data = request.data
    return Response(request_data, status.HTTP_201_CREATED)

```

and just curl against it with large json objects, testing with `ps` between calls:
```
echo '["'$(dd if=/dev/zero bs=1 count=10) '"]' | curl -XPOST http://localhost:8080 -d @-
```

and if you look at RSS in ps memory mostly just go up and never released

## Expected behavior

rss memory will be released between requests and will go

## Actual behavior
rss memory goes up and almost never released

**Comment by rooterkyberian** [comment]
As JSON parser used is DOM-style parser everything has to be loaded into memory. With how memory management behaves, your reported RSS will still go up after processing request whatever you do, but this memory will be reused during handling of other requests so I wouldn't call it "leaking".

Addressing this, like you in #5147, with making sure we don't use too much memory on single request seems like a right choice, but "RSS" will still go up and stay up - and that is something you most likely wouldn't be able to fix without going down to CPython-level.

**Comment by tomchristie** [comment]
Indeed cPython's memory allocation pattern isn't "leaking", although it does hold on to previously allocated memory to be reused subsequently. Also agreed that reducing the memory footprint as in #5147 is a valid improvement.
