### ISSUE TITLE
Django Rest framework doc(basic) doesn't support links like /accounts/password-reset.

### ISSUE THREAD

**Issue by alex1vanchik** [encode/django-rest-framework#5152]
Hi. Guys, I have a problem. Django Rest framework doc(basic) doesn't support links like /accounts/password-reset. I used to documenting my api. Maybe I'm doing something wrong or this doesn't support.  Can someone help me?

**Comment by tomchristie** [comment]
You'll probably need to rephrase that as I could understand exactly what you meant. Which docs are you referring to? The autoogrnerated API docs?

In any case the best place to take usage questions is the discussion group: https://groups.google.com/forum/m/#!forum/django-rest-framework

**Comment by alex1vanchik** [comment]
Hi Tom,
Thanks for answerin. I'm very glad that you answered
I used to The autoogrnerated API docs(From the core of Django Rest framework
).
For generation I use generics, viewsets, mixins.
Simple example:
users/ - Displayed in documentation
users/{id} - Displayed in documentation
users/personal-profile - Not displayed in documentation

class UserPersonalProfile(generics.RetrieveUpdateAPIView):
    permission_classes = (permissions.IsAuthenticated,)
    serializer_class = UserSerializer
    queryset = User.objects.all()

    def get_object(self):
        return self.request.user

​For the account does not work at all since there endpoints like:
/accounts/base-sign-up
/accounts/base-auth-token
/accounts/sn-auth-token


2017-05-18 14:12 GMT+03:00 Tom Christie <notifications@github.com>:
