### ISSUE TITLE
The autoogrnerated API docs(From the core of Django Rest framework) doesn't support endpoints like /accounts/password-reset.

### ISSUE THREAD

**Issue by alex1vanchik** [encode/django-rest-framework#5156]
Guys, I'm sorry I'm writing here. But only here I can get an answer. Since I already wrote https://gitter.im/tomchristie/django-rest-framework , https://groups.google.com/forum/m/#!topic/django-rest-framework/9bc7IKn9oYI, https://github.com/encode/django-rest-framework/issues/5152 . But I did not receive a response.

I used to The autoogrnerated API docs(From the core of Django Rest framework).
For generation I use generics, viewsets, mixins.
Simple example:
users/ - Displayed in documentation
users/{id} - Displayed in documentation
users/personal-profile - Not displayed in documentation

class UserPersonalProfile(generics.RetrieveUpdateAPIView):
    permission_classes = (permissions.IsAuthenticated,)
    serializer_class = UserSerializer
    queryset = User.objects.all()

    def get_object(self):
        return self.request.user

​For the account does not work at all since there endpoints like:
/accounts/base-sign-up
/accounts/base-auth-token
/accounts/sn-auth-token

![example](https://cloud.githubusercontent.com/assets/28433163/26202117/db1643fe-3bde-11e7-980b-772261b79016.jpeg)

**Comment by xordoquy** [comment]
Hi,
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
If you didn't got an answer there, try to narrow down the issue and/or rephrase it. Keep in mind that it's unpaid volunteer answers.
If you think it's a Django REST framework issue, it'll greatly help to have a minimal test case we case reproduce.

**Comment by carltongibson** [comment]
This is the same problem as https://github.com/encode/django-rest-framework/issues/5077

The generated schema includes all endpoints but the documentation template does not display them. There are some preliminary workarounds list on #5077 but it's currently a known limitation.

**Comment by carltongibson** [comment]
@alex1vanchik There's no need to 👍 and comment on the other issue — it's just adds noise. (Using the 👍is sufficient. (Thanks!)
