### ISSUE TITLE
rename of model with non-default primary key field results in create rather than rename

### ISSUE THREAD

**Issue by cjw296** [encode/django-rest-framework#5158]
## Steps to reproduce

Have a model, serializer, view, router as:

```python
class MyModel(models.Model):
    name = models.CharField(max_length=100, primary_key=True)

class MyModelSerializer(serializers.ModelSerializer):
    class Meta:
        model = MyModel
        fields = '__all__'

class MyModelViewSet(viewsets.ModelViewSet):
    queryset = MyModel.objects.all().order_by('name')
    serializer_class = MyModelSerializer

router = DefaultRouter()
router.register(r'mymodel', MyModelViewSet)
urlpatterns = patterns('',
    url(r'^api/', include(router.urls)),
)
```

Now PUT  `{'name': 'new-name'}` to `/api/mymodel/some-existing-name`

## Expected behavior

Existing model instance is renamed.

## Actual behavior

A new model named `new-name` is created and the existing `some-existing-name` is ignored.

**Comment by mcspud** [comment]
At first glance I believe it is because you haven't declared a `lookup_field` on the `Viewset` class.
See docs: http://www.django-rest-framework.org/api-guide/serializers/

**Comment by xordoquy** [comment]
According to me, this is linked to Django's default behavior on PK:

    MyModel.objects.all()
    # <QuerySet [<MyModel: test>, <MyModel: test1>]>
    instance = MyModel.objects.all()[0]
    instance.name
    # 'test'
    instance.name = 'other test'
    instance.save()
    MyModel.objects.all()
    # <QuerySet [<MyModel: test>, <MyModel: test1>, <MyModel: other test>]>


I'm closing this ticket as I do think that handling automatically PK could break things in particular when/if you have FK pointing to it and I foresee too many edge cases that would make it too magic.

**Comment by cjw296** [comment]
@xordoquy - let's see what the django folk say: https://code.djangoproject.com/ticket/28228

**Comment by tomchristie** [comment]
Actual behavior in this case is that `400 {'name': ['mymodel with this name already exists.']}` is raised. However it's fairly easy to accidentally remove the default uniqueness check that we provide with `ModelSerializer` (eg. using `validators` in `extra_kwargs`, or by specfiying the field explicitly and not including the uniqueness constraint)

Nothing else we can do here, but clarifying the root issue against the django ticket above.

**Comment by tomchristie** [comment]
https://code.djangoproject.com/ticket/28228#comment:7
