### ISSUE TITLE
Documentation Style overrides similar to Django Admin customization

### ISSUE THREAD

**Issue by Brobin** [encode/django-rest-framework#5169]
This is more of an idea than an issue with drf.

I would love to see some sort of customization options for the style of the documentation pages. The django admin app has blocks such as `extra_style`, `branding`, `title` etc. that allow injecting extra styles and content into the base layout of the admin page. 

Example, adding a custom font and some css:

```html
{% extends "docs/base.html" %}
{% load staticfiles %}
{% block extra_style %}
    <link href="https://fonts.googleapis.com/css?family=Product+Sans" rel="stylesheet">
    <link href="{% static 'css/docs.css' %}" rel="stylesheet" />
{% endblock %}
```

I am currently doing this by copying the entire `docs/index.html` template and editing that, but I think we can do it cleaner. I'd be more than willing to help out in making this possible if this is something that is deemed useful.

**Comment by carltongibson** [comment]
@Brobin I think this would be a reasonable addition. If you want to submit a PR that would be welcome. 

I'm going to close this ticket: whilst it's an enhancement it's not something I want to allocate time to right now. 

That PR is very welcome though! 🙂
