### ISSUE TITLE
Custom Token models

### ISSUE THREAD

**Issue by samfrances** [encode/django-rest-framework#5171]
I'm looking to create a custom subclass of the Token model, but one customised not to authenticate as a particular user, but to grant permissions to a particular model instance of a non-User model.

The current `Token` model doesn't make that very easy, because there isn't a way to change or get rid of the `user` field on a custom sublass of `Token`.

It occurred to me that it would be fairly easy, without any change in functionality, to split `Token` into a base class `TokenBase` that has all the fields and methods apart from `user`, and then have `Token` essentially look like the following:

```
class Token(BaseToken):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, related_name='auth_token',
        on_delete=models.CASCADE, verbose_name=_("User")
    )
```

Then `BaseToken` could be used as the basis for other forms of token which associate to different models.

I understand that there's a desire to keep the built-in token app as simple as possible. However, this would not materially change the way the built-in tokens work, while providing greater scope for customisation.

In any case, I wanted to scope out whether there would be any support or appetite for this proposal.

**Comment by carltongibson** [comment]
The packaged authentication token implementation is deliberately kept simple. You are welcome (and encouraged) to use it as a base for your own token implementation (matching your own needs) but this is not something that would be added to the core.

**Comment by samfrances** [comment]
I guess the point I was making was that the current class is difficult or impossible to use as a base for your own implementation if you don't want to link the token to a user. (At least, if "base" means "base class" rather than "copying the code and modifying").

In any case, thanks for taking the time to consider my suggestion.

**Comment by carltongibson** [comment]
> At least, if "base" means "base class" rather than "copying the code and modifying"

Indeed 🙂 — but here it does mean "copying the code and modifying" — and that's a long-standing design decision.

**Comment by bobozar** [comment]
Hello @carltongibson ,

I want to use Rest Token on different sites e.g test.example.com and production.example.com. I want a situation whereby each domain will have different Token Key. The difference can be 60 random hexadecimal for Test and 80 random hexadecimal for Production. I want to avoid a situation whereby a Token on a test site can't be used on Production site. Can I set params for that in settings.py like TOKEN-AUTH= {'token_length':60} or just sublcass the Token models and add my own fields and methods? What do you suggest?
