### ISSUE TITLE
Include a manage.py command to create user token

### ISSUE THREAD

**Issue by andreagrandi** [encode/django-rest-framework#5173]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

After I create a user (`myuser`), if I want to create an auth token for it, I have to:

1) open a shell: `./manage.py shell`

2) execute:

```
from django.contrib.auth.models import User
from rest_framework.authtoken.models import Token

user = User.objects.get(username='myuser')
Token.objects.get_or_create(user=user)
```

## Expected behavior

It would be useful to have something like:

```
./manage.py drf-token-create myuser
Token for user 'myuser' created: fasd8fgashfas8fygasfdyhasidfaoiufdgaf
```

## Actual behavior

There is no such command.

## Note

If there is enough interest for this feature and you think it may be useful for other people, I'm happy to code it in my spare time. I would be glad to finally contribute back to DRF with some code.

**Comment by tomchristie** [comment]
Yeah I think we'd probably accept that. Pull requests very welcome. I'll close off the ticket in the meantime as it's not something I think we'd pick up on our own steam otherwise.

**Comment by andreagrandi** [comment]
@tomchristie hi Tom! Thanks for your reply. If I self-assign this to me, are you ok to re-open the issue? Or do you prefer me to just:

1) fork the code
2) make the PR
3) use the above description when I will do the final PR

Cheers

**Comment by tomchristie** [comment]
Yup make the PR, and include the description there (no harm in linking here too).

For things where we're happy for someone to progress them in a pull request, but wouldn't otherwise act on them I'd rather we close off the active issue, and act on the PR on it's own merit.

Thanks!
