### ISSUE TITLE
Tutorial 1 - Github source link is broken

### ISSUE THREAD

**Issue by staypufd** [encode/django-rest-framework#5178]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
1. Go to:  http://www.django-rest-framework.org/tutorial/1-serialization/
2. See third paragraph that starts with:
Note: The code for this tutorial is available in the tomchristie/rest-framework-tutorial repository on GitHub
3. Click the link:   tomchristie/rest-framework-tutorial 
4. It tries to go to:  https://github.com/encode/rest-framework-tutorial and does, but gets a 404 error

## Expected behavior
Expect to be taken to the source code for the tutorial

## Actual behavior
Goes to GitHub at:  https://github.com/encode/rest-framework-tutorial and there is nothing there, so it shows 404 error screen.

**Comment by jpadilla** [comment]
Ah right. Correct location is https://github.com/tomchristie/rest-framework-tutorial. @tomchristie want to transfer that repo to the encode org?

**Comment by staypufd** [comment]
thx

**Comment by xordoquy** [comment]
Fixed. Thanks for reporting it.
