### ISSUE TITLE
Compressing coreapi and schema.js

### ISSUE THREAD

**Issue by bluesurfer** [encode/django-rest-framework#5180]
I am using `django-compressor` to minify my static sources. It seems there's a problem if I try to compress `coreapi` and `schema.js`.

When compressing using `compress` tags:

    {% compress js  %}
        
        <script src="{% static 'rest_framework/js/coreapi-0.1.0.js' %}"></script>
        <script src="{% url 'api-docs:schema-js' %}"></script>
        
        

    {% endcompress %} 

Then I get:
`
/api/docs/schema.js' isn't accessible via COMPRESS_URL ('/static/') and can't be compressed
`
Therefore, I have to keep these js file uncompressed. What a waste :)

**Comment by tomchristie** [comment]
schema.js is dynamically generated. It wouldn't really be js-compressible in any case as it's almost all a Base64 rendered string.
