### ISSUE TITLE
Add a pre_save hook for serializers

### ISSUE THREAD

**Issue by aidanlister** [encode/django-rest-framework#5183]
We inject the current user when dealing with objects throughout our app so that signal handlers can create security logs etc. We do this with a customised serializer like so: 

```
    def pre_save(self, instance):
        """ Lifecycle hook that is called just before .save() but after the instance has been created. """
        pass

    def create(self, validated_data):
        raise_errors_on_nested_writes('create', self, validated_data)

        ModelClass = self.Meta.model

        # Remove many-to-many relationships from validated_data.
        # They are not valid arguments to the default `.create()` method,
        # as they require that the instance has already been saved.
        info = model_meta.get_field_info(ModelClass)
        many_to_many = {}
        for field_name, relation_info in info.relations.items():
            if relation_info.to_many and (field_name in validated_data):
                many_to_many[field_name] = validated_data.pop(field_name)

        try:
            instance = ModelClass(**validated_data)
            self.pre_save(instance) # ABAS Added
            instance.save()
        except TypeError:
            tb = traceback.format_exc()
            msg = (
                'Got a `TypeError` when calling `%s.objects.create()`. '
                'This may be because you have a writable field on the '
                'serializer class that is not a valid argument to '
                '`%s.objects.create()`. You may need to make the field '
                'read-only, or override the %s.create() method to handle '
                'this correctly.\nOriginal exception text was: %s.' %
                (
                    ModelClass.__name__,
                    ModelClass.__name__,
                    self.__class__.__name__,
                    tb
                )
            )
            raise TypeError(msg)

        # Save many-to-many relationships after the instance is created.
        if many_to_many:
            for field_name, value in many_to_many.items():
                setattr(instance, field_name, value)

        return instance

    # This is a monkey patch on DRF's `update`. The only difference is us setting the user.
    # https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/serializers.py#L899
    def update(self, instance, validated_data):
        raise_errors_on_nested_writes('update', self, validated_data)

        # Simply set each attribute on the instance, and then save it.
        # Note that unlike `.create()` we don't need to treat many-to-many
        # relationships as being a special case. During updates we already
        # have an instance pk for the relationships to be associated with.
        for attr, value in validated_data.items():
            setattr(instance, attr, value)

        self.pre_save(instance) # ABAS Added
        instance.save()

        return instance
```

Would you accept a PR that added a "pre_save" hook to serialisers as above? Otherwise we need to replicate the whole create/update method which is is fine but it means every time we upgrade we need to check for any changes to these methods upstream.

**Comment by carltongibson** [comment]
This wouldn't be accepted. The view mixins already provide perform_create, perform_update, perform_destroy for this kind of functionality. (See "Save and deletion hooks" in the Generic Views docs http://www.django-rest-framework.org/api-guide/generic-views/#methods)

**Comment by aidanlister** [comment]
Hey Carlton, I think the functionality I need is not covered by those - I
need to change how the model is initialised before it's saved. There's no
serialiser.save(commit=False) which would let me get the instance and add
the tracker info before saving

**Comment by aidanlister** [comment]
@carltongibson thoughts?

**Comment by carltongibson** [comment]
I think any object initialisation you need can be handled by passing extra kwargs to save.

**Comment by aidanlister** [comment]
I need to do setattr(object.tracker.user, self.request.user) I don't think this is achievable any other way?

**Comment by tomchristie** [comment]
Given that we have an overridable `.save()` we're already providing for pre/post save overriding. (Although prefer the view hooks where possible)

**Comment by carltongibson** [comment]
Not seeing why you can't just configure the tracker in perform_create and then pass it to the serialiser.

Otherwise I think you just have to live with checking compatibility before an upgrade.

**Comment by aidanlister** [comment]
@carltongibson I can't do `instance.tracker.user = self.request.user` in perform_create / perform_update, because the only way I can get the instance is calling `serializer.save` which is too late.

@tomchristie The .save() method in the serializer calls self.create() to get the instance with the validated data, so at no point would I be able to get the instance and add the tracker before .save() is called :(

**Comment by carltongibson** [comment]
http://www.django-rest-framework.org/api-guide/serializers/#passing-additional-attributes-to-save

You pass the tracker as a kwarg.

**Comment by aidanlister** [comment]
@carltongibson That's not possible (or at least, very difficult) if you look at the way the tracker is created on the instance via contribute_to_class, https://github.com/jazzband/django-model-utils/blob/master/model_utils/tracker.py

Here's the tracker if you haven't seen it yet:
https://django-model-utils.readthedocs.io/en/latest/utilities.html#field-tracker

**Comment by xordoquy** [comment]
@aidanlister if not for saving, you can still use the serializer's context to get the user performing the request.
Please, let's move this to the mailing list as this turns into an usage question.
