### ISSUE TITLE
New Requests version breaks test.py APITestCase client

### ISSUE THREAD

**Issue by audiolion** [encode/django-rest-framework#5184]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

Use `APITestCase`'s `client` with Request on 2.16.0

## Expected behavior

It works

## Actual behavior

Requests [tore out all its vendor packages](https://github.com/kennethreitz/requests/commit/8e17600ef60de4faf632acb55d15cb3c178de9bb) in their most recent release (2.16.0). We now get an error because we relied on those vendored packages (namely `urllib3`).

```
from rest_framework.test import APITestCase
  File "/home/ubuntu/virtualenvs/venv-2.7.12/lib/python2.7/site-packages/rest_framework/test.py", line 30, in <module>
class HeaderDict(requests.packages.urllib3._collections.HTTPHeaderDict):
  AttributeError: 'module' object has no attribute 'packages'

**Comment by rpkilby** [comment]
Is this still relevant, given the reversion?

**Comment by audiolion** [comment]
oh my bad, closed the PR, forgot to close this

**Comment by tomchristie** [comment]
Thanks for having jumped on it, all the same @audiolion! 😄
