### ISSUE TITLE
Validation is failing for "null" value of foreign field when using Django rest 3.6.2

### ISSUE THREAD

**Issue by priyanka-thkr** [encode/django-rest-framework#5190]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [ ] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

**Comment by xordoquy** [comment]
Closing this due to the lack of actionnable content.
Please note that the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!

**Comment by priyanka-thkr** [comment]
Thanks, have posted in group. I didn't knew about the group .
