### ISSUE TITLE
Ordered serializer validation

### ISSUE THREAD

**Issue by mmautner** [encode/django-rest-framework#5193]
There seems to be no documented way to declare the order in which a serializer's validators are invoked when validating data.

Some (dated) discussion on StackOverflow:

https://stackoverflow.com/questions/27591574/order-of-serializer-validation-in-django-rest-framework

**Comment by xordoquy** [comment]
This sort of logic belongs to the business layer and should be left outside the serializers which is basically Kevin's answer as well.
The most common use case being that all the fields are validated and that the response returns as much information as possible to the client as possible and I don't see that changing anytime soon.

**Comment by mmautner** [comment]
Thanks @xordoquy

**Comment by xordoquy** [comment]
@mmarvick please note that I'm always interested in hearing about the use case that brought that point.

**Comment by mmautner** [comment]
@xordoquy I have a `CreateAPIView` which atomically creates 2 different models (`A` and `B`).

I wanted to raise a 404 if model `A` does not exist without surfacing the validation messages of model `B`--I was trying to accomplish this with a single `ModelSerializer`.

With your feedback, my path forward has been to overload my `CreateApiView`'s `create` method to invoke my validation of model `A` explicitly before calling the parent `create`.
