### ISSUE TITLE
standard routes for viewset supports decorators

### ISSUE THREAD

**Issue by craynic** [encode/django-rest-framework#5195]
Noticed that decorators such as `permission_classes` and `throttle_classes` do not function on standard routes (create, list, update, destroy, etc.). Hope they could be used like those for function based views, or another decorator like `detail_route` or `list_route` which accept arguments of those classes. Adding permissions or throttles for a certain view function is a fairly common use.

**Comment by xordoquy** [comment]
I agree it's not a good thing to have different behavior between the base CRUD actions and `detail_route` / `list_route`

Here's two reasons why it's different.
1. there are functions such as `get_permissions`, `get_throttle` and that you can use to tune a per entry point behavior. They are used for schema and documentation. Maybe `detail_route` and `list_route` should be documentated about how to use those methods.
2. technical reason is that detail_route / list_route creates another APIView behind your back and injects back the various dedicated settings. It works mostly because those entry point don't make the difference between CRUD actions. If you want to deal with several HTTP verb, you'll have to explicitly handle them in your method.

It's unlikely to happen for the second reason mostly.
I need to think about the everything goes into the get_* method vs the use of decorators. Though the latter looks easier, I like better the former to keep concerns into a single place. Simple is not the same as easy.

**Comment by craynic** [comment]
Thank you for your reply.

`get_permissions` and `get_throttle` do not have a view function argument, so the only way to decide which permission or throttle to be use is reading information from `self.request`, which is not easy to write or to read. I would rather call the permission or throttle directly in the view function.

Noticed that `DefaultRouter` deals with CRUD routes and other routes (DynamicXxxRoute) in different ways. I think just a little trick will make those decorators work. If that goes against the simple you want, I wil try to write a custom router to fit my case. If that were done, the code will be updated here.

**Comment by xordoquy** [comment]
Through ´get_permissions' or ´get_throtlle ´ don't have the view argument you can figure the current action according to ´self.action'

**Comment by craynic** [comment]
Thank you very much. Hope that `self.action` could be mentioned in documents.

I have tried to patch a router to make decorators work. I found it impossible. One standard route is shared among multiple actions, so `initkwargs` could not apply on an individual action. Using `self.action` in `get_throttles` seems to be the best solution for this case.

**Comment by xordoquy** [comment]
> Hope that self.action could be mentioned in documents.

Feel free to open a PR about that. We start relying on it so I really think it should go in the public API.

**Comment by xordoquy** [comment]
Meanwhile, I'm going to close this issue.

**Comment by tu-pm** [comment]
I also stumbled upon this issue recently, but with the `@action` decorator on ViewSets. I also just found out that you can override basically any ViewSet class attributes with the `@action` decorator, thus make extra actions as flexible as function-based views while they're still being grouped together. It would be great if we can do the same thing for the default actions.

The idea is to have a ViewSet that looks like this:

```python
class FooViewSet(ListModelMixin, RetrieveModelMixin, GenericViewSet):
    queryset = FooModel.objects.all()
    serializer_class = FooSerializer

    @initkwargs(response=FooDetailSerializer)
    def retrieve(self, request, *args, **kwargs):
        return super().retrieve(request, *args, **kwargs)

    @initkwargs(response=BarSerializer, response_many=True, pagination_class=NoPagination)
    @action(detail=True, methods=['get'], url_path='bars')
    def list_bars(self, request, *args, **kwargs):
        return Response(data='', status=200)

    @initkwargs(request=BarCreateSerializer, response=BarSerializer, response_code=201)
    @action(detail=True, methods=['post'], url_path='bars')
    def create_bars(self, request, *args, **kwargs):
        return Response(data='', status=201)
```

The `@initkwargs` decorator works just like the `@action` decorator - it just adds the `kwargs` attribute to the view function, with some modifications. But as @craynic points out, the router treats all default list actions as one Route and all default detail actions as another Route, so we can't pass initkwargs to them separately.

Using decorator is much nicer than using `get_...` methods, especially when working with serializers, you'd never know what the result of `self.get_serializer_class()` is until you look at the function's implementation. In large ViewSets it could be very inconvenient to keep scrolling up and down to know what kind of data we're dealing with.

Another upside of using decorators is that we have an easy an uniformed way to customize and utilize the same overridden attributes for the view method logics, the schema generator and the metadata class. No need to use `@extend_schema` or magic metadata determination, just pure `view.serializer_class` will do the trick.

Fixing the router is not too much of a problem I think, I'd be happy to make a PR if this idea went through.
