### ISSUE TITLE
Is "driver" a reserved word?

### ISSUE THREAD

**Issue by SRJ9** [encode/django-rest-framework#5199]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [ ] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
1. Create a serializer with a field named "driver".
3. Add the line
>  driver = serializers.SerializerMethodField()
3. Add a method "get_driver(self, obj)"

## Expected behavior
Serializer:driver value should be the value returned by get_driver method.

## Actual behavior
Field "driver" is ignored in Serializer when is a SerializerMethodField.
If driver is not a SerializerMethodField, driver is showed.
If you renamed "driver" by other field name and "get_driver" by "get_{new field}" is OK.

**Comment by xordoquy** [comment]
Can't reproduce with:

    class UserSerializer(serializers.HyperlinkedModelSerializer):
        driver = serializers.SerializerMethodField()

        class Meta:
            model = User
            fields = (
                'id', 'username', 'driver'
            )

        def get_driver(self, obj):
            return 'DEMO'
