### ISSUE TITLE
coreapi and TokenAuthentication problem

### ISSUE THREAD

**Issue by jet10000** [encode/django-rest-framework#5200]
rest_framework.authentication.TokenAuthentication

```
coreapi action api-token-auth create
<Error: 400 Bad Request>
    password: [
        "This field is required."
    ]
    username: [
        "This field is required."
    ]
```
How could i setup username and password?

I have test it:

coreapi action api-token-auth create --param passowrd=pwd --param username=root

but,

coreapi.exceptions.ParameterError: {'passowrd': 'Unknown parameter.', 'username': 'Unknown parameter.'}

===============================================
```
coreapi get http://127.0.0.1:8000/schema/
<My API "http://127.0.0.1:8000/schema/">
    api-token-auth: {
        create()
    }
    users: {
        list()
        read(id)
    }
```

**Comment by xordoquy** [comment]
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
