### ISSUE TITLE
Polymorphic viewset (variable serializer & queryset depending on the URL args)

### ISSUE THREAD

**Issue by and3rson** [encode/django-rest-framework#5203]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

1. Create URL for a viewset:

    ```python
    router.register('items/(?P<item_type>products|services)', ItemsViewSet, base_name='item')
    ```

2. Create ModelViewSet:

    ```python
    class ItemsViewSet(ModelViewSet):
        def get_item_type(self):
            return self.request._request.resolver_match.kwargs.get('item_type')

        def get_queryset(self):
            if self.get_item_type() == 'product':
                return ProductModel
            else:
                return ServiceModel

        def get_serializer_class(self):
            if self.get_item_type() == 'products':
                return ProductModelSerializer  # ProductModelSerializer.Meta.model == ProductModel
            else:
                return ServiceModelSerializer  # ServiceModelSerializer.Meta.model == ServiceModel
    ```

3. `GET /items/products`

## Expected behavior

The ViewSet should choose the queryset and serializer based on `item_type` url kwarg and render it.

## Actual behavior

DRF raises exception:

    Exception: Could not resolve URL for hyperlinked relationship using view name "product-detail". [...]

Seems like DRF ignores the `base_name` of the viewset and still tries to use the model name to determine the view name based on serializer model. Is there any way to override this behavior to resolve multiple models to `item-detail` instead of `<model_name>-detail`?

Please excuse me if it's a usage issue, but considering the availability of the `get_serializer_class` method I assume that such behavior should be possible. I went through the docs and couldn't find a way to override the method that generates view name from model.

Thanks in advance. DRF rocks!

**Comment by xordoquy** [comment]
> Seems like DRF ignores the base_name of the viewset and still tries to use the model name to determine the view name based on serializer model. Is there any way to override this behavior to resolve multiple models to item-detail instead of <model_name>-detail?

You'll need to explicitly define the `HyperlinkedRelatedField` with the proper `view_name` argument. Refer to http://www.django-rest-framework.org/api-guide/relations/#hyperlinkedrelatedfield for more informations.
Also note that I'm not sure the default `HyperlinkedRelatedField` will work since you'll need 2 arguments instead of just one.
