### ISSUE TITLE
Allow to GET a full object but POST/PUT/DELETE with only an id on related fields

### ISSUE THREAD

**Issue by sametmax** [encode/django-rest-framework#5206]
## Checklist

- [x ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x ] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

Create a Serializer with a link to another serializer. You can have the relation be symbolized by an id, a hyperlink or a full object. But it must be either. This means you have to choose between hard to read (only a reference you have to fetch) but easy to write (only a reference to send) or easy to read (full object) but hard to write (you have to recreate the full chain of nested objects to create a new entry).

## Expected behavior

There should be a way to ask for a serializer to accept only an reference (id or link) as an input, but always return the full object.

## Actual behavior

Currently you have to do all the work manually or create 2 serializers.

## Current workaround

I'm currently using something like this to work around this issue:

```python

from collections import OrderedDict

from rest_framework import serializers


class AsymetricRelatedField(serializers.PrimaryKeyRelatedField):

    def to_representation(self, value):
        return self.serializer_class(value).data

    def get_queryset(self):
        if self.queryset:
            return self.queryset
        return self.serializer_class.Meta.model.objects.all()

    def get_choices(self, cutoff=None):
        queryset = self.get_queryset()
        if queryset is None:
            return {}

        if cutoff is not None:
            queryset = queryset[:cutoff]

        return OrderedDict([
            (
                item.pk,
                self.display_value(item)
            )
            for item in queryset
        ])

    def use_pk_only_optimization(self):
        return False

    @classmethod
    def from_serializer(cls, serializer, name=None, args=(), kwargs={}):
        if name is None:
            name = f"{serializer.__class__.name}AsymetricAutoField"

        return type(name, [cls], {"serializer_class": serializer})
```

This let me write:
```python

class FooSerializer(serilizers.ModelSerializer):

    bar = AsymetricRelatedField(BarSerializer)

    class Meta:
        model = Foo
```

Et I can send an id for bar in a POST, or get a a full bar object in my GET. I wish something like this would officially exist in DRF.

**Comment by xordoquy** [comment]
This tends to pop up on a regular basis. I thought someone made a 3rd party for that but can't find it. I'd be happy to add it to the documentation if anyone implements it.

However I think it's unlikely to go into core as I do believe the result of a GET should be able to be sent through a PUT and keep the operation idempotent. I would like to avoid the asymmetry as much as possible.

To achieve this, one needs to mark the pk or url field as read/write on the nested serializer while every other nested serializer's fields are set to read only. Therefore, you can set the relation through the primary key while sending the full object in return.

**Comment by fabien-michel** [comment]
Just to share, our workaround for this problem is to have two fields:

- bar to get serialized related field
- bar_id to get and write it PK

```python
class FooSerializer(serilizers.ModelSerializer):
    bar = BarSerializer(read_only=True)
    bar_id = serializers.PrimaryKeyRelatedField(source='bar',  queryset=Bar.objects.all(), )

    class Meta:
        model = XXX
        fields = ('bar', 'bar_id', )
```

**Comment by BigChief45** [comment]
@fabien-michel Thanks for the workaround. However, this also includes the `bar_id` field in the response. Is there any way to not include this in the response but still use it for creation?

**Comment by czarcismok** [comment]
@fabien-michel thanks, I've been struggling with that concept for a while now
@BigChief45 just add `write_only=True` argument to `bar_id` field ;)

**Comment by joehoeller** [comment]
@BigChief45 - can you plz provide a code example? I am new to DRF, thanks! :)

**Comment by murdav** [comment]
@sametmax I really would like to implement your workaround but I got this error:

```
class InfoSerializer(serializers.ModelSerializer):
    source = AsymetricRelatedField(SourceSerializer)
```
`TypeError: __init__() takes 1 positional argument but 2 were given`

Do you have any clue?
Thanks.
D

**Comment by murdav** [comment]
Updated code:

```
# fields.py
class AsymetricRelatedField(serializers.PrimaryKeyRelatedField):

    def to_representation(self, value):
        return self.serializer_class(value).data

    def get_queryset(self):
        if self.queryset:
            return self.queryset
        return self.serializer_class.Meta.model.objects.all()

    def get_choices(self, cutoff=None):
        queryset = self.get_queryset()
        if queryset is None:
            return {}

        if cutoff is not None:
            queryset = queryset[:cutoff]

        return OrderedDict([
            (
                item.pk,
                self.display_value(item)
            )
            for item in queryset
        ])

    def use_pk_only_optimization(self):
        return False

    @classmethod
    def from_serializer(cls, serializer, name=None, args=(), kwargs={}):
        if name is None:
            name = f"{serializer.__name__}AsymetricAutoField"

        return type(name, (cls,), {"serializer_class": serializer})

```

```
class FooSerializer(serilizers.ModelSerializer):
    bar = AsymetricRelatedField.from_serializer(BarSerializer)()

    class Meta:
        model = Foo
```

**Comment by whirish** [comment]
@fabien-michel This doesn't seem to work anymore:
 ```Got a `TypeError` when calling `Foo.objects.create()`. This may be because you have a writable field on the serializer class that is not a valid argument to `Foo.objects.create()`. You may need to make the field read-only, or override the FooSerializer.create() method to handle this correctly.```

**Comment by xordoquy** [comment]
@whirish this looks more like an issue with you serializer's field. I don't see any reason the proposed solution wouldn't work any longer.

**Comment by whirish** [comment]
@xordoquy would you mind taking a look? I think my model is fairly standard:
 ```python
# models.py
class Narration(OrderedModel):
    narrative = models.ForeignKey(Narrative, on_delete=models.CASCADE)
    attached_events = models.ManyToManyField(CachedData)
    settings = models.ForeignKey(MapSettings, on_delete=models.CASCADE)

# serializers.py
class NarrationSerializer(ModelSerializer):
    narrative = NarrativeSerializer(read_only=True)
    settings = MapSettingsSerializer(read_only=True)
    attached_events = CachedDataSerializer(many=True, read_only=True)

    class Meta:
        model = Narration
        fields = "__all__"
        # depth = 1 [also doesn't work]
````

**Comment by xordoquy** [comment]
The mailing is the correct place for those questions.

**Comment by joehoeller** [comment]
Can you please explain what you're trying to do in 1-2 sentences for
specificity and clarity?

**Comment by joehoeller** [comment]
If this is what I am thinking you're asking, there is Django bulk updates,
otherwise you will have to write it all in your javascript on the front end
side using flatMap().

**Comment by Vatoth** [comment]
> @xordoquy would you mind taking a look? I think my model is fairly standard:
> 
> ```python
> # models.py
> class Narration(OrderedModel):
>    narrative = models.ForeignKey(Narrative, on_delete=models.CASCADE)
>    attached_events = models.ManyToManyField(CachedData)
>     settings = models.ForeignKey(MapSettings, on_delete=models.CASCADE)
> 
> # serializers.py
> class NarrationSerializer(ModelSerializer):
>    narrative = NarrativeSerializer(read_only=True)
>    narrative_id = PrimaryKeyRelatedField(source='Narrative',  queryset=Narrative.objects.all(), write_only=True)
>    settings = MapSettingsSerializer(read_only=True)
>    settings_id = PrimaryKeyRelatedField(source='MapSettings',  queryset=MapSettings.objects.all(), write_only=True)
>    attached_events = CachedDataSerializer(many=True, read_only=True)
>    attached_events_id = PrimaryKeyRelatedField(source='CachedData',  queryset=CachedData.objects.all(), write_only=True, many=True)
> 
>    class Meta:
>        model = Narration
>        fields = "__all__"
>        # depth = 1 [also doesn't work]
> ```

You have miss referenced the source

```py
attached_events = CachedDataSerializer(many=True, read_only=True)
attached_events_id = PrimaryKeyRelatedField(source='CachedData', queryset=CachedData.objects.all(), write_only=True, many=True)
```
became
```py
attached_events = CachedDataSerializer(many=True, read_only=True)
attached_events_id = PrimaryKeyRelatedField(source='attached_events', queryset=CachedData.objects.all(), write_only=True, many=True)
```

**Comment by qxrftz** [comment]
> > @xordoquy would you mind taking a look? I think my model is fairly standard:
> > ```python
> > # models.py
> > class Narration(OrderedModel):
> >    narrative = models.ForeignKey(Narrative, on_delete=models.CASCADE)
> >    attached_events = models.ManyToManyField(CachedData)
> >     settings = models.ForeignKey(MapSettings, on_delete=models.CASCADE)
> > 
> > # serializers.py
> > class NarrationSerializer(ModelSerializer):
> >    narrative = NarrativeSerializer(read_only=True)
> >    narrative_id = PrimaryKeyRelatedField(source='Narrative',  queryset=Narrative.objects.all(), write_only=True)
> >    settings = MapSettingsSerializer(read_only=True)
> >    settings_id = PrimaryKeyRelatedField(source='MapSettings',  queryset=MapSettings.objects.all(), write_only=True)
> >    attached_events = CachedDataSerializer(many=True, read_only=True)
> >    attached_events_id = PrimaryKeyRelatedField(source='CachedData',  queryset=CachedData.objects.all(), write_only=True, many=True)
> > 
> >    class Meta:
> >        model = Narration
> >        fields = "__all__"
> >        # depth = 1 [also doesn't work]
> > ```
> 
> You have miss referenced the source in your serializer
> for example
> 
> ```python
> attached_events = CachedDataSerializer(many=True, read_only=True)
> attached_events_id = PrimaryKeyRelatedField(source='CachedData', queryset=CachedData.objects.all(), write_only=True, many=True)
> ```
> 
> became
> 
> ```python
> attached_events = CachedDataSerializer(many=True, read_only=True)
> attached_events_id = PrimaryKeyRelatedField(source='attached_events', queryset=CachedData.objects.all(), write_only=True, many=True)
> ```

then i got a ValidationError('attached_events_id': "This field is required."), because there is  "attached_events" object in validated_data not "attached_events_id". Where is wrong?

**Comment by florianmartens** [comment]
@qxrftz I do think you have to make the put/post/patch request with a "narrative_id" key present and omit the "narrative" key (since it is read_only anyway).

**Comment by KyryloKaralyus** [comment]
if any earthlings in the future still need this, there is a package for separate read_serializers and write_serializers
