### ISSUE TITLE
DRF Authentication Classes incompatible with CORS

### ISSUE THREAD

**Issue by jxcl** [encode/django-rest-framework#5208]
When clients interact with servers with CORS enabled, preflight `OPTIONS` requests are sent by the client to `POST` endpoints, among others, without authentication. This is according to the CORS spec. The spec also states that all preflights should be responded to with a `200 OK`. 

Currently, `rest_framework.permissions.IsAuthenticated` return `False` in all cases when there are no authentication credentials. This makes DRF incompatible with CORS.

Users wanting to use CORS on their website have to subclass `IsAuthenticated` like so

```
class IsAuthenticatedAllowOptions(IsAuthenticated):
    def has_permission(self, request, view):
        if request.method == 'OPTIONS':
            return True

        return super().has_permission(request, view)
```

Can I suggest either the default `IsAuthenticated` be modified to do this, or perhaps to add a `IsAuthenticatedCors` class?

Context: https://stackoverflow.com/a/15734032

**Comment by tomchristie** [comment]
Are you using this (recommended) package? https://github.com/ottoyiu/django-cors-headers/
The support is implemented as middleware, so it bypasses the authentication settings.
