### ISSUE TITLE
OPTIONS request method with CoreAPI

### ISSUE THREAD

**Issue by bluesurfer** [encode/django-rest-framework#5215]
I need to get the available choices for a form field but CoreAPI doesn't seem to have a "options"  action to call the appropriate API (e.g. `OPTIONS /api/books/`). 

Am I missing something or I am bound to use the old ugly `$.ajax`?
(yes, I am proudly using jQuery in 2017 😄 )

**Comment by tomchristie** [comment]
For now, yes.
At some point the schema will include the options itself.
There's no intention of having the CoreAPI clients support `OPTIONS` calls since the information that they make available ought to be presented in the schema. (This is just an aspect where we're lacking right now)
