### ISSUE TITLE
Full text search filter with Posgtresql

### ISSUE THREAD

**Issue by LennyLip** [encode/django-rest-framework#5216]
Since Django 1.10 support Full text search with Postgressql
https://docs.djangoproject.com/en/1.11/ref/contrib/postgres/search/

it would be nice if [SearchFilter](https://github.com/encode/django-rest-framework/blob/master/rest_framework/filters.py#L81) support FTS postgressql too.

**Comment by tomchristie** [comment]
Not a bad idea, yup. Any guidance on what we'd need to change in order to handle this would be much appreciated from any contributors.

**Comment by tomchristie** [comment]
I'm going to close this off for now. We'd certainly consider this as functionality, but it'd need someone to kick things off with a pull request.
