### ISSUE TITLE
TypeError: <class 'django.db.models.fields.EmailField'> is not JSON serializable

### ISSUE THREAD

**Issue by chadbrewbaker** [encode/django-rest-framework#5217]
## Steps to reproduce
The rest_framework/utils/encoders.py JSONEncoder barfs when trying to serialize an email field.

## Expected behavior
Django REST Framework supports email JSON serialization.

## Actual behavior
TypeError: <class 'django.db.models.fields.EmailField'> is not JSON serializable

**Comment by chadbrewbaker** [comment]
I changed :
```python
email = models.EmailField
```
To:
```python
email = models.EmailField(max_length=100,blank=True)
```
I think rest_framework/utils/encoders.py needs some testing to flush out why it threw the type error instead of an error the the EmailField was null.

**Comment by xordoquy** [comment]
This isn't the intended usage for an encoder. Renderer expects basic Python types which can be retrieve with serializers.
