### ISSUE TITLE
SlugField doesn't accept Unicode

### ISSUE THREAD

**Issue by Alir3z4** [encode/django-rest-framework#5223]
## Steps to reproduce
 
The model has a SlugField with `allow_unicode=True`

```
class Person(models.Model):
    name = models.SlugField(
        allow_unicode=True,
        max_length=155,
        unique=True
    )
```

The serializer is a `ModelSerializers`:
```
class PersonSerializer(serializers.ModelSerializer):
    class Meta:
        model = User
        fields = ('name',  )
```

## Expected behavior

The serializer should accept unicode values just like the field on the model.

## Actual behavior

By passing `علیرضا` as value for `name` field, it fails.
The serializer print out the following error:
```
{'name`: ['Enter a valid "slug" consisting of letters, numbers, underscores or hyphens.']}
```

**Comment by akarpodinis** [comment]
+1  I'm having this problem now.
The initializer doesn't respect `allow_unicode` at all.

**Comment by nicwolff** [comment]
`serializers.SlugField` also adds its non-Unicode-aware `RegexValidator` even if custom `validators` were passed in which is pretty mean. https://github.com/encode/django-rest-framework/blob/master/rest_framework/fields.py#L800

**Comment by xordoquy** [comment]
PR welcomed :)
