### ISSUE TITLE
list serializer with data and deserilizer is not working

### ISSUE THREAD

**Issue by anush0247** [encode/django-rest-framework#5226]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

```python
#userSerializer.py
from rest_framework import serializers


class userSerializer(serializers.ListSerializer):
    child = serializers.IntegerField()

In [12]: u =userSerializer(data=[1,2])

In [13]: u =userSerializer(data=[1,2], many=True)

In [14]: u.is_valid()
Out[14]: False

In [15]: u.errors
Out[15]: [{u'non_field_errors': [u'Expected a list of items but got type "int".']}, {u'non_field_errors': [u'Expected a list of items but got type "int".']}]

In [16]: u =userSerializer(data=[1,2])

In [17]: u.is_valid()
Out[17]: True

In [18]: u.errors
Out[18]: []

In [19]: u.data
Out[19]: [1, 2]

In [20]: u.save()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-20-5d13c143bca2> in <module>()
----> 1 u.save()

/home/aneesh/.virtualenvs/discussions/local/lib/python2.7/site-packages/rest_framework/serializers.pyc in save(self, **kwargs)
    691         validated_data = [
    692             dict(list(attrs.items()) + list(kwargs.items()))
--> 693             for attrs in self.validated_data
    694         ]
    695 

AttributeError: 'int' object has no attribute 'items'

In [21]: 

```

**Comment by xordoquy** [comment]
`ListSerializer` is not meant to be used like this.
Please refer to the [documentation](http://www.django-rest-framework.org/api-guide/serializers/#listserializer) for more informations about the `ListSerializer`.
