### ISSUE TITLE
AttributeError on self.request, self.args and self.kwargs

### ISSUE THREAD

**Issue by vstoykov** [encode/django-rest-framework#5228]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

Create a `ViewSet` and overwrite `dispatch` method and try to access one of `self.request`, `self.args` or `self.kwargs` before calling `super`

## Expected behavior

It should return the appropriate objects

## Actual behavior

It raises `AttributeError`

This should be related to this Django ticket https://code.djangoproject.com/ticket/19316 which was fixed before 5 years in Django 1.6 and backported to Django 1.5.
The solution is to set these in the decorator generated in `as_view` method as Django does (https://github.com/django/django/commit/ea6b95dbec77371d517392ffb465017b8eb7001c)

I can try to prepare a PR

**Comment by tomchristie** [comment]
> Create a ViewSet and overwrite dispatch method and try to access one of self.request, self.args or self.kwargs before calling super

Don't do that.

**Comment by tomchristie** [comment]
Blergh - reconsidering on re-reading this, given what django does.
