### ISSUE TITLE
SchemaGenerator:get_description break markdown syntax

### ISSUE THREAD

**Issue by aklim007** [encode/django-rest-framework#5240]
This shema using for django-rest-swagger

[This](https://github.com/encode/django-rest-framework/blob/master/rest_framework/schemas.py#L479) code delete start/end spaces in descriptions. 
```
 lines = [line.strip() for line in description.splitlines()]
```

But spaces is a part markdown syntax!

Where is it important:

- list
    - sublist
```
- list
    - sublist
```

    code

```
    code
```

**Comment by carltongibson** [comment]
Yep. This seems valid. 

[`get_view_description` already handles `dedent`-ing](https://github.com/encode/django-rest-framework/blob/master/rest_framework/views.py#L51), so is this doing anything here? 

@aklim007: a failing test case with your example would be a good start to a PR here. ;-)
