### ISSUE TITLE
Upgrade 3rd party JavaScript libraries

### ISSUE THREAD

**Issue by wojtekerbetowski** [encode/django-rest-framework#5246]
Django REST framework uses outdated jQuery (currently: 1.12, latest is 3.2).

Do you plan to upgrade it?

**Comment by tomchristie** [comment]
I'd be happy to, but I'm not particularly bothered either way since we've not had any issues raised related to it. Pull requests would be welcome and accepted, otherwise going to treat this as a non-issue for now.

**Comment by lmannering** [comment]
Wondering if this should be re-evaluated, apparently jquery 1.12 has a known security vulnerability: 

<img width="766" alt="screen shot 2018-03-05 at 11 43 08 am" src="https://user-images.githubusercontent.com/14155046/36956658-8f8feac2-206a-11e8-894b-1453a18f4688.png">

Thanks for a great framework :)

**Comment by carltongibson** [comment]
This was done in #5823.

**Comment by lmannering** [comment]
Oops, sorry @carltongibson I installed 3.3.7, but I can see #5823 is due in 3.3.8. Thanks 👍
