### ISSUE TITLE
Invalid syntax code in coreapi documentation.

### ISSUE THREAD

**Issue by tungox6** [encode/django-rest-framework#5247]
Link to the document: http://www.django-rest-framework.org/topics/api-clients/#instantiating-a-client

Invalid syntax code:
`var client = coreapi.Client()`

The correct code should be:
`var client = new coreapi.Client()`

**Comment by paultiplady** [comment]
@tungox6 the docs are editable in Github here: https://github.com/encode/django-rest-framework/blob/master/docs/topics/api-clients.md

A PR to fix this error would likely be accepted.
