### ISSUE TITLE
CursorPaginator support for page_query_param

### ISSUE THREAD

**Issue by cypreess** [encode/django-rest-framework#5249]
I found it very usefull for frontend apps to set page size via query param when using `CursorPaginator`. I am attaching PR for that that is basically adoption of of `PageNumberPagination` approach inside `CursorPaginator`.

Disclaimer: I decided to leave both `max_page_size`  and `offset_cutoff` as they are serving different semantic purpose (even if feels very similar).

**Comment by cypreess** [comment]
@tomchristie any chance making a glance look at this?

**Comment by carltongibson** [comment]
Closed by #5250
