### ISSUE TITLE
Cannot set both 'fields' and 'exclude' options on serializer

### ISSUE THREAD

**Issue by sagargavli** [encode/django-rest-framework#5254]
## Checklist
Seen this issue when ChildSerializer is Inherited from ParentSerialzer .  ParentSerializer is having `exclude` field and  ChildSerializer is with `include` field

**Comment by xordoquy** [comment]
The issue is missing proper description.
Should DRF forbid such configuration but doesn't at the moment ? Or does it already forbid it ?
If the latter, I wouldn't consider it as a bug as you could make a mixin of the common things between the two serializers and remove the heritage.
