### ISSUE TITLE
Docs templatetags AttributeError: 'NoneType' object has no attribute 'items'

### ISSUE THREAD

**Issue by maxpa1n87** [encode/django-rest-framework#5256]
## Checklist

- [x ] I have verified that that issue exists against the `3.6.3` branch of Django REST framework.
- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x ] I have reduced the issue to the simplest possible case.
- [x ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

- Install version 3.6.3 from pip `install djangorestframework==3.6.3`
- Put in URLConf `include_docs_urls()`
- Runserver
- Open browser in `http://localhost:8000/docs/`

## Expected behavior

Render docs

## Actual behavior

Exception rendered:
```
builtins.AttributeError

AttributeError: 'NoneType' object has no attribute 'items'

rest_framework/templatetags/rest_framework.py", line 244, in items
```

## Requirements
```
coreapi==2.3.1
Django==1.11.3
django-filter==1.0.4
djangorestframework==3.6.3
drfdocs==0.0.11
Markdown==2.6.8
Pygments==2.2.0
```

**Comment by j0hnsmith** [comment]
I just installed `djangorestframework==3.6.2` (instead of `3.6.3`) and the error goes away.

**Comment by kgodey** [comment]
This is happening to us too, but only for unauthenticated users.

**Comment by Woile** [comment]
I've reproduced the steps, drf 3.6.3 with `url(r'^docs/', include_docs_urls(title='My API title')),` and no error appeared, can you provide more information?

**Comment by maxpa1n87** [comment]
It's all right from my side also it works as expected. Can be closed.
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 15.08.2017, 19:28, Santiago <notifications@github.com> schrieb:
I've reproduced the steps, drf 3.6.3 with url(r'^docs/', include_docs_urls(title='My API title')), and no error appeared, can you provide more information?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/encode/django-rest-framework","title":"encode/django-rest-framework","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/encode/django-rest-framework"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Woile in #5256: I've reproduced the steps, drf 3.6.3 with `url(r'^docs/', include_docs_urls(title='My API title')),` and no error appeared, can you provide more information?"}],"action":{"name":"View Issue","url":"https://github.com/encode/django-rest-framework/issues/5256#issuecomment-322532907"}}}

**Comment by litchfield** [comment]
Dupe #5198 I can confirm the error exists for include_docs_urls(Public=True) on DRF version 3.6.3 when not authenticated and IsAuthenticated permissions are set
