### ISSUE TITLE
permission_classes argument for list_route and detail_route doesn't work

### ISSUE THREAD

**Issue by mehdipourfar** [encode/django-rest-framework#5263]
Even though my viewset methods have IsAuthenticated argument as permission_classes, I will receive server errors in the context of AnonymousUser object has not attribute ...

I've put ipdb inside has_permission method of IsAuthenticated and noticed that it never gets. It will be called if i put it inside has_permission method of AllowAny class.

**Comment by tomchristie** [comment]
This isn't clearly enough described to be an actionable issue.

**Comment by mehdipourfar** [comment]
What should I do or how can I help? This is an security bug.

**Comment by xordoquy** [comment]
This feels like a use case issue. Did you already try to ask on the mailing list and provided a traceback ?
If you think it's a DRF issue, we need a test case we can reproduce to consider a bug, in particular since it seems to be working for us.

**Comment by mehdipourfar** [comment]
I've made an example project to prove what I said but I've found the problem elsewhere.
The problem is that I use get_permission_classes method inside my viewset and set permissions based on request methods. But unfortunately permission_classes in list_route and detail_route decorators won't be appended to permission classes from get_permission_classes of viewset method.

**Comment by mehdipourfar** [comment]
If I remove get_permission_classes method from my viewset, everything works as expected.

**Comment by mehdipourfar** [comment]
Alright, my problem was solved by using append inside get_permissions method. But I think this topic is not well documented.

**Comment by rpkilby** [comment]
Improvements to the docs are always welcome :)
