### ISSUE TITLE
parameter url reverse

### ISSUE THREAD

**Issue by pkyalo** [encode/django-rest-framework#5266]
I'm having issues in reversing urls with parameters in root API endpoint; 
for example : 

/items/(?P<pk>[0-9]+)/$

I get reverse for 'url name' note found

**Comment by tomchristie** [comment]
Hi there & thanks for your question.

The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions.

Thanks! 😀
