### ISSUE TITLE
RawPostDataException thrown when reading from request.data

### ISSUE THREAD

**Issue by lsoaresesilva** [encode/django-rest-framework#5267]
## Checklist

- [X ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X ] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ X] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [ X] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

1. Create a class View:

```
class MyControlller(APIView):
    def post(self, request, format=None):
        myData = request.data.get("anything")

```
## Expected behavior

Return the data sent through form.

## Actual behavior

Throws an exception RawPostDataException

----
If I change APIView to View and request.data to request.POST everything works correct, so I think DRF is reading the body somewhere.

**Comment by tomchristie** [comment]
As described here, it's not possible to reproduce this issue.
You may want to take a look at the middleware you've got installed.
