### ISSUE TITLE
Problem when using router with base_name and url with ModelSerializer

### ISSUE THREAD

**Issue by Fabitosoft** [encode/django-rest-framework#5277]
I am using the same model to create 3 different apis, so I have to use base_name on each route.
Then, when I try to include the 'url' field into my serializer I got and error just at that moment.

To show what's happened I put just some lines of my code

## Steps to reproduce

models.py

```
class Tercero(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    alias = models.CharField(max_length=20, null=True, blank=True, unique=True)
    
    es_modelo = models.BooleanField(default=False)
    es_empleado = models.BooleanField(default=False)
    es_proveedor = models.BooleanField(default=False)
    en_la_empresa = models.BooleanField(default=False)

    objects = models.Manager()
    modelos = TercerosModelosQuerySet.as_manager()
    empleados = TercerosEmpleadosQuerySet.as_manager()
    internos = TercerosInternoQuerySet.as_manager()
```

urls.py
```
from django.conf.urls import url, include
from rest_framework import routers
from .views import (
    ModeloPresenteViewSet,
)
router = routers.DefaultRouter()
router.register(r'modelos_presentes', ModeloPresenteViewSet, base_name='modelos_presentes')
```
views.py

```
from rest_framework import viewsets, permissions

from .serializers import TerceroSerializer
from .models import Tercero
from .permissions import ReadOnly, IsStaffReadOnly

class ModeloPresenteViewSet(viewsets.ModelViewSet):
    queryset = Tercero.modelos.presente()
    serializer_class = TerceroSerializer
    permission_classes = (ReadOnly,)
```

serializers.py
```

class TerceroSerializer(serializers.ModelSerializer):
    categoria_modelo = serializers.StringRelatedField()

    class Meta:
        model = Tercero
        fields = ('url', 'id', 'user')
```

## Expected behavior
List of models with url each

## Actual behavior
Request Method: | GET
-- | --
http://127.0.0.1:8000/api/modelos_presentes/
1.11.1
ImproperlyConfigured
Could not resolve URL for hyperlinked relationship using view name "tercero-detail". You may have failed to include the related model in your API, or incorrectly configured the `lookup_field` attribute on this field.
/Users/fabioandresgarciasanchez/PycharmProjects/virtualenv/dramor_env/lib/python3.4/site-packages/rest_framework/relations.py in to_representation, line 390
/Users/fabioandresgarciasanchez/PycharmProjects/virtualenv/dramor_env/bin/python
3.4.4
['/Users/fabioandresgarciasanchez/PycharmProjects/01_DrAmor',  '/Users/fabioandresgarciasanchez/PycharmProjects/01_DrAmor/dramorapp_habitaciones',  '/Users/fabioandresgarciasanchez/PycharmProjects/01_DrAmor/geografia',  '/Users/fabioandresgarciasanchez/PycharmProjects/01_DrAmor',  '/Users/fabioandresgarciasanchez/PycharmProjects/01_DrAmor/website_configuraciones',  '/Users/fabioandresgarciasanchez/PycharmProjects/01_DrAmor/dramorapp_servicios',  '/Users/fabioandresgarciasanchez/PycharmProjects/01_DrAmor/website_perfiles',  '/Users/fabioandresgarciasanchez/PycharmProjects/01_DrAmor/website',  '/Users/fabioandresgarciasanchez/PycharmProjects/01_DrAmor/admin_modelos',  '/Users/fabioandresgarciasanchez/PycharmProjects/01_DrAmor/dramorapp_terceros',  '/Users/fabioandresgarciasanchez/PycharmProjects/01_DrAmor/mdb_floppy_forms',  '/Users/fabioandresgarciasanchez/PycharmProjects/01_DrAmor/DrAmor',  '/Users/fabioandresgarciasanchez/PycharmProjects/01_DrAmor/admin_dashboards',  '/Users/fabioandresgarciasanchez/PycharmProjects/01_DrAmor/dramorapp_modelos',  '/Library/Frameworks/Python.framework/Versions/3.4/lib/python34.zip',  '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4',  '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/plat-darwin',  '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/lib-dynload',  '/Users/fabioandresgarciasanchez/PycharmProjects/virtualenv/dramor_env/lib/python3.4/site-packages',  '/Users/fabioandresgarciasanchez/PycharmProjects/virtualenv/dramor_env/lib/python3.4/site-packages/setuptools-28.8.0-py3.4.egg',  '/Users/fabioandresgarciasanchez/PycharmProjects/virtualenv/dramor_env/lib/python3.4/site-packages/pip-9.0.1-py3.4.egg',  '/Users/fabioandresgarciasanchez/PycharmProjects/01_DrAmor/DrAmor']
Dom, 16 Jul 2017 12:53:42 -0500

**Comment by xordoquy** [comment]
Please don't use the issue tracker for usage questions.
Also note that the error looks inconsistent with the code sample you provided.
To end, [how hyperlinks are determined](http://www.django-rest-framework.org/api-guide/serializers/#how-hyperlinked-views-are-determined) should give you the hint to fix the issue.
