### ISSUE TITLE
BaseRenderer "format" class attribute masks Python "format" function

### ISSUE THREAD

**Issue by carldunham** [encode/django-rest-framework#5281]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Example code:
```
from rest_framework.renderers import BaseRenderer
class FooRenderer(BaseRenderer):
    format = 'foo'
```

```
$ pip install flake8 flake8-builtins
$ flake8
./test.py:3:5: B003 "format" is a python builtin, consider renaming the class attribute
```

## Expected behavior
Great-smelling code.

## Actual behavior
Not-so-great-smelling code.

**Comment by tomchristie** [comment]
pip uninstall flake8-builtins

**Comment by tomchristie** [comment]
More seriously, there's no conflict with a class attribute used in that way.
We *could* give ourselves extra pain here if we wanted, but it wouldn't give us much of a win as a result.
