### ISSUE TITLE
Serializer works incorrect for model boolean fields(blank=false)

### ISSUE THREAD

**Issue by alex1vanchik** [encode/django-rest-framework#5283]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

1. create a model Test with a test_filed like:

```
class TestModel(models.Model):
    test_field = models.BooleanField(blank=False)
```

2. create ModelSerializer like:
```
class TestSerializer(serializers.ModelSerializer):
    class Meta:
        fields = ('test_field',)
        model = TestModel
```
3. Create view and send to it empty parameters {}
## Expected behavior
The serializer will see that the test_field in the model blank=False and automatically set required=True. Accordingly, the user sees an validation error that the test_field is required(code 400).
## Actual behavior
User receives a fatal error `django.db.utils.IntegrityError: NOT NULL constraint failed: test_field`
If set on the serializer `test_field = serializers.BooleanField(required=True)` will be work fine.

**Comment by xordoquy** [comment]
flagging a field as blank is not the same as not providing it.

**Comment by alex1vanchik** [comment]
Then explain, Why do that works for the other types of fields like IntegerField? This is not a bug, this is feature 👍

**Comment by xordoquy** [comment]
If it behave differently from the other field, you may be using the browsable API and/or HTML forms while the mention of `{}` lead me to assume it was JSON.
Provided that you're using HTML forms, the [documentation](http://www.django-rest-framework.org/api-guide/fields/#boolean-fields) explains this difference which is also an [issue](https://docs.djangoproject.com/en/1.11/ref/forms/fields/#booleanfield) with Django

**Comment by alex1vanchik** [comment]
It's about type conversion in the serialization level. A simple example:
sent like JSON {}
## For IntegerField
if `test_int = models.IntegerField(blank=False)` we get http status code 400 test_int is required
if  `test_int = models.IntegerField(blank=False, default=0)` we get http status code 201
## For BooleanField
if `test_bool = models.BooleanField(blank=False)` we get django.db.utils.IntegrityError: NOT NULL constraint failed: test_bool
if  `test_int = models.BooleanField(blank=False, default=False)` we get http status code 201

Example from real life you made a mistake and sent test_booll. In response you get an fatal error. Although for other types everything would work fine. It's certainly not difficult to set a default value or add one line to the serializer, but as for me there is a flaw. And this drawback is in the serializer. 

Thank you very much for your great work
