### ISSUE TITLE
DestroyModelMixin should call serializer method to remove model, not instance directly

### ISSUE THREAD

**Issue by rsinger86** [encode/django-rest-framework#5287]
I prefer to keep domain logic out of my views and models. So, I tend do it in my serializers, often delegating to a "service module", as recommended by this popular SO answser: https://stackoverflow.com/a/12857584/1807888

DRF's CBV mixins all call serializer methods to modify the model layer, except for the DestroyModelMixin, which [directly calls](https://github.com/encode/django-rest-framework/blob/master/rest_framework/mixins.py#L87) the model instance method. 

For consistency, it would be nice if this mixin also delegated to the serializer, where I could override as necessary in order to inject my domain-specific logic.

**Comment by tomchristie** [comment]
Understand the point you're making here, but it's not something we'll be acting on.
Given that there's no data validation involved in deletion, it'd be an extra source of indirection to force that through the serializers.
If anything there's a reasonable argument that serializers shouldn't deal with persistence at all, only data validation and transformation, but given the marginal benefits and the fact that'd mean re-architecting a vast number of existing projects that's also not something I'm minded to explore.
Interesting point to raise, tho, thanks.

**Comment by rsinger86** [comment]
Thanks for the clarification, I understand your reasons.
