### ISSUE TITLE
Cannot include query parameter when using the HyperlinkIdentityField

### ISSUE THREAD

**Issue by klarakaleb** [encode/django-rest-framework#5289]
## Checklist

- [+] I have verified that that issue exists against the `master` branch of Django REST framework.
- [+] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [+] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [+] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [+] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Attempt to include the Query Parameter (e.g. specific level) in the serializers.HyperlinkedIdentityField.

## Expected behavior
URL with www.api.com/group/?level=Specific_level

## Actual behavior
Unable to include the respective query parameter as a variable when trying to generate an URL using the serializers.HyperlinkedIdentityField i.e. could only output www.api.com/group.
Could utilise the django.urls.reverse() but it would be useful if there was an extension to the serializers.HyperlinkedIdentityField that would enable the inclusion of the query parameters into the automatically generated URL

**Comment by xordoquy** [comment]
Could you be more specific about your use case ?
I don't get it from the description you provided. An example of code that would lead to the url you provided would be helpful.

**Comment by klarakaleb** [comment]
Apologies - my usecase is the following:

For a single object, I have 2 parameters (id and level) that I would like to include into the url field in order to make my API as browsable as possible. My current API architecture of the view that I would like to hyperlink to is /view/<id>/?level=<level>

With the current HyperlinkedIdentityField, I am unable to generate the ?level=<level> part of the url. 
I think this would be quite useful to have, rather than to have to build the url from scratch.

My current solution to the problem has been to extend the HyperlinkedIdentityField to create the QueryParamHyperlinkedIdentiyField as following:

class QueryParamHyperlinkedIdentiyField(serializers.HyperlinkedIdentityField):
    def __init__(self, query_params, **kwargs):
        super(QueryParamHyperlinkedIdentiyField, self).__init__(**kwargs)
        self.query_params = query_params

    def get_url(self, obj, view_name, request, format):
        url = super(QueryParamHyperlinkedIdentiyField, self).get_url(obj, view_name, request, format)
        if len(self.query_params) > 0:
            url += "?"+urlencode({k: getattr(obj, v) for k,v in self.query_params.items()})
        return url

Which allows me to use the following one-liner to get the url of interest:

url = QueryParamHyperlinkedIdentiyField(view_name='hogs-detail', lookup_field='hog_id', query_params={'level': 'level'})

I hope my intent is clearer now.

**Comment by samwak** [comment]
Hey @klarakaleb I'm in the exact same cas then yours
I'm trying your solution, extending the HyperlinkedIdentityField, I get this error

`TypeError: __init__() got an unexpected keyword argument 'query_params'`

Do you know why ?
Thanks

**Comment by xordoquy** [comment]
@klarakaleb sorry for the delay. Thanks for the explanation, indeed it makes sense.

**Comment by klarakaleb** [comment]
@samwak Hey! How did you initiate it in the serializers.py? 

It should something along the lines of:

 protein_url = QueryParamHyperlinkedIdentityField(view_name='protein-detail', lookup_field='id', query_params={'level': 'level'})

The above works like a charm for me!

**Comment by samwak** [comment]
Hey @klarakaleb Yes I think I did like you did .. Do I miss something ?
# serializers.py
```
class QueryParamHyperlinkedIdentiyField(serializers.HyperlinkedIdentityField):
	def init(self, query_params, **kwargs):
		super(QueryParamHyperlinkedIdentiyField, self).init(**kwargs)
		self.query_params = query_params

	def get_url(self, obj, view_name, request, format):
		url = super(QueryParamHyperlinkedIdentiyField, self).get_url(obj, view_name, request, format)
		if len(self.query_params) > 0:
			url += "?"+urlencode({k: getattr(obj, v) for k,v in self.query_params.items()})
		return url

class ProfileDetailSerializer(serializers.ModelSerializer):
	history_bets = QueryParamHyperlinkedIdentiyField(
                                 view_name='profile_bets_api',
                                 lookup_field='pk', 
                                 query_params={'status': 'history'}
                                 )
```
# url.py
```
url(r'^api/profiles/(?P<pk>\d+)/bets/$', 
        ProfileBetOddPairListAPIView.as_view(),
        name='profile_bets_api',
        ),
```
# Error
```
TypeError: __init__() got an unexpected keyword argument 'query_params'
```

**Comment by xordoquy** [comment]
May I suggest to continue that thread on the mailing list please ?

**Comment by carltongibson** [comment]
I'm going to close in line with #5317: a custom field like this needs to live in the user's own project.

**Comment by apollodatasolutions** [comment]
Another solution is to add this as a custom field on the Serializer and then have that field call a property on the model that returns the customized URL, that's how we solved it.

`class LeadDetailSerializer(serializers.ModelSerializer):
    ...
    portfolio = serializers.CharField(source='portfolio_url')

class Lead(models.Model):
    ...

    @property
    def portfolio_url(self):
        """ Returns the URL for the portofolio for easier use inside the leads API """

        return reverse('leads:lead_portfolio') + '?lead={pk}&token={token}'.format(pk=self.pk, token=self.portfolio_token)
`
