### ISSUE TITLE
AssertionError at Tutorial 2: Requests and Responses

### ISSUE THREAD

**Issue by untitledboy** [encode/django-rest-framework#5293]
Following all steps in [Tutorial 2: Requests and Responses](http://www.django-rest-framework.org/tutorial/2-requests-and-responses/) I've got following error trying to access **127.0.0.1:8000/snippets/**

> AssertionError at /snippets/
Cannot apply DjangoModelPermissions on a view that does not set `.queryset` or have a `.get_queryset()` method.

I fixed it by adding **permission_classes** into **views.py**
```
...
from rest_framework.permissions import AllowAny
from rest_framework.decorators import api_view, permission_classes

@api_view(['GET', 'POST'])
@permission_classes((AllowAny, ))
...

@api_view(['GET', 'PUT', 'DELETE'])
@permission_classes((AllowAny, ))
...
```

It would be great if you add it into tutorial.

**Comment by xordoquy** [comment]
The tutorial doesn't use the `DjangoModelPermissions` so you probably have tempered with the settings.
