### ISSUE TITLE
Feature request: DEFAULT_LIST_SERIALIZER_CLASS setting

### ISSUE THREAD

**Issue by rapilabs** [encode/django-rest-framework#5294]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

I'd like to propose that a setting `LIST_SERIALIZER_CLASS` that overrides the list serializer that `ModelSerializer` makes use of.  Currently we can set the `list_serializer_class` property on the serializer Meta however if you have a standard serializer for your entire site then it would be nice to set this globally.  Thankyou! :)

**Comment by tomchristie** [comment]
Perfectly reasonable, but would rather limit this to users overriding the views or serializer classes, to come up with new base classes, rather than adding settings.
