### ISSUE TITLE
generics.ListAPIVIEW not compatible with schema generation 

### ISSUE THREAD

**Issue by tyan4g** [encode/django-rest-framework#5296]
## Steps to reproduce
I define a listAPIVIEW
```
class UserList(generics.ListCreateAPIView):
    """
    get:
    Return a list of all the existing users.

    post:
    Create a new user instance.
    """
    def get_queryset(self):
           return .....
```
## Expected behavior
when I visit the 
localhost/docs/
I should see the documentation of the API endpoint

## Actual behavior

> UserWarning:
> UserList is not compatible with schema generation "{} is not compatible with schema generation".format(view.__class__)

**Comment by daleione** [comment]
I work well in my project with listAPIView, I guss maybe you url was empty for UserList, give it a value.
It's a bug for docs couldn't display null url View api.

**Comment by carltongibson** [comment]
The issue description here doesn't give enough information. I'm going to close this. I suspect the warning is arising elsewhere. 

Try running `python -Werror` to convert the warning to an error and look at the traceback.
