### ISSUE TITLE
serializers one to many relationship set length control.

### ISSUE THREAD

**Issue by tyan4g** [encode/django-rest-framework#5297]
## Steps to reproduce
I have 2 model , a user have multiple cars.
```
class User(Model):
          id = AutoField()
         name = CharField()

class Car(Model):
        id = AutoField()
       name = CharField()
       user = ForeignkeyField(User)
```
and two serializer for the 2 model

```
class UserSerilizer():
       car_set = CarSerilizer(many=True)
        class Meta:
                field = ('name', 'car_set')
```
## Expected behavior

when I serializers the user with the cars.
it return all the cars associated with the user.
..but I only want to show top 2 cars..

## Actual behavior
I want to limit the cars in the car set...how can I do that with serilizer...

**Comment by tomchristie** [comment]
Hi there & thanks for your question.

The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions.

Thanks! 😀
