### ISSUE TITLE
Docs How do I generate a richer API documentation?

### ISSUE THREAD

**Issue by anshengme** [encode/django-rest-framework#5299]
## Checklist

- [ ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [ ] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Expected behavior

I would like to use Markdown to write API documentation, of course, the real method, similar to

```bash
|参数|描述|
|:--|:--|
|page|第几页|
|limit|条数|
```

## Actual behavior

In fact he will automatically render a line of strings

does django-rest automatically generate API documentation for more detailed instructions?

In production, we are using APIView.

**Comment by anshengme** [comment]
http://www.django-rest-framework.org/img/api-docs.gif

Is there a sample code in the picture above? If so, I would like to refer to it.

**Comment by carltongibson** [comment]
There's not really a clear issue here it's more a usage question. Please see the [Mailing List](https://groups.google.com/forum/#!forum/django-filter) for usage questions and discussions. If you can provide a concrete example that is more helpful. 

The GIF is showing the tutorial code by the look of it. (???)
