### ISSUE TITLE
Misleading ListField signature

### ISSUE THREAD

**Issue by buoto** [encode/django-rest-framework#5301]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
ListField [signature in docs](http://www.django-rest-framework.org/api-guide/fields/#listfield) is misleading. It implies that `child` argument can be passed as positional arg. However `ListField.__init__` [pops `child` from kwargs](https://github.com/encode/django-rest-framework/blob/master/rest_framework/fields.py#L1525).
```
>>> from rest_framework.fields import ListField, CharField
>>> ListField(CharField()).child
```
## Expected behavior
```
CharField()
```
## Actual behavior
```
_UnvalidatedField()
```

**Comment by jpadilla** [comment]
@buoto want to put a PR together updating the docs?

**Comment by xordoquy** [comment]
Ideen but at the same time it should not be None, so altering the signature to `child=None` would be misleading as well
