### ISSUE TITLE
field_to_schema should handle ListField like ListSerializer

### ISSUE THREAD

**Issue by tuky** [encode/django-rest-framework#5311]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
```python
from rest_framework.serializers import *
from rest_framework.schemas import *
field_to_schema(ListField(child=CharField()))
field_to_schema(ListSerializer(child=CharField()))
```

## Expected behavior
```python
# output: <coreschema.schemas.Array object at 0x7fc81a0540d0>
# output: <coreschema.schemas.Array object at 0x7fc819b47cd0>
```

## Actual behavior
```python
# output: <coreschema.schemas.String object at 0x7fc81a0540d0>
# output: <coreschema.schemas.Array object at 0x7fc819b47cd0>
```

https://github.com/encode/django-rest-framework/blob/master/rest_framework/schemas.py#L33

**Comment by carltongibson** [comment]
Closed by #5326
