### ISSUE TITLE
The reverse function fails on complex regex.

### ISSUE THREAD

**Issue by cnobile2012** [encode/django-rest-framework#5314]
I'm using version 3.6.3 of the framework.

What I'm seeing is that a URL like this: ```r'hosts/((?P<host>.{1,256})/)*$'``` works perfectly fine when I hit the endpoint directly, but when using ```reverse``` in unit tests it fails.

What I'm trying to do is permit the endpoint to be used with or without the ```host``` argument, but when the ```host``` argument is used it must not be longer than 256 characters. As I mentioned above it does work as long as the ```reverse``` function is not used.

The actual error message that I get is below:
  ```
  django.urls.exceptions.NoReverseMatch: Reverse for 'host-view' with keyword arguments 
  '{'host': 'ecs-vas-test2'}' not found. 1 pattern(s) tried: ['api/dsapi/hosts/((?P<host>.{1,256})/)*$']
  ```
The actual named url is ```dsapi:host-view```. The namespace does not show in the error message above, however, this happens with named urls that do not have namespaces aswell so this shouldn't make any difference.

I'm not sure if the issue is in the Rest Framework code or in the underlying Django code.

**Comment by tomchristie** [comment]
There's nothing in REST framework that'd contribute to this being an issue as far as I can see.

Could reopen this ticket if it's demonstrated that the issue *isn't* in the regex, or in Django's reverse.
