### ISSUE TITLE
get_serializer_class does not have access to self.request

### ISSUE THREAD

**Issue by faria** [encode/django-rest-framework#5315]
I am using DRF 3.6.3   I have a generics.RetrieveUpdateAPIView and I want to use a different serializer for Retrieve vs Update.  In get_serializer_class(self), I try to check self.request.method in order to return the right class.  But the error I'm getting says that request is None:

File "/Users/faria/proj/users/views.py", line 143, in get_serializer_class

    if self.request.method in permissions.SAFE_METHODS:

`AttributeError: 'NoneType' object has no attribute 'method'`

The docs appear to indicate that self.request is available in get_serializer_class, or am I reading it incorrectly?
http://www.django-rest-framework.org/api-guide/generic-views/

**Comment by xordoquy** [comment]
You did read it correctly.
Please note that the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
