### ISSUE TITLE
Schema generation with ViewSet

### ISSUE THREAD

**Issue by cristianocca** [encode/django-rest-framework#5318]
When using viewsets.ViewSet, it seems impossible to make the schema generation introspection (for django rest swagger or open api) to find the correct serializer class in order to build the body params. 

I know you could use GenericViewSet, since the requirement is that there's get_serializer method on the class, but I can't seem to find a way, if any, to return a different serializer per view set method which should be a normal use case.

Any way to do this?

**Comment by rpkilby** [comment]
Hi @cristianocca - the issue tracker is intended for bug reports & feature requests. If you're looking for [support](http://www.django-rest-framework.org/#support), I'd recommend either the IRC channel or discussion group.
