### ISSUE TITLE
[Question] Why does the APITest's client not use 'application/json' as a content type?

### ISSUE THREAD

**Issue by Enether** [encode/django-rest-framework#5322]
As nobody answered me in the discussion group, I'm taking my question here.
This thing completely threw me off when I was trying to figure out why the boolean values I passed through the test client came out as strings (integers as well).
```

# other stuff omitted
class LessonEditViewTests(APITestCase):
    def test_xx(self):
        resp = self.client.patch(f'/education/course/{self.course.id}/lesson/{self.lesson.id}',
                                 HTTP_AUTHORIZATION=self.teacher_auth_token,
                                 data={
                                     "is_under_construction": False
                                 })
```
Using this, the view receives a `is_under_construction` key in the `request.data` dict with a string value of `'False'`

This seems counter-intuitive to me and as such took me some time to figure out the problem.
To combat this, I needed to re-structure the call like this
```
# other stuff omitted
class LessonEditViewTests(APITestCase):
    def test_xx(self):
        resp = self.client.patch(f'/education/course/{self.course.id}/lesson/{self.lesson.id}',
                                 HTTP_AUTHORIZATION=self.teacher_auth_token,
                                 data=json.dumps({
                                     "is_under_construction": False
                                 }), content_type='application/json')
```

In my opinion, this should be the default behavior of the APITestCase. Is there any specific reason why this is not the way I'm suggesting?

**Comment by tomchristie** [comment]
Could have gone either way on this. The reason is that we maintain compatibility with the Django test client, and just *extend* its functionality.

Use the `format='json'` argument rather than building the content and content_type explicitly.

Alternatively set TEST_REQUEST_DEFAULT_FORMAT='json' to get this behavior everywhere... http://www.django-rest-framework.org/api-guide/settings/#test-settings

**Comment by Enether** [comment]
Yeah I could set the `TEST_REQUEST_DEFAULT_FORMAT` but that would require me to call `json.dumps` on every data, right?
I don't understand why it's not default behavior as it sounds so natural to me.

Thanks for the quick response

**Comment by tomchristie** [comment]
> Yeah I could set the TEST_REQUEST_DEFAULT_FORMAT but that would require me to call json.dumps on every data, right?

No, you'd pass the raw data.

> I don't understand why it's not default behavior as it sounds so natural to me.

Again, the reason is that we maintain compatibility with the Django test client, and just extend its functionality. On balance I'd probably prefer having taken the alternate choice too, yes, but it is where it is now.

**Comment by Enether** [comment]
I see, it automatically parses it.
It is great that this exists as an option, thanks for pointing it out!
