### ISSUE TITLE
Posting an api html form with PrimaryKeyRelatedField data gets error: "Expected a list of items but got type \"unicode\""

### ISSUE THREAD

**Issue by arctelix** [encode/django-rest-framework#5323]
## Steps to reproduce
Using the built in api playground post an html form with a PrimaryKeyRelatedField containing a list of id's
## Expected behavior
The related field should update
## Actual behavior
Error returned: "Expected a list of items but got type \"unicode\""

**Comment by carltongibson** [comment]
There’s not enough to reproduce an issue here. Can you try to provide a full example? (If not we’d have to close as unactionable) Thanks

**Comment by xordoquy** [comment]
Closing it until we have more content.
