### ISSUE TITLE
Add documentation for new command used to create users tokens

### ISSUE THREAD

**Issue by andreagrandi** [encode/django-rest-framework#5327]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

Documentation for this feature https://github.com/encode/django-rest-framework/pull/5188 is missing

## Expected behavior

We should have documentation for this new command

## Actual behavior

We don't have any documentation for this command

**Comment by tomchristie** [comment]
Ace, thanks!
