### ISSUE TITLE
HyperlinkedIdentityField doesn’t work without kwargs

### ISSUE THREAD

**Issue by merwok** [encode/django-rest-framework#5330]
## Checklist

- [ ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

* Have a view configured with a route that does not have kwargs, e.g. /users/me/
* Define `get_object` to return `self.request.user` (with `IsAuthenticated` as authn class)
* Add `'url'` to the serializer class (a ModelSerializer) and `extra_kwargs = {'url': {'view_name': 'users:profile'}}`

## Expected behavior

Response includes `"url": "http://localhost/api/v1/users/me/"`

## Actual behavior

Traceback: ```Could not resolve URL for hyperlinked relationship using view name "users:profile". You may have failed to include the related model in your API, or incorrectly configured the `lookup_field` attribute on this field.```

Adding `'lookup_field': None` gives another error: ```getattr(): attribute name must be string```.  This could be changed to become a simple way to define a `url` field where the `reverse` calls only needs a view name and no kwargs, instead of requiring users to write a HyperlinkedIdentityField subclass.

**Comment by carltongibson** [comment]
> ... instead of requiring users to write a HyperlinkedIdentityField subclass.

What does that subclass look like? Something like this, yes...

```python
class NoKwargsHyperlinkedIdentityField(HyperlinkedIdentityField):
    def get_url(self, obj, view_name, request, format):
        return self.reverse(view_name, kwargs={}, request=request, format=format)
```

My first thought is to say that's cleaner (for the special case of hyperlinked fields **not** taking a variable lookup) than adding the API surface area to account for it: 

* We **could** add a `takes_kwargs=True` attribute (or such) but the `get_url` implementation is in `HyperlinkedRelatedField`, i.e. the superclass so we'd need to refactor there to add hooks — something like a `_get_kwargs` — which we could then conditionally work around in the subclass, when overriding `get_url`. 
* But that seems like adding a lot of _nasty little methods_ just to avoid a three-line subclass. 
* Custom fields aren't meant to be something you avoid writing. I can see we **could** add flexibility here but I don't think it would be a win. 

I would close this but I see @rpkilby's 👍 — what say you? 🙂

**Comment by carltongibson** [comment]
In line with the reasoning on #5317, I am, in fact, going to close this issue. 

We explicitly don't want to add complexity to the base supported fields — especially when a solution is so easily available in a custom field. Our maintenance time is limited and there are more pressing items on the list. This one has to be a no.

**Comment by rpkilby** [comment]
After a second look, I agree w/ @carltongibson. 

Additionally, handling `lookup_field = None` in `get_url()` only solves half of the problem. Users would still need to override [`HyperlinkedRelatedField.get_object()`](https://github.com/encode/django-rest-framework/blob/3.6.3/rest_framework/relations.py#L289-L298) in order for this to work fully. Adding this ability does not seem like it would be a win.
