### ISSUE TITLE
How to optimize SerializerMethodField()?

### ISSUE THREAD

**Issue by elcolie** [encode/django-rest-framework#5336]
Hi. 
I want to optimize database hitting.<br>
https://medium.com/@sarit.r/django-serializer-experiment-b5c440d50782
Am I implement wrong coding style?

**Comment by tomchristie** [comment]
Hi there & thanks for your question.

The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions.

Thanks! 😀

**Comment by elcolie** [comment]
Okay
