### ISSUE TITLE
Schema documentation for response objects

### ISSUE THREAD

**Issue by Igonato** [encode/django-rest-framework#5338]
## Steps to reproduce

Build an API view that supports "GET" actions (list, retrieve). 

## Expected behavior

Fields information presented in some form in the schema Document.

## Actual behavior

[Generator doesn't even do introspection if the method isn't one of PUT, PATCH or POST](https://github.com/encode/django-rest-framework/blob/43c7af0bb51ba2110ec075a0ebe17f52dbb08e9c/rest_framework/schemas.py#L567)

## Reasoning

Information about return objects can be used (e.g. with [swagger-codegen](https://github.com/swagger-api/swagger-codegen)) to generate client libraries for languages and tools that support type-checking. Also, it would be nice to see "an example" object in the documentation like the included docs view or Swagger UI.

**Comment by limdauto** [comment]
This is a duplication of https://github.com/encode/django-rest-framework/issues/4502

**Comment by tomchristie** [comment]
As per @limdauto, yup.

**Comment by Igonato** [comment]
My bad!

**Comment by tomchristie** [comment]
S'all good - deserves highlighting.
