### ISSUE TITLE
3.6.4 Release

### ISSUE THREAD

**Issue by carltongibson** [encode/django-rest-framework#5340]
Checklist:

- [x] Create pull request for [release notes](https://github.com/tomchristie/django-rest-framework/blob/master/docs/topics/release-notes.md) based on the [3.6.4 milestone](https://github.com/tomchristie/django-rest-framework/milestones/***). PR: #5344
- [x] Bump remaining unclosed issues. 
- [x] Update the translations from [transifex](http://www.django-rest-framework.org/topics/project-management/#translations).
- [x] Ensure the pull request increments the version to `3.6.4` in [`restframework/__init__.py`](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/__init__.py).
- [x] Confirm with @tomchristie that release is finalized and ready to go.
- [x] Ensure that release date is included in pull request.
- [x] Merge the release pull request.
- [x] Push the package to PyPI with `./setup.py publish`.
- [x] Tag the release, with `git tag -a 3.6.4 -m 'version 3.6.4'; git push --tags`.
- [x] Deploy the documentation with `mkdocs gh-deploy`.
- [x] Make a release announcement on the [discussion group](https://groups.google.com/forum/?fromgroups#!forum/django-rest-framework).
- [x] Make a release announcement on twitter.
- [x] Close the milestone on GitHub.

**Comment by carltongibson** [comment]
Target for this is over-the-weekend, possibly into Monday.

**Comment by carltongibson** [comment]
I'm going to block this pending a result on #5343: I want to check JavaScript interaction not broken for nested links. (TODO: proper test project for manual testing...)

(It may let us sneak a couple of little ones in too.)

**Comment by carltongibson** [comment]
#5343 is resolved — JS interaction for nested docs is tested to work.

**Comment by carltongibson** [comment]
#5344 closed this, but it's not quite done yet.

**Comment by carltongibson** [comment]
OK, this is done. 

https://pypi.python.org/pypi/djangorestframework/3.6.4

PyPI page didn't render properly. I'll look into that for next time.

**Comment by tomchristie** [comment]
Rad!

**Comment by jpadilla** [comment]
@carltongibson probably missing `pypandoc`? I think [this](https://github.com/encode/django-rest-framework/blob/master/setup.py#L63) is not properly exiting here and using [this](https://github.com/encode/django-rest-framework/blob/master/setup.py#L19) fallback.

**Comment by carltongibson** [comment]
@jpadilla I thought I had that... 🙂 but yes.
