### ISSUE TITLE
JSON output should be sorted 

### ISSUE THREAD

**Issue by sergiomb2** [encode/django-rest-framework#5341]
After comment in https://github.com/encode/django-rest-framework/pull/4202 it was suggest that I open a new issue , with python 3.5 my data is a dictionary and not a OrderDict so the result is almost random sorted and to fix it, we just need add sort_keys=True, in line 105 of  /usr/lib/python3.5/site-packages/rest_framework/renderers.py where we have  ret = json.dumps .
Reading de pull request mention my suggestion is if type (data) = dict use sort_keys=True if type of data is an orderdict don't 

Thanks,

## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

**Comment by carltongibson** [comment]
This isn't something we're going to add to the core. Either return an `OrderedDict` or provide your own renderer implementing the change you want. 

> ...with python 3.5 my...

Whilst it ["should not be relied upon"](https://docs.python.org/3/whatsnew/3.6.html#new-dict-implementation), `dict` maintains key order in Python 3.6. You may just want to upgrade.

**Comment by sergiomb2** [comment]
After analyze my code I realize that I'm using JSONField  with [1] and the problem is that we receive dictionaries in posts of http and the problem is the output of the results of these JSON Fields ...  
About extend class JSONRenderer , we only need add sort-keys in json.dumps , yeah I could copy all render function but I don't understand why not sorted specially if is a dictionary , or if we may have the option to not sort it, i.e it will not change the default behavior , please take a look to  https://github.com/encode/django-rest-framework/pull/5347

[1] 
https://github.com/adamchainz/django-mysql/
