### ISSUE TITLE
Django rest framework 3.6.4 release hangs when reading request.data property

### ISSUE THREAD

**Issue by robvdl** [encode/django-rest-framework#5352]
Since upgrading to DRF 3.6.4 it made our tests hang, after spending a few hours drilling down why, it turns out as soon as reading request.data it hangs.

Going back to DRF 3.6.3 fixed the problem.

**Comment by carltongibson** [comment]
OK. Thanks for the report. Any chance you could demonstrate the hang (the DRF suite is running fine) or use git bisect to find where the issue was introduced?

**Comment by robvdl** [comment]
That is the problem because this is a project I am working on at work, but I will try my best to get more details tomorrow and make a bit of a test case if needed.  I need to find out exactly what the issue is, because it is happening during a unit test in our system but I need to be sure that it isn't me that is doing something wrong :)  If so, I will close the issue.

**Comment by xordoquy** [comment]
That's the point of asking for single isolated test case. In 99% it sorts out whether it's on DRF side or one's project ;)

**Comment by robvdl** [comment]
I am closing this because I cannot prove it in an isolated Django project, I think the previous devs on our own codebase have done some crazy magic with the tests that is making it hang.

Spent a few hours trying to reproduce it, but just couldn't

**Comment by carltongibson** [comment]
Okay, thanks for the follow-up. 

If you manage to track it down to something our end please do come back to us.

**Comment by robvdl** [comment]
It's totally not drf's fault I tracked it down to something the original authors of our code base did, they subclassed JSONParser for some reason and called it LoggingJSONParse and created a FakeStream class and send that to super().parse() instead of the actual stream object which appears to be WSGIRequest.  Obviously this is pretty non-standard, which is why I closed this issue as it has nothing to do with drf itself.

**Comment by carltongibson** [comment]
OK. Thanks again for the follow-up. Good luck with your project.
