### ISSUE TITLE
Possibly erroneous description of `Response.data` attribute

### ISSUE THREAD

**Issue by ScottKelly** [encode/django-rest-framework#5360]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Visit http://www.django-rest-framework.org/api-guide/responses/#data
## Expected behavior
The description of `.data` should be accurate
## Actual behavior
The attribute `.data` is described as the unrendered content of a `Request` object when it's referred above as the serialized content of the response.

ref #5361

**Comment by carltongibson** [comment]
Closed by #5361
