### ISSUE TITLE
Allow naming of a permission being checked thats value is then saved to request.permissions

### ISSUE THREAD

**Issue by jturmel** [encode/django-rest-framework#5364]
We have situations where depending on the permission checks that passed we want to switch the serializer to do something different, like a **IsOwner** vs a **IsFriend** check. Then when running through get_serializer_class we check whether request.permissions.get('IsFriend') is True (or not False or None) depending on what we're doing and set a different serializer. It would be nice if this was built into the framework maybe in a way that where if you could instantiate the permission to be used by calling IsFriend(name='are_friends') otherwise it wouldn't set a value on request.permissions at all (to avoid collisions, etc) ...

Thoughts?

**Comment by carltongibson** [comment]
This is going to be out of scope for Django REST Framework itself. 

You're very welcome to implement some kind of `UserPassesTest` base permission that keeps a track of the results (somewhere) and then query that later. You may even want to package that up as a third-party app—we'd happily link to it from the docs—but it's not something we'd add to core.

**Comment by jturmel** [comment]
The idea is that you can use the core permissions that are already available like IsAutheticated and have a way to know that permission check passed or failed. I guess I'm lost on how that's outside the scope of the framework absolutely.
