### ISSUE TITLE
Authentication and source code selection buttons in interactive API docs overlap with API endpoints

### ISSUE THREAD

**Issue by rubendv** [encode/django-rest-framework#5370]
## Checklist

- [ ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [ ] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Have enough DRF API endpoints / a small enough window so that the endpoints in the navbar reach to the bottom of the window.

## Expected behavior
The Authentication and source code selection buttons appear below all endpoints. Endpoint list could be scrollable?

## Actual behavior
The Authentication and Source Code language selection buttons on the bottom left of the interactive API docs overlap with endpoints in the navigation bar on the left when there are enough endpoints.
When you uncollapse an endpoint close to these buttons it opens under these buttons.

![Example](https://user-images.githubusercontent.com/1076757/29807708-6a3b3614-8c95-11e7-8cb1-77d05e75a520.png)

**Comment by rubendv** [comment]
We have already started fixing this ourselves, as it is important for us that this is fixed in the coming weeks.

**Comment by carltongibson** [comment]
@rubendv Thanks for the report. 

> ... a small enough window...

Grrr. Yes. Always tricky. 

I'd definitely be happy to see a PR on this. Both screenshots and a demo project where we can see this  action are helpful in reviewing.

**Comment by JonasVDB-awingu** [comment]
We have fixed this for now by overwriting the style of the menu-list-bottom in the sidebar.html file:

`<ul class="menu-list menu-list-bottom" style="position: static">`

The downside of this solution is that the 'authentication' and 'source code' menu items are shown below the API resources and are not always visible (depending on the screen size) without scrolling.

**Comment by anshengme** [comment]
@JonasVDB-awingu How did you change the value of the API documentation HTML?

**Comment by carltongibson** [comment]
I'm going to de-milestone this for now. 

I'm fairly sure a flexbox solution would solve most issues here. 

Something like this gets us quite close: 

```
.sidebar > .menu-list {
    display: flex;
    flex-direction: column;
    justify-content: space-between;
}
```

Then we're just missing the `height` on the `.sidebar > .menu-list` element (which we should be able to achieve converting the sidebar to `display: flex` too). 

No doubt a bit of experimentation is needed to get it just right. I'm very happy to see a user PR for this

**Comment by andrewhannum** [comment]
I seem to have discovered a simple solution to this. By changing menu-list-bottom to use "position: sticky" (as opposed to "static" or "absolute"), the Auth/Code menu items stick to the bottom of the sidebar as expected with no other changes, and continue to operate correctly even during interaction (collapse, uncollapse, etc.).

The downside of this is that "position: sticky" is a recent CSS addition and will only work in more modern browser versions (and no versions of IE).

I've opened a pull request for this change here: https://github.com/encode/django-rest-framework/pull/5516
