### ISSUE TITLE
List serializer configuration would simplify drf-hal-json extension

### ISSUE THREAD

**Issue by claytondaley** [encode/django-rest-framework#5391]
[`drf-hal-json`](https://github.com/Artory/drf-hal-json) (linked to the active fork) is a 3rd party library that formats responses in compliance with the HAL spec.  The HAL spec requires that all resources (including `-list`) be rendered as a `dict` with a link to its own URL (in `_links.self.href`).

The default behavior of DRF for an unpaged `-list` resource is to render it as a `list` of `dict`.  Obviously, a `list` cannot have a `_links` key so [the PR at Antory\drf-hal-json#20](https://github.com/Artory/drf-hal-json/pull/20):

 - replaces the default `ListSerializer` with a `HalListSerializer`
 - constructs a link for the `-list` of the resource

Any 3rd party formatter that is incompatible with a top-level `ListSerializer` would require a similar change.  Unfortunately.  the default `ListSerializer` is [hard coded](https://github.com/encode/django-rest-framework/blob/master/rest_framework/serializers.py#L157) in `many_init`.  To (1) continue to support a user-defined `Meta` value, (2) change the default, and (3) avoid duplicating core code, the PR [conditionally injects](https://github.com/Artory/drf-hal-json/pull/20/files#diff-b4cde0b81fcd75168eccbc3c3a11ad8cR64) the new default into Meta.  It would be simpler/cleaner if [the default was configurable on the class](https://github.com/Artory/drf-hal-json/pull/20/files#diff-b4cde0b81fcd75168eccbc3c3a11ad8cR55) and could be overridden by the `HalModelSerializer`.

The infrastructure for constructing `-detail` URLs is also spread across several files.  This plugin needed the same for `-list`.  Because there's no call supporting `view_name`, the PR adds [a meta option to override the default](https://github.com/Artory/drf-hal-json/pull/20/files#diff-b4cde0b81fcd75168eccbc3c3a11ad8cR39).  I'm not sure if the same setting would be any help in the core, but wanted to at least draw attention to it as it might eliminate the need for a `view_name` in other cases.

**Comment by carltongibson** [comment]
Parameterising the list serialiser class certainly seems valid. Happy to at least look at a PR on that.

**Comment by carltongibson** [comment]
I’m going to close this. Happy to see a simple solution as per #5393 but we’re not going to consider it an _Open Issue_.
