### ISSUE TITLE
pickled = pickle.dumps(value, pickle.HIGHEST_PROTOCOL) PicklingError: Can't pickle <type '_sre.SRE_Pattern'>: attribute lookup _sre.SRE_Pattern failed

### ISSUE THREAD

**Issue by sagarg1988** [encode/django-rest-framework#5392]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

**Comment by sagarg1988** [comment]
I am facing this issues while setting the cache value of  serializer, 
    `serializer = ModelSerializer(object_settings)` # object_settings is object of Setting Model(not default settings)
    serializer = cache.get(key, None)

**Comment by xordoquy** [comment]
Serializers aren't pickable and I'm not sure we'll work on that.
Any reason you're not just caching the result ?
