### ISSUE TITLE
Docs crash when a viewset is called `data`

### ISSUE THREAD

**Issue by akx** [encode/django-rest-framework#5395]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework. (Commit 71ad99e0b276a90d055)
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

* Register a viewset with the name `data` to a router. (`router.register('data', SomeViewSet)`)
* Navigate to the generated API docs page (as included by `include_docs_urls()`)

👉  See a minimal test repo here: https://github.com/akx/drf-docs-fail

## Expected behavior

The docs work as usual.

## Actual behavior

Docs crash with 

> *AttributeError*: 'Link' object has no attribute 'links'
> in djangorestframework/rest_framework/templatetags/rest_framework.py
> / schema_links, line 253

## Workaround

Don't name a viewset `data`.

(However, this isn't an acceptable workaround in my project, since the viewset literally concerns bits of data, and any other name would be worse.)

**Comment by carltongibson** [comment]
This'll need the same fix as #4972 (Fancy doing a PR?)

Thanks of the report!

**Comment by akx** [comment]
Mmm, if I understand correctly, this would require a `data` filter (to make it possible to reference the `data` attribute as opposed to Django's implicit `['data']`)?
If that is the case, would it maybe be better to write a generic `attr` filter?

```django
{% for link in document|attr:data|items %}...{% endfor %}
```

**Comment by carltongibson** [comment]
Yep. Sounds good.
