### ISSUE TITLE
Allow `include_docs_urls` to configure Schema View Authentication

### ISSUE THREAD

**Issue by psychok7** [encode/django-rest-framework#5399]
Hi there, i am using the built in api documentation from drf 3.6 http://www.django-rest-framework.org/topics/documenting-your-api/

I am only able to access the API docs if i am logged into Django admin for example (even if my endpoints do not have any authentication).

Is there a way for me to disable the authentication in the API docs?

Thanks

**Comment by carltongibson** [comment]
@psychok7 What are your [`DEFAULT_AUTHENTICATION_CLASSES`](https://github.com/encode/django-rest-framework/blob/master/rest_framework/settings.py#L41-L44)? You're probably requiring Session or Basic auth implicitly. 

You can set these to `[]` as a work around. Either that or you'll need to manually configure the docs view. 

The `include_docs_urls` should allow this. (But currently doesn't)

**Comment by psychok7** [comment]
@carltongibson your workaround worked, thanks

**Comment by carltongibson** [comment]
#5309 sketches this.
