### ISSUE TITLE
Field class name lower case

### ISSUE THREAD

**Issue by jun0jang** [encode/django-rest-framework#5402]
why is empty class lower case at fields.py?
if this is faulty, can i contribution?

**Comment by xordoquy** [comment]
fields.py doesn't lowercase classes names.
field names are either taken from the `Serializer` definition or extracted from the `Model`'s.
I'm closing this issue as it's not clear in its current form and looks more like a usage issue.

**Comment by jun0jang** [comment]
```
class empty:
    """
    This class is used to represent no data being provided for a given input
    or output value.

    It is required because `None` may be a valid input or output value.
    """
    pass
```
but empty class is starting capital letter
https://github.com/encode/django-rest-framework/blob/master/rest_framework/fields.py#L43
