### ISSUE TITLE
Allow explicit adding `renderer` to `Response`

### ISSUE THREAD

**Issue by GlaciErrDev** [encode/django-rest-framework#5405]
Hi folks!

I want to have a possibility to explicitly add `renderer` class to my response(`Response`)

Because when I have way for handling either CSV renderer for response CSV file if everything is ok or 
return `Response` in JSON format with an error message.

I can't do it with `renderer_classes = ...` or `content_negotiation_class = ...`

Thanks and Regards,
Mike

**Comment by carltongibson** [comment]
https://github.com/encode/django-rest-framework/blob/d300c3c648e6141c47dd28769036727f85281721/rest_framework/views.py#L385-L387

You can manually rest these values in your view before returning your response. 

The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!

**Comment by GlaciErrDev** [comment]
This is not what I need, `perform_content_negotiation` this action starts before my logic in `list` or `create`.
