### ISSUE TITLE
Django MinValueValidator message not being copied to Serializer fields

### ISSUE THREAD

**Issue by rvignesh89** [encode/django-rest-framework#5410]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

Create a decimal field with a MinValueValidator and a custom error message. 

```python
class ItemModel(models.Model):
    price = models.DecimalField(decimal_places=2, 
                                max_digits=10, 
                                validators=[MinValueValidator(limit_value=0, 
                                                    message='Price has to be >= 0.')])

class ItemSerializer(serializers.ModelSerializer):
    class Meta:
        model = ItemModel
        fields = '__all__'

data = {'price': -1}
serializer = ItemSerializer(data, partial=True)
serializer.is_valid()



```

## Expected behavior

```python
serializer.errors['price'] == ['Price has to be >= 0.'] 
```

## Actual behavior

```python
serializer.errors['price'] == ['Ensure this value is greater than or equal to 0.'] 
```

### Extra

I've drilled down this problem to be here,

```python
    # Ensure that min_value is passed explicitly as a keyword arg,
    # rather than as a validator.
    min_value = next((
        validator.limit_value for validator in validator_kwarg
        if isinstance(validator, validators.MinValueValidator)
    ), None)
    if min_value is not None and isinstance(model_field, NUMERIC_FIELD_TYPES):
        kwargs['min_value'] = min_value
        validator_kwarg = [
            validator for validator in validator_kwarg
            if not isinstance(validator, validators.MinValueValidator)
        ]
```

Based on my understanding of the codebase a fix looks something like this.

```python
    # Ensure that max_value is passed explicitly as a keyword arg,
    # rather than as a validator.
    min_value, message = next((
        (validator.limit_value, validator.message) for validator in validator_kwarg
        if isinstance(validator, validators.MinValueValidator)
    ), (None, None))
    if min_value is not None and isinstance(model_field, NUMERIC_FIELD_TYPES):
        kwargs['min_value'] = min_value
        kwargs['error_messages'] = {'min_value': message}
        validator_kwarg = [
            validator for validator in validator_kwarg
            if not isinstance(validator, validators.MinValueValidator)
        ]
```

The same problem also exists for other type of validators because they seem to be constructed in a similar manner.

I'll submit a PR with a failing test to confirm the issue on `master`.

**Comment by xordoquy** [comment]
Maybe we should not remove that validator and leave it as it is.

**Comment by carltongibson** [comment]
> Maybe we should not remove that validator and leave it as it is.

OK. I had a think about this. Bottom line: Yes, maybe, there's a case for altering the way we do things here. We're popping a declared validator just to re-create an equivalent one... It's also a bit of a head-mess to keep track of exactly where what validator is coming form and where it applies etc. Maybe we could refactor to clear this up. 

But I don't think we should do that now. I'm not going to open an issue for it. If we adjust here over time, as the input arrives I think that's OK. I think for now we should go on with the existing decisions. 

So here we just need to finish up #5411 and we'll call it a day.

**Comment by carltongibson** [comment]
Closing as per https://github.com/encode/django-rest-framework/pull/5572#issuecomment-345628358
