### ISSUE TITLE
Question for ModelViewSet: Unintuitive call of filter_queryset for update, retrieve/detail, delete calls?

### ISSUE THREAD

**Issue by anx-ckreuzberger** [encode/django-rest-framework#5412]
Before you call redirect me to StackOverflow, please hear me out. My question is not related on how to implement something. I am however trying to raise awareness that there is something already implemented in DRF that seems to be unintuitive (for me). (FYI, I am using DRF 3.6)

**TL;DR:**  I am questioning why would one even call ``filter_queryset`` in the ``get_object`` method of a (Model)ViewSet?

# Example
I have a ModelViewSet with ModelSerializer and am using a soft-delete filter which automatically hides all objects that have ``deleted == True`` (without having to specify this filter):
When I call ``GET /api/tasks/`` I only get objects that have not been deleted (yet).

However, I can also explicitly define this filter:
``GET /api/tasks/?deleted=on`` or ``GET /api/tasks/?deleted=off`` (default).

Now this is fine for list calls, and can be easily accomplished with django filters (Using a BooleanDefaultFilter and BooleanDefaultField).

But when I want to do a retrieve/detail call, e.g., ``GET /api/tasks/123/``, I usually do not specify any filters (makes sense, does it?). 

This leads to a very simple problem: Soft-deleted objects can not be found using the above detail call. Problem: ``filter_queryset`` is called for the ``get_object`` method, and as I have ``deleted=off`` as a default filter, I will not be able to make detail calls on soft-deleted object. 

To retrieve a soft-deleted object I would have to make the following API call:
``GET /api/tasks/123/?deleted=on``.

This behaviour seems unintuitive for me (why would I need to provide a filter for a detail call?).

# DRF Source

It is very easy to see what is going on in the ViewSet. Every call to ``get_object`` does this:
```python
queryset = self.filter_queryset(self.get_queryset())
```
(see https://github.com/encode/django-rest-framework/blob/master/rest_framework/generics.py#L77-L103 ).

So essentially, if I do not want this behaviour, I just have to override ``filter_queryset`` like this:
```python
    def filter_queryset(self, qs):
        if self.action == 'list':
            return super(BaseViewSet, self).filter_queryset(qs)

        return qs
```
I consider my code from above as dirty and non-pythonic. It's a hack.

So either I am missing the point of why ``get_object`` is calling ``filter_queryset`` (feel free to teach me a lesson here), or (please forgive me if I sound ignorrant) ``get_object`` should just not be calling ``filter_queryset`` at all.

Please discuss and let me know if I should provide a PR and a test.

**Comment by xordoquy** [comment]
This will be more clear if you consider the `filter_queryset` removes rows a user shouldn't be able to see. If we remove the call to `filter_queryset` then anyone will be able to see any object.

**Comment by xordoquy** [comment]
NB: I agree in your use case that's counter intuitive although in other it's totally valid.
Maybe we can improve that by adding a word on the documentation about the instances calling the filtering.

**Comment by anx-ckreuzberger** [comment]
Thank you for the reply. I hope this issue won't be completely ignored now that it is closed, as I would like to provide more reasoning behind this, and maybe we can find a solution that is not API breaking. I do see the point that ``DjangoObjectPermissionsFilter`` would need this kind of behaviour to continue working as it is. I do have a proposal at the bottom of this wall of text on how we could extend the behaviour of DRF in the future.

# Some more Reasoning

> This will be more clear if you consider the filter_queryset removes rows a user shouldn't be able to see. If we remove the call to filter_queryset then anyone will be able to see any object.

I was thinking that this is the reason behind it, and it's perfectly valid for simple use cases of ``ModelViewSet``, such as:

```python
class SimpleModelViewSet(ModelViewSet):
    queryset = Task.objects.all()
    serializer = TaskSerializer
    filter_class = ShowOnlyTasksOfCurrentUserFilter
```

with ``ShowOnlyTasksOfCurrentUserFilter`` being responsible for filtering out tasks for the current user.

I consider my use case of the ``ModelViewSet`` to be a bit more advanced then that (but then again, maybe I am doing it wrong). My ViewSet looks more like this:

```python
class ComplexModelViewSet(ModelViewSet):
    queryset = Task.objects.none()
    serializer = TaskSerializer
    filter_class = TaskFilter

   def get_queryset(self, ...):
       """ Get all Tasks that are viewable by the current user, and select/prefetch related elements """
       Task.objects.viewable_by_current_user().select_related('project').prefetch_related('sub_tasks')
```

The ``TaskFilter`` filter itself could now furthermore allow filtering by ``project``, or by the task start date, etc..., but has absolutely nothing to do with permissions and such.

Basically I already take care about what the user is allowed to see in the ``get_queryset`` method by calling a self-written QuerySet method ``viewable_by_current_user``. I am aware that ``DjangoObjectPermissionsFilter`` will do the opposite and lets the ``filter_queryset`` method take care of restricting the queryset.

Anyway, I would like to extend the behaviour of filtering/restricting for future versions of DRF, by splitting filtering into two parts:

- part 1: restricting
  Filters should restrict the output (e.g. for permissions) (failing to come up with a better name, I just call this ``restrict_queryset`` for now, making it more verbose that these are the filters that will actually restrict access to certain elements) - these could be mainly filters that do not rely on query parameters
- part 2: filtering/sorting
  Filters should only reduce/re-order the queryset based on query parameters (e.g., sorting, full-text-search, filtering by a single parameter) (also, failing to come up with a better name here, I will keep ``filter_queryset`` for this sort of filtering) - these could be filters that rely on query parameters

The behaviour of the API endpoints would then be as follows:

- list endpoint calls ``self.filter_queryset(self.restrict_queryset(self.get_queryset()))``
- retrieve/update/delete endpoints that call ``get_object`` will call ``self.restrict_queryset(self.get_queryset())``

I hope my proposal is not considered obsolete or stupid. I'm not saying this is what it should look like in a perfect world, I'm just trying to improve on how filters could work in the future, and I'm more then happy to help to push this forward into DRF.

**Comment by carltongibson** [comment]
Hi @anx-ckreuzberger.

Your suggestion is neither stupid nor obsolete. It makes plenty of sense. 

Your use of `get_queryset` is textbook, and, yes, in that context the enforced filtering can seem redundant. I’ve hit this exact query myself. #5237 comes up simply by it being overlooked. 

Reading your comments I’m with you more or less all the way. The bit I didn’t agree on was your objection to overriding `filter_queryset`. I didn’t see a problem there. Yes, the particular code is just for your one case, but I could see that being generalised as you develop. It didn’t strike me as objectionable. 

Then when we come to the actual proposal I’m -1.

You’ll be welcome to implement a bass view class with this kind of behaviour but for me the extra API just isn’t something we want to add to the framework. We aim to keep it tight. One reason it’s so good is because that’s been maintained over a number of years. Our goal is to cover the core use cases. For me this is outside that. 

I’m also not sure that I don’t prefer just recommending that you do in fact just implement `filter_queryset` rather than looking for a generic solution here. If you look at the base implementation, it is about handling the possible list of filter backends. If you drop that (i.e. don’t call `super`) your implementation is two lines of crystal clear code. (And you could save one dropping the class attribute.)

When given the choice here between adding API to the framework itself or two lines in user land code I’m always going to vote for the latter. It’s not that your idea is stupid, far from it. It’s just that I’m not sure it’s good for the health of the project.

**Comment by anx-ckreuzberger** [comment]
Hi!

I can totally understand that introducing additional complexity to the API/filters is something you do not want. Also, thank your for providing more insight on this. As you said, #5237 is related to this, and maybe with some time and more users finding their way into those filter methods, we will find a more elegant solution.
