### ISSUE TITLE
(non-default) port missing with absolute URLs (e.g. in schema URL)

### ISSUE THREAD

**Issue by blueyed** [encode/django-rest-framework#5416]
`request.build_absolute_uri()` is used in e.g. [`SchemaGenerator.get_schema()`](https://github.com/encode/django-rest-framework/blob/9aaea2586bf5a5fab0294943d069e92969b497f2/rest_framework/schemas.py#L311), but this does not include the port being used.

This is bad when using e.g. the coreapi-cli client against a local runserver instance, where links cannot be resolved then.

While the port could be included on Django's side maybe, it might be better to use [`get_raw_uri()`](https://github.com/django/django/blob/ac756f16c5bbbe544ad82a8f3ab2eac6cccdb62e/django/http/request.py#L147) instead?!

**Comment by rpkilby** [comment]
Hi @blueyed. Off the cuff, this doesn't sound correct. Both `request.build_absolute_uri()` and `request.get_raw_uri()` ultimately make calls to `request._get_raw_host()`, which is what is used to return the HOST+PORT.

**Comment by blueyed** [comment]
@rpkilby 
You're right - so it would likely not help to use `get_raw_uri()` then, and I need to investigate if and why `_get_raw_host()` does not work.

**Comment by rpkilby** [comment]
Sounds good. I'm going to close this for now, since this sounds like a configuration issue.

**Comment by blueyed** [comment]
It turned out to be a bug in coreapi-cli when using `--debug`.. https://github.com/core-api/coreapi-cli/pull/22
