### ISSUE TITLE
How to get a custom request header when i use Custom authentication

### ISSUE THREAD

**Issue by Rmond** [encode/django-rest-framework#5420]
i use the custom authentication like this:
```
 class CustomAuthentication(authentication.BaseAuthentication):
    def authenticate(self, request):
        username = request.META.get('HTTP_X_USERNAME')
        #username = request.META.get('X_USERNAME')
        print username
        #username =  request.data.get("username",None)
        if not username:
            return None
        try:
            user = Users.objects.get(username=username)
        except Users.DoesNotExist:
            raise exceptions.AuthenticationFailed('No such user')
        return (user, None)
```
but I can't get the request header when use request like this 
`.\curl.exe -v -H 'X_USERNAME:A17041708' http://127.0.0.1:8000/api/users`
I print the ' request.META' ,is not have 'HTTP_X_USERNAME' or 'X_USERNAME'.how should i do to get the custom header

**Comment by tomchristie** [comment]
Hi there & thanks for your question.

The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions.

Thanks! 😀

**Comment by Rmond** [comment]
I'm sorry, but I can't open the  discussion group ,because i am come from china

**Comment by tomchristie** [comment]
https://stackoverflow.com/ is a good alternative then.

> I print the ' request.META' ,is not have 'HTTP_X_USERNAME' or 'X_USERNAME'.how should i do to get the custom header

If it's not in `request.META` then it must be getting removed *before* the Django application. Either by the server, or by some intermediary.

**Comment by amjada0903** [comment]
try 
.\curl.exe -v -H 'UserNameE:A17041708' http://127.0.0.1:8000/api/users

and change the authenticate function username = request.META.get('HTTP_USERNAME')

**Comment by pcoelho-ubi** [comment]
All headers with  underscore are stripped from the request https://code.djangoproject.com/ticket/25048 , It took me some time to find this so I though I'll leave it here.

If you really want to use an underscore use an hyphen in the request (ex. "API-KEY" becomes requests.META["HTTP_API_KEY"]).
