### ISSUE TITLE
Serializer#to_internal_value inconsistency on the value returned

### ISSUE THREAD

**Issue by pardo** [encode/django-rest-framework#5423]
If I call the api using `Content-Type:application/x-www-form-urlencode`
it will make the rest framework internals to handle data as a QueryDict

and if a call the api using  `Content-Type:application/json`
rest framework internals will handle data as an standard python {}

This behavior makes **ListSerializer** to return **empty** when the content type is **json** and an **empty python list** if it is url encoded data

You can easily reproduce running this code

```python
from django.http.request import QueryDict

from rest_framework import serializers
from rest_framework.serializers import ListSerializer
from rest_framework.fields import empty

# look at rest_framework.serializers.Serializer#to_internal_value

class EmailSerializer(serializers.Serializer):
    email = serializers.EmailField()
    content = serializers.CharField(max_length=200)
    created = serializers.DateTimeField()

email_serializer = EmailSerializer()
email_serializer.field_name = "email"
assert email_serializer.get_value({}) is empty
assert email_serializer.get_value(QueryDict()) is empty

email_list_serializer = ListSerializer(child=EmailSerializer())
email_list_serializer.field_name = "email_list"
assert email_list_serializer.get_value({}) is empty
# this will fail because is returning an empty list instead of empty
assert email_list_serializer.get_value(QueryDict()) is empty
```

**Comment by pardo** [comment]
this is related #5175

**Comment by rafalp** [comment]
This also makes `required=True` don't do anything when `ListField` is skipped in form data, whereas expected behavior would be failing validation with the "This field is required" error.

**Comment by tomchristie** [comment]
> This behavior makes ListSerializer to return empty when the content type is json and an empty python list if it is url encoded data

Yup - there's not much we can do about that. `application/x-www-form-urlencode` is not able to differentiate between an empty list and no data. We deliberately choose to interpret it as an empty list in that case. The problem with altering that behavior would mean you'd never be able to set a list field to empty with that encoding.

Best solution - only specify `JSON` parsers on views that include data structures that form data cannot properly handle.

**Comment by rafalp** [comment]
@tomchristie Your answer makes sense, but wouldn't similarity of behaviour be the goal here?

Currently I'm seeing conflicting defaults:

Django - empty fields raise validation error
JSON - if field is empty, validation error is raised

FORM - if field is empty, no validation error is raised, you need to remember about `allow_empty=False` of you'll be up for surprise.
