### ISSUE TITLE
Add More Examples of Writable Nested Serializers to Documenation

### ISSUE THREAD

**Issue by rodmanning** [encode/django-rest-framework#5425]
## Checklist

- [X] I have verified that that issue exists against the `master` branch of Django REST framework.
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [X] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [X] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Short Version

Can we please add the information in [3.0 Announcement](http://www.django-rest-framework.org/topics/3.0-announcement/#removal-of-transform_field_name) about the use of `to_representation` on serializers __classes__ (cf. _Removal of Transform Field_) to the docs to help better explain how to change the representation of fields in ModelSerializers?

(Sorry about the non-standard format for the issue text, just made more sense this way given that it's a documentation suggestion (feature/functionality is great!)

I can do up a pull request which just moves the information in the _3.0 Announcement_ into `serializers.md` (probably into [override-serialization-and-deserialization-behaviour](http://www.django-rest-framework.org/api-guide/serializers/#overriding-serialization-and-deserialization-behavior)) if that suits?
## Long Version

Outcome desired was to have a related field (i.e. `ForeignKey`) on a `ModelSerializer` that was writable by passing the `pk`, but returned a nested representation. For example:

```
class ExampleModel(models.Model):
    user = models.ForeignKey(User)
    ...

class ExampleUserSerializer(serializers.ModelSerializer):
    class Meta:
        model = User
        fields = ["username", "email", ... ]


class TestSerializer(serializers.ModelSerializer):
    class Meta:
        model = ExampleModel
        fields = ["user",]`
```

Problem I struggled with was changing the representation to use the nested `ExampleUserSerializer`, but to accept write input to `TestSerializer` with just the User's `pk`. For example, you could update the `user` on `ExampleModel` by sending a request with:
    
    {"user": 3}

And get back the updated `ExampleModel` as:

    {"username": "myusername", "email": "me@world.com", ...}

Worked it out by adding a `to_representation` method on the `TestSerializer` (etc.) by referring to the bit about _"Removal of Transform Field"_ in [3.0 Announcement](http://www.django-rest-framework.org/topics/3.0-announcement/#removal-of-transform_field_name). Found _some_ information about this at [override-serialization-and-deserialization-behaviour](http://www.django-rest-framework.org/api-guide/serializers/#overriding-serialization-and-deserialization-behavior), but the example in the _3.0 Announcement_ just made it so much clearer.

**Comment by janicheen** [comment]
I'm a beginner at DRF and have been struggling to find a clean and proper way to deal with exactly this. Could you share your solution using to_representation? I totally agree this should be better covered in the documentation. It must be a fairly common issue?

**Comment by xordoquy** [comment]
This seems to be a pretty common but - in my opinion - a not so good design.
Issue with nested serializers is that they are *complex*. Everybody would love to see its own use case covered although they are quite a lot of different use cases.

Note that the 3.0 announcement has an explicit example to help for the upgrade from 2.x to 3.x.
You should be able to find this covered by a couple of blog post.

I'm not convinced that should go into the nested serializer section. It's a broader topic that's already covered in the [Overriding serialization and deserialization behavior](http://www.django-rest-framework.org/api-guide/serializers/#overriding-serialization-and-deserialization-behavior). At most, I'll consider a short sentence that links to that part.

**Comment by rodmanning** [comment]
Fair enough — my design decision traded complexity in the API for some trade-offs in the frontend logic, but understand it's not always ideal (and that there are _lots_ of use cases to cover).

Thing that got me in this case was that I wasn't expecting to find the information that solved my problem in the _release notes_, and the example that's already in the release notes was really useful to me.

Short sentence linking to relevant example/notes would be great, as that would've pointed me in the right direction sooner.

**Comment by tomchristie** [comment]
I think that adding an example to this section... http://www.django-rest-framework.org/api-guide/serializers/#overriding-serialization-and-deserialization-behavior would be pretty reasonable. I don't particularly think that we should use nested serializers for that example, but I do think that demonstrating how you can use `to_representation`, in a similar way to the example in the 3.0 announcement would be fair enough.

**Comment by nevermorever** [comment]
So is what's the best way to deal with this, override serializer behavior or use distinct serializer when read and write?
