### ISSUE TITLE
Serialize Django Model field's parameters in Rest Framework

### ISSUE THREAD

**Issue by davidrdz93** [encode/django-rest-framework#5428]
I would like to know how it is posible to serialize some attributes that are defined in models.py, for example:'verbose_name ', 'help_text' or even 'read_only' specially when using ModelSerializer.I know it is posible to access all field's parameters with SerializerMethodField() but Immagine (like in my case) if you have models with many fields (in my case 40 fields), then you must do 40 SerializerMethodField() in order to have that data serialized for my front-end (in my case angular-cli).
I have been looking for this answer for a while without success.!

Sorry if this is not the right place to make this answer!

**Comment by tomchristie** [comment]
Hi there & thanks for your question.

The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions.

Thanks! 😀
