### ISSUE TITLE
Add Glossary to Docs

### ISSUE THREAD

**Issue by guettli** [encode/django-rest-framework#5431]
I would like to add a highlevel perspective in the quickstart.

http://www.django-rest-framework.org/tutorial/quickstart/

I would like to define terms and steps. I am not a native speaker, I guess this could get improved a lot.

**GET Request**

1. client sends a GET request to the DRF application
1. A **Serializer** uses the Django ORM and transforms it to ?????? (here I am missing the matching term)
1. A **Renderer** takes ?????? and converts it to a bytestring. This can be JSON, YAML, XML, Protocol Buffers, ...
1. The bytestring gets send to the client as response

**POST Request**

1. client sends a POST request to the DRF application. The bytestring in the request can be JSON, YAML, ...
1. A **Parser** takes the bytestring and transforms it to ??????. 
1. ?????? gets mapped to a Django Model using a **Deserizalizer**
1. The data gets saved
1. A response gets send to the client.

My goal is to speed up new developers and to make them  understand how DRF works quicker.

What do you think?

It would be great if there are places in the docs where the terms Serializer, Renderer, Parser gets explained. 

I know, for you (the experts) it is all clear :-)

**Comment by carltongibson** [comment]
Hi @guettli. 

I guess I'd draw a distinction between the Quickstart and the rest of the Tutorial ([starting here](http://www.django-rest-framework.org/tutorial/1-serialization/)). (I note the navigation doesn't really make that clear as it stands.)

I see the Quickstart as for people already familiar with Django Request/Response cycles and HTTP methods who just want the code examples to begin. They'll hit the API Guide next. I see the tutorial as taking a slower walk through to build up the information your talking about. 

The Quickstart ends: 

> If you want to get a more in depth understanding of how REST framework fits together head on over to the tutorial...

Maybe that, or similar, could be at the beginning...?

> It would be great if there are places in the docs where the terms Serializer, Renderer, Parser gets explained

I guess I think that already happens: in the relevant sections of the API Guide. 

Maybe an overview would help though. Short of a draft it's hard to say...

**Comment by guettli** [comment]
I though about this again.

I am missing a glossary.

The parts of DRF (Parser, Serializer) do IPO (Input Processing Output).

What input do they get, and what output do they create?

**Comment by carltongibson** [comment]
OK. Lets rename this then. Hang on... Done.

So: Add a Glossary. Sounds great. 

Can I suggest you open a PR beginning that? Make sure the "Allow maintainers to Edit" flag is checked.  Add what you can. We can contribute beyond that. We can ask for input from the community too. Once it's done we can merge. 

Sound OK? 

I'm going to close this on the assumption that the PR will be enough to track this. 

Thanks for the suggestion!
