### ISSUE TITLE
Typo in Dutch translation

### ISSUE THREAD

**Issue by whyscream** [encode/django-rest-framework#5432]
There is a typo in the Dutch translation at https://github.com/encode/django-rest-framework/blob/master/rest_framework/locale/nl/LC_MESSAGES/django.po#L177

The fix:
```diff
- msgstr "Deze waarde voldoet niet aan het vereisde formaat."
+ msgstr "Deze waarde voldoet niet aan het vereiste formaat."
```

I'd submit a PR but the translations are managed at transifex?

**Comment by carltongibson** [comment]
@whyscream Thanks for the report. 

> ...the translations are managed at transifex?

That's right. [Here's the project](https://www.transifex.com/django-rest-framework-1/django-rest-framework/dashboard/) — There's a "Join Team" button you can click. We'd love to have you!

**Comment by whyscream** [comment]
@carltongibson already submitted. but maybe a bit of a hurdle for a oneline fix. Maybe @mikedingjan can fix it?

**Comment by xordoquy** [comment]
@whyscream I just added you to the team.
