### ISSUE TITLE
Raising ValidationError with a string argument raises a ValueError

### ISSUE THREAD

**Issue by MadWombat** [encode/django-rest-framework#5438]
## Checklist

- [ ✓] I have verified that that issue exists against the `master` branch of Django REST framework.
- [ ✓] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [✓ ] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [✓ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [ ✓] I have reduced the issue to the simplest possible case.
- [ ✓] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
```
from rest_framework import serializers

class CustomSerializer(serializers.Serializer):
    f1 = serializers.IntegerField()
    f2 = serializers.CharField()

    def to_internal_value(self, data):
        raise serializers.ValidationError('Never Valid!')


s = CustomSerializer(data={'f1': 1, 'f2': 2})
if not s.is_valid():
    print(s.errors)
```
## Expected behavior

Get the validation errors dict

## Actual behavior
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/bug_report.py in <module>()
     11 s = CustomSerializer(data={'f1': 1, 'f2': 2})
     12 if not s.is_valid():
---> 13     print(s.errors)

/usr/local/lib/python3.6/site-packages/rest_framework/serializers.py in errors(self)
    543             detail = ErrorDetail('No data provided', code='null')
    544             ret = {api_settings.NON_FIELD_ERRORS_KEY: [detail]}
--> 545         return ReturnDict(ret, serializer=self)
    546 
    547 

/usr/local/lib/python3.6/site-packages/rest_framework/utils/serializer_helpers.py in __init__(self, *args, **kwargs)
     19     def __init__(self, *args, **kwargs):
     20         self.serializer = kwargs.pop('serializer')
---> 21         super(ReturnDict, self).__init__(*args, **kwargs)
     22 
     23     def copy(self):

ValueError: too many values to unpack (expected 2)
```

Technically, the docs do say (http://www.django-rest-framework.org/api-guide/serializers/#advanced-serializer-usage)

> If any of the validation fails, then the method should raise a serializers.ValidationError(errors). 
> Typically the errors argument here will be a dictionary mapping field names to error messages.

but at the same time in another place a string is passed into the exception in the docs (http://www.django-rest-framework.org/api-guide/exceptions/#validationerror)

> The detail argument may be a list or dictionary of error details, and may also be a nested data structure. By convention you should import the serializers module and use a fully qualified ValidationError style, in order to differentiate it from Django's built-in validation error. For example. raise serializers.ValidationError('This field must be an integer value.')

The exception above happens when serializer is trying to build an OrderedDict from a list of one error. Either ValidationError needs to do a better type coercion (it converts details argument to a list, but it expects a dict or a list with keys and values) or it should not allow string literal as details.

**Comment by rpkilby** [comment]
Hi @MadWombat. Object-level validation errors should be raised in the `validate()` method, not `to_internal_value()`. See: http://www.django-rest-framework.org/api-guide/serializers/#object-level-validation

**Comment by MadWombat** [comment]
The documentation explicitly says to use `ValidationError` in `to_internal_value()`

http://www.django-rest-framework.org/api-guide/serializers/#to_internal_valueself-data

**Comment by xordoquy** [comment]
The `ValidationError` creation with a string will only work with root serializer's fields.
You can not do that at the top level serializer because there are some expectations:

    class SubSerializer(serializers.Serializer):
        a = CustomSerializer()

    s2 = SubSerializer(data={'a': {'f1': 1, 'f2': 2}})
    if not s2.is_valid():
        print(s2.errors)

    >>> {'a': ['Never Valid!']}

**Comment by MadWombat** [comment]
Well, at the very least some sort of update to the docs is in order. 

But this seems like a weird piece logic. The same exception class used in the same way in the same method works fine in one serializer, but not in another. If ValidationError expects a dictionary, then it should raise an error if you pass a string. And if it accepts a string, it should accept it no matter where it happens. Encapsulation principle and all that.

**Comment by xordoquy** [comment]
The logic is totally valid. You can raise a a `ValidationError` with a string as long as it's somewhere in the serializer's field - even if that field is itself a serializer.

And despite inheriting from a `Field`, the top level serializer isn't a field as it's the root serializer.

It doesn't make sense in the root serializer to raise a flat string as the all validation expects it to be a dict.

I though it's reasonable to add a word in the doc saying that the ValidationError can get a string anywhere except in the root serializer.

**Comment by MadWombat** [comment]
As I said, you are breaking the encapsulation. A class should not care who and where is instantiating it. And this is causing problems in using the class, in this case ValidationError, because knowing its API is not enough, you have to be aware of rules of where and how it should be instantiated.

In my example, the usage makes perfect sense to me. Somebody passes bad data to the serializer, so to_internal_object() cannot complete and get or create the object, so it needs to raise a validation error with the error message. I used it in exactly the same way in other validation methods and the docs tell me that I should use it here. Yet it doesn't work.

**Comment by rpkilby** [comment]
Hi @MadWombat - I've opened #5466 to clarify the docs.

**Comment by MadWombat** [comment]
Thanks. I still think this is breaking the OOP principles. A class should not care where or under what circumstances it is being instantiated. Either ValidationError should not accept string argument or the results should be handled appropriately. If you have to specify in the docs "class X can only be called with arguments Y when you are doing Z" it is a sign of a bad design.

**Comment by rpkilby** [comment]
`ValidationError`s don't actually have any magical behavior here - it's the Serializer that catches the exception and provides the appropriate handling. For example, both of the following methods raise an identical exception, while having completely different results.

```python
def validate(...):
    raise ValidationError('foo')

def validate_some_field(...):
    raise ValidationError('foo')
```

The difference to the above methods is that `to_internal_value()` does not receive any special validation handling. The same also applies to raising a `ValidationError` in the `__init__()` or any other non-validation method.

**Comment by 0xankit** [comment]
if you pass validation error like this it should work. 
def to_internal_value(self, data):
        raise serializers.ValidationError({"key": 'Never Valid!'})

**Comment by nearcliff** [comment]
@0xankit https://clich-gavin.github.io/withering/
