### ISSUE TITLE
example site for the built-in docs of v3.6?

### ISSUE THREAD

**Issue by michaelsbradleyjr** [encode/django-rest-framework#5439]
The website [restframework.herokuapp.com](http://restframework.herokuapp.com/), linked from the main page of this project's website, is a great example of the framework's browseable API feature, but it's using an older version of the framework (v3.1) and doesn't show off the built-in docs feature that [arrived with v3.6](http://www.django-rest-framework.org/topics/3.6-announcement/).

Are there any public live examples of the built-in docs?  I would really like to be able to point manager-types to a live example/s, preferably associated with an established business' published API/s.

**Comment by carltongibson** [comment]
Duplicate of #5074. (We'll update it for 3.7)

**Comment by michaelsbradleyjr** [comment]
Still not updated.
