### ISSUE TITLE
REST framework's Request class extends the standard HttpRequest

### ISSUE THREAD

**Issue by dilyanpalauzov** [encode/django-rest-framework#5446]
http://www.django-rest-framework.org/api-guide/requests/ states 
  REST framework's Request class extends the standard HttpRequest, adding support for REST framework's flexible request parsing and request authentication.

Extend means inherits from,s o all methods of the base class, like get_full_path exist in the derived class.  This is not the case with rest_framework.Request, we have a composition.

Write at http://www.django-rest-framework.org/api-guide/requests/#request-parsing that the access to the underlying HttpRequest object is available over Request._request .

**Comment by tomchristie** [comment]
We do provide access to the underlying API. Ie. https://github.com/encode/django-rest-framework/blob/master/rest_framework/request.py#L375 (Yes, we're doing that using composition rather than inheritance, but that's an implementation detail)

**Comment by dilyanpalauzov** [comment]
As I don't know the methods of all classes, I oftern do `dir(object)` and `dir(rest_framework.request.Request-object)` does not print `get_full_path`, so I need a lot of time to come to the idea to call `rest_framework.request.Request-object.get_full_path().`

I can also imagine, that writing type hints for a function that accepts either django.http.HttpRequest or rest_framework.request.Request cannot be written as: `def x(r: django.http.HttpRequest)` as the call with rest_framework.response.Request parameter would not work.  One has to write `def x(r: typing.Union[django.httpRequest, rest_framework.request.Request])`.


So this is not just an implementation detail, but a matter that there is no inheritance and the documentation is misleading in this regard.

**Comment by rpkilby** [comment]
There is a section on composition, although it might be helpful to make it more prominent.

http://www.django-rest-framework.org/api-guide/requests/#standard-httprequest-attributes

**Comment by xordoquy** [comment]
> I can also imagine, that writing type hints for a function that accepts either django.http.HttpRequest or rest_framework.request.Request cannot be written as: def x(r: django.http.HttpRequest)

This is unlikely you'll have to use either the DRF request and the Django request in the same view unless you're specifically looking for troubles.
Even so you'd be able to use the Django request instead.

**Comment by tomchristie** [comment]
> There is a section on composition

@rpkilby - Good call, yes. As far as I'm concerned we've already addressed this issue in the docs.
