### ISSUE TITLE
Location on newly created objects

### ISSUE THREAD

**Issue by dilyanpalauzov** [encode/django-rest-framework#5447]
When a new object is created with POST in a ViewSet,  send the location of the former.

```diff
diff --git a/rest_framework/mixins.py b/rest_framework/mixins.py
--- a/rest_framework/mixins.py
+++ b/rest_framework/mixins.py
@@ -20,6 +20,8 @@ class CreateModelMixin(object):
         serializer.is_valid(raise_exception=True)
         self.perform_create(serializer)
         headers = self.get_success_headers(serializer.data)
+        if 'Location' not in headers:
+            headers['Location'] = request._request.get_full_path() + str(getattr(serializer.instance, self.lookup_field)) + '/'
         return Response(serializer.data, status=status.HTTP_201_CREATED, headers=headers)
 
     def perform_create(self, serializer)
```

**Comment by tomchristie** [comment]
We already handle this.

https://github.com/encode/django-rest-framework/blob/master/rest_framework/mixins.py#L28

**Comment by dilyanpalauzov** [comment]
https://github.com/encode/django-rest-framework/blob/master/rest_framework/mixins.py#L28 mentions URL_FIELD_NAME and http://www.django-rest-framework.org/api-guide/settings/#url_field_name  says "A string representing the key that should be used for the URL fields generated by HyperlinkedModelSerializer."

I am not talking about HyperlinkedModelSerializer, but for any ModelSerializer.

The existing code tries to retrieve for each model api_settings.URL_FIELD_NAME, it shall instead retrieve the lookup_field and add a terminating '/'.
