### ISSUE TITLE
Honour Prefer: return=minimal

### ISSUE THREAD

**Issue by dilyanpalauzov** [encode/django-rest-framework#5450]
A minimal implementation for `RFC 7240: Header Prefer: return=minimal`.

When an object is created or updated, the client might not be interested to receive the changed object, as the client might be aware of its new state,  Instead the client just wants to be sure that the object was changed.

```diff
diff --git a/rest_framework/renderers.py b/rest_framework/renderers.py
--- a/rest_framework/renderers.py
+++ b/rest_framework/renderers.py
@@ -99,6 +99,10 @@ class JSONRenderer(BaseRenderer):
         else:
             separators = INDENT_SEPARATORS
 
+        if renderer_context.get('request'):
+            if 'return=minimal' in renderer_context['request'].META.get('HTTP_PREFER',''):
+               return {}
+
         ret = json.dumps(
             data, cls=self.encoder_class,
             indent=indent, ensure_ascii=self.ensure_ascii,

```

**Comment by carltongibson** [comment]
I'd expect this kind of behaviour in the view.

```
if 'return=minimal' self.request.META.get('HTTP_PREFER',''):
   return Response({}, status_code=...)
```

This is something we'd expect you to handle in user-land code rather than in the framework itself. (You could easily create a mixin to encapsulate this behaviour; see `mixins.py` for the provided examples.)

**Comment by dilyanpalauzov** [comment]
While this can of course be handled by the users of DRF, is there any reason for not implementing this part of RFC7240 in DRF?

**Comment by carltongibson** [comment]
Yeah. Keeping the framework tight. It's a question of bandwidth and maintainability really. 

There are an endless number of features we could implement. But doing so would not be good for the framework. 

We aim for the 80%. IMO this is outside that. It's an easy user-land fix, so I recommend that to you. If RFC7240 becomes the next **must have** we may reconsider.

**Comment by tomchristie** [comment]
Also, while it may have an RFC its certainly far from being widely used.

**Comment by dilyanpalauzov** [comment]
Avoiding unnecessary traffic is a feature DRF shall not only support, but also encourage.  Nobody has interest that developers don't come to the idea to avoid unnecessary traffic, because they are not hinted of the possibility to do so.  If developers were aware of this, I can imagine they would massively avoid unnecessary traffic.

RFC 7240 is new and therefore not widely known.

**Comment by rpkilby** [comment]
Hi @dilyanpalauzov, the recommended path forward is to create a 3rd party extension that implements the RFC. A complete, external implementation will make it possible to determine whether or not the additional complexity is worth adding it to the framework.
