### ISSUE TITLE
CSP issue: Bootstrap docs theme relies on external Google Font

### ISSUE THREAD

**Issue by robvdl** [encode/django-rest-framework#5461]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

You just need a simple app with the docs enabled to reproduce this, e.g.

```python
from rest_framework.documentation import include_docs_urls

urlpatterns = [
    url(r'docs/', include_docs_urls(title='My API')),
]
```

Then go to docs/ url in the browser.

## Expected behavior

I would prefer it loaded static files, css and fonts from the same domain only.

## Actual behavior

The file bootstrap-theme.min.css is loading an external font from Google which is not always desirable for ultra secure systems locked down by CSP rules, I would prefer all static files come from my own domain only.

In django-rest-framework/rest_framework/static/rest_framework/docs/css/bootstrap-theme.min.css it has this line at the top:

```css
@import url("https://fonts.googleapis.com/css?family=Roboto:400,500,700");/*!
```

Can we change this either to another font, OR server the same font locally if Googles license permits it?

**Comment by robvdl** [comment]
My current solution I have to add these to allow google fonts to load, but I would prefer not to have to do this if possible:

```python
CSP_STYLE_SRC = ("'self'", 'fonts.googleapis.com')
CSP_FONT_SRC = ("'self'", 'fonts.gstatic.com')
```

**Comment by tomchristie** [comment]
> I would prefer it loaded static files, css and fonts from the same domain only.

Yup, I'd be in favor of that.
Pull requests from anyone welcome on this.

**Comment by carltongibson** [comment]
This would require a custom bootstrap build. I know we don't update bootstrap often but it'd be an extra thing to keep in sync. 

This can be resolved at the project level just by putting said custom build in a project level `static` folder under `rest_framework/docs/css/bootstrap-theme.min.css` and setting `STATICFILES_FINDERS` to look there first. (This is the default Django behaviour if you define `STATICFILES_DIRS`.)

**Comment by carltongibson** [comment]
I'm going to close this. If a PR comes in, we can look at it then. Otherwise I suggest the project level workaround.
