### ISSUE TITLE
model serialiser not respecting validators specified in extra_kwargs

### ISSUE THREAD

**Issue by royalpranjal** [encode/django-rest-framework#5475]
This is my **serializer.py**
```
class CostSerializer(serializers.ModelSerializer):
    def validate(self, attrs):
        # do some validations on initial_data
        return self.initial_data
    
   class Meta:
        model = Cost
        fields = ['name']
        extra_kwargs = {'name': {'validators': []}}
```

This is my **models.py**
```
class Cost(models.Model):
    name = models.CharField(max_length=255)
```

Why is the model serialiser not respecting the validators (empty validation)  which I specified in  `extra_kwargs` ?

**Comment by tomchristie** [comment]
`extra_kwargs: {'name': 'validators': []}` means you'll override any `validators=...` argument that's present on the model. You won't be overriding any other arguments that are present (eg. max_length.)

If you want a field without any validation at all I'd suggest including the field explicitly on the serializer instead, eg....

    name = serializers.CharField(...)

**Comment by royalpranjal** [comment]
Thanx mate. That works
