### ISSUE TITLE
Interact form always send boolean field with false value

### ISSUE THREAD

**Issue by judgerain** [encode/django-rest-framework#5477]
## Checklist

- [ ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
In the Built-in API documentation, while using the "Interact" forms, boolean field always use false value in request.
## Expected behavior
It should send value depending from checkbox state.

## Actual behavior
![bool_false](https://user-images.githubusercontent.com/10948969/31171987-81dd9280-a90a-11e7-9e77-9c4d949e41e0.png)

**Comment by levidyrek** [comment]
I will take this one.
