### ISSUE TITLE
Views not included (replaced) in schema under certain conditions

### ISSUE THREAD

**Issue by mlubimow** [encode/django-rest-framework#5484]
## Checklist

- [X] I have verified that that issue exists against the `master` branch of Django REST framework.
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [X] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [X] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

If someone is having his patterns like this:

```
patterns = [
    url(r'^test/objects/', ExampleListView.as_view()),
    url(r'^test/(?P<pk>\d+)/objects/', ExampleListView.as_view()),
]
```
or

```
patterns = [
    url(r'^test/(?P<slug>\w+)/', ExampleDetailView.as_view()),
    url(r'^test/(?P<pk>\d+)/', ExampleDetailView.as_view()),
]
```

Schema generated by the SchemaGenerator will be (thats for first case):

```
Document(
    url=u'',
    title='Swallowed list view',
    content={
        'test': {
            'objects': {
                'list': Link(
                    url=u'/test/{id}/objects/',
                    action=u'get',
                    fields=[
                        Field(
                            u'id',
                            required=True,
                            location='path',
                            schema=<coreschema.schemas.Integer object at 0x107798210>
                        )
                    ]
                )
            }
        }
    }
)
```

## Expected behavior

All links included in the schema.

## Actual behavior

Because of the way how links are implemented (dictionary), if there are multiple detail views, list views and possibly others, they get replaced in get_links() step in SchemaGenerator.

**Comment by carltongibson** [comment]
Yes they do. 

You’ll need to subclass SchemaGenerator and (probably best) override get_keys() to produce a dictionary structure that will match your url patterns.

**Comment by mlubimow** [comment]
@carltongibson At first glance, to get correct Document it should be enough to modify `insert_into` function from schemas/generators.py to hold values in lists and always just append to a key instead of replacing.

Next, the question is about renderers. I'm not sure if they need to be updated because I tried rendering my Document (with lists) in unit test and surprisingly it worked, both links were included in returned json. The question is only if this will be understood by swagger - I didn't check that.

**Comment by mlubimow** [comment]
@carltongibson PR with fix added :)
