### ISSUE TITLE
Major schema changes not reported in 3.7.0 changelog

### ISSUE THREAD

**Issue by mattjegan** [encode/django-rest-framework#5493]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

* Looks at [the 3.7.0 release notes](http://www.django-rest-framework.org/topics/release-notes/)
* Notice https://github.com/encode/django-rest-framework/pull/5354 is not referenced anywhere.

## Expected behavior

Ideally, there would be an entry noting a breaking change on something like `SchemaGenerator().get_serializer_fields(...)` since it is now a part of `AutoSchema`. For my use case I went from:

```python
generator = SchemaGenerator()
return generator.get_serializer_fields('/', 'POST', view)
```

to 

```python
generator = AutoSchema()
generator.view = view
return generator.get_serializer_fields('/', 'POST')
```

however I needed to go through the issue tracker and recent PRs to find that this was the solution.

## Actual behavior

The changelog should have a correct reference to the breaking change and the solution to fix it.

**Also, thanks for the awesome work you guys do!** 😄

**Comment by carltongibson** [comment]
Hmmm yes. It’s in the release announcement, but this is a an oversight. 

I obviously forgot that bit. 

I’d take a PR here. 👍🏽

And, you’re welcome.

**Comment by mattjegan** [comment]
No worries, I'll make a PR when I get a chance, probably a couple days away.
