### ISSUE TITLE
Lists are not currently supported in HTML input.

### ISSUE THREAD

**Issue by congtoanle** [encode/django-rest-framework#5495]
I get this error when make serializers for a ManytoMany field:
![image](https://user-images.githubusercontent.com/19923843/31535090-e27eee70-b023-11e7-9570-a10d8dd8be64.png)
Please help me fix this.

**Comment by xordoquy** [comment]
Nested serializers don't work with the browsable API.
Use the json content type instead.

**Comment by krdeepak** [comment]
Same issue comes when using django postgres ArrayField. Is there any solution for it? Even changing the field to comma separated string using drf ListField does not solve this.

https://stackoverflow.com/questions/48330135/django-rest-framework-serialize-arrayfield-as-string/48344897

**Comment by rpkilby** [comment]
Hi @krdeepak - the underlying issue is that lists are not well represented by HTML form inputs. I would recommend switching over to the JSON input instead.

As to the SO article, I think if you were to inherit `CharField`, this might work. e.g., 

```python
class StringArrayField(CharField, ListField):
    ...
```

**Comment by jsinhSolanki** [comment]
@krdeepak Did you find any real solution to this?

**Comment by krdeepak** [comment]
No, I just use raw json input when needed.

**Comment by jsinhSolanki** [comment]
@krdeepak for quick response.

**Comment by malik-tillman** [comment]
Why does it work in admin?

**Comment by juan-kabbali** [comment]
This feature could be a nice enhancement for future releases.

**Comment by lalitvasoya** [comment]
> No, I just use raw json input when needed.

when i want to upload image at that time raw json could not work is there any idea about it

**Comment by chaitanya2903** [comment]
@lalitvasoya You can set the ListField parameter required = False and then make a PUT request to update the same object.

**Comment by MHM98** [comment]
I have the same issue.
can anyone help, please?

**Comment by meequz** [comment]
Everyone who seek help, you can tell DRF to show the field as a simple text input by using `style` parameter of you serializer field.
```
class MySerializer(serializers.Serializer):
     my_list_field = serializers.ListField(
          child=...,
          style={'base_template': 'input.html'},
     )
```

**Comment by Masterquiz** [comment]
This is the nice solution that worked out for me.
Suppose you want to select photos to add to an album.

`from rest_framework import serializers
 
from photos.models import Photo

class AlbumSerializer(serializers.ModelSerializer):
    
    photos = serializers.PrimaryKeyRelatedField(queryset=Photo.objects.all(), many=True)`
