### ISSUE TITLE
Translations of documentation

### ISSUE THREAD

**Issue by heaviss** [encode/django-rest-framework#5504]
Hi! Is it possible to add translations to DRF documentation?
There is an attempt to [translate docs to russian](https://github.com/ibrikin/django-rest-framework-rusdoc), I'm sure this attempt is not unique.

I tried to search about translations in contribution guide, google group, issues and documentaion, but didn't find anything. sorry if missed something.

**Comment by xordoquy** [comment]
Hi, I think it will require some changes in mkdocs.
I'd also like to see translation happening although it'll require some work on top of translation work itself.

**Comment by heaviss** [comment]
Excellent! I want to help with russian translation.
I'd also like to help with changes in mkdocs, but I have almost no experience with real projects. If someone will help, I'm ready.

**Comment by carltongibson** [comment]
Best place to start is this issue for an enhancement on the MkDocs repo I think. https://github.com/mkdocs/mkdocs/issues/617

**Comment by carltongibson** [comment]
I'm going to close this here. Until MkDocs supports i18n there's little we can do.

**Comment by xordoquy** [comment]
ack

**Comment by carltongibson** [comment]
@xordoquy I think I agree. 😃 We need a superhero with a free weekend to make something happen.

**Comment by heaviss** [comment]
@carltongibson Seems that all you have since 2015 is junior with a free weekend (me 😃).

**Comment by carltongibson** [comment]
@heaviss _Junior Hero_ it is then. 😃

If you want to look at i18n in MkDocs, that would be AMAZING!!!™. 

I don't know who's active there but I'm sure you'd get some support.
