### ISSUE TITLE
request.stream doesn't always return a stream.

### ISSUE THREAD

**Issue by Alexgmin** [encode/django-rest-framework#5517]
## Checklist

- [X] I have verified that that issue exists against the `master` branch of Django REST framework.
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [X] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [X] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
On a Custom authentication scheme, try to access the request.stream as a stream.

## Expected behavior
A stream instance is always returned

## Actual behavior
A request instance is returned if request._read_started is false and a Stream is returned when it's true.

Example:
```
def authenticate(self, request):
    foo = request.body
    bar = request.stream
    value = request.stream.getvalue()
```
This works because request.stream returns a StringIO instance.

```
def authenticate(self, request):
    # foo = request.body
    # bar = request.stream
    value = request.stream.getvalue()
```
This doesn't because request.stream returns a Request instance (WSGIRequest in my case)

Removing this [conditional](https://github.com/encode/django-rest-framework/blob/9ec81e32dae8b742c83e71a33218b4ab59ba3571/rest_framework/request.py#L271) solves the problem in this case, but i don't know what other implications it has.

**Comment by carltongibson** [comment]
@Alexgmin Fancy doing a little research into the history here? 

I seem to have vague memories of something about not being able to access the stream if it had already been read, but I can't bring it to mind exactly instantly.

**Comment by Alexgmin** [comment]
@carltongibson 
Investigating a bit, it seems that this pull https://github.com/encode/django-rest-framework/pull/4500 added the condition, related to this issue. https://github.com/encode/django-rest-framework/issues/3951
So yeah, you can only access the stream once,

**Comment by carltongibson** [comment]
@Alexgmin OK. That was it yes. 

This may just be something you'll have to work around. 

The discussion on #3951 suggests we fallback to using the request is if the steam is already exhausted. Looking now, I can't see exactly where that `Request` type return is employed. Given the discussion I suspect we are but, if we were **not** using that then **maybe** we could adjust the return here, to e.g. `None` or such. 

I think I'm going to close this as is. I'm not sure there's anything obviously actionable for us. 

If you want to dig into it more I'm **very happy** to review concrete suggestions.
