### ISSUE TITLE
Documentation fails when using detail_route with 'options' method

### ISSUE THREAD

**Issue by amitripshtos** [encode/django-rest-framework#5528]
## Checklist

- [X] I have verified that that issue exists against the `master` branch of Django REST framework.
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [X] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [X] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

Hello, thanks for this awesome piece of software!
The issue is the following:
When using detail_route in ModelViewSet and using "options" method , the documentation page fails with an exception.

## Steps to reproduce
1. Create a project with ModelViewSet
2. Add this method in the class

```
@detail_route(methods=['options', 'get', 'put'])
def test(self, request, *args, **kwargs):
  pass
```

3. Check that the documentation is not working

## Expected behavior
The documentation should work using the "options" method

## Actual behavior
The documentation page is crashing with exception
KeyError: 'options'

Thanks for the help!
Amit.

**Comment by carltongibson** [comment]
@amitripshtos Thanks for the report. Addressed in #5532
