### ISSUE TITLE
Add rounding parameter to DecimalField

### ISSUE THREAD

**Issue by merwok** [encode/django-rest-framework#5531]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

- Have a decimal field named score with decimal_places=1
- Serialize an objet with a score attribute that has a value of Decimal('7.25')

## Expected behavior

Output shows 7.3

## Actual behavior

Output shows 7.2.

The behaviour does not match human expectations and DecimalField does not accept a rounding parameter (for the Decimal.quantize method).

It seems overkill to install something like django-rest-framework-braces to work around one missing param in the API.

**Comment by rpkilby** [comment]
I think this is a sensible addition, given that `quantize()` only has two arguments (in addition to the context). 

For now, you *should* be able to control rounding by altering the global decimal context. It's not ideal, but it should work.

**Comment by trangttt** [comment]
Hi, I made a tentative implementation. Hope it works. One of my very first PR. :)

**Comment by merwok** [comment]
Thanks to all involved!
