### ISSUE TITLE
schema data type model

### ISSUE THREAD

**Issue by gfrancqu** [encode/django-rest-framework#5536]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [ ] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

I'm facing issue to generate a proper api schema with nice data models definitions. Generating client code from my api schema result in models respectively named data, data1, data2, data3

## Steps to reproduce
I just installed django_rest_auth and add some custom serializer and settings to enable email login, I also use django_rest_swagger to generate the schema. But I can't find a way to obtain definitions of objects model (in drf or drf_swagger), looking at the code make me think that this is just not implemented

## Expected behavior
![exepected_ehavior](https://user-images.githubusercontent.com/11816129/32046447-616804b4-ba43-11e7-982c-bb9bf89fd3ff.png)
this come from the swagger-editor pet store sample

## Actual behavior
![actual_behavior](https://user-images.githubusercontent.com/11816129/32046441-59c63c3a-ba43-11e7-9d48-2e4946474a3b.png)

any help about how to perform this (if a missed something in code or documentation) is welcome

**Comment by carltongibson** [comment]
Hi @gfrancqu. 

There's not an addressable issue here I'm afraid. It's not clear this is about Django REST Framework or `django_rest_swagger` or `drf_swagger`. (Maybe these are the same thing...)

Django REST Framework's schema generation (essentially) uses the serialiser to populate the the Core API schema. There are renderers that will map from that to OpenAPI. 

I suggest you have a look at https://github.com/limdauto/drf_openapi too. 

You're best bet if you need help here is probably StackOverflow. (I'm afraid we can't handle usage questions on the Issue Tracker here.) 

If we can pin down a concrete issue with Django REST Framework I'm happy to take a look. 

Good luck
