### ISSUE TITLE
Proposal for changing GitHub Repository Description

### ISSUE THREAD

**Issue by bholagabbar** [encode/django-rest-framework#5540]
The current repository's name is 'Web APIs for Django' which is far too vague and doesn't quite convey how powerful DRF is and the fact that it's the most popular, recommended framework for building REST APIs in Django. Even https://github.com/encode/apistar has the description *A smart Web API framework, designed for Python 3*

I propose to change it to something like ` Powerful, flexible toolkit for building REST APIs in Django` (which is taken off the website description) or something on those lines. What do you guys think?

**Comment by tomchristie** [comment]
I quite like that we've got a simple no-nonsense description at the moment. Happy to take other's opinions on this, but I'll leave it as it is unless there's some consensus.

**Comment by bholagabbar** [comment]
@tomchristie Well it seems though we're not going to have a consensus when you've closed the issue :)

**Comment by tomchristie** [comment]
Despite the close am still happy to see conversation either here or on the discussion group, but don’t particularly consider it as an open issue.
