### ISSUE TITLE
Unhanded exception is wsgiref (py3) caused from CreateModelMixin

### ISSUE THREAD

**Issue by canni** [encode/django-rest-framework#5541]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test

## Steps to reproduce
- python3.x (reporduceable on 3.4 - 3.6)
- Install django 2.0beta & latest DRF
- Create simple model
- Create simple HyperlinkedModelSerializer that uses 'url' field instead of 'id'
- Create simple viewset
- run standard django runserver (wsgiref)
- POST new model

## Expected behavior

- model gets created without any issues

## Actual behavior

- models is created but:
- Exception is raised by wsgiref from here https://github.com/python/cpython/blob/3.6/Lib/wsgiref/headers.py#L43

The issue is that header is of type `Hyperlink`, and wsgiref explicitly checks for `str` only
It's caused here: https://github.com/encode/django-rest-framework/blob/master/rest_framework/mixins.py#L30
The data is not a `str`

**Comment by carltongibson** [comment]
@canni Thanks for the report. Any chance you could post a minimal test project so we can quickly reproduce this? 

Can you also post the full traceback so we can see that? `get_success_headers` is meant to return a `dict` so the problem isn't there exactly. 

Our test suite is [passing again Django `master`](https://travis-ci.org/encode/django-rest-framework/jobs/294611809) — so we must be missing a test somewhere.

The reproduce steps seem simple enough. This must be new: what changed and where? (Is this even our bug...?)

**Comment by tomchristie** [comment]
> so we must be missing a test somewhere

The wsgiref tests are just more particular about WSGI conformance.
Unlikely that this is actually causing any issues with server implementations, since we've not had it raised in any other context, but we could wrap that expression with `str(...)` for completeness.

**Comment by canni** [comment]
This test fails with django 2.0 beta, but works with 1.x

```python
# tests/test_wsgiref.py

from threading import Thread
from wsgiref.simple_server import make_server

import requests
from django.db import models
from django.test import SimpleTestCase, override_settings
from django.core.servers.basehttp import get_internal_wsgi_application

from rest_framework import serializers, viewsets
from rest_framework.routers import SimpleRouter


class WsgirefTestModel(models.Model):
    text = models.CharField(max_length=200)


class NoteSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = WsgirefTestModel
        fields = ('url', 'text')


class NoteViewSet(viewsets.ModelViewSet):
    queryset = WsgirefTestModel.objects.all()
    serializer_class = NoteSerializer


notes_router = SimpleRouter()
notes_router.register(r'notes', NoteViewSet)

urlpatterns = notes_router.urls


@override_settings(ROOT_URLCONF='tests.test_wsgiref', ALLOWED_HOSTS=['*'])
class TestHeaderHandlingWithHuperlinkedSerilizer(SimpleTestCase):
    def setUp(self):
        self.httpd = make_server('', 0, get_internal_wsgi_application())
        self.addr = self.httpd.server_address
        self.thread = Thread(target=self.httpd.serve_forever)
        self.thread.start()

    def tearDown(self):
        self.httpd.shutdown()
        self.thread.join()

    def test_no_header_error_in_wsgiref(self):
        response = requests.post('http://%s:%d/notes/' % self.addr, json={'text': 'test_text'})

        assert response.status_code == 201
        assert response.headers['Location'] == 'http://%s:%d/notes/1/' % self.addr
```

**Comment by canni** [comment]
@tomchristie don't you want to include a regression test for this? And probably we should try to identify if there's no more other headers passed not as plain strings? :)
