### ISSUE TITLE
DEFAULT_PAGINATION_CLASS=None by default breaks pagination in ModelViewSets

### ISSUE THREAD

**Issue by frishberg** [encode/django-rest-framework#5554]
I am working on an API that uses the django-rest-framework. We use ModelViewSets to present our results. Using `PAGE_SIZE` in our settings.py allowed us to paginate the results. However, recently this pagination stopped working. In our project's requirements, we had pinned `djangorestframework~=3.6`; a redeployment of our app recently picked up version 3.7, which incorporated the change from https://github.com/encode/django-rest-framework/commit/107e8b3d23a933b8cdc1f14045d7d42742be53a9.

As a workaround, we are setting `DEFAULT_PAGINATION_CLASS` in our settings.py. (We could, of course, also have pinned our minor version exactly.) However, the [documentation](http://www.django-rest-framework.org/api-guide/pagination/) states that "Pagination is only performed automatically if you're using the generic views or viewsets." I believe this is out of date.

## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [ ] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
* Extend ModelViewSet and direct a view to it per API instructions
* Set PAGE_SIZE to 20 in settings.py
* Observe that there is no pagination
## Expected behavior
* PAGE_SIZE should work for any ViewSet which extends the generic viewsets.
## Actual behavior
* PAGE_SIZE is ignored unless DEFAULT_PAGINATION_CLASS is set explicitly.

**Comment by carltongibson** [comment]
This was an intended change. Either set `DEFAULT_PAGINATION_CLASS` explicitly or define `pagination_class` on your view. Either will work.

**Comment by frishberg** [comment]
Two questions:

- Are API-breaking changes intended in minor version changes? If so, we'll be sure to pin exact versions from now on.
- Would you accept a pull request fixing the documentation?

**Comment by carltongibson** [comment]
It’s not so much a breaking change as a clarification of an ambiguous behaviour. (All fixes are breaking changes if you’re relying on the broke behaviour.)

You should always pin to exact versions. 

We’ll always happily look at PRs improving the docs! 🙂
