### ISSUE TITLE
The tutorial is terrible

### ISSUE THREAD

**Issue by yangnw** [encode/django-rest-framework#5558]
## Steps to reproduce
Visit http://www.django-rest-framework.org/tutorial/1-serialization/.

## Expected behavior
The tutorial should present some most common use scenarios, beyond the simplest one.

## Actual behavior
It's pretty much the same material as the quickstart.

**Comment by yangnw** [comment]
[This blog post][http://blog.josephmisiti.com/customzing-apis-with-django-rest-framework], for example, is something I'd like to see in the tutorial.

**Comment by carltongibson** [comment]
Hmmm. The tutorial is in general highly thought of. 

The idea is that you use the main docs beyond the tutorial. 

Thanks for the input.

**Comment by yangnw** [comment]
@carltongibson 
OK, may I only disliked it because I read it on Kindle.

> The idea is that you use the main docs beyond the tutorial.
In that case, there should be pointers to appropriate API guides for the most common scenarios, possibly at the end of the tutorial (like in Apple's docs).

**Comment by xordoquy** [comment]
The tutorial is about Django REST framework, not about how to build a RESTful API. That would be the material for a book out of the scope of the documentation.
Documentation has a comprehensive layout that covers every part of Django REST framework.

Do you have any example to showcase the pointers you are referring to ?

**Comment by yangnw** [comment]
@xordoquy They point to sections within the API Guide of DRF itself, not to an external source.

A parallel example would be [Core Data Programming Guide - Fetching Objects](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/CoreData/FetchingObjects.html), at the end of the section you see a link to documentation of NSFetchRequest.

**Comment by xordoquy** [comment]
could be considered although I'd argue someone starting the tutorial should finish it first otherwise it'll try to get something more advanced than it is.

**Comment by yangnw** [comment]
@xordoquy The links make it more self-contained. Anyways, your call, I'll change the issue title.
