### ISSUE TITLE
Core API docs - Post parameter form

### ISSUE THREAD

**Issue by BenjaVR** [encode/django-rest-framework#5570]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

Create a simple model, serializer and view
```py
# views.py
class UserView(ApiView):
    def post(request):
        serializer = UserSerializerCreate(data=request.data, context={'request': request})
        # ... save and return Response ...
```
```py
# serializers.py
class CreateUserSerializer(ModelSerializer):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'password')
```

## Expected behavior
Something like this, with all post parameters:
![1](https://i.imgur.com/uth2NIa.png)

## Actual behavior
Nothing to interact with...
![2](https://i.imgur.com/m9oH4R0.png)

**Comment by carltongibson** [comment]
You either need to:

* Subclass `GenericAPIView`, which exposes `get_serializer`, which in-turn allows introspection of serialiser fields.
* Pass `manual_fields` to `AutoSchema`, or else subclass `AutoSchema` to have awareness of your serialiser class. See docs on [Per-view Schema Customisation](http://www.django-rest-framework.org/api-guide/schemas/#per-view-schema-customisation)

I'd point you towards the first option to begin. (Just from the code example I'd guess you don't need to be using `APIView` directly for your use-case.) 

In general, the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
