### ISSUE TITLE
SSL and DRF auto-doc(interactive API documentation). Cross ssl call problem

### ISSUE THREAD

**Issue by alex1vanchik** [encode/django-rest-framework#5571]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
1. Use DRF doc and SSL(https). 
2. Open any endpoint in the doc and send request https://monosnap.com/file/YVAVxs7MJkxsiYrS2elCaJLsvXIbPX
## Expected behavior
Don't get any response https://monosnap.com/file/YVAVxs7MJkxsiYrS2elCaJLsvXIbPX.
## Actual behavior
Must receive a response

**Comment by alex1vanchik** [comment]
Here's what the console gives, maybe it will help you https://monosnap.com/file/aukyqzfWg4LANIp0xaQgnnTkDQigFR

**Comment by carltongibson** [comment]
@alex1vanchik You're going to need to provide more details here, or a reproduce... What was the requested resource you've obscured? Where did that come from? 

I'd guess you're [settings](https://docs.djangoproject.com/en/1.8/ref/settings/#secure-proxy-ssl-header) might not be correct. 

I'm going to close this. I'm happy to re-open if you can give us more to go on.

**Comment by alex1vanchik** [comment]
When you request any resource, you will get this error. If I use the swagger all is ok or use resource doc. Example https://monosnap.com/file/8BSCjWDJhdzP1JnTNEaeTLm5gy2dmc. I don't think that this is a configuration problem. Just check how your documentation works with ssl

**Comment by carltongibson** [comment]
> Just check how your documentation works with ssl.

Yes. Working fine. So there's something else going on in your set-up. 

There isn't enough from the information provided here to know what. 

It's most probably a config error on your end. 

Happy to look at an issue if you can help us identify one. (But you need to provide more info)

**Comment by alex1vanchik** [comment]
@carltongibson I understand you, I just wanted to make sure that everything on your side is ok. I'll find out what the problem is and I will leave here recommendations for the rest. Thanks you

**Comment by alex1vanchik** [comment]
The problem is fixed. @carltongibson was absolutely right. Need to set up [settings](https://docs.djangoproject.com/en/1.8/ref/settings/#secure-proxy-ssl-header)
