### ISSUE TITLE
ImportError: cannot import name RequestsClient

### ISSUE THREAD

**Issue by weasteam** [encode/django-rest-framework#5575]
When I am looking at this documentation: http://www.django-rest-framework.org/api-guide/testing/, I have no idea on how to import `RequestsClient`. 

I tried many methods, all failed.  Any idea on how to make it work?

```
>>> from rest_framework.test import RequestsClient
Traceback (most recent call last):
  File "<console>", line 1, in <module>
ImportError: cannot import name RequestsClient
```

**Comment by xordoquy** [comment]
Make sure you have a recent enough version:

    >>> from rest_framework.test import RequestsClient
    >>>
