### ISSUE TITLE
why dry handle datetime so violence?

### ISSUE THREAD

**Issue by callnothing** [encode/django-rest-framework#5580]
https://github.com/encode/django-rest-framework/blob/0f33e63e10f23b9af243480a0eb002be3e98159b/rest_framework/fields.py#L1177

if i set USE_TZ False, drf save datetime string like "2017-11-12T06:00:45.898Z" as "2017-11-12T06:00:45.898000".

**Comment by callnothing** [comment]
hack drf by this code
`
def default_timezone(self):
    return timezone.get_default_timezone()

DateTimeField.default_timezone = default_timezone
`

**Comment by rpkilby** [comment]
Hi @callnothing, I'm closing this as there isn't anything that is clearly actionable.

**Comment by xordoquy** [comment]
@callnothing there's no reason to use timezone whenever USE_TZ is false.
