### ISSUE TITLE
DRF 3.6.4/3.7.0 breaks reading request.POST if request.body was read

### ISSUE THREAD

**Issue by D3X** [encode/django-rest-framework#5582]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
- Create any DRF view
- Add a middleware or a signal handler that uses `request.POST`

## Expected behavior
- `request.POST` works fine

## Actual behavior
- `AttributeError` is raised by Django's `HttpRequest._load_post_or_files`

----

The reason the exception is raised is because Django's `WSGIReqeust.POST` checks `if hasattr(self, '_post')` (which it doesn't have) and proceeds to `_load_post_and_data`, which in turn calls `parse_file_upload` which tries to set `self.upload_handlers`, but the `upload_handler.setter` checks `if hasattr(self, '_files')`. At this point, `_files` has already been [set by DRF](https://github.com/encode/django-rest-framework/blob/master/rest_framework/request.py#L255) (to make closing file handles possible), so it raises an exception.

I think the solution to this is to set `request._post` in addition to `request._files` to preserve the interface. I am not sure if there's an easy way to set it to the original `POST` as it seems DRF only calls `_load_data_and_files`, which deserializes the data etc.

----

edited for formatting (@rpkilby)

**Comment by rpkilby** [comment]
For context, this was changed in #5262, which superseded #5255. Amusingly enough, the original PR did set `_post` in addition to `_files`. 

@D3X - would you be able to reduce this into a failing test case?

**Comment by D3X** [comment]
@rpkilby Thanks for

**Comment by D3X** [comment]
@rpkilby I played with it a bit and it seems it only breaks if `request.body` was read before DRF did its magic.

Also have added a failing test PR, as you can see above.

**Comment by xordoquy** [comment]
This doesn't look very knew to me. Did you had that issue in prior versions ?

**Comment by D3X** [comment]
@xordoquy No. I bumped into it today, while trying to update my project's dependencies, including updating DRF from 3.6.3 to 3.6.4 (can't go to 3.7 yet). It has worked fine before that.
