### ISSUE TITLE
The test APIClient's .credentials() method should have a better name

### ISSUE THREAD

**Issue by mikeengland** [encode/django-rest-framework#5585]
## Expected behavior
I belive the APIClient would be more user friendly if the .credentials() method was called .headers() or something similar.

Calling the method .credentials() when it sets headers can be confusing. For example, I wanted to add a HTTP_ACCEPT header to the request, and did not realise credentials() would allow that. I assumed it would just be for auth-related setup.

## Actual behavior
.credentials() can also be used to set non-auth related headers.

Thanks!

**Comment by xordoquy** [comment]
Credentials should be left for authentication.
The correct way to set headers is to provide them as extra argument to get/post/whatever or during the client's instantiation as explained in the [Django documentation](https://docs.djangoproject.com/en/1.11/topics/testing/tools/#making-requests)

**Comment by mikeengland** [comment]
@xordoquy Thanks, I didn't realise you could specify them to the client on instantiation.
