### ISSUE TITLE
The AuthTokenSerializer returns the wrong message when the user's is_active is false

### ISSUE THREAD

**Issue by motatoes** [encode/django-rest-framework#5586]
## Checklist

- I have verified that that issue exists against the `master` branch of Django REST framework.
- I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- I have reduced the issue to the simplest possible case.
- I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Attempt to retrieve an access token for a user with `is_active` is false. 

## Expected behavior
The message returned by the serialiser should indicate the user account has been disabled or is inactive

## Actual behavior

    'Unable to log in with provided credentials.'

I'm using this `is_active` flag to check for whether or not the user has confirmed his email. [As I have seen in the code for the serializer, there is a note about this for Django 1.10+](https://github.com/encode/django-rest-framework/blob/master/rest_framework/authtoken/serializers.py#L24). This happens because the `authenticate` function returns `None` when `is_active` is False. I would expect the `authenticate` method to return the user object even if `is_active` is set to False as further checking can be performed manually.

Arguably this is an issue with `Django 1.10+` but the issue could be fixed using the [proxy function of DRF](https://github.com/encode/django-rest-framework/blob/master/rest_framework/compat.py#L317)

**Comment by carltongibson** [comment]
I don’t think there’s anything we can do to help you here. Authentication in Django works how it does. This isn’t something we’re going to override. 

Your best bet would be to manually fetch the user instance, do your checks and then return the user or not based on that in a custom authentication scheme. You can use the existing scheme as a guide but the protocol/interface/contract here it that authenticate returns the user if it passes or None if not.
