### ISSUE TITLE
Release note for 3.7.3 not published

### ISSUE THREAD

**Issue by browniebroke** [encode/django-rest-framework#5589]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

While upgrading, I noticed the release notes for the latest release isn't published [in the docs](http://www.django-rest-framework.org/topics/release-notes/#37x-series), although it is there [in the source](https://github.com/encode/django-rest-framework/compare/3.7.2...3.7.3).  On [RTD](http://django-rest-framework.readthedocs.io/en/latest/topics/release-notes/#37x-series), 3.7.2 is also missing.

Hopefully, that's just a minor issue, but I thought I'd notify about it in case something is broken in the build.

## Expected behavior

There should be a section for the 3.7.3 release.

## Actual behavior

Section is missing.

**Comment by carltongibson** [comment]
RTD seems to be up to date now. I assume that's just a caching issue. 

I've redeployed the main docs. 3.7.3 is now showing. I assume I just missed that in the rush to push 3.7.3. 

Thanks for the report.
