### ISSUE TITLE
JSON response: getting List of List insted of JSON data 

### ISSUE THREAD

**Issue by ramukodandapuram** [encode/django-rest-framework#5592]
Hi ,
I am getting below error 

![views1](https://user-images.githubusercontent.com/17873942/32784789-cb78fc1e-c975-11e7-885c-b85e086cea7c.png)
**Code**
`
`
from django.http import HttpResponse
from django.core.serializers import serialize
from rest_framework.views import APIView
from .models import Employee
from .serializers import EmployeeSerializers
#from sqlalchemy import create_engine
from django.db import connection 
`

vews.py

class employee_list(APIView):
	
	    
	

	def get(self,request,format =None):
		
		#engine =create_engine("mysql://root:Passw0rd@localhost/employee",echo=True)
		
		cursor = connection.cursor()  	
		cursor.callproc("Get_Usp_Employee") 
		
		employees=cursor.fetchall() 
		cursor.close() 

		return Response(employees) 

`
 **Required output** 
![required](https://user-images.githubusercontent.com/17873942/32785211-f8d04b9e-c976-11e7-8326-9399e6ce108d.png)
 I was failing to utilize the feauture of serilization, tried many ways but response was not satisfactory! pleas help me!! any help can be appreciated.

**Comment by xordoquy** [comment]
Hi,

The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
