### ISSUE TITLE
No "Location" in response header when post success with 201 code

### ISSUE THREAD

**Issue by arrownj** [encode/django-rest-framework#5595]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
1. create a normal post api, such as http://localhost:8000/api/entries/ which will add a entry to entries with post method.

2. call the post api with curl
curl -XPOST http://localhost:8000/api/entries/ -b "name=entry1" -v

## Expected behavior
these is a "Location" in response http header

## Actual behavior
no "Location" in the response header.

**Comment by carltongibson** [comment]
The `CreateModelMixin` includes logic to set the location header exactly as described: 

https://github.com/encode/django-rest-framework/blob/15024f3f07b9311887ad6f5afb366f6c032c0486/rest_framework/mixins.py#L28-L32

Any of the generic views extending `CreateModelMixin` will apply this. 

If you're creating your own views you'll either need to to use `CreateModelMixin` or implement similar logic yourself.
