### ISSUE TITLE
how to do case-insensitive ordering

### ISSUE THREAD

**Issue by sant527** [encode/django-rest-framework#5603]
how to do case-insensitive ordering. My ordering is always case sensitive

**Comment by rpkilby** [comment]
Hi @sant527 - the issue tracker is intended for bug reports & feature requests. If you're looking for [support](http://www.django-rest-framework.org/#support), I'd recommend either the IRC channel or discussion group.

That said, this [post](https://stackoverflow.com/questions/3409047/django-orm-case-insensitive-order-by) on SO seems relevant. To integrate those solutions into DRF, you would need to subclass the `OrderingFilter` and override the [`.filter_queryset()`](https://github.com/encode/django-rest-framework/blob/3.7.3/rest_framework/filters.py#L235-L241) method.
