### ISSUE TITLE
SchemaJSRenderer renders invalid Javascript 

### ISSUE THREAD

**Issue by steffann** [encode/django-rest-framework#5608]
## Steps to reproduce
Request docs/schema.js when using a Python 3 server.

## Expected behavior
Get valid Javascript looking like:

    var coreJSON = window.atob('eyJf...');

## Actual behavior
Under Py3 the base64.b64encode() method returns a binary object, which gets rendered as b'...' in schema.js. This results in the output becoming:

    var coreJSON = window.atob('b'eyJf...'');

which is invalid Javascript.

**Comment by carltongibson** [comment]
Was fixed by #5607
