### ISSUE TITLE
Wheels include .DS_Store files.

### ISSUE THREAD

**Issue by sjoerdjob** [encode/django-rest-framework#5615]
## Steps to reproduce

* Download latest wheel from PyPI (currently https://pypi.python.org/pypi/djangorestframework/3.7.3, https://pypi.python.org/packages/f5/2c/3c3c81b8ecd60952c20ccd5fc1d19c0b22731c80c75649dd2e3fef361aaf/djangorestframework-3.7.3-py2.py3-none-any.whl#md5=ee78a9aaddc972e9bf75ebaa4c0d6ff5)
* List the files in the wheel
* Search for DS_Store in the results

## Expected behavior

No hits.

## Actual behavior

```
unzip -l djangorestframework-3.7.3-py2.py3-none-any.whl | grep DS
     6148  07-01-2014 01:42   rest_framework/templates/.DS_Store
     6148  09-28-2017 10:00   rest_framework/templates/rest_framework/.DS_Store
```

**Comment by rpkilby** [comment]
I think the issue here is the use of `package_data`. Since we provide a `MANIFEST.in`, we should be able to just use `include_package_data=True`.

**Comment by carltongibson** [comment]
Incoming `Fix MANIFEST.in` commit... 😀 

Thanks for the report @sjoerdjob. We'll sort it for the next release.
