### ISSUE TITLE
November is mispelled on the 3.7.2 and 3.7.3 release notes

### ISSUE THREAD

**Issue by Alexgmin** [encode/django-rest-framework#5634]
https://github.com/encode/django-rest-framework/blob/master/docs/topics/release-notes.md#373
https://github.com/encode/django-rest-framework/blob/master/docs/topics/release-notes.md#372

I don't think novemember is the correct term.

**Comment by carltongibson** [comment]
@Alexgmin Thanks for the report. Fixed now. PRs always welcome! 🙂
