### ISSUE TITLE
Make the sidebar resizeable

### ISSUE THREAD

**Issue by googol7** [encode/django-rest-framework#5638]
The sidebar size has a width of [225px](https://github.com/encode/django-rest-framework/blob/master/rest_framework/static/rest_framework/docs/css/base.css#L39) and is not resizeable. So linebreaking / word wrapping occurs and items are broken into multiple lines which looks confusing because it looks like a section header then.

![bildschirmfoto 2017-11-30 um 16 38 18](https://user-images.githubusercontent.com/282412/33439472-caec172a-d5ed-11e7-9bc2-7fec822cac67.png)

**Comment by carltongibson** [comment]
Hey @googol7 Thanks for the report. 

Yes. I see where you're coming from here. 

> Flat is better than nested. 

🙂

I'm going to give this a "help wanted" sticker. I'd be very happy to see a PR making an improvement here.

**Comment by rtindru** [comment]
@carltongibson  @googol7 Where is the docs sidebar shown? Can you help me reproduce this please?

**Comment by googol7** [comment]
In my case I just call https://0.0.0.0:8000/docs in the browser to see it.

**Comment by Beastjdhr** [comment]
Hey! I'd like to collaborate to this project. Can I take the issue?

**Comment by carltongibson** [comment]
@Beastjdhr Yes! Great. Please go ahead.

**Comment by avinasha39** [comment]
Hi I will like to contribute, if its not already solved,

and do we have a fixed size for sidebar or it should take up space according to text.

**Comment by sabya14** [comment]
Hi, I am actively looking to start contributing to open source, please let me know if i can submit a PR.
Thanks

**Comment by tomquinonero** [comment]
Hi, I am right now at the djangocon eu sprints and will try to tackle this out.

**Comment by nipan09** [comment]
Hi, I am a new contributor on github and I would like to contribute in this issue. Shall I?

**Comment by Scaramoush** [comment]
I guess this issue is solved and can be closed?
