### ISSUE TITLE
Why the quickstart tutorial suggest creating new apps inside the project directory?

### ISSUE THREAD

**Issue by nguyendv** [encode/django-rest-framework#5662]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [ ] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Expected behavior
The [quickstart tutorial](http://www.django-rest-framework.org/tutorial/quickstart/) suggests creating new apps inside project directory. It admits that it's unusual. As a django/djangorestframework beginner, I expect a link to another section in the document, or an external source explain that suggestion.

> It may look unusual that the application has been created within the project directory. Using the project's namespace avoids name clashes with external module (topic goes outside the scope of the quickstart, you can see more [here](url)).

## Actual behavior
The tutorial states the topic goes outside the scope of the tutorial without providing a link to a further explanation

> It may look unusual that the application has been created within the project directory. Using the project's namespace avoids name clashes with external module (topic goes outside the scope of the quickstart).

**Comment by xordoquy** [comment]
Hi,

I agree a link would be nice.
I would definitively welcome and consider a PR on that topic.

However since it's unlikely we have the resources yet, I'm going to close the issue to keep the number of open issues manageable.

**Comment by tomchristie** [comment]
Echoing @xordoquy. Pull requests welcome, but otherwise not going to consider it a warranting an issue.

**Comment by hayate** [comment]
I agree with the author of the documentation that explaining namespaces clashes is outside the scope of the quickstart.

Even a link might not be necessary. For example, simply googling "python namespaces" gives you all the info you need.

However, I would like to know if there is anything intrinsic to DRF compared to a standard Django app that increases the chances of namespace clashes.

The Django documentation warns about namespaces clashes, which is helpful for new python programmers. 
But specifically, it suggests creating the app outside the project directory. (https://docs.djangoproject.com/en/4.0/intro/tutorial01/)

While the DRF documentation suggests creating the app inside the project directory.
So, in my opinion, what requires a little more explanation is this inconsistency of where to create the app and NOT what namespaces are.

Is there something in particular to DRF that makes namespace clashes more likely to happen than a regular Django app?

If we take the same care about namespace clashes as we do when creating a regular Django app outside the project directory, can we do the same with DRF? Will it all work as expected?
