### ISSUE TITLE
Serializer set required to False for model BooleanField()

### ISSUE THREAD

**Issue by dongzhangfan** [encode/django-rest-framework#5664]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
1. create a simple model `models.py`
```python
from django.db import models


class TestModel(models.Model):
    flag = models.BooleanField()
    integer = models.IntegerField()

```
2. create a simple serializer `serializers.py`
```python
from rest_framework import serializers
from .models import TestModel


class TestSerializer(serializers.ModelSerializer):

    class Meta:
        model = TestModel
        fields = 'flag', 'integer'
```

3. run these commands in django shell
```python
from <app-name>.models import TestModel
from <app-name>.serializers import TestSerializer

serializer = TestSerializer()
print(repr(serializer))
```
it shows:
```python
TestSerializer():
    flag = BooleanField(required=False)
    integer = IntegerField()
```

## Expected behavior
I am expecting `flag = BooleanField()`

## Actual behavior
`flag` is set to `required=False`.

**Comment by xordoquy** [comment]
Interesting.
This is expected although not clearly stated by the [documentation](http://www.django-rest-framework.org/api-guide/fields/#booleanfield). If `required=True` was set on this field, it wouldn't work with forms. However, I'm realizing that:

- this may have side effect on a pure JSON API
- this is not explicitly stated by the documentation

What would be the best way to go ?
Set `required=False` by default and allow users to override ?
Treat forms validation in a different way ?

Most likely my opinion would go for option 2.

**Comment by carltongibson** [comment]
> I'm thinking about adding a field in the DRF setting so that I can overwrite the behavior for now, although it seems a little hacky. 

Far from being hacky, that's a great solution. Per-project custom fields are a great thing. They're to be encouraged. (The supplied fields are great but they need to cover cases, such as HTML-form submission, say, which may not be relevant to you.)

**Comment by dongzhangfan** [comment]
@carltongibson Thanks, It's good to know this!

Could you give me some suggestions on where to look into? I'm pretty new to the framework, let along its codebase. I am assuming it's near the `rest_framework/settings.py`?

**Comment by carltongibson** [comment]
@dongzhangfan There's a [full example of using a _Required Boolean Field_ here](http://notes.noumenal.es/2017/12/13/required-by-default.html). I hope that helps.

**Comment by tomchristie** [comment]
Seconding @carltongibson - I'd be happy to see a documentation tweak here.
If the default behavior isn't suitable, then overriding the field explicitly is the simplest option.

**Comment by carltongibson** [comment]
PR incoming

**Comment by dongzhangfan** [comment]
@carltongibson Thanks! It is a great post and is really helpful!

**Comment by dms-cat** [comment]
@carltongibson Could you please put that page back up? I can't figure out how to make a required boolean field. `field_name = serializers.BooleanField(required=True)` in the serializer does not make the field required.
