### ISSUE TITLE
`raise_errors_on_nested_writes` support for `to_many`

### ISSUE THREAD

**Issue by claytondaley** [encode/django-rest-framework#5666]
## Background

The [current implementation](https://github.com/encode/django-rest-framework/blob/1692feb535472cb78c49328613a14aef48f77787/rest_framework/serializers.py#L761) of `raise_errors_on_nested_writes` permits the following approach to nested serialization (simplified for illustration):

```
class ReturnsAModelInstanceSerializer(ModelSerializer):
    class Meta:
        model = MyChildModel
        fields = '__all__'

    def to_internal_value(self, data):
        data = super(ReturnsAModelInstanceSerializer, self).to_internal_value(data)
        # insert complex matching logic here... with a trivial case being:
        return self.Meta.model(**data)

class ParentSerializer(ModelSerializer):
    class Meta:
        model = MyParentModel
        fields = '__all__'

    # ForeignKey in the underlying Model
    related = ReturnsAModelInstanceSerializer()

    def create(self, validated_data):
        # Must ensure 'related' has a PK due to FK dependency
        if 'related' in validated_data and validated_data['related'].pk is None:
            validated_data['related'].save()
        return super(ParentSerializer, self).create(validated_data)
```

Even though the field *is* a nested `Serializer`, it passes [this part](https://github.com/encode/django-rest-framework/blob/1692feb535472cb78c49328613a14aef48f77787/rest_framework/serializers.py#L788) of the `raise_errors_on_nested_writes` check because the entry in `validated_data` is populated with a model instance.  In this way, it's acting more like a related field than a nested serializer (which seems reasonable to me).

## Issue

Now consider the same infrastructure, but with a `many` field instead:

```
class ParentSerializer(ModelSerializer):
    ...
    related = ReturnsAModelInstanceSerializer(many=True)
    ...
```

In this version, the entry in `validated_data` is populated with a `list` of model instances.  It seems just as reasonable as the previous version, but it runs afoul of the `list` check [in the same place](https://github.com/encode/django-rest-framework/blob/1692feb535472cb78c49328613a14aef48f77787/rest_framework/serializers.py#L788).

## Proposal

`raise_errors_on_nested_writes` should be `many`-aware:

 - If the field is not a `many` serializer, the current check is used
 - If the field is a `many` serializer, the (same) checks are applied to each list element (ignoring the wrapping list)

I can submit the trivial PR (w/ test cases) if the general approach to nested serialization does not raise any red flags.

**Comment by xordoquy** [comment]
I'm more inclined to say you should customize the `ListSerializer` so its `to_internal_value` returns something that doesn't inherit from a `list`.

**Comment by claytondaley** [comment]
> I'm more inclined to say you should customize the ListSerializer so its to_internal_value returns something that doesn't inherit from a list.

Consider the two cases:

 - An iterable wrapping model instances (ready for assignment to a `many` field)
 - An iterable wrapping dicts (ready for assignment to a `many` field)

The first should pass and the second should fail regardless of the type of the iterable.

**Comment by xordoquy** [comment]
I'm missing context here. It looks like those are really tricky edge cases and I'm fine with saying it's not supported out of the box.

**Comment by carltongibson** [comment]
I (too) don't think this is a road we want to go down. The implementation deliberately avoids support for nested writes. It (deliberately) does that because it's a complicated topic that is too project specific for us to handle in core. Adding complication here goes against those long-standing design decisions.
