### ISSUE TITLE
format_suffix_pattern not working with path() in django 2.0

### ISSUE THREAD

**Issue by mr-skyaakash** [encode/django-rest-framework#5672]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Expected behavior
when using format_suffix_patterns() from the rest_framwork.urlpatterns class, it should format the url pattern for url() from django.conf.urls as well as the newly introduced path() from django.urls

## Actual behavior
getting an error when using path() in urlpatterns[], and then formatting it using the format_suffix_patterns() method

**Comment by xordoquy** [comment]
Next step on that issue would be to write a failing test case.

**Comment by adjordan** [comment]
I am having the same issue with the following urls.py file:

```
from django.urls import path, re_path
from rest_framework.urlpatterns import format_suffix_patterns
from snippets import views

urlpatterns = [
    path('snippets/', views.snippet_list),
    re_path('snippets/(?P<pk>[0-9]+)/', views.snippet_detail)
]

urlpatterns = format_suffix_patterns(urlpatterns)
```
