### ISSUE TITLE
ModelSerializer should update only the patched fields

### ISSUE THREAD

**Issue by bckohan** [encode/django-rest-framework#5674]
The update method on ModelSerializer calls instance.save(). I'm proposing that this should be changed to something like instance.save( update_fields=validated_data.keys( ) ) to ensure only the patched fields are updated. Of course, any m2m fields will need to be plucked out.

I'm currently overriding the update method in my own code to workaround a race condition where two simultaneous requests update different fields on the same model. If both serializes have loaded the model instance before either gets to update, whichever serializer hits update last will overwrite the first serializers update.

**Comment by xordoquy** [comment]
We do leave those use cases to the developers.
Patch implementation is basic. You likely want to rewrite the view's patch to deal with concurrents write and use `select_for_update` and the like. I feel there will be issues with relational models if we go down that road.
I'm closing this issue based on it. Other will reopen it if they feel I'm wrong on that one.
