### ISSUE TITLE
Add missed parenthesis to make a method call for string

### ISSUE THREAD

**Issue by Skyross** [encode/django-rest-framework#5684]
That issue stopped me using DRF swagger and `filter_backends` together.

https://github.com/encode/django-rest-framework/blob/0f33e63e10f23b9af243480a0eb002be3e98159b/rest_framework/schemas/inspectors.py#L370

**Comment by xordoquy** [comment]
Closing this as it is missing context.
There's a template that helps providing informations for bug reports so we can ensure it's not a user issue and someone can start working on it.

**Comment by carltongibson** [comment]
This was fixed in https://github.com/encode/django-rest-framework/pull/5613.
