### ISSUE TITLE
SchemaGenerator outputs non-functional URLs when using Django 2.0 path()

### ISSUE THREAD

**Issue by tiltec** [encode/django-rest-framework#5686]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

Create a Django 2.0 URLconf and generate a schema from it.

```py
urlpatterns = [
  path('example/', ExampleListView.as_view()),
  path('example/<int:pk>/', ExampleDetailView.as_view()),
]
```

## Expected behavior

Get a schema with urls `/example/` and `/example/{id}/`

## Actual behavior

Got `/example\\/` and `/example\\/{id}\\/`.

Ref: https://github.com/marcgibbons/django-rest-swagger/issues/718

## Background

Django 2.0 auto-escapes the string passed into `path()`, see [this piece of code](https://github.com/django/django/blob/df41b5a05d4e00e80e73afe629072e37873e767a/django/urls/resolvers.py#L206-L209)

## Possible solution

SchemaGenerator could undo this escaping when building the schema, I'm working on PR that does this.

**Comment by tiltec** [comment]
SchemaGenerator uses `simplify_regex` from `django.contrib.admindocs`, I wonder if they have the same problem and it should be fixed there?

**Comment by axnsan12** [comment]
@tiltec I don't see how calling str helps? care to elaborate?

**Comment by axnsan12** [comment]
Ah, I see now, django gets around this by calling str() directly on the `RoutePattern`/`RegexPattern` object; the result of `str(RoutePattern)` is a `path()` route, so simplify_regex does not affect it at all. For `RegexPattern`, `simplify_regex` transforms it into something that looks like `str(RoutePattern)`, and they then treat both kinds like `RoutePatterns` (i..e `path()` routes)

django-rest-framework does it in the opposite way, and grabs the regex from the `RoutePattern` and treats both kinds as regexes, which fails because the `RoutePattern` regex is heavily escaped and not handled by `simplify_regex`.

**Comment by tiltec** [comment]
Exactly! [RoutePattern.__str__()](https://github.com/django/django/blob/df41b5a05d4e00e80e73afe629072e37873e767a/django/urls/resolvers.py#L264-L265) returns the original route, which is not a regex. That doesn't matter for `simplify_regex()` apparently...

**Comment by axnsan12** [comment]
For what it's worth, this seems to be the same problem as #5675. I made an attempt at a naive fix for the way django-rest does it ([here](https://github.com/axnsan12/drf-yasg/commit/521172c195f261244666cb5d96cb977f1187d6d0), but filpping it around to the same treatment as django would probably make more sense.

**Comment by tiltec** [comment]
True, I didn't notice this one. Close here and move discussion to the other one?
