### ISSUE TITLE
ugettext_lazy should be renamed to gettext_lazy

### ISSUE THREAD

**Issue by werevolff** [encode/django-rest-framework#5690]
https://github.com/encode/django-rest-framework/blob/ea0b3b32ad49d9ac34af8caf49c81b9d8f231b83/rest_framework/authtoken/apps.py#L2

**Comment by xordoquy** [comment]
And why should it be renamed ?

**Comment by werevolff** [comment]
Sorry, after upgrading to Django2, got import error.

**Comment by carltongibson** [comment]
@werevolff Since you closed the issue, I assume it went away? What was the resolution?

**Comment by werevolff** [comment]
Don't know. At first time, I updated from Django 1.11, and got this error. After the virtualenv folder deletion, I could not to reproduce it.

**Comment by carltongibson** [comment]
OK. That _sounds_ like it's probably stale `.pyc` files lying around. If you hit it again, please come back.

**Comment by werevolff** [comment]
Yes, this is the most probable cause, along with fatigue.
