### ISSUE TITLE
Missing file in the 3.7.4 release.

### ISSUE THREAD

**Issue by xordoquy** [encode/django-rest-framework#5692]
static/rest_framework/fonts/glyphicons-halflings-regular.woff2 is missing from the 3.7.4 tarball while being in the repository.
Unfortunately this break some static files pipelines since the file is referenced in some css.

**Comment by axnsan12** [comment]
https://github.com/encode/django-rest-framework/blob/a81e60ff390b9b6788b2cac24a01ee4dd2dcffd2/MANIFEST.in#L3 this line seems to be the problem.

Why is it not simply `*` instead of listing all the extensions?

**Comment by xordoquy** [comment]
Probably because at some point there was other -intermediate- files in there.

**Comment by axnsan12** [comment]
And would it be ok to change it to * now? I think that would be safer in the future to prevent things like this from happening again.

**Comment by carltongibson** [comment]
Looks like #5695 is related. Maxim: Never touch the packaging. (Grrrr. 🙂)

We have the `dist` build now: 

https://github.com/encode/django-rest-framework/blob/d903896d3dc52e26bed1c0a31e409364e2d620fb/tox.ini#L33-L39

We should be able to add smoke tests at least (i.e. they don't need to be perfect) to catch these kind of regressions. 

(Grrrr. 🙂)

**Comment by xordoquy** [comment]
> And would it be ok to change it to * now? I think that would be safer in the future to prevent things like this from happening again.

That's a double edged sword. It could also include unwanted temporary files.

**Comment by axnsan12** [comment]
> That's a double edged sword. It could also include unwanted temporary files.

Which would IMO be better than missing important files because it's unlikely to break stuff. `recursive-exclude`or `global-exclude` would also be able to fix that just as well as including by extension.

One could also argue that temporary/intermediate files should sit in separate directories in the first place.

**Comment by xordoquy** [comment]
> One could also argue that temporary/intermediate files should sit in separate directories in the first place.

I totally agree with that by sometime, when it's generated, it's not as easy. I remember packaging my own pyc files once.

We need to weight all that and take a decision.

**Comment by tomchristie** [comment]
Keep it simple: We add `*.woff2` and roll a new release.

**Comment by tomchristie** [comment]
3.7.5 released
