### ISSUE TITLE
when foreignkey set null, how can i get a single field about foreignkey

### ISSUE THREAD

**Issue by yywing** [encode/django-rest-framework#5714]
## Steps to reproduce
```
class Case(models.Model):
    name = XXX
    info = XXX
class Test(models.Model):
    case = models.ForeignKey('case',null=True)
class TestSerializer(serializers.ModelSerializer):
    case_info = serializers.StringRelatedField(source='case.info', allow_null=True, required=False)
```
## Expected behavior
I hope if test.case set null, case_info is null. 
## Actual behavior
Now, it would raise AttributeError.
```'NoneType' object has no attribute 'info'```

Actually, I set ```on_delete=models.SET_NULL```.

**Comment by rpkilby** [comment]
Hi @yywing - the issue tracker is intended for bug reports & feature requests. If you're looking for [help](http://www.django-rest-framework.org/#support), I'd recommend either the IRC channel or discussion group.
