### ISSUE TITLE
help_text is not rendered consistently

### ISSUE THREAD

**Issue by beruic** [encode/django-rest-framework#5715]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
1. Create a help text in a serializer field that contains a html tag.
2. Enable the docs page with `rest_framework.documentation.include_docs_urls()`

## Expected behavior
Rendering of the help text is the same all placed.

## Actual behavior
In the browsable API form and in the interact window of the docs page where the serializer field is present, html tags are rendered. In the parameter description under the _Request Body_ section in the docs page, the tag is escaped instead so it is displayed.

## Further notes
A solution to this must of course be uniform. Furthermore (and I am unsure whether I should create another issue for this) I think line breaks must be possible.

**Comment by carltongibson** [comment]
Hi @beruic. 

Could you upload a couple of screenshots showing exactly what you mean here? (This would clarify the issue.)

Any chance you could track down the offending lines in the templates? (This would be the starting point for putting together a test case, and hence a fix.) 

Thanks.

**Comment by tomchristie** [comment]
Closing this off for now. Happy to reconsider if we've got more info.

**Comment by beruic** [comment]
Ok, so I have made a test with the following serializer:

```python
class SortingSerializer(serializers.Serializer):

    my_field = serializers.CharField(
        help_text='This text has<br>a line break'
    )
```

This results in the following renderings of the help text:
![normal](https://user-images.githubusercontent.com/724716/37157300-be7af216-22e8-11e8-91de-102841ac3432.png)
![docs](https://user-images.githubusercontent.com/724716/37157303-c0a25368-22e8-11e8-85db-e54af09834c0.png)
![docs_interact](https://user-images.githubusercontent.com/724716/37157308-c3073966-22e8-11e8-856b-549f05609577.png)

Now I would be ok with `<br>` just working, but it would be even better if you should use `\n` instead, but it just renders as a space everywhere.

**Comment by carltongibson** [comment]
Hmmm. There's not going to be much we can do here. 

The relevant code is here: 

https://github.com/encode/django-rest-framework/blob/d2994e0596c3163ac970b29dad6a61485f938045/rest_framework/schemas/inspectors.py#L26-L29

We're **not** going to want to introduce the kind of complexity that would be needed to handle arbitrary html fragments (and line break escapes and whatever you can think of). 

You're best bet would be to subclass `AutoSchema` and override `get_serializer_fields` to inspect the returned `description` of each field and what logic you need there.

**Comment by beruic** [comment]
I have made a pull request that fixes the issue by making rendering consistent. Whether the current behavior is desired, I believe is a decision to make for a future version.
