### ISSUE TITLE
Improve "Documenting your API" documentation section

### ISSUE THREAD

**Issue by fazpu** [encode/django-rest-framework#5718]
I have been working with the new Angular, written in Typescript.

On large projects, the workflow (and I believe best practice) is following:
1. there is a change in the API
2. swagger file is generated
3. Typescript interfaces and Angular services communicating with the API are auto-generated (e.g. with [this](https://github.com/swagger-api/swagger-codegen) or [this](https://github.com/jnwltr/swagger-angular-generator)).

In order do it, you need to have a definition of response schema. To the best of my knowledge, the Core API does not currently support that.

This is a major DRF issue that has been reported over a year ago in [issue #4502](https://github.com/encode/django-rest-framework/issues/4502). It seems there is still no Core API fix in sight.

In my opinion, the auto-documenting mechanism is currently the biggest DRF's pain point.

The situation seemed hopeless until some good soul created [drf-yasg](https://github.com/axnsan12/drf-yasg). To me, this is the best documenting solution in town.

I wasted too much time on this issue and I believe there will be others following my path. Hence, the documentation should include:

- clear statement that the current Core API solution does not support auto-generated response schemas.
- there is [drf-yasg](https://github.com/axnsan12/drf-yasg) that does have this capability

**Comment by carltongibson** [comment]
> It seems there is still no Core API fix in sight.

As said https://github.com/encode/django-rest-framework/issues/4502#issuecomment-351359159 this is what we're looking into for 3.8. 

> In my opinion, the auto-documenting mechanism is currently the biggest DRF's pain point.

It's good times when this is true. We've come a long way in the last few years. 😃

Whilst I hear your pain, I'm going to close this issue as is. Given your PR in #5719, this is essentially a duplicate (with a big +1) of #4502. The short answer there is, _Yes, we know. We're working on. Contributions Welcome!_.
