### ISSUE TITLE
Web browsable API has been down for weeks.

### ISSUE THREAD

**Issue by JNaftali** [encode/django-rest-framework#5722]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
go to http://restframework.herokuapp.com/

## Expected behavior
the web browsable API renders

## Actual behavior
the site appears to be in maintenance mode, and has been so for roughly the last several weeks. Is this intended?

**Comment by carltongibson** [comment]
This has been under maintenance as part of https://github.com/encode/rest-framework-tutorial/issues/41#issuecomment-342317221. 

That work is concluded now and the site is back up. 

Thanks @jpadilla for the awesome work! 🎉
