### ISSUE TITLE
Throttling With UserRateThrottle and ScopedRateThrottle

### ISSUE THREAD

**Issue by muthuveltkp** [encode/django-rest-framework#5723]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
In settings.py,

REST_FRAMEWORK = {
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
        ),
    'DEFAULT_THROTTLE_RATES': {
        'user': '100/day',
        'foo.get': '500/day'
    }
}

The above settings will allow read(foo.get) for 500 requests / 100 requests per day?

## Expected behavior

foo.get endpoint should allow 500 requests & other endpoints should allow 100 requests.
Totally 600 requests per day.

## Actual behavior

This settings is allowed only 100 requests per day in all endpoints(include foo.get endpoint).
Totally 100 requests per day only.

**Comment by xordoquy** [comment]
No, the expected behavior is: 100 requests per day in all endpoints as explained in the documentation:

> Before running the main body of the view each throttle in the list is checked. If any throttle check fails an exceptions.Throttled exception will be raised, and the main body of the view will not run.
