### ISSUE TITLE
URL contains a backslash

### ISSUE THREAD

**Issue by kwdiwt** [encode/django-rest-framework#5730]
![_ _20180107110904](https://user-images.githubusercontent.com/7121840/34646584-02d590b8-f3a7-11e7-9e8d-09e6109f9994.png)
Django 2.0         djangorestframework 3.7.3
```python
router = DefaultRouter()
router.register(r'books', views.BiddersList)
urlpatterns = [ 
    path(r'admin/', admin.site.urls),
    path(r'api/', include(router.urls)),
    path(r'api/spec', get_swagger_view(title='Book API'))
] 
```
SchemaGenerator.get_schema     returns a backslash
How to fix it?

**Comment by axnsan12** [comment]
Upgrade to 3.7.7

**Comment by kwdiwt** [comment]
thx
