### ISSUE TITLE
Incorrect "Accept" header of client.get

### ISSUE THREAD

**Issue by RokkerRuslan** [encode/django-rest-framework#5731]
## Checklist

- [ ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [ ] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

Create new project, add `include_docs_urls`

On client side:

      client.get("http://127.0.0.1:8000/api/docs/").then(function(data) {
        // Load a CoreJSON API schema.
        console.log(data)
        console.log('schema loaded')
        context.commit('initialize', schema)
      })

## Expected behavior

schema variable is js object with coreapi schema

## Actual behavior

schema is just html page.

Wireshark dump of headers:

```
    GET /api/docs/ HTTP/1.1\r\n
    Host: 127.0.0.1:8000\r\n
    Connection: keep-alive\r\n
    Pragma: no-cache\r\n
    Cache-Control: no-cache\r\n
    Origin: http://localhost:8080\r\n
    User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/63.0.3239.84 Chrome/63.0.3239.84 Safari/537.36\r\n
    Accept: */*\r\n
    Accept-Encoding: gzip, deflate, br\r\n
    Accept-Language: en-US,en;q=0.9,ru;q=0.8,es;q=0.7\r\n
    \r\n
```

## Investigation

Any actions raises - Uncaught LinkLookupError: Invalid link lookup: ["auth","create"]

coreapi python lib working correct:

```
coreapi get http://127.0.0.1:8000/api/docs/
<FooBar API "http://127.0.0.1:8000/api/docs/">
    auth: {
        create(email, password)
    }
```
Wireshark dump of headers:

```
Hypertext Transfer Protocol
    GET /api/docs/ HTTP/1.1\r\n
    Host: 127.0.0.1:8000\r\n
    user-agent: coreapi\r\n
    Accept-Encoding: gzip, deflate\r\n
    accept: application/coreapi+json, application/vnd.coreapi+json, */*\r\n
    Connection: keep-alive\r\n
    \r\n
```

**Comment by carltongibson** [comment]
Hi @RokkerRuslan, 

I think we need to take this over to https://github.com/core-api/javascript-client. Your complaint is that the client does not set the `application/coreapi+json` right? At first glance I'd guess it would be good to expect the right headers to be set. But we'll need to address it over there. 

In your case you should have `window.schema` already available, and so you should be free follow the [Using the Client](http://www.django-rest-framework.org/topics/api-clients/#using-the-client) steps.
