### ISSUE TITLE
Tutorial Documentation for Django 2.x

### ISSUE THREAD

**Issue by pktippa** [encode/django-rest-framework#5737]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

When I django 2.0 from below command.

```sh
$ pip install django
```

Got a different project structure that is not the same as 

https://github.com/encode/django-rest-framework/blob/master/docs/tutorial/quickstart.md#project-setup

And the Adding urls, it gives error, since the package structure is different now.

```python
from tutorial.quickstart import views
```

https://github.com/encode/django-rest-framework/blob/master/docs/tutorial/quickstart.md#urls

**Comment by xordoquy** [comment]
Just gave a try with a freshly installed Django 2.0 and got the same layout as the quickstart mentions:

    find .
    .
    ./tutorial
    ./tutorial/__init__.py
    ./tutorial/quickstart
    ./tutorial/quickstart/migrations
    ./tutorial/quickstart/migrations/__init__.py
    ./tutorial/quickstart/models.py
    ./tutorial/quickstart/__init__.py
    ./tutorial/quickstart/apps.py
    ./tutorial/quickstart/admin.py
    ./tutorial/quickstart/tests.py
    ./tutorial/quickstart/views.py
    ./tutorial/settings.py
    ./tutorial/urls.py
    ./tutorial/wsgi.py
    ./manage.py
