### ISSUE TITLE
A lacking closing paren.

### ISSUE THREAD

**Issue by koala-lava** [encode/django-rest-framework#5743]
In [tutorial 4 authentication and permission](http://www.django-rest-framework.org/tutorial/4-authentication-and-permissions/#adding-login-to-the-browsable-api), there's a tiny bug when you copypast the code from documentation. 

This bit lacks additional paren:
```url(r'^api-auth/', include('rest_framework.urls'),```
It's stange when you see the [source code](https://github.com/encode/django-rest-framework/blob/22f1c590998b0629bcf67e71f0d96f0a9fb80ec1/docs/tutorial/4-authentication-and-permissions.md) here on github, there is a paren.

**Comment by axnsan12** [comment]
> It's stange when you see the source code here on github, there is a paren.

It's not at all strange, it means that it was fixed.

The fix is just not yet deployed.

**Comment by xordoquy** [comment]
Indeed, it was fixed in #5713 and will be deployed when the next release is ready.

**Comment by carltongibson** [comment]
It might be worth a doc deploy... It's too late for me to verify there's no feature stuff in the tonight but if not I could push a doc update tomorrow AM. 

Looks like just a couple of doc fixes/improvements: https://github.com/encode/django-rest-framework/compare/3.7.7...master

**Comment by carltongibson** [comment]
An updated version of the docs is live now. 📖
