### ISSUE TITLE
create_only fields attribute

### ISSUE THREAD

**Issue by eracle** [encode/django-rest-framework#5745]
Hello there.
I am copy pasting the docs:

----------------
read_only:

Read-only fields are included in the API output, but should not be included in the input during create or update operations. Any 'read_only' fields that are incorrectly included in the serializer input will be ignored.

----------------

It would be interesting to have an option that allow to set the field's value only at creation time, from there on there is no possibility for the field's value will not be updated any more. it could be named like: create_only

## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

**Comment by carltongibson** [comment]
You need to use a [CreateOnlyDefault](http://www.django-rest-framework.org/api-guide/validators/#createonlydefault). 😉

**Comment by xordoquy** [comment]
@eracle we prefer to have a simple way to do that rather than to have tons of settings for very specific needs.

**Comment by dhaval-mehta** [comment]
Hi, 

I still believe in many cases `create_only_fields` is required and CreateOnlyDefault is not sufficient.

Assume Social media apps like Facebook. Here users can become friends of other users. 
Assume a simple connection model where the sender and receiver are foreign key fields.

When A connection is created, the sender will be CurrentUserDefault but what would be CreateOnlyDefault the receiver? We need this value only during creation Time from the end-user.

The second example could be a shipment model in an e-commerce company. Source and destination will be `create only` fields but the end-user needs to enter these fields.

I went through docs I found CreateOnlyDefault works correctly only if the field is read-only. Also, CreateOnlyDefault does not allow value from the end-user.

**Comment by Automobileservices4** [comment]
#5745

**Comment by dhaval-mehta** [comment]
> #5745

@Automobileservices4 Can you please explain your comment?

**Comment by rpkilby** [comment]
Hi @dhaval-mehta. This is approaching a more niche use case, and is unlikely to be added to the framework. The current behavior is straightforward - fields are generally readable and writeable, and `write_only`/`read_only` restrict the field to either half of that behavior.

But as described in the OP, `create_only` is a restriction on when the field is writable. An `update_only` argument is then also justifiable, but we'd generally prefer not to add settings to cover every possible use case, as each new setting increases complexity. 

So, this is probably best handled as a custom validator. I haven't tested the following, but it should be close enough to get you started. 

```python
def create_only_validator(value, field):
    instance = field.parent.instance
    if instance is not None:
        initial = field.get_attribute(instance)
        if initial != value:
            raise ValidationError(...)

# https://www.django-rest-framework.org/api-guide/validators/#accessing-the-context
create_only.requires_context = True
```

**Comment by dhaval-mehta** [comment]
Thanks, @rpkilby.  It is working like a charm. 

Can we include this in docs? It will help many people.

I am open to raising a merge request.

**Comment by rpkilby** [comment]
Probably not. This doesn't really belong in the serializer docs, as it's more a recipe for a specific use case.

**Comment by d2718nis** [comment]
Stumbled upon this thread while researching options for the same issue not for the first time. Another good one would be having two separate serializers for create and update actions like so:
```python
class ConnectionUpdateSerializer(serializers.ModelSerializer):

    class Meta:
        model = Connection
        fields = ('other')


class ConnectionCreateSerializer(ConnectionUpdateSerializer):

    class Meta:
        model = Connection
        fields = ('sender', 'receiver', 'other')
```

After that you need to update `get_serializer_class` method of your ViewSet:

```python
class ConnectionViewSet(viewsets.ModelViewSet):

    def get_serializer_class(self):
        if self.action == 'create':
            return ConnectionCreateSerializer

        if self.action == 'update':
            return ConnectionUpdateSerializer
```

But still, that's a lot of code, logic and tests compared to one setting in serializer field. Maybe it should be `field.mutable` which defaults to `True` instead of `create_only` setting to be more consistent with the current workflow? Thanks!
