### ISSUE TITLE
Add support for section description in API Documentation

### ISSUE THREAD

**Issue by Brobin** [encode/django-rest-framework#5746]
This is a suggestion more than a bug. I would like it if each section of the generated API documentation can have a description as well as each link in the section.

## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

I was working on creating API documentation, and found no way to document a model or a viewset in a general sense, without having the same description on every endpoint. I tried this, expecting the main description to render before each endpoints's heading.

```python
class MyModelListView(viewsets.ModelViewSet): 
    """
    This is a description of what MyModel is.

    read:
    Get a MyModel by id

    list:
    Get a list of available MyModels
    """
    http_method_names = ['get', 'list', 'head']
    queryset = MyModel.objects.order_by('id')
    serializer_class = serializers.MyModelSerializer
```

## Expected behavior

This is the result I was looking for 

![drf_api_docs](https://user-images.githubusercontent.com/6194619/34888548-3f3fef34-f790-11e7-96cb-05cc87ed2207.png)

## Actual behavior

No description shows up.

---

I examined the template, hoping to find a way to make this show up, but I don't have enough understanding of the schema generators to get this done. Is this possible?

**Comment by tomchristie** [comment]
We don't currently have any way in coreapi to do this, and it's also not possible to have section descriptions in swagger/openapi schemas, so going to close this off for now.

I think we *might* end up expanding some support here, but nothing actionable right now.

**Comment by axnsan12** [comment]
Just a nitpick, but you can have tag descriptions in openapi: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#tag-object

**Comment by tomchristie** [comment]
Good to know. Doing some work on refreshing coreapi now so maybe we’lol be able to come back to this.
