### ISSUE TITLE
DecimalField fails with "A valid number is required" when '' is passed

### ISSUE THREAD

**Issue by codebreach** [encode/django-rest-framework#5749]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
- Create a `DecimalField` `decimal` in the model with `blank=True, null=True` (and other args)
- Create related Serializer
- Try to save using serilizaer with `decimal=''`

## Expected behavior
- Should save value of `NULL` to db

## Actual behavior
- Returns error `{decimal: A valid number is required}`

## Comments
I have looked at the code and it seems to be that the cause is 
https://github.com/encode/django-rest-framework/blob/master/rest_framework/fields.py#L1052-L1055

We can add some blank/null handling like it has been done for `CharField` in
https://github.com/encode/django-rest-framework/blob/master/rest_framework/fields.py#L772-L775

I am more than happy to open a PR with tests if this is something that classifies as a bug and will be accepted.

Please let me know :)

**Comment by xordoquy** [comment]
Hi, an empty string is not a a Null value. Try with `None`. `serializeer.DecimalField` won't allow empty string since it doesn't have a `allow_blank` option

**Comment by codebreach** [comment]
can we implement an allow_blank type thing?
essentially our users are sending `decimal: ''` and we want that to behave like `decimal: null`

**Comment by xordoquy** [comment]
You'll need to override the field and add this behavior.

**Comment by codebreach** [comment]
that would imply explicitly defining a field each and every place decimal field is used, as opposed to currently we get the serializer fields for free.

just making sure that you are not open to this being part of DRF

**Comment by xordoquy** [comment]
You can alter https://github.com/encode/django-rest-framework/blob/master/rest_framework/serializers.py#L847 to make it the default mapping without requiring to override the field on every occurence.

It's unlikely to see `DecimalField` with a `allow_blank` option in core as it doesn't make sense to me.

**Comment by codebreach** [comment]
Got it. Thanks a lot for the support

**Comment by rootux** [comment]
This is how I solved this:
```
class BlankableDecimalField(serializers.DecimalField):
    """
    We wanted to be able to receive an empty string ('') for a decimal field
    and in that case turn it into a None number
    """
    def to_internal_value(self, data):
        if data == '':
            return None

        return super(BlankableDecimalField, self).to_internal_value(data)
```

Then somewhere in your serializer you can use as such:
```
width = BlankableDecimalField(max_digits=20, decimal_places=8, required=False)
```

**Comment by georgmzimmer** [comment]
> You can alter https://github.com/encode/django-rest-framework/blob/master/rest_framework/serializers.py#L847 to make it the default mapping without requiring to override the field on every occurence.
> 
> It's unlikely to see `DecimalField` with a `allow_blank` option in core as it doesn't make sense to me.

React does not like you to use null or undefined values to initialize your state variables.  You'll get this if you try it:

`Warning: A component is changing an uncontrolled input of type number to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component`

So your only alternative is to default to empty string.  Which DRF rejects.  So you are left to perform extra work in your react code to fix the data to work around the for DRF DecimalField quirk.

**Comment by tomchristie** [comment]
I don’t have a problem with allowing empty strings to get mapped to None by DecimalField - that’s be absolutely fine, and we could probably accept a PR doing so. But, keep in mind that the output would still default to None. (Perhaps it’d need a flag to switch between styles?)

**Comment by Osca-M** [comment]
I experienced the same, a little modification to the solution provided by @rootux 

```
class BlankableDecimalField(serializers.DecimalField):
    """
    We wanted to be able to receive an empty string ('') for a decimal field
    and in that case turn it into a None number. 
    """

    def to_internal_value(self, data):
        if data == '':
           """
          if you return None you shall get a type error ```TypeError: '>' not supported between instances of 'NoneType' and 'int'```
           """
            return 0
        return super(BlankableDecimalField, self).to_internal_value(data)
```

```
width = BlankableDecimalField(
        max_digits=15, decimal_places=2, max_value=999999999, min_value=0, allow_null=True
    )
```
