### ISSUE TITLE
IntegerField with a 0 value is not rendered properly with TemplateHTMLRenderer

### ISSUE THREAD

**Issue by kgeorgy** [encode/django-rest-framework#5767]
## Steps to reproduce

Create a serializer with an *IntegerField* (or a *ModelSerializer* for a model with an *IntegerField*).

In the view, set the renderer to be *TemplateHTMLRenderer*.

If there is a zero value stored for the field into the DB, then the input field in the generated HTML has no value set:

`﻿﻿<input name="x" class="form-control" type="number">`

This make sense if the value was None but not if the value is 0.

## Expected behavior

The generated HTML code should be for 0 value:

`﻿﻿<input name="x" class="form-control" value="0" type="number">`

## Actual behavior

The following HTML code is generated:

`﻿﻿<input name="x" class="form-control" type="number">`

### Suspicion

I suspect the problem is in [input.html](https://github.com/encode/django-rest-framework/blob/master/rest_framework/templates/rest_framework/vertical/input.html), in the line

`<input name="{{ field.name }}" {% if style.input_type != "file" %}class="form-control"{% endif %} type="{{ style.input_type }}" {% if style.placeholder %}placeholder="{{ style.placeholder }}"{% endif %} {% if field.value %}value="{{ field.value }}"{% endif %} {% if style.autofocus and style.input_type != "hidden" %}autofocus{% endif %}>`

The `{% if field.value %}value="{{ field.value }}"{% endif %}`  may be evaluated as False because value is 0.

**Comment by nikhil96sher** [comment]
Hey! I would like to work on this. Would add a PR soon.

**Comment by kgeorgy** [comment]
@nikhil96sher With pleasure ;)

I just mentioned one of the `input.html` for the vertical template, but it should be present also for the inline, horizontal, etc. (If it is confirmed that the issue is what I suspect)

**Comment by xordoquy** [comment]
@kgeorgy your analysis seems correct, thanks for the nice work !

**Comment by nikhil96sher** [comment]
@kgeorgy The issue is in fact what you suspected.
Just confirming the expected outputs for the different inputs, 
`field.value = None` => value shouldn't be there
`field.value = 0` => value = 0
`field.value = ""` => value = ""

**Comment by kgeorgy** [comment]
Exact, for the third point, it make sense to put value="" in the HTML, even if (if I remember well) browsers does not send value in form encoded data if value is "". But it is coherent to display value="" for a empty string value.

**Comment by nikhil96sher** [comment]
@kgeorgy @xiaohanyu I have added the PR #5768. 
For the case of field.value = "", a test made me realize that `utils.serializer_helpers.BoundField.as_field_error()` converts None to '' (caught by `TestNestedBoundField.test_rendering_nested_fields_with_none_value` ) and so we shouldn't add value="" for these cases.
