### ISSUE TITLE
Language config for Django Rest Framework SearchFilter Full-text search

### ISSUE THREAD

**Issue by joinworldtv** [encode/django-rest-framework#5774]
There is no way to set the language flag for Django REST Framework SearchFilter (Full-text search). 

So here is my code:

```
class SearchViewSet(generics.ListAPIView):     
    queryset = ServicePrice.objects.all()     
    serializer_class = ServicePriceSerializer     
    filter_backends = (filters.SearchFilter,)     
    search_fields = ('@service__name',)     # <-- Full-text search
```

I need to set (somewhere) that my language is Spanish, so the result should be something like this:

`SELECT to_tsvector('spanish', 'bla-bla-bla in spanish') @@ plainto_tsquery('spanish', 'bla');`

The example of using the language config from Django:

`SearchVector('body_text', config='spanish') `

**Comment by tomchristie** [comment]
You'll need to use a custom search filter to add that functionality.
