### ISSUE TITLE
Request feature: Be able to set client remote ip address

### ISSUE THREAD

**Issue by elcolie** [encode/django-rest-framework#5775]
**Background:**
My Django Backend needs to leave open `webhooks` endpoints for the Internet for example `SocialMedia`, ... etc
Therefore I have to create the `whitelist` to protect my database

I would like this think as a feature
```python
client = APIClient()
client.set(remote_addr='111.111.111.111')
```

Or if you have any workaround on this issue. Please let me know.

I had tried asking for the answer from `stackoverflow`, but non of them satisfy my requirement
https://stackoverflow.com/questions/48415210/django-rest-client-test-with-specific-ip

**Comment by rpkilby** [comment]
Are you looking to set the remote_addr HTTP header? If so, it's fairly straightforward.

https://docs.djangoproject.com/en/2.0/topics/testing/tools/#django.test.Client

**Comment by elcolie** [comment]
@rpkilby Thank you. That's is what I need 👍
