### ISSUE TITLE
[Query] Is there any plan to integrate protobuf into django rest?

### ISSUE THREAD

**Issue by akhilputhiry** [encode/django-rest-framework#5779]
Similar to JSON is there any plan to include protobuf? JSON seems to very bulky and protobuf seems to very lean. May be we can generate the `.proto` file from django models or serializer and use it to generate protobuf? I am interested in working on this idea. But I need some mentors? What do you think.

**Comment by xordoquy** [comment]
None I'm aware of.
The best way to get it working would be to create a 3rd party at first. Mailing list or IRC would be a good way to communicate.

**Comment by allardhoeve** [comment]
Even though this is closed, it seems like a cool project. Certainly sounds possible to generate a schema!

**Comment by mbande** [comment]
@akhilputhiry i'm interested in this idea too.
please share links if you created some 3rd party or something.

**Comment by xordoquy** [comment]
Also, think about adding it to the 3rd party resource page on Django REST framework - as well as the parser/renderer pages - and annonce it on the mailing lists :)
