### ISSUE TITLE
DEFAULT_AUTHENTICATION_CLASSES and DEFAULT_PERMISSION_CLASSES settings are not working

### ISSUE THREAD

**Issue by 27149chen** [encode/django-rest-framework#5786]
DEFAULT_AUTHENTICATION_CLASSES and DEFAULT_PERMISSION_CLASSES settings in the django setting REST_FRAMEWORK are not working after upgrading from 3.4.7 to 3.7.7

## Steps to reproduce
Nothing is changed, after upgrade, these two settings no longer have any effect.
1. If permission_classes is set but authentication_classes not, permissions in permission_classes and DRF default authentication take effect.
2. If authentication_classes is set but permission_classes not, authentication in authentication_classes and DRF default permissions take effect.
3. If permission_classes and authentication_classes are set, everything is fine.
4. If permission_classes and authentication_classes are not set , all DRF default .

## Expected behavior
DEFAULT_AUTHENTICATION_CLASSES and DEFAULT_PERMISSION_CLASSES settings in the django setting REST_FRAMEWORK should work.
## Actual behavior
DEFAULT_AUTHENTICATION_CLASSES and DEFAULT_PERMISSION_CLASSES settings in the django setting REST_FRAMEWORK are not working.

**Comment by xordoquy** [comment]
From your step to reproduce, it looks like everything is fine.
Could you be more explicit about what doesn't work ?

**Comment by 27149chen** [comment]
Hi,

custom permission and authentication settings in django setting key "REST_FRAMEWORK" don't work.
for example, if I set token authentication in django settings, when accessing an API, the DRF basic authentication is used.

**Comment by xordoquy** [comment]
This likely something wrong with some part of your project. Maybe some settings are overridden without you noticing it.
I haven't noticed anything wrong on my projects nor has this been reported and I believe this would be spotted very fast.
As it currently is, there isn't much we can do. The next step here would be a set up the simplest project that demonstrate the issue so we can have a look at it.

**Comment by nadimtuhin** [comment]
The issue is 'rest_framework' in installed_app is not loading :(

**Comment by 27149chen** [comment]
@nadimtuhin , how to load it? Is there any difference from older versions?

**Comment by nadimtuhin** [comment]
found the issue, I imported pagination class in settings file, so drf was not loading the settings from settings.REST_FRAMEWORK
