### ISSUE TITLE
compat.set_many

### ISSUE THREAD

**Issue by cymushier** [encode/django-rest-framework#5789]
I have been using compat.set_many in some of my mixins. I just updated and broke everything that was relying on it. Is there some sort of reason for this of workaround?

**Comment by xordoquy** [comment]
This was a compatibility trick to support Django < 1.10. Since we don't support those any longer we removed the compatibility hack.
See https://github.com/encode/django-rest-framework/commit/c674687782ef96a3bb8466b412e99debd3d04f00#diff-ce493f71b3679e91b72126c168670399
