### ISSUE TITLE
topics/contributing/

### ISSUE THREAD

**Issue by dilyanpalauzov** [encode/django-rest-framework#5791]
http://www.django-rest-framework.org/topics/contributing/ says:

> git clone git@github.com:encode/django-rest-framework.git

which shows, when executed:

> Cloning into 'django-rest-framework'...
>Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
> Permission denied (publickey).
> fatal: Could not read from remote repository.
>
> Please make sure you have the correct access rights and the repository exists.

The correct text shall be:
> git clone git://github.com/encode/django-rest-framework.git

so that the code can be downloaded without keys.

**Comment by carltongibson** [comment]
Hmmm. I don't know what your setup is but GitHub's UI recommends the URL as-is: 

![screenshot 2018-02-01 15 04 15](https://user-images.githubusercontent.com/64686/35682513-482decb4-0761-11e8-913d-62e8f3fd1163.png)

(For reference the HTTPS URL is <https://github.com/encode/django-rest-framework.git>)

**Comment by dilyanpalauzov** [comment]
I am talking about http://www.django-rest-framework.org/topics/contributing/ .  For preparing a contribution, people are not supposed to clone with SSH but unauthenticated.

Otherwise the logic on topics/contributing is:
1. Development
To start developing on Django REST framework, clone the repo: `git clone git@github.com:encode/django-rest-framework.git` - **this step fails for most people**
2. Testing
To run the tests, clone the repository, and then: ... - **who is supposed to come so far, if cloning the repository from the first step has failed?**

**Comment by carltongibson** [comment]
I agree, except step 1 does not fail for most people. You don't need auth to clone a public repo. The URL is just that that GitHub recommends.

**Comment by xordoquy** [comment]
Actually git@ style uri requires auth since it goes through SSH. Start an anonymous session and you'll only see `https://github.com/encode/django-rest-framework.git`

This being said, I don't think an anonymous checkout is the way toward contribution. Should be fork the project and clone your fork or something similar.

**Comment by carltongibson** [comment]
OK. Lets have it then. 

> Should be fork the project and clone your fork or something similar.

Quick fix saying that.
