### ISSUE TITLE
Cannot Set more than one cookie in APIView classes using rest_framework Response object

### ISSUE THREAD

**Issue by infintesimal** [encode/django-rest-framework#5793]
when writing an apiview function, this is not an issue as I can get a handle on a django response object there. But when using an APIView class, it fails.

## Steps to reproduce
1. Define an APIView class, e.g. CreateAPIView
2. In this APIView class, override get_success_headers(self, data) so that it attempts to set more than one Cookie, e.g.
```def get_successs_headers(self, data):
  myheaders = {
     'Set-Cookie': 'foo=bar; path=/; domain=example.come; max-age=86400' ,
     'Set-Cookie': 'coo=car; path=/; domain=example.come; max-age=86400' ,
}
```
Obviously won't work only one of those two duplicate keys will survive.
## Expected behavior
Need to have a method where I can add multiple cookies to the rest_framework Response object
## Actual behavior
I can set only one cookie (though I can set multiple headers that are independent)

The offending source code is a combination of API of the rest_framework response object, which wants headers passed in as a simply dictionary and the handling of this dictionary
here 

> https://github.com/encode/django-rest-framework/blob/master/rest_framework/response.py#L47-#L49

**Comment by rpkilby** [comment]
Hi @infintesimal - it's not clear to me what exactly are you asking for. Are you expecting that the cookie headers are merged? eg, the output would look like:

```python
myheaders = {
     'Set-Cookie': 'foo=bar; coo=car; path=/; domain=example.come; max-age=86400' ,
}
```

**Comment by infintesimal** [comment]
Sorry, I am asking to be able to set more than one cookie in a DRF APIView response.
I illustrated the example above as to why it doesn't work
.
The functionality that I expect is that the rest_framework Reponse class, which is not instantiable, actually allow for the setting of more than 1 cookie.

I want to be in a spot where i can use the 
get_success_headers(self,data) function to set more than one cookie on the DRF response.

Something like
Response.set_cookie("foo=bar; path=/; domain=example.com, max-age=86400")
Response set_cookie("coo=car; path=/, domain=example.com, max-age=86400")

So that my response headers would actually show
```
...
Set-Cookie; foo=bar; ...
Set-Cookie; coo=car; ...
...
```

The current code does not permit this without overriding or radically redefining the rest_framework Response class.  Does that help clarify?

Steve

**Comment by infintesimal** [comment]
To be more explicit (longer code below; the meat is in the def get_success_headers(self, data) function. Using CreateAPIView ouf of the box, I can only set one cookie on the reponse. I believe I should be able to set as many cookies as my view wishes to set (in practice that is at least 2, maybe 3)

```
from django.db.utils import IntegrityError
from django.utils.decorators import method_decorator
from django.utils.translation import gettext_lazy as _
from django.views.decorators.clickjacking import xframe_options_exempt

from rest_framework.views import exception_handler
from rest_framework.generics import CreateAPIView
from rest_framework.response import Response
from rest_framework.exceptions import APIException, ParseError
from rest_framework import status
#from rest_framework.decorators import authentication_classes
#from rest_framework.decorators import permission_classes
#from rest_framework.permissions import AllowAny

from auth.hashers import make_password

from pg2.base import CookieBuilder
from dim.models import Guids, Logins
from dim.serializers import GuidSerializer, CreateLoginSerializer

@method_decorator(xframe_options_exempt, name='dispatch')
class CreateLogin(CreateAPIView):
    model = Logins
    queryset = Logins.objects.all()
    serializer_class = CreateLoginSerializer
    error = False
    error_message = None
    error_data = {}

    def get_success_headers(self, data):
        try:
            cookie = CookieBuilder(name="guid", value=str(data['guid']))
            cookie_str = cookie.get_cookie_str()
            # TROUBLE BEGINS HERE, I REALLY WANT TO SET MORE THAN ONE COOKIE!
            return {'Set-Cookie': cookie_str }
        except (ValueError, TypeError, AttributeError):
            return {}

    def perform_create(self, serializer):
        #serializer.is_valid()
        guid = Guids()
        guid.save()
        try:
            serializer.save(guid=guid, password=make_password(serializer.validated_data['password']))
        except (APIException, IntegrityError):
            guid.delete(purge=True)
            detail = _('already exists. If this email belongs to you, try resetting the password')
            self.error = True
            self.error_message = _('email ') + str(serializer.validated_data['email']) + ' ' + str(detail)
            self.error_data = {
                "status": "error",
                "message": self.error_message,
                "email": str(serializer.validated_data['email'])
            }

```

**Comment by tomchristie** [comment]
I don’t see us changing get_success_headers to allow for mulitple headers with the same key. Not sure how we’d do that anyway. I’d suggest overriding the view method itself, possibly calling ‘super’ and then set_cookie on the response before returning it.

**Comment by infintesimal** [comment]
@tomchristie, It doesn't need to be get_success_headers(self, data) that needs to be changed.
The current flow for an APIView is that the API View calls create(), create() calls perform_create then control returns to create(), which calls get_success_headers() and lastly return Response()

The DRF Reponse object itself is incapable of adding more than 1 cookie header. IMO, that breaks the very essence of request response handling; any piece of the chain that returns a response, should be able to set more than one cookie.

I think the answer is in either changing how rest_framework.Response is implemented or offering an alternative.

After I dug tracing the django source code, the essence of this is that wsgi.py does this at the very "end" of the response process. It looks for cookie objects in the response object. So it seems to me that adding a method that will attach cookie values (using SimpleCookie as elsewhere in django) would solve the entire problem.

**Comment by rpkilby** [comment]
> The DRF Reponse object itself is incapable of adding more than 1 cookie header. 

@infintesimal - I don't understand. Is there a reason you can't use [`Response.set_cookie`](https://github.com/django/django/blob/c10cb9716f8fd7398a8206cd8b33ed2f03065f85/django/http/response.py#L156-L196) or is there a reason `set_cookie` is insufficient? DRF's Response inherits Django's `HttpResponse`, which does most of the heavy lifting.

**Comment by tomchristie** [comment]
So override ‘APIView.create’
