### ISSUE TITLE
Missing/faulty information in API documentation (schemas)

### ISSUE THREAD

**Issue by vhelke** [encode/django-rest-framework#5794]
## Checklist

I have verified that that issue exists against the master branch of Django REST framework.
I have searched for similar issues in both open and closed tickets and cannot find a duplicate.

## Steps to reproduce

Missing details in API documentation: schemas

https://github.com/encode/django-rest-framework/blob/master/docs/api-guide/schemas.md#get_manual_fieldsself-path-method

```
def get_manual_fields(self, path, method):
    """Example adding per-method fields."""

    extra_fields = []
    if method=='GET':
        extra_fields = # ... list of extra fields for GET ...
    if method=='POST':
        extra_fields = # ... list of extra fields for POST ...

    manual_fields = super().get_manual_fields()
    return manual_fields + extra_fields
```

manual_fields should be
```
manual_fields = super().get_manual_fields(path, method)
```

The problem seems to be only documentation related.

**Comment by carltongibson** [comment]
Hi @vhelke. Yep. If you want to make a quick PR adjusting, that would be great!
