### ISSUE TITLE
Documentation unclear about using LiveServerTestCase with RequestsClient

### ISSUE THREAD

**Issue by emft** [encode/django-rest-framework#5803]
## Checklist

- [X] I have verified that that issue exists against the `master` branch of Django REST framework.
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [X] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [X] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

I've been told that the `RequestsClient` should only be used with `LiveServerTestCase` (https://github.com/encode/django-rest-framework/issues/5801).  However, the [documentation](http://www.django-rest-framework.org/api-guide/testing/#requestsclient) is not clear about that at all.  It mentions a few issues to consider with `RequestsClient` but not that one at all.

**Comment by tomchristie** [comment]
> I've been told that the RequestsClient should only be used with LiveServerTestCase

That's not correct.

**Comment by xordoquy** [comment]
@tomchristie correct me if I'm wrong:
`RequestsClient` can be used with a lot of things other than `LiveServerTestCase`.
However, `RequestsClient` will not work with "regular" `TestCase` if the goal is to test the current code.

**Comment by tomchristie** [comment]
The client calls into the WSGI interface. I don’t have any reason to think LiveServerTestCase is required, but perhaps I’m missing something about test setup/tear down in that case?

**Comment by rfleschenberg** [comment]
I ran into what seems to be the same problem as https://github.com/encode/django-rest-framework/issues/5801. My test passes with `APILiveServerTestCase`, but fails with `APITestCase` (500 response, "Connection already closed"). It would be nice to understand why, and maybe indeed the documentation should be updated somehow?

My test looks like this:

```python
class TestCreatePrescription(APILiveServerTestCase):
    # We want to use RequestsClient here to get a more realistic test.
    # For some reason, we have to use APILiveServerTestCase to get this to work.
    # It would be nice to understand why.
    # https://github.com/encode/django-rest-framework/issues/5801
    # https://github.com/encode/django-rest-framework/issues/5803#issuecomment-362557169

    def test_create_prescription(self):
        jpg_path = os.path.join(
            os.path.dirname(__file__), "..", "..", "..", "testdata/images/valid.jpg"
        )
        client = RequestsClient()
        with open(jpg_path, "rb") as jpg_file:
            response = client.post(
                "http://testserver/api/v2/mhplus/prescription/",
                data=jpg_file.read(),
                headers={
                    "Content-Type": "image/jpeg",
                    "Content-Disposition": "attachment; filename=prescription.jpg",
                }
            )
        assert response.status_code == status.HTTP_201_CREATED, response.json()
```
