### ISSUE TITLE
Update jQuery/bootstrap and use single copy

### ISSUE THREAD

**Issue by blueyed** [encode/django-rest-framework#5804]
There are two versions of jQuery included (3 if you include `docs_theme`):

```
% find rest_framework docs_theme -iname '*jquery*js*'
rest_framework/static/rest_framework/docs/css/jquery.json-view.min.css
rest_framework/static/rest_framework/docs/js/jquery-1.10.2.min.js
rest_framework/static/rest_framework/docs/js/jquery.json-view.min.js
rest_framework/static/rest_framework/js/jquery-1.12.4.min.js
docs_theme/js/jquery-1.8.1-min.js
```

It would be good to only have one copy included, and update it then - to fix e.g. an existing vulnerability (https://snyk.io/vuln/npm:jquery:20150627).

**Comment by blueyed** [comment]
bootstrap is also affected:
```
./rest_framework/static/rest_framework/docs/css/bootstrap-theme.min.css
./rest_framework/static/rest_framework/docs/css/bootstrap.min.css
./rest_framework/static/rest_framework/docs/js/bootstrap.min.js
./rest_framework/static/rest_framework/css/bootstrap.min.css
./rest_framework/static/rest_framework/css/bootstrap-tweaks.css
./rest_framework/static/rest_framework/js/bootstrap.min.js
./licenses/bootstrap.md
./docs_theme/css/bootstrap-responsive.css
./docs_theme/css/bootstrap.css
./docs_theme/js/bootstrap-2.1.1-min.js
```

https://snyk.io/vuln/npm:bootstrap:20160627

**Comment by lsolberg** [comment]
Just a heads-up.. This bit me in a weird way.

My environment is without internet connection and I am using django-debug-toolbar. I need to use it's `JQUERY_URL` config to point to an internal jquery, which at the time being was `/static/rest_framework/js/jquery-1.12.4.min.js` (yes, I know....)

It did however not cause any major detectable issues for me when 1.12.4 was gone, except that the parsers django-rest-framework used was failing when using the web-frontend of drf, causing issues very similar to https://github.com/encode/django-rest-framework/issues/3623..

Updating `JQUERY_URL` to `/static/rest_framework/js/jquery-3.3.1.min.js` solves this (haha.. I will move it to an internal CDN when I have that ready ☺️  )
