### ISSUE TITLE
Invalid data

### ISSUE THREAD

**Issue by ezequiel454** [encode/django-rest-framework#5805]
I dont know what is the problem, i am trying everything.
The user can be null
but on the post method ,i got this problem.

![image](https://user-images.githubusercontent.com/11526507/35756433-1156d39c-084a-11e8-87b1-f00589394a0d.png)

![image](https://user-images.githubusercontent.com/11526507/35756456-248d4cfc-084a-11e8-865a-8f3c6c8835fc.png)

![image](https://user-images.githubusercontent.com/11526507/35756468-345735da-084a-11e8-85ba-256ce898422d.png)

**Comment by tomchristie** [comment]
The issue tracker is for reporting bugs and feature requests.

I’m not sure what ‘RelationModelSerializer’ is or ‘is_relation=True’, but those aren’t part of the rest framework package.
