### ISSUE TITLE
/rest_framework/compat.py in <module>, line 26（No module named urls）

### ISSUE THREAD

**Issue by kkdetong** [encode/django-rest-framework#5808]
ImportError at /
No module named urls
Request Method:	GET
Request URL:	http://127.0.0.1:8000/
Django Version:	1.8.13
Exception Type:	ImportError
Exception Value:	
No module named urls
Exception Location:	/home/python/.virtualenvs/py2/local/lib/python2.7/site-packages/rest_framework/compat.py in <module>, line 26
Python Executable:	/home/python/.virtualenvs/py2/bin/python
Python Version:	2.7.11
Python Path:	
['/home/python/movieweb_python/movieweb',
 '/home/python/.virtualenvs/py2/lib/python2.7',
 '/home/python/.virtualenvs/py2/lib/python2.7/plat-x86_64-linux-gnu',
 '/home/python/.virtualenvs/py2/lib/python2.7/lib-tk',
 '/home/python/.virtualenvs/py2/lib/python2.7/lib-old',
 '/home/python/.virtualenvs/py2/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/home/python/.virtualenvs/py2/local/lib/python2.7/site-packages',
 '/home/python/.virtualenvs/py2/lib/python2.7/site-packages']
Server time:	星期一, 5 二月 2018 12:08:26 +0000

![qq 20180205202215](https://user-images.githubusercontent.com/33319742/35804377-8e6e4d78-0ab2-11e8-862a-b4ff9de1f41b.png)

**Comment by xordoquy** [comment]
Make sure your Django REST framework version is compatible with the installed Django version.

**Comment by zenglijuan** [comment]
请问你这个问题怎么解决的呀？我也遇到了这个问题，不知道怎么解决
