### ISSUE TITLE
Support for path() in urls.py

### ISSUE THREAD

**Issue by sanderzz91** [encode/django-rest-framework#5811]
Hi,

I'm using Django 2.0.1 and when I scaffold my projects with it, it generates a urls.py file containing

```
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
]
```

I saw that the documentation on the site uses the url() function instead of the path() function, for example:

```
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('broker.urls')),
    url(r'^api-auth', include('rest_framework.urls')),
]
```

Now, I tried to modify this code slightly so I could use the django.urls.path() function again, but it seems that that doesn't work. Did I do something wrong, or is django.urls.path() just not supported in the Django REST Framework? If not, is it going to be? I prefer path() because it's slightly simpler to write the path strings, and it doesn't require understanding of regex strings.

Kind regards.

**Comment by carltongibson** [comment]
Hi @sanderzz91 

I'm going to assume this is the namespacing issue that will be addressed in #5609. Have a look at the examples there. You **should** be able to get it working. 

For interest: What was your issue? What was your error? (If it's something different we can re-open.)

**Comment by sanderzz91** [comment]
I'm sorry for the late answer, I'm developing an application with tight deadlines.

Up til now I couldn't make the URL config work with the path() functions.
My code with path() functions is the following.

**projectfolder/broker/urls.py**

```
from django.urls import path, include

app_name = 'broker'
urlpatterns = [
    path('users/', views.UserViewSet, name='users'),
    path('dashboards/', views.DashboardViewSet, name='dashboards'),
    path('widgets/', views.WidgetViewSet, name='widgets')
]
```

**projectfolder/Broker/urls.py** (Broker is my 'main' app, so it has the root urlconf)


```
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('broker.urls', 'broker'), namespace='broker')),
    # The GUI's authentication endpoint (built in in Django REST Framework):
    path('auth-gui/', include('rest_framework.urls')),
    # The REST authentication methods endpoint (http://django-rest-auth.readthedocs.io/en/latest/):
    path('auth-rest', include('rest_auth.urls')),
    path('auth-rest/registration', include('rest_auth.registration.urls'))
]
```
This code was based on based on https://github.com/encode/django-rest-framework/pull/5609#issuecomment-363178026. and https://stackoverflow.com/a/47689138/5433896.
I've also tried `path('', include('broker.urls', namespace='broker'))` instead of `path('', include('broker.urls', namespace='broker')),`, but then I have the same issue (see further below).

But then when I make a request to http://127.0.0.1:8000/widgets/ I get the following error:

```
Internal Server Error: /widgets/
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\broker\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\ProgramData\Anaconda3\envs\broker\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\ProgramData\Anaconda3\envs\broker\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: __init__() takes 1 positional argument but 2 were given
[08/Mar/2018 10:29:40] "GET /widgets/ HTTP/1.1" 500 63063
```

I get the same error for every URL that is mentioned in my broker/urls.py.

So up til now I've configured my URLs with:

**projectfolder/broker/urls.py**

```
from django.conf.urls import url, include

router = DefaultRouter()

router.register(r'users', views.UserViewSet)
router.register(r'dashboards', views.DashboardViewSet)
router.register(r'widgets', views.WidgetViewSet)

urlpatterns = [
    url('^', include(router.urls))
]
```

**projectfolder/Broker/urls.py**

```
from django.conf.urls import url, include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('broker.urls')),
    # The GUI's authentication endpoint (built in in Django REST Framework):
    url(r'^auth-gui/', include('rest_framework.urls')),
    # The REST authentication methods endpoint (http://django-rest-auth.readthedocs.io/en/latest/):
    url(r'^auth-rest/', include('rest_auth.urls')),
    url(r'^auth-rest/registration', include('rest_auth.registration.urls'))
]
```

And that works. I'm curious as to why the alternative doesn't work.
For the sake of completeness, I see that in my error `traceback process_exception_by_middleware` is mentioned, so I'm posting the middleware I use as well:

```
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Must come before CommonMiddleware.
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware'
]
```

And my dependency versions are:

```
name: broker
channels:
  - defaults
dependencies:
  - certifi=2018.1.18=py36_0
  - django=2.0.2=py36hd476221_0
  - pip=9.0.1=py36h226ae91_4
  - python=3.6.4=h6538335_1
  - pytz=2018.3=py36_0
  - setuptools=38.5.1=py36_0
  - vc=14=h0510ff6_3
  - vs2015_runtime=14.0.25123=3
  - wheel=0.30.0=py36h6c3ec14_1
  - wincertstore=0.2=py36h7fe50ca_0
  - pip:
    - chardet==3.0.4
    - defusedxml==0.5.0
    - django-allauth==0.35.0
    - django-cors-headers==2.1.0
    - django-rest-auth==0.9.3
    - djangorestframework==3.7.7
    - idna==2.6
    - mysqlclient==1.3.12
    - oauthlib==2.0.6
    - python3-openid==3.1.0
    - requests==2.18.4
    - requests-oauthlib==0.8.0
    - six==1.11.0
    - urllib3==1.22
prefix: C:\ProgramData\Anaconda3\envs\broker
```

**Comment by carltongibson** [comment]
@sanderzz91. 

You still need to use a router. 

This isn't right: 

```
    path('users/', views.UserViewSet, name='users'),
```

All class based views need to be routed using `as_view()`. With ViewSets there's a bit more to it, which is what routers do for you. 

None of this changes with `path`.
