### ISSUE TITLE
Readonly field doesn't raise error for invalid source parameter

### ISSUE THREAD

**Issue by kevgathuku** [encode/django-rest-framework#5813]
## Checklist

- [ ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Example project: https://github.com/kevgathuku/drf-repro

The issue is as seen in [serializers.py](https://github.com/kevgathuku/drf-repro/blob/master/docs/serializers.py#L9)
Despite this, the app runs okay and never raises an error

## Expected behavior
I expected to get an error when trying to access a non-existent field on the `source` parameter

## Actual behavior
The incorrect code fails silently and I am not made aware of the error in form of a warning or exception
I tracked it down to this location in the source code:
https://github.com/encode/django-rest-framework/blob/master/rest_framework/fields.py#L445-L446

**Comment by tomchristie** [comment]
We've equally well had folks raise an issue that `required=False` fields *shouldn't* require the field to exist, so that's the behavior we currently have. Which I think is reasonable enough.

**Comment by kevgathuku** [comment]
Hey @tomchristie thanks for the response.
I think the issue lies with handling of the `ReadOnlyField `.

For example when I set the` required` option to `True` for a `ReadOnlyField` in `serializers.py` 
e.g.
```
owner = serializers.ReadOnlyField(source='owner.this-doesn-t-esits', required=True)
```
then I get this error:
```
  File "/Users/kevin/.virtualenvs/drf-repro/lib/python3.6/site-packages/rest_framework/fields.py", line 320, in __init__
    assert not (read_only and required), NOT_READ_ONLY_REQUIRED
AssertionError: May not set both `read_only` and `required`
```

**Comment by tomchristie** [comment]
True, yup. It's a bit ambiguous.

**Comment by kevgathuku** [comment]
I agree, it is. 
So how can an invalid `source` in a `ReadOnlyField` be detected? It creeps in undetected, and that's what I hoped to address by raising the issue.
Therefore, it is still unresolved, right @tomchristie ?

**Comment by tomchristie** [comment]
Resolution: Don't use an invalid source parameter.

There's not a lot we can do about this given that the field is `required=False`, and we take that to mean that the field may or may not exist.
