### ISSUE TITLE
How to import another table's row count?

### ISSUE THREAD

**Issue by teamhide** [encode/django-rest-framework#5814]
I'm using Django Rest framework. (DB = MySQL)

I want to import another table's row count.

[article table]
- articleNo(Primary key)
- userkey
- content
- likeCount

[like table]
- articleNo(FK to article)
- userkey

For example, articleNo == 1, counting number of row in a like table and storing article table's likeCount column.

All I want to know is about "like table", particularly suitable for a certian condition that counts values in table and list it to "article table"

Can it be implemented with Rest framework?

Thanks.

p.s. As I'm a non-native English speaker, it would be very appreciated if you use plain language to help my understanding.

**Comment by rpkilby** [comment]
Hi @teamhide - the issue tracker is intended for bug reports & feature requests. If you're looking for [support](http://www.django-rest-framework.org/#support), I'd recommend either the IRC channel or discussion group.
