### ISSUE TITLE
Django DecimalField is rendered as string in json

### ISSUE THREAD

**Issue by yprez** [encode/django-rest-framework#582]
This was introduced in 2.1.16

**Comment by StErMi** [comment]
Is this bug still opened? Because I was just using DecimalField and in my JSON it's rappresented as a string.

**Comment by SalahAdDin** [comment]
Which parameter?

**Comment by ChristopherBrix** [comment]
@SalahAdDin: It's a [parameter for the DecimalField](http://www.django-rest-framework.org/api-guide/fields/#decimalfield)

**Comment by vyscond** [comment]
The `coerce_to_string` param is available to `2.3.14`?
