### ISSUE TITLE
casing incoherence javascript VS Python ?

### ISSUE THREAD

**Issue by amineparis** [encode/django-rest-framework#5820]
What if Django-rest-framework would have an option to automatically transform **python friendly snake_case attribute names** to j**son/javascript friendly camelCase attribute names** in serializers ?

**Comment by xordoquy** [comment]
This is something you can do either by altering the renderer/parser (probably my best option) or by adding a mixin and/or using an alternative base serializer.
Either way this can be done as a 3rd party.

**Comment by rpkilby** [comment]
https://github.com/vbabiy/djangorestframework-camel-case
