### ISSUE TITLE
enable django model properties (calculated fields) when fields='__all__' for model serializers

### ISSUE THREAD

**Issue by amineparis** [encode/django-rest-framework#5822]
this way we don't need to mention all fields just because we need to serialize a new calculated field

**Comment by xordoquy** [comment]
This is something you can do either by altering the renderer/parser (probably my best option) or by adding a mixin and/or using an alternative base serializer.
Either way this can be done as a 3rd party.

**Comment by xordoquy** [comment]
wooots, wrong issue, sorry.

**Comment by rpkilby** [comment]
This is a continuation of #5797.

The purpose of `Meta.fields` is to generate serializer fields from model fields. The resulting serializer fields are configured based on the attributes of the associated model field. For example, the field's type, whether or not it should be required, if null values are allowable, etc.. This is not possible with properties, as they do not have these attributes.

**Comment by amineparis** [comment]
Consider it` read_only`, as I do manually each time I add model property

**Comment by tomchristie** [comment]
You'll need to specify them explicitly on the serializer, as we have no way of automagically determining what type they should be serialized with.

**Comment by amineparis** [comment]
@tomchristie  Ok, this way we need extra_fields meta attribute that behaves the same as exclude to mention only additional fields instead of listing all just because we have on new property to include

**Comment by xordoquy** [comment]
This is unlikely to go to core but you can make it a third party possibly through a mixin. Should be possible through by overriding `get_field_names`.

**Comment by amineparis** [comment]
May I please know why it is unlikely to go to core ?

**Comment by xordoquy** [comment]
Because you already have options that cover this use case such as
- explicitly list the fields - yes, it's a good one that prevent some fields to leak.
- override the `get_field_names`

If we go down the road of adding parameters, we'll end up with a lot of options that will make DRF hard to maintain, hard to customize, hard to learn.
Easy and simple are two different things and we target the latter.

**Comment by xordoquy** [comment]
To be honest, I'm +1 on removing exclude based on security reasons.

**Comment by rpkilby** [comment]
> It looks strange however to have exclude to ignore fields and do not have an equivalent to add fields.

- `Meta.fields = '__all__'`: generate serializer fields for *all* of the model's fields
- `Meta.fields = [...]`: generate serializer fields for the model's fields in this list
- `Meta.exclude = [...]`: generates serializer fields for all of the model's fields except for those in this list

**Comment by amineparis** [comment]
OK. Thnak you, your choice seems wise
