### ISSUE TITLE
URL Parameters not getting passed from path to get_queryset()

### ISSUE THREAD

**Issue by colindjk** [encode/django-rest-framework#5824]
When using ModelViewSet, URL parameters are not being handled correctly. 

## Steps to reproduce
```python
# In my views.py
class ExampleView(viewsets.ModelViewSet):
    serializer_class = serializers.ExampleSerializer

    def get_queryset(self, fid=-1):
        print(fid)

# In my urls.py file
path('examples/<int:fid>/', views.ExampleView.as_view(actions={'get': 'list'}))
```

If I do not include `fid` as a positional argument, the request will result in an error, claiming it must be included in the `get_queryset()` method. However, if I pass a value into the URL as part of a request, for example, to:
```
localhost/examples/2/
```
## Expected behavior
prints `2`
## Actual behavior
prints `-1`

Then the value that is printed out will be `-1` instead of `2`. Not sure what I could be doing wrong, in the mean time, `GET` parameters could be used instead, as a workaround. 

## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

**Comment by colindjk** [comment]
Forgot to mention, I'm on `python 3.5.4` and `djangorestframework==3.7.7`.

**Comment by xordoquy** [comment]
`get_queryset` [doesn't accept arguments](https://github.com/encode/django-rest-framework/blob/cdb8a3c3c86bbb74f17f8880c52000602b015ed4/rest_framework/generics.py#L50).
What you are likely looking after may be [`lookup_url_kwarg`](http://www.django-rest-framework.org/api-guide/generic-views/#attributes)

**Comment by colindjk** [comment]
Interesting, not sure why but if I took out the kwarg fid without removing <int:fid> from the URL, an error was triggered. 
Not having that issue anymore though, sorry for the inconvenience.

**Comment by blueskaie** [comment]
def get_queryset(self):
   print(self.request.query_params.get(fid, -1))

# In my views.py
class ExampleView(viewsets.ModelViewSet):
    serializer_class = serializers.ExampleSerializer

    def get_queryset(self):
        print(self.request.query_params.get(fid, -1))

# In my urls.py file
path('examples', views.ExampleView.as_view(actions={'get': 'list'}))

localhost/examples?fid=2


Please try in this way
