### ISSUE TITLE
No way to document the type of dynamic Fields

### ISSUE THREAD

**Issue by leiserfg** [encode/django-rest-framework#5825]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

There is not a way of specify the type of calculated fields aka serializers.SerializerMethodField(), that's way you can't properly document the api.

**Comment by rpkilby** [comment]
Have you tried inheriting both `SerializerMethodField` and a typed field, such as `CharField`?

**Comment by tomchristie** [comment]
I’d consider this a constraint if the automated docs generation, which simply isn’t able to automatically handle all types of cases. I’d suggest explicitly writing an OpenAPI schema or similar in those cases.
