### ISSUE TITLE
Remove circular references in `parser_context` and `renderer_context`.

### ISSUE THREAD

**Issue by zubchick** [encode/django-rest-framework#5826]
I found a memory leak in APIView code caused by circular references.

## Minimal working example :
(tested with python2.7 and rest-framework from master)
### **app.py**
```python
#!/usr/bin/env python
import sys

from django.conf.urls import url

from rest_framework.views import APIView
from rest_framework.response import Response


class AnonymousUser(object):
    pass


class MemoryLeakView(APIView):
    def post(self, request, **kwargs):
        self._20_megabyte = "0123456789abcdef" * 64 * 1024 * 20
        return Response({'a': 'done'})


urlpatterns = [
    url(r'^memory-leak/$', MemoryLeakView.as_view()),
]


if __name__ == "__main__":
    from django.core.management import execute_from_command_line
    execute_from_command_line([sys.argv[0], 'runserver'])
```
### **settings.py**
```python
DEBUG = True
MIDDLEWARE_CLASSES = []
INSTALLED_APPS = ['rest_framework', 'app']
ROOT_URLCONF = 'app'

REST_FRAMEWORK = {
    'UNAUTHENTICATED_USER': 'app.AnonymousUser',
}
SECRET_KEY = '123'
```

## Expected behavior
The same amount of memory before and after POST request.

## Actual behavior
Every request `curl -i -XPOST 'http://127.0.0.1:8000/memory-leak/'` adds ~20Mb to memory usage of the process.

## The cause
The couse of the problem is circular references from `APIView` to `Request` and back (and from `APIView` to `Response` and back). All these objects (and many others) remain in memory as a garbage, not collected by gc for certain reasons.

* Reference from `APIView` to `request` [here](https://github.com/encode/django-rest-framework/blob/d1c92c81ff86fb8c6e9ccf2b394852595ff52141/rest_framework/views.py#L467), then [back](https://github.com/encode/django-rest-framework/blob/d1c92c81ff86fb8c6e9ccf2b394852595ff52141/rest_framework/views.py#L370) through [parser_context](https://github.com/encode/django-rest-framework/blob/d1c92c81ff86fb8c6e9ccf2b394852595ff52141/rest_framework/views.py#L190).
* Reference from `APIView` to `response` [here](https://github.com/encode/django-rest-framework/blob/d1c92c81ff86fb8c6e9ccf2b394852595ff52141/rest_framework/views.py#L485), then [back](https://github.com/encode/django-rest-framework/blob/d1c92c81ff86fb8c6e9ccf2b394852595ff52141/rest_framework/views.py#L410) through [renderer_context](https://github.com/encode/django-rest-framework/blob/d1c92c81ff86fb8c6e9ccf2b394852595ff52141/rest_framework/views.py#L203).

## Ideas
The first idea I had was to wrap context references with `weakref.proxy` [here](https://github.com/encode/django-rest-framework/blob/d1c92c81ff86fb8c6e9ccf2b394852595ff52141/rest_framework/views.py#L190), [here](https://github.com/encode/django-rest-framework/blob/d1c92c81ff86fb8c6e9ccf2b394852595ff52141/rest_framework/views.py#L203), and [here](https://github.com/encode/django-rest-framework/blob/d1c92c81ff86fb8c6e9ccf2b394852595ff52141/rest_framework/views.py#L215).
This fixes the issue (I've tested), but because of questionable design decisions, view references are sometimes used after the view destruction (for example `response.render()` internally calls `get_default_renderer` that expects `view`). So it could not be a sufficient solution.

A proper way to fix this is to change `get_*context` functions and return only objects are needed to request and response, without the whole view.

**Comment by tomchristie** [comment]
My understanding here is that the references will get cleaned up, but you're just not able to determine exactly when. I'd be happy to consider pull requests to remove the use of circular references, to ensure more consistent GC behaviour, which I think would be beneficial.

> A proper way to fix this is to change get_*context functions and return only objects are needed to request and response, without the whole view.

We can't easily determine within the view what context will be needed. I'm not overly keen on including the `view` reference in there, but we do need it for eg. the browsable API renderer.

I'll take any actionable PRs towards reducing circular references, but in it's current state there's nothing obvious for us to do here.

> view references are sometimes used after the view destruction

I'm not sure what you mean. We're still within the request/response cycle. There's no view "destruction".

**Comment by tomchristie** [comment]
Retitled.

**Comment by xordoquy** [comment]
Related interesting reading: https://medium.com/@chipiga86/circular-references-without-memory-leaks-and-destruction-of-objects-in-python-43da57915b8d

**Comment by xordoquy** [comment]
Might be worth adding the weakref in the `get_parser_context` / `get_renderer_context`

**Comment by xordoquy** [comment]
and preliminary tests seems to show it's improving a lot.

**Comment by zubchick** [comment]
> Might be worth adding the weakref in the get_parser_context / get_renderer_context

I already tried:

> The first idea I had was to wrap context references with weakref.proxy here, here, and here.
This fixes the issue (I've tested), but because of questionable design decisions, view references are sometimes used after the view destruction (for example response.render() internally calls get_default_renderer that expects view). So it could not be a sufficient solution.

> I'm not sure what you mean. We're still within the request/response cycle. There's no view "destruction".
Please, see the test for example: https://github.com/encode/django-rest-framework/blob/d71bd57b645190cf3edb8772f8886272c30c2a6b/tests/test_renderers.py#L678

**Comment by zubchick** [comment]
> My understanding here is that the references will get cleaned up, but you're just not able to determine exactly when.

Sometimes it's not :) Like in this case.

**Comment by axnsan12** [comment]
This doesn't seem to be a problem in python 3:

## app.py

```python
...
class MemoryLeakView(APIView):
    ...

    def get(self, request, **kwargs):
        import gc
        gc.collect()
        return Response(gc.garbage)
...
```

## Testing
```console
$ ps -C python u
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root   2132  0.5  2.8 238964 29176 pts/0    S+   14:03   0:00 python ./manage.py runserver
root   2136  5.5 15.2 457492 155124 pts/0   Sl+  14:03   0:07 /root/circref/venv/bin/python ./manage.py runserver
$ for i in {0..100}; do curl -s -i -XPOST 'http://127.0.0.1:8000/memory-leak/' > /dev/null; done
$ ps -C python u
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root   2132  0.4  2.8 238964 29176 pts/0    S+   14:03   0:00 python ./manage.py runserver
root   2136  6.4 43.4 785172 441864 pts/0   Sl+  14:03   0:09 /root/circref/venv/bin/python ./manage.py runserver
$ curl 'http://127.0.0.1:8000/memory-leak/'
[]
$ ps -C python u
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root   2132  0.4  2.8 238964 29176 pts/0    S+   14:03   0:00 python ./manage.py runserver
root   2136  6.4 15.2 457492 155124 pts/0   Sl+  14:03   0:09 /root/circref/venv/bin/python ./manage.py runserver
$ for i in {0..100}; do curl -s -i -XPOST 'http://127.0.0.1:8000/memory-leak/' > /dev/null; done
$ ps -C python u
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root   2132  0.4  2.8 238964 29176 pts/0    S+   14:03   0:00 python ./manage.py runserver
root   2136  7.9 43.4 785172 441864 pts/0   Sl+  14:03   0:13 /root/circref/venv/bin/python ./manage.py runserver
$ curl 'http://127.0.0.1:8000/memory-leak/'
[]
$ ps -C python u
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root   2132  0.3  2.8 238964 29176 pts/0    S+   14:03   0:00 python ./manage.py runserver
root   2136  7.8 15.2 457492 155124 pts/0   Sl+  14:03   0:13 /root/circref/venv/bin/python ./manage.py runserver
```

**Comment by xordoquy** [comment]
> The first idea I had was to wrap context references with weakref.proxy here, here, and here.
This fixes the issue (I've tested), but because of questionable design decisions, view references are sometimes used after the view destruction (for example response.render() internally calls get_default_renderer that expects view). So it could not be a sufficient solution.

I'd rather use a `weakref.ref` rather than `weakref.proxy` 
I need to see how and when the response is rendered. I though that was before the view returned from dispatch but I'm not sure because it is not obvious.

**Comment by tomchristie** [comment]
> Sometimes it's not :) Like in this case.

I'm just going to reiterate that there's *no* indication of a memory leak, just that circular references make it less clear when the objects will be reclaimed.

Django core also uses references to the view in `TemplateView` (`get_context_data` includes it in the `TemplateResponse`.)

In favour of *concrete* PRs towards reducing circular references? Sure.
In favour of "circular references exist, this is a bug." Nope.

I'm going to close this off. PRs reducing occurrences of circular references will be considered on their own merits.

**Comment by zubchick** [comment]
>  no indication of a memory leak
okay.jpg  Say it to my production deployment

**Comment by tomchristie** [comment]
> Say it to my production deployment

The exact same code is running on *any* Django project using TemplateView or using REST framework. That's probably 50%+ of all deployed projects.

> Every request curl -i -XPOST 'http://127.0.0.1:8000/memory-leak/' adds ~20Mb to memory usage of the process.

Running this with 200Mb, Python 2.7 I can see the memory rise to 1GB, then fall again, and hover around that figure. On different systems I'd expect you to see the GC kicking in at different points.
