### ISSUE TITLE
BrowsableAPI CSRF Errors with Auto-Generated Forms and SessionAuthentication

### ISSUE THREAD

**Issue by Jaredn** [encode/django-rest-framework#5829]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Use the Browsable API with TokenAuthentication and SessionAuthentication.  This problem explicitly occurs with SessionAuthentication though.

## Expected behavior
Forms automatically generated in the BrowsableAPI will have a CSRF Token generated along with them, such that when the form is submitted, the CSRF Token is provided and thus the form is accepted.

## Actual behavior
CSRF Token is NOT generated when using the BrowsableAPIRenderer and attempting to edit an object with the auto-generated form (PUT / PATCH) results in CSRF Token Not Provided errors.

## My Own Thoughts
Django 1.11.5
DRF 3.6.4

I have found a number of issues over the years that seem to state this all as true, but I can't seem to find a solution for it.  Examples:
https://github.com/encode/django-rest-framework/issues/2815 - Seems to have the same problem, tries a code fix but doesn't get merged.
https://github.com/encode/django-rest-framework/issues/4113 - I commented here as well, but someone else that seems to have the same problem.  Tom Christie also responded here.
https://groups.google.com/forum/#!topic/django-rest-framework/j7Zi0BkMYc8 - Great Response from Tom again, but seems to talk mostly about AJAX, and I'm just using DRF's built-in BrowsableAPIRenderer

This project in particular is a few years old that I'm working on, and I could have sworn this used to work in the past.  Somewhere along the line though, it seems that this functionality just stopped working and we started getting CSRF errors.  I'm like 99% sure that the CSRF Token should be in the <form> tags when the form gets auto-generated, but it's just not there when I inspect the HTML source.

Note - that the API itself works fine when using an API Token (TokenAuthentication) which is how we use this API internally for real.  But in our dev/staging environments it would be great to have the browsable API Forms be functional.

I'd love to get some feedback on potential issues, but I'm at a loss on where to go from here.  I'm willing to provide settings/details if anyone is willing to help me troubleshoot.

**Comment by carltongibson** [comment]
Hi @Jaredn. 

As it stands, your Steps to Reproduce aren't clear enough. "Use the Browsable API" — only SessionAuth is applicable here, since browsers can't send Tokens. 

OK, so I'm looking at a Browsable API endpoint, and submitting forms and all works. i.e. I can't reproduce this from the description. 

Any chance you could `startproject` to create a minimal test project demonstrating the behaviour, from `master`, or the latest 3.7.7 release? 

Doing that, either you'll pin it down or you'll work out where the issue is in your project. 

Short of more steps I'm not sure what I can say that would help. (Sorry I can't say more.) 

I'm going to close this as is, but I'm very happy to re-open if you can provide a reproduce. Thanks.
