### ISSUE TITLE
No exception to raise (django-rest-framework/rest_framework/views.py Line 454)

### ISSUE THREAD

**Issue by 0xfib** [encode/django-rest-framework#5831]
https://github.com/encode/django-rest-framework/blob/2854679f563252f3ad398133bf16159049a4f0b3/rest_framework/views.py#L454

**Comment by rpkilby** [comment]
`raise_uncaught_exception` is called from within this exception block via `handle_exception`. 

https://github.com/encode/django-rest-framework/blob/2854679f563252f3ad398133bf16159049a4f0b3/rest_framework/views.py#L482-L483

The bare `raise` should be reraising the original exception, although we should probably `raise exc` instead.

**Comment by tomchristie** [comment]
I think the bare ‘raise’ is correct here. Keeps the original traceback context.

Happy to reopen this if I’m incorrect there.
