### ISSUE TITLE
Review recommendation for JWT Authentication

### ISSUE THREAD

**Issue by dopry** [encode/django-rest-framework#5838]
I tested out https://github.com/GetBlimp/django-rest-framework-jwt based on reading through http://www.django-rest-framework.org/api-guide/authentication/. 

It doesn't seem to be well supported. It implements some sort of sliding token by default without blacklisting. It uses the 'access' token as the 'refresh' token. It's not a workflow I've found with tokens in any standards, which makes me fear that it hasn't been very well vetted for security. 

To see some more typical flows for token/claim based auth read up on the specs for OpenID Connect, SAML, or Kerberos. They all use different types of tokens, but the procedures and workflows for handling tokens are well vetted. 

I did a review of https://github.com/davesque/django-rest-framework-simplejwt. It's appears actively supported. The workflow uses separate access token and refresh tokens. It does have a sliding token option, and the docs mention it is a less secure albiet convenient approach. It also provides a blacklisting 
app. It's a much better implementation.

I think it would be good to remove mentions of https://github.com/GetBlimp/django-rest-framework-jwt, until the maintainers can start addressing issues in the queue and improve their documentation.  I think it presents a security risk to new developers who aren't really familiar with JWTs or token/claims based authentication workflows and the risks that come with them.

**Comment by carltongibson** [comment]
Hi @dopry. Could you put a PR together with your suggested changes? This will give us something concrete to review.

**Comment by Allan-Nava** [comment]
Hi @carltongibson ,

I want to use:

```
class CareerViewSet(viewsets.ModelViewSet):
    #
    authentication_classes  = (JSONWebTokenAuthentication,)
    permission_classes      = ()
    queryset                = Career.objects.all()
    serializer_class        = CareerSerializer
```
This is my serializer:
```
class CareerSerializer(serializers.ModelSerializer):
    #
    position        = PositionSerializer(read_only=True)
    category        = GroupTypeSerializer(read_only=True)
    championship    = ChampionshipSerializer(read_only=True)
    id_team         = GroupSerializer(read_only=True)
    #
    class Meta:
        model   = Career
        fields  = ('__all__')
    #
#
```

But it doesn't work, how can I implemente the JSONWebTokenAuthentication with ModelViewSet?

**Comment by Allan-Nava** [comment]
I ma trying to build custom Jsonwebtoken because I use keycloak

**Comment by mscansian** [comment]
We have also fallen in the trap of using [GetBlimp/django-rest-framework-jwt](https://github.com/GetBlimp/django-rest-framework-jwt) because of the recommendation. It looks like the project is abandoned and also it does not work with django-axes since version 4.x.x :(
