### ISSUE TITLE
authentication_classes should affect built-in documentation authentication options

### ISSUE THREAD

**Issue by w00kie** [encode/django-rest-framework#5841]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
- Set `DEFAULT_AUTHENTICATION_CLASSES` to only `rest_framework.authentication.TokenAuthentication`.
- Add the built-in API documentation routes with `public=True`

## Expected behavior
In the sidebar, at the bottom in the Authentication section, only the *none* and *token* options should be available in accordance with the `authentication_classes` parameter of the docs setup.

## Actual behavior
All authentication methods are shown although only *none* and *token* will actually work.

**Comment by carltongibson** [comment]
Yeah. This is basically hardcodes ATM: 

https://github.com/encode/django-rest-framework/blob/0da461710ad552c401a47b29b93e829ce879a696/rest_framework/templates/rest_framework/docs/sidebar.html#L26-L31

**Comment by tomchristie** [comment]
No longer relevant since we're pushing folks in the direction of third party OpenAPI docs explorers now.
