### ISSUE TITLE
serializers.ModelSerializer.create docstring

### ISSUE THREAD

**Issue by dilyanpalauzov** [encode/django-rest-framework#5842]
The docstring of `serializers.ModelSerializer.create` contain `create(**validated_data)`.  docutils states, that there is a strong start-marker because of the two asterisks, without an end-marker.  While escaping the asterisks does help, it is better to mark the sample code as such:

```diff
diff --git a/rest_framework/serializers.py b/rest_framework/serializers.py
index 3e48592..29b83c9 100644
--- a/rest_framework/serializers.py
+++ b/rest_framework/serializers.py
@@ -883,13 +883,13 @@ class ModelSerializer(Serializer):
         """
         We have a bit of extra checking around this in order to provide
         descriptive messages when something goes wrong, but this method is
-        essentially just:
+        essentially just::
 
             return ExampleModel.objects.create(**validated_data)
 
         If there are many to many fields present on the instance then they
         cannot be set until the model is instantiated, in which case the
-        implementation is like so:
+        implementation is like so::
 
             example_relationship = validated_data.pop('example_relationship')
             instance = ExampleModel.objects.create(**validated_data)
```

This comes into play, when for a Sphinx is used to generate documentation for a project, extracting the help from the docstrings with `autodoc_default_flags = ['undoc-members']`.  In this case methods without docstrings apparently inherit the docstrings from `ModelSerializer.create` and the **validated_data strong start-marker without a closing marker warning.

**Comment by carltongibson** [comment]
Django REST Framework's documentation (including docstrings) is all in Markdown, rather than RST. (You'll need to use a converter, or a different tool, or live with the warning I'm afraid.)
