### ISSUE TITLE
Timezone does not set 

### ISSUE THREAD

**Issue by ivanff** [encode/django-rest-framework#5845]
## Checklist

- [ ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [ ] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
DateTimeField
...

    def to_representation(self, value):
        if not value:
            return None

        output_format = getattr(self, 'format', api_settings.DATETIME_FORMAT)

        if output_format is None or isinstance(value, six.string_types):
            return value

        if output_format.lower() == ISO_8601:
            value = self.enforce_timezone(value)
            value = value.isoformat()
            if value.endswith('+00:00'):
                value = value[:-6] + 'Z'
            return value
        return value.strftime(output_format)
## Actual behavior

**Timezone does not set (self.enforce_timezone(value)) for non ISO_8601 formatsd**

**Comment by carltongibson** [comment]
Was fixed in #5833. (Please see item 1 of the issue template checklist.)
