### ISSUE TITLE
HyperlinkedModelSerializer fails when app_name is configured and URLs added to app.

### ISSUE THREAD

**Issue by shuckc** [encode/django-rest-framework#5850]
## Checklist

- [X] I have verified that that issue exists against the `master` branch of Django REST framework.
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [X] I have reduced the issue to the simplest possible case.
- [X] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce 
Add the now-mandatory `app_name` configuration to an app (in Django 2.0) using DRF or otherwise pass an `app_name` using the 2-tuple form of url `include(...)`. `HyperlinkedModelSerializer` will raise the following exception whilst rendering a view containing auto-generated `url` fields:

> Could not resolve URL for hyperlinked relationship using view name "XXX-detail". You may have failed to include the related model in your API, or incorrectly configured the `lookup_field` attribute on this field.

## Expected behavior
The page should render with functional URLs

## Actual behavior
Exception is raised.

Can be worked around by manually defining the `url` field on each Serializer and specifying a `view_name` kawarg which duplicates the `app_name:view_name` values. Each field referring to another object must be similarly defined manually. 

Raised following discussion on issue #5659 . PR to follow.

**Comment by shuckc** [comment]
Pull request is https://github.com/encode/django-rest-framework/pull/5851

**Comment by py2010** [comment]
https://github.com/encode/django-rest-framework/blob/master/rest_framework/utils/field_mapping.py

line 60:
    return '**%(app_label)s:**%(model_name)s-detail' % {

==========================
def get_detail_view_name(model):
    """
    Given a model class, return the view name to use for URL relationships
    that refer to instances of the model.
    """
    return '%(model_name)s-detail' % {
        'app_label': model._meta.app_label,
        'model_name': model._meta.object_name.lower()
    }
==========================
