### ISSUE TITLE
Incorrect `serializer.get_fields()[field].source` when `read_only=True`

### ISSUE THREAD

**Issue by OJFord** [encode/django-rest-framework#5852]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

```python
class SomeSerialiser(ModelSerializer):

    different_name = CharField(source='actual_name', read_only=True)

    # ...

field = SomeSerialiser().get_fields()['different_name']
print(field.__class__.__name__)
assert field.source == 'actual_name'
```

(`CharField` not significant; to match type of `actual_name`.)

## Expected behaviour

Assertion passes.

## Actual behaviour

Assertion fails, `field` is a `ReadOnlyField` with `field.source == 'different_name'`.

**Comment by OJFord** [comment]
That said, I'm trying and failing to reproduce this in a test case - not just against master but 3.7.7 (which is the version I failed to mention above) too.

When I print out `field` in the test it's not a `ReadOnlyField` as above when I see the error, but a `CharField` with the correct `source`. Any idea what I might have done (whether or not it's a bug) to make it be a `ReadOnlyField`?

**Comment by kevin-brown** [comment]
`ReadOnlyField` suggests that you may be using the `ReadOnlyField` class directly instead of `CharField`. This is recommended in a few places within the docs, but as far as I can tell we do not automatically create this field within the code base.

Note that a `CharField(read_only=True)` appears to be different from a `ReadOnlyField()`.

**Comment by OJFord** [comment]
It's definitely `CharField(read_only=True)` I'm doing.

**Comment by eshwaric** [comment]
I tired to reproduce this issue in a django app with djangorestframwork=3.7.7, django=1.11 and python2.7 with an intention of writing a test case, but with no success. Is that config correct for reproducing the issue.

**Comment by xordoquy** [comment]
Closing this as I can not reproduce either.

```
class Company(serializers.HyperlinkedModelSerializer):
    othername = serializers.CharField(read_only=True, source='name')

In [8]: field  = Company().get_fields()['othername']
In [11]: field.source
Out[11]: 'name'
```
