### ISSUE TITLE
Allow custom model.manager for ModelSerializer

### ISSUE THREAD

**Issue by tonythomas01** [encode/django-rest-framework#5853]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Suppose you have multiple model managers on class B, a FKey relation on class A to class B like: 
```
    b_data = BSerializer(many=False)
``` 
 
## Expected behavior
Without editing the models.py by defining a default, this should be possible from the serializer point of view.
## Actual behavior
DRF by default selects the `default_manager`

**Comment by carltongibson** [comment]
Hi @tonythomas01. I'm sorry I'm not following your use-case here. Can you explain more fully? 

(I'm going to close this as is, on the basis that I've never bumped into a problem here but I'm happy to re-open if we can pin it down to a concrete issue.)

**Comment by momen7899** [comment]
Let me explain the problem I faced myself.
I have 2 managers in my model and I use this model in 2 APIs. Now I want to use one of these managers in each of the APIs.
Because I use my model as nested, I cannot specify which one of the managers to use in the view, and I need to do this in my nested serializer.
How can I do it?
