### ISSUE TITLE
serializer depth makes fields ignored on create

### ISSUE THREAD

**Issue by sam-moshenko** [encode/django-rest-framework#5856]
## Steps to reproduce
[You can install the project from github](https://github.com/sam-moshenko/drf_depth_problem)
[Also this question is duplicated on stackoverflow.](https://stackoverflow.com/questions/49058931/drf-serializer-depth-makes-fields-ignored-on-create)
## Expected behavior
On post `/answer/` create `Answer` and return the object with `question` field being not `pk` but actual `Question` object.
## Actual behavior
`NOT NULL constraint failed: forum_answer.question_id`

**Comment by xordoquy** [comment]
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!

**Comment by TaPO4eg3D** [comment]
I have the same problem but this issue is still not answered. Any updates about that?

**Comment by rpkilby** [comment]
Hi @TaPO4eg3D. This is answered in the SO question above.
