### ISSUE TITLE
A tuple index out of range is raised if the value of the ordering attribute is an empty list

### ISSUE THREAD

**Issue by Alexgmin** [encode/django-rest-framework#5861]
## Checklist

- [X] I have verified that that issue exists against the `master` branch of Django REST framework.
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [X] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [X] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

1. On an APIView with ordering using rest_framework.OrderingFilter, set the value of the attribute of the view "ordering" to an empty list or tuple:
```python
class Foo(generics.ListAPIView):
    filter_backends = (
        filters.OrderingFilter,
    )
    
    ordering = ()
```
## Expected behavior
Everything works the same as if the value of ordering was `None`.

## Actual behavior
A `tuple index out of range` is raised at https://github.com/encode/django-rest-framework/blob/d2994e0596c3163ac970b29dad6a61485f938045/rest_framework/filters.py#L245

I understand that is not on the documentation, however, since other filter attributes, like `search_fields`, `filter_fields` and `ordering_fields` work with an empty list as the value, it makes sense for this to also work with an empty list.

**Comment by carltongibson** [comment]
Hi @Alexgmin. I would take a patch covering this edge-case, but my first thought is "Don't hold it that way" — don't apply `OrderingFilter` with an empty `ordering`... 

Would you be prepared to put together a PR for this? If so it would be warmly received.

**Comment by Alexgmin** [comment]
Sure, I'll see if I can have some time to do it.

**Comment by shaohaojiecoder** [comment]
Can I do it?

**Comment by Alexgmin** [comment]
Of course!

On 20 Mar 2018 06:50, "shaohaojei" <notifications@github.com> wrote:

Can I do it?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/encode/django-rest-framework/issues/5861#issuecomment-374484095>,
or mute the thread
