### ISSUE TITLE
new filter - search by field

### ISSUE THREAD

**Issue by ozbarshalom** [encode/django-rest-framework#5862]
Many times users use search per column in a data table, for example:
![image](https://user-images.githubusercontent.com/12782508/37078078-67b94390-21e6-11e8-9ada-018f38c4c5ad.png)

the current SearchFilter is not usefull that case because it perform search over all allowed fields in the view, in this case - there is need to allow the user choose the fields he would like to search for

The query should look like that:
?search__name=a&search__age=1

The query should support a nested query

**Comment by tomchristie** [comment]
Closing as per #5863.
This'd be great as a third party package. We'd happily link to it in the documentation here - http://www.django-rest-framework.org/api-guide/filtering/#third-party-packages
