### ISSUE TITLE
CSRF Failed in token authentication, order of DEFAULT_AUTHENTICATION_CLASSES matters?

### ISSUE THREAD

**Issue by zetaab** [encode/django-rest-framework#5865]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

use following settings in django rest framework
```
REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
  'DEFAULT_RENDERER_CLASSES': (
    'rest_framework.renderers.JSONRenderer',
    #'rest_framework.renderers.XMLRenderer',
    #'rest_framework.renderers.BrowsableAPIRenderer',
  ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    )
} 
```

## Expected behavior

Excepted behavior is that token authentication does not ask for CSRF and does not create sessionid cookies.

## Actual behavior

```
curl -XPOST http://localhost:8000/api/1.0/massgenerate -H 'Authorization: Token xxxx' -v
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8000 (#0)
> POST /api/1.0/massgenerate HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.54.0
> Accept: */*
> Authorization: Token xxxx
>
< HTTP/1.1 403 Forbidden
< Date: Wed, 07 Mar 2018 12:18:20 GMT
< Server: WSGIServer/0.2 CPython/3.6.2
< Content-Type: application/json
< Allow: POST, OPTIONS
< X-debug-data-url: http://localhost:8000/__debug__/data/1520425100.500494/
< X-Frame-Options: SAMEORIGIN
< Vary: Accept-Language, Cookie
< Content-Language: en
< Content-Length: 46
< X-Sentry-ID: cf2146eeb25749de91b9274aea39d43d
< Set-Cookie:  sessionid=4cmdher7gxx8nkxxxh2vhxbgoc; expires=Wed, 06-Mar-2019 12:18:20 GMT; HttpOnly; Max-Age=31449600; Path=/
<
* Connection #0 to host localhost left intact
{"detail":"CSRF Failed: CSRF cookie not set."}


curl -XPOST http://localhost:8000/api/1.0/massgenerate -H 'Authorization: token xxxx' -v
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8000 (#0)
> POST /api/1.0/massgenerate HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.54.0
> Accept: */*
> Authorization: token c889931460f1137e064fa98abca6bf4addf27bc5
>
< HTTP/1.1 400 Bad Request
< Date: Wed, 07 Mar 2018 12:18:32 GMT
< Server: WSGIServer/0.2 CPython/3.6.2
< Content-Type: application/json
< Allow: POST, OPTIONS
< X-debug-data-url: http://localhost:8000/__debug__/data/1520425112.421431/
< X-Frame-Options: SAMEORIGIN
< Vary: Accept-Language, Cookie
< Content-Language: en
< Content-Length: 74
< X-Sentry-ID: 44e6361575d742789546d68e93a425a6
<
* Connection #0 to host localhost left intact
{"link":["This field is required."],"targets":["This field is required."]}
```

Like you can see if I write `Token` it asks for CSRF, and if I use lowercase `token` it works as should.

However, if I change order of `DEFAULT_AUTHENTICATION_CLASSES`
```
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    )
```

It works as should:

```
% curl -XPOST http://localhost:8000/api/1.0/massgenerate -H 'Authorization: token xxxx' -v
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8000 (#0)
> POST /api/1.0/massgenerate HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.54.0
> Accept: */*
> Authorization: token xxxx
>
< HTTP/1.1 400 Bad Request
< Date: Wed, 07 Mar 2018 12:21:14 GMT
< Server: WSGIServer/0.2 CPython/3.6.2
< Content-Type: application/json
< Allow: POST, OPTIONS
< X-debug-data-url: http://localhost:8000/__debug__/data/1520425273.703460/
< X-Frame-Options: SAMEORIGIN
< Vary: Accept-Language, Cookie
< Content-Language: en
< Content-Length: 74
< X-Sentry-ID: 58f2389d15554586abd89dc156020872
<
* Connection #0 to host localhost left intact
{"link":["This field is required."],"targets":["This field is required."]}%                                                                                                 
% curl -XPOST http://localhost:8000/api/1.0/massgenerate -H 'Authorization: Token xxxx' -v
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8000 (#0)
> POST /api/1.0/massgenerate HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.54.0
> Accept: */*
> Authorization: Token xxxx
>
< HTTP/1.1 400 Bad Request
< Date: Wed, 07 Mar 2018 12:21:16 GMT
< Server: WSGIServer/0.2 CPython/3.6.2
< Content-Type: application/json
< Allow: POST, OPTIONS
< X-debug-data-url: http://localhost:8000/__debug__/data/1520425276.774616/
< X-Frame-Options: SAMEORIGIN
< Vary: Accept-Language, Cookie
< Content-Language: en
< Content-Length: 74
< X-Sentry-ID: 43d82f17e3724ea2944b41ca85c3247c
< Set-Cookie:  sessionid=e6n9s1rtpmxxxd5clfh6yahvfnbk; expires=Wed, 06-Mar-2019 12:21:16 GMT; HttpOnly; Max-Age=31449600; Path=/
<
* Connection #0 to host localhost left intact
{"link":["This field is required."],"targets":["This field is required."]}
```

So two questions:
1. should order of these authentication classes matter? Looks like so? Is this bug?
2. why token authentication in both cases is creating sessionid, if `Token` is written in camelcase. Is this bug? It is not created if `token` is used

djangorestframework==3.7.7
Django==2.0

**Comment by xordoquy** [comment]
> should order of these authentication classes matter? Looks like so? Is this bug?

http://www.django-rest-framework.org/api-guide/authentication/#how-authentication-is-determined
http://www.django-rest-framework.org/api-guide/authentication/#unauthorized-and-forbidden-responses

> why token authentication in both cases is creating sessionid, if Token is written in camelcase. Is this bug?

That's how the Django's session middleware works.

**Comment by kingbuzzman** [comment]
@xordoquy do you see some benefit in trying all the backends, and if any of them fail, ignore it, continue on to the next one, if they all fail, return your 401, otherwise auth the user.

example: 
https://github.com/encode/django-rest-framework/blob/master/rest_framework/request.py#L368

My issue is i have multiple backends that will either use jwt, django restframework token, and/or custom aws auth. All of them use the `Authorize: bearer ...` header, if any of them fail, i cant auth the request.

_this may be the wrong place to ask, apologies_

**Comment by xordoquy** [comment]
@kingbuzzman missing context, I don't get your point / question.
OP's issue is that session authentication doesn't play nice with other auth scheme. User was logged with session - though it also had token - and thus was getting a CSRF issue because it was going through session auth.

**Comment by kingbuzzman** [comment]
@xordoquy yes this is unrelated to OP's issue.

This is me looking for an issue that remotely had the keywords i was looking for "DEFAULT_AUTHENTICATION_CLASSES" and me trying to steer the conversation.

----

The way that DRF does auth, essentially breaks if there are multiple auths that look at the same variable ("Authorization" in the case).

Lets say we have these auth classes in DEFAULT_AUTHENTICATION_CLASSES:
something.JWTAuth
something.TokenAuth
something.AWSAuth

if i send `Authorization: bearer ..somejwt..` -- it will work, since its the first one and its valid, cool!
if i send `Authorization: bearer ..some.django.Token..` -- it will not work, since when jwt tries to json load the value it throws an error. Now i can patch this on myside, since this is mine. I pass None, and it continues to the second authorizer, and `something.TokenAuth` accepts it. cool.
if i send `Authorization: bearer ..some.aws.token..` -- it will not work, since when jwt tries to json load the value it throws an error. Now i can patch this on myside, since this is mine. I pass None, and it continues to the second authorizer, `something.TokenAuth` will throw an error since its not valid, and will never go on to my next authorizer

**Comment by carltongibson** [comment]
@kingbuzzman The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion. Thanks!
