### ISSUE TITLE
Flat list of values in nested serializers

### ISSUE THREAD

**Issue by kishorpawar** [encode/django-rest-framework#5866]
Say I have serializers as below.  

    class AbcSerializer(serializers.ModelSerializer):
    	class Meta:
    		model = Abc
    		fields = ('a',) # there could be other fields too in model.
    
    
    class XyzSerializer(serializers.ModelSerializer):
    
    	a = AbcSerializer(many=True)
        class Meta:
            model = Xyz
            fields = '__all__'  

this gives me list of dictionaries like 

    [{a: 1}, {a: 2}]  

is there any parameter like `flat=True`, which would give me a flat list like  

    [1, 2]

**Comment by xordoquy** [comment]
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!

**Comment by mattxs** [comment]
So where's the solution?
