### ISSUE TITLE
Inappropriate Default Style will be set for ChoiceField when Instantiating ModelSerializers.

### ISSUE THREAD

**Issue by Asayu123** [encode/django-rest-framework#5868]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

1. Define a ModelSerializer with a model that contains TextField with choices.
```python
from django.db import models
from rest_framework.serializers import ModelSerializer

# Model Definition
class Network(models.Model):
    name = models.TextField()
    description = models.TextField(blank=True)
    status = models.TextField(choices=(('active', 'active'), ('inactive', 'inactive')))
    ... 
# Serializer Definition
class NetworkSerializer(ModelSerializer):

    class Meta:
        model = Network
        fields = '__all__'
```
2. Instantiate the Serializer with data.

## Expected behavior
A instance of the Serializer has a ChoiceField named 'status' with a style: {'base_template': 'input.html'}

## Actual behavior
A instance of the Serializer has a ChoiceField named 'status' with a style: {'base_template': 'textarea.html'}

## Problem
Consequently, Django REST framework's built-in form renderer treats this attribute same as a free-descriptive text.

## Causes
As you can see, when a serializer builds standard fields, get model's field's kwargs first.

https://github.com/encode/django-rest-framework/blob/d2994e0596c3163ac970b29dad6a61485f938045/rest_framework/serializers.py#L1176

and If original field model has Textfield, style  {'base_template': 'textarea.html'} will be applied as a default field argument of the serializer.
https://github.com/encode/django-rest-framework/blob/c674687782ef96a3bb8466b412e99debd3d04f00/rest_framework/utils/field_mapping.py#L91

Then HTMLFormRenderer treats this field, it temporally applies default style "style: {'base_template': 'input.html'}"
however, this style will be overridden with {'base_template': 'textarea.html'} that has been set via serializer instantiation.
https://github.com/encode/django-rest-framework/blob/a540acdc9552bcaf704371c3e1dee216059a221e/rest_framework/renderers.py#L342

## Acknowledgements
I am not sure whether this is expected behavior or not, so I created this issue.
It looks like applying a default style in an initialization process of serializer causes this issue, so move this application to HTMLFormRender might solve this problem.

Thank you in advance :)

**Comment by tomchristie** [comment]
For that case use `CharField` and set `max_length`.
The `TextField` is for multiline, unbounded-length strings.
