### ISSUE TITLE
docs: JSON input to JSONField is not parsed correctly

### ISSUE THREAD

**Issue by beruic** [encode/django-rest-framework#5873]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
1. Create a JSONField on a serializer
2. Submit `{"a": "test"}` to the field through docs
3. Breakpoint at the return of `JSONField.to_internal_value()`

## Expected behavior
The returned data is a dictionary with a single key `a` that has a value which is string `test`.

## Actual behavior
The returned data is the string `{"a": "test"}`

**Comment by beruic** [comment]
This verified on version 3.7.7.

**Comment by beruic** [comment]
I have narrowed this down to the point where I am confident to conclude that the issue is that the `data-type` attribute is set to `string` on the input element of the `JSONField`. Setting `data-type` to `object` produce the desired behaviour. Now I just need to figure out how to do just that.

**Comment by carltongibson** [comment]
Hey @beruic. Thanks for the report. 

Sounds like this will be coming out of `coreschema`. I'm just in the process of pulling that into DRF for v3.8 now. (#5855) 

There issue will be here: 

https://github.com/core-api/python-coreschema/blob/494435d8fbaff12285094e99c54c38f5a1434afb/coreschema/encodings/html.py#L54-L74

I'll see if I can close this whilst I'm porting this to DRF.

**Comment by beruic** [comment]
You are right that this is related to `coreschema`, but the fix lies in `rest_framework.schemas.inspectors.field_to_schema()`. I have solved this just now in DRF. Expect a pull request soon.

I cannot however fix it for `DictField`, which has the same problem with input, because `coreschema.schema.Object` does not have an `items` argument for child schema like `coreschema.schema.Array` does. I think that a `coreschema.schema.Dictionary` is needed because, while `coreschema.schema.Object` has a `properties` argument, it seems to validate per key. I was considering making a feature request for `coreschema`, but if I understand you correctly, that is not going to be necessary, but we have to fix it in DRF.
Thoughts?

**Comment by beruic** [comment]
Just a quick update: It seems that `DictField` does return `coreschema.Object` in `rest_framework.schemas.inspectors.field_to_schema()`, so I may have gotten something wrong. I will see if I can get time investigating this more, but it is likely that I do not get around it again before I actually need `DictField` for something.

**Comment by beruic** [comment]
I just realized that I hadn't gotten anything wrong. `DictField` handling has been added since version 3.7.7 authored by @jlaine and committed by @carltongibson. There is no tests for this code either, and it is already in the master, so I cannot see why this PR should not be able to make it into 3.8 as well.

**Comment by beruic** [comment]
I do however see a potential bug in that the code for handling `DictField` does not handle the child schema.
