### ISSUE TITLE
Feature request: Add the posibility of raw JSON input in interact modals

### ISSUE THREAD

**Issue by beruic** [encode/django-rest-framework#5874]
Like it's possible in the normal browsable API, it would be nice to be able to simply enter JSON for input in an interact modal.

**Comment by xordoquy** [comment]
I'm missing context here. What are you referring to ?

**Comment by beruic** [comment]
When you open the normal browsable API for an object (or whatever your viewset is for), you can switch between form input and raw data. I would like this raw data input  to be available in the interact modal of docs as well.

**Comment by tomchristie** [comment]
I'm not really clear *where* the suggestion is to make a change here. Happy to *consider* changes, but let's include screenshots in any suggestions, so we can all be clear exactly what the intent is.

**Comment by tomchristie** [comment]
I assume this relates to the API docs, which is redundant at this point, since we're pointing folks towards third party OpenAPI options instead.
