### ISSUE TITLE
import error rest_framework_httpsignature.authentication django rest frame work?????????????????????????????

### ISSUE THREAD

**Issue by hemanthsp** [encode/django-rest-framework#5875]
unable to import from rest_framework_httpsignature.authentication import SignatureAuthentication in django 1.8v and python 2.7.6 ,it causeing importing error only to this class SignatureAuthentication in vs studio , please help but i can able to import this class rest_framework.authentication using djangorestframework==3.4.1

**Comment by xordoquy** [comment]
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!

**Comment by hemanthsp** [comment]
its your lib, close or open bug,do whatever you want

**Comment by rpkilby** [comment]
@hemanthsp - `rest_framework_httpsignature` is a different package. Make sure that you have installed it.
