### ISSUE TITLE
Choice Field validate the value before calling validate in serializer

### ISSUE THREAD

**Issue by peeomid** [encode/django-rest-framework#5876]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
I have a model with choice field (this is from fcm-django)
```
class FCMDevice(Device):
    DEVICE_TYPES = (
        (u'ios', u'ios'),
        (u'android', u'android'),
        (u'web', u'web')
    )

    type = models.CharField(choices=DEVICE_TYPES, max_length=10)
```

And in its serializer, I try to convert type to lower case

```
class FCMDeviceSerializer(ModelSerializer):
    class Meta(DeviceSerializerMixin.Meta):
        model = FCMDevice

    def validate_type(self, value):
        return value.lower()
```

## Expected behavior
So when I pass value "IOS", it should convert to "ios" before validating with choices.

## Actual behavior
It actually raises validation error before being validated
```
{'type': ['"IOS" is not a valid choice.']}
```

**Comment by carltongibson** [comment]
This is expected behaviour. 

https://github.com/encode/django-rest-framework/blob/0da461710ad552c401a47b29b93e829ce879a696/rest_framework/serializers.py#L461-L468

Base field-level validation is applied before the additional serialiser-level methods are called. 

Your best bet is to subclass the field and override `to_internal_value` to make the `lower()` call.

**Comment by peeomid** [comment]
Thanks a lot for such quick response @carltongibson, and thanks for pointing out the suggestion.

Just curious about this design though, as I thought serializer would be wrapper on top, before executing model level thing?
