### ISSUE TITLE
MultipleFieldLookupMixin Concrete example

### ISSUE THREAD

**Issue by Calion54** [encode/django-rest-framework#5879]
Hi

I would like this url `/set/pk1/pk2/` in the modelViewSet

So I use this [Lien](http://www.django-rest-framework.org/api-guide/generic-views/#customizing-the-generic-views) But I got a 404 because I use a simple router.

My question is : Do we have to declare a new modified router ? In the doc, it's not indicate and it's annoying if we put them in a nested view like this `/toto/pk/set/pk1/pk2/`

Example of custom router :
```
class SetRouter(SimpleRouter):
    routes = [
        Route(
            url=r'^{prefix}{trailing_slash}$',
            mapping={'get': 'list'},
            name='{basename}-list',
            initkwargs={'suffix': 'List'}
        ),
        Route(
            url=r'^{prefix}/(?P<pk1>\w+)/(?P<pk2>.+){trailing_slash}$',
            mapping={'get': 'retrieve'},
            name='{basename}-detail',
            initkwargs={'suffix': 'Detail'}
        ),
        DynamicListRoute(
            url=r'^{prefix}/{methodname}{trailing_slash}$',
            name='{basename}-{methodname}',
            initkwargs={}
        ),
        DynamicDetailRoute(
            url=r'^{prefix}/(?P<pk1>\w+)/(?P<pk2>[a-zA-Z0\[\] +]+)/{methodname}{trailing_slash}$',
            name='{basename}-{methodname}',
            initkwargs={}
        )
    ]

```

thank you,

**Comment by tomchristie** [comment]
This sort of usage question is better suited to the discussion group... https://groups.google.com/forum/m/#!forum/django-rest-framework
