### ISSUE TITLE
Python builtin `list()` redefined in ViewSet subclasses

### ISSUE THREAD

**Issue by samueldg** [encode/django-rest-framework#5884]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Description

When overwriting the `list()` method for `ViewSet` subclasses (in particular, `ModelViewSet` subclasses, or other classes inheriting from `ListModelMixin`), you end up redefining/shadowing a Python builtin: [`list()`](https://docs.python.org/3/library/functions.html#func-list).

The documentation also redefines `list` in the example for `ViewSet`s: http://www.django-rest-framework.org/api-guide/viewsets/#example

This can have some unintended side effects in the rest of the class definition, which would be really unintuitive. (See in **Steps to reproduce** for examples I found.)

It can also confuse syntax highlighters, for which the Python builtins can be considered different (actually how I realized there was an issue in the first place.)

## Steps to reproduce

An example of impacting a default kwarg:

```python
>>> class MyViewSet():
...     def list(self):
...         return('woopsie')
...     def convert_collection(self, collection, callable=list):
...         return(callable(collection))
...
>>>
>>> m = MyViewSet()
>>> m.convert_collection([1,2,3], tuple)
(1, 2, 3)
>>> m.convert_collection((1,2,3), list)
[1, 2, 3]
>>> m.convert_collection((1,2,3))
'woopsie'
```

An example of impacting a class attribute definition:

```python
>>> class MyViewSet:
...     my_list = list((1, 2, 3, 4))
...     def list(self):
...         return('woopsie')
...     my_other_list = list((1, 2, 3, 4))
...
>>> m = MyViewSet()
>>> m.my_list
[1, 2, 3, 4]
>>> m.my_other_list
'woopsie'
```

## Expected behavior

Overwriting a parent class method should not shadow a Python builtin for the rest of the code in the body of the class.

## Actual behavior

Python `list()` builtin will be shadowed by the `list()` method.

**Comment by tomchristie** [comment]
Woah. Okay, that's some surprising scoping rules there, that I've never been aware of.

The bare method name isn't visible inside any other method bodies, but it *does* scope within other method declarations or class names.

A quick search around and I couldn't find any references to anyone else noticing that this scoping could be problematic, eg. someone specifically asks about naming methods as builtins (which I also wouldn't ever have assumed could be problematic) and nobody calls this out... https://stackoverflow.com/questions/9109333/is-it-bad-practice-to-use-a-built-in-function-name-as-an-attribute-or-method-ide

I don't like it, and it clearly is broken in those circumstances, but I also think there's a high cost of change here, and that the cases in which the scoping is problematic are unlikely to occur, and the breakage would be loud and immediate.

Tending towards closing this as, "yes it'll break those cases, don't do that". Not perfect, but probably pragmatic enough.

**Comment by samueldg** [comment]
@tomchristie Thanks for the quick answer! I agree with your conclusion: these are edge cases and the cost of changing the API is not worth it.

At least now you are aware, and people can stumble on this issue if they research some weird behaviours!

For those time travellers: to work around this, you can:

* define the `list` method in an intermediate class from which you inherit, then use the `list` keyword in your derived class's body as usual; or
* reassign the `list` builtin to something else at the top of your module, e.g. `list_ = list`, then use that name in the class definition's body.

**Comment by xordoquy** [comment]
You should also note use lists as default argument to functions or methods. This is often used as a hiring test:

```
>>> def demo(a=list()):
...   a.append(1)
...   print(a)
... 
>>> demo()
[1]
>>> demo()
[1, 1]
```

So I guess yes it's a bad thing to get the name collision in any scope, but it's also a bad thing to use a list as default value.

**Comment by shaohaojiecoder** [comment]
yes,A few days ago I also read an article on the scope of variables。In Python，if use list in function ,it won't destroy the scope when it run over.

**Comment by BruOp** [comment]
@xordoquy To be clear the example shows providing `list` the _function_ as a default argument, which won't run into the issue you're highlighting.

**Comment by samueldg** [comment]
@xordoquy What you should not use for default arguments is *mutable objects* (like a dictionary, a list, etc.) (See [Using a mutable default value as an argument](https://docs.quantifiedcode.com/python-anti-patterns/correctness/mutable_default_value_as_argument.html))

Using the `list` or `dict` functions, for instance, is fine. The standard lib's documentation does this quite a lot, e.g.: https://docs.python.org/3.6/library/collections.html#defaultdict-examples

**Comment by Tenzer** [comment]
I stumbled into the same issue here, while switching a codebase to use [PEP 585](https://www.python.org/dev/peps/pep-0585/) type annotations (e.g. replacing `typing.List` with just `list`).

Would it be possible to make an alternative name for the `list` method that doesn't collide with the builtin? People who reach this problem would have an easy way to work around it (by renaming the method).
I know Beautiful Soup uses a trailing underscore in `class_` to avoid colliding with a builtin: https://www.crummy.com/software/BeautifulSoup/bs4/doc/#searching-by-css-class. Perhaps `list_` could be made as an alternative?
