### ISSUE TITLE
Dynamically change nested field queryset

### ISSUE THREAD

**Issue by sassanh** [encode/django-rest-framework#5895]
Is it possible to dynamically change queryset of a nested field based on `request.user` for example? It is possible for `PrimaryKeyRelatedField` by changing `queryset` attribute of the field in serializer's `__init__`, I need the same for a nested field.

**Comment by sassanh** [comment]
Just wanted to note that I know how to do it with `MethodField`s, but I want it to be writable.

**Comment by tomchristie** [comment]
This type of usage question is better suited to the discussion group. Thanks!
