### ISSUE TITLE
Allow guardian permission caching for content types

### ISSUE THREAD

**Issue by radyz** [encode/django-rest-framework#5896]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [ ] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
1. Configure django guardian object level permissions
2. Configure view with `DjangoObjectPermissionsFilter`
3. Create view permission for queryset

## Expected behavior
Multiple calls to list objects should cache the result of the permission content type

## Actual behavior
Multiple calls to list objects calls multiple times the database

When using guardian to filter by object permission I noticed the `DjangoObjectPermissionsFilter` class uses the shortcut function `get_objects_for_user` to get the object queryset, however in doing so, it's building the permission parameter in the form of `app_label.view_model`. When used in this manner guardian is performing a database call each time the function is called to determine the proper content type for which the permission is valid. Instead it should be using the form of `view_model` and guardian is smart to figure out where that permission belongs from the queryset parameter and under the hood uses django's contenttype manager which caches the result so further calls do not query the database.

For the time being I'm working around this issue by overriding this class and setting `perm_format = 'view_%(model_name)s' ` instead, so when passed to guardian it's in the form of 'view_model' only.

**Comment by tomchristie** [comment]
Thanks for this. I’d accept pull requests along these lines but otherwise don’t think it’s problematic enough to warrant us putting time into. If anything we should be pushing the guardian integration into a third party package in any case.
