### ISSUE TITLE
Race conditions for model serializer `update` if thrown into an async task?

### ISSUE THREAD

**Issue by tleewu** [encode/django-rest-framework#5897]
https://github.com/encode/django-rest-framework/blob/5e6abfbafebd7eed8ece110b8c32949f88e94e9d/rest_framework/serializers.py#L957

I had a question about this line. Couldn't this theoretically run into a race condition if two parallel threads called `update` on the same instance? One save would override the other save.

I wonder if a solution like this would prevent this from happening as often.

```
    def update(self, instance, validated_data):
        raise_errors_on_nested_writes('update', self, validated_data)
        info = model_meta.get_field_info(instance)
        update_fields = []

        # Simply set each attribute on the instance, and then save it.
        # Note that unlike `.create()` we don't need to treat many-to-many
        # relationships as being a special case. During updates we already
        # have an instance pk for the relationships to be associated with.

        for attr, value in validated_data.items():
            update_fields.append(attr)
            if attr in info.relations and info.relations[attr].to_many:
                field = getattr(instance, attr)
                field.set(value)
            else:
                setattr(instance, attr, value)
        instance.save(update_fields=update_fields)

        return instance
```

**Comment by xordoquy** [comment]
> I had a question about this line. Couldn't this theoretically run into a race condition if two parallel threads called update on the same instance? One save would override the other save.

Yes it could. That's an interesting point. I was about to close it as "it's the developer work" but I need to think about it more.

**Comment by tomchristie** [comment]
Different threads won’t have the same instance. It’ll be a different object-in-memory in each case.

**Comment by tleewu** [comment]
@tomchristie how about for async tasks? 

Also, if I'm updating only a few properties, why am I saving every property for the entire instance?

**Comment by tomchristie** [comment]
See https://github.com/encode/django-rest-framework/issues/2648 and #4675.

I misunderstood your query slightly, in that there is a concurrency issue wrt PATCH requests. (But it’s not about threads or async - these could be updates on two entirely different server instances)

**Comment by felipeota** [comment]
I run into this issue on a project I am working on. I have two concurrent PATCH requests on the same model that can run almost at the same time and sometimes one overwrites fields of the other with values loaded from the db beforehand. Fixed with @tleewu solution.
