### ISSUE TITLE
DjangoModelPermissions - AssertionError - not set '.queryset'

### ISSUE THREAD

**Issue by nikolasbrandao** [encode/django-rest-framework#5901]
## Problem

Hello, i'm trying to add DjangoModelPermissions in my project, permission IsAuthenticated worked but  
DjangoModelPermissions i get the following error message:

AssertionError at /api/v01/root/empresas
Cannot apply DjangoModelPermissions on a view that does not set `.queryset` or have a `.get_queryset()` method.

Django version 2.0.3
DRF version 3.7.7
## My ViewSet

`from django.shortcuts import render
from rest_framework.renderers import JSONRenderer
from rest_framework.response import Response
from rest_framework.decorators import api_view, permission_classes
from rest_framework import viewsets, status
from django.http import HttpResponse, JsonResponse
from .models import Empresa
from .serializers import EmpresaSerializer
from rest_framework.permissions import IsAuthenticated, IsAuthenticatedOrReadOnly, DjangoModelPermissions
from django.contrib.auth.models import User
from django.http import HttpResponse

class EmpresaViewSet(viewsets.ModelViewSet):
    queryset = User.objects.none()
    serializer_class = EmpresaSerializer

    def __init__(self, data, **kwargs):
        content = JSONRenderer().render(data)
        kwargs['content_type'] = 'application/json'
        super(JsonResponse, self).__init__(content, **kwargs)

    @api_view(['GET'])
    def index(request):
        return HttpResponse("Hello, world.")

    @api_view(['GET', 'POST'])
    @permission_classes((DjangoModelPermissions, ))
    def simple_empresas(request):
        if request.method == 'GET':
            empresas = Empresa.objects.all()
            serializer = EmpresaSerializer(empresas, many=True)
            return Response(serializer.data)
        elif request.method == 'POST':
            serializer = EmpresaSerializer(data=request.data)
            if serializer.is_valid():
                serializer.save()
                return Response(serializer.data, status=status.HTTP_201_CREATED)
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    @api_view(['GET', 'PUT', 'DELETE'])
    def detail_empresa(request, pk):
        try:
            empresa = Empresa.objects.get(ID=pk)
        except Empresa.DoesNotExist:
            return Response(status=status.HTTP_404_NOT_FOUND)

        if request.method == 'GET':
            serializer = EmpresaSerializer(empresa)
            return Response(serializer.data)
        elif request.method == 'PUT':
            serializer = EmpresaSerializer(empresa, data=request.data)
            if serializer.is_valid():
                serializer.save()
                return Response(serializer.data)
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
        elif request.method == 'DELETE':
            empresa.delete()
            return Response(status=status.HTTP_204_NO_CONTENT)`

## Expected behavior
I need to protect the routes, so that only authenticated users with specific permissions can modify the attributes

The documentation was not clear enough for me, I ask for help.

**Comment by xordoquy** [comment]
Hi,

The `api_view` decorator does create a `View` class behind the scene.
I have hard time reading your code sample because indentation doesn't seem correct but whether or not the `api_view` decorated functions are within the viewset or not won't change the fact that the `api_view` does not provide a `queryset`.
You probably want to use the [`list_route` / `detail_route`](http://www.django-rest-framework.org/api-guide/routers/#extra-link-and-actions) instead
