### ISSUE TITLE
Respect order of JSON keys

### ISSUE THREAD

**Issue by jcampbell05** [encode/django-rest-framework#5902]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ x This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

Implement a serializer with a serializermethodfield that returns a dictionary.

## Expected behavior

This dictionary should be serialized as is.

## Actual behavior

The dictionaries keys end up in a totally random order than the order you specify them in.

**Comment by xordoquy** [comment]
> This dictionary should be serialized as is.

Depending on your version of Python this might be true or not. For Python >= 3.6 this will [be true](https://mail.python.org/pipermail/python-dev/2016-September/146327.html).

**Comment by jcampbell05** [comment]
@xordoquy is there a way of backporting or is it just easier to upgrade to 3.6 ?

**Comment by xordoquy** [comment]
You should be able to work around it by using OrderedDict
