### ISSUE TITLE
Feature Request: Add `hidden` core argument to serializer fields 

### ISSUE THREAD

**Issue by Tiedye** [encode/django-rest-framework#5907]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.

I've often come across the case where I would like to use one serializer to serve a model to users with various access levels to that model.  For some users I'd like to hide some of the fields, and the first simple solution I can think of would be to add an optional `hidden` argument to the base serializer field that would simply have the effect of excluding that field on read (and maybe forcing the default on write).  It would also be reasonable to allow a list of functions like the `validators` argument to increase flexibility.

This could be achieved with a custom field, but it would be a backwards compatible change that I think could be widely used and having it as a core argument to every serializer seems cleaner to me.

**Comment by tomchristie** [comment]
Various existing things that might help you out here:

* HiddenField - http://www.django-rest-framework.org/api-guide/fields/#hiddenfield
* `write_only` - http://www.django-rest-framework.org/api-guide/fields/#write_only
* Dynamically modifiying serializer fields - http://www.django-rest-framework.org/api-guide/serializers/#dynamically-modifying-fields

**Comment by Tiedye** [comment]
Hello!  Before we put this one to bed, I like to make myself a little more clear.

So the purpose of this request was to add the ability to basically make a field conditional.  For example:

I have a serializer as follows (and a corresponding model that you can infer):
```python
class Invitation(serializers.Serializer):
    date: serializers.DateTimeField()
    message: serializers.TextField()
    owner: serializers.HiddenField(default=serializers.CurrentUserDefault())
    recipients: serializers.PrimaryKeyRelatedField(queryset=User.objects.all())
```
Now, I want to allow all the recipients to access the endpoint that uses this serializer to view their invitations, but I dont want them to see the other recipients, with this feature it would be simple and clear (assuming it is implemented with the same semantics as defaults an validators):
```python
class UserIsRecipient(object):
    def set_context(self, serializer_field):
        self.user = serializer_field.context['request'].user
        self.instance = serializer_field.parent.instance
    def __call__(self):
        return self.instance is None or not instance.recipients.filter(pk=self.user.pk).exists()

class Invitation(serializers.Serializer):
    date: serializers.DateTimeField()
    message: serializers.TextField()
    owner: serializers.HiddenField(default=serializers.CurrentUserDefault())
    recipients: serializers.PrimaryKeyRelatedField(hidden=UserIsRecipient(), queryset=User.objects.all())
```
TO BE CLEAR: this is not a help request, I know of various other ways to achieve this effect, but I do not believe that any of those ways would be nearly as clear and concise as adding a new core argument that allowed fields to be included or excluded dynamically.

**Comment by Tiedye** [comment]
@tomchristie Has this been received?

**Comment by tomchristie** [comment]
Sure. There’s lots of different types of dynamic behaviours developers might want. Unless there’s a very clear and obvious case for it being worth the extra complexity, then we’ll avoid it.
