### ISSUE TITLE
ValidationError(str) should default to a dict with default key NON_FIELD_ERRORS_KEY not a list

### ISSUE THREAD

**Issue by markddavidoff** [encode/django-rest-framework#5909]
Moved to issue as requested by @xordoquy in PR #5908
@xordoquy the docs specifically say otherwise 

> Validation errors are handled slightly differently, and will include the field names as the keys in the response. If the validation error was not specific to a particular field then it will use the "non_field_errors" key, or whatever string value has been set for the `NON_FIELD_ERRORS_KEY` setting.

http://www.django-rest-framework.org/api-guide/exceptions/

I expected `ValidationError("it borked")` to return a dict keyed on `NON_FIELD_ERRORS_KEY`.

**Comment by xordoquy** [comment]
This is a bit more complex than that. The quote applies to the exceptions risen during the serializer's validation process. Serializer will call [`as_serializer_error`](https://github.com/encode/django-rest-framework/blob/c2b24f83a3d552845e29b7e3d39acf50beba1b5c/rest_framework/serializers.py#L321-L344) which will deal with proper formatting.
Maybe we should make that more clear in the documentation.

**Comment by rpkilby** [comment]
@bukowa. Validation errors are specially handled only during the validation phase. The `create` method is called outside of that phase, so yes, this is expected behavior. The short answer is "don't do that." A longer answer will depend on what exactly you are trying to accomplish. I would recommend asking on the various DRF support channels.

**Comment by Allan-Nava** [comment]
> ```python
> class CustomSerializer(serializers.Serializer):
>     default_error_messages = {
>         'wrong': 'this is bad'
>     }
>     
>     def validate(self, validated_data):
>         self.fail('wrong')
>         # {"non_field_errors": ["this is bad"]}
> 
>     def create(self, validated_data):
>         self.fail('wrong')
>         # ["this is bad."]
> ```
> 
> The error message ('this is bad') is not bound into "non_field_errors" when called in "create".
> Response contains the error message in a list. When called in "validate" it works as intended binding to "non_field_errors".
> 
> It is intended?

is possible to have the response without the list like:
`# {"non_field_errors": "this is bad"}`

**Comment by rpkilby** [comment]
You most likely don't want to do this. Serializers can raise multiple non-field errors, and returning just one string would truncate the other messages.

If you did want to override this, your best bet is probably in the view's exception handler.
