### ISSUE TITLE
Please extend docs for use maximum speed code for REST + Database Stored Proc

### ISSUE THREAD

**Issue by mmmcorpsvit** [encode/django-rest-framework#5911]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [ ] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Actual behavior

please need good sample in docs

**Comment by tomchristie** [comment]
I’d recommend against stored procedures as a general rule.

**Comment by mmmcorpsvit** [comment]
why?

**Comment by mmmcorpsvit** [comment]
if my speed of execute of storedproc more that validate operations that have sense do validate AFTER execution. But this is my first experience with REST Framework)

**Comment by tomchristie** [comment]
I wouldn’t say don’t ever use them, just not as a general rule. Managing business logic in application code is far easier to deal with in application code, than in database hooks. Under some circumstances you might want to use them but I don’t think they’re appropriate to include in our docs, and there’s nothing about using them that’d be specific to rest framework.
