### ISSUE TITLE
import coreapi failure since version 3.8.0

### ISSUE THREAD

**Issue by gsvr** [encode/django-rest-framework#5918]
## Checklist
- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Install django 2.0 with latest version of django-rest-framework via pip, and activate in settings.py
Try to open a shell and/or do:
`from rest_framework.authtoken import views`

## Expected behavior
Should just load the views module.

## Actual behavior
`ModuleNotFoundError: No module named 'coreapi'`

## Suggested fix
It seems like the `coreapi` module should no longer be optional, but should be a dependency that installs with a pip install -
https://github.com/encode/django-rest-framework/blob/2709de1310f35dda97fad28ccf555878f5646b17/requirements/requirements-optionals.txt#L7

**Comment by DEKHTIARJonathan** [comment]
i have the same issue

**Comment by gsvr** [comment]
I'll supply a PR soon (in the next hour, hopefully).

**Comment by dz0** [comment]
can it be, that 3.7.7 is also affected?
