### ISSUE TITLE
rest_framework.exceptions.ErrorDetail is unhashable after commit #5787

### ISSUE THREAD

**Issue by bacilla-ru** [encode/django-rest-framework#5919]
Commit #5787 makes class rest_framework.exceptions.ErrorDetail unhashable. This breaks functionality of some third-party libraries (like https://github.com/FutureMind/drf-friendly-errors). 

## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

from rest_framework.exceptions import ErrorDetail
err = ErrorDetail('error', code=1)
hash(err)

## Expected behavior

valid hash

## Actual behavior

Traceback (most recent call last):
  File "<input>", line 1, in <module>
TypeError: unhashable type: 'ErrorDetail'

**Comment by carltongibson** [comment]
OK. Yes. Since we added `__eq__()` it would be worth adding `__hash__()`

**Comment by danielmartins** [comment]
ErrorDetail stil not hashable. 

```
from rest_framework.exceptions import ErrorDetail
err = ErrorDetail('error', code=1)
hash(err)
TypeError: unhashable type: 'ErrorDetail'
``` 

Python 3.7.0 and Rest Framework 3.8.2

**Comment by bacilla-ru** [comment]
> ErrorDetail stil not hashable.
> 
> ```
> from rest_framework.exceptions import ErrorDetail
> err = ErrorDetail('error', code=1)
> hash(err)
> TypeError: unhashable type: 'ErrorDetail'
> ```
> 
> Python 3.7.0 and Rest Framework 3.8.2

The question must be 'when is the next release?'

**Comment by rpkilby** [comment]
You can track the 3.9 release in #6190. It's slated to be released around October 1st, but I would expect delay, as #6119 is still a WIP.

**Comment by carltongibson** [comment]
Yep. It's coming.
