### ISSUE TITLE
Browsable API crashes when using to_representation

### ISSUE THREAD

**Issue by stormpat** [encode/django-rest-framework#5935]
I have a model that has an relation, and i only want a single field from the related table.

```python
def to_representation(self, instance):
        return instance.type
```
The serializer returns the type column value (a string), and all is fine. But the API browser crashed with the error:

```
Exception Value: | 'str' object has no attribute 'items'
rest_framework/templates/rest_framework/horizontal/form.html, error at line 4
 {% load rest_framework %}
{% for field in form %}
{% if not field.read_only %}
{% render_field field style=style %} <--- Here
{% endif %}
{% endfor %}
``` 

If i turn the format to json it works as expected.

**Comment by xordoquy** [comment]
Unfortunately there isn't enough informations here to make this actionable.
My bet here is that you used a string returned by to_representation` for a field that expects a structure - most likely a list of items for a dropdown.

**Comment by stormpat** [comment]
It seems indeed that the API browser expects some fields to be a object (in dropdowns). I was under the impression that the API browser could display and valid JSON structure.

I will investigate further and see if i find any solution.
