### ISSUE TITLE
NamespaceVersioning is not picking the right version for request.version

### ISSUE THREAD

**Issue by Uxio0** [encode/django-rest-framework#5939]
## Steps to reproduce
 Set up namespace versioning

```
REST_FRAMEWORK = {
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.NamespaceVersioning'
}

```
Define a url with namespace='api:v1'

`url(r'^api/v1/', include('myapp.urls', namespace='api:v1'))`

## Expected behavior
When you go to request.version you should get "v1"

## Actual behavior
When you go to request.version you get "api"

**Comment by xordoquy** [comment]
Django namespaces uses the : to split the namespaces. In your example, there will be a mismatch because you define "api:v1" as a single namespace while Django's function will consider it's a [nested namespace](https://docs.djangoproject.com/en/2.0/topics/http/urls/#introduction):

> Namespaces can also be nested. The named URL 'sports:polls:index' would look for a pattern named 'index' in the namespace 'polls' that is itself defined within the top-level namespace 'sports'.
