### ISSUE TITLE
Documentation: Change HTTP Signature Authentication recommendation

### ISSUE THREAD

**Issue by cveilleux** [encode/django-rest-framework#5946]
The current recommandation for implementing HTTP Signature Authentication, [available here](https://www.django-rest-framework.org/api-guide/authentication/#http-signature-authentication) recommends the following module:

https://github.com/etoccalino/django-rest-framework-httpsignature
https://pypi.org/project/djangorestframework-httpsignature/

That module has not been updated in almost 3 years and contains a very broken rsa implementation.
See: https://github.com/etoccalino/django-rest-framework-httpsignature/issues/13

You should update the recommandation for https://github.com/ahknight/drf-httpsig which is properly maintained and has an available pypi release named `drf-httpsig`

**Comment by tomchristie** [comment]
@cveilleux Would you be interested in making a pull request to the documentation, that we can then review?

**Comment by int3l** [comment]
@cveilleux , @tomchristie Here we go :)
