### ISSUE TITLE
[DOCS]If you have a project with a large number of applications, some of them are not displayed in the documentation (more precisely, the latter)

### ISSUE THREAD

**Issue by alex1vanchik** [encode/django-rest-framework#5948]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Create a project with many applications/endpoint categories. It is front-end bug. I think the easiest way to test this is to create mock with endpoint categories. I have about 28 categories.
## Expected behavior
Not all endpoints are visible. The last two applications are hidden under auntification, source code sections. This is perfectly clear if you compare the list to the [desktop](https://monosnap.com/file/9vTp7saSRg8Af8jyjgKgZL57cO1ztA) and [mobile](https://monosnap.com/file/edBLhlJ8cnIYJOsJ1XfMYNaIwsMMrq) version. 

## Actual behavior
All endpoints must be visible.

**Comment by tomchristie** [comment]
Isn't the sidebar scrollable now? Seem to recall this being resolved in https://github.com/encode/django-rest-framework/issues/5370

**Comment by alex1vanchik** [comment]
Yes, you fix one bug, but allowed another

**Comment by tomchristie** [comment]
Looks to me like this could be resolved by adding...

```css
#menu-content {
    padding-bottom: 100px
}
```

Allows user to scroll all the way to the end...

![image](https://user-images.githubusercontent.com/647359/39043823-4fc42b70-4486-11e8-9fff-106db65589e1.png)

**Comment by alex1vanchik** [comment]
yes, it's very easy to fix this problem. I added
```
.menu-content{
    margin-bottom: 70px
}
```
70 px this is the size of the two items. look well

**Comment by carltongibson** [comment]
@alex1vanchik Fancy making a PR?

**Comment by alex1vanchik** [comment]
@carltongibson No. I'm just doing my best to get the problem help straighten out as soon as possible. I really like DRF. You can delete this topic if you think this is PR + I am not front-end developer
