### ISSUE TITLE
Nullable ListField with allow_null=True not working?

### ISSUE THREAD

**Issue by MiltosD** [encode/django-rest-framework#5951]
Nullable ListiField as recommended here  `ListField(child=NestedSerializer(allow_null=True))` does not seem to work on version 3.8.2
e.g.
 `list_field = ListField(child=NestedSerializer(allow_null=True))`

The message returned when setting `list_field: null` and trying to PATCH is:

> "list_field": [
                            "This field may not be null."
                    ]

To provide some more context, I use MongoDB and django-rest-framework-mongoengine 3.3.1, if this important.  **django-rest-framework-mongoengine** API reference states that

> **ListField** and DictField are mapped to corresponding DRF fields, with respect to nested field specification

so it may (or not) be the right place to raise this issue..

**Comment by tomchristie** [comment]
As your specifying it there, you’re allowing for null items. Ie. [null, null, ...]

Use allow_null on the ListField itself.
