### ISSUE TITLE
AnonRateThrottle for limited Api calls

### ISSUE THREAD

**Issue by MirzaBaig715** [encode/django-rest-framework#5952]
documentation of Throttling doesn't explain if the throttling rate for Anonymous users can be limited to some number.For example, if the anonymous user is restricted to only 50 api calls rather than per hour,day. Is there any possibility that I can do this to allow anonymous users for only just 50 api calls?

**Comment by tomchristie** [comment]
You’d need to implement that as a custom class. Having said that, a throttle rate is far more conventional than a single fixed number of allowed calls - I wouldn’t really recommend that approach.

**Comment by MirzaBaig715** [comment]
okay thanks @tomchristie
