### ISSUE TITLE
Documentation - Tutorial change "python manage.py" to "django-admin.py"

### ISSUE THREAD

**Issue by patrickdigiovanni** [encode/django-rest-framework#5954]
In the tutorial there is a line that reads: 

Once that's done we can create an app that we'll use to create a simple Web API.

`python manage.py startapp snippets`

I believe the correct command here would be 

`django-admin.py startapp snippets`

A beginner might get stuck on this for hours.

Thanks!

**Comment by xordoquy** [comment]
Hi,
The tutorial is correct.
If you don't have the `manage.py` after the `cd tutorial` then you'll run into more issues later.
