### ISSUE TITLE
Serializer inheritance not inherit declated fields

### ISSUE THREAD

**Issue by Smosker** [encode/django-rest-framework#5957]
Python 3.5, drf 3.8.2

## Steps to reproduce
```
from rest_framework import serializers
from django.db import models

class User(models.Model):
    last_name = models.CharField(max_length=1000,)
    first_name = models.CharField(max_length=1000,)
    login = models.CharField(max_length=1000,)

class SomeModel(models.Model):
    field1 = models.CharField(max_length=1000,)
    author = models.ForeignKey(User, null=False, blank=False,)

class UserSerializer(BaseSerializer):
    class Meta:
        model = User
        fields = 'last_name', 'first_name', 'login',

class ObjectWithAuthorMixin:
    author = UserSerializer(read_only=True)

class BaseSerializer(serializers.ModelSerializer):
    pass

class SomeModelSerializer(ObjectWithAuthorMixin, BaseSerializer):
    class Meta:
        model = SomeModel
        fields = ('id', 'field1', 'author', )

print(SomeModelSerializer().get_fields())

```
## Expected behavior
```
OrderedDict([('id', IntegerField(label='ID', read_only=True)),
             ('field1', CharField(max_length=1000)),
             ('author', UserSerializer(read_only=True):
                  last_name = CharField(max_length=1000)
                  first_name = CharField(max_length=1000)
                  login = CharField(max_length=1000))])
```
## Actual behavior
```
OrderedDict([('id', IntegerField(label='ID', read_only=True)),
             ('field1', CharField(max_length=1000)),
             ('author', PrimaryKeyRelatedField(queryset=User.objects.all()))])
```

As you can see for some reason serializer user for user `PrimaryKeyRelatedField` instead of `UserSerializer`, does this expect to behave like this?

Serializer inheritance doesn't work like this? I should manyally set 
`author = UserSerializer(read_only=True)` for `SomeModelSerializer`?

**Comment by carltongibson** [comment]
This is expected behaviour. See the [docs on Serializer Inheritance](http://www.django-rest-framework.org/api-guide/serializers/#serializer-inheritance) for more guidance. 

(Hint: try to avoid serialiser inheritance: whatever typing you save yourself will be lost 100-fold in maintenance later.)

**Comment by xordoquy** [comment]
also note that there's no reason a class that doesn't inherit from Serializer gets DRF fields discovered.

**Comment by mahoriR** [comment]
> This is expected behaviour. See the [docs on Serializer Inheritance](http://www.django-rest-framework.org/api-guide/serializers/#serializer-inheritance) for more guidance.
> 
> (Hint: try to avoid serialiser inheritance: whatever typing you save yourself will be lost 100-fold in maintenance later.)

People don't use inheritance to save typing. Inheritance is used so that we keep code DRY. Otherwise people will need to make changes at 10 different places instead of just 1 that is inherited by other 9.

**Comment by musfiqurcse** [comment]
@mahoriR Here the discussion is not about avoiding inheritance. It is more about when to use serializer inheritance. If we use such serializer inheritance (especially inheriting meta class), you are breaking one principle from **SOLID**.
