### ISSUE TITLE
AutoSchema does not generate a description

### ISSUE THREAD

**Issue by anshengme** [encode/django-rest-framework#5960]
- django==2.0.4
- djangorestframework==3.8.2

```python
class LiveViewSet(mixins.ListModelMixin,
                  viewsets.GenericViewSet):
    ......
    schema = AutoSchema(
        manual_fields=[
            coreapi.Field(name="create_start_date", required=False, location="query", description="发布开始时间"),
            coreapi.Field(name="create_end_date", required=False, location="query", description="发布结束时间")
        ]
    )
```

![20180427144122](https://user-images.githubusercontent.com/16428340/39348292-14af7d20-4a29-11e8-8147-1f3279886c97.png)

**Comment by anshengme** [comment]
![wx20180427-144457](https://user-images.githubusercontent.com/16428340/39348419-9eb08082-4a29-11e8-995a-4013de139308.png)

**Comment by carltongibson** [comment]
Description is (has been for a while) deprecated. Use the `schema` argument instead. 

```
schema=coreschema.String(description="发布开始时间")
```

or similar.
