### ISSUE TITLE
No 'exceptions' entry in 'API GUIDE' menu on official site

### ISSUE THREAD

**Issue by ryanking8215** [encode/django-rest-framework#5975]
Well, it's not a big problem. I guess the 'exceptions' entry is missed.

**Comment by xordoquy** [comment]
no idea what you are referring too, I can see it on the menu.

**Comment by rpkilby** [comment]
@ryanking8215 - the API Guide entries aren't sorted alphabetically. "Exceptions" are fourth from the bottom.  

http://www.django-rest-framework.org/api-guide/exceptions/
