### ISSUE TITLE
When I set a property method on model, the serializer cannot read it

### ISSUE THREAD

**Issue by wuxie2015** [encode/django-rest-framework#5980]
When I set a property method on model with @property, it doesn't work since I can't see it in valid data while when I directly use model it self it could work. I've saw the source code of django restful framework, on line 236 of serializers.py , the code is 
`self._validated_data = self.run_validation(self.initial_data)`
Here i could see my property in `self.initial_data` but I can't see it in `self._validated_data`. So can you tell me how to fix it?

Here is my code:
```python
# Model.py
class Host(models.Model):
    id = models.AutoField(primary_key=True)
    superPass = models.CharField(max_length=128, null=True, default='')

    @property
    def superPassword(self):
        origin_password = self.super_pass[0:-5]
        return origin_password

    @superPassword.setter
    def superPassword(self,new_password):
        origin_password = new_password
        encrypted = origin_password + "fadfa"
        self.super_pass = encrypted 

    @superPassword.deleter
    def superPassword(self):
        del self.super_pass

# Hostserializer.py
class HostSerializer(serializers.ModelSerializer):
    class Meta:
        model = Host
        fields = (
            'id',
            'superPassword')
```

**Comment by xordoquy** [comment]
DRF won't generate a field without the source being a Django's field itself. It would lack any description and constraint associated with it.
Therefore you need to explicitly [declare the field within the serializer](http://www.django-rest-framework.org/api-guide/serializers/#specifying-fields-explicitly).
Please also note that the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
