### ISSUE TITLE
quickstart: missing keys "count", "next", "previous" 

### ISSUE THREAD

**Issue by zachvalenta** [encode/django-rest-framework#5983]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

follow the 'quickstart'

## Expected behavior

in section: http://www.django-rest-framework.org/tutorial/quickstart/#testing-our-api

"by going to the URL `http://127.0.0.1:8000/users/`" see the following

<img width="899" alt="screen shot 2018-05-12 at 12 31 03 pm" src="https://user-images.githubusercontent.com/11388735/39959507-aa06193e-55e0-11e8-8b98-a48271a6243b.png">

## Actual behavior

instead see this 

<img width="1280" alt="screen shot 2018-05-12 at 12 33 42 pm" src="https://user-images.githubusercontent.com/11388735/39959514-b818a410-55e0-11e8-9160-54e499d8c1dd.png">

*note*: issue is not different number of users, but that don't see "count", "next", "previous"; even if create second user, these keys don't appear

<img width="1280" alt="screen shot 2018-05-12 at 12 37 51 pm" src="https://user-images.githubusercontent.com/11388735/39959557-4d7e34f2-55e1-11e8-974c-1163dc5fc4b2.png">

**Comment by tomchristie** [comment]
Looks valid on first pass to me - pagination *is* off by default, so we wouldn't expect to see the paginated style here, right?
Anyone up for running through the quickstart to confirm?

**Comment by tamirOK** [comment]
@tomchristie  is right. Pagination is off by default. To enable it these lines need to be added to the settings file:
```python
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 2,
}

**Comment by tomchristie** [comment]
We can either update the docs to turn on pagination, or update the docs with a correct screenshot.
Any preferences? (Pull requests in either direction are welcome)

**Comment by tamirOK** [comment]
Update the docs. [PR](https://github.com/encode/django-rest-framework/pull/5987)

**Comment by int3l** [comment]
@zachvalenta I guess this issue is fixed now? Please close it if that's the case :+1:
