### ISSUE TITLE
Serializer.data returns a copy of the validated data

### ISSUE THREAD

**Issue by willmcgugan** [encode/django-rest-framework#5998]
## Checklist

- [X] I have verified that that issue exists against the `master` branch of Django REST framework.
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [X] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [X] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

I've noticed some behaviour to serializers which tripped me up recently. I'm not certain if this is a problem with my expectations, a documentation issue, or a legitimate bug...

The BaseSerializer class caches its `data` attribute on the object, but `Serializer.data` returns a copy of `BaseSerializer.data` every time it is accessed (via `ReturnDict`).

This is a little inefficient (which is not a big deal), but it means that any changes to the `data` dict will essentially be reset when `Serializer.data` is next called. 

Should I expect to be able to mutate the `.data` attribute? For my particular use case I wanted to pop a key, and pass the remaining values to another part of my code. Something along these lines:

```python
name = serializer.data.pop('name')
call_thing(name, **serializer.data)
```

That failed because `name` still existed in the second call to `serializer.data`.

How about caching the return value of `.data` on `Serializer`, to preserve mutable semantics?

**Comment by xordoquy** [comment]
preserving mutable things are tricky for most people including experienced one.

```
data = serializer.data
mutate_data_for_other_purposes(data)
return Response(serializer.data)
```

This can be much more obfuscated in real base code but it'll be down a lot of hours wasted to understand what / how things have been messed up.

My take on this is the current behavior is much more expected / understandable.

**Comment by willmcgugan** [comment]
Not sure if there is a precedence in Django or serializers in general, but as a Python interface its somewhat surprising. As its an attribute I would expect it to have the same semantics as a simple dict property. If it were a function called `get_data()` I wouldn't make that assumption.

There's a lack of consistency in the Serializer classes; the BaseSerializer does cache the data on the object, so any custom serializer derived from that would operate like a regular dict.

If the behaviour is to be that you shouldn't expect to be able to mutate `.data` I'd think it would be a good idea to either document it, or enforce it.

I have worked around this in the way you suggested. So its not a big issue for me. But I do consider it a bit of a *wart* in the api, that may be worth looking at down the line.

**Comment by rpkilby** [comment]
I would agree that this is a somewhat unusual interface. Attributes/properties don't usually return a different object on each access.

Reopening to discuss. Should the serializer `.data` be cached?

**Comment by rpkilby** [comment]
As a quick test, I changed the `data` properties to:

```python
    @property
    def data(self):
        if not hasattr(self, '_data'):
            ret = super(ListSerializer, self).data
            self._data = ReturnList(ret, serializer=self)
        return self._data
```

The test suite passes.

**Comment by xordoquy** [comment]
And this may break user's code that rely on it in a very bad way and hard to debug.
I'm still against changing this unless there's a clear warning when it's accessed for the second or more time AND it is clearly stated in the next minor (as opposed to micro) release notes.

**Comment by rpkilby** [comment]
> a clear warning when it's accessed for the second or more time

Not sure if this would work. The `serializer.data` is accessed by the mixin and also during rendering.

----

Actually, just realized that mutating the `serializer.data` would probably break rendering a bit. In the example above, popping the `name` field results in that value not being rendered for the field.

**Comment by xordoquy** [comment]
If people are told not to do something and yet still do it, so be it, they'll have to bear the consequences as well.
I'm against the proposed change as I already said. If it turns out the majority is willing to accept it, I'm fine but I will not let it go in a release without a clear warning both in the release notes and code.
There are too many side effects to subtle to easily figure out.

**Comment by carltongibson** [comment]
Hi @willmcgugan. Thanks for your thoughts. I'm glad you've resolved this issue. 

I'm going to close this as-is. Currently, there's no real desire (or capacity for that matter) for a major rewrite. APIs can always be improved* but DRF's is pretty stable, and we're pretty happy with that. 

Thanks again. 

[*]: And yes the serialiser layer bears life-scars. Again that's OK at this stage.

**Comment by xordoquy** [comment]
@willmcgugan thanks for sharing thoughts. Your latest comment rings a bell here and makes way more sense to me.
Will definitively keep that in mind because I think we can go further with it.
