### ISSUE TITLE
OPTIONS request should not return content? (re CORS)

### ISSUE THREAD

**Issue by metachris** [encode/django-rest-framework#5999]
DRF seems to return the full content with an OPTIONS request. Is that expected / wanted behavior? Asking because CORS preflight requests are OPTIONS requests, and not sure we want to return the content there. Any thoughts / suggestions?

**Comment by xordoquy** [comment]
> DRF seems to return the full content with an OPTIONS request. Is that expected / wanted behavior? 

I think so.

> not sure we want to return the content there.

[RFC](https://tools.ietf.org/html/rfc7231#section-4.3.7) states:

> The response payload, if any, might also describe the communication options in a machine or human-readable representation.

So it seems ok to add description of the resource.
That said, you can override the default behavior if you need a empty response content.
