### ISSUE TITLE
request.user should return a SimpleLazyObject like Django's request.user

### ISSUE THREAD

**Issue by jcushman** [encode/django-rest-framework#6002]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

Real-world case:

I have a cache middleware that checks whether authentication has been performed, by checking whether request.user has been populated. So I want to prevent DRF's BrowsableAPIRenderer from evaluating request.user unless it is actually used for authentication. The following steps should work:

* Set `def perform_authentication(self, request): pass` on an unauthenticated DRF view so authentication is not performed in advance.
* Override `{% block userlinks %}` in the template so `request.user` is not accessed.

Simple failing test case:

```
@api_view()
def hello_world(request):
    response = Response({'unused_variable': request.user}, template_name='foo.html'))
    assert not hasattr(request, '_user')
    return response
```

## Expected behavior

Providing request.user to a template should not perform authentication unless it is used.

## Actual behavior

Authentication is performed immediately on assigning request.user to another variable.

This does not happen with Django templates, and happens here because DRF's `request.user` is implemented differently from Django's `request.user`. Django [wraps its `get_user()` function in `SimpleLazyObject`](https://github.com/django/django/blob/master/django/contrib/auth/middleware.py), so simple assignment doesn't cause it to be evaluated.

I think it would be good in general for DRF's `request.user` to work the same as Django's. The simplest way I can see to do that is something like this:

```
    def _get_user(self):
        if not hasattr(self, '_user'):
            with wrap_attributeerrors():
                self._authenticate()
        return self._user

    @property
    def user(self):
        """
        Returns the user associated with the current request, as authenticated
        by the authentication classes provided to the request.
        """
        return SimpleLazyObject(lambda: self._get_user())
```

But that may have side effects I'm not thinking of. Does something like that seem like a good idea?

**Comment by tomchristie** [comment]
Authentication always runs inside `APIView`. We *could* perform authentication lazily (which is behavior we did previously once have) but it's more likely to result in unexpected behavior from the developer perspective. (Eg. different if you don't include any permission classes, but you do include authentication classes, they'll only run if request.user is accessed inside the view.)

**Comment by jcushman** [comment]
Fair enough!

If anyone else wants Django's lazy-loaded behavior for `request.user` for whatever reason, here's the monkeypatch I ended up with in `myapp/__init__.py`:

```
import rest_framework.request
from django.utils.functional import SimpleLazyObject


OriginalRequest = rest_framework.request.Request

class CustomRequest(OriginalRequest):

    @property
    def user(self):
        """
            Override DRF's Request.user property to return a lazy object, so we don't perform authentication if we
            don't have to.

            Note: OriginalRequest.user.fget(self) is the equivalent of super().user, which doesn't work for properties.
        """
        if not hasattr(self, '_lazy_user'):
            self._lazy_user = SimpleLazyObject(lambda: OriginalRequest.user.fget(self))
        return self._lazy_user

    @user.setter
    def user(self, value):
        """ Preserve DRF's Request.user setter. """
        OriginalRequest.user.fset(self, value)

if OriginalRequest.__name__ != "CustomRequest":
    rest_framework.request.Request = CustomRequest
```

Monkeypatching a property is a bit ugly unfortunately, but it seems to work.
