### ISSUE TITLE
DRF Not authenticating csrf-cookie on post-requests from logged in users

### ISSUE THREAD

**Issue by MGrass1** [encode/django-rest-framework#6006]
I've been having a hell of a time trying to get Django to accept post-requests from logged in users. Numerous SO-posts with no responses later I've come here to see if the problem is within the way DRF handles session authentication with cookies. [Here's the latest post made to SO](https://stackoverflow.com/questions/50546081/django-angular-403-django-not-accepting-csrf-cookie-csrf-token-missing-or-inco) Although a more comprehensive post [was made here.](https://stackoverflow.com/questions/50530351/django-403-forbidden-when-sending-post-requests-from-angular-only-when-user-is-l) Post requests can be made through the browsable API. 
Here are the results in the browser console when cookie gets set: 
![getcookie](https://user-images.githubusercontent.com/34198073/40579636-60e24852-612c-11e8-88a8-05366dcd00e1.png) 
Here are the results in the browser console when the same cookie is passed through a post requests:
![postcookie](https://user-images.githubusercontent.com/34198073/40579638-75617cbc-612c-11e8-926b-129d2f2ef2ee.png)

A later get-requests shows that the same set-cookie as the current cookie is set by Django, so the cookie value hasn't changed between requests, it does this between not being logged in and loggin in, although the cookie is updated as it should be when that happens.
This is the cookie strategy from Angular:
```
providers: [
    {
      provide: XSRFStrategy,
      useValue: new CookieXSRFStrategy('csrftoken', 'X-CSRFToken')
    }
  ],
```

Lastly I'm sorry if questions relating to other languages are off-limits. I'm at my wits end here.

Django version 2.0.3
DRF version 3.8.2
Angular version 6.0.2

## Steps to reproduce
CSRF_USE_SESSIONS = False in settings.py
Default DRF authentication methods.
Create a DRF modelviewset.
Send a post request while logged in as the user  through Angular  with the correct 'csrftoken' cookie-values.

## Expected behavior
Accepting the csrftoken cookie and allowing the post request
## Actual behavior
403 CSRF verification failed. Request aborted. "Reason given for failure: CSRF token missing or incorrect."

**Comment by rpkilby** [comment]
Hi @MGrass1 - the issue tracker is intended for bug reports & feature requests. If you're looking for [help], I'd recommend either the IRC channel or discussion group.

That said, my first recommendation is to always reduce complexity. In this case, remove the angular app from the equation and see if you can't get this working with just jQuery. See the [example implementation] from the Django docs. 

If you can't reduce complexity, try rebuilding the problem from the ground up. eg, start with the simplest example (simple Django view + jquery), then add on additional layers (DRF, then angular).

[help]: http://www.django-rest-framework.org/#support
[example implementation]: https://docs.djangoproject.com/en/2.0/ref/csrf/#ajax
