### ISSUE TITLE
TokenAuthentication -- Why can there be only one token per user?

### ISSUE THREAD

**Issue by brutasse** [encode/django-rest-framework#601]
in `authtoken/models.py` the User <-> Token association is a OneToOneField. Is there a specific reason for it not to be a simple ForeignKey?

With sessions, users can have multiple opened sessions. With APIs, people can have multiple devices / apps talking to a service and it'd be preferable for them not to share the same token.

It's very simple to write a custom TokenAuthentication that allows multiple tokens (I need something similar to GitHub's API, with a note / note_url associated to each token) but I'm wondering if it'd not be a saner default to allow multiple tokens per user. I'm happy to write a patch for this, otherwise I'll just roll my own TokenAuthentication.

Opinions?

**Comment by Gocht** [comment]
@brutasse There's something like this yet?

**Comment by tomchristie** [comment]
The third party JWT auth package is the best alternative token auth implemention. Worth looking at.

**Comment by basco-johnkevin** [comment]
+1

**Comment by jonathan-golorry** [comment]
I find the token=password comparison to be silly. Do you know any services that require you to change your password and invalidate every other session you have open every time you log out?

**Comment by Opalo** [comment]
@jonathan-golorry :+1: Extacly! There should be no relation/comparison between token and password.

**Comment by rwoloszyn** [comment]
Comparation token eq password is total misunderstanding. Tokens by definition short-term authentications mechanism, and password is not. Having multiple tokens per user is not bad idea at all.

Guys is there any 3rd pary token authorization mechanism which will produce tokens per mobile client ? (mobile device) ?

**Comment by JockeTF** [comment]
@rwoloszyn Yes, you may want to look into [Django OAuth Toolkit](https://github.com/evonove/django-oauth-toolkit). I use it via [Django REST framwork Social OAuth2](https://github.com/PhilipGarnero/django-rest-framework-social-oauth2) for both social and non-social use cases.

**Comment by rwoloszyn** [comment]
@JockeTF thanks. I will look into it, however as far as I check now I cand find anything about generating multiple token per device.

**Comment by JockeTF** [comment]
Ah, I was interpreting...

> Guys is there any 3rd pary token authorization mechanism which will produce tokens per mobile client ? (mobile device) ?

... As there being several client *types* for which users should have different tokens.

With the OAuth library users will get a new access and refresh token every time they submit their username and password. Tokens will be tied to a specific client ID (application). Each user can have several valid tokens for several different clients at the same point in time. Access tokens are usually short-lived, but new ones can be retrived using the refresh token.

**Comment by rwoloszyn** [comment]
@JockeTF ok. I get that. But I want to accomplish other thing. 
I would like to allow user to login/register by facebook and for now only facebook and when login or registartion completes generate my own backend token which will be used betwenn client<-> backend 
communication. I would like to also have different tokens for different mobile client. 
Ex. User have 2 mobile phones I would like to generate token per client and also associate tokens with this specifif device, so when user next tile log in I would know which device he/she is using.
I do not want to user provide any username/password staff. I would like to authenticate with faceboook, retreive my unique backend token per device. Is there any ready to go solution which could do that ? If not I am going to make one :)

**Comment by JockeTF** [comment]
@rwoloszyn [Django REST framwork Social OAuth2](https://github.com/PhilipGarnero/django-rest-framework-social-oauth2) will do most of what you want though the convert-token view. You may have to learn a little bit about how [Python Social Auth](https://github.com/omab/python-social-auth) works though, specifically about how to customize the pipeline.

I'm not sure if using different clients IDs for the different devices makes sense in your case, so you should look into that. If you don't want to use a different client ID per device, then you'll have to make something for keeping track of which device the tokens belong to. However, things pretty much work the way you want it to out-of-the-box if you do use a unique client ID per device.

**Comment by rwoloszyn** [comment]
@JockeTF that seem realy good. Thanks for good advices. I will share my results as soon as I get it working. Thanks again.

**Comment by omidraha** [comment]
Related package:
- [django-rest-knox](https://github.com/James1345/django-rest-knox)

> 
> Knox authentication is token based, similar to the
> ``TokenAuthentication`` built in to DRF. However, it overcomes some
> problems present in the default implementation:
> 
> -  DRF Tokens are generated with ``os.urandom``, which is not
>    cryptographically secure.
> 
>    Knox uses OpenSSL to provide tokens.
> 
> -  DRF tokens are limited to one per user. This does not facilitate
>    securely signing in from multiple devices, as the token is shared. It
>    also requires *all* devices to be logged out if a server-side logout
>    is required (i.e. the token is deleted).
> 
>    Knox provides one token per call to the login view - allowing each
>    client to have its own token which is deleted on the server side when
>    the client logs out.
> 
>    Knox also provides an option for a logged in client to remove *all*
>    tokens that the server has - forcing all clients to re-authenticate.
> 
> -  DRF tokens are stored unencrypted in the database. This would allow
>    an attacker unrestricted access to an account with a token if the
>    database were compromised.
> 
>    Knox tokens are only stored in an encrypted form. Even if the
>    database were somehow stolen, an attacker would not be able to log in
>    with the stolen credentials.
> 
> -  DRF tokens track their creation time, but have no inbuilt mechanism for tokens
>    expiring. Knox tokens can have an expiry configured in the app settings (default is
>    10 hours.)

**Comment by thisismsreddy** [comment]
@brutasse  It's been more then three years, is there any solution to solve this problem, Please let me know , thanks !!!

**Comment by brutasse** [comment]
@thisismsreddy nothing directly usable but you can have a look at https://github.com/feedhq/feedhq/blob/master/feedhq/reader/models.py -- multiple tokens per user, stored in the database with cache lookups to speed things up and spare SQL queries.

**Comment by zetaab** [comment]
why not use foreignkey here https://github.com/encode/django-rest-framework/blob/master/rest_framework/authtoken/models.py#L16? Then it allows more than one session per user? Of course it needs then more modifications to other things like examples as well.

**Comment by rahulsoibam** [comment]
5 years later, and this is still a problem. Most products/services require multiple sessions per user. Imagine logging into your account from the web app and your phone notifies you that you are logged out from the mobile app. Fix it by logging in again on the phone only to find out that you're logged out of the web application ad infinitum.

**Comment by n2ygk** [comment]
Would oauth2 be a solution? No session state per-se, just Bearer tokens.

**Comment by Simouche** [comment]
I solved this by implementing few things quickly... it took me around 5 minutes.
[check it out!](https://stackoverflow.com/a/71879453/9137227)
