### ISSUE TITLE
throttling rate for given view

### ISSUE THREAD

**Issue by wsqy** [encode/django-rest-framework#6013]
I want throttling for given view or common in settings.py
I have try set throttle_rates for view But no work，how do???
```
    throttle_rates= {
        'anon': '2/minute',
        'user': '4/minute',
    }
````

**Comment by xordoquy** [comment]
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
