### ISSUE TITLE
CSRF token validation on unauthenticated requests

### ISSUE THREAD

**Issue by csdenboer** [encode/django-rest-framework#6014]
Hey,

In the documentation (http://www.django-rest-framework.org/api-guide/authentication/#sessionauthentication) is mentioned that 'only authenticated requests require CSRF tokens, and anonymous requests may be sent without CSRF tokens' and that login views 'should always have CSRF validation applied'. Login requests are unauthenticated, so based on this information CSRF token validation must be enforced explicitly for the login view. 

Somewhere else in the documentation (http://www.django-rest-framework.org/topics/ajax-csrf-cors/) is mentioned 'If you're using SessionAuthentication you'll need to include valid CSRF tokens for any POST, PUT, PATCH or DELETE operations' which implicitly states that both unauthenticated and authenticated requests require a CSRF token.

What is the thruth? Should I add @method_decorator(csrf_protect, name='dispatch') in front of the login view or is this handled correctly automatically?

**Comment by tomchristie** [comment]
> which implicitly states that both unauthenticated and authenticated requests require a CSRF token.

Session authenticated POST etc requests require CSRF. Unauthenticated request do not. Yes, you should explicitly require CSRF on a login view if you’re writing it yourself.
