### ISSUE TITLE
Allowing explicit 'method_name' on SerializerMethodField

### ISSUE THREAD

**Issue by ablakey** [encode/django-rest-framework#6015]
I sat here trying to decide what's better etiquette: resurrecting a 3-year-old ticket or making a new one. Apologies if this is impolitely disruptive.

Relates to this discussion 3 years ago: https://github.com/encode/django-rest-framework/issues/2420

An AssertionError is raised if you redundantly set `'method_name'` to the same format as the method.  eg:

```
type = SerializerMethodField('get_type')

def get_type(self, obj):
    return obj.type
```

The problem, in my opinion, is that it enforces one consistent style of "Django Magic" where you need to understand Django's implementation in order to understand the code. To a general Python reader, it's not clear that Django magically knows which method to call because the method name is *similar* to the field name.

The final say 3 years ago was: "...The behaviour as it currently stands is deliberate design and I'm happy with the benefit of enforcing a single consistent style."  I don't think I understand what the benefit is. Enforced consistency, sure. But it's enforced implicitness.

Any change of opinion on this matter?  I'd be happy to take responsibility of making the necessary changes if so. Thank you for your time.

**Comment by carltongibson** [comment]
Hi. 

SerializerMethodField is no longer around. Instead all filters accept a [method](http://django-filter.readthedocs.io/en/latest/ref/filters.html#method) argument, allowing correct type validation at the form level.

Given that, I don’t think there’s an issue here.

**Comment by carltongibson** [comment]
Sorry, wrong repository.

**Comment by carltongibson** [comment]
The benefit is a lack of repetition. 

Users were constantly writing lines like `my_field = ... 'get_my_field'` and nobody liked it. The 'get_my_field' was implied. 

I can’t see any appetite for going back on that decision. 

But no harm in asking. 🙂
