### ISSUE TITLE
No "actions" in OPTIONS when calling ".json" but visible with ".api"

### ISSUE THREAD

**Issue by jiargei** [encode/django-rest-framework#6016]
Hej Guys!

I'm not sure if this is really an issue but it seems to one for me...

Kind Regards, Jürgen

## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

1. Call Web-Site (working properly)
    1. Open Browser
    2. open http(s)://to.my.site/api/v1.0/object/
    3. click "OPTIONS"
    4. I can see "actions" key
2. Call API (curl, python, browser not working properly)
    1. open terminal/python console/browser
    2. call/open OPTIONS http(s)://to.my.site/api/v1.0/object/?format=json
        1. curl -X OPTIONS url
        2. python.requests.options(url)
        3. browser (url)
    3. no key "actions" available !!!!

## Expected behavior

1.iv: key "actions" available
2.iii: key "actions" available

## Actual behavior

1.iv: key "actions" available
2.iii: key "actions" NOT available

**Comment by no-dap** [comment]
This doesn't look like bug. when I requested options to my api with python requests, I got actions in my json.
<img width="1680" alt="screen shot 2018-07-18 at 5 56 23 pm" src="https://user-images.githubusercontent.com/26595506/42870874-eff25608-8ab3-11e8-8a28-bdef3b1ad962.png">
