### ISSUE TITLE
`ChoiceField` sets wrong property in `__init__()`

### ISSUE THREAD

**Issue by seawolf42** [encode/django-rest-framework#6022]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

Create a ChoiceField.

## Expected behavior

* ChoiceField calls `_get_choices()` when queried for choices.
* ChoiceField calls `_set_choices()` when field.choices set to a value.

## Actual behavior

ChoiceField returns raw choices array, and setting `field.choices` simply updates that element directly.

**Comment by xordoquy** [comment]
I just checked by altering the functions to print whenever they are called:

```
In [3]: from rest_framework import serializers

In [4]: field = serializers.ChoiceField(
   ...:             allow_null=True,
   ...:             choices=[
   ...:                 1, 2,
   ...:             ]
   ...:         )
   ...:         
SET_CHOICES
GET_CHOICES

In [5]: 

In [5]: field.choices = [1]
SET_CHOICES
GET_CHOICES

In [6]: 

```
