### ISSUE TITLE
Try/catch in HyperlinkedRelatedField too broad.

### ISSUE THREAD

**Issue by tveastman** [encode/django-rest-framework#6025]
In https://github.com/encode/django-rest-framework/blob/master/rest_framework/relations.py#L347-L350

Catching and silently discarding the `TypeError` and `ValueError` seems overly broad, is it necessary?

I'm asking, after spending time debugging a derived `HyperlinkedRelatedField` where, it turns out, I was using the wrong method signature, which was throwing `TypeError` exceptions that DRF was thing reporting as 'object not found'.

Turns out there was an error in the documentation which I've patched in https://github.com/encode/django-rest-framework/pull/6024

Maybe correcting the docs is enough to prevent similar mistakes in the future, but catching `TypeError` could mask all sorts of errors, is it too broad?

**Comment by tomchristie** [comment]
I'm not sure it's resolvable. Making a queryset lookup with a string that *doesn't* convert to the expected type will raise one of those two error classes.

This will happen eg. in the case of API input of a hyperlinked URL using "/organizations/abc" for a model that expects "/organizations/123" .

We do need to catch those cases and represent them as "does_not_exist" errors against the user input.
