### ISSUE TITLE
JSONRenderer does not return a valid json response when `data=None`

### ISSUE THREAD

**Issue by kltdwrds** [encode/django-rest-framework#6026]
## Steps to reproduce
```
@permission_classes((AllowAny, ))
class Viewset(viewsets.ViewSet):
    renderer_classes = (JSONRenderer, )
    def list(self, request, *args, **kwargs):
        return Response()
```
## Expected behavior
A valid json response body like `null` or `{}`
## Actual behavior
No `Content-Type` header set and an empty response is returned - particularly painful when making requests with jquery's `ajax()`.  It throws an parseerror and rejects the promise on a success response with an empty body.  See here https://stackoverflow.com/a/6186905

PR here: https://github.com/encode/django-rest-framework/pull/6027

**Comment by rpkilby** [comment]
Just a quick clarification.. I may not be recreating your exact setup, but a quick, manual test shows that the `Content-Type` header is correctly set to `application/json`.

As to the empty response, I'm inclined to agree with @kltdwrds. I don't know if the spec allows an empty body, however, both JavaScript's `JSON.parse` and Python's `json.loads` fail to decode an empty string.

**Comment by kltdwrds** [comment]
hmm I'm using
```
from rest_framework import viewsets
from rest_framework.renderers import JSONRenderer
from rest_framework.response import Response
```
Not sure where the `Content-Type` header gets set, but I just confirmed it missing from responses using the example above.

**Comment by kltdwrds** [comment]
It looks like the `Content-Type` header is deleted on an empty renderer response (line 80)
https://github.com/encode/django-rest-framework/blob/master/rest_framework/response.py#L72
