### ISSUE TITLE
get_serializer ignores context in kwargs

### ISSUE THREAD

**Issue by backbohne** [encode/django-rest-framework#6029]
I've just struggling while adding extra context to my serializer. Using this code:

`serializer = self.get_serializer(data=request.data, context={'request': request, 'instance': product})`

But get_serializer ignores context and overwrite it with:

`kwargs['context'] = self.get_serializer_context()`

Does it make sense to change this line to:

`context = self.get_serializer_context()`
`context.update(kwargs.get('context', {}))`
`kwargs['context'] = context`

Regrads
Frank

**Comment by xordoquy** [comment]
Hi,

I don't really get the issue here.
If you want the original context and avoid duplicate it, you should call the parent:

```
def get_serializer_context(self):
    context = super().get_serializer_context()
    # add things in context.
    return context

```
