### ISSUE TITLE
Django REST 3.8.2 CurrentUserDefault doesn't work

### ISSUE THREAD

**Issue by damonsu** [encode/django-rest-framework#6031]
When i tried to create a new Post, i get always the following error:
     Exception Value: | (1048, "Column 'user_id' cannot be null")

But i get no error before i updated to Django Rest 3.8.2. It seems like that the function CurrentUserDefault doesn't work.

My Code:

    class PostSerializer(serializers.ModelSerializer):
    user = UserSerializer(
        many = False,
        read_only = True,
        default=serializers.CurrentUserDefault()
    )

    class Meta:
        model = Post
        fields = ('id', 'user', 'post_date')

    def create(self, validated_data):
        return Post.objects.create(**validated_data)

-----------------------------------------------------
**Solution based on the reply of  @blueyed **

    def create(self, validated_data):
         if 'user' not in validated_data:
             validated_data['user'] = self.context['request'].user
         return Post.objects.create(**validated_data)

**Comment by xordoquy** [comment]
Due to #5886 this will not work any longer.
You now need to override the view and explicitly add the current user.

Somewhat off topic, but it looks like the documentation isn't up to date with this new behavior (http://www.django-rest-framework.org/api-guide/serializers/#specifying-read-only-fields)

> Note: There is a special-case where a read-only field is part of a unique_together constraint at the model level. In this case the field is required by the serializer class in order to validate the constraint, but should also not be editable by the user.
> 
> The right way to deal with this is to specify the field explicitly on the serializer, providing both the read_only=True and default=… keyword arguments.
> 
> One example of this is a read-only relation to the currently authenticated User which is unique_together with another identifier. In this case you would declare the user field like so:
> 
> user = serializers.PrimaryKeyRelatedField(read_only=True, default=serializers.CurrentUserDefault())

**Comment by carltongibson** [comment]
The example there is still eighth for validation (where you do need the default due to the unique together constraint). 

We need to add a bit more re the need to supply the value when saving.

**Comment by anx-ckreuzberger** [comment]
Hi! 

I'm going to do some shameless self-promotion here (sorry for that), but my package should fix your issue. 

For your use-case of setting the current user (automagically), take a look at the [Django-UserForeignKey](https://github.com/beachmachine/django-userforeignkey) Package.

It works as a Django Middleware and sets the current user in your model, so you don't need to rely on your Devevelopers to always set the current user in your View Logic or serializers.

(I've also created a  [YouTube Video](https://www.youtube.com/watch?v=iJCbYMgUDW8) for a demo).

**Comment by blueyed** [comment]
Another approach might be to set it in your serializer's `create` by default: https://github.com/lock8/django-rest-framework-jwt-refresh-token/pull/35/files#diff-84229b1d4af72d928beddfa32e80cc8eR23 (?)

**Comment by carltongibson** [comment]
@blueyed: Yes. Pass the value during `perform_create()` in the view (which calls `save()`) — or override `save()` or `create()` or `update()` in the serialiser as appropriate. 

Extra notes in the docs emphasising this would be welcome. Where would **you** (i.e. all of you) expect to see that note? (I don't think it'll need a lot. PRs there welcome.)

**Comment by damonsu** [comment]
@blueyed you code works like a magic!! Thank you!

**Comment by blueyed** [comment]
@damonsu 
Great, you're welcome.

@carltongibson 
Regarding docs I've stumpled upon this: https://github.com/encode/django-rest-framework/blame/3fcc076d9124fc202be1a4379b6b753209c7afbe/docs/api-guide/generic-views.md#L156
Also `read_only` is pretty clear about it already: https://github.com/encode/django-rest-framework/blob/3fcc076d9124fc202be1a4379b6b753209c7afbe/docs/api-guide/fields.md#read_only.

Therefore it is likely more an issue when updating to the new behavior, and you have to remember this change (e.g. in the case of https://github.com/lock8/django-rest-framework-jwt-refresh-token I still was bisecting to find the issue, although I came across this before already).

**Comment by carltongibson** [comment]
> ...although I came across this before already

Indeed. 🙂 ([IIRC, it was you that dug out the root issue here](https://github.com/encode/django-rest-framework/pull/5708#issuecomment-355569737))

**Comment by to-bee** [comment]
Using `serializers.HiddenField` in combination with `CurrentUserDefault` works fine: `HiddenField(default=CurrentUserDefault())`
