### ISSUE TITLE
Regression string representation ValidationError 3.7.7 -> 3.8.x

### ISSUE THREAD

**Issue by emiel** [encode/django-rest-framework#6032]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

We're seeing a regression in the string representation of a ValidationError raised by a serializer.

```
{'errors': {
     'phones': [ErrorDetail(string=u'This field is required.', code=u'required')],
     'emails': {0: [ErrorDetail(string=u'Enter a valid email address.', code='invalid')]}
}, 'type': 'Validation Error'}
```
As you can see "ErrorDetail" is now showing up instead of just the string value.

## Steps to reproduce

I've put together the following test case (place it in `tests/test_serializer.py`).

The following tests passes for 3.7.7. As you can see the expected failure is the string representation of the validator error (without code).

```
#
# 3.7.7 
#

class TestValidationErrorRegression:
    def setup(self):

        class TestSerializer(serializers.Serializer):
            one = serializers.ListField(child=serializers.CharField(max_length=4))
            two = serializers.ListField(child=serializers.CharField())

        self.Serializer = TestSerializer

    def test_validate(self):
        input_data = {
            'one': ["exceed_max", "exceed_max_again"],
        }

        serializer = self.Serializer(data=input_data)
        assert not serializer.is_valid()
        assert serializer.errors == {
            'one': ['Ensure this field has no more than 4 characters.'],
            'two': ['This field is required.']
        }
```

However in 3.8 we're seeing that instead of a string representation we're seeing the ErrorDetail class show up. See 'actual behaviour below'.

Note: The test is adapted a bit for 3.8.x because of https://github.com/encode/django-rest-framework/pull/5655. (Perhaps also the source of the regression)

```
#
# 3.8.x (master)
#

class TestValidationErrorRegression:
    def setup(self):

        class TestSerializer(serializers.Serializer):
            one = serializers.ListField(child=serializers.CharField(max_length=4))
            two = serializers.ListField(child=serializers.CharField())

        self.Serializer = TestSerializer

    def test_validate(self):
        input_data = {
            'one': ["exceed_max", "exceed_max_again"],
        }

        serializer = self.Serializer(data=input_data)
        assert not serializer.is_valid()
        assert serializer.errors == {
            'one': {
                0: 'Ensure this field has no more than 4 characters.',
                1: 'Ensure this field has no more than 4 characters.'
            },
            'two': ['This field is required.']
        }
```

## Expected behavior

This is a good question. Not sure if `ErrorDetails` is supposed to be exposed via `serializer.errors`. I know it is propagated to ValidationError and that `ValidationError.detail` happily returns a string representation including "ErrorDetail(...)".

## Actual behavior
```
________________________________________________________________________________________________________________ TestValidationErrorRegression.test_validate _________________________________________________________________________________________________________________
tests/test_serializer.py:634: in test_validate
    assert serializer.errors == {
E   AssertionError: assert {'two': [Erro...ax_length')]}} == {'one': {0: 'E...s required.']}
E     Common items:
E     {u'two': [ErrorDetail(string=u'This field is required.', code=u'required')]}
E     Differing items:
E     {'one': {0: [ErrorDetail(string=u'Ensure this field has no more than 4 characters.', code=u'max_length')], 1: [ErrorDetail(string=u'Ensure this field has no more than 4 characters.', code=u'max_length')]}} != {'one': {0: 'Ensure this field has no more than 4 characters.', 1: 'Ensure this field has no more than 4 characters.'}}
E     Full diff:
E     - {'two': [ErrorDetail(string=u'This field is required.', code=u'required')], 'one': {0: [ErrorDetail(string=u'Ensure this field has no more than 4 characters.', code=u'max_length')], 1: [ErrorDetail(string=u'Ensure this field has no more than 4 characters.', code=u'max_length')]}}
E     + {u'one': {0: u'Ensure this field has no more than 4 characters.',
E     +           1: u'Ensure this field has no more than 4 characters.'},
E     +  u'two': [u'This field is required.']}
```

**Comment by rpkilby** [comment]
cc @blueyed, @carltongibson

**Comment by blueyed** [comment]
@emiel 
Please bisect it.

I've thought it was because of https://github.com/encode/django-rest-framework/pull/5785, but that is not merged.
Would be good to also test this then.

As for the diff, it appears to have become a list now - `ErrorDetail` itself compares equal to a string:

```python
In [1]: from rest_framework.exceptions import ErrorDetail

In [2]: ErrorDetail('foo') == 'foo'
Out[2]: True

In [3]: ErrorDetail('foo', code='invalid') == 'foo'
Out[3]: True

In [4]: ErrorDetail('foo', code='something_else') == 'foo'
Out[4]: True
```

The problem is that there is a code now, and it becomes a list:


```
{'one': {0: [ErrorDetail(string=u'Ensure this field has no more than 4 characters.', code=u'max_length')],
         1: [ErrorDetail(string=u'Ensure this field has no more than 4 characters.', code=u'max_length')]}}
!= 
{'one': {0: 'Ensure this field has no more than 4 characters.',
         1: 'Ensure this field has no more than 4 characters.'}}
```

**Comment by blueyed** [comment]
The following passes on master:
```python
class TestValidationErrorRegression:
    def setup(self):

        class TestSerializer(serializers.Serializer):
            one = serializers.ListField(child=serializers.CharField(max_length=4))
            two = serializers.ListField(child=serializers.CharField())

        self.Serializer = TestSerializer

    def test_validate(self):
        input_data = {
            'one': ["exceed_max", "exceed_max_again"],
        }

        serializer = self.Serializer(data=input_data)
        assert not serializer.is_valid()
        assert serializer.errors == {
            'one': {
                0: 'Ensure this field has no more than 4 characters.',
                1: 'Ensure this field has no more than 4 characters.'
            },
            'two': ['This field is required.']
        }
```

**Comment by blueyed** [comment]
But I agree that the representation is confusing.
It should however still become a string in the end:
```python
(Pdb++) str(serializer.errors)
"{'one': {0: [ErrorDetail(string='Ensure this field has no more than 4 characters.', code='max_length')], 1: [ErrorDetail(string='Ensure this field has no more than 4 characters.', code='max_length')]}, 'two': [ErrorDetail(string='This field is required.', code='required')]}"
(Pdb++) import json
(Pdb++) json.dump
       dump   dumps  
(Pdb++) json.dumps(serializer.errors)
'{"one": {"0": ["Ensure this field has no more than 4 characters."], "1": ["Ensure this field has no more than 4 characters."]}, "two": ["This field is required."]}'
```

**Comment by emiel** [comment]
I've been poking at this some more and now have a better understanding of what is going on. It is indeed as @tomchristie pointed out, a regression in our test cases. The test case that broke on our side looked something like:

```
response = view(request)
self.assertEqual(response.status_code, 400)
self.assertEqual(response.data["type"], "Validation Error")
errors = response.data["errors"]
self.assertEqual(errors["phones"][0], ["This field is required."])
```

After running the response through a renderer (JSON) everything is as expected.

I'm going to update our test cases to just include ErrorDetail as this appears to be correct.

From my side the issue is resolved but was caught off guard a bit. ;)

Thanks all.

**Comment by blueyed** [comment]
> We could add an __eq__ method to them for easier error testing?

It is there already: https://github.com/encode/django-rest-framework/blob/5bc3b7712f76fb3e8e0d40e9352bbd93d405c6af/rest_framework/exceptions.py#L78-L83

pytest however then uses the `repr` in case it's not equal (AFAIK).

**Comment by blueyed** [comment]
@emiel 
Not sure if I understand you correctly - it would really help if you could git-bisect the change in DRF that is causing your failure, but it is likely as for the fixed test case I posted above, where it's 6bd773e7f (#5655, like mentioned before).

```
  22                 'one': {                                                                
  23                     0: ['Ensure this field has no more than 4 characters.'],            
  24                     1: ['Ensure this field has no more than 4 characters.'],            
  25                 },                                                                      
  26                 'two': ['This field is required.']                                      
  27             }                                                                           
(Pdb++) pp serializer.errors
{'one': ['Ensure this field has no more than 4 characters.'],
 'two': ['This field is required.']}
```

So it really looks like some understanding, since your original report stated that you adopted the test for 3.8, but then did not took into account that the values for the dict items in "one" are lists, and not single entries.

Anyway, I think this issue can be closed, too.. :)

**Comment by emiel** [comment]
Hello again,

Thanks for following up @blueyed. I've dug even deeper and now have an explanation of what is going on in my test case. The source of my pain is due to a combination of things: tricky `assertEqual` statements on my part and a couple of changes in 3.8.

* Introduction of `__repr__` on `ErrorDetail` 769bc1336fd5d6a7fcf10d8be3b374c3e7a21bb3
* Composite field child errors: https://github.com/encode/django-rest-framework/pull/5655

My serializer.errors dict looks as follows under the two different DRF versions. By adding `__repr__` to ErrorDetail the output changed. This threw me off because I initially thought this was the reason the tests started to fail. Though as pointed out, __eq__ works just fine and ErrorDetail behaves as a string when needed. To be clear there is no issue here.

```
3.7.x
errors = {'phones': [u'This field is required.'], 'emails': [u'Enter a valid email address.']}

3.8.x
errors = {
  'phones': [ErrorDetail(string=u'This field is required.', code=u'required')],
  'emails': {0: [ErrorDetail(string=u'Enter a valid email address.', code='invalid')]}
}
```

The actual reason my tests were failing was due to https://github.com/encode/django-rest-framework/pull/5655, as you pointed out. Above `emails` is now a dict instead of a list.

My assert looked as follows:

```
self.assertEqual(errors["emails"][0], "Enter a valid email address.")
```
And because...

```
>>> l = [1,2,3]
>>> l[0]
1
>>> d = {0: [1,2,3]}
>>> d[0]
[1, 2, 3]
```
Things got a bit confusing and I'm here on this wild goose chase. :)

Changing the assert to the following resolved the issue. Though I think I'll rewrite this for clarity later.

```
self.assertEqual(errors["emails"][0], ["Enter a valid email address."])
```

This does appear to be an API change and so the changelog could have been a bit louder here I guess. But it's not really an issue for us.

Thanks for thinking along and feel free to close this issue.

**Comment by blueyed** [comment]
Cool.  I wasn't aware that the repr was so new (https://github.com/encode/django-rest-framework/commit/769bc1336fd5d6a7fcf10d8be3b374c3e7a21bb3).

I cannot close the issue, but you can.. :)

**Comment by emiel** [comment]
Thanks again!

**Comment by carltongibson** [comment]
OK. Thanks everyone for taking the extra time here.

**Comment by carltongibson** [comment]
>...so the changelog could have been a bit louder here...

@emiel Would happily merge a PR on the release notes calling out the change if you think it would help others. (From this end it's hard to know 🙂) 

Thanks again.
