### ISSUE TITLE
Still can not document parameters with the doc string in custom detail/list view?

### ISSUE THREAD

**Issue by daimon99** [encode/django-rest-framework#6035]
Usually we need add custom detail/list view in the viewset.
And it has custom parameters which different from the serializer object.
So, how we document for the custom detail/list view function?
I see the formal document, it seems suggest i do like this:
```
class XXXViewset:
    schema = AutoSchema(manual_fields=[
            coreapi.Field("extra_field", ...),
        ])
```
But if we do like this, all the methods will have this field, not only the custom action.
How to add specific fields to a specific action?
Is there an easy way? How about describe it in the doc string in this function?
I think it will be the humanic way to document a custom detail/list view.

**Comment by carltongibson** [comment]
See https://github.com/encode/django-rest-framework/pull/5992. This should resolve it. Just pending final review it’ll be part of v3.9, which we’re beginning to prepare now.
