### ISSUE TITLE
Reconsider recommending django-oauth-toolkit or put a warning in docs

### ISSUE THREAD

**Issue by sassanh** [encode/django-rest-framework#6051]
In the docs here: http://www.django-rest-framework.org/api-guide/authentication/#django-oauth-toolkit
drf is recommending `django-oauth-toolkit`:

> The package is well documented, and well supported and is currently our recommended package for OAuth 2.0 support.

As far as I know `django-oauth-toolkit` has no mechanism to avoid brute forcing passwords. I guess we should at least warn users there that it's not immune to brute force.

**Comment by rpkilby** [comment]
I'm going to close this for now. On the one hand, this sounds like a significant issue. On the other, we can't track another project's issues in our own documentation. It's just not feasible to maintain this list without constantly being out of date.

I've brought this up previously (see: #5977), but the best thing we can do is prune outdated 3rd-party apps, then take a more neutral stance in our recommendations.

**Comment by sassanh** [comment]
@rpkilby 
Can you kindly tell me what's the current recommendation for authentication? 

And about the documentation, what about removing the line quoted above? Telling people "currently our recommended package" is django-oauth-toolkit doesn't seem to be wise without a warning. I agree that we shouldn't track other projects issues in the docs but when we're recommending a package in the docs that has security risks I think we should either mention the risk or avoid the recommendation.
I'm not comfortable saying it in public but I guess all web services out there using django-oauth-toolkit are vulnerable to brute-force and none of them are secure right now (unless they have patched the package or some other third party module like cloudflare is saving them from brute force.)

**Comment by rpkilby** [comment]
> Can you kindly tell me what's the current recommendation for authentication?

We haven't provided OAuth with our services recently, so I don't know what the current provider landscape is like. Looking at the [OAuth grid](https://djangopackages.org/grids/g/oauth/) over at djangopackages.org, your best bet is `django-oauth-toolkit`. It seems to be the only modern/up-to-date OAuth provider.

> And about the documentation, what about removing the line quoted above? 

Regardless of faults, the line is still true. As far as I can tell, there aren't any decent alternatives. Even `django-rest-framework-oauth` seems to be significantly out-of-date.

That said, I plan to reorganize the 3rd-party package docs at some point. Currently, they're a bit disorganized, as they're spread over the individual sections of the guide, as well as the dedicated 3rd-party apps topic. I'd like to consolidate this into a single section that's a little more terse. e.g., remove installation notes and example code, adopt more neutral language.
