### ISSUE TITLE
Adding a field to read_only_field skips its validation

### ISSUE THREAD

**Issue by shanavas786** [encode/django-rest-framework#6066]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
- use the following code
models.py
```python
from django.db import models
class A(models.Model):
  key = models.CharField(max_length=10, unique=True)
  other = models.CharField(max_length=10)

```
serializers.py
```python
from rest_framework import serializers
from <app>.models import A
class ASerlzr(serializers.ModelSerializer):
  class Meta:
    model = A
    fields = ('other', 'key')
    read_only_fields = ('key', )
```
- insert one entry to A with empty key
- run the following in shell
```python
from <app>.models import A
from <app>.serializers import ASerlzr

data = {'other': 'other'}
s = ASerlzr(data=data)
print(s.is_valid())
s.save()
```
## Expected behavior
`s.is_valid()` should return False
It does so when `key` is removed from `read_only_fields`
## Actual behavior
`s.is_valid()` returns True
`s.save()` fails because of unique constraint violation

**Comment by xordoquy** [comment]
This is up to the developer to get this right.
Marking a field as read only means it won't be validated nor writable.
You need to customize the create/update and pass your value to the serializer's `save` to fix it.
