### ISSUE TITLE
Inline CSS and javascript in API templates conflict with common CSPs

### ISSUE THREAD

**Issue by harrislapiroff** [encode/django-rest-framework#6069]
Django REST Framework's HTML-formatted API responses use templates with a few instances of inline CSS and javascript. Unfortunately many [Content Security Policies](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) cause browsers to reject inline CSS and javascript by default.

### Steps to Reproduce

1. Use a Django project with an API (that allows HTML format) created using Django REST Framework
2. Install [`django-csp`](https://django-csp.readthedocs.io/en/latest/installation.html) and its middleware. The default configuration should work fine.
3. With the dev server running, visit http://localhost:8000/path/to/api/ in a web browser. Observe errors like these:

<img width="518" alt="screen shot 2018-07-06 at 2 22 20 pm" src="https://user-images.githubusercontent.com/296631/42394439-1b910cea-8128-11e8-8da6-e80eb33a3c95.png">

### Proposed Mitigations

This problem is particularly irksome because the DRF viewsets make it challenging to modify the response headers. Using `django-csp` I did create some DRF classes that were CSP compatible and worked for my specific use case, but [this solution](https://gist.github.com/harrislapiroff/b0f34320aba7449c34a6097bc57ab5e8) involved some duplication of code and may not work for more complex cases. I'd propose three potential mitigations:

1. Break up `ViewSetMixin.as_view` to make it easier to override portions of it or add hooks for modifying the generated view. This will allow a developer to use something like `django-csp`'s decorators to update those views.
2. Reduce the need for custom CSP by moving inline styles and javascript to static files.
3. Include out-of-the-box CSP support. This seems probably beyond the scope of DRF.

**Comment by carltongibson** [comment]
Related #5740. @harrislapiroff Fancy having a look there and commenting?

**Comment by juspence** [comment]
After merging fixes for the CSRF token and forms, Django-REST-Framework no longer requires ```script-src: 'unsafe-inline'``` in the CSP.

After merging fixes for the inline CSS, Django-REST-Framework *mostly, but not fully*, no longer requires ```style-src: 'unsafe-inline'``` in the CSP. There is a little bit of inline styling that breaks with a strong CSP like ```style-src: 'self'```.

This broken styling is (I think) only related to syntax highlighting using CSS that's dynamically generated by Pygments. We can't move it to an external stylesheet easily, nor can we fix it for our users without causing side effects.

You won't see this error if Pygments is not installed, or if your CSP contains 'unsafe-inline'. You can also ignore this error if you don't care about syntax highlighting.

If you want an error-free strong CSP with syntax highlighting enabled:

    Make sure you have a strong CSP like style-src: 'self'
    Visit your page in Google Chrome
    In the Developer Tools console, note the error message about CSP and the hash
    Add that hash to your CSP, like style-src: 'self' 'sha256-1234'

**Comment by auvipy** [comment]
@juspence thanks for testing and merging them and share the consensus with us.
