### ISSUE TITLE
How to customize error exception information

### ISSUE THREAD

**Issue by zhengyscn** [encode/django-rest-framework#6071]
example:
DRF Response:
{
    "non_field_errors": [
        "Node(app) already exists."
    ]
}

I want a return like this.
{
"code":-1
"msg":"Node(app) already exists."
}

**Comment by rpkilby** [comment]
Hi @zhengyscn - the issue tracker is intended for bug reports & feature requests. If you're looking for [support](http://www.django-rest-framework.org/#support), I'd recommend either the IRC channel or discussion group.
