### ISSUE TITLE
Authenticated POST request triggers CSRF as intended, PATCH doesn't

### ISSUE THREAD

**Issue by arummukainen-qvik** [encode/django-rest-framework#6085]
Found out that doing POST to DRF required CSRF token in header, but PATCH doesn't. Easily reproduced and tested with Postman/Paw/curl/whatever

## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
```
class SomeViewSet(viewsets.ModelViewSet):
    queryset = SomeModel.objects.all()
    serializer_class = SomeSerializer
    permission_classes = (IsAuthenticated,)
    authentication_classes = (TokenAuthentication, SessionAuthentication,)
```

## Expected behavior
PATCH to require CSRF token in header

## Actual behavior
PATCH commits to database without CSRF token. POST does require CSRF as intended

**Comment by xordoquy** [comment]
As explained [here](https://github.com/pillarjs/understanding-csrf#avoid-using-post), CSRF are really required for POST only.
