### ISSUE TITLE
Modal dialog stays hidden using AdminRenderer

### ISSUE THREAD

**Issue by nyirit** [encode/django-rest-framework#6086]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
* Use AdminRenderer
* Open "Create" dialog for an object
* Leave a required field empty
* Click "Save"

## Expected behavior
See the modal dialog with the validation error message.

## Actual behavior
Dialog stays hidden (but it is generated as an error modal dialog), no validation error message is displayed.

**Comment by tomchristie** [comment]
Closing this off as stale.
