### ISSUE TITLE
SchemaGenerator cann't be overrided via settings

### ISSUE THREAD

**Issue by onegreyonewhite** [encode/django-rest-framework#6092]
## Expected behavior
SchemaGenerator should be overridable.
It can solve a lot of problems and helps to esier integration with drf-yasg or other.
```
REST_FRAMEWORK = {
    'SCHEMA_GENERATOR_CLASS': 'rest_framework.schemas.generators.SchemaGenerator'
}
```
## Actual behavior
There is no settings to override SchemaGenerator class.

**Comment by tomchristie** [comment]
You can customize the schema generation, as documented in https://github.com/encode/django-rest-framework/blob/master/docs/api-guide/schemas.md#adding-a-schema-view

Doesn't necessarily need to directly be a setting to allow for customization.
