### ISSUE TITLE
get_serializer_fields ignore GET method

### ISSUE THREAD

**Issue by kaldown** [encode/django-rest-framework#6100]
could yo please answer, why you ignore payload on get?
https://github.com/encode/django-rest-framework/blob/master/rest_framework/schemas/inspectors.py#L325

https://tools.ietf.org/html/rfc7231#section-4.3.1

**Comment by xordoquy** [comment]
As the RFC says, "A payload within a GET request message has no defined semantics". Therefore there's no reason we should consider the GET payload by default.
Please also consider this is an issue tracker. Discussion and usage questions should be asked on the  [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework). Thanks!

**Comment by tomchristie** [comment]
Seconding @xordoquy, yup. We don't *stop* you from doing so, we just don't make any provision for it because it's unclear how it'd be useful. It's unsupported in most other clients and server implementations too.

**Comment by xordoquy** [comment]
Also, GET is expected to be safe. Should DRF consider the GET payload to process the data, it wouldn't follow the good practices and possibly would not comply to some RFCs.

**Comment by kaldown** [comment]
but it's not strict to MUST TO. But you strip it as default. So after this I should made a mess with supering default behavior for no reason

**Comment by xordoquy** [comment]
no idea what you are referring to

**Comment by kaldown** [comment]
There is no word "MUST NOT provide payload in get", but you made this so

**Comment by tomchristie** [comment]
@kaldown It'd be *far* more surprising default behavior if we assumed that a serializer class was also used to indicate the presence of a body on a GET request.

You'll need to customize the schema generation if you want to support this use-case. It's not what everyone else will expect.
