### ISSUE TITLE
A few issues with documentation & template pack (HTMLFormRenderer)

### ISSUE THREAD

**Issue by velis74** [encode/django-rest-framework#6101]
I was experimenting with forms and found a few minor issues:

1. The documentation says default template pack is `horizontal` while in fact it is `vertical`

http://www.django-rest-framework.org/topics/html-and-forms/#using-template-packs

https://github.com/encode/django-rest-framework/blob/8493990a66e36d5dd4a62742d861b5b6b15cae80/rest_framework/renderers.py#L263

2. The input templates in horizontal template pack do not add `row` class to row DIVs. As a consequence, the render is completely off with labels being drawn vertically one character per line (when narrow) or same as vertical when there's enough horizontal room. Discussing the "too narrow" scenario: Adding `row` class doesn't help the problem much as default label : input ratio is set to 2: 10. I'm not too proficient with bootstrap so I don't have a good suggestion on how to fix this, but I'd still suggest at least 4:8 or adding something like `white-space: nowrap` to labels.

3. The documentation is a bit skimpy on how to use the template packs. My initial try was with `'vertical'` only to find that I need to specify the app as well `'rest_framework/vertical'` (which is - granted - more logical). That then worked. Still, having a sample in docs would help somewhat.

4. If you specify format in the query to a `ViewSet`, such as http://yourserver/rest/viewset/pk/?format=xyz, you will get the same *"404 Not found"* if **the renderer** is not found as you would if **the record** was not found. Makes it a bit awkward diagnosing the issue as there's no additional info.

Given some guidance on what the desired fixes would be, I can fix these and submit a PR.

**Comment by velis74** [comment]
As the issue hasn't yet been addressed, I'll just continue with further issues I found - with offer for a PR remaining for these as well.
I also apologise for my n00bness here. It may well be that I simply totally misunderstand the entire concept here, so please don't take my comments as my attempts of lecturing you: they are here solely because it's me that doesn't understand a lot of things and am trying to clarify them.

5. I find it impossible to specify a custom form template for `render_form` tag. It always just takes the `base_template` as defined in the class and fetches that template from template pack directory. This suggests to me that implementing a custom form template would require overriding `HTMLFormRenderer` each time?
Instead my current "solution" is that I extended the tag with another parameter (form_template) which I then insert into the style dict and pass that to HTMLFormRenderer. If this parameter is present, the given form template will be used.

6. Another issue I am facing is giving the form & field templates more context: more context variables that is. To be precise, I need some settings.py variables. 
Again, one could add parameter to add to `style` dict or simply forward the entire template context. The latter is definitely easier, but I'm not sure whether you'd find that "polluting" or not.

7. I'm pretty sure I DON'T understand how the `template` member of `style` is used in field rendering. The way I see it is that if set, ALL fields would be using the same template? Also, how would one go about setting this member if render_form doesn't give us the opportunity and the template being used for rendering forms is always the same? OTOH if rendering forms by hand ONLY using render_field tags also makes it a bit awkward as we need a separate style variable for each field being rendered.

8. Finally, I am also at odds with the design where `HTMLFormRenderer` is the entity deciding on standard field templates. Is there a particular reason that the approach is different here than otherwise (ViewSet gladly takes a template variable which it then uses in rendering the ViewSet through `TemplateHTMLRenderer`). I understand the entire problem is quite complex as there are many possible ViewSet renderers but still: wouldn't a `default_style` member in `Field` class be a more versatile approach? That way any `Field` derivative could specify its own template & its parameters already in the code declaring said field instead of forcing the programmer to override `HTMLFormRenderer`

**Comment by carltongibson** [comment]
Hi @velis74 

> ... with offer for a PR remaining for these as well.

Yes please! 😀

**Comment by velis74** [comment]
So you will accept any PR I conjure up? Without discussing proposed solutions?
Can you please just comment shortly on my points whether my direction of thinking is correct or not? I'd really rather not waste your time by implementing something that's at odds with base concepts of the framework.

**Comment by carltongibson** [comment]
I’d suggest you break out the individual points into separate small PRs. The initial docs points are all straightforward. The latter points probably need more discussion, but it’s not yet clear to me what you have in mind. (What would your proposal actually look like? From there it’s easy to comment.)

**Comment by velis74** [comment]
I have submitted the first PR: https://github.com/encode/django-rest-framework/pull/6135

I have found that point 2 was my mistake as I failed to realise that a class had not been added to the form tag as per Bootstrap guidelines. Documentation amended to warn future n00bs like me.
I have found that point 3 was my mistake as clear examples of using template packs are given just below the linked documentation. Must have been low on caffeine at the time...

Please note that the tests are currently failing because of an unrelated issue (seems that a 404 message for not finding a record has been changed in Django making the test_get_instance_view_filters_out_name_with_filter_backend test fail). A quick search for a PR fixing this didn't net me much so maybe I could try and fix this one too? I believe this is also the cause of the build:failing badge on project front github page.

**Comment by velis74** [comment]
It seems that today's patch by @rpkilby to travis.yml fixed my remaining failing test. @carltongibson would it be possible for you to comment on the PR. I really don't dare proceed without the initial one. If FIXES stuff that was wrong or lacking. The other issues I have actually want to CHANGE stuff in the package. I realise it's a huge inconvenience to volunteer team, but I promise the following patches will have a much better effect vs invested time ratio for you guys.
