### ISSUE TITLE
ModelSerializer.create() does not work for model with custom manager

### ISSUE THREAD

**Issue by K0Te** [encode/django-rest-framework#6110]
## Checklist

- [✔️] I have verified that that issue exists against the `master` branch of Django REST framework.
- [✔️] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [✔️] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [✔️] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [✔️] I have reduced the issue to the simplest possible case.
- [✔️] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
`ModelSerializer.create()` does not work for models with custom managers, in case if there is no `model.objects` manager.
Small failing example:
```
class Model(models.Model):
    name = models.CharField(max_length=64)
    all_objects = models.Manager()

class TestModelSerializer(serializers.ModelSerializer):
            class Meta:
                model = Model
                fields = ('name',)

TestModelSerializer().create({'name': 'test_name'})
``` 

## Expected behavior
Object should be created, either using default managers `create()`, or just by creating model instance and saving it.

## Actual behavior
Exception is raised:
```
rest_framework/serializers.py:940: in create
    instance = ModelClass.objects.create(**validated_data)
E   AttributeError: type object 'IssueNewTestModel' has no attribute 'objects'
```

**Comment by carltongibson** [comment]
Closed by #6111
