### ISSUE TITLE
Message attribute of permission class ignored when client is anounymous

### ISSUE THREAD

**Issue by Yaser-Amiri** [encode/django-rest-framework#6117]
## Steps to reproduce
I have a viewset that uses this permission class:

```
class ResourceBlahPermissions(permissions.BasePermission):

    def has_permission(self, request, view):
        if request.META.get('REMOTE_ADDR').startswith('192.168.134.'):
            self.message =  'Nobody from your LAN can access this endpoint'
            return False
        if request.user.is_authenticated and not request.user.is_staff:
            self.message =  'You are not admin'
            return False
        return True
```
## Expected behavior

Sometimes I need to send custom messages to my client in permission class (event anonymous users).
I need to show some custom message to my anonymous users.

## Actual behavior
In the example I wrote, the first condition ignores messages and shows "Authentication credentials were not provided.' to anonymous users.

**Comment by rpkilby** [comment]
Hi @Yaser-Amiri. I would recommend writing a [custom authenticator](http://www.django-rest-framework.org/api-guide/authentication/#custom-authentication) and adding it at the end of the authenticators list. While you wouldn't necessarily authenticate a user, you would be blocking certain classes of anonymous users.

**Comment by Yaser-Amiri** [comment]
Hi @rpkilby ,Thanks for following up.
It's not about authentication! Let me explain an example with more details,
There is a resource name Blah, It has a viewset an model serializer and ..., and It's API is public (for list and retrieve), I want to to prevent some objects to be shown to client based on some conditions (for example those created in more than 1 month ago/ or any other condition based on object ), Writing custom authentication won't work for this, I need object and view action and ...!

**Comment by rpkilby** [comment]
In that case, I would either raise the `PermissionDenied` exception directly in the authentication class or alter the behavior of the `permission_denied` method locally.
