### ISSUE TITLE
Exceptions error details malformed

### ISSUE THREAD

**Issue by ogrimator** [encode/django-rest-framework#6123]
https://github.com/encode/django-rest-framework/pull/5787/commits/f6d203e96a0585ea7e2724eb03174e75eefcd6e1
The following commit has added a new functions for errors processing in Rest Framework but now the error information is malformed.

The following line in current Master branch will produce an output in text form that looks like a line of code you would like to execute and return result:
https://github.com/encode/django-rest-framework/blob/90ed2c1ef7c652ce0a98075c422d25a632d62507/rest_framework/exceptions.py#L88

Problem is resolved when this function is changed to something that I think author intended to do:
```python
    def __repr__(self):
        return unicode_to_repr(
               ErrorDetail(
                      string=six.text_type(self), 
                      code=self.code
                )
        )
```

**Comment by sdushay** [comment]
Was this ever resolved?

**Comment by xordoquy** [comment]
It does not look like it's been resolved.
A good starting point would be to setup a failing test case to demonstrate the issue.
