### ISSUE TITLE
Django REST Framework: Browsable API hangs infinitely for create and update view while admin site and postman works very fast and correctly.

### ISSUE THREAD

**Issue by Ziruliu** [encode/django-rest-framework#6127]
I have two models with a many-to-one relationship, and I set up viewset for both models. While I was trying to view them via browser, the first model works correctly, but the second model hang there infinitely, and finally led the server to be crashed. I figured out this only happens if I tried to create or update model, and strangely, when I tried to do the same actions on admin site or postman, everything worked correctly.

I guess there might be an issue with the browsable API; anyone knows how to fix it?

Thanks a lot.

**Comment by rpkilby** [comment]
Hi @Ziruliu. It's not really possible to debug your issue without further information. I would recommend reducing the problem to a minimal example and then ask for help on the [support](http://www.django-rest-framework.org/#support) channels.

If you can determine that there is indeed an issue with DRF, then that minimal example/test case will help finding the exact cause.

**Comment by Ziruliu** [comment]
The two models have 700 and 6000 instances, respectively. I have dealt with models with much more instances, but I have never met a problem like this...

**Comment by tomchristie** [comment]
In that case I’m going to have to defer to @rpkilby’s answer. You’ll need to reduce this to a reproducible case in order for us to be able to look into it.
