### ISSUE TITLE
Do not swallow or misuse AttributeError

### ISSUE THREAD

**Issue by dmugtasimov** [encode/django-rest-framework#6129]
If I have a model with a property defined that is used by serializer

```
class MyModel(Model):
    @property
    def value(self):
        return object().a

class MyModelSerializer(Serializer):
    value = serializers.JSONField(read_only=True)

    class Meta:
        model = MyModel
        fields = ('value',)
```

then exception is swallowed by internal DRF code which make debugging much harder.

It seems that offending code is here:
https://github.com/encode/django-rest-framework/blob/a628a2dbce8f8f3047d30fe5345f86ae843bcdcc/rest_framework/fields.py#L454

Please, use a different technique to detect existence of an attribute for a serialized instance.

**Comment by tomchristie** [comment]
> Please, use a different technique to detect existence of an attribute for a serialized instance.

We’d consider Pull Requests or concrete suggestions, yup.

**Comment by dmugtasimov** [comment]
Sorry, I do not have time for either of them. I hope you will change this behavior along with occasional refactoring in the future (unless you forget because you closed the issue).
