### ISSUE TITLE
anon throttle checks with Tokenauthentication

### ISSUE THREAD

**Issue by udipercepto** [encode/django-rest-framework#6136]
When using Tokenauthentication the throttle to anonymous user will never get called. This is because the Tokenauthentication will raise "invalid token" for requests with invalid token...
This way the anonymous throttle doesn't really protect against brute force attempts of the Token Authentication.
![image](https://user-images.githubusercontent.com/17979818/44405958-2ff91b00-a563-11e8-9b07-2460df2cc3a5.png)

Also the check_permissions in APIView is checked before the throttle, so even if the first issue is fixed the permissions will raise error before the throttle will block the attempts.

![image](https://user-images.githubusercontent.com/17979818/44405815-d7298280-a562-11e8-91d6-6caa1f1430f5.png)

To my understanding the anon throttle mechanism built in order to block this kind of attempts and currently it does not.

**Comment by tomchristie** [comment]
If the request is being denied because the authentication failed then it’s irrelevant if throttling checks are also applied or not.

**Comment by tomchristie** [comment]
Closed due to misreading ticket.

Brute force attacks aren’t really feasible against API tokens tho.

**Comment by tomchristie** [comment]
Going to treat this as stale/insufficient priority since it's not being re-raised
