### ISSUE TITLE
DateTimeField should be able to keep original timezone info

### ISSUE THREAD

**Issue by favll** [encode/django-rest-framework#6140]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce / Actual behavior
DRF's `DateTimeField` has no option to keep a `datetime`'s original timezone information during serialization/deserialization. Here a serialization example:

0. Set `USE_TZ = True` and `TIME_ZONE = "UTC"`.
1. Consider the following `datetime` object: `dt = datetime.datetime(2018, 9, 4, 7, 30, tzinfo=<DstTzInfo 'Europe/Berlin' CEST+2:00:00 DST>)`.
2. Serialize it with `serializers.DateTimeField().to_representation(dt)`

This yields `'2018-09-04T05:30:00Z'` which represents the datetime in the UTC timezone.

## Expected behavior
The serialized datetime is correct, however, does not contain any information about the original timezone. DRF's `DateTimeField` should provide an option to preserve this timezone info by instead serializing to: `'2018-09-04T07:30:00+02:00'`.

## Why?
While the returned string is correct, there are use cases in which a frontend (API consumer) might want to display the datetime in the timezone it was originally in. For example, a flight ticket search engine generally displays any datetimes in the local timezone of the airport. So instead of displaying the departure time of a flight in UTC it generally displays it in the timezone of the airport. This is however not possible with the current implementation of `DateTimeField`.

## Possible Solution
Would the maintainers be open to a PR that adds an option to the `DateTimeField` that would allow it to deserialize / serialize datetimes while keeping their original datetime? I can go into depth about other use cases and possible implementations, however, I would like to first know if this idea is welcome in general.

This problem was already mentioned in #3732 and generally well received ("I’m really happy to take a PR on this."), however, the issue originally addressed another problem and was subsequently closed before the issue I am mentioning here was addressed.

**Comment by carltongibson** [comment]
Ref #5435 and related.

**Comment by favll** [comment]
![image](https://user-images.githubusercontent.com/9731313/44581230-25c26100-a79d-11e8-9d35-0f6742d03c9d.png)

This is how we currently handle the issue, so it would actually be quite easy to add a boolean flag to `__init__` that will activate this behavior.

**Comment by agalazis** [comment]
to me not being able to store timezone is like losing data as an event happens in a specific timezone. This could be stored in an all in one fashion but limitations imply saving event timezone elsewhere

**Comment by georgek** [comment]
Agreed, this causes data loss by converting the timestamp into the timezone of the server.

**Comment by xordoquy** [comment]
I believe this would be a nice thing to have... but I suspect the implementation will not be possible out of the box.
To my understanding, Django converts timezone aware DateTime into UTC (if `USE_TZ` is set) to store it as such in PostgresQL. That means that the TZ info must be stored in a second field *or* Django implementation should be updated which places the change out of the core boundaries.
Am I missing something ?

**Comment by georgek** [comment]
It looks like that is case, yes. But all supported versions of Postgres support a timestamp with timezone type at no extra cost compared to a regular timestamp. I have a feeling Django has this behaviour to support other DBs that don't support storing the timezone.

In any case, it does look like an upstream issue rather than a DRF issue.
