### ISSUE TITLE
Translated the API Guide document into Korean.

### ISSUE THREAD

**Issue by KimDoKy** [encode/django-rest-framework#6144]
I translated the API Guide document into Korean.

But I do not know where to file path the translated file.

And I want to know if the translated file should have a status of .md or mkdocs.

**Comment by rpkilby** [comment]
Hi @KimDoKy, mkdocs unfortunately does not support translations. We might be able to address this once https://github.com/mkdocs/mkdocs/issues/211 is resolved.
