### ISSUE TITLE
DecimalField should keep input precision

### ISSUE THREAD

**Issue by l0b0** [encode/django-rest-framework#6149]
## Checklist

- [ ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question.
- [x] This cannot be dealt with as a third party library.
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

```
>>> from rest_framework.serializers import DecimalField
>>> DecimalField(max_digits=40, decimal_places=20).to_internal_value('4.0')
Decimal('4.00000000000000000000')
```

## Expected behavior

The result should be `Decimal('4.0')`.

## Actual behavior

See above.

## Rationale

You might have heard the joke about the museum staff member informing the visitor that the dinosaur on display is 65 million and five years old. When the visitor, astonished, asks how they know so precisely, the staff member informs them that it's really quite simple: the dinosaur was found to be 65 million years old, and that was five years ago.

I'm working on a system which will receive engineering measurement values with various precision in text form - some are integers, others have up to at least six decimal digits of precision. It is important that these values are stored and presented with the same precision as they were recorded. Precision coercion also makes automated testing very awkward, because none of the tests look sensible when I assert that storing a specific number results in a completely different number being returned.

PostgreSQL at least does not normalize decimal numbers to a specific number of decimal places when inserting or selecting, so this should work just fine with existing databases.

**Comment by xordoquy** [comment]
The documentation says:
"`decimal_places` The number of decimal places to store with the number."
Thus the actual behavior is expected.
What you need is something different from the `DecimalField` provided by Django REST framework and Django.

**Comment by l0b0** [comment]
I wasn't trying to say it doesn't work as documented. I'm just saying how it works in Django REST Framework and Django is contrary to how at the very least Python `Decimal` and PostgreSQL `decimal` work, diminishing the usefulness of `DecimalField`.

**Comment by carltongibson** [comment]
Django REST Framework is merely mirroring the behaviour of the underlying Django field here, as it should. If you want to make an improvement in Django I suggest you take it up there. It's not an addressable bug for Django REST Framework.

**Comment by l0b0** [comment]
As far as I can tell Django's DecimalField does the right thing:

```
>>> from django.db.models.fields import DecimalField
>>> DecimalField(max_digits=40, decimal_places=20).to_python('4.0')
Decimal('4.0')
>>> DecimalField(max_digits=40, decimal_places=20).get_prep_value('4.0')
Decimal('4.0')
```

I'm not sure if either of these are the equivalent of `to_internal_value`; please let me know if I'm checking the wrong thing.
