### ISSUE TITLE
fields

### ISSUE THREAD

**Issue by little-firefly** [encode/django-rest-framework#6150]
## Checklist

- [ ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [ ] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

**Comment by tomchristie** [comment]
![fields](https://user-images.githubusercontent.com/647359/44786129-10797800-ab8b-11e8-919c-3e01fb368b31.jpg)

**Comment by little-firefly** [comment]
I am so sorry. I didn't want to create an issue.
