### ISSUE TITLE
How to modify the final result of the rest_framework response?

### ISSUE THREAD

**Issue by ReadRou** [encode/django-rest-framework#6153]
I have been looking for a long time official document, but I didn't get the answer I wanted. I spent 2 hours here. :)

I want to modify the final result and add a custom field to this result. What should I do?

**Comment by ReadRou** [comment]
![image](https://user-images.githubusercontent.com/30749019/44951953-cc48e900-aea4-11e8-8e85-adeb6855de0f.png)
My implementation is like this.

But I think the code is not good enough. Which old driver can tell more elegant writing?

**Comment by carltongibson** [comment]
You're approach seems fine. 

Either that or you could create a serialiser for the final response, then nesting the model serialiser. 

In any case the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
