### ISSUE TITLE
how to add/update field value in nested list(using MPTT model for tree view)

### ISSUE THREAD

**Issue by xporium** [encode/django-rest-framework#6157]
Hi,
please any one tell me how to update/insert field and value in nested json list based on condition.
 
like first my nested json list is like 

objlist= [{ "label": "1", "children": [{ "label": "2", "children": [{ "label": "3" }]}]}{"label": "4","children": [{ "label": "5"},{ "label": "6"}]}{"label":"7"},{"label":"8"}]

after implement recursion and logic my output will like below\

objlist= [{ "label": "1", "children": [{ "label": "2", "children": [{ "label": "3" }]}], "checked":"true"}{"label": "4","children": [{ "label": "5", "checked":"true"},{ "label": "6"}]}{"label":"7"},{"label":"8", "checked":"true"}]

and achieve this the code would be written below

queryset = models.Master_Industry.objects.filter(parent__isnull=True)
serializer1 = masterserializer.IndustrySerializer(queryset, many=True)
json_string = json.dumps(serializer1.data)    
stringobj = 1,5, 8
my_dict = json.loads(json_string)

for item in my_dict:
	if item["value"] in stringobj:
		item["checked"] = True
		continue    

	for itemchild in item["children"]:
		if itemchild["value"] in stringobj:
			itemchild["checked"] = True
			continue     

		for itemchildinner in itemchild["children"]:
			if itemchildinner["value"] in stringobj:
				itemchildinner["checked"] = True
				continue
print(my_dict)      

so please tell me how to resolve this?
thanks

**Comment by rpkilby** [comment]
Hi @xporium - the issue tracker is intended for bug reports & feature requests. If you're looking for [help](http://www.django-rest-framework.org/#support), I'd recommend either the IRC channel or discussion group.
