### ISSUE TITLE
Retrieve concrete value from object

### ISSUE THREAD

**Issue by kaldown** [encode/django-rest-framework#6162]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
```
d = {'a':1, 'b': {'c':3}}
class S(serializers.Serializer):
  b = serializers.JSONfield(source='b.c')

s = S(data=d)
s.is_valid()
s.data
```
## Expected behavior
Want to set a 'b' field to 'c' value (3)
How to achieve that without redefining field class every time?
For instance I need to use custom field in many serializers, but want to return only concrete field.
I assume source should 'source' a field from object, but not.

## Actual behavior
returns whole dict

**Comment by kaldown** [comment]
http://www.django-rest-framework.org/api-guide/serializers/#example

**Comment by xordoquy** [comment]
I don't see the whole dict returned. In fact, I have a non valid serializer with error being: `{'f': [ErrorDetail(string='This field is required.', code='required')]}`

`source` argument is used for serialization ie, from Python complex objects to simple type objects.
In your example, you're trying to deserialize which expects data such as {'f': 3} and would return {'b', {'c': 3}}

Also please note that the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
