### ISSUE TITLE
why Django serialization takes 3 to 30 seconds

### ISSUE THREAD

**Issue by StupidTAO** [encode/django-rest-framework#6170]
record = ExchangeCoinTransaction.objects.filter(eth_tx_hash=eth_tx_hash)
if not record:
    return False, "the eth transaction is't exchange coin transaction"
json_rec = serializers.serialize("json", record)
record = json.loads(json_rec)

#This simple query database, and serialize the results of the operation takes 3 to 4s, similar operations may take more time

**Comment by xordoquy** [comment]
Hi,

The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
