### ISSUE TITLE
GenericAPIViews cannot raise APIExceptions from get_queryset

### ISSUE THREAD

**Issue by tyrion** [encode/django-rest-framework#6184]
If I want to raise an APIException in the `get_queryset` method of a `GenericAPIView`, I get an error (during the exception handling process) when browsing the html version of the APIs, because the renderer tries to call `get_queryset` again.

This happens in the `BrowsableAPIRenderer.get_filter_form` method. There is a check to prevent running the method if the view does not use filters (see: [renderers.py](https://github.com/encode/django-rest-framework/blob/fc6cbb5b2618b9372622fb052cb647f44476a32f/rest_framework/renderers.py#L622)), but unfortunately every `GenericAPIView` always defines the `filter_backends` attribute.

```python
class ExampleView(GenericAPIView):
    def get_queryset(self):
        raise APIException('Error')

    def get(self, request, format=None):
        self.get_queryset()
```

As a workaround I could use something like this, to hide the `filter_backends` attribute, but I think it's very ugly:
```python
class HideProperty:
    def __get__(self, instance, owner):
        raise AttributeError()

class ExampleView(GenericAPIView):
    filter_backends = HideProperty()
    ...
```

I noticed that there are many issues similar to this one (e.g. #4240 ), but none of them seem to address my problem of wanting to raise an APIException from `get_queryset`.

If you consider having an empty list as `filter_backends` to be different than not having the attribute defined at all, then I would suggest checking if the attribute is `None`. This would allow me, at least, to override this behaviour in a subclass, without relying on hacks, by just defining `filter_backends = None`.
Even though IMHO this behaviour is very counterintuitive and should be turned off by default.

**Comment by xordoquy** [comment]
What would the use case be to have an invalid queryset but still try to display the browsable API ?

**Comment by tyrion** [comment]
What I am doing is following the example given in the documentation about filtering (here: http://www.django-rest-framework.org/api-guide/filtering/#filtering-against-query-parameters ). I just extended it so that it raises a `ParseError` in case the input is malformed.

So the use case would be having the browsable API display the expected error, instead of crashing. Am I doing something wrong?

**Comment by tyrion** [comment]
I found a probably better workaround that the one I mentioned above, that is raising the exception in `filter_queryset` instead of `get_queryset`. I discovered the method by reading the code and, even if for some reason it's mentioned that I am "unlikely to want to override this method", it seems to work very well for my purpose (as the method is not called twice as `get_queryset` is).

You may want to document this method before closing the issue, maybe under the filtering example that I linked in my previous message. Otherwise, if you don't want this method to be overridden at all, I think this issue should still be addressed somehow.

**Comment by rpkilby** [comment]
I'm going to close off for now. That said, happy to review PRs for this. e.g., something that indicates that DRF generally expects `get_queryset` to return a queryset and not raise exceptions.
