### ISSUE TITLE
i get this error from my API but on refresh it works as expected.

### ISSUE THREAD

**Issue by TAUFEEQ1** [encode/django-rest-framework#6194]
_NamespacePath' object has no attribute 'sort'

Request Method: | GET
-- | --
http://compute.glassociates.engineering/tasks/?projid=1
2.1.1
AttributeError
'_NamespacePath' object has no attribute 'sort'
/home/nsamba/projects/global/project_manager/project_manager/lib/python3.6/site-packages/pkg_resources/__init__.py  in _rebuild_mod_path, line 2066
/home/nsamba/projects/global/project_manager/project_manager//bin/python
3.5.2
['/home/nsamba/projects/global/project_manager/project_manager/lib/python3.6/site-packages',  '/usr/lib/python35.zip',  '/usr/lib/python3.5',  '/usr/lib/python3.5/plat-x86_64-linux-gnu',  '/usr/lib/python3.5/lib-dynload',  '/usr/local/lib/python3.5/dist-packages',  '/usr/lib/python3/dist-packages',  '/home/nsamba/projects/global/project_manager/project_manager/manager',  '/home/nsamba/projects/global/project_manager/project_manager/manager/manager',  '/home/nsamba/projects/global/project_manager/project_manager/lib/python3.6/']
Tue, 18 Sep 2018 11:35:54 +0000

**Comment by xordoquy** [comment]
Hi,

I'm afraid there isn't much we can do without a test case we can reproduce.
Please also note that this is a bug tracker.
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take usage questions.
Thanks!
