### ISSUE TITLE
self.action is set to None during HEAD request

### ISSUE THREAD

**Issue by OskarPersson** [encode/django-rest-framework#6196]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.

## Steps to reproduce
Send a HEAD request to a viewset which prints `self.action` in `get_queryset`:

```
class MyViewSet(viewsets.ModelViewSet):
    def get_queryset(self):
        print self.action
```

## Expected behavior
During a `HEAD` request this should, just like during `GET` request, print `list` or `retrieve` depending on the route requested.

## Actual behavior
`None` is printed

**Comment by xordoquy** [comment]
This is a side effect of:
1. [default head being set to get](https://github.com/encode/django-rest-framework/blob/b090ae9d30f26117f474479b853289a46c6ca615/rest_framework/viewsets.py#L109)
2. routers not mapping `head`

The `self.action` mapping is performed [here](https://github.com/encode/django-rest-framework/blob/b090ae9d30f26117f474479b853289a46c6ca615/rest_framework/viewsets.py#L145)

**Comment by OskarPersson** [comment]
One fix seems to be to just add 'head' with the same value as 'get' to the mappings in SimpleRouter: https://github.com/encode/django-rest-framework/blob/master/rest_framework/routers.py#L123.

Not sure how it should be tested and if it creates some other problems though.

**Comment by xordoquy** [comment]
indeed. I don't see any side effect and it doesn't look like the mapping is tested.
We'll need to add a line about it in the release note though.

**Comment by Sinkler** [comment]
> One fix seems to be to just add 'head' with the same value as 'get' to the mappings in SimpleRouter: https://github.com/encode/django-rest-framework/blob/master/rest_framework/routers.py#L123.

One more action is needed to fix it for dynamic (detail) routes: add `head` [here](https://github.com/encode/django-rest-framework/blob/3.9.2/rest_framework/decorators.py#L135) or [here](https://github.com/encode/django-rest-framework/blob/3.9.2/rest_framework/routers.py#L232) something like this:
```python
    if 'get' in action.mapping and 'head' not in action.mapping:
        action.mapping['head'] = action.mapping['get']
```

**Comment by Bitblade** [comment]
It doesn't seem this was implemented yet, so I made these workarounds. 
Note: This does not include the suggestion in https://github.com/encode/django-rest-framework/issues/6196#issuecomment-479618481. It will not work for those routes. 

```python3
class PatchedDefaultRouter(routers.DefaultRouter):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for route in self.routes:
            if hasattr(route, 'mapping'):
                route.mapping['head'] = 'retrieve' if route.detail else 'list'


class PatchedSimpleRouter(routers.SimpleRouter):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for route in self.routes:
            if hasattr(route, 'mapping'):
                route.mapping['head'] = 'retrieve' if route.detail else 'list'
```
