### ISSUE TITLE
urlize_quoted_links filter is not registered correctly

### ISSUE THREAD

**Issue by dkliban** [encode/django-rest-framework#6201]
## Steps to reproduce
Put the following in a template:

```
{% autoescape off %}{% for key, val in response_headers|items %}
<b>{{ key }}:</b> <span class="lit">{{ val|break_long_headers|urlize_quoted_links|my_filter }}</span>{% endfor %}

</span>{{ content|urlize_quoted_links|my_filter }}</pre>{% endautoescape %}
</div>
```

## Expected behavior

my_filter receives unescaped input text

## Actual behavior

my_filter receives escaped text

I've put together a PR for this issue. https://github.com/encode/django-rest-framework/pull/6191

**Comment by dkliban** [comment]
@tomchristie Please take a look at this issue. I made the PR based on the documentation from django[0].

[0] https://docs.djangoproject.com/en/2.1/howto/custom-template-tags/#filters-and-auto-escaping

**Comment by rpkilby** [comment]
Somehow this was detached from the milestone..
