### ISSUE TITLE
How make django API work only in specific package name app?

### ISSUE THREAD

**Issue by asfarmed** [encode/django-rest-framework#6205]
Hi 
I created an Android application and linked it to a control panel and a database using django.

But what I noticed was that in this library,my api link are accessible in general,

and I do not want my api to be accessed or used by anyone else.

how make it worked in spisific package name ?

**Comment by tomchristie** [comment]
Hi there & thanks for your question.

The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions.

Thanks! 😀
