### ISSUE TITLE
JSONField form data in a related model renders as python dict

### ISSUE THREAD

**Issue by aleehedl** [encode/django-rest-framework#6211]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

Assuming the following models, serializers and viewsets:

```
# models.py

from django.db import models
from django.contrib.postgres.fields import JSONField

class RelatedModel(models.Model):
    json_content = JSONField()


class MainModel(models.Model):
    name = models.CharField(max_length=64)
    related_object = models.ForeignKey(
        to=RelatedModel,
        on_delete=models.CASCADE
    )

# serializers.py
class RelatedModelSerializer(serializers.ModelSerializer):
    class Meta:
        model = RelatedModel
        fields = '__all__'


class MainModelSerializer(serializers.ModelSerializer):
    related_object = RelatedModelSerializer()

    class Meta:
        model = MainModel
        fields = (
            'id', 'name', 'related_object'
        )

# views.py
class MainModelViewSet(viewsets.ModelViewSet):
    serializer_class = MainModelSerializer
    queryset = MainModel.objects.all()


class RelatedModelViewSet(viewsets.ModelViewSet):
    serializer_class = RelatedModelSerializer
    queryset = RelatedModel.objects.all()

# Create models in shell:

rm = RelatedModel.objects.create(json_content={'bool': False, 'text': 'Test text'})
MainModel.objects.create(name='Main', related_object=rm)
```

Then, open the MainModel instance in the Browsable API and look for the content in the form.

## Expected behavior

Form data for the `json_content` field to be in JSON format, that is: 
```
{
    "bool": false,
    "text": "Test text"
}
```

## Actual behavior
Json content rendered as a python dict, that is `{'bool': False, 'text': 'Test text'}`, as shown in:
![screenshot from 2018-09-25 18-01-56](https://user-images.githubusercontent.com/220983/46023361-24ae8780-c0ed-11e8-8569-fd1f6ed69615.png)

When viewing the RelatedModel itself (using RelatedModelViewSet) the json content is rendered fine.

**Comment by gabomgp** [comment]
Is there a workaround for this problem?, I think the same problems occurs with nested serializers in my REST Api output. The JsonField in the related entity is returned as string with a python dict and not is valid JSON.

**Comment by giancarlopro** [comment]
in [serializers#549](https://github.com/encode/django-rest-framework/blob/master/rest_framework/serializers.py#L549) when a field is a Serializer, thats the case with related_object, it returns a `NestedBoundField` to parse it.
after that all fields found by `NestedBoundField` will be parsed as a `BoundField`, because `NestedBoundField` can't identify if the field is a json field.

You can see this here in [serializer_helpers#119](https://github.com/encode/django-rest-framework/blob/master/rest_framework/utils/serializer_helpers.py#L119)

as a workaround, i did this inside `BoundField.as_form_field`, put the code from JSONBoundField that parses the json from `value` inside it:
```Python
# serializer_helpers#81
def as_form_field(self):
    value = '' if (self.value is None or self.value is False) else self.value
    # if value is a valid json then we parse it
    if not getattr(value, 'is_json_string', False):
        try:
            value = json.dumps(self.value, sort_keys=True, indent=4)
        except (TypeError, ValueError):
            pass

    return self.__class__(self._field, value, self.errors, self._prefix)
```

and it rendered as expected:
![image](https://user-images.githubusercontent.com/9954401/46918543-928df680-cfa9-11e8-8815-b098627ef1ec.png)

i think thats not the best solution, but now the problem's found. I woudl like to help with a PR to fix this, if you could give me instructions.

sorry for my bad english, thats all.

**Comment by aleehedl** [comment]
Yes, this workaround works for this case but I'm afraid it might break something else. But it gave me the idea that by adapting the `Serializer.__getitem__` logic into `NestedBoundField.__getitem__`, the JSONBoundField would be used properly.

**Comment by giancarlopro** [comment]
You waited 20 days to get a hint on this, and couldn't wait 1 day for me to make a PR fixing it. I was gonna make a PR for the hacktoberfest event, but you were faster than me, that's discouraging for me related to contribute with open source again.
Had to say that to express how i feel.
Problem's solved. Peace.

**Comment by aleehedl** [comment]
I'm sorry, I didn't mean to steal your PR. I personally do not care for my open source reputation, so if you wish to make a PR to this issue and improve upon my solution, feel free to do so. I use DRF in my daily job so I simply wanted to get the issue resolved as quickly as possible without thinking any further. Your contribution certainly hinted me to the right direction.

Alternatively, if you can come up with a way to attribute you in this PR, I'm open for suggestions.

**Comment by giancarlopro** [comment]
it's ok man, i just got a bit frustrated, but our purpose here is the same, to get the issue fixed. your solution is already made, let's not waste more time, right?
i just overreacted, sorry.
