### ISSUE TITLE
Consider omitting link to drf v2

### ISSUE THREAD

**Issue by morenoh149** [encode/django-rest-framework#6213]
I naively was reading the v2 docs http://www.tomchristie.com/rest-framework-2-docs/ because on the main site it said "Note: This is the documentation for the version 3 of REST framework. Documentation for version 2 is also available.".

As django 2.x is fairly new, I misread and assumed drf was lagging with a matching version. In reality the current releases of drf are 3.8.x. Consider removing this mention at the top of the homepage. Or maybe add a version navigator in the lower right corner, same as the django docs.

**Comment by xordoquy** [comment]
Enough time went by since DRF 3.x started.
I agree we can remove that warning

**Comment by rpkilby** [comment]
Hi @morenoh149. This has already been dropped in #5993. The docs will be updated once DRF 3.9 is released.
