### ISSUE TITLE
CharFields don't accept lazy (eg translated) strings

### ISSUE THREAD

**Issue by davidszotten** [encode/django-rest-framework#6214]
```
    def test_lazy(self):

        from django.utils.translation import ugettext_lazy
        class ExampleSerializer(serializers.Serializer):
            char = serializers.CharField()
        serializer = ExampleSerializer(data={'char': ugettext_lazy('abc')})
        assert serializer.is_valid()
```

fails with `{'char': [ErrorDetail(string='Not a valid string.', code='invalid')]}`

is this expected? it doesn't seem unreasonable to also accept lazy strings, though i may be missing some context

thanks!

**Comment by xordoquy** [comment]
I don't see a reason your client would send lazy strings and parsers don't return any.
lazy_strings will be correctly processed for serialization but I can't think a use case where we're have some during deserialization.

**Comment by davidszotten** [comment]
i also serialize data from other places in my app (which does include lazy strings).

**Comment by xordoquy** [comment]
Then you'll have to ensure they get evaluated first.
The [documentation](http://www.django-rest-framework.org/api-guide/serializers/#deserializing-objects) states:

> we restore those native datatypes into a dictionary of validated data

Deserialization - which is what is done in your example - is supposed to move from basic types to more complex ones. lazy strings are not a basic type and I don't think it's a good thing to allow them here.
Are you sure what you're after isn't:

```
serializer = ExampleSerializer(instance={'char': ugettext_lazy('abc')})
assert serializer.data == 'abc'
```

**Comment by davidszotten** [comment]
i suspect the codebase i'm looking at is abusing drf a bit so not surprised if the use case isn't supported, but wanted to ask. i think i do want `data=` because i want to check `is_valid`

basically the serializers are being used to make sure the data returned from views conforms to schemas defined by them (which is why they're instantiated with dicts but may have eg lazy strings in them)
