### ISSUE TITLE
Have a problem with auth authenticate

### ISSUE THREAD

**Issue by teguh87** [encode/django-rest-framework#6216]
## Checklist

- [] I have verified that that issue exists against the `master` branch of Django REST framework.
- [] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [] I have reduced the issue to the simplest possible case.
- [] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Actual behavior

This is me or this a bug from this module because I'm always facing problem while using oauth2_provider within this django-rest-framework, I stack trace always showing same error : 

<pre>
 Internal Server Error: /users
dg01         | Traceback (most recent call last):
dg01         |   File "/usr/local/lib/python3.6/site-packages/rest_framework/request.py", line 77, in wrap_attributeerrors
dg01         |     yield
dg01         |   File "/usr/local/lib/python3.6/site-packages/rest_framework/request.py", line 223, in user
dg01         |     self._authenticate()
dg01         |   File "/usr/local/lib/python3.6/site-packages/rest_framework/request.py", line 376, in _authenticate
dg01         |     user_auth_tuple = authenticator.authenticate(self)
dg01         | AttributeError: 'IsAuthenticated' object has no attribute 'authenticate'
dg01         |
dg01         | During handling of the above exception, another exception occurred:
</pre>

Please help me for fixing this issue

**Comment by xordoquy** [comment]
Hi,

This is an issue tracker. We need minimum information to reproduce bugs if you think there's one.
Note that the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!

**Comment by teguh87** [comment]
Thanks for fast response

I been fixed this problem by disabled the  <pre>DEFAULT_AUTHENTICATION_CLASSES</pre> and  unset <pre>rest_framework.permissions.IsAuthenticated</pre>

this completed configuration
<pre>
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
        # 'rest_framework.permissions.IsAuthenticated',
    )
}
</pre>

Question : How do I set the permission in rest api request?
