### ISSUE TITLE
rest_framework.documentation lose filter_fields and pagination parameters when using @action

### ISSUE THREAD

**Issue by jhd4tmr** [encode/django-rest-framework#6217]
## Checklist

- [ 1 ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [ ] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

suppose i have a viewset named BlogViewSet here.

```
class BlogViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Blog.objects.filter(is_published=True).prefetch_related('tags').order_by('-update_time')
    serializer_class = serializers.BlogSerializer
    pagination_class = StandardResultsSetPagination
    e = ['tags__text', 'language']
    lookup_field = 'uri'

    def list(self, request, *args, **kwargs):
        queryset = self.filter_queryset(self.get_queryset())

        page = self.paginate_queryset(queryset)
        if page is not None:
            serializer = serializers.BlogListSerializer(page, many=True)
            return self.get_paginated_response(serializer.data)

        serializer = serializers.BlogListSerializer(queryset, many=True)
        return Response(serializer.data)

    @action(detail=False, url_path='uris')
    def uris(self, request):
        uris = list(map(lambda x: {'uri': x.uri, 'date': x.update_time}, self.queryset))
        return Response(uris)

    @action(detail=True)
    def view(self, request, uri):
        plus_blog_visit(uri)
        return Response()

    @action(detail=False)
    def hottest(self, request):
        uris = list(map(lambda x: {'uri': x.uri, 'date': x.update_time}, self.queryset))
        return Response(uris)

```

I add it to the router and i can successfully visit the different routers of  my api. But the docs generated from the rest_framework.documentation is not right.

## Expected behavior

![](https://www.dota2sites.com/media/images/blog/725DF9F5-9A01-4D1F-8369-DAACB1192D6D.png)

![](https://www.dota2sites.com/media/images/blog/86E72A25-F377-4864-8D70-941D47F9E039.png)

I want all the functions in the viewset can be filtered by the parameters i set in the viewset. Such like the filter_fields and pagination backend.

## Actual behavior

![](https://www.dota2sites.com/media/images/blog/146A1074-330D-4AD7-B592-9104DD188315.png)

![](https://www.dota2sites.com/media/images/blog/F6C908DE-6CFC-4671-BB51-1F645B10EED0.png)

Actually, i can not filter my customized functions like hottest in the doc.

**Comment by rpkilby** [comment]
Hi @jhd4tmr. Have you tried the master branch? There are some changes in the upcoming 3.9 release that might have inadvertently fixed this for you.

**Comment by rajeshyogeshwar** [comment]
I do not want to do a me too. But I have similar issue, I have viewset with `list`, `retrieve` functions. I am trying to use separate schemas for `list` and `retrieve` because my `list` will have quite a few query parameters and I want to highlight them. But nothing shows up.

I am using `v3.9.0` of django rest framework.

**Comment by auvipy** [comment]
closing this as part of deprecated Core API
