### ISSUE TITLE
Different license on website and github

### ISSUE THREAD

**Issue by traynier** [encode/django-rest-framework#6226]
## Checklist

- [X] I have verified that that issue exists against the `master` branch of Django REST framework.
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [X] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [X] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
The license on the website at https://www.django-rest-framework.org/#license is different to the license in the source code at https://github.com/encode/django-rest-framework/blob/master/LICENSE.md

## Expected behavior
They be the same.

## Actual behavior
It looks like the github version has been updated but not the website.  Different copyright holder, and an extra clause in the github sourcecode version.

**Comment by tomchristie** [comment]
Resolved in `docs/index.md` - It'll get updated in the next release. Thanks!
