### ISSUE TITLE
Drop Django 1.11 support

### ISSUE THREAD

**Issue by tomchristie** [encode/django-rest-framework#6230]
Once 3.9 has been released I think we probably ought to drop our support for Django 1.11 and Python 2.7. We can start by dropping these from master, and then have our 3.10 release be the first to only support Python 3 onwards.

**Comment by rpkilby** [comment]
Should we drop Python 2 but otherwise support Django 1.11 until the next LTS is released?

**Comment by auvipy** [comment]
Dropping support of python 2 after 3.9 release and waiting for dropping django 1.11 after the release of django 2.2 alpha at least? I would like to volunteer to drop python 2 support if needed.

**Comment by xordoquy** [comment]
Unfortunately some will have gone under our radars.

**Comment by rpkilby** [comment]
Note that we can now drop Python 3.4 as well, which just went EOL on the 18th.

**Comment by webbyfox** [comment]
I did manage to fix test issue at https://github.com/encode/django-rest-framework/pull/6591 which is a fix for https://github.com/encode/django-rest-framework/pull/6277 from @auvipy

**Comment by auvipy** [comment]
@carltongibson IMHO the title should be changed to Python 2.7 and 3.4 drops.... not Django 1.11 before 3.0 release at least.

**Comment by rpkilby** [comment]
Removing from the milestone, since we've already dropped Python 2 support, and I don't think we want to drop Django 1.11 until Django 3.0 is released.
