### ISSUE TITLE
Cannot import generics from rest_framework

### ISSUE THREAD

**Issue by truongthinnguyen** [encode/django-rest-framework#6239]
Hi guys,

I am a newbie with Django rest framework. Can you please help me to resolve issue that my project could not use generics from rest_framework.
My environment as below
* Django 1.8
* Django rest framework 3.8.2
* Python 2.7.15

views.py
```
from rest_framework import generics

from .models import Todo
from .serializers import TodoSerializer

class ListTodo(generics.ListCreateAPIView):
    queryset = Todo.objects.all()
    serializer_class = TodoSerializer


class DetailTodo(generics.RetrieveUpdateDestroyAPIView):
    queryset = Todo.objects.all()
    serializer_class = TodoSerializer
```

settings.py 
```
INSTALLED_APPS = [
    'rest_framework',
    'polls.apps.PollsConfig',
    'todos.apps.TodosConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ]
}
```

I guess there is a problem that my project could not import rest_framework because if I change the code in views.py likes below. It will be worked.
```
from django.shortcuts import render

def index(request):
    return render(request, 'polls/home.html', {})
```

Thanks for reading my issue.

**Comment by xordoquy** [comment]
Hi,

Django 1.8 isn't supported by DRF 3.8.
Please note that the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
