### ISSUE TITLE
Documentation: Links to files on github are split per character

### ISSUE THREAD

**Issue by TauPan** [encode/django-rest-framework#6246]
e.g. https://www.django-rest-framework.org/api-guide/permissions/ instead of linking to the file `permissions.py` links to each letter of the filename separately. Backwards.

Looks like someone wanted to iterate over a list of strings and instead iterated over the string...

**Comment by TauPan** [comment]
Hm, also happens with two files apparently https://www.django-rest-framework.org/api-guide/views/

**Comment by tomchristie** [comment]
Meh. Built with wrong version of mkdocs.
Resolved now, thanks.
