### ISSUE TITLE
Unable to order by JSONField

### ISSUE THREAD

**Issue by SebCorbin** [encode/django-rest-framework#6248]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a pull request.

## Steps to reproduce
Use a nested JSONField for ordering

## Expected behavior
Data should be ordered as per requested

## Actual behavior
Nothing happens

**Comment by tomchristie** [comment]
Not super clear what behaviour ordering against a JSON field would have.
