### ISSUE TITLE
type object 'Token' has no attribute 'objects'

### ISSUE THREAD

**Issue by doctorallen** [encode/django-rest-framework#6250]
I'm trying to implement my own serializer and view to handle Token based authentication with email instead of username. In copying the [ObtainAuthToken](https://github.com/encode/django-rest-framework/blob/3.8.2/rest_framework/authtoken/views.py) view, an error is returned about the `Token` object not having the `objects` attribute. 

## Steps to reproduce
1. `mkdir restframework`
2. `cd restframework/`
3. `virtualenv env`
4. `source env/bin/activate`
5. `pip install django`
6. `pip install djangorestframework`
7. `django-admin startproject tutorial`
8. `cd tutorial`
9.  `python manage.py shell`
  ```
from rest_framework.authtoken.models import Token
Token.objects.all()
```

## Expected behavior
Token class can query objects

## Actual behavior
```
python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 03:03:55)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from rest_framework.authtoken.models import Token
>>> Token.objects.all()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: type object 'Token' has no attribute 'objects'
```

This class (being a django model) should be able to query using the `objects` attribute, should it not?

**Comment by xordoquy** [comment]
That's because you didn't add the auth token in the settings' `INSTALLED_APPS`

**Comment by doctorallen** [comment]
@xordoquy Thank you!

**Comment by aseem-hegshetye** [comment]
Add `'rest_framework.authtoken'` to INSTALLED_APPS list in settings.py

**Comment by tinshade** [comment]
> Add `'rest_framework.authtoken'` to INSTALLED_APPS list in settings.py
Don't forget to run a `python manage.py migrate` after making changes in your settings file

**Comment by nickmccullum** [comment]
This comment solved my problem, 4 years later. Thanks!

**Comment by HRUAS** [comment]
thank you @xordoquy

**Comment by Lokesh-Chigulla** [comment]
I have tried all the steps above but still this error is popping TypeError at /login/
Object of type method is not JSON serializable

**Comment by GunzzGT** [comment]
still returns
rest_framework.authtoken.models.Token.DoesNotExist: Token matching query does not exist.
after adding authtoken in 'INSTALLED_APPS'

traceback shows
    self.token = Token.objects.get(user=self.user)
is that a bad way to get token.objects?

**Comment by vishal-ahirwar** [comment]
> rest_framework.authtoken

thank you :)

**Comment by try515** [comment]
Thank you all, This discussion helped me a lot

**Comment by siecp-1001** [comment]
thanks you

**Comment by IxBahy** [comment]
> still returns rest_framework.authtoken.models.Token.DoesNotExist: Token matching query does not exist. after adding authtoken in 'INSTALLED_APPS'
> 
> traceback shows self.token = Token.objects.get(user=self.user) is that a bad way to get token.objects?


did u find a way to solve this 
I'm using a custom user and I guess its the problem :/
