### ISSUE TITLE
Custom theme for Browsable API not rendering properly

### ISSUE THREAD

**Issue by piby180** [encode/django-rest-framework#6251]
## Checklist

- [x ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Files:

proj
-app
-templates
--rest_framework
----api.html
-proj
--settings.py

api.html

```
{% extends "rest_framework/base.html" %}


{% block bootstrap_theme %}
          <link rel="stylesheet" href="https://bootswatch.com/4/flatly/bootstrap.css" type="text/css">
{% endblock %}


{% block branding %}
    <a class="navbar-brand" rel="nofollow" href="#">
        My Title
    </a>
{% endblock %}
```
settings.py

```
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
```

## Expected behavior

1) Breadcrumb should be rendered properly.
2) GET button should be in proper place.
3) Navbar should be rendered properly.

![image](https://user-images.githubusercontent.com/8469664/47050765-dd725e80-d1a1-11e8-8ce4-fc9ce4e1571e.png)

## Actual behavior

![image](https://user-images.githubusercontent.com/8469664/47050778-e6fbc680-d1a1-11e8-8be3-228186fc27d9.png)

**Comment by rpkilby** [comment]
Hi @piby180. The DRF templates are written against Bootstrap 3, not Bootstrap 4 which has a different markup structure. You'll need to provide your own templates.
