### ISSUE TITLE
'generateschema --description' doesn't accept multi-word strings

### ISSUE THREAD

**Issue by stephenfin** [encode/django-rest-framework#6263]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

$ docker-compose run --rm web python3 -Werror manage.py generateschema --format openapi --url patchwork.ozlabs.org --description 'Testing 123'

## Expected behavior

Output renders with `info.description` set to `Testing 123`.

## Actual behavior

```
$ docker-compose run --rm web python3 -Werror manage.py generateschema --format openapi --url patchwork.ozlabs.org --description 'Testing 123'
Starting patchwork_db_1 ... done
usage: manage.py generateschema [-h] [--title TITLE] [--url URL]
                                [--description DESCRIPTION]
                                [--format {openapi,openapi-json,corejson}]
                                [--version] [-v {0,1,2,3}]
                                [--settings SETTINGS]
                                [--pythonpath PYTHONPATH] [--traceback]
                                [--no-color]
manage.py generateschema: error: unrecognized arguments: 123
```

I'm not sure if this is an issue with Django management commands or an really obvious oversight, but I feel like this _should_ work?

**Comment by carltongibson** [comment]
This works for me testing locally: 

```
$ ./manage.py generateschema --description 'Testing 1,2,3'
info:
  description: Testing 1,2,3
  ...
```

I **very much** suspect that the issue is to do with the way the shell will handle the quotes when passing the arguments down to each child process. You'll have to add the appropriate escaping... (How does a `print(sys.argv)` script look when run via docker? (And so on...) 

Good luck. Please do post the solution when you figure it out!
