### ISSUE TITLE
URL-based versioning messes with openapi output

### ISSUE THREAD

**Issue by stephenfin** [encode/django-rest-framework#6264]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

```
git clone https://github.com/stephenfin/patchwork
cd patchwork
git checkout openapi-test
docker-compose build
docker-compose run --rm web python3 -Werror manage.py generateschema --format openapi
```

## Expected behavior

Output should render correctly.

## Actual behavior

Output includes various `{var}` tags. I can't find any references to these in `django-rest-framework` or `django-filter`, but I'm guessing this where the issue lies nonetheless.

```
$ docker-compose run --rm web python3 -Werror manage.py generateschema --format openapi
Starting patchwork_db_1 ... done
info:
  description: ''
  title: ''
  version: ''
openapi: 3.0.0
paths:
  /api/{var}:
    get:
      operationId: api_read
      parameters:
      - in: path
        name: var
        required: true
        schema:
          description: ''
          title: !!python/tuple
          - ''
          type: string
      tags:
      - api
  /api/{var}bundles/:
    ...
```

I suspect it's to do with the URL-based versioning we're using but I'm not certain.

https://github.com/getpatchwork/patchwork/blob/5c569b05b912a2b5f4646267f19033216948d3de/patchwork/urls.py#L238-L245

**Comment by auvipy** [comment]
may be can keep this to track if the URL based versioning messes with drf-spectacular as well?

**Comment by tomchristie** [comment]
Let's close it here. Issue was opened 4 years ago, no traction.
May or may not be an existing issue in `drf-spectacular`, but either way let's leave it for folks to deal with there if it *is* hitting anyone.
