### ISSUE TITLE
Tutorial chapter 5 code sample needs a different import statement

### ISSUE THREAD

**Issue by tsnee** [encode/django-rest-framework#6266]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [n/a] I have reduced the issue to the simplest possible case.
- [n/a] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

The statement `from django.conf.urls import url, include` needs to be changed to `from django.urls import path`.

## Steps to reproduce
Run the sample code in docs/tutorial/5-relationships-and-hyperlinked-apis.md, specifically the last snippets/urls.py code block.
## Expected behavior
It produces no error messages.
## Actual behavior
Error message:
NameError: name 'path' is not defined

**Comment by srinivasreddy** [comment]
Please close.
