### ISSUE TITLE
allow one-off donations

### ISSUE THREAD

**Issue by zachvalenta** [encode/django-rest-framework#6275]
**tl;dr** I'd love to support DRF with a one-off donation.

Currently the project only accepts [donations via subscription](https://fund.django-rest-framework.org/topics/funding/).

If an individual user wants to donate a specific amount, they need to:

- start a monthly subscription and then remember to cancel after n months once they've met their intended donation amount for the year
- donate $15/month indefinitely

Could DRF allow one-off donations as well, [like Django](https://www.djangoproject.com/fundraising/)?

**Comment by tomchristie** [comment]
Thanks, but I’d rather keep our revenue model strictly focused on recurring payments.
