### ISSUE TITLE
Checking request's auth success makes it impossible to have custom permissions

### ISSUE THREAD

**Issue by chpmrc** [encode/django-rest-framework#6293]
## Description

DRF checks if the user is authenticated when applying custom permissions. This makes it impossible to write custom permissions based on other parameters that apply even with unauthenticated users.

## Example

```python
class IsCorrectSubdomain(permissions.BasePermission):
    message = "Can only access through the right subdomain."

    def has_permission(self, request, view):
        return request.get_host().startswith('mysubdomain.')


class ResourceViewSet(viewsets.ModelViewSet):
    queryset = Resource.objects.all()
    permission_classes = (IsCorrectSubdomain,)
```

**Expected result**:

HTTP 403 with message "Can only access through the right subdomain."

**Actual result**:

HTTP 401 with message "Authentication credentials were not provided."

## Notes

Seems like the problem is here:
https://github.com/encode/django-rest-framework/blob/40da2a21ef08f9394eb03d018d560516f940a1b2/rest_framework/views.py#L175

**Comment by n2ygk** [comment]
If I'm understanding your issue correctly, you just need to add `authentication_classes` along with `permission_classes` to your view.  `authentication_classes` are checked sequentially left-to-right until one succeeds. `permission_classes` must all succeed.  If you want no authentication, try:
```python
class ResourceViewSet(viewsets.ModelViewSet):
    queryset = Resource.objects.all()
    permission_classes = (IsCorrectSubdomain,)
    authentication_classes = []
```
You're probably hitting up against a default authentication [backend](https://docs.djangoproject.com/en/2.1/topics/auth/customizing/#authentication-backends).

**Comment by chpmrc** [comment]
That makes sense but I feel like checking authentication in the permissions is mixing authentication and authorization a bit. Anyway that seems like a good enough solution for now. Thank you! Closing this since I doubt it will be changed.
