### ISSUE TITLE
'Request' object has no attribute 'accepted_renderer'

### ISSUE THREAD

**Issue by Lopukhovych** [encode/django-rest-framework#6300]
After initializing and run project shows error: 'Request' object has no attribute 'accepted_renderer'

## Steps to reproduce
1. Create empty folder: mkdir django_rest; cd django_rest
2. Create new venv:  python3.6 -m venv env 
3. source env/bin/activate
4. pip install coreapi django djangorestframework \
      djangorestframework-simplejwt
5. django-admin startproject config .
6. In config/settings.py:
   INSTALLED_APPS = [
    ...
    'rest_framework',
   ]

   REST_FRAMEWORK = {
       'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
     ),
  'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
  }
7. In config/urls.py:
from django.conf.urls import url, include
from django.views import generic
from rest_framework.schemas import get_schema_view
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from rest_framework import views, serializers, status
from rest_framework.response import Response

class MessageSerializer(serializers.Serializer):
    message = serializers.CharField()

class EchoView(views.APIView):
    def post(self, request, *args, **kwargs):
        serializer = MessageSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        return Response(
            serializer.data, status=status.HTTP_201_CREATED)
urlpatterns = [
    url(r'^$', generic.RedirectView.as_view(
         url='/api/', permanent=False)),
    url(r'^api/$', get_schema_view()),
    url(r'^api/auth/', include(
        'rest_framework.urls', namespace='rest_framework')),
    url(r'^api/auth/token/obtain/$', TokenObtainPairView.as_view()),
    url(r'^api/auth/token/refresh/$', TokenRefreshView.as_view()),
    url(r'^api/echo/$', EchoView.as_view())
]
8. Run ./manage.py migrate
           ./manage.py createsuperuser
           ./manage.py runserver
9. Go to http://127.0.0.1:8000/
## Expected behavior
Show django rest framework schema page with requests
## Actual behavior
TypeError at /api/
AttributeError at /api/
'Request' object has no attribute 'accepted_renderer'

**Comment by xordoquy** [comment]
If you look closer at the error, you should see that you didn't install yams which is required.

**Comment by gmic** [comment]
pip install pyyaml

**Comment by sedmo** [comment]
got the same error here and your suggestions worked. Thanks! I got this error when I tried to use the schema endpoint for coreapi while doing the tutorial.

**Comment by ruanhailiang** [comment]
After initializing and run project shows error: 'Request' object has no attribute 'accepted_renderer'

Internal Server Error: /api/users/
Traceback (most recent call last):
  File "/home/ruanhailiang/anaconda3/envs/adminweb/lib/python3.6/site-packages/rest_framework/views.py", line 485, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/ruanhailiang/anaconda3/envs/adminweb/lib/python3.6/site-packages/rest_framework/views.py", line 394, in initial
    neg = self.perform_content_negotiation(request)
  File "/home/ruanhailiang/anaconda3/envs/adminweb/lib/python3.6/site-packages/rest_framework/views.py", line 306, in perform_content_negotiation
    renderers = self.get_renderers()
  File "/home/ruanhailiang/anaconda3/envs/adminweb/lib/python3.6/site-packages/rest_framework/views.py", line 260, in get_renderers
    return [renderer() for renderer in self.renderer_classes]
  File "/home/ruanhailiang/anaconda3/envs/adminweb/lib/python3.6/site-packages/rest_framework/views.py", line 260, in <listcomp>
    return [renderer() for renderer in self.renderer_classes]
TypeError: 'str' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ruanhailiang/anaconda3/envs/adminweb/lib/python3.6/site-packages/rest_framework/request.py", line 409, in __getattr__
    return getattr(self._request, attr)
AttributeError: 'WSGIRequest' object has no attribute 'accepted_renderer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ruanhailiang/anaconda3/envs/adminweb/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ruanhailiang/anaconda3/envs/adminweb/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ruanhailiang/anaconda3/envs/adminweb/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ruanhailiang/anaconda3/envs/adminweb/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ruanhailiang/anaconda3/envs/adminweb/lib/python3.6/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ruanhailiang/anaconda3/envs/adminweb/lib/python3.6/site-packages/rest_framework/views.py", line 497, in dispatch
    response = self.handle_exception(exc)
  File "/home/ruanhailiang/anaconda3/envs/adminweb/lib/python3.6/site-packages/rest_framework/views.py", line 457, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/ruanhailiang/anaconda3/envs/adminweb/lib/python3.6/site-packages/rest_framework/views.py", line 465, in raise_uncaught_exception
    renderer_format = getattr(request.accepted_renderer, 'format')
  File "/home/ruanhailiang/anaconda3/envs/adminweb/lib/python3.6/site-packages/rest_framework/request.py", line 411, in __getattr__
    return self.__getattribute__(attr)
AttributeError: 'Request' object has no attribute 'accepted_renderer'
[10/Oct/2019 15:43:59] "GET /api/users/ HTTP/1.1" 500 121397
------------------------------------------------------------------------------------------------
# define the serializers
class UserSerializer(serializers.ModelSerializer):
    class Meta:
        model = UserProfile
        fields = '__all__'
# urls.py
urlpatterns = [
 
    path('users/', UserList.as_view({'get': 'list', 'post': 'create'})),
   
]
# views.py

class UserList(ListModelMixin, CreateModelMixin, GenericViewSet):
    """
    list:
        获取所有的用户，并以创建时间排序
        Return all users,ordered by most recent joined.
    """
    print('ok')
    permission_classes = [permissions.IsAuthenticated, TokenHasReadWriteScope]
    queryset = UserProfile.objects.all()
    serializer_class = UserSerializer

# python conda env

Package                Version  
---------------------- ---------
asn1crypto             0.24.0   
backports.csv          1.0.7    
certifi                2019.9.11
cffi                   1.12.3   
chardet                3.0.4    
coreapi                2.3.3    
coreschema             0.0.4    
cryptography           2.7      
defusedxml             0.6.0    
diff-match-patch       20181111 
Django                 2.2.5    
django-cors-middleware 1.4.0    
django-crispy-forms    1.7.2    
django-formtools       2.1      
django-import-export   1.2.0    
django-oauth-toolkit   1.2.0    
django-rest-swagger    2.2.0    
django-reversion       3.0.4    
djangorestframework    3.10.3   
et-xmlfile             1.0.1    
future                 0.15.2   
httplib2               0.9.2    
idna                   2.8      
itypes                 1.1.0    
jdcal                  1.4.1    
Jinja2                 2.10.3   
Markdown               3.1.1    
MarkupSafe             1.1.1    
mysqlclient            1.4.4    
oauthlib               3.1.0    
odfpy                  1.4.0    
openapi-codec          1.3.2    
openpyxl               3.0.0    
Pillow                 6.2.0    
pip                    19.2.3   
pycparser              2.19     
PyMySQL                0.9.3    
pyOpenSSL              19.0.0   
pytz                   2019.2   
PyYAML                 5.1.2    
requests               2.22.0   
setuptools             41.2.0   
simplejson             3.16.0   
six                    1.10.0   
sqlparse               0.3.0    
tablib                 0.13.0   
uritemplate            3.0.0    
urllib3                1.25.6   
wheel                  0.33.6   
xlrd                   1.2.0    
xlwt                   1.3.0  
I tried to run this command “pip install pyyaml”, but it still didn't work.
