### ISSUE TITLE
Authentification issue with Django 1.11 

### ISSUE THREAD

**Issue by Anto59290** [encode/django-rest-framework#6305]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

In a python2.7, Django 1.11 ( < 1.11.6), you must be logged into your Django account. 

```py
from rest_framework.authentication import *
check = CSRFCheck()
check.process_request({})
```

## Expected behavior
The code should keep on going

## Actual behavior
`AttributeError: 'CSRFCheck' object has no attribute 'process_request' `

## More details

[Looks likes this method](https://github.com/django/django/blob/master/django/middleware/csrf.py#L200) was introduced in Django 1.11.6 therefore DRF 3.9.0 

Full stacktrace https://pastebin.com/raw/59LjvsKR

Seeing the view as an Anonymous works fine.

**Comment by rpkilby** [comment]
Hi all - I would recommend upgrading to the latest version of Django 1.11.x (current latest is 1.11.17). Is there any reason you are unable to do so and are stuck before 1.11.6?
