### ISSUE TITLE
SessionAuthentication with Django Rest Auth login failed with CSRF missing.

### ISSUE THREAD

**Issue by realsoftdev** [encode/django-rest-framework#6314]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Rest framework conf
```
'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
 ),
```

angular request header
```
headers: {
	"X-CSRFToken": undefined (I can not get csrftoken string anywhere before login)
},
withCredentials: true
```

Response from django rest-auth login api
```
{
    "detail": "CSRF Failed: CSRF token missing or incorrect."
}
```
## Expected behavior
`successful login`

## Actual behavior
If l remove `x-csrftoken` and `withcredentials` from request header, login succeed but after login I can't access to all authenticated apis as cookies not updated.
If I add  `x-csrftoken` and `withcredentials` to request header, login failed.

**Comment by xordoquy** [comment]
From the documentation:

> This means that only authenticated requests require CSRF tokens, and anonymous requests may be sent without CSRF tokens. This behaviour is not suitable for login views, which should always have CSRF validation applied.

You should be able to get the login page before posting to it to ensure you get the CSRF token.

**Comment by zdytch** [comment]
So 'SessionAuthentication' method is not approriate choice since you use Angular/React/etc login form instead of django form, thus cannot include {% csrf_token %} 
Right?
