### ISSUE TITLE
DeprecationWarning with markdown

### ISSUE THREAD

**Issue by blueyed** [encode/django-rest-framework#6317]
Code: https://github.com/encode/django-rest-framework/blob/bf9533ae37affc64638c21f551250914dd5f80be/rest_framework/compat.py#L263-L265

Warning:

> DeprecationWarning: Using the add method to register a processor or pattern is deprecated. Use the `register` method instead.

Relevant commit in markdown: https://github.com/Python-Markdown/markdown/commit/6ee07d2735d86d7a3d0b31c3409d42d31997a96c

**Comment by tomchristie** [comment]
This'd probably be a good one for a contributor to jump onto, right?

*waves to the world*

**Comment by rpkilby** [comment]
Note - we added the "good first issue" label a while back, which theoretically helps new users find issues like these?

**Comment by mcab** [comment]
I gave it a shot in PR #6412!

**Comment by rpkilby** [comment]
Thanks again @mcab!

**Comment by dsspeights** [comment]
RE: the [Release Notes](https://www.django-rest-framework.org/community/release-notes/#versioning), is there an ETA on when 3.9.X (5?) will be published with this fix?  
Getting ready to start a new proj, curious if it would be better to use 3.9.4 or wait (if it will be shortly) for this fix?  Using [Django 2.2](https://docs.djangoproject.com/en/2.2/releases/) and [django-cors-headers](https://pypi.org/project/django-cors-headers/) 3.0.2 (latest)  Thanks,

**Comment by rpkilby** [comment]
Hi @dsspeights. This was resolved in #6722, which will be part of the next release (v3.10).
