### ISSUE TITLE
Converting `many=True` to {key_field: {serializer_fields}}

### ISSUE THREAD

**Issue by claytondaley** [encode/django-rest-framework#6323]
I'm working with an external data consumer that requires a syntax like (focusing on `items`):

```
{
   "items": {
        "pk1": {<fields1>},
        "pk2": {<fields2>},
         ...
    },
    "owner": <value>
    ...
} 
```

Technically, the source uses the FK of a OneToOne relationship as its key, but `pk` is simpler to imagine.  A comparable requirement is found in a [question](https://stackoverflow.com/questions/29930401/return-list-of-objects-as-dictionary-with-keys-as-the-objects-id-with-django-res) on StackOverflow.

The "right" way to solve this is a `ListSerializer` that serializes to a `dict` rather than a `list` e.g. by `pop`ing one of the fields and using it as a key.  For example, a serializer definition like:

```
class DictListSerializer(ListSerializer):
    # custom implementation of to_representation and to_internal_value

class MyNestedListSerializer(DictListSerializer):
    field = 'pk'

class MyNestedSerializer(ModelSerializer):
    default_list_serializer_class = MyNestedListSerializer

class MyBaseSerializer(ModelSerializer):
    object_type= MyNestedSerializer(many=True)
```

Is there any interest in adding the `DictListSerializer` implementation to core (i.e. I take the extra time to build tests, etc.)?  If so, what naming makes sense?

**Comment by tomchristie** [comment]
It’d be better suited as third party I think. We’d happily link to it from the docs tho.

**Comment by claytondaley** [comment]
OK.  I have an alpha (but working) version at `drf-keyed-list` on [github](https://github.com/claytondaley/drf-keyed-list) and pypi.  What more needs to be done before it's link eligible?

**Comment by tomchristie** [comment]
Eessh - finally got around to tidying this issue up.
That's already absolutely fine if you wanted to submit a pull request adding it to the docs as a third party package.
