### ISSUE TITLE
DjangoModelPermissions does not respect Django `can_read_model` permissoin

### ISSUE THREAD

**Issue by paultiplady** [encode/django-rest-framework#6324]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

Use `DjangoModelPermissions` on a ViewSet, and access with a user that does not have `can_view_<model>` permisson.

## Expected behavior
The user should not be able to view the model, as they don't have the required permission.

## Actual behavior
All authenticated users are granted read-only permission.

**Comment by paultiplady** [comment]
Breaking back-compat might not be desirable; if so would it be worth adding a subclass that does respect the permission? Something like this would be an option:

```
class DjangoModelPermissionsStrict(DjangoModelPermissions):
    perms_map = {
        'GET': ['%(app_label)s.view_%(model_name)s'],
        'OPTIONS': [],
        'HEAD': [],
        'POST': ['%(app_label)s.add_%(model_name)s'],
        'PUT': ['%(app_label)s.change_%(model_name)s'],
        'PATCH': ['%(app_label)s.change_%(model_name)s'],
        'DELETE': ['%(app_label)s.delete_%(model_name)s'],
    }
```

**Comment by nemesisdesign** [comment]
Hi everyone, there's a patch which adds support for view permission and is backward compatible: https://github.com/encode/django-rest-framework/pull/8009.

**Comment by kxbin** [comment]
This is great，Hope this PR can pass.

**Comment by Ukie1** [comment]
Still seems like a good idea to fix this

**Comment by dfrankow** [comment]
Not stale?

**Comment by iamunadike** [comment]
DjangoModelPermissions does not work on viewsets , this is really annoying ....
Even with this custom_permissions.py
the label **'%(app_label)s'** needs to be auto recognised I supposed, to make the work easy

```
from rest_framework.permissions import DjangoModelPermissions
class D7896DjangoModelPermissions(DjangoModelPermissions):
    perms_map = {
        'GET':['%(app_label)s.view_%(model_name)s'],
        'OPTIONS': [],
        'HEAD': [],
        'POST': ['%(app_label)s.add_%(model_name)s'],
        'PUT': ['%(app_label)s.change_%(model_name)s'],
        'PATCH': ['%(app_label)s.change_%(model_name)s'],
        'DELETE': ['%(app_label)s.delete_%(model_name)s'],
    }
```
