### ISSUE TITLE
Docs: How does Binary in JSON work

### ISSUE THREAD

**Issue by guettli** [encode/django-rest-framework#6342]
## Checklist

- [ x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [ x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

1. Read https://www.django-rest-framework.org/api-guide/fields/#jsonfield
2. ask yourself: How do they do this?
3. Find not answer in the docs.

AFAIK there is no official way to encode binary data in JSON.
That's why it would be very nice if you could explain your solution in the docs.

**Comment by tomchristie** [comment]
JSON doesn’t support binary data.

**Comment by tomchristie** [comment]
You could use base64 encoded strings I guess, but it’s bit something we’d build in.

**Comment by guettli** [comment]
@tomchristie Please elaborate "but it’s bit something we’d build in." I am unsure if I understood you.

**Comment by guettli** [comment]
I know that JSON does not support binary data. But it would be great of the DRF would support or suggest a standard work-around. If you do not (at least document) a common work-around, then every developer facing this problem will solve the same issue over and over again. Please help new comers. Thank you.

**Comment by tomchristie** [comment]
> Please elaborate "but it’s bit something we’d build in." I am unsure if I understood you.

Typo. it's *not* something we'd build in.

**Comment by tomchristie** [comment]
I reckon we could happily accept pull requests to the documentation noting that binary data isn't supported by JSON, and recommending base64 encoding in that case.
