### ISSUE TITLE
401 unathorized while using token authentication drf

### ISSUE THREAD

**Issue by Akashutreja** [encode/django-rest-framework#6349]
Hi guys,
I am using drf default token authentication. But there's weird behaviour which i am facing. It get unauthorized randomly on some incoming request and If i check token of unauthorized request it is same with the token of request which returned 200. Please help me out.
My request header is like Authorization: Token <token key>
Here is my settings.py file containing.
REST_FRAMEWORK = {
   'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    )}
Thanks

**Comment by xordoquy** [comment]
Hi,
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
