### ISSUE TITLE
Objects builtin methods are not called when passed in fields source

### ISSUE THREAD

**Issue by antwan** [encode/django-rest-framework#6351]
I open this ticket to check whether it's worth working on a specific case I spotted recently.
It is not possible to use built-in methods (or functions) in fields "source" argument, as they are not treated as `simple_callable`.

## Steps to reproduce
Example with Django User's date joined:

    # serializers.py
    day_joined = serializer.ReadOnlyField(source=`date_joined.date`)

#### Result
    {
        "day_joined": "<built-in method date of datetime.datetime object at 0x109400000>"
    }

#### Expected result
    {
        "day_joined": "2008-09-03"
    }

## Suggestion
There are [ways](https://stackoverflow.com/questions/48567935/get-parameterarg-count-of-builtin-functions-in-python) to ensure a built-in method/callable is a simple callable (ie can be called without arguments as per [`rest_framework.fields.is_simple_callable`](https://github.com/encode/django-rest-framework/blob/master/rest_framework/fields.py#L56)).

I'm happy to create the PR for this, but need to know if it's worth it beforehand.

Related: see #5114

**Comment by dz0** [comment]
aha, a bit frustrating to write SerializerMethodField.... instead

I stumbled upon same named method in IPython:
```python
# @ta_env/lib/python3.5/site-packages/IPython/core/oinspect.py:197
def is_simple_callable(obj):
    """True if obj is a function ()"""
    return (inspect.isfunction(obj) or inspect.ismethod(obj) or \
            isinstance(obj, _builtin_func_type) or isinstance(obj, _builtin_meth_type))

# @ta_env/lib/python3.5/site-packages/IPython/core/oinspect.py:58
_builtin_func_type = type(all)
_builtin_meth_type = type(str.upper)  # Bound methods have the same type as builtin functions

```

**Comment by rpkilby** [comment]
Hi @antwan. I'm going to echo Tom's response in https://github.com/encode/django-rest-framework/issues/5114#issuecomment-298956002. If you can submit a minimal, low-friction pull request, then that would be worth including. However, the solution in the SO answer is too complex/brittle for the value that it provides. 

That said, if a simple solution can't be found, it would be worth raising a helpful error message. e.g., 
> Python's built-in functions are not supported. Wrap the call in a function, method, or property.
