### ISSUE TITLE
When post with form-data, ModelSerializer went wrong

### ISSUE THREAD

**Issue by VictorWangwz** [encode/django-rest-framework#6356]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce and Actual behavior
Create a model with a field, for example, is_active, default as True; Create a ModelSerializer for it; Post with multipart/form-data without is_active; -> will create an object with default as false. If post with just raw json, it will do the right thing.
I do not clearly know how the serializer parses the querydict from request.data passed by form-data. But It does not parse it in the expected way. I just check the validated_data after validation, it contains "is_active": False which is really weird. Also, If I pass the parameter is_active in form-data, the validated_data will contains both "is_active": True and "is_active": False.
## Expected behavior and things to solve
1. When post with multipart/form-data, parse request.data the same way as raw json;
2. The serializer should not create default fields for the fields that are not provided and do not have default value.
3. When validated_data contains duplicated values, just use the one from request.data.

**Comment by xordoquy** [comment]
> When post with multipart/form-data, parse request.data the same way as raw json;

This was already answered in #6355. Please don't reopen an issue for the same thing.
The HTML spec states:

> When a form is submitted, only "on" checkbox controls can become successful.

Which means that missing checkbox in HTML forms means it's a `False` value which explains why it bypasses the default value.
JSON is more explicit in its intend and allows finer control.
