### ISSUE TITLE
--format option to generateschema is ignored

### ISSUE THREAD

**Issue by hoylemd** [encode/django-rest-framework#6359]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Description

I'm trying to generate a json-formatted openapi schema with the generateschema command, but the format option seems to be completely ignored.  I also tested it with the 'corejson' format, with the exact same result (stack trace suggesting that `options.format` was not correctly parsed from the command invocation)

## Steps to reproduce

```bash
python manage.py generateschema --format openapi-json
```

## Expected behavior

A json-formatted openapi schema is printed to stdout

## Actual behavior

```python_stacktrace
Traceback (most recent call last):
  File "./manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/management/commands/generateschema.py", line 30, in handle
    renderer = self.get_renderer(options['format'])
  File "/usr/local/lib/python3.7/site-packages/rest_framework/management/commands/generateschema.py", line 37, in get_renderer
    'openapi': OpenAPIRenderer(),
  File "/usr/local/lib/python3.7/site-packages/rest_framework/renderers.py", line 1033, in __init__
    assert yaml, 'Using OpenAPIRenderer, but `pyyaml` is not installed.'
AssertionError: Using OpenAPIRenderer, but `pyyaml` is not installed.
```

## Environment

I have the following DRF-related packages installed in my env.  There are others, but I don't think they're relevant so I've omitte them for brevity:

```requirements.txt
attrs==18.2.0
coreapi==2.3.3
coreschema==0.0.4
Django==2.1.3
django-extensions==2.1.4
django-filter==2.0.0
djangorestframework==3.9.0
djangorestframework-jsonapi==2.6.0
Markdown==3.0.1
MarkupSafe==1.1.0
pytest==4.0.1
pytest-django==3.4.4
uritemplate==3.0.0
urllib3==1.24.1
```

**Comment by carltongibson** [comment]
> Using OpenAPIRenderer, but `pyyaml` is not installed.

Install pyyaml.

**Comment by carltongibson** [comment]
Yes please. 🙂

**Comment by hoylemd** [comment]
Will do!  Might have to wait til tomorrow though.
