### ISSUE TITLE
ContentNotRenderedError when JSON exception swallowed

### ISSUE THREAD

**Issue by rrauenza** [encode/django-rest-framework#6364]
## Checklist

- [ ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [ x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

I've tested this in 3.8.2

Also posted here for future searches:   https://stackoverflow.com/questions/53842591/contentnotrenderederror-in-django-rest-framework

I've built a view and serializer where the serializer has a field that is a `SerializerMethodField()`.  In that field's get method I have something like:

```
def get_result(self, obj):
    result = Result(obj.a, obj.b, obj.c)
    return dict(
        percent_change=result.percent_change,
        [...]
    )
```

Turns out my `result.percent_change` sometimes was `NaN` or `Infinity` which is not supported by JSON.  

The problem is that this root cause was difficult to find because the JSON exception was somehow swallowed and we ended up with a `ContentNotRenderedError: The response content must be rendered before it can be accessed.` instead.

Regardless whether this gets fixed or not, wanted to post this so people searching for this error realize it's likely a swallowed exception.

Related?  https://github.com/encode/django-rest-framework/issues/4809

## Expected behavior
Instead of `ContentNotRenderedError` exception, it would be nice to see original exception somehow.

(Or some advice how to find the root cause exception.)

## Actual behavior
JSON conversion exception is swallowed.

**Comment by rrauenza** [comment]
I'll see what I can do, but I should also mention I'm using these for my view since it is the view swallowing the error, not the serializer:

               mixins.ListModelMixin,                                   
               mixins.RetrieveModelMixin,                                        
               viewsets.GenericViewSet

I did make a serializer to test this -- just need to make a view:

```
from rest_framework import serializers

class FooSerializer(serializers.Serializer):

    result = serializers.SerializerMethodField()

    def get_result(self, obj):
        return {
            'nan': float('nan'),
            'num': 1.1111,
        }

```

**Comment by tomchristie** [comment]
Going to close this off as stale
