### ISSUE TITLE
AutoSchema inspects the wrong field in get_path_field

### ISSUE THREAD

**Issue by merwok** [encode/django-rest-framework#6369]
## Checklist

- [ ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

I don’t want to use auto-incremented numeric database IDs as my HTTP identifiers.

- Most models have the automatic ID field + `uid = ShortUUIDField(db_index=True)`
- One model has `code = models.CharField(max_length=5)` (not unique or db_index because it’s part of a composite key with `user`)
- viewsets define `lookup_field = "uid"` or `"code"`
- serializers have `extra_kwargs = {"url": {"lookup_field": "uid"}}`

In the generated route regex and coreapi-based docs, the internal name `uid` or `code` leaks out.  To fix this, one can add `lookup_url_kwarg` so that the variable in the route is named `id`.  So far so good.

## Expected behavior

In the docs view (the one generated by include_docs_url), the form where I have to input the resource ID to fill in the URI accepts strings.

(The dream behaviour would actually be hypermedia integration!  All my serialized objects include a `url` field, but clicking on that leaves the docs page.)

## Actual behavior

The input only accepts integers.

This comes from rest_framework.schemas.inspectors.AutoSchema.get_path_fields, which extracts the variable name `id` from the route and inspects the `id` field in the model.  The lookup field should be inspected instead.

**Comment by carltongibson** [comment]
Yep, seems reasonable. If you want to put together a simple test case showing this, I'd guess a fix wouldn't be too hard.

**Comment by carltongibson** [comment]
Given this is the old CoreAPI based generation, I'm going to close this as inactive/stale. If anyone wants to follow up with a fresh issue if there's still something relevant then that would be great.
