### ISSUE TITLE
[Doc] Remove reference to deprecated drf_openapi package?

### ISSUE THREAD

**Issue by johnthagen** [encode/django-rest-framework#6378]
The third party packages section has a link to `drf_openapi`:

https://www.django-rest-framework.org/api-guide/schemas/#drf-openapi

But `drf_openapi` has been deprecated and seems to be a dead project now:

https://github.com/limdauto/drf_openapi

Should the docs be updated to either to indicate that this package is deprecated, or maybe just remove the reference all together? Would you accept a PR?

**Comment by tomchristie** [comment]
Yup, would accept a pull request dropping that from the docs. Thanks!
