### ISSUE TITLE
URLPathVersioning: Use Default Version when It's None (Not Invalid)

### ISSUE THREAD

**Issue by ykh** [encode/django-rest-framework#6379]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Allowed Versions: v1, v2
Default Version: v2 (It's latest version as often)
My URL Pattern: `api/((?P<version>(\w){2})/)?users/`

## Expected behavior
1- When GET `api/v1/users/`: get users data according to version v1.
2- When GET `api/users/` :  get users data according to Default-Version.

## Actual behavior
for Case 1: get users data according to version v1.
for Case 2: get 404 error: "Invalid version in URL path."

I think it makes sense when client didn't specified version in URI, he expects get response from latest version as often (not getting error)!

**Comment by tomchristie** [comment]
Sanity check: Does the second version populate the URL keyword arguments as `{"version": None}`, or `{}`?

**Comment by ykh** [comment]
@tomchristie "version" is None.
