### ISSUE TITLE
[Doc] Mention OpenAPI in tutorial schema section

### ISSUE THREAD

**Issue by johnthagen** [encode/django-rest-framework#6381]
One of the things that was a bit confusing as a someone new to DRF was around schemas / CoreAPI. Following the tutorial, there was no mention of OpenAPI being roadmap forward and CoreAPI being effectively deprecated in the long term (related to https://github.com/core-api/core-api/issues/58).

From https://www.django-rest-framework.org/community/3.9-announcement/#whats-next

> We're planning to iteratively work towards OpenAPI becoming the standard schema representation. This will mean that the `coreapi` dependency will gradually become removed, and we'll instead generate the schema directly, rather than building a CoreAPI `Document` object.

The [schemas api-doc section](https://www.django-rest-framework.org/api-guide/schemas/#schema-output-formats) does mention OpenAPI:

> `renderers.OpenAPIRenderer` - Renders into YAML-based OpenAPI, the most widely used API schema format.

But the [tutorial page](https://www.django-rest-framework.org/tutorial/7-schemas-and-client-libraries/) doesn't mention OpenAPI. Would it be helpful if that page mentioned OpenAPI as the widely used "standard" so new users aren't led down the path of using CoreAPI directly for new projects?

**Comment by tomchristie** [comment]
I'm not sure. Either way we've got some more comprehensive work to do in updating that, yup.

**Comment by sad-boy-uoa** [comment]
Hi there, has there been any update on this?

**Comment by carltongibson** [comment]
This is addressed by #6668

**Comment by rpkilby** [comment]
I think this can be closed, as it looks like we're dropping the schema tutorial. https://github.com/encode/django-rest-framework/pull/6668#issuecomment-508017283
