### ISSUE TITLE
use coreapi, only get method can be seen bye viewset

### ISSUE THREAD

**Issue by richie1983825** [encode/django-rest-framework#6384]
## Steps to reproduce
Python3, Django 2.1.4, DjangoRestFramework 3.9.0

When finish the tutorial, I want to documenting the API, so follow this guide:
https://www.django-rest-framework.org/topics/documenting-your-api/

## Expected behavior
function based views, class baed views and viewset can be seen in /docs

## Actual behavior
Only using generic class basd views, the post method is OK. 
1.  when using function based views or APIView class, the post method can be seen, but no parameters in dialog
![image](https://user-images.githubusercontent.com/5040250/50424198-9ee0da80-089b-11e9-99d8-052ee9dd199c.png)

2. when using viewsets, no post method can be seen.
![image](https://user-images.githubusercontent.com/5040250/50424185-6f31d280-089b-11e9-8de6-9b3a6b0091fd.png)

**Comment by charanjit-singh** [comment]
Hello I'm new to this community and I know how REST_FRAMEWORK works, I know serializers, validators, API_VIEWS, permissions, etc. I want to join this community. Can anybody help me to work on easy issues so that I can start contributing into DRF. 
Thanks.

**Comment by bukowa** [comment]
I think that each documentation / browsable API is usually calling the "get_serializer" method on the view.

**Comment by rpkilby** [comment]
@charanjit-singh some packages have a ["good first issue"](https://github.com/encode/django-rest-framework/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22), "beginner friendly", or similar tag that is targeted to people like you. Unfortunately DRF is fairly mature, and there aren't many issues that are beginner friendly.

That said, I'd recommend scanning the open issues and seeing if you can find something you think you can handle.

**Comment by carltongibson** [comment]
This is expected behaviour. 

As @bukowa says, automatic schema introspection relies on the presence of a `get_serializer()` method. This is not available for function based views or plain `APIView` subclasses, which are not `GenericAPIView` based. 

The `ViewSet` case is not showing the `POST` views because the user is not authenticated, and so fails the permission check.
