### ISSUE TITLE
add bson.timestamp support

### ISSUE THREAD

**Issue by radzhome** [encode/django-rest-framework#6390]
## Checklist

- [ x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [ x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

Any way this can be included in the JsonEncoder? Right now I have to patch the encoder locally to handle Timstamp data. JsonField sometimes includes this data type and when it does, without this patch you get a `Timstamp is not JSON serializable`

```
"""
Helper classes for parsers.
"""
from __future__ import absolute_import, unicode_literals

import datetime
import decimal
import json  # noqa
import uuid
import bson

from django.db.models.query import QuerySet
from django.utils import six, timezone
from django.utils.encoding import force_text
from django.utils.functional import Promise

from rest_framework.compat import coreapi


class JSONEncoder(json.JSONEncoder):
    """
    JSONEncoder subclass that knows how to encode date/time/timedelta,
    decimal types, generators and other basic python objects.
    """
    def default(self, obj):
        # For Date Time string spec, see ECMA 262
        # https://ecma-international.org/ecma-262/5.1/#sec-15.9.1.15

        if isinstance(obj, Promise):
            return force_text(obj)
        elif isinstance(obj, datetime.datetime):
            representation = obj.isoformat()
            if representation.endswith('+00:00'):
                representation = representation[:-6] + 'Z'
            return representation
        elif isinstance(obj, datetime.date):
            return obj.isoformat()
        elif isinstance(obj, datetime.time):
            if timezone and timezone.is_aware(obj):
                raise ValueError("JSON can't represent timezone-aware times.")
            representation = obj.isoformat()
            return representation
        elif isinstance(obj, datetime.timedelta):
            return six.text_type(obj.total_seconds())
        elif isinstance(obj, decimal.Decimal):
            # Serializers will coerce decimals to strings by default.
            return float(obj)
        elif isinstance(obj, uuid.UUID):
            return six.text_type(obj)
        elif isinstance(obj, QuerySet):
            return tuple(obj)
        elif isinstance(obj, bytes):
            # Best-effort for binary blobs. See #4187.
            return obj.decode('utf-8')
        elif hasattr(obj, 'tolist'):
            # Numpy arrays and array scalars.
            return obj.tolist()
        elif (coreapi is not None) and isinstance(obj, (coreapi.Document, coreapi.Error)):
            raise RuntimeError(
                'Cannot return a coreapi object from a JSON view. '
                'You should be using a schema renderer instead for this view.'
            )
        elif hasattr(obj, '__getitem__'):
            try:
                return dict(obj)
            except Exception:
                pass
        elif hasattr(obj, '__iter__'):
            return tuple(item for item in obj)
        elif isinstance(obj, bson.timestamp.Timestamp):
            return str(obj)
        return super(JSONEncoder, self).default(obj)

```

I am using pymongo to fetch the data and it seems to be converting mongodb type Timestamp to a bson.timestamp.Timestamp.

**Comment by tomchristie** [comment]
> JsonField sometimes includes this data type and when it does, without this patch you get a Timstamp is not JSON serializable

A JSON field that returns non-JSON serializable datatypes isn't really doing it's job.

It sounds like this is the behavior of mongo or python's mongo driver. What you probably want to do is make sure that you're serializing the field into an appropriate string representation. (Perhaps a custom field type that has a `to_native` that strictly forces all the datatypes into plain JSON serializable types.)

Alternatively use a custom JSON renderer class.

**Comment by radzhome** [comment]
Yeah I tried to use custom renderer, and parse too because the browsable renderer needs to be patched as well which has the default parser attached to it. When you do that, along with the custom encoder as above, it works but for whatever reason the JSONRenderer doesn't do its job anymore.

Yeah the main issue is that pymongo uses this bson timestamp rather than returning a string. I'll keep at it. It would be great if we could at least set the default JSON Encoder for the project in settings.py (REST_FRAMEWORK).

**Comment by rpkilby** [comment]
>  It would be great if we could at least set the default JSON Encoder for the project in settings.py 

If you're creating a custom encoder class, then it would be straightforward to subclass `JSONRenderer` and set the `encoder_class` there. You can then override the [`DEFAULT_RENDERER_CLASSES`](https://www.django-rest-framework.org/api-guide/settings/#default_renderer_classes) setting.

**Comment by radzhome** [comment]
I already tried that, that breaks update and create due to missing request.data, see this issue I posted

https://github.com/encode/django-rest-framework/issues/6393

and can be reproduced using this code https://github.com/radzhome/drfcustomparser
