### ISSUE TITLE
Dynamically select paginator

### ISSUE THREAD

**Issue by saintcrawler** [encode/django-rest-framework#6397]
https://github.com/encode/django-rest-framework/blob/7749e4e3bed56e0f3e7775b0b1158d300964f6c0/rest_framework/generics.py#L164

Most classes in DRF allow overriding default fields dynamically by .get_<name>() methods. So that you can provide different values depending on current request, for example. 

I wonder why there is no possibility to do that for paginator? In my case I want to use Limit-Offset pagination by default and Cursor pagination if a certain key is passed to `request.query_params`.

I solved it with this code:

```python
    @property
    def paginator(self):
        if not hasattr(self, '_paginator'):
            self._paginator = MyCursor() if 'cursor' in self.request.query_params else pagination.LimitOffsetPagination()
        return self._paginator
```

But I think it would be more naturally to replace the line I pinned at the top by this:

```python
 self._paginator = self.get_pagination_class()()
...
...
def get_pagination_class(self):
    return self.pagination_class
```

What do you think?

**Comment by tomchristie** [comment]
Fair enough question, tho I don't particularly want the extra indirection, given that this isn't a particularly common use-case.

Stick with overriding `paginator`
