### ISSUE TITLE
"Cannot set both 'fields' and 'exclude' options." Why not?

### ISSUE THREAD

**Issue by liavkoren** [encode/django-rest-framework#6399]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Add a `fields` attribute to a Serializer Meta class, and an `exclude` attribute.
## Expected behavior
I'd expect this to work as long as the intersection of `fields` and `exclude` is empty. This is an excellent way to document in code what's private and what's public.

## Actual behavior
I get an AssertionError : (

**Comment by tomchristie** [comment]
It’s an unnecessary nonsense to use both.

**Comment by tomchristie** [comment]
Sorry - not intended.
It's just not necessary and wouldn't mean anything to have both.

**Comment by tomchristie** [comment]
To be complete here...

> I'd expect this to work as long as the intersection of fields and exclude is empty.

We *could* allow it in that single particular case, but it's more consistent not to and to *always* have a single style.

**Comment by kmcheung12** [comment]
I think it helps to convey the intention of the serializer.

For instance, in a one `Blog` many `Comment`s relation, an API to retrieve a blog may look like

http://example.com/blog/1
```json
{
    "title": "Hello world",
    "content": "lorem ipsum",
    "comments": [
        {
            "id": "comment_id_1",
            "author": "Alice",
            "content": "good",
        },
        {
            "id": "comment_id_2",
            "author": "Bob",
            "content": "good",
        },]
}
```

the `Comment.py` might be like

```python
class Comment(serializers.ModelSerializer):
    # fields ommitted 
    blog = models.ForeignKey('Blog', on_delete=models.CASCADE, related_name='comments')
```

`BlogSerializer.py`:

```python
class BlogSerializer(serializers.ModelSerializer):
    comments = CommentSerializer(many=True, read_only=True)
    class Meta:
        model = Blog
        fields = ('title', 'content', 'comments')
```

and in `CommentSerializer.py`

```python
class CommentSerializer(serializers.ModelSerializer):
    class Meta:
        model = Comment
        fields = ('id', 'author', 'content')
        exclude = ('blog') # here
```
by allowing `fields` and `exclude` together, i think it helps better communicate the engineer's intention that `blog` is not to be embedded under `comment`

but also agrees with @xordoquy that it leaves ambiguity

**Comment by tomchristie** [comment]
Again: We *could* allow it in that single particular case, but it's *more consistent not to* and to always have a single style.

**Comment by rpkilby** [comment]
Just to add on my two cents after the fact... the mix of fields/exclude in this case would effectively be "code as comment". You want to include some set of fields, but also convey that you have explicitly excluded a different set of fields. I'd argue that you should instead write a comment that states that these fields have been excluded, and possibly explain why if helpful. e.g. "We've excluded `blog` because comments are nested under their parent blog."
