### ISSUE TITLE
@action url_path parser to other router view

### ISSUE THREAD

**Issue by youshutong2080** [encode/django-rest-framework#6401]
## Checklist

- [ ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [ ] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
code below:
```python
#url.py
router = DefaultRouter()
router.register('app-combine', CombineViewSet, base_name='app-combine')

urlpatterns = [
    url(r'combine/(?P<short_name>\w+)/$', CombineAPIView.as_view()),
]

urlpatterns  += router.urls


#views.py
class CombineViewSet(ViewSet):
    permission_classes = [IsAuthenticated]
    authentication_classes = [JSONWebTokenAuthentication]

    def list(self, request):
        queryset = Combine.objects.filter(creator=request.user.id)
        serializer = CombineSerializer(queryset, many=True, context={'request': request})
        return Response({'code': 0, 'data': serializer.data, 'msg': None}, status=status.HTTP_200_OK)

    @action(methods=['post'], detail=False, url_path='test')
    def test(self, request):
        print('helo')
        return Response({'code': 0})

class CombineAPIView(APIView):
    permission_classes = [IsAuthenticated]
    authentication_classes = [JSONWebTokenAuthentication]

    def get(self, request, short_name):
        queryset = Combine.objects.get(uri__exact=short_name)
        serializer = CombineSerializer(queryset, context={'request': request})
        return Response({'code': 0, 'data': serializer.data, 'msg': None}, status=status.HTTP_200_OK)
```
## Expected behavior
request `app-combine/test/` route to`CombineViewSet`
## Actual behavior
request `app-combine/test/` route to`CombineAPIView`

**Comment by sevdog** [comment]
The problem lies here:
```
urlpatterns = [
    url(r'combine/(?P<short_name>\w+)/$', CombineAPIView.as_view()),
]

urlpatterns  += router.urls
```

Your regex does not start with `^` and is defined _before_ your router urls, so it will match both `combine` and `app-combine`.

To make your code work you should either rewrite your regex ( `r'^combine/(?P<short_name>\w+)/$'`) or invert the order in which you define your url (`urlpatterns  = router.urls + urlpatterns`).

**Comment by youshutong2080** [comment]
if the problem is there, all of the router views func will be wrong; but just occurred to `test`

**Comment by xordoquy** [comment]
Thanks @sevdog for the analysis and explanation.
I'm seconding you there, the issue is in the urls definition.
