### ISSUE TITLE
Best practices for service layer or service objects

### ISSUE THREAD

**Issue by Tankske** [encode/django-rest-framework#6403]
Would be nice to have 
- either best practices documentation available about where to put business logic, 
- or to provide objects that could be used throughout the framework.

The former would mean that DRF documentation contains a page explaining where business logic would fit best:
- A service layer could be an option to provide general tasks such as email-confirmation, extra validation such as approvals from other users etc.
- A proxy model could be another option, this to implement domain driven design. If I would create an application enabling conversations, I could store the separate messages containing links with each other. I would then create a domain model conversations which builds further upon messages to provide a conversation thread.
- Querysets/managers are an option if your logic concerns consistency for certain updates of your models.
Giving guidance/best practices/references for specific business logic needs considering the DRF architecture design would be helpful for many coders I believe.. 

For the latter, I refer to an existing GitHub project: https://github.com/mixxorz/django-service-objects

My sources:
- https://stackoverflow.com/questions/12578908/separation-of-business-logic-and-data-access-in-django
- https://sunscrapers.com/blog/where-to-put-business-logic-django/

**Comment by tomchristie** [comment]
Generally: Models and Model Manager classes. Tho either way I think high level architectural discussions are just slightly beyond the scope of the official docs. Would be very happy to link out to third party learning resources tho.

**Comment by Tankske** [comment]
Linking out to third party learning resources would be great! I that something you would keep in this thread as you prefer to keep it out of official docs?
