### ISSUE TITLE
Check permission when creating new objects related to parent objects

### ISSUE THREAD

**Issue by stockersky** [encode/django-rest-framework#6409]
## Checklist

- [*] I have verified that that issue exists against the `master` branch of Django REST framework.
- [] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [*] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [*] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

Very classical use-case : A user is the owner of a parent objects. Child objects linked through ForeignKey. When creating a new child object through the DRF GUI, for example, the select box will list all parent objects available, whatever the logged in use is the owner. 

**But the real problem comes from the fact that - indeed, whatever perm you set up - you can just select a parent object you do not own as a FK and it will be created.**

The problem is that a malicious user could create child objects linked to parent objects owner by someone else (especially if PK are incremented integer, it's easy to guess that object 999 exists if you just created object 1000). Then some user would have prank objects on their dashboard.

**There are many POST on Stackoverflow about this :**   
[https://stackoverflow.com/questions/38204553/django-rest-framework-permission-to-creat](https://stackoverflow.com/questions/38204553/django-rest-framework-permission-to-create)
[https://stackoverflow.com/questions/35879857/check-permissions-on-a-related-object-in-django-rest-framework](https://stackoverflow.com/questions/35879857/check-permissions-on-a-related-object-in-django-rest-framework)

even here :
[https://github.com/encode/django-rest-framework/issues/1985](https://github.com/encode/django-rest-framework/issues/1985)
[https://github.com/encode/django-rest-framework/issues/6082](https://github.com/encode/django-rest-framework/issues/6082)

Every solution goes in all directions... scary...

**When created new objects, 'has_object_permission' seems to be executed (from the doc, it should not) but it's not enforced.** 

```python
class IsOwner(permissions.BasePermission):
    """
    Object-level permission to only allow owners of an object to edit it.
    """
    def has_object_permission(self, request, view, obj):
        print("has_object_permission !!!! {} - {} - {}".format(obj.myobj.id, obj.myobj.owner, request.user))
        # return obj.myobj.owner == request.user
        return False 
```

While creating an object, this would print out in the console but obviously it's not enforced at all...

**On the other side, "has_permission" is not properly enforced as the object does not exist yet...**

## Solution found

Do the validation in the serializers.ModelSerializer : 

``` python
class MyClassSerializer(serializers.ModelSerializer):
    class Meta:
        model = MyClass
        fields = '__all__'

    def validate(self, data):
        linkedObj = data['parent']
        # print(linkedObj.owner)
        # print(self.context['request'].user)
        if linkedObj.owner == self.context['request'].user:
            return data
        else:
            raise NotAuthenticated(detail=None, code=None)

```

I did not realize this security issue at first. I know it's not really a bug but more or less something that felt out in the darkness of DRF design. But, it could be a great idea to document how to do so, because I guess there are apps around that could suffer from this...

**Comment by xordoquy** [comment]
Hi,

I'm not really sure what the issue here is.

> When created new objects, 'has_object_permission' seems to be executed (from the doc, it should not) but it's not enforced.

No it's not. You are probably seeing it called because of the permissions checks required by the browsable API to know whether or not you are allowed to edit the newly created instance.

> But the real problem comes from the fact that - indeed, whatever perm you set up - you can just select a parent object you do not own as a FK and it will be created.

Not sure what this means. If it's about nested serializer, the developers are responsible for the creation. If it's about your dataset not checking what the user should be restricted to, it's also the developer responsibility though [overriding the `get_queryset`](https://medium.com/django-rest-framework/limit-related-data-choices-with-django-rest-framework-c54e96f5815e)

I'm closing this issue as I'm not even sure what the issue is.
A test case and shorter explanation would help.

**Comment by stockersky** [comment]
@xordoquy 

Thanks for your first comment : indeed, while testing with postman, I do not see debug printing on the console. 

About your second answer, this is not more complicated than this :  

models.py
```python
class Daddy(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=20)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

class Kiddy(models.Model):
    title = models.CharField(max_length=12)
    daddy = models.foreignKey(Daddy, on_delete=models.CASCADE)
```

serializer.py : 
```python
class KiddySerializer(serializers.ModelSerializer):
    class Meta:
        model = Kiddy
        fields = '__all__'
```

viewset.py
```python
class KiddyViewSet(viewsets.ModelViewSet):
    serializer_class = KiddySerializer
    queryset = User.objects.none()

    permission_classes = (IsAuthenticated, IsOwner, )

    def get_queryset(self):
        dad_uuid = self.kwargs['dad']
        return Kiddy.objects.filter(daddy__pk=dad_uuid).filter(daddy__owner=self.request.user)
```
permission.py
```python
class IsOwner(permissions.BasePermission):
"""
Object-level permission to only allow owners of an object to edit it.
Assumes the model instance has an `owner` attribute.
"""

def has_object_permission(self, request, view, obj):
    if request.user != obj.daddy.owner:
        return False
    else:
        return True

def has_permission(self, request, view):
        daddy = Curriculum.objects.get(pk=view.kwargs['daddy']
        return daddy.owner == request.user
```

Everything seems protected, except the creation of a new 'kiddy' object by a user not being the owner of the related 'daddy' object.

payload = { "title": "prankkkk", daddy="uuid_of_a_daddy_object_not_owned by me" }
You POST this and it pass...

You can look in the stackoverflow links suggested in my first post : they describe the same pb with different examples.

**Comment by Gouravchawla** [comment]
I'm interested in knowing how to handle this use case too.

**Comment by xordoquy** [comment]
This is quite different from permissions because it is a different rule.
Either you want to apply it on creation and updates which could be a serialiser level validator, either it's specific to creation and you should override the default creation view to check this rule.
