### ISSUE TITLE
django-filter: filter_fields is deprecated, filterset_fields is to be used

### ISSUE THREAD

**Issue by x-yuri** [encode/django-rest-framework#6411]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
1. Open https://www.django-rest-framework.org/api-guide/filtering/
2. Search for `filter_fields`.

## Expected behavior
Nothing found.

## Actual behavior
No nothing found :)

## More info
[`filter_fields`][1] is deprecated in favor of [`filterset_fields`][2]. At least the following [file][3] is to be updated. It probably makes sense to change `get_filter_fields` method name as well.

[1]: https://github.com/carltongibson/django-filter/blob/2.0.0/django_filters/views.py#L13-L17
[2]: https://github.com/carltongibson/django-filter/blob/2.0.0/django_filters/rest_framework/backends.py#L52-L57
[3]: https://github.com/encode/django-rest-framework/blob/3.9.1/docs/api-guide/filtering.md

**Comment by carltongibson** [comment]
> It probably makes sense to change get_filter_fields method name as well.

This relates to schema generation. I don't think it's worthwhile at this point.
