### ISSUE TITLE
Move the functionality of getting the serializer schema to the serializer itself

### ISSUE THREAD

**Issue by khomyakov42** [encode/django-rest-framework#6418]
## Checklist

- [*] I have verified that that issue exists against the `master` branch of Django REST framework.
- [*] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [*] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [*] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [*] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

The function "rest_framework.schemas.inspectors.field_to_schema"  does not allow to create schemas for custom serializers. I think that it is more correct to bring this functionality to the serializer itself, by analogy with "FilterBackend.get_schema_fields". If you agree with this, then I could send you a request.

**Comment by carltongibson** [comment]
You're welcome to override `field_to_schema` to inject whatever logic you like back into the serializer, but, this isn't a move we're going make. Bar the `schema` property on `APIView`, all the schema handling is contained in `rest_framework.schemas` by design.

**Comment by khomyakov42** [comment]
how i can override field to schema? To use monkey patching?

**Comment by carltongibson** [comment]
Subclass AutoSchema.
