### ISSUE TITLE
APIView always return 400 Bad Request when posting data

### ISSUE THREAD

**Issue by zhiyiZeng** [encode/django-rest-framework#6425]
![image](https://user-images.githubusercontent.com/20840761/51961161-ce849300-2496-11e9-89b5-48c7ec2501a3.png)

But when #print(self.request.data), it works perfectly.

![image](https://user-images.githubusercontent.com/20840761/51961209-f116ac00-2496-11e9-96cc-3c6934cb60fa.png)

I'm using Django 1.11, DRF 3.9.0, windows10.
Any help would be appreciated.

**Comment by tomchristie** [comment]
Hi there & thanks for your question.

The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions.

Thanks! 😀
