### ISSUE TITLE
How to create a record without operating a specific field?

### ISSUE THREAD

**Issue by fwhezfwhez** [encode/django-rest-framework#6436]
The question might be asked in another way. How to handle an auto-add field which is not primary key in Django. 
Hello, For some reasons table is not migrated from django.
// postgres
```sql
create table t(
    id serial primary key,
    show_index integer nextval('auto-add-1')
);
CREATE SEQUENCE 
auto-add-1
START WITH 1 
INCREMENT BY 1
NO MINVALUE 
NO MAXVALUE 
CACHE 1;
```
To ensure the sequence works, I exec `insert into t(id) values(1);` twice, and get records:
| id | show_index|
|:--|:--|
| 1 | 1 |
| 2 | 2 |

Field `show_index` should be controled by database.
In the python Django code,I've declared
`show_index = serializers.IntegerField(required=False)`
`show_index = models.IntegerField(auto_created=True)`
When I use rest api and post `{id:2}`, new record is to be
| id | show_index|
|:--|:--|
| 1 | 1 |
| 2 | 2 |
| 3 | null |

You see, both serializer or model config setting don't work.
How can I let field show_index use the db sequence in Django?

**Comment by tomchristie** [comment]
Hi there & thanks for your question.

The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions.

Thanks! 😀
