### ISSUE TITLE
Object level permissions on DjangoModelPermissions

### ISSUE THREAD

**Issue by khamaileon** [encode/django-rest-framework#644]
Hi guys,

I have an issue with Permissions. I use django-guardian for per-object permissions and I would like to add a view_'model_name' permission. I made my own DjangoModelPermissions class (http://pastebin.com/8k5HFemb) but when I add "GET': ['%(app_label)s.view_%(model_name)s']," to perms_map, I loose all permissions on the object.

Besides that, if I check if my user has the view_'model_name' permission, it's ok.
myuser.has_perm('poll.view_poll', obj) >> True

It drives me crazy :(

PS: I'm on Django 1.4.3 with the last revision of DRF

**Comment by albandum** [comment]
Did #1093 get removed ?? I had to fall back to the method described here to avoid having to set global permissions. Thanks !
