### ISSUE TITLE
Update docs for SearchFilter with Django 2.1

### ISSUE THREAD

**Issue by dgilge** [encode/django-rest-framework#6445]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Compare https://github.com/encode/django-rest-framework/blob/master/docs/api-guide/filtering.md#searchfilter
and https://docs.djangoproject.com/en/2.1/ref/contrib/admin/#django.contrib.admin.ModelAdmin.search_fields

## Expected behavior
If I'm not mistaken, the DRF documentation should mention that the search changed with Django 2.1. Something like:

> Django <= v2.0:
> 
> * `^` Starts-with search.
> * `=` Exact matches.
> * `@` Full-text search.  (Currently only supported Django's MySQL backend.)
> * `$` Regex search.
> 
> Django >= v2.1:
> 
> You can specify the desired search behavior by adding `__<lookup>` to the field. The older shortcuts are equal to:
> 
> * `^` = [`__startswith` Starts-with](https://docs.djangoproject.com/en/2.1/ref/models/querysets/#std:fieldlookup-startswith) search.
> * `=` = [`__iexact` Case-insensitive exact matches](https://docs.djangoproject.com/en/2.1/ref/models/querysets/#std:fieldlookup-iexact).
> * `@` = [`__search` Full-text search](https://docs.djangoproject.com/en/2.1/ref/contrib/postgres/search/#std:fieldlookup-search).
> * None = [`__icontains` Case-insensitive containment test](https://docs.djangoproject.com/en/2.1/ref/models/querysets/#std:fieldlookup-icontains).
> * `$` = Regex search.

Sorry for not opening a PR. But I'm not sure about the *Regex search* and I didn't have the opportunity to test anything.

This issue also solves #5216.

**Comment by rpkilby** [comment]
Hi @dgilge. DRF's search syntax is based off of Django's admin search, but `SearchFilter` has its own, distinct implementation. Django 2.1 adding support for arbitrary lookups does not affect `SearchFilter`.  Or are you suggesting that we add support for arbitrary lookups?

**Comment by carltongibson** [comment]
As @rpkilby says the two filters (Django admin, and DRF) are **not** the same. 

What's more, I'm not at all sure that exposing `__ADD-YOUR-OWN-LOOKUP` functionality via an API is a very good idea. (I'm not even sure it's a very good idea in the Django admin either, but at least there users are _"staff"_, so presumably not malicious in intent.) [*] 

I don't think a doc change is currently needed. 

(Unless I'm missing it, the `SearchFilterTests` are missing a `FTS`. As per #5216, if you wanted to add one, and we could see what breaks with the different DB backends, that would be a good start to extending that functionality.) 

[*]: Maybe I just worry too much.

**Comment by rpkilby** [comment]
> [*]: Maybe I just worry too much.

At a minimum, the lookups would need to be restrictable in some way. e.g., a `search_lookups` whitelist or something. That said, I'm also not inclined to add this to the core framework. It could be handled in a third-party extension though.

**Comment by dgilge** [comment]
OK, thank you for explaining. For me following sentence of the DRF docs sounded like DRF was using the admin search: "The `SearchFilter` class supports simple single query parameter based searching, and is based on the Django admin's search functionality."

> What's more, I'm not at all sure that exposing __ADD-YOUR-OWN-LOOKUP functionality via an API is a very good idea. (I'm not even sure it's a very good idea in the Django admin either, but at least there users are "staff", so presumably not malicious in intent.) [*]

I totally agree. When I understand it correctly, you have to define the allowed lookups in `search_fields` before you can use them in Django.

> At a minimum, the lookups would need to be restrictable in some way. e.g., a `search_lookups` whitelist or something. That said, I'm also not inclined to add this to the core framework. It could be handled in a third-party extension though.

I guess you can just use the search field lookups in DRF like `search_fields = ('username__iexact', 'email__search', 'profile__profession__icontains')`. I think that's actually sufficient. But I didn't have a chance to test it yet.
