### ISSUE TITLE
Document requirements on django.contrib 

### ISSUE THREAD

**Issue by mnieber** [encode/django-rest-framework#6448]
I'm trying to remove the database from my Django site. This includes removing dependencies on django.contrib, such as `django.contrib.sessions` and `django.contrib.contenttypes`. However, this seems to break DRF: my site only started working again when DRF was also removed.

I understand if DRF needs those django.contrib apps, but it would be nice if the dependencies on django.contrib were documented, e.g. "if you use any of the DRF authentication features, then django.contrib.auth and django.contrib.sessions are required", etc, etc.

**Comment by tomchristie** [comment]
In its current state this ticket is too general to be actionable. REST framework *as a whole* doesn’t require a database, or (I believe) necessarily depend on particular apps to be installed. However I think we could perfectly well consider narrowed down suggestions such as “*this authentication class* requires applications X, Y, Z to be installed”.

The mos obvious dependencies there are likely to be some of the authentication and permission classes.

**Comment by carltongibson** [comment]
And even `django.contrib.sessions` doesn't **require** a database... (it requires **some** backend, but...)

**Comment by mnieber** [comment]
Well, to give a more concrete (actionable) example: when I removed `django.contrib.sessions` from `INSTALLED_APPS` and `MIDDLEWARE`, my calls to `APIView` were crashing (i got http `500` errors). However, when I substituted `django.views.View` for `APIView`, the calls were succeeding again (as it should be, since my site does not use sessions).

So I do strongly have the impression that core parts of the DRF depend on `django.contrib.sessions`, and AFAIK this is not yet documented.

**Comment by carltongibson** [comment]
Hi @mnieber. It's almost certainly that you're using `SessionAuthentication`, which yes, relies on sessions and auth and ... If you strip down to a bare APIView (remove `authentication_classes` etc) you can dispatch without all that stuff. 

Very happy to review specific changes to the docs!

**Comment by mnieber** [comment]
Hi Carlton, you're right, I forgot that I need to change the defaults in the `REST_FRAMEWORK` settings. It works now. For anyone reading this later, both the following settings should be applied:

    REST_FRAMEWORK = {
        'DEFAULT_AUTHENTICATION_CLASSES': tuple(),
        'UNAUTHENTICATED_USER': None,
    }
