### ISSUE TITLE
Test failures vs Django master (3.0) because django.utils.six was removed

### ISSUE THREAD

**Issue by therefromhere** [encode/django-rest-framework#6449]
Tests are failing vs django master because django.utils.six and django.utils.encoding.python_2_unicode_compatible were just removed (https://github.com/django/django/commit/41384812efe209c8295a50d78b45e0ffb2992436 / https://code.djangoproject.com/ticket/27753), and they are used in lots of places.

eg: https://travis-ci.org/encode/django-rest-framework/jobs/489928209

What's the preferred solution?

a) Drop py2 and six (#6277 and some followup) (hopefully sometime before Django 2.2 is released)?
b) Add six as a dependency until py2 is dropped?  (it'd have to be a bit more than this because e.g. `django.utils.encoding.python_2_unicode_compatible` was also removed)
c) other?

## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

Run tests vs django master - eg `tox -e py37-djangomaster`

## Expected behavior

Tests to pass

## Actual behavior

Fails with `ImportError: cannot import name 'six' from 'django.utils'`

**Comment by tomchristie** [comment]
Probably the simplest thing is that *once* 2.2 is in beta, we start to roll our next major release, which drops Python 2 support.

**Comment by carltongibson** [comment]
Django master isn’t due to be released until December, as Django 3.0. 

The failures against 2.2 are because we don’t have migrations in the test models as per Tim’s https://github.com/encode/django-rest-framework/pull/6422#issuecomment-459553441

So I think we have time here. Let’s get 2.2 passing this week. Then we can decide on the timeline for dropping Python 2.0.

**Comment by therefromhere** [comment]
@carltongibson ah my mistake, I thought master was still destined for 2.2, I didn't notice the stable/2.2 branch.  Yeah this is much less pressing than I thought.

**Comment by auvipy** [comment]
I believe this could e closed.

**Comment by carltongibson** [comment]
Yep, this will be accounted for when dropping Python 2. Any failures against Django 3.0 will be addressed in time. Thanks all.
