### ISSUE TITLE
Serializer doesn't support annotated fields properly

### ISSUE THREAD

**Issue by arielpontes** [encode/django-rest-framework#6451]
Let's say I have the following model:

```
class Track(models.Model):
    album = models.ForeignKey(Album)
    name = models.CharField()
    number = models.CharField()
```
And serializer:
```
class Track(serializers.ModelSerializer):
    class Meta:
        model = TrackSerializer
        fields = ('name', 'number', 'album_name')
```
And view:
```
class TrackListView(generics.ListAPIView):
    def get_queryset(self):
        return Track.objects.annotate(album_name=F('album__name'))
```
Accessing this view will result in the following error:

`FieldError: Cannot resolve keyword 'album_name' into field. Choices are: name, number, album`

If I try to specify this custom field manually, like this:
```
class Track(serializers.ModelSerializer):
    album_name = serializers.CharField(source='album_name')
    class Meta:
        model = TrackSerializer
        fields = ('name', 'number', 'album_name')
```
I get the same error. If I use any name other than the label I used in the annotation, it works:

```
class Track(serializers.ModelSerializer):
    name_of_album = serializers.CharField(source='album_name')
    class Meta:
        model = TrackSerializer
        fields = ('name', 'number', 'name_of_album')
```

This doesn't seem to make sense. I found myself having to find two names for every annotation I make. It should be possible to use the same name for the `source` parameter and the `annotation` done on the queryset.

**Comment by xordoquy** [comment]
Using a serializer as model won't work.

**Comment by arielpontes** [comment]
Sorry, I had some errors in my example code. I fixed it now and in the process realized the errors were somewhat different. I updated the description.

**Comment by xordoquy** [comment]
> Isn't it redundant to have to specify the field manually though?

No because `album_name` is no field. It's a data and doesn't have any field declaration tied to it on the model thus no way to have introspection work with it.

Please note that the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!

**Comment by mihow** [comment]
My solution for annotated fields is to add a dummy method to the model.

view:
```
class TrackListView(generics.ListAPIView):
    def get_queryset(self):
        return Track.objects.annotate(album_name=F('album__name'))
```

model:
```
class Track(models.Model):
    album = models.ForeignKey(Album)
    name = models.CharField()
    number = models.CharField()

    def album_name(self):
        raise ValueError("The album_name attribute is only accessible if the queryset is annotated")
```
