### ISSUE TITLE
Cant accessed from other server when test on postmen code work, i was install cors and same error , help me..

### ISSUE THREAD

**Issue by jemmycalak** [encode/django-rest-framework#6452]
ConnectionError at /a
HTTPConnectionPool(host='my-url.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04E9DED0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

**Comment by tomchristie** [comment]
Hi there & thanks for your question.

The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions.

Thanks! 😀
