### ISSUE TITLE
"count" in CursorPagination?

### ISSUE THREAD

**Issue by JulienPalard** [encode/django-rest-framework#6456]
## Checklist

- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)

OK this may be handled in third party, but I'm still posting, in case. The `CursorPagination` does not give a `count`, is this voluntary? It looks easy to implement and I'm currently trying it in my code by inheriting the `CursorPagination` like this:

```python
class CursorPaginationWithCount(pagination.CursorPagination):
    def paginate_queryset(self, queryset, request, view=None):
        self.count = self.get_count(queryset)
        return super().paginate_queryset(queryset, request, view)

    def get_count(self, queryset):
        """
        Determine an object count, supporting either querysets or regular lists.
        """
        try:
            return queryset.count()
        except (AttributeError, TypeError):
            return len(queryset)

    def get_paginated_response(self, data):
        return response.Response(
            OrderedDict(
                [
                    ("next", self.get_next_link()),
                    ("previous", self.get_previous_link()),
                    ("count", self.count),
                    ("results", data),
                ]
            )
        )
```

I can do a PR, implementing it in CursorPagination directly, if I see my code is reliable in my service. Is it worth it or should this go to third party?

**Comment by tomchristie** [comment]
It's intentional yup - CursorPagination is intended to deal with cases where you may have very large result sets and don't want to perform full counts or iterate through a massive result set to get to the starting index.

**Comment by jet2018** [comment]
@tomchristie is right, counting results will make this type of pagination lose its main objective, but I would request that django core team considers on how to give us the total of the results in any other way so that we get it too.

**Comment by papansarkar101** [comment]
But how can I then have pagination with custom page_size where all the objects are having same ID. In this case, CursorPagination only worked fine but it doesn't have count. I need the count as well. 

Please help!

**Comment by phichawee** [comment]
Really
