### ISSUE TITLE
Third party link in issue template is failing

### ISSUE THREAD

**Issue by JulienPalard** [encode/django-rest-framework#6457]
In the following checklist:

## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

Click on the `in the form of third party libraries`.

## Expected behavior

Learn about third party libraries :)

## Actual behavior

404

**Comment by xordoquy** [comment]
Indeed, should be "https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages" in the template.
Leaving this to @tomchristie as I don't have the proper permissions to change it.

**Comment by rpkilby** [comment]
> ## Expected behavior
> Learn about third party libraries :)

> ## Actual behavior
> 404

I recently reorganized some of the docs. I did not think to check links outside of the docs. 😓

**Comment by JulienPalard** [comment]
@rpkilby no problem, it happen, and it's now fixed, don't worries :)
