### ISSUE TITLE
AssertionError if Field.source equal to field_name

### ISSUE THREAD

**Issue by belkka** [encode/django-rest-framework#6459]
https://github.com/encode/django-rest-framework/blob/de3929fb3334262bbf57980fff41d3f8c6f2b8b4/rest_framework/fields.py#L375

When defining a serializer field one need to set `source` attribute to value based on some global constant used across the project, e. g. `name = SomeField(source=NAME_SRC)` they have to check that `NAME_SRC != 'name'`. If keep `source=NAME_SRC`, editing the constant later *may* break app in unexpected way. If omit `source=...` when `NAME_SRC == 'name'`, editing this constant break app in even more unexpected way.

```
        # In order to enforce a consistent style, we error if a redundant
        # 'source' argument has been used. For example:
        # my_field = serializer.CharField(source='my_field')
```
According to comment the goal of this assertion is to enforce avoiding redundant **string literal** in simple cases, but, in fact, to make code always working properly in other cases you have to write something like
```
my_field = serializer.CharField(**(
    {'source': MY_CONFIGURABLE_FIELD} if MY_CONFIGURABLE_FIELD != 'my_field' else {}
))
```

I suggest to remove the assertion or at least replace it with some kind of warning.

**Comment by belkka** [comment]
Should I make a pull request?

**Comment by tomchristie** [comment]
Thanks, but I'd rather leave things as they are.
Forcing users not to end up with redundant 'source=' is a benefit for most users, and the use case here is enough of an edge case that you'll just need to work around it, sorry.

**Comment by belkka** [comment]
Why isn't runtime warning enough?

**Comment by rpkilby** [comment]
@belkka. Warnings are useful for alerting developers about something they should react to. e.g., a module has been deprecated in favor of another, and their code should be updated. In this case though, DRF is enforcing stylistic convention, and a runtime warning isn't the appropriate mechanism for this. You could argue whether DRF should enforce stylistic convention, but that's a separate discussion.

**Comment by belkka** [comment]
@rpkilby. I sincerely do not understand your explanation why warning is not appropriate :( 

> Warnings are useful for alerting developers about something they should react to

It is just the case O_o

> DRF is enforcing stylistic convention, and a runtime warning isn't the appropriate mechanism for this

Neither is `assert`

> You could argue whether DRF should enforce stylistic convention

Well, actually I think it is great feature of DRF because usually it makes our code more clear, but in this particular case the problem is *how* it is implemented. Equality of `field_name` and `source` values indicates about weird code only under assumption that `source` is defined using string literal. In other cases there is no reason to forbid them being equal. More generally, we have following situation: there is a function with optional arugment
```
def sum_digits(number, base=10):
    quot, rem = divmod(number, base)
    return rem + (sum_digits(quot, base) if quot else 0)
```
We do not want people to write something like `sum_digits(x, 10)` because we made 10 default value for them. So we insert check:
```
def sum_digits(number, base=None):
    assert base != 10, "10 is default value"
    if base is None:
        base = 10
    quot, rem = divmod(number, base)
    return rem + (sum_digits(quot, base) if quot else 0)
```
but this means that now it is wrong to pass any variables or expressions as second argument of `sum_digits`, e. g. `sum_digits(x, get_base())` because this won't work as soon as `get_base()` return 10.

It would be great to have something preventing us from writing redundant code, but as you can see *detecting* that redundant code is not so easy as it may look like. This kind of naive `assert arg != default_value` is bad approach because in fact it disallows to use function in any non-trivial cases. It is not obvious why it should be considered ok for DRF `Serializer`.

**Comment by carltongibson** [comment]
@belkka This has been this way since v3.0 IIRC. Yours is the first complaint. Using asserts is the style DRF goes for, always has. I’m not sure it’s something there’d be any appetite to change. 

I do see that in your particular example it requires a bit more code but I think that’s just the cost. The benefit is failing earlier and harder and so helping people write better code. Sorry.
