### ISSUE TITLE
Bulk token generation

### ISSUE THREAD

**Issue by beruic** [encode/django-rest-framework#6461]
I am missing an easy way to (re)generate tokens for a (query)set of users.

I came here to make a pull request, but thinking about it I would like input from the community on whether my thoughts are far out, and I should pull myself together and create each token with a separate save.

From my investigation I have concluded that this could be fixed by moving key generation to the constructor, and thus making it possible to save a bunch of new tokens with `Token.objects.bulk_create()`.

This raises the question of why the [key generator method](https://github.com/encode/django-rest-framework/blob/1660469ed8a2afd7fd08c6087ec9fc341c30b4f9/rest_framework/authtoken/models.py#L37) is not static or a class method.
It could arguably be made static or a class method, but when discussing with myself, I conclude that then it would be hard to override with a custom method that needs access to `self`.
This is however also infeasible as long as `Token` is not based on an `AbstractToken` class.

**Comment by carltongibson** [comment]
> I am missing an easy way to (re)generate tokens for a (query)set of users.

Something like this in a for-loop: 

```
def generate_new_token(user):
    user.auth_token.delete()
    Token.objects.create(user=user)
```

We don't want to add complexity to the provided token authentication implementation. You're welcome to make additions in your own project, or build a third-party package with something more advanced. (IIRC such already exists...)

**Comment by beruic** [comment]
I have been lingering around this one for some time now, so here are my thoughts.

**1.** I have concluded that is a bad idea to put token generation in the constructor, since this could lead to newly created token keys being returned, but not saved.

**2.** Currently in my solution I have the following method for regenerating Tokens for a (query)set of users:

```python
def regenerate_user_tokens(queryset):
    Token.objects.filter(user__in=queryset).delete()
    generator = Token()
    new_tokens = [Token(user=u, key=generator.generate_key()) for u in queryset.iterator()]
    Token.objects.bulk_create(new_tokens)
```
It kinda feels a bit silly to construct an object to use a method that has no side effects on the instance, and thus is essentially static.

What @carltongibson propose in the previous comment will make a database request per created object, while here they are created in bulk. But since `bulk_create` does not call the `save()` method, the token key must be added through an argument.

If the `generate_key()` method was a class method, I could invoke it without creating an instance of `Token`. Then my code above could be turned into the following:

```python
def regenerate_user_tokens(queryset):
    Token.objects.filter(user__in=queryset).delete()
    new_tokens = [Token(user=u, key=Token.generate_key()) for u in queryset.iterator()]
    Token.objects.bulk_create(new_tokens)
```

I know this is kinda a smallish thing, and I can understand why people would disregard it. now, at least, it's off my chest :)
