### ISSUE TITLE
Broken link on Browser enhancements page

### ISSUE THREAD

**Issue by kaoru-furuta** [encode/django-rest-framework#6465]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [ ] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Description

This link on Browser enhancements page is broken:

- broken link: https://github.com/encode/ajax-form

- page: https://www.django-rest-framework.org/topics/browser-enhancements/

The repository linked seems to be dead, has this been integrated into DRF? I think this needs to be updated with the correct link, or removed if no link exists.

**Comment by rpkilby** [comment]
It might have been auto-replaced when DRF was moved to the encode organization. You can still find ajax-form under @tomchristie's account.
