### ISSUE TITLE
Manage Viewset list HTTP returned code

### ISSUE THREAD

**Issue by marcoooo** [encode/django-rest-framework#6466]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
None

## Expected behavior

Viewset classes automatically return good http header when a list is retrieved, but in case of an empty list, it could be good to return a 204 - No Content instead of 200. Because even if the request was successful result is empty. May it worth a new parameter or config to viewset to let user set their own return HTTP code for this particular behaviour: either 200 or 204 (I don't think this would have a big impact for some Javascript test sur as 'success' because this is still a 2XX returned code.

## Actual behavior

Viewset return 200 HTTP code when GET returned list is empty. I saw some discussion about this on previous issues, but related to delete returned code.

**Comment by xordoquy** [comment]
I am going to close this because:
- It is simple enough to override the default behavior if required
- I think returning a 204 instead of a 200 with an empty list may not be a good idea in most cases - client needs a different parsing strategy.

**Comment by marcoooo** [comment]
Thanks for your response. I agree override is simple.
