### ISSUE TITLE
Serializer save priority should be less than model save()

### ISSUE THREAD

**Issue by omkar-dsd** [encode/django-rest-framework#6471]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
1. Include a _many-to-many_ field in model and in serializer.
2. Override model `save()` method to add or remove something from many-to-many field. 

## Expected behavior
1. What done in model save method should be final.
## Actual behavior
1. No matter what you do in model `save()` method, the serializer will take all the related field data **after** model save is called upon. Whatever comes serializers m2m field is saved as it is, no matter what you do in model `save()`

I can take up this issue if approved. The expected behavior should be model save should be given more priority by default.

**Comment by xordoquy** [comment]
This is a design decision on Django's side: Django managers provide a `create` method that doesn't call `save`.
Django REST framework creates instances through the manager's `create`.
Note that if you're updating you'll notice the model's save being called as "final".
