### ISSUE TITLE
Update serializer BooleanField docs for Django 2.1's removal of blank=True

### ISSUE THREAD

**Issue by edmorley** [encode/django-rest-framework#6474]
## Checklist

- [X] I have verified that that issue exists against the `master` branch of Django REST framework.
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [X] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [X] I have reduced the issue to the simplest possible case.

## Proposed docs change

Hi!

In Django 2.1, as part of adding null support to BooleanField, the previously implicit/hardcoded `blank=True` of `BooleanField` was removed:
​https://github.com/django/django/commit/5fa4f40f45fcdbb7e48489ed3039a314b5c961d0#diff-bf776a3b8e5dbfac2432015825ef8afeL995

This means that d-r-f serializer `BooleanField`s are no longer generated with a `required=False` on the field. (Which in our case meant new `This field is required` validation errors in our tests from cases where our API was using `PUT` when it really should have been using `PATCH`.)

So the mention here needs updating (ideally to mention the behaviour changed in Django 2.1, since these docs were one of the places I looked at when trying to figure out why tests were failing post Django 2.1 upgrade):
https://github.com/encode/django-rest-framework/blame/0e10d32fb122619a7977909536b642d09603192a/docs/api-guide/fields.md#L127

I've also filed a Django ticket since this change isn't mentioned in the Django 2.1 release notes or on the fields docs page:
https://code.djangoproject.com/ticket/30216

Many thanks :-)

**Comment by carltongibson** [comment]
OK, yep. Good. It looks like you've covered all the corners on that one. 🙂
Thanks for the report.

**Comment by edmorley** [comment]
The updated docs look great - thank you :-)
