### ISSUE TITLE
What happened to 3.9.x?

### ISSUE THREAD

**Issue by beruic** [encode/django-rest-framework#6476]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Issues
Looking at https://www.django-rest-framework.org/, the newest version seems to be `3.9.1`, however, under https://github.com/encode/django-rest-framework/releases, 3.8.2 is the latest release, and the tags for `3.9.0` and `3.9.1` are hidden.
Is this because these versions are not considered stable?

Furthermore, I seem to be unable to find a changelog mentioning the two versions.
Where is the official source for changelog on this project?

**Comment by carltongibson** [comment]
Release announcement: 
  https://www.django-rest-framework.org/community/3.9-announcement/

Change Notes: 
  https://www.django-rest-framework.org/community/release-notes/#39x-series

TBH GitHub's "Releases" feature is a bit of a pain, because it's just more work and people expect it to be canonical (when the docs on the site are...)

**Comment by beruic** [comment]
@carltongibson Could you then perhaps just link to https://www.django-rest-framework.org/community/release-notes/ from the README?
