### ISSUE TITLE
Importing rest_registration.schemas may raise AppRegistryNotReady

### ISSUE THREAD

**Issue by apragacz** [encode/django-rest-framework#6478]
This bug was found by someone using two DRF-based packages in conjunction: `django-rest-registration` and `django-rest-framework-simplejwt`, see below:

https://github.com/apragacz/django-rest-registration/issues/36

The bug was fixed in `django-rest-registration` but the original issue in DRF may still cause problems.

## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [ ] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

* Install `django-rest-framework-simplejwt`
* Add `JWTAuthentication` to `REST_FRAMEWORK['DEFAULT_AUTHENTICATION_CLASSES']`:
```python 
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}
```
* Create a [Django check](https://docs.djangoproject.com/en/dev/ref/checks/) which imports directly or indirectly `rest_registration.schemas`
* Start the server (`./manage.py runserver`) or just run the checks (`./manage.py check`) 

## Expected behavior

module gets imported without any problems.

## Actual behavior

`AppRegistryNotReady` is being raised.

**Comment by carltongibson** [comment]
This is a bug in the simple JWT package. [It's calling `get_user_model()` at import time](https://github.com/davesque/django-rest-framework-simplejwt/blob/fb248971406c7807b71e347c3381f1b198e07686/rest_framework_simplejwt/state.py#L6) rather than using `settings.AUTH_USER_MODEL`. This is leading to the import failure when trying to fetch the class added to `api_settings.DEFAULT_AUTHENTICATION_CLASSES` (as per the stack trace in https://github.com/apragacz/django-rest-registration/issues/36)

"Don't use models at import time" is the rule. All modules referenced in DRF settings should be importable without triggering `AppRegistryNotReady`.

**Comment by apragacz** [comment]
@carltongibson I agree that it is not the best design in `django-rest-framework-simplejwt` , but I also think that accessing any settings attribute (whether it is Django `settings` attribute or DRF `api_settings` attribute) at import time is an antipattern, so I would consider fixing it.

I will try to fix the problem in `django-rest-framework-simplejwt` you mentioned.

**Comment by carltongibson** [comment]
Django itself accesses many settings prior to app ready. `INSTALLED_APPS` and `DATABASES` themselves being the most obviously necessary ones... Accessing settings is not a problem. "Doing things in settings", specifically things that need models, is the issue, hence the `AppRegistryNotReady` exception.
