### ISSUE TITLE
Document that action methods cannot overwrite View attrs

### ISSUE THREAD

**Issue by nawarnoori** [encode/django-rest-framework#6490]
## Checklist

- [X] I have verified that that issue exists against the `master` branch of Django REST framework.
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [X] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [X] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

I upgraded our app to DRF 3.9.2 and noticed this happening. We have a viewset that declares an action called `name` and I started getting a very weird exception every time I tried to `POST` to it. Other endpoints were unaffected.

## Steps to reproduce

Declare an `action` in a `viewset` that is called `name`:
```
@action(methods=('post',), detail=False, permission_classes=())
def name(self, request):
    return Response(['ok'], 201)
```
Add it to urls.py:
```
from rest_framework.routers import SimpleRouter

from drf_issue.app import views
...
router = SimpleRouter()
router.register('test', views.TestViewSet, 'test-viewset')
urlpatterns += router.urls
```
Try `POST`-ing to this endpoint:

```
curl -X POST -H "Content-Type: application/json" -d '{}' http://127.0.0.1:8000/test/name/
```
## Expected behavior
The endpoint returns a 201

## Actual behavior
```
TypeError at /test/name/
'str' object is not callable
...
Traceback:

File "/home/nawarnoori/.virtualenvs/sandbox/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/home/nawarnoori/.virtualenvs/sandbox/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  126.                 response = self.process_exception_by_middleware(e, request)

File "/home/nawarnoori/.virtualenvs/sandbox/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  124.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/nawarnoori/.virtualenvs/sandbox/lib/python3.6/site-packages/django/views/decorators/csrf.py" in wrapped_view
  54.         return view_func(*args, **kwargs)

File "/home/nawarnoori/.virtualenvs/sandbox/lib/python3.6/site-packages/rest_framework/viewsets.py" in view
  116.             return self.dispatch(request, *args, **kwargs)

File "/home/nawarnoori/.virtualenvs/sandbox/lib/python3.6/site-packages/rest_framework/views.py" in dispatch
  495.             response = self.handle_exception(exc)

File "/home/nawarnoori/.virtualenvs/sandbox/lib/python3.6/site-packages/rest_framework/views.py" in handle_exception
  455.             self.raise_uncaught_exception(exc)

File "/home/nawarnoori/.virtualenvs/sandbox/lib/python3.6/site-packages/rest_framework/views.py" in dispatch
  492.             response = handler(request, *args, **kwargs)

Exception Type: TypeError at /test/name/
Exception Value: 'str' object is not callable
```
I have asked about this on [SO](https://stackoverflow.com/questions/55024513/django-drf-3-9-2-breaks-my-viewset-actions) and after spending some time digging I believe the issue is [this PR](https://github.com/encode/django-rest-framework/pull/5605/files#diff-faaea574b0b229b4c6ccf6078f194d17), specifically the `cls.name` variable.

Not sure if an issue but it should be documented perhaps that some names are reserved. I got around this using `url_path='name'`.

I have prepared a small project that replicates this:
[issue.tar.gz](https://github.com/encode/django-rest-framework/files/2937935/issue.tar.gz)
Just call `python manage.py runserver` (from a compatible python 3 executable).

**Comment by rpkilby** [comment]
Hi @nawarnoori - this is functionally the same issue as #6083. The root problem is that any View class attributes cannot be overridden with a detail view. 

Some of these restricted names are documented [here](https://www.django-rest-framework.org/api-guide/viewsets/#introspecting-viewset-actions), but it isn't currently clear that you cannot create extra actions with those names. We should also document the workaround, which is something like:

```python
@action(methods=['get'], detail=True, url_path='name', url_name='name')
def _name(self, request, pk):
    pass
```

**Comment by carltongibson** [comment]
🧐 Thought for later: Would it be feasible to ass a system check to pick up this sort of thing?

**Comment by rpkilby** [comment]
The problem right now is that these attrs are set inside `as_view`, which isn't inspectable. I think we could define these attrs on the `ViewSet` instead, then add a check inside the `action` decorator to complain if the method is overwriting existing class attributes throughout the MRO. This should be possible as a runtime check.

I don't think we could necessarily do this as a system check though, since the methods will have already overridden the attrs on the class, and we can't really distinguish between user/non-user classes in the MRO. e.g., we can't just check the MRO of `ViewSet`, as an extension might provide a subclass that defines additional class attrs. Sorry if this explanation isn't very clear. I can go into more detail if it doesn't make sense. But tl;dr: the check would probably need to happen in the `action` decorator, not a system check.

**Comment by xordoquy** [comment]
router's could test that it is a callable and callable has a `mapping` attribute [for example](https://github.com/encode/django-rest-framework/blob/master/rest_framework/decorators.py#L147).

I'm not confortable with the traceback. It looks like it crashes inside the exception handler.
Is it possible to get the full traceback ?

**Comment by rpkilby** [comment]
#6083 largely has the same traceback.

I think this is actually a symptom of how we handle uncaught exceptions. Essentially, `dispatch` catches the exception, and loses the underlying context (i.e., the line that's *actually* raising the `TypeError`, which should be:
https://github.com/encode/django-rest-framework/blob/9d06e43d05abf1ec57f15566b29ad53ac418ae05/rest_framework/views.py#L492

**Comment by nawarnoori** [comment]
What happens in my case is that inside `views.APIView.dispatch`, `handler` is assigned `'Name'`:
```python
if request.method.lower() in self.http_method_names:
    # request.method.lower() is 'post' and self.post is equal to 'Name'
    handler = getattr(self, request.method.lower(),
                      self.http_method_not_allowed)
```
and then called a few lines further down:
```python
   # this is essentially doing 'Name'(request, *args, **kwargs) which fails with the aformentioned uncaught TypeError
   response = handler(request, *args, **kwargs)
```

**Comment by tomchristie** [comment]
Isn't this just a case of Python being Python? There's all sorts of public API that can get accidentally overwritten when using subclassing-for-behaviour. Which isn't super ideal or graceful, but is also the price you pay for the casual kinda style that Python brings to the table.

Anyways, if someone wants to advocate for a change here and has a concrete proposal, then perhaps there's something for us to follow up with, bu otherwise I think this falls into the Python-is-dynamic-and-can-be-a-bit-smoochy category for me.
