### ISSUE TITLE
Testing docs should briefly mention needing to giving permission to create db

### ISSUE THREAD

**Issue by johnthagen** [encode/django-rest-framework#6496]
When going through the testing guide for the first time: https://www.django-rest-framework.org/api-guide/testing/

I immediately hit the issue that my django postgres user didn't have permission to create the needed test database: https://www.django-rest-framework.org/api-guide/testing/

I think it would be helpful if a small note was added to the testing docs about this so new users could be informed about this potential obstacle.

This stackoverflow post explains it well: https://stackoverflow.com/a/14186439/1398841

**Comment by xordoquy** [comment]
I don't think this specific point should be noted in the docs.
On the other hand, I'd be fine with a more general note saying it uses Django's test system with a few changes with a link to the Django testing documentation.

**Comment by rpkilby** [comment]
Agreed - this is a Django testing issue, not a DRF testing issue. Happy to look at a PR per @xordoquy's recommendation.
