### ISSUE TITLE
Misleading IsAdminUser signature

### ISSUE THREAD

**Issue by Vincent089** [encode/django-rest-framework#6497]
Class IsAdminUser has a misleading name as it only checks for "is_staff" which does not make the user an "admin"

class IsAdminUser(BasePermission):
    """
    Allows access only to admin users.
    """

    def has_permission(self, request, view):
        return bool(request.user and request.user.is_staff)

**Comment by tomchristie** [comment]
I think it's close enough to be clear. We've not had the ticket raised before, and that class has been in place for a long time now.

Django's docs: "By default, logging in to the admin requires that the user has the is_superuser or is_staff attribute set to True."
