### ISSUE TITLE
how to use multithreading in django rest framework???

### ISSUE THREAD

**Issue by rmohamedfazil** [encode/django-rest-framework#6505]
I am using Django rest framework. I had a rest URL when i call that URL at a time from various 3, 4 streaming client, I got a response from only one client remaining client not responding me for that purpose only i want to know how to use multithreading in Django rest framework?  how to resolve this problem? can anyone help me out this problem?

**Comment by tomchristie** [comment]
Hiya.

The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) would be the best place to take this. Though I think you'll need to try to describe more clearly what the issue is.
