### ISSUE TITLE
How to  Call a Rest URL at a same time from 4 streaming client?

### ISSUE THREAD

**Issue by rmohamedfazil** [encode/django-rest-framework#6507]
I had the rest URL like(https://marketguru/django/mongodb). I call that URL to POST a record into store various database like Mysql, MongoDB, Mlab. For Post a record I am using only one common REST URL(https://marketguru/django/mongodb).  I call that URL from 4 salesforces streaming client at the same time for example[12/mar/2019  10:27:50]. I got a response from only one client remaining not responding. I call that URL from 2 salesforces streaming client at a various time for example[12/mar/2019  10:27:50],[12/mar/2019  10:27:51]. I got a response from both clients. for my knowledge, we call a rest URL at the same time is the problem because we post 4 requests at a time only one request is completing remaining missing. I want to call the common rest URL from various 4 or 5 clients at the same time. how to resolve this problem in Django REST Framework? Any multithreading concepts are there in Django REST Framework? Anyone help me out this problem?

**Comment by tomchristie** [comment]
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place for usage questions - we aim to keep the issue tracker for bugs and actual work on the project itself.

(Aside: REST framework will be multithreaded by default - the server will take care of that for you.)
