### ISSUE TITLE
怎么修改序列化后的数据呢

### ISSUE THREAD

**Issue by yaguang1994** [encode/django-rest-framework#6510]
怎么修改序列化后的数据呢,比如里面以分为单位的钱数转为元为单位.

**Comment by tomchristie** [comment]
> "How to modify the serialized data, for example, the amount of money in the unit is converted into yuan"

**Comment by tomchristie** [comment]
Hi there & thanks for your question.

The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions.

Thanks! 😀
