### ISSUE TITLE
APIView class has no attribute 'action'

### ISSUE THREAD

**Issue by diegohdez90** [encode/django-rest-framework#6515]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

I have my `APIView` class:

```
class SufficiencyCancelDocumentView(APIView):

    permission_classes = (SufficiencyCancelPermission,)

    def put(self, request, folio):
        ...
       return Response(...)
```

I call my endpoint:

```
urlpatterns: [
    ...
    path('sufficiency/<folio>/cancel', SufficiencyCancelDocumentView.as_view()),
    ...
]
```

My permissions:

```
def has_full_permission():
    return ['create', 'list', 'retrieve', 'update', 'partial_update']

...
class SufficiencyCancelPermission(BasePermission):
    def has_permission(self, request, view):
        if request.user.area in 'REPS':
            return view.action in has_full_permission()
        else:
            return has_superuser_permission(request) # Called from another file

```

And return a status error 500.

## Expected behavior

No display error and extract `action` from `APIView` class.

## Actual behavior

Display: this error:
```
'SufficiencyCancelDocumentView' object has no attribute 'action'
```

**Comment by xordoquy** [comment]
Hi,

`APIView` has no action (it's something specific to `ViewSet`).
The expected behavior here is the one I'd expect.
I'm closing this issue on that basis.
I will consider reopening with a proper argument about why the actual behavior would need to be changed.

**Comment by alecko85** [comment]
Hi xordoquy, the method `_get_responses`I have a GET method that returns a single object, but by default in `openapi.AutoSchema._get_responses()` the GET methods are considered as an array. If I could set an action to GET methods this behavior can change and generated schema reflect reality.
Thanks

**Comment by xordoquy** [comment]
This is unrelated to the initial question.
Please use the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) for discussions and usage questions. Thanks!
