### ISSUE TITLE
Plain-text parser is merging request body to method type.

### ISSUE THREAD

**Issue by cyberaa** [encode/django-rest-framework#6516]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

**Parser(example from documentation)**
```
class PlainTextParser(parsers.BaseParser):
    """Custom plain text parser to extract 'text/plain' payloads from requests."""

    media_type = 'text/plain'
    format = 'text'

    def parse(self, stream, media_type=None, parser_context=None):
        """Simply returns a string representing the body of the request.

        Args:
            stream (bytes): A stream-like object representing the body of the request.
            media_type (str): Default 'Content-type' of the request.
            parser_context(dict): Dictionary containing any additional context that is required to parse the content.

        Returns:
            `data`: will simply be a string representing the body of the request.
            `files`: will always be `None`.
        """
        try:
            return stream.read()
        except ValueError as error:
            raise exceptions.ValidationError('Text-plain parse error - %s' % error)
```
**View**
```
@decorators.api_view(['POST'])
@decorators.parser_classes((parsers.PlainTextParser,))
def test_view(request):
    return response.Response({'received data': request.DATA})
```

**Call**
```
POST http://localhost:80/test
Headers: 
 - Content-Type: text/plain
Body: 2
```

**Response**:
```
{
    "detail": "Method \"2POST\" not allowed."
}
```

## Expected behavior
**Response**:
```
{
   "received data": "2"
}
```
## Actual behavior
```
{
    "detail": "Method \"2POST\" not allowed."
}
```

It seems it's merging the request body from POST to the Method somehow. I couldn't find any references to this behavior when searching, so I guess it's a newly found bug. The parser was extracted from DRF's documentation(https://www.django-rest-framework.org/api-guide/parsers/).

Could you have a look?

Thanks.

**Comment by turfaa** [comment]
I can't reproduce the error. Can you give the complete HTTP request?

Also, are you sure you're in the master branch? Because you're using `request.DATA` which has been deprecated in version 3.0 and has been fully removed in version 3.2.

**Comment by tomchristie** [comment]
Assume you must be issuing a malformed http request or something like that.
