### ISSUE TITLE
Cannot cancel funding plan

### ISSUE THREAD

**Issue by akosladanyi** [encode/django-rest-framework#6517]
On [this](https://fund.django-rest-framework.org/topics/funding/) page one can sign up for funding plans, however there is no way to cancel a subscription despite the page claiming one can "cancel at any time". Also no one replies to emails sent to funding@django-rest-framework.org.

**Comment by tomchristie** [comment]
I think the funding@ email is broken - apologies I’ll lool into that. Drop me a line on tom@tomchristie.com

**Comment by tomchristie** [comment]
More than happy to refund any payments since a requested cancellation.
