### ISSUE TITLE
Please provide examples of testing file and image uploads

### ISSUE THREAD

**Issue by bukowa** [encode/django-rest-framework#6536]
I think i tried everything while testing ````serializers.ImageField(required=True)````
But each time i receive ````{'image': [ErrorDetail(string='No file was submitted.', code='required')]}````

None of stackoverflow or google answers really work, such a trivial and simple task but this is not clear what do i actually pass to the test client data? ````image```` variable below

````python

# serializer
class ImageUploadSerializer(serializers.Serializer):

    image = serializers.ImageField(required=True)


# view
class ImageUploadApiView(GenericAPIView):

    serializer_class = ImageUploadSerializer
    parser_classes = (MultiPartParser, )

    def post(self, request):
        serializer = self.get_serializer(data=request.data)
        if serializer.is_valid(raise_exception=True):
            print(serializer.data)
            return Response(serializer.data)


# test
        image = ???
        resp = self.client.post(
            reverse_lazy('uploadimage'),
            data={'image': image},
            content_type='multipart/form-data'
        )
````
Can someone please explain how do you test an image / file upload ?

**Comment by xordoquy** [comment]
This is exampled in the [Django documentation](https://docs.djangoproject.com/en/dev/topics/testing/tools/#django.test.Client.post).
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!

**Comment by tomchristie** [comment]
I guess we could accept pull requests linking from relevant sections in our docs to the main Django docs. Happy to take suggestions there.

**Comment by bukowa** [comment]
Because it is better to ask a specified question and get a specified answer, for further reference this is working code:


````python
import tempfile

from PIL import Image
from django.test import TestCase
from rest_framework.reverse import reverse_lazy


class ImageUploadTestCase(TestCase):

    def test_upload(self):

        image = Image.new('RGB', (100, 100))

        tmp_file = tempfile.NamedTemporaryFile(suffix='.jpg')
        image.save(tmp_file)
       
        # important line, why?
        tmp_file.seek(0)

        resp = self.client.post(
            reverse_lazy('uploadimage'),
            data={'image': tmp_file},
            # prefered over 'content_type' param, why?
            format="multipart"
        )

````
