### ISSUE TITLE
Cannot add "<xx: xx object>": instance is on database "default", value is on database "backup"

### ISSUE THREAD

**Issue by ghostry** [encode/django-rest-framework#6538]
```
djangorestframework = "==3.9.2"
#settings.py
DATABASE_ROUTERS = ['website.dbRouter.DefaultRouter']
#dbRouter.py
class DefaultRouter(object):
    def db_for_read(self, model, **hints):
        return 'backup'

    def db_for_write(self, model, **hints):
        return 'default'
#models.py
xx = models.ManyToManyField(xx, null=True, verbose_name='xx')
```
The database is read and written separated, and many-to-many errors occur.
Ask for help

**Comment by tomchristie** [comment]
Hi there & thanks for your question.

The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions.

Thanks! 😀

**Comment by ghostry** [comment]
There are no people in the discussion group, I solved it myself.
I think this is not a usage issue, it is a development issue.
I did not see the processing of database read and write separation in the source code.
It is said that we should judge this situation.
