### ISSUE TITLE
The authtoken app needs to be deprecated and eventually removed

### ISSUE THREAD

**Issue by benwilber** [encode/django-rest-framework#6539]
It has [security issues](https://github.com/encode/django-rest-framework/issues/6537) and [other bugs](https://github.com/encode/django-rest-framework/pull/6439) that nobody seems to want to fix, or aren't able.  I think it needs to be removed from the documentation completely and enter deprecation status.

**Comment by carltongibson** [comment]
Hi. Thanks for the report. It doesn’t seem very constructive. 

Both the issues you liked just need contributions to be be resolved. Looking at them it seems you even offered to provide a patch for the one. Did that ever appear?

We’re not going to remove the TokenAuth app. For whatever faults it may have, it serves a useful role.

**Comment by benwilber** [comment]
What would you think if there was a new app called authtoken2 that fixed the primary key issue.  The new app would be the recommended authtoken app in the docs.  The old one would be deprecated and there would be some migration instructions from the old app to the new one.

This way FKs to the old model keep working, but the new model is the way forward

**Comment by carltongibson** [comment]
We should just be able to migrate the primary key. (No?)

**Comment by tomchristie** [comment]
> We should just be able to migrate the primary key. (No?)

Kinda depends on how large the tables might be for some of our users.

**Comment by tomchristie** [comment]
We could possibly introduce a new key, and have a policy that checks both but writes only to the new one.

**Comment by tomchristie** [comment]
I guess either authtoken2 or migrate are the smartest options. If we could take the migrate route but provide some way for users to not have to adopt it if it’d be problematic, that might also be a thing.

**Comment by rpkilby** [comment]
Also, possibly `rest_framework.contrib.authtoken` as an alternative name?
