### ISSUE TITLE
No different schemas for separate list/post serializers

### ISSUE THREAD

**Issue by tejinderss** [encode/django-rest-framework#6547]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Add different serializers in get_serializer_class for list and create 

## Expected behavior
The generate UI documentation should have different models for different end points 

## Actual behavior
The generated document shows same data model that is one mentioned in serializer_class in the class

**Comment by carltongibson** [comment]
The schema generator calls the view's `get_serializer()` method. Both the `action` and `request` are available for use there. So this **should** work as expected if you're returning different serialisers...

Can you pin down more precisely what's happening?

**Comment by tejinderss** [comment]
Sorry forgot to mention I am using model viewsets

**Comment by carltongibson** [comment]
(Still doesn't tell me anything... sorry!) Are you using different serializers for different actions? If so how/where are you branching? Based on what?

**Comment by tejinderss** [comment]
Sorry I was using serializer_class class variable as well with the get_serializer_class
