### ISSUE TITLE
How to add a custom comment for an ’id‘

### ISSUE THREAD

**Issue by hughxusu** [encode/django-rest-framework#6554]
<img width="628" alt="高检标注系统" src="https://user-images.githubusercontent.com/12914038/55308708-1ec7a380-548e-11e9-9a10-2c16e1b2c333.png">
I want to add a custom description in retrieve api. Where help_text can change it?

Thanks.

**Comment by xordoquy** [comment]
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
