### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by rpkilby** [encode/django-rest-framework#6558]
See https://github.com/encode/django-rest-framework/pull/5886#issuecomment-478789115

Just opening this to make sure we don't lose track of it.

> The docs recommend
>
> "If you want the date field to be visible, but not editable by the user, then set read_only=True and additionally set a default=... argument."
>
> It then says:
>
> "The field will not be writable to the user, but the default value **will still be passed through to the validated_data**."
>
> This is not true. It will **not** be passed through to the validated_data.

**Comment by phankiewicz** [comment]
Seems like @rpkilby already made this change in #6847. Let's close this ticket then.

**Comment by rpkilby** [comment]
Thanks
