### ISSUE TITLE
[Help] KeyError when to get a HiddenField in update method

### ISSUE THREAD

**Issue by wakaryry** [encode/django-rest-framework#6560]
## Steps to reproduce
```Python
class ClubValidateSerializer(serializers.ModelSerializer):
    user = serializers.HiddenField(default=serializers.CurrentUserDefault())

    class Meta:
        model = Club
        fields = ('id', 'validated', 'user')
        read_only_fields = ('id',)

    def update(self, instance, validated_data):
        if instance.validated == validated_data['validated']:
            return instance
        history = ClubValidateHistory(club=instance, validator=validated_data['user'],
                                      from_state=instance.validated, to_state=validated_data['validated'])
        instance.validated = validated_data['validated']
        instance.save()
        history.save()
        return instance
```

## Expected behavior
I want to get the user field in validated_data, but it throws KeyError. It from a patch update.

## Actual behavior
`history = ClubValidateHistory(club=instance, validator=validated_data['user']`,
KeyError: 'user'
"PATCH /backend/clubs/4/validate/ HTTP/1.1" 500 17633

**Comment by tomchristie** [comment]
Hi there & thanks for your question.

The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions.

Thanks! 😀

**Comment by wakaryry** [comment]
I just want to know why I can not get HiddenField in validated_data.
I have used HiddenField in many serializers, but it's the first time I try to reach it in update. But it throws a KeyError. The doc says I can get the HiddenField in validated_data, but there exists none.
@tomchristie Thanks.

**Comment by wakaryry** [comment]
I know the reason it throws KeyError now. The club model do not have a user field, so the user field can not into update/create's validated_data.

**Comment by sshishov** [comment]
It is still unclear why `PATCH` request is not working with `CurrentUserDefault`?
