### ISSUE TITLE
ModelSerializer seems to not serialize Models

### ISSUE THREAD

**Issue by elmcrest** [encode/django-rest-framework#6563]
In case someone reads this right now (22:25 Berlin time) - I will edit thins, just wanted to get a issue ID for a branch

## Checklist

- [ ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [ ] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

**Comment by tomchristie** [comment]
Will consider reopening or not in due course 👍
