### ISSUE TITLE
Add OpenAPI version of SchemaView

### ISSUE THREAD

**Issue by carltongibson** [encode/django-rest-framework#6566]
#6532 is focusing first on the `generateschema` command. This will enable a static schema that will be built using `apistar` for the docs. 

For dynamic schema's (e.g. where model choice fields are used) we need two things: 

* A version (or adjustment) of `SchemaView` that will generate the schema on demand.
    * Instantiate generator. 
    * Call `get_schema()`
    * Render to response. 
* Integration with `apistar`. Is it just a JS endpoint to fetch the schema? Do we also serve the static files? Etc. @tomchristie  to advise on this part as we get nearer.

**Comment by carltongibson** [comment]
@xordoquy This was the `SchemaView` task we talked about.

**Comment by Lucidiot** [comment]
AFAIK, `apistar` does not handle a schema URL: you would have to `requests.get` the schema before passing it to a `Client` instance. Even with something like `Client('http://somewhere')` that would automatically get the schema, I guess it will set the `Accept: application/json, */*` header which will give priority to JSON rendering. Then, the `SchemaView` would work just like any other API endpoint and the rendering would depend on classic JSON/browsable API renderers depending on the project config.

Maybe we could add an `apistar` docs renderer that takes the schema and *somehow* runs the docs generator?

**Comment by carltongibson** [comment]
Looking at `SchemaView` now, if we (cough) _just_ overrode `get_renderers()` to check whether the `generator` was an old CoreAPI generator or a new OpenAPI generator, and adjust accordingly, I think it might more or less just work.

Then yes, we need to work out about actually serving the docs site...

**Comment by carltongibson** [comment]
This is now part of #6532
