### ISSUE TITLE
Permissions checked multiple times per request

### ISSUE THREAD

**Issue by tedtramonte** [encode/django-rest-framework#6571]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Expected behavior
In the browsable API, permissions are checked once per API view, and the allowed method forms are rendered based on that permission check.

## Actual behavior
In the browsable API, permissions are checked multiple times, once for each method form, and the allowed method forms are rendered based on their own permission check.

### My use case
I have implemented a custom permission which checks a third-party API for ownership of my API object. Based on that request, I want to either allow full access or no access. Unfortunately, depending on the page being accessed in my API, the third-party endpoint is being hit 4-6 times in under a second per request and causing me to be rate-limited. The first request succeeds, so the functionality works, but it seems inconsiderate for me to continue with this implementation. Beyond turning off the browsable API, I'm not sure what can be done besides opening a PR to rework this behavior.

It seems a similar discussion occurred on [StackOverflow](https://stackoverflow.com/a/52731612/9730563), which pointed towards DRF and not a mistake on my end.

**Comment by tedtramonte** [comment]
Similarly, `get_queryset()` will also be called twice for the browsable API. I discovered that while attempting to work around the Permissions issue by filtering the ViewSet's queryset. This [StackOverflow](https://stackoverflow.com/questions/41864094/django-rest-framework-view-get-queryset-is-called-twice) question confirms it.

At this point, I'm thinking DRF was designed to behave this way, but I'm not sure why.

**Comment by xordoquy** [comment]
The Browsable API will simulate requests on different actions of the Viewset both to figure out whether or not the user can perform the action and what the serializer looks like. This may lead to duplicated calls to permissions / serializers.
