### ISSUE TITLE
Add full context of serialization errors

### ISSUE THREAD

**Issue by victorct** [encode/django-rest-framework#6574]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Create a simple serializer: 

```
class CreateUserSerializer(serializers.Serializer):
  name = serializers.CharField(max_length=10)
```

Validate with that serializer:

```
 data = {'name': 'something larger than 10'}
 serializer = CreateUserSerializer(data=data)
 serializer.is_valid()
 errors = serializer.errors
 name_error_detail = errors['name'][0]
```

At this point I'am able to do anything with an instance of `ErrorDetail`.

## Expected behavior

When creating an API, a little more of context in the errors could make such a difference. I would expect the representation of an `ErrorDetail` to have this context, for example instead of receiving this as a response

```
{
    "name": [
        {
            "message": "Ensure this field has no more than 10 characters.",
            "code": "max_length"
        }
    ]
}
```

would be awesome if I could receive something like this:
```

{
    "name": [
        {
            "message": "Ensure this field has no more than 10 characters.",
            "code": "max_length",
            "context": {
                 "max_length_allowed": 10
            }
        }
    ]
}
```

**Comment by tomchristie** [comment]
You can build more complex error handlers with https://www.django-rest-framework.org/api-guide/exceptions/#custom-exception-handling - you'd need to dig into how ValidationErrors look.

We're not going to make any large overhauls ourselves in this area, but any third party error handlering packages would be absolutely welcome.

**Comment by victorct** [comment]
I looked at how `ValidationErrors` look, and since the class `ErrorDetails` is the one providing the details on each error, and the only info it has is a message and a code, I think the change has to be made starting from this class, because if anybody does a third party library for this, it would require IMO basically to re-write all of the errors section.

If you need any help with this matter, I would be happy to help you :)

**Comment by tomchristie** [comment]
You'd probably need to map the key back on to the serializer class in order to figure out those extra details, yup.
