### ISSUE TITLE
to_representation omits field if there is an error.

### ISSUE THREAD

**Issue by mehdipourfar** [encode/django-rest-framework#6575]
## Steps to reproduce
```
class Person(models.Model):
    first_name = models.CharField(max_length=100)
   
    @property
    def full_name(self):
         # this will raise error because last_name field does not exist
         return "{}{}".format(self.first_name, self.last_name)

class PersonSerializer(serializers.ModelSerializer):
    class Meta:
         model = Person
         fields = ('first_name', 'full_name')

person = Person.objects.create(first_name='John')
serializer = PersonSerializer(person)
print(serializer.data) # printed result is {'first_name': 'John'}
```
## Expected behavior
Raising exception
## Actual behavior
full_name field is omitted from data silently

**Comment by rpkilby** [comment]
Hi @mehdipourfar - properties are generated as `ReadOnlyField`s, which are `required=False`. This is necessary so that they don't raise an exception during save. For reading however, the missing attribute implies that the field should be skipped (this behavior applies to all non-required fields).

**Comment by mehdipourfar** [comment]
Hi @rpkilby - I think `required` is not a meaningful property when we are talking about _reading_ the data. The example above was very basic but in my project, I had a property which raised error for some of my objects. Therefore, that field was included in serializer for some objects and excluded for some others. And you can imagine how hard it was for me to debug it because there was no errors. If there is an error inside a property that doesn't mean that the developer expects that field to be excluded from serializer.

**Comment by mehdipourfar** [comment]
Consider the case when I create a client app with an static type language and I create a non nullable data field for a property. If the server omits the field from the serializer, the client app will simply crash.

**Comment by rpkilby** [comment]
I don't disagree - it is a confusing behavior and I would prefer that `required` did not affect the serialized output. However, the current implementation is that non-required fields [may be omitted](https://www.django-rest-framework.org/api-guide/fields/#required) during serialization, and I don't know of a trivial way to work around this. 

It's also not as simple as just setting `required=True` on a manually declared `ReadOnlyField`. Not only is there a check in `Field.__init__` that prevents this, setting `required=True` would break write / deserialization (i.e., users would have to supply a value for a read-only field, which is nonsensical). 

You could possible try to monkeypatch [`Field.get_attribute()`](https://github.com/encode/django-rest-framework/blob/29cbe574a384c3bcc09434a3a9c5ff0cb7576b99/rest_framework/fields.py#L447-L474) and remove the required check, or you could override it just for `ReadOnlyField`, although you may want to test to ensure this doesn't affect create/update behavior when deserializing.

**Comment by mehdipourfar** [comment]
What if we just move `field.get_attribute(instance)` out of try except block in [Serializer.to_representation](https://github.com/encode/django-rest-framework/blob/29cbe574a384c3bcc09434a3a9c5ff0cb7576b99/rest_framework/serializers.py#L508-L519) function?

**Comment by xordoquy** [comment]
I'm closing this because there isn't much we can do here.
The issue here is that you are using a property which raises a too generic exception that DRF also need in its code. Would `full_name` be a function, the outcome would be different:

```python
>>> class Person:
...   def __init__(self, first_name):
...     self.first_name = first_name
...   @property
...   def full_name(self):
...     return "{}{}".format(self.first_name, self.last_name)
...   def fname(self):
...     return "{}{}".format(self.first_name, self.last_name)
... 
>>> p = Person('abc')
>>> p.fname()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "<console>", line 8, in fname
AttributeError: 'Person' object has no attribute 'last_name'
>>> p.full_name
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "<console>", line 6, in full_name
AttributeError: 'Person' object has no attribute 'last_name'
>>> from rest_framework import serializers
>>> class PersonSerializer(serializers.Serializer):
...   first_name = serializers.CharField()
...   fname = serializers.CharField(required=False, read_only=True)
... 
>>> s = PersonSerializer(p)
>>> s.data
Traceback (most recent call last):
  File "/Users/xordoquy/.local/share/virtualenvs/invoices/lib/python3.7/site-packages/rest_framework/fields.py", line 106, in get_attribute
    instance = instance()
  File "<console>", line 8, in fname
AttributeError: 'Person' object has no attribute 'last_name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/xordoquy/.local/share/virtualenvs/invoices/lib/python3.7/site-packages/rest_framework/serializers.py", line 563, in data
    ret = super(Serializer, self).data
  File "/Users/xordoquy/.local/share/virtualenvs/invoices/lib/python3.7/site-packages/rest_framework/serializers.py", line 262, in data
    self._data = self.to_representation(self.instance)
  File "/Users/xordoquy/.local/share/virtualenvs/invoices/lib/python3.7/site-packages/rest_framework/serializers.py", line 517, in to_representation
    attribute = field.get_attribute(instance)
  File "/Users/xordoquy/.local/share/virtualenvs/invoices/lib/python3.7/site-packages/rest_framework/fields.py", line 453, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "/Users/xordoquy/.local/share/virtualenvs/invoices/lib/python3.7/site-packages/rest_framework/fields.py", line 111, in get_attribute
    raise ValueError('Exception raised in callable attribute "{0}"; original exception was: {1}'.format(attr, exc))
ValueError: Exception raised in callable attribute "fname"; original exception was: 'Person' object has no attribute 'last_name'
>>> class PersonSerializer(serializers.Serializer):
...   first_name = serializers.CharField()
...   full_name = serializers.CharField(required=False, read_only=True)
... 
>>> s = PersonSerializer(p)
>>> s.data
{'first_name': 'abc'}
>>> 
```

**Comment by xordoquy** [comment]
> What if we just move field.get_attribute(instance) out of try except block in Serializer.to_representation function?

That would create a quite important backward incompatibility. [Documentation](https://www.django-rest-framework.org/api-guide/fields/#required) states:

> If the key is not present it will simply not be included in the output representation.

**Comment by mehdipourfar** [comment]
This paragraph in docs is also confusing because it says the default value for `required` is `True` but in case of `readonly_fields` it's `False`.
And by the way, it is not best design choice for a Restful API to omit some fields some times in some endpoints. If a developer is currently using this feature (setting `required=False` to omit non-existing or error-prone field from serialized data) he is actually hacking.

**Comment by xordoquy** [comment]
> This paragraph in docs is also confusing because it says the default value for required is True but in case of readonly_fields it's False

Indeed, documentation could explicitly state the `ReadOnlyField`'s `required` value is False

> it is not best design choice for a Restful API to omit some fields some times in some endpoints.

As far as I can understand it, the current design is aligned with the OpenAPI specifications for `readOnly`:

> Declares the property as "read only". This means that it MAY be sent as part of a response but SHOULD NOT be sent as part of the request. If the property is marked as readOnly being true and is in the required list, the required will take effect on the response only.

It doesn't say the field MUST be part of the response.

**Comment by mehdipourfar** [comment]
Okay. I accept that it could be not sent but still I insist that this design could lead to some errors that are very hard to debug.

**Comment by jakedouglas** [comment]
I also found it very surprising that DRF was suppressing exceptions.
