### ISSUE TITLE
DjangoGuardianObjectPermissionsFilter Broken on django 1.11 with python 2.7

### ISSUE THREAD

**Issue by jsharpe** [encode/django-rest-framework#6577]
This line unconditionally disables django-guardian from being detected with python 2.7 but it should still work with older releases that don't meet the conditions in the comments:
https://github.com/encode/django-rest-framework/blob/29cbe574a384c3bcc09434a3a9c5ff0cb7576b99/rest_framework/compat.py#L172

**Comment by xordoquy** [comment]
We don't test against older Django-guardian versions so there might be other incompatibilities.
If you are confident enough, I'd suggest you override `DjangoObjectPermissionsFilter.__init__()` to skip the installation check (or perform your own).

**Comment by jsharpe** [comment]
Can I suggest that you add a warning into the code in the python2 path as currently the code returns a rather confusing error message that guardian is not installed. You have to dig into the code to find out the information about the incompatibility

**Comment by xordoquy** [comment]
@carltongibson do you think we'll have releases before merging Python 2.7 removal PR ?

**Comment by carltongibson** [comment]
Yeah. good. I had basically thought no. But it might be worth throwing this in quick... Thoughts?

**Comment by rpkilby** [comment]
Almost everything merged since 3.9.2 has either been a docs fix or a minor code cleanup. We could release 3.9.3 if it's not too much trouble. 

Maybe change the check to:

```python
if six.PY2 and guardian.VERSION >= (1, 5):
    return False
```

From #6054, there were issues importing `guardian`, but since this is a runtime check, it might be fine?

**Comment by carltongibson** [comment]
OK. Let’s reopen to assess. I’ve been putting off dropping Python 2, so we may as well look at taking advantage of that. 

Happy to look at a PR adjusting the compat code here. I don’t mind doing the release.

**Comment by xordoquy** [comment]
It might be more like:

    if six.PY2 and django.version >= (2, 2) and guardian.VERSION >= (1, 5):
