### ISSUE TITLE
No Portuguese fallback available

### ISSUE THREAD

**Issue by nawarnoori** [encode/django-rest-framework#6582]
## Checklist

- [X] I have verified that that issue exists against the `master` branch of Django REST framework.
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [X] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [X] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Send a request with `Accept-Language: pt` or `pt-pt` that will trigger a translated DRF message, say, about incorrect date format.

E.g if you have the following setup:

```python
class DateOfBirthSerializer(serializers.Serializer):
    date_of_birth = fields.DateField()

class ValidateViewSet(viewsets.ViewSet):
    @action(methods=('post',), detail=False)
    def date_of_birth(self, request):
        DateOfBirthSerializer(data=request.data).is_valid(raise_exception=True)
        return Response({})

router = SimpleRouter()
router.register('validate', ValidateViewSet, 'validate')
```
And then you send the following request:

```bash
curl --request POST \
  --url http://api.com/validate/date_of_birth
  --header 'accept-language: pt' \
  --header 'content-type: application/json' \
  --data '{"date_of_birth": "20000-01-01"}'
```

## Expected behavior
As only Brazilian Portuguese is available, `pt` should fall back to it and it should return:
```json
{
  "date_of_birth": [
    "Formato inválido para data. Use um dos formatos a seguir: YYYY-MM-DD."
  ]

```

## Actual behavior
`pt` doesn't fallback to any version of Portuguese and so falls back to English:
```python
{
  "date_of_birth": [
    "Date has wrong format. Use one of these formats instead: YYYY-MM-DD."
  ]
}
```

I know this is essentially regulated by the locale middleware, but what I propose is that we duplicate the "Portuguese (Brazil)" translation for just "Portuguese" and leave "Portuguese (Portugal)" alone. That way there is some form of Portuguese available for the `pt` accept language header.

**Comment by tomchristie** [comment]
> I know this is essentially regulated by the locale middleware, but what I propose is that we duplicate the "Portuguese (Brazil)" translation for just "Portuguese" and leave "Portuguese (Portugal)" alone. 

Seems reasonable.

**Comment by rpkilby** [comment]
Is this something that needs to be managed via transifex or our release process, or is there an issue here within DRF's codebase?

**Comment by tomchristie** [comment]
@rpkilby - Needs to be dealt with through Transifex really.

**Comment by tomchristie** [comment]
Have duplicated "pt-br" into "pt" - should get picked up in the upcoming 3.10 release.
If there's still any issues after this can look into again (and duplicate to pt-pt if needed)
