### ISSUE TITLE
Use lists for Serializer.fields examples, not tuples

### ISSUE THREAD

**Issue by spookylukey** [encode/django-rest-framework#6604]
It would be great if the documentation for `Serializer.fields` (and any similar attributes) could show lists, not tuples.

Lists do have significant advantages:

1. They are the data structure designed for arbitrary length sequences, tuples are not. This is the way the language is designed. ([Says Guido](https://marc.info/?l=python-dev&m=107666578526990&w=2)).
2. Writing a one-tuple is ugly and error prone (not surprising, since conceptually it doesn't make any sense, you don't need a data structure to hold a single piece of data).

In most cases it really doesn't make much difference, but the effect of using tuples in one place is that they naturally spread, and that's the real problem.

The project I've recently joined, which is a heavy user of django-rest-framework and not much else, has code like this:

```python
    class FooSerializer(ModelSerializer):
        class Meta:
            fields = ('foo', 'bar')

    class DetailedFooSerializer(FooSerializer):
        class Meta:
            fields = FooSerializer.Meta.fields + ('baz', )
```

A tuple in the first instance pushes you to carry on using tuples in the second instance, because `[] + ()` raises `TypeError`.

The result, eventually, is code like this:

```python
    fields = ()
    if condition:
        fields += ('foo',)
    if other_condition:
        fields += ('bar', 'baz')     
```

And worse:

```python
    stuff = ()
    for thing in all_the_things:
        stuff += (thing.attribute,)
        stuff += tuple([foo.attribute for foo in other_things])
```

I'm not kidding, I have code like this, quite a lot of it. It's like "What a shame! If only this language had a data structure that was designed for arbitrary length sequences and that allowed you to add to that sequence in [amortized O(1) time](https://wiki.python.org/moin/TimeComplexity) instead of having to rebuild data structures in a loop, resulting in quadratic performance!"

I even have developers insisting "for consistency" that any constant sequences (like `Serializer.fields` or module level constants) must be tuples. And indeed consistency as an argument does have some merit, the problem is being consistent with the wrong pattern.

This code wasn't even written by novices either, it was written very recently by really good developers, some of whose names' you'll know (assuming the 'you' who is reading this ticket is Tom Christie). They are definitely aware of the list data structure. The only way I can explain this is by a habit of using tuples, and consistency/compatibility with code that uses tuples. It appears typing `()` to represent an empty list has become a habit, and then they proceed to fight the language at every step. Tuples were just not designed for this.

Of course, there are other ways to avoid the performance issues of using tuples like this, but it's about "falling into the pit of success", which is even more important for projects that have weaker developers.

Interestingly, by contrast, the `permission_classes` attributes on all our `View` classes are lists, despite our apparent tuples policy. Look at the DRF docs and you'll find the explanation - example code and documentation exerts a very strong influence. I suspect that the DRF's `Meta.fields` attribute being a tuple is itself traced back to the way that Django documented things like `ModelAdmin.fields` ([some of this has now been corrected to lists](https://docs.djangoproject.com/en/2.2/intro/tutorial07/) but not all).

I would like to eradicate the tuple pestilence infecting our code base, and it would really help my case if the docs for DRF showed best practice. I'm happy to submit a patch if this ticket is accepted.

**Comment by rpkilby** [comment]
I feel guilty saying this... On the one hand, I always appreciate a thoroughly written argument. On the other hand, I'm not going to spend the time reading it 😄(in part, because I already agree with you).

but for context, iirc the use of tuples over lists originates from Django's docs. However, the Django docs have since migrated to use lists over tuples (circa v1.4 - v1.6?), and we should follow suit. I would be +1 on a PR that updates our docs to use lists instead of tuples.

**Comment by rpkilby** [comment]
Also, I think this should apply generally (settings, `View` attributes, etc... - not just `Meta.fields`)

**Comment by tomchristie** [comment]
> However, the Django docs have since migrated to use lists over tuples (circa v1.4 - v1.6?), and we should follow suit.

Agreed. Would accept any pull request that switched the style over. 👍

**Comment by LondonAppDev** [comment]
I understand the switch to `list` for things like serializer fields as they may change dynamically as @spookylukey demonstrates in the examples above.

However, for `authentication_classes` and `permission_classes` wouldn't `tuple` be preferred because they wouldn't be changed for the request? Is the reason they were _all_ changed to lists for consistency, or am I misunderstanding something?

PS. Apologies for commenting on this old post... thought it might be the best place for clarification so I can also help propagate best practices and "eradicate the tuple pestilence infecting our code base" :)

**Comment by spookylukey** [comment]
@LondonAppDev The argument here (whether you accept it or not), is that tuples are not merely immutable lists, they are datastructures where each position has a different meaning. 

Apologies if you are already aware of this, but in case it is helpful I may as well develop the point. For example, you might use a tuple like this:
```python
person_details = ("Jon Smith", "jonsmith@example.com")
```
Each position has a different meaning. This is how tuples work in other languages, and it's how Guido intended them to be used in Python. 

So usually it is a mistake to have tuples that are sequences of arbitrary length.

(Aside: there are cases where it is necessary, particular where you have a sequence of things which from one perspective is position dependent, and from another perspective is arbitrary length. For example, this function:
```python
def format_name_and_email_address(name, email):
    return f'{name} <{email}>'
```
Here `name` and `email` are a sequence of position arguments with different meaning for the different positions. However, if I write a generic decorator function:
```python
def log_args(func):
    def wrapper(*args):
        logging.log(f'{func.__name__} called with args: {', '.join(repr(arg) for arg in args)}')
        return func(*args)
    return wrapper

```
Here, if we use `@log_args` on `format_name_and_email_address`, those same two positional arguments are processed by the wrapper in `log_args` as an arbitrary length tuple where every argument has the same "meaning" ie. "this is an argument". That's because `log_args` is intended to be generic, so has to work with tuples of arbitrary length.

End aside.)

That would be the primary reason for making `permission_classes` etc. lists - each position in the sequence has the same meaning, so list is the appropriate structure.

The examples I added above are additional arguments about what happens if you think of tuples just as sequences that are "fixed lists" - the tuples end up getting everywhere (due to incompatibilities with lists that causes you to prefer one or the other, and due to habits), even when they are an extremely bad choice of datastructure.

**Comment by LondonAppDev** [comment]
@spookylukey fantastic, thanks for such an excellent and well written response. I was missing the part about tuples being used for positionally dependent items, now I understand that piece, it makes perfect sense. 

Lists it is!
