### ISSUE TITLE
Tight coupling of user.has_perm() to view queryset.

### ISSUE THREAD

**Issue by Dmitri-Sintsov** [encode/django-rest-framework#6606]
`permissions.DjangoModelPermissions` artificially ties Django `user.has_perm()` to view queryset's model.

Django user permissions and querysets should be completely decoupled, because large apps may have different "change" permissions. It's much better just to specify permissions via their `'app_label.codename'` rather than hardcoding these as `'%(app_label)s.add_%(model_name)s'`.

Current approach causes tight coupling in `get_required_permissions(self, method, model_cls)` which requires mandatory `model_cls` to be specified. Large apps may provide custom permissions which does not fit into suggested `'%(app_label)s.add_%(model_name)s'` scheme.

Yes it's possible to override `perms_map`, however still `model_cls` argument of `get_required_permissions()` should be optional one and do not require queryset to be specified.

Django user permissions are not for the querysets only!

**Comment by Dmitri-Sintsov** [comment]
Also `GET` method misses default `'%(app_label)s.view_%(model_name)s'` perm string.

**Comment by tomchristie** [comment]
We welcome alternative third party implementations, which we can then promote from the documentation. If someone comes up with an alternative that’s clearly an improvement on the current DjangoModelPermissions, then we could consider adopting it.

**Comment by rpkilby** [comment]
Hi @Dmitri-Sintsov, just to clarify, there are two related concepts here.

- Django has a generic user permissions system (`user.has_perm()`).
- Django's `auth` app implements a set of default permissions for each model. 

You are expecting `DjangoModelPermissions` to check generic `<app label>.<permission codename>` permissions. However, `DjangoModelPermissions` is checking the default model permissions. The coupling of the view's model to the permissions check is its designed purpose.

That said, it might be useful to have a more generic `DjangoUserPermissions` class that allows users to specify the codenames on the viewset itself.

**Comment by Dmitri-Sintsov** [comment]
@rpkilby `DjangoModelPermissions` does not pass the instances of models to check, it only checks Django content types permissions.

I run large Django project which uses Django auth backend and no DRF, with many custom permissions. These can be defined in Django models this way:

https://docs.djangoproject.com/en/dev/topics/auth/customizing/#custom-permissions

```
class Task(models.Model):
    ...
    class Meta:
        permissions = [
            ("change_task_status", "Can change the status of tasks"),
            ("close_task", "Can remove a task by setting its status as closed"),
        ]

```

which do not fit the suggested '%(app_label)s.%(action)_%(model_name)s' schema.

When developing custom auth backend for DRF based project, I received complains that auth backend does not match / fit their code well. When looking at DRF code, I see why.

**Comment by xordoquy** [comment]
> which do not fit the suggested '%(app_label)s.%(action)_%(model_name)s' schema.

Sure thing. If you want to work around those default permissions, documentation says:

> To use custom model permissions, override DjangoModelPermissions and set the .perms_map property. Refer to the source code for details.


> `DjangoModelPermissions` does not pass the instances of models to check, it only checks Django content types permissions.

Which is the `DjangoModelPermissions`' goal. Feels like you should be using [`DjangoObjectPermissions`](https://www.django-rest-framework.org/api-guide/permissions/#djangoobjectpermissions) instead.

**Comment by rpkilby** [comment]
> I run large Django project which uses Django auth backend and no DRF, with many custom permissions. 

I understand that you can have custom permissions that do not conform to the given format. What I'm saying is that the  `DjangoModelPermissions` works similar to the Django admin, in that it [leverages the default set of permissions](https://docs.djangoproject.com/en/2.2/topics/auth/default/#permissions-and-authorization). The Django admin does not automatically adapt to your custom permissions. Similarly, `DjangoModelPermissions` is designed to work with the default permissions, not custom permissions. The coupling is intentional.

I think the best course of action is to create an entirely new permissions class that looks at the view for its perm map.
