### ISSUE TITLE
PrimaryKeyRelatedField converts ids to model instances

### ISSUE THREAD

**Issue by x-yuri** [encode/django-rest-framework#6607]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

```py
class ChildSerializer(serializers.ModelSerializer):
    parent_id = PrimaryKeyRelatedField(queryset=models.Parent.objects.all())
    class Meta:
        model = models.Child
        fields = ('id', 'parent_id')
        read_only_fields = ('id',)
```

## Expected behavior

It works (I'm able to create a database record).

## Actual behavior

> TypeError: int() argument must be a string, a bytes-like object or a number, not 'ModelTwo'

And AFAICS, I'm not the [first][1] who doesn't expect it to convert id to model instance. Can you explain your reasoning? Doesn't it make sense to incorporate the fix from the other issue?

[1]: https://github.com/encode/django-rest-framework/issues/6599

**Comment by tomchristie** [comment]
Serialisers validate *data* coming in, or serialise to *data* going out.
The external representation will always be a plain data structure.

**Comment by tomchristie** [comment]
For further questions on this I’d suggest the discussion group.

**Comment by xordoquy** [comment]
I also suggest to provide a minimal working test case that demonstrate the issue so we can analyse it.
The provided code is a good start but we don't have the associated models nor the traceback. Even though we're have, it's likely we wouldn't have the time to copy/paste, setup a new project for it and test it.
However, it'll be more likely if we'd have a PR with an additional test case that travis can run and that demonstrate the issue you are facing.

**Comment by x-yuri** [comment]
Okay, from what I can see `PrimaryKeyRelatedField` is not supposed to be used that way. The expected usage is probably:

```py
class ChildSerializer(serializers.ModelSerializer):
    parent = PrimaryKeyRelatedField(queryset=models.Parent.objects.all())
    class Meta:
        model = models.Child
        fields = ('id', 'parent')
        read_only_fields = ('id',)
```

Or else `PrimaryKeyRelatedField` returns a model that gets assigned to `parent_id` field, and as such fails.

**Comment by MuSayyaf88** [comment]
I faced the same issue, to get "id" instead of "object" you have to change:
`parent_id = PrimaryKeyRelatedField(queryset=models.Parent.objects.all())`
To:
`parent_id = PrimaryKeyRelatedField(queryset=models.Parent.objects.all().values_list('id', flat=True))`
