### ISSUE TITLE
http_method_names don't work in browser

### ISSUE THREAD

**Issue by Hau-Hau** [encode/django-rest-framework#6610]
## Checklist

- [ ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [X] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [X] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
```python
class View(generics.CreateAPIView,
           generics.DestroyAPIView,
           generics.GenericAPIView):
    http_method_names = ('post', 'delete')

    def create(self, request, *args, **kwargs):
        return Response(status=status.HTTP_200_OK)

    def delete(self, request, *args, **kwargs):
        return Response(status=status.HTTP_200_OK)
```

## Expected behavior
Allow only POST and DELETE HTTP methods in all environments.

## Actual behavior
In Postman it is impossible to make GET request (I got 405), but request from Firefox and Chrome is passed as allowed method. 

I also found that after small change in _allowed_methods method everything works as i expect:
```python
class View(generics.CreateAPIView,
           generics.DestroyAPIView,
           generics.GenericAPIView):
    http_method_names = ('post', 'delete')

    def _allowed_methods(self):
       #removed .upper() from 'm.upper()'
        return [m for m in self.http_method_names if hasattr(self, m)]

    def create(self, request, *args, **kwargs):
        return Response(status=status.HTTP_200_OK)

    def delete(self, request, *args, **kwargs):
        return Response(status=status.HTTP_200_OK)
```

I know that I can block methods with permissions etc. But this behaviour is not clear for me at all and looks like a bug

**Comment by xordoquy** [comment]
I'm not convinced it's an issue with DRF.
[`http_method_names`](https://docs.djangoproject.com/en/2.2/ref/class-based-views/base/#django.views.generic.base.View.http_method_names) is a Django thing so if it's not working well, either it's an issue within Django itself - which seems unlikely - or it might have a misconfiguration somewhere on the stack you are using.

**Comment by dedolence** [comment]
I am also seeing `http_method_names` not applying when I override it in a CBV. I've set it to an empty list and tried a single method, and in both cases any request method is still allowed through in the browser.
