### ISSUE TITLE
get_error_detail should not format without error.params

### ISSUE THREAD

**Issue by WolfgangFellger** [encode/django-rest-framework#6622]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [x] ~~I~~ @michael-k has included a failing test as a pull request. (Thanks!)

get_error_detail should not attempt to format the message in DjangoValidationErrors if params aren't used. This is also in line with how [Django behaves](https://github.com/django/django/blob/b9cf764be62e77b4777b3a75ec256f6209a57671/django/core/exceptions.py#L168-L169).

If f-strings are used to generate the error message, this means duplicate formatting, and fails if a `%` occurs in the message.

## Steps to reproduce

Most basic example I could muster (this is actually supposed to be ModelValidator with the validator on a Django model)

```python
from rest_framework import serializers
from django.core.exceptions import ValidationError


def validate(value):
    raise ValidationError(f'{value} is invalid')

class MySerializer(serializers.Serializer):
    field = serializers.CharField(validators=[validate])


s = MySerializer(data={'field': 'f%'})  
if not s.is_valid():  # throws TypeError: not enough arguments for format string
    print(s.errors)
```

## Expected behavior
Should return the error message "f% is not valid"

## Actual behavior
Throws a TypeError in https://github.com/encode/django-rest-framework/blob/1a0a8dde00187994bd4206e9d74219f148afc1c6/rest_framework/fields.py#L242

**Comment by michael-k** [comment]
FYI: I'm working on a PR to solve this.  Including a failing test.
