### ISSUE TITLE
Unable to set an empty string for url_path @action parameter

### ISSUE THREAD

**Issue by jordanambra** [encode/django-rest-framework#6645]
## Checklist

- [X] I have verified that that issue exists against the `master` branch of Django REST framework.
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [X] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

1. Create a View or ViewSet with a custom @action decorator
2. Set the url_path parameter = ""

Example case attempting to implement bulk delete

```
@action(methods=['delete'], detail=False, url_path="")
def bulk_destroy(self, request, *args, **kwargs):
    pass
```

## Expected behavior
Set the url_path suffix EXACTLY to an empty string.

## Actual behavior
Because url_path is a falsy value, it is overridden by the name of the function, in the example case it is "../../bulk_destroy"

I understand this is not necessarily broken, but it is frustrating to be unable to explicitly declare an empty url_path.

The action decorator in decorators.py could be updated to the following code:

```
func.url_path = url_path if url_path is not None else func.__name__
```

**Comment by xordoquy** [comment]
I'm disagree empty `url_path` should be allowed.
I'm afraid this will lead to hard to debug issues even for advanced users - let alone that it will mess with the routers.
If you want to enable a DELETE operation on a list, you should alter the [default router's routes](https://www.django-rest-framework.org/api-guide/routers/#example) so it routes to your `bulk_destroy`

**Comment by frnhr** [comment]
I ran into this exact issue today, while trying to add support for PATCH on the list view.

The idea of `@action` decorator is, AFAICS, to remove the need for custom rounters. It seems like this should just work and DRF is fighting itself here... Is the distinction between `Route` and `DynamicRoute` needed? If `list` was a `DynamicRoute` by default, we could do `@list.mapper.patch` (or `.delete`).

**Comment by frnhr** [comment]
I ran into this exact issue today, while trying to add support for PATCH on the list view.

The idea of `@action` decorator is, AFAICS, to remove the need for custom routers. It seems like this should just work and DRF is fighting itself here... Is the distinction between `Route` and `DynamicRoute` needed? If `list` was a `DynamicRoute` by default, we could do `@list.mapper.patch` (or `.delete`).

**Comment by rpkilby** [comment]
Hi @frnhr. 

> The idea of `@action` decorator is, AFAICS, to remove the need for custom routers. 

Extra actions aren't a replacement for custom routers. They're more a complement that allow you to define ad hoc functionality that doesn't fit within the standard CRUD model. e.g., a user resource with a set/unset password feature. Custom routers still have their purpose (e.g., singleton routes, nested routing). 

> If `list` was a `DynamicRoute` by default, we could do `@list.mapper.patch` (or `.delete`).

This works in some cases, but leads to others that are nonsensical. e.g., if a viewset defines `partial_update`, but also wraps a `@retrieve.mapper.patch`. Which of these should win? There are additional complications when you add inheritance to the mix. 

I think the real answer is that we need better support/guidance for singleton and other non-standard route structures. "Use a custom router" isn't really sufficient.

**Comment by frnhr** [comment]
Hi @rpkilby, thanks for the reply!

I agree there is a place for custom routers. But I'm still left with the feeling that the two functionalities overlap quite a bit. "There should be one-- and preferably only one --obvious way to do it." In the ideal world.

That said, having this little issue and two ways to go about it is miles better then not having them at all, so thank you and the gang for DRF, the hard at work and all that jazz. Goes without saying...

In my case, I ended up hacking a new mapping to the router in `urls.py` like so:

``` python
router.routes[0].mapping['patch'] = 'list_update'
```

Feels very doggy, but is also very short and seems to work perfectly, so... ¯\\\_(ツ)_/¯
