### ISSUE TITLE
Allow optional use of field labels

### ISSUE THREAD

**Issue by omkar-dsd** [encode/django-rest-framework#6648]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Expected behavior
Allow labels to be specified optionally which is already a property of field. If user wants to return the field labels in place of field name, he/she should be able to configure so by setting it up in the `extra_kwargs`

## Actual behavior
Currently, there is no such option to provide label in `to_representation`

**Comment by rpkilby** [comment]
Closing, per #6649
