### ISSUE TITLE
Code in the documentation is sometimes of the wrong span class (`pun` rather than `pln`)

### ISSUE THREAD

**Issue by meli-lewis** [encode/django-rest-framework#6657]
I see that people missing the trailing `.` in the quickstart documentation has already arisen: https://github.com/encode/django-rest-framework/commit/1ba822010d0943c67c127f3f62e873b64348ef87#diff-306f5e40924dc731960189d645f34641, but I think the problem could also be css-related!

I noticed that the trailing dot appears to have the same hex value as comments and confirmed in developer tools that this is the case (they're both #93a1a1) and believe this is because that single character is wrapped in the wrong span class (`pun` rather than `pln`).

Frontend is not my strong suit, so while I'd like to fix this small matter without bothering y'all, I couldn't parse why it's happening. My guess after a cursory review of this [prettify script](https://github.com/encode/django-rest-framework/blob/master/docs_theme/js/prettify-1.0.js) is that you're typically assigning styles to punctuation programmatically, but that this is an edge case.

I hope I didn't miss this already being an issue! I searched all open issues for the associated hex code, "pun" and "punctuation," but did not find one.

**Comment by tomchristie** [comment]
Thanks for raising this!

Any particular page when you think this ends up displaying problematically?

I can see on the quickstart that the code parsing ends up being a bit patchy in places...

![Screenshot 2019-05-21 at 11 26 09](https://user-images.githubusercontent.com/647359/58088794-519f3580-7bbb-11e9-85fc-b23b9411d524.png)

With the punctuation getting different styling in a few places.

There's not a lot that we can easily do about that, and it *does* still display, it's just not a great style. Given our constraints I'm going to close this off as "not much to be done about it".
