### ISSUE TITLE
Include "default" value on fields

### ISSUE THREAD

**Issue by AlexisCaffa** [encode/django-rest-framework#6664]
Similar to https://github.com/encode/django-rest-framework/issues/467.

`default` is a attribute on model classes, which can be used for generating nice forms with preset values.
`rest_framework.fields.Field` and `ModelSerializer` should support it.

### An idea to implement it
Add the condition in [get_field_kwargs](https://github.com/encode/django-rest-framework/blob/master/rest_framework/utils/field_mapping.py#L80) like:
``` python
if model_field.default:
    kwargs['default'] = model_field.default
```

Then in the [SimpleMetadata](https://github.com/encode/django-rest-framework/blob/master/rest_framework/metadata.py#L124) add the `default` attr into the list of attrs:
``` python
attrs = [
    'read_only', 'label', 'help_text',
    'min_length', 'max_length',
    'min_value', 'max_value', 'default'
]
```

**Comment by tomchristie** [comment]
A model default affects if a serializer field is *required or not*, rather than implying a default on the serializer field itself.
