### ISSUE TITLE
Make throttling classes add action to history even on throttling failures

### ISSUE THREAD

**Issue by diox** [encode/django-rest-framework#6666]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce / Description of the issue
With DRF throttling classes current implementation, [an action gets added to the history only on success](https://github.com/encode/django-rest-framework/blob/9811a29a5a1348f1a5de30a9a7a5d0f8d2fd4843/rest_framework/throttling.py#L130-L141). This means that additional attempts that result in a 429 response aren't considered in throttling checks later. My suggestion is to consider those as well, punishing brute-forcing and rewarding clients that wait the recommended wait period.

Given the following throttling class:
```python
 class TestThrottle(AnonRateThrottle):
    rate = '3/min'
```

Example scenario of a client hitting an API protected with this class - number in parenthesis is the number of actions the throttling class has left in its history when deciding whether or not to throttle.

| Seconds | Current behavior | Proposed behavior  |
| --------| ---------------- | ------------------ |
| 0       | Pass (0)         | Pass (0)           |
| 5       | Pass (1)         | Pass (1)           |
| 10      | Pass (2)         | Pass (2)           |
| 15      | Throttled (3)    | Throttled (3)      |
| 62      | Pass (2)         | Throttled (3)      |
| 66      | Pass (2)         | Throttled (3)      |
| 76      | Pass (2)         | Pass (2)           |

This is a somewhat backwards-incompatible change, in the sense that the behavior would be different and the cache contents would differ as well, but unless someone relies on it for purposes other than throttling I don't think it should be much of a problem.

It could be done as a third-party library, but I believe it's better to have this change in DRF itself to make throttling more efficient against brute-force attacks. I haven't written the pull request yet, but it's relatively trivial and I'd be willing to do it, I just want to validate the idea first.

**Comment by nepbuhtuh0986** [comment]
Thanks

**Comment by tomchristie** [comment]
Looking at it again, and I *do* have mixed feelings on the behavioral change.

It's very unforgiving - Clients that are attempting actions at *slightly* over the throttle rate can end up being perputually throttled.

No absolute decision here but wanted to raise my thoughts there.

(The related issue "add history to all throttling classes" seems far more clear-cut to me tho.)

**Comment by diox** [comment]
It is more aggressive yes. It's clearly meant to punish bad behavior more, to deal with clients ignoring 429 responses, brute-forcing until they get past the throttle duration. I believe this is still fair, but I'm biased of course :smile:

**Comment by xordoquy** [comment]
Could we set a flag to trigger that new behavior ?

**Comment by tomchristie** [comment]
Righty - thanks for taking the time to talk all this through.

> Could we set a flag to trigger that new behavior?

I'd rather we take a decision on behalf of our users.

I'm inclined to agree with this comment https://github.com/mozilla/addons-server/issues/11393#issuecomment-491503779

> Isn't that by design though? - if you try on 19:59 of a 20 minute throttle you have to wait another 20 minutes? I could imagine that being very annoying. Especially when you don't find out there is a throttle until you hit it the first time.

On balance I'd like to leave our behaviour as-is. I think it's clear, and the behavior in the first column would be more obvious to me as a user than then second.

**Comment by diox** [comment]
I'd like to point out that the comment you're referring to was wrong. If you try on 19:59 of a 20 minute throttle, you don't have to wait for another 20 minutes with my change. As I noted in my reply you only need to wait for the first actions in that window to expire.

Nevertheless, I understand that you don't want to have this in DRF itself. We'll implement it in our own classes then.

**Comment by rpkilby** [comment]
> I'd like to point out that the comment you're referring to was wrong. 

@tomchristie - given this, is it worth having a second look? https://github.com/mozilla/addons-server/issues/11393#issuecomment-491510198

Temporarily reopening to make sure this doesn't get lost (comments on closed issues have a tendency to be forgotten).

**Comment by tomchristie** [comment]
> given this, is it worth having a second look

@rpkilby Thanks, yes I'd read that and I'm still happy with our existing approach here. 😌

The throttling classes limits how many successful requests may be made per period - that's perfectly reasonable.

Having a stricter style where throttled requests beyond that *also* apply to the limit and *reduce* the number of successful requests that can be made is a little more obscure behavior as I see it.

It's also worth noting that *application-level* throttling can be a mediation against DDOS attacks, but it really shouldn't ever be the first line - the only appropriate level for that will be at the gateway server / CDN frontend. Application-level throttling should generally be considered to be appropriate for handling business-level restrictions on appropriate per-user usage levels.
