### ISSUE TITLE
PageNumberPagination

### ISSUE THREAD

**Issue by psv-git** [encode/django-rest-framework#6679]
Im using PageNumberPagination in my project now.

## 1) Pagination class use "url" instead of "path".

[Django docs say "url" will be deprecated soon.](https://docs.djangoproject.com/en/2.2/ref/urls/)

"url" pass GET arguments to "request.query_params", but "path" pass it to "**kwargs" 

```python
class PageNumberPagination(BasePagination):
    def paginate_queryset(self, queryset, request, view=None):
        ....  
        page_number = request.query_params.get(self.page_query_param, 1)  
        ....  
```
This line ignoring request params in "**kwargs", so urls like

> path("get/objects/from-page/\<int:page\>", ObjectViewSet.as_view({"get": "list"}))

will not be paginated.

I found solution for my case:

```python
class ObjectViewSet(GenericViewSet):
    def list(self, request, *args, **kwargs):
        ....  
        page_number = kwargs.get("page", None)  
        self.request.query_params._mutable = True  
        self.request.query_params.update({"page": page_number})  
        self.request.query_params._mutable = False  
        page = self.paginate_queryset(queryset)
        if page is not None:
            serializer = self.get_serializer(page, many=True)
            return self.get_paginated_response(serializer.data)
        ....
```

But i think its really not good. Is this a bug? Can you change this behavior?

**Comment by rpkilby** [comment]
Hi @psv-git. The usage you've shown is incorrect. 

```python
path("get/objects/from-page/<int:page>", ObjectViewSet.as_view({"get": "list"}))
```
In the above, your `page` param is part of the URL path, not the query string. e.g., it would match

```
/get/objects/from-page/20
```

Pagination expects the `page` param to be passed as part of the URL querystring. e.g., 

```
/get/objects?page=20
```

The corresponding route would be something like:
```python
path("get/objects, ObjectViewSet.as_view({"get": "list"}))
```

**Comment by psv-git** [comment]
Thanks for response. That was my fault. Django documentation is not intuitive, so I thought this way not used now.
