### ISSUE TITLE
Documentation really slow because of broken fund subdomain

### ISSUE THREAD

**Issue by WoLpH** [encode/django-rest-framework#6682]
It seems that the fund app is currently broken (and really slow) which results in really slow interaction with the docs (specifically, the search).

The specific link that's broken: https://fund.django-rest-framework.org/sidebar_include.js

For the time being I've blocked the url using umatrix which makes everything fast again. But would it be a possibility to load that script non-blocking/async?

So instead of:
```html
<script src="https://fund.django-rest-framework.org/sidebar_include.js"></script>
```
We could have:
```html
<script async src="https://fund.django-rest-framework.org/sidebar_include.js"></script>
```

**Comment by tomchristie** [comment]
Resolved now, thanks!
(Would happily take a PR changing the script loading to async too)

**Comment by WoLpH** [comment]
@tomchristie I've created the pull request: https://github.com/encode/django-rest-framework/pull/6686
