### ISSUE TITLE
serializer django-celery-beat CrontabSchedule model error

### ISSUE THREAD

**Issue by springgreenner** [encode/django-rest-framework#6690]
django:2.2
restframework:3.9.2
django-celery-beat:1.4.0

I use drf, django-celery-beat CrontabSchedule model serializer error; TypeError: Object of type'UTC'is not JSON serializable, how can I solve it?

**Comment by xordoquy** [comment]
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
