### ISSUE TITLE
Create Token Key Based on Environment

### ISSUE THREAD

**Issue by bobozar** [encode/django-rest-framework#6714]
I want to use Rest Token on different sites e.g test.example.com and production.example.com. I want a situation whereby each domain will have different Token Key. The difference can be 60 random hexadecimal for Test and 80 random hexadecimal for Production. I want to avoid a situation whereby a Token on a test site can't be used on Production site. Can I set params for that in settings.py like TOKEN-AUTH= {'token_length':60} or just sublcass the Token models and add my own fields and methods? What do you suggest?

**Comment by tomchristie** [comment]
Hi there & thanks for your question.

The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions.

Thanks! 😀
