### ISSUE TITLE
Too slow loading with many urls

### ISSUE THREAD

**Issue by GabrielPetz** [encode/django-rest-framework#6721]
## Steps to reproduce
In my system I have around 200 models, for each one there is 6 different urls, 2 for get and post without ids, and the others with get, put, patch and delete passing the id, so, in the end the API contains 1200 urls in total. But the rest_framework load to slow all these urls. 

My example model: 

![image](https://user-images.githubusercontent.com/30831468/58645346-91f86500-82d9-11e9-9f95-e7f58fb56e00.png)

Actually my serializers.py example:

![image](https://user-images.githubusercontent.com/30831468/58644280-565c9b80-82d7-11e9-89ed-f08eb663429e.png)

My views.py example: 

![image](https://user-images.githubusercontent.com/30831468/58644507-c5d28b00-82d7-11e9-8d55-2869cbc5ace2.png)

And my urls.py example:

![image](https://user-images.githubusercontent.com/30831468/58644588-f5819300-82d7-11e9-938e-f460c010307e.png)

## Expected behavior

The loading should be faster. With all the amount of urls that I mention.

## Actual behavior

With the same serializers.py, views.py and urls.py the loading takes more than 4 minutes, when I reduced the urls to only 6 the loading was  fast as it should be, but with all the 1200 urls, it takes unusable.

**Comment by rpkilby** [comment]
Hi @GabrielPetz. There isn't much here that is actionable. If you could profile the code and determine what is taking 4 minutes to run during startup, then maybe we could address that, but we don't have the bandwidth to recreate your setup.

That said, you shouldn't need 6 URLs (one for each HTTP method) per model. You could simplify this to two URLs - one for the list view (get/post) and one for the detail view (get/put/patch/delete).

**Comment by GabrielPetz** [comment]
Thanks @rpkilby for reply my issue, I'm gonna reduce the urls number by 3 per model, but this is only solve my problem by now, the project still growing, and on the future this problem could be back. So I will be glad if that issue could enter in you backlog to be analyzed.

**Comment by rpkilby** [comment]
Hi @GabrielPetz. If you could create an example repository that reproduces the issue, then that's something we could look at. But beyond that, we don't have the bandwidth to recreate your setup.

**Comment by xordoquy** [comment]
If the issue is that it's slow when you have 1200 urls defined, it's likely a Django issue rather than a Django REST framework one.
Note that resolving or reversing an url means it'll scan them one by one until it has match.
