### ISSUE TITLE
ListModelMixin and RetrieveModelMixin does not do any validation

### ISSUE THREAD

**Issue by jonathan-s** [encode/django-rest-framework#6729]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Right now when using `ListModelMixin` or `RetrieveModelMixin` no validation is happening when returning the response. An endpoint using one of these two mixins may accept a query parameter, ideally this query parameter should be validated in the serializer, and if it is not valid the serializer should raise an exception. 

Since no validation is happening in either of these mixins you could have a situation where your endpoint gives a 500 error instead of 400 error. 

## Expected behavior
An endpoint that uses ListModelMixin or RetrieveModelMixin should only use a valid serializer. 

## Actual behavior
The serializer is not checked if it is valid or not, which prevents any the serializer any checking if all query parameters are valid.

**Comment by xordoquy** [comment]
The query parameter should be checked by the `Filter`. I don't see any reason why it should be validated by the serializer. Beside, more often than not invalid query parameters are either discarded or will return results accordingly - ie empty list.

**Comment by jonathan-s** [comment]
👍
