### ISSUE TITLE
RetrieveDestroyAPIView returns 403/405

### ISSUE THREAD

**Issue by wojsamjan** [encode/django-rest-framework#6731]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Similar
[5101](https://github.com/encode/django-rest-framework/issues/5101)

## Steps to reproduce
API tests - (RetrieveDestroyAPIView)
```
self.user = get_user_model().objects.create_user('tuser', 't@t.com', 'passpass')
self.client = APIClient()
self.client.force_authenticate(self.user)
````
```
self.admin = get_user_model().objects.create_superuser('auser', 'a@a.com', 'passpass')
self.client = APIClient()
self.client.force_authenticate(self.admin)
```

SEND a ```PUT``` & ```PATCH``` requests to ```RetrieveDestroyAPIView```

## Expected behavior
405 for both as method is not allowed. Due to #5101 at least consistency with 403*

## Actual behavior
For user got 403 for both - put/patch, for admin 405 for both - put/patch

**Comment by tomchristie** [comment]
Presumably you've got some admin-only permissions setup. (So you're only getting 405 with a logged in admin user.)
