### ISSUE TITLE
serializer does not hash password when fields is __all__

### ISSUE THREAD

**Issue by meysam81** [encode/django-rest-framework#6737]
## Checklist

- [ ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
when inheriting from `rest_framework.serializers.ModelSerializer`, and also the `Meta.fields` is equal to `__all__`, the user `password` is not hashed, and instead, saved in plain text in database.

## Expected behavior
I would expect some kind of default hashing like the following (that I had to add for now apparently):

```
from django.contrib.auth.models import User
from django.contrib.auth.hashers import make_password

from rest_framework import serializers


class UserSerializer(serializers.ModelSerializer):

    @staticmethod
    def validate_password(password: str) -> str:
        return make_password(password)

    class Meta:
        model = User
        fields = '__all__'
        extra_kwargs = {
            'email': {'required': True},
        }
```

## Actual behavior
currently, when you save a user with the given endpoint in `urlpattenrs`, it just saves the password as is (plain text).

It shouldn't be like that. It should have some kind of `default` hashing system compatible with the django hash.

**Comment by xordoquy** [comment]
The serializer does just what he is said to. If anything should be responsible to hash the password, it'd be the model itself.

**Comment by meysam81** [comment]
so you mean this should be an implementation in `django.contrib.auth.models.User`?

**Comment by xordoquy** [comment]
This should be something specific to your own implementation of `User`.
The way it currently works has less magic and thus is easier to understand and troubleshoot.
Raw model mapping to an API isn't a good idea. Did you realize you'll expose the password ? Even if it's hashed, it's not something one usually want.

**Comment by meysam81** [comment]
Yes I am aware. It's a working progress and I'm not worried about that yet. But thanks for pointing it out.
And thanks again for clearing the issue as well.

**Comment by meysam81** [comment]
hey mate,
just a quick question cause I'm lost a little bit at the moment
based on what you said earlier, I'm thinking that the serializer isn't the best place for that `make_password` I wanted to have to hash the password (validate_password)
so I was wondering where to put it and after a little bit of reading through the source codes of both DRF and the django itself, I come up to the point that I should override the `rest_framework.CreateModelMixin.create` in my own viewset (I am inheriting from the `ModelViewSet`)
so my question to you is, **is this the right approach, or am I just fooling around here?**

**Comment by tomchristie** [comment]
Yeah that'd be perfectly sensible.
