### ISSUE TITLE
OpenAPI Schema should support custom operationId on methods

### ISSUE THREAD

**Issue by HT154** [encode/django-rest-framework#6739]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [ ] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
1. Set up a view
2. Add `post` and `get` methods

## Expected behavior
I can override generated `List`, `Retrieve`, or `Create` actions on a per-method basis

## Actual behavior
I'm stuck with the generated names

## Use case
I have a login endpoint that redirects users to an external SSO service. For legacy reasons, this must support GET and POST requests. When the OpenAPI schema is generated (with `rest_framework.schemas.openapi.AutoSchema`), I end up with two operations on the same path (less than ideal, but acceptable) and non-sensical actions (bad). I'd like to instead have the operation IDs `GetLogin` and `PostLogin`.

**Comment by carltongibson** [comment]
Hi @HT154. 

So, what's actually generated vs what'd desired? (Just the snippet is fine.)

Then can you override `get_operation()` or `_get_operation_id()` to give you the result you want?

**Comment by xordoquy** [comment]
At some point, one may want to override a specific view's operation id and it doesn't feel right to include a test on the class view inside `_get_operation_id()` to get that customization.
My though about the schema generation is that it may lack some hooks to customize things on a per view basis to escape the autogeneration.

**Comment by carltongibson** [comment]
Right! Almost certainly. **But** I'm not sure what those hooks are/should be prior to people using the generation, creating some subclasses and seeing the patterns that emerge. 

We added API for the CoreAPI version thinking "this is what people need" and I don't think it saw any use at all. Thus, I'd rather keep it simple for the first version and let people show us subclasses that do more. We can then bring it in. 

Unless somebody can confidently predict the required API...

**Comment by carltongibson** [comment]
First guess, an AutoSchema subclass here would just look like this: 

```
LoginViewSchema(AutoSchema):

    def _get_operation_id(self, path, method):
        if method == 'POST'
            return 'PostLogin'
        else: 
            return 'GetLogin'
```

Then:

```
class LegacyLoginView(APIView):
    schema = LoginViewSchema()
```

That looks pretty clean to me (for a first pass, where we don't know the common required customisations).

**Comment by xordoquy** [comment]
oh, didn't know you could have a per view `AutoSchema`. Seconding you then.

**Comment by carltongibson** [comment]
Yeah... (This was the same design as introduced back in v3.7, except without the **guessed** extra API). 

The idea is: 

* Schema level customization: subclass `SchemaGenerator`. 
* Per-view customization: subclass `AutoSchema`. 

**Maybe** there's some _declarative_ API to be added in a 3.10.1 or 3.10.2, but I want that to be based on actual patterns. 

Doc updates are in https://github.com/encode/django-rest-framework/pull/6668

**Comment by HT154** [comment]
I'm going to proceed with subclassing the relevant schema classes for my purposes, but here are the modifications I've wanted to make so far:
* The one mentioned in this issue: customizable operation IDs - default CRUD operation names aren't applicable for everything. I think a decorator around view methods/functions would be the best API
* Ability to override serializers for requests and responses (independently) - Example: a view that takes a path parameter and no body data and kicks off a background task, returning info about that task (ID, location, etc.)
* Doc-comments as descriptions for paths and operations - View- and method-level docs are definitely a must

I think most or all of these should be included upstream. I'm happy to open issues for the others if you feel it's appropriate, or if this should be implemented as a separate package, go ahead and close this.

**Comment by carltongibson** [comment]
The CoreAPI stuff already did descriptions from docstrings. That could be ported very easily. (A quick PR there would be most welcome!)

There’s hooks for both request body and responses in AutoSchema, so adjusting the serialiser there would be easy enough. (How you’d generalise that would be interesting to see.)

Best bet is to create what you need and put it up as a repo/package that we can look up, and maybe yes there could be stuff to bring in. 

(Initially a bit 😬 about decorators, vs just saying “create a subclass” but it’s much clearer once there’s actual code in play.) 

I’ll leave this open for a few days just in case people want to comment.

**Comment by HT154** [comment]
Unfortunately, my employer requires legal approval for all public code sharing :(

I _might_ be able to post my implementation in 4-8 months

**Comment by carltongibson** [comment]
Well, perhaps you can still post the kind of thing you end up with, rather than the actual code itself. No worries though. 🙂

**Comment by HT154** [comment]
Other potential improvements:
* Surfacing auth, permissions, and throttle info
* Some way to specify request header parameters (pass it a serializer?)
* Ability to add arbitrary serializers as definitions not associated with views (maybe via django settings key?), eg. for message broker message schemas

**Comment by HT154** [comment]
Here's what I've got for custom operation IDs so far:
```python
@api_view(...)
def my_view(...)

```

**Comment by carltongibson** [comment]
Hey @HT154. Yep, I see where you're going with that. 

For me, I think I prefer to keep all the schema stuff in one-place, in the AutoSchema subclass, rather than sprinkling all over the view like this, but I can see there's room for different styles. 

Either way, as I said, until patterns emerge from actual usage, we're going to stick to the simple approach we have, leaving open the option for improvement in the future. 

Thanks for the input. If you do happen to wrap your work up in a re-usable SchemaGenerator/AutoSchema subclass, do let us know!

**Comment by dhaval-mehta** [comment]
Hi @carltongibson, 
Did you find any pattern to solve this?

The solution suggested by @HT154 is nice but I have one concern. In the future, we may customize everything i.e. `tags`, `operation ids`, `request payloads`,  `responses` and many more things. 

The Spring Framework similarly allows schema customization. Just to generate 2 different responses, code took so many lines. [click here to see an example.](https://www.baeldung.com/swagger-2-documentation-for-spring-rest-api#3-custom-methods-response-messages)

I have a second approach. Let's have a separate view and schema generation logic. It might be in schemas.py. Here, we can provide a class that easily allows overriding schema generation.

**Comment by carltongibson** [comment]
Subclassing AutoSchema already allows this.

**Comment by ReetiMauryaCrest** [comment]
@carltongibson is there a way to generate OperationID using basename provided in router using AutoSchema? Or do we need to provide different names based on operations like shown in your example? 

I have 2 viewsets which are working on same model, one is a simple model viewset while the other is a grouped version for the model, I am able to generate and use different paths based on basename in the grouped version but when I run generateSchema it is generating same operationID's for both the viewset, which I thought would be overwritten to reflect basename.
