### ISSUE TITLE
Add the new locale HY

### ISSUE THREAD

**Issue by melikyan-a** [encode/django-rest-framework#6743]
I did request on Transifex for the new locale HY-AM, I am ready to make translation.

**Comment by rpkilby** [comment]
@tomchristie is there anything to be done? Either here or on Transifex?

**Comment by melikyan-a** [comment]
Please add HY locale in the next release, I finished the translation on Transifex.

**Comment by tomchristie** [comment]
@melikyan-a - Great... looks like that oughta all get pulled into the next release now.

Thanks for the bump @rpkilby!

**Comment by melikyan-a** [comment]
Dear @tomchristie, in version 3.10 HY locale did not added (

**Comment by rpkilby** [comment]
Hm. 3.10 updated the translations. @tomchristie is there something that needs to be done to pickup new translation files?

**Comment by melikyan-a** [comment]
Have you any news guys?

**Comment by tomchristie** [comment]
Closing as stale, though if anyone confirms that this *still* isn't fixed in 3.12, then we could have a look again.
