### ISSUE TITLE
[docs] Fixed header sometimes overlaps page anchors

### ISSUE THREAD

**Issue by rpkilby** [encode/django-rest-framework#6749]
Jumping to a subsection via the sidenav will sometimes cause the page header to overlap the anchor point. When navigation is working correctly, there's a perceptible flicker/jump, so I'm guessing javascript is being used to calculate the offsets. Looking at mkdocs's docs, this isn't an issue. I'm wondering if this is something that will be fixed by upgrading mkdocs (#6623), or if it's a theme issue.

![foo](https://user-images.githubusercontent.com/2370209/59729209-39d6c380-91f2-11e9-8871-bcb8d1584dc3.gif)

**Comment by tomchristie** [comment]
Looks like this is resolved.
