### ISSUE TITLE
BasePermission's has_permission and has_permission should return False

### ISSUE THREAD

**Issue by dms-cat** [encode/django-rest-framework#6750]
## Checklist

- [ ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question.
- [x] This cannot be dealt with as a third party library.
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request.

## Steps to reproduce

1. Create a subclass of `BasePermission` and add it to `permission_classes` for a view set.
1. Try to access an instance within the view set.

## Expected behavior

Access should be denied, because the permission has not been granted, that is, it has not been assigned to any users.

## Actual behavior

Access is allowed.

This is counter to [OWASP recommendations](https://www.owasp.org/index.php/Positive_security_model), and makes it unfeasible to maintain a complex security model.

**Comment by carltongibson** [comment]
This would require a major version change and break all existing Django REST Framework installations that made use of the permissions system. 

See the [How permissions are determined docs](https://www.django-rest-framework.org/api-guide/permissions/#how-permissions-are-determined) for correct usage.

**Comment by l0b0** [comment]
As far as I can tell this would break exactly those installations which have *holes* in their permissions handling. Surely that's an *improvement?*

**Comment by dms-cat** [comment]
How about renaming `BasePermission` to `AllowAny` then?

**Comment by tomchristie** [comment]
The only case where this really matters is if you use `BasePermission` and don't override `has_permission`.

So long as you actually *have* a `has_permission` implementation, then it's not particularly *either* a "positive security model" *or* a "negative security model".

In a different world perhaps we could do something like this, but the logical outcome would be that we strictly deny *all* incoming requests, unless the dev has explicitly added permissions. That *might* be a good strict model, but we're 8 years into this projects history at this point, and I don't think it's a feasible change.

By all means lets make any changes that make it harder to do things wrong, but this doesn't look like a practical suggestion. (Renaming it to `AllowAny` and subclassing is an okay suggestion but doesn't feel like an improvement from my POV either).

**Comment by dms-cat** [comment]
OK, we'll look into replacing `BasePermission` for our application.
