### ISSUE TITLE
ModelSerializer fields does not get updated correctly when signals are connected to some fields

### ISSUE THREAD

**Issue by Krystofee** [encode/django-rest-framework#6751]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

Having model Ticket

``` Python
class Ticket(models.Model):
    tags = models.ManyToManyField(to='Tag', ...)
    changed_by_signal = models.CharField(...)
    # ... other fields ...
```

then some custom signal which is listening to Ticket.tags changes

``` Python
@receiver(m2m_changed, sender=Ticket.tags.through)
def process_tags_changed(sender, ticket, tag_set, **kwargs):
    ticket.changed_by_signal = 'Some value'
    ticket.save()
```

and TicketModelSerializer

``` Python
class TicketModelSerializer(serializers.ModelSerializer):
    class Meta:
        model = Ticket
        fields = ('tags', 'changed_by_signal')
```

then when you save serializer with new `tags` and `changed_by_signal` **left unchanged** (e. g. `None`), you would expect the value of `changed_by_signal` to be 'Some value' as the signal sets, but the value is `None`. Why? Because `ModelSerializer.update` method does not update fields in correct way.

``` Python
class ModelSerializer(Serializer):
    ...

    def update(self, instance, validated_data):
        raise_errors_on_nested_writes('update', self, validated_data)
        info = model_meta.get_field_info(instance)

        # Simply set each attribute on the instance, and then save it.
        # Note that unlike `.create()` we don't need to treat many-to-many
        # relationships as being a special case. During updates we already
        # have an instance pk for the relationships to be associated with.
        for attr, value in validated_data.items():  # <- 1.
            if attr in info.relations and info.relations[attr].to_many:
                field = getattr(instance, attr)
                field.set(value)
            else:
                setattr(instance, attr, value)
        instance.save()

        return instance
```

1. ModelSerializer updates the data from validated_data dict which is not sorted in any way. So when `tags` gets updated before `changed_by_signal`, then the value which is set by signal gets overriden.

## Proposed solution

I suppose changing the ModelSerializer method to

1. save non m2m fields (does not trigger any signals and does not change the instance as a side effect)
2. save m2m fields (can trigger side signals and change instance by side effects)

``` Python
class ModelSerializer(Serializer):
    ...

    def update(self, instance, validated_data):
        raise_errors_on_nested_writes('update', self, validated_data)
        info = model_meta.get_field_info(instance)

        # Simply set each attribute on the instance, and then save it.
        # Note that unlike `.create()` we don't need to treat many-to-many
        # relationships as being a special case. During updates we already
        # have an instance pk for the relationships to be associated with.
        m2m_fields = []
        for attr, value in validated_data.items():
            if attr not in info.relations or not info.relations[attr].to_many:
                setattr(instance, attr, value)
            else:
                m2m_fields.append((attr, value))

        for attr, value in m2m_fields:
            field = getattr(instance, attr)
            field.set(value)

        instance.save()

        return instance
```

Which stores m2m fields in a list that is processed after every other field has been changed. This is my temporary override for the TicketModelSerializer. I would consider making a pull request with changes that fix this issue.

**Comment by tomchristie** [comment]
I think we're likely going to pass on this, as an out-of-scope usage.

We could *consider* a pull request that addressed it, but it seems like a pretty fundamental change, and it's not obvious that it wouldn't have side effects.

If you're really invested in seeing it happen you're welcome to attempt a pull request for it, to see if you're able to make the proposed change without affecting anything already existing in the test suite.

**Comment by xordoquy** [comment]
This looks like it'll fix your use case by using side effects.
I guess it should work out of the box by setting `changed_by_signal` as read-only since you're altering the data anyway.

**Comment by Krystofee** [comment]
I've created pull request as @tomchristie suggested. It passed all tests from `./runtests.py`. Please let me know if anything else is required.

@xordoquy what if I need field `changed_by_signal` to by writable? (I named it in the simplest example `changed_by_signal` to emphasize what's going on but it can be any field.)

**Comment by xordoquy** [comment]
> what if I need field changed_by_signal to be writable?

Then - with the proposed change - it's going to be overridden by the signal meaning it'll be useless to make it writable.

**Comment by Krystofee** [comment]
What if the signal is conditional based on other change, getting overriden under specific circumstances? 

My concrete problem is that I have user-definable automation system, which listens to the django signals and does many actions, such as modifying the instance. **Even in django forms are m2m fields saved after saving the instance.**

**Comment by rpkilby** [comment]
I think I'm +1 to this change. The current behavior is subject to whatever order the dict keys happen to be in. This is more predictable. 

It's also worth noting that modelforms also update/save the instance before setting the m2m fields. I'd be +1 to changing this as well.

**Comment by tomchristie** [comment]
Didn't fully understand this at first, but #6752 has convinced me, yup. 👍

**Comment by aMegvinov** [comment]
I can't understand why instance is getting saved before setting m2m_fields:
```
m2m_fields = []
for attr, value in validated_data.items():
    if attr in info.relations and info.relations[attr].to_many:
        m2m_fields.append((attr, value))
    else:
        setattr(instance, attr, value)

instance.save()

# Note that many-to-many fields are set after updating instance.
# Setting m2m fields triggers signals which could potentially change
# updated instance and we do not want it to collide with .update()
for attr, value in m2m_fields:
    field = getattr(instance, attr)
    field.set(value)

return instance
```
are they saved at all?

**Comment by auvipy** [comment]
> are they saved at all?

can you demonstrate a failing test case? please
