### ISSUE TITLE
IntegrityError is not

### ISSUE THREAD

**Issue by gforcada** [encode/django-rest-framework#6759]
## Checklist

- [X] I have verified that that issue exists against the `master` branch of Django REST framework.
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [X] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [ ] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

We have the following models with a constraint on the `Relation` one:

```python
class User(models.Model):
    user_id = models.CharField(max_length=255)

class Relation(models.Model):
    follower = models.ForeignKey(User, on_delete=models.CASCADE, related_name='+')
    followed = models.ForeignKey(User, on_delete=models.CASCADE, related_name='+')

    class Meta:
        constraints = [
            # Check that users can not follow themselves
            models.CheckConstraint(
                check=~Q(follower=F('followed')), name='follower_ne_target'
            )
        ]
```

On the viewset we have:

```python
class FollowersViewSet(mixins.CreateModelMixin, viewsets.GenericViewSet):
    queryset = User.objects.all()
    serializer_class = UserIdSerializer
    lookup_field = 'user_id'

    def create(self, request, user_id):
        followed = get_object_or_404(User, user_id=user_id)
        follower = get_object_or_404(User, user_id=request.data['user_id'])
        relation, created = Relation.objects.get_or_create(
            followed_id=followed.id, follower_id=follower.id
        )
        serializer = RelationSerializer(relation, context={'request': request})
        return Response(
            serializer.data,
            status=created and status.HTTP_201_CREATED or status.HTTP_409_CONFLICT,
        )
```
If someone tries to follow herself/himself the `Relation.objects.get_or_create` fails with an `IntegrityError` as expected.

What is not expected is that rather than getting a json response telling that a constraint was not met, or even a generic "something happened", we get a raw error message coming from django.

## Expected behavior
To get a response like with any other validation errors that return a nicely parseable json response.

## Actual behavior
You get a plain django error message

**Comment by rpkilby** [comment]
Hi @gforcada. There are two separate issues here.

> ## Expected behavior
> To get a response like with any other validation errors that return a nicely parseable json response.

Validation error handling is performed in the serializer, not the view. In general, any non-`APIException` raised in your view is going to result in a 500. You'll need to perform your own error handling here. 

> What is not expected is that rather than getting a json response telling that a constraint was not met 

Unfortunately, there is no clean, generalizable way for handling integrity errors. Separate exception classes aren't raised for unique constraint failures, non-null failures, or other arbitrary constraint failures (e.g., the check constraint on your model), so we can't provide useful error messages that inform the user as to what went wrong. There are different suggestions for handling integrity errors <sup>[[1](https://stackoverflow.com/a/27729696/1103124)], [[2](https://stackoverflow.com/a/12495497/1103124)]</sup>, but ultimately any solution is going to be specific to your use case. 

DRF has a few validators for guaranteeing uniqueness, but these don't catch/process integrity errors. Instead, they execute a query to ensure a conflicting object does not already exist. However, that solution wouldn't work here. I'd recommend adding a check to your code that ensures the follower != followed, and raise a DRF validation error accordingly.
