### ISSUE TITLE
Serializer as the default serializer in GenericAPIView

### ISSUE THREAD

**Issue by WisdomPill** [encode/django-rest-framework#6763]
I always go into the problem of putting a serializer in an api that does not use a serializer, but only the get_object() or get_queryset() methods.
My suggestion is to put Seraliazer as the default serializer in GenericAPIView.

Thanks.

**Comment by rpkilby** [comment]
Hi @WisdomPill. We would prefer that the view break in obvious ways (e.g., loudly complain about a missing class), rather than having the serializer class fail to function. The former is conveyed as a programmer error, while the latter is conveyed as a user/client error.
