### ISSUE TITLE
Multile HelpText on Serializer  Meta clkas 

### ISSUE THREAD

**Issue by mullerivan** [encode/django-rest-framework#6778]
Hi there awesome work BTW.

just  trying to  overwrite  all helper text from my model, cause the  Help that i need to  print  on UI is  compliantly  different  from API
So would like to  overwrite ti  in bunch 
something like 

```
class MyModelSerializer(serializers.ModelSerializer):
    class Meta:
        model = MyModel
        fields = FIELDS
       help_texts = {'field_one':''MyAPiHelpText', field_two: 'MyAPiHelpText'}
```

Any  clue of how to  do that? 

Thanks

**Comment by rpkilby** [comment]
Hi @mullerivan. Field arguments can be provided via `Meta.extra_kwargs`.

class MyModelSerializer(serializers.ModelSerializer):
    class Meta:
        model = MyModel
        fields = FIELDS
        extra_kwargs = {
            'field_one': {'help_text': 'MyAPiHelpText'}, 
            'field_two': {'help_text': 'MyAPiHelpText'},
        }

**Comment by mullerivan** [comment]
Thanks mate!
