### ISSUE TITLE
Missing List Comprehension in docs/tutorial/1-serialization.md | Tutorial 1: Serialization | snippets/models.py 

### ISSUE THREAD

**Issue by alex-code4okc** [encode/django-rest-framework#6780]
## Checklist

- [yes] I have verified that that issue exists against the `master` branch of Django REST framework.
- [yes] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [yes] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [NA] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [yes] I have reduced the issue to the simplest possible case.
- [No] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
In Tutorial 1: Serialization, when creating the Snippets model in snippets/models.py, the variable STYLE_CHOICES is assigned: 

STYLE_CHOICES = sorted( (item, item) for item in get_all_styles() )

The global function sorted() expects  a  list, or an iterable. However this is not being given. STYLE_CHOICES should be generated by using a list comprehension just like LANGUAGE_CHOICES variable defined immediately before it.

## Expected behavior
STYLE_CHOICES should be a list and assigned the following:
STYLE_CHOICES = sorted( [(item, item) for item in get_all_styles()] )

## Actual behavior
snippets/models.py currently fails as sorted is not being given a list or an iterable.

**Comment by xordoquy** [comment]
Thanks for the report.
I could not reproduce the issue with Python 2.7 nor with Python 3.7.
