### ISSUE TITLE
I want to disable the Browsable API display URL from becoming a hyperlink automatically.

### ISSUE THREAD

**Issue by tkhr2019** [encode/django-rest-framework#6782]
Hello.

It's convenient to be able to run REST from a browsable API using django-rest-framework.
If JSON contains a URL, it will automatically become a hyperlink.

I handle dangerous domains, so I do not want them to be easily hyperlinked.
Please let me know if there is a way to disable the ability to make URLs automatically hyperlinks.

Thank you.

**Comment by tomchristie** [comment]
Hi there & thanks for your question.

The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions.

Thanks! 😀

**Comment by tkhr2019** [comment]
Thank you for answering.
I will ask you in a discussion group.
