### ISSUE TITLE
Lists are not currently supported in HTML input

### ISSUE THREAD

**Issue by layamahmoudi** [encode/django-rest-framework#6790]
My project is about a university system. 2 Custom Users named Student and Professor are defined which inherits Django User Model. There is a course Model which have ManyToMany relation with Professor model to define courses and define professor for each course. I used CreateMixinModel, UpdateMixinModel, DestroyMixinModel to Update, Create and delete courses. CRUD was applied correctly. But there was a problem in displaying Professor's information and it just return professor id. I use a nested serializer in CourseCreateSErializer to display professor information beside course info. And now I cannot edit Course Object.

I want to be able to edit Course Object

models.py:
```python
class Professor(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    professor_no = models.PositiveIntegerField()

    def get_full_name(self):
        return self.user.first_name

    def __str__(self):
        return self.user.first_name + " " + self.user.last_name


class Course(models.Model):
    professor = models.ManyToManyField(Professor)
    name = models.CharField(max_length=100)
    unit = models.PositiveIntegerField()
```

serializers.py:
```python
class CustomUserSerializer(serializers.ModelSerializer):
    class Meta:
        model = CustomUser
        fields = ('first_name',
                  'last_name',
                  'identity_no',
                  'email')

    def create(self, validated_data):
        return CustomUser.objects.create(**validated_data)

class ProfessorDetailSerializer(serializers.ModelSerializer):
    user = CustomUserSerializer()
    class Meta:
        model = Professor
        fields = (
            'user',
            'professor_no'
        )

    def create(self, validated_data):
        return CustomUser.objects.create(**validated_data)

class CourseDetailSerializer(serializers.ModelSerializer):
    professor =ProfessorDetailSerializer(many=True)

    class Meta:
        model = Course
        fields = (
            'professor',
            'name',
            'unit',
        )
```

view.py:
```python
class CourseDetailView(DestroyModelMixin, UpdateModelMixin, RetrieveAPIView):
    queryset = Course.objects.all()
    serializer_class = CourseDetailSerializer
    permission_classes = [IsAuthenticatedOrReadOnly]


    def put(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        return self.destroy(request, *args, **kwargs)
```

**Comment by rpkilby** [comment]
Hi @layamahmoudi. The browsable API form doesn't support lists of objects, however you can switch to "Raw data" to input the data as a JSON object.

**Comment by layamahmoudi** [comment]
Hi, I cannot understand what I should do

در تاریخ دوشنبه ۸ ژوئیهٔ ۲۰۱۹،‏ ۲۳:۲۰ Ryan P Kilby <notifications@github.com>
نوشت:

**Comment by rpkilby** [comment]
I've highlighted the buttons in red. You should be able to enter a list of data by switching from "HTML form" to "Raw data".

![Screen Shot 2019-07-08 at 12 19 56 PM](https://user-images.githubusercontent.com/2370209/60836566-ceda3600-a17a-11e9-9e6d-1417965330a3.png)

**Comment by layamahmoudi** [comment]
So, how I should do it??

در تاریخ دوشنبه ۸ ژوئیهٔ ۲۰۱۹،‏ ۲۳:۵۱ Ryan P Kilby <notifications@github.com>
نوشت:

**Comment by tomchristie** [comment]
@layamahmoudi Heya - Could you please take any further questions around this to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) - that's a better place for usage questions. Thanks!
