### ISSUE TITLE
CSRF: Why does SessionAuthentication disable CSRF for unauthenticated users? 

### ISSUE THREAD

**Issue by ajbeach2** [encode/django-rest-framework#6795]
Django Rest Framework by default will make APIView csrf excempt for ApiView. CSRF handling in DRF is done at the SessionAuthenticaiton class level.

Here is the relevant code:
https://github.com/encode/django-rest-framework/blob/master/rest_framework/views.py#L144
All ApiView(s) will by default will be csrf_exempt.

When requests are authenticated with the SessionAuthentication class, unauthenticated users csrf tokens are not enforced
https://github.com/encode/django-rest-framework/blob/master/rest_framework/authentication.py#L124

If using SessionAuthenticaiton, any login views for example, that use the base ApiView and default SessionAuthentication class, would be vulnerable to csrf. 

Shouldn't the SessionAuthentication authenticate method always enforce csrf regardless if it is an unauthenticated user for?

**Comment by xordoquy** [comment]
> Shouldn't the SessionAuthentication authenticate method always enforce csrf regardless if it is an unauthenticated user?

no because it'll enforce CSRF checks on other authentication methods.

> If using SessionAuthenticaiton, any login views for example, that use the base ApiView and default SessionAuthentication class, would be vulnerable to csrf.

This is why we have a [warning in the docs](https://www.django-rest-framework.org/api-guide/authentication/#sessionauthentication) about not doing that:

> Warning: Always use Django's standard login view when creating login pages. This will ensure your login views are properly protected.

**Comment by ajbeach2** [comment]
@xordoquy I am not sure i follow.  This would affect all requests is that what you are saying? not just posts? Don't SessionAuthentation and TokenAuthenticaiton have separate authenticate methods?

> Warning: Always use Django's standard login view when creating login pages. This will ensure your login views are properly protected.

If i am building a SPA, with a restful json API why would i render my login forms in the API duplicating styling, other front end components to the API layer?  I am not sure this recommendation makes sense. 

Maybe a decorator makes more sense?

In any case, I have a web app where I am only using session authentication, and this is how i enabled csrf on my login view. Is there a better approach with DRF?

```
from rest_framework.authentication import SessionAuthentication


class SessionAuthAll(SessionAuthentication):

    def authenticate(self, request):
        """
        Returns a `User` and force CSRF even if
        the user is Unauthenticated
        """

        # Get the session-based user from the underlying HttpRequest object
        user = getattr(request._request, 'user', None)

        self.enforce_csrf(request)

        # CSRF passed with authenticated user
        return (user, None)

class LoginView(APIView):
    permission_classes = ()
    authentication_classes = (SessionAuthAll,)

    @method_decorator(never_cache)
    @method_decorator(ensure_csrf_cookie)
    def get(self, request, format=None):
        serializer = UserSerializer(request.user, context={'request': request})
        if(request.user.__str__() == 'AnonymousUser'):
            return Response({'authenticated': False,
                             'user': {"username": 'AnonymousUser'}},
                            status.HTTP_200_OK)
        else:
            return Response({'authenticated': request.user.is_authenticated,
                             'user': serializer.data}, status.HTTP_200_OK)

    @method_decorator(never_cache)
    @method_decorator(csrf_protect)
    def post(self, request, format=None):
        user = authenticate(request,
                            username=request.data.get('username', None),
                            password=request.data.get('password', None))
        if user is None:
            return Response({"error":
                             {"login": ["Invalid username or password"]}},
                            status=status.HTTP_401_UNAUTHORIZED)
        else:
            login(request, user)
            return Response({
                'authenticated': True,
                'user': UserSerializer(user).data},
                status.HTTP_200_OK)

```

**Comment by xordoquy** [comment]
> This would affect all requests is that what you are saying? not just posts?

This would affect POST / PUT / PATCH that are send using a non session based authentication method - provided that are listed after the session authentication backend.

> Don't SessionAuthentation and TokenAuthenticaiton have separate authenticate methods?

Sure but let's consider a token based auth request using the POST verb.
The request arrives and SessionAuth tries to authenticate it. It fails, consider it's an anonymous request and runs the CSRF check.
Since token based auth are not subject to CSRF, it will break any client using the token authentication due to the lack of CSRF.

> If i am building a SPA

then you should consider a token based auth such as JWT or OAUTH2.
Session based authentication are a nice way to provide a single login if the site has pure Django pages and some rendered through JS+API but requires CSRF.

**Comment by tomchristie** [comment]
Related https://github.com/encode/django-rest-framework/issues/785, https://github.com/encode/django-rest-framework/issues/6104

Happy to see this discussed further, but it probably ought to be on the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework).

Thanks! 😀

**Comment by ajbeach2** [comment]
I can see now the issue now with supporting both both a Token + Session backend.  My above solution only works because I am explicitly disabling TokenAuth, i only have SessionAuthentication enabled in settings.py. If for example, you had both backends configured in settings.py, and you did enforce csrf only in SessionAuthentication, the requests would still always succeed because it would succeed in the TokenAuthencation backend, which wouldn't enforce csrf.

Thanks for the clarification.
