### ISSUE TITLE
Links in docs navbar are broken

### ISSUE THREAD

**Issue by spookylukey** [encode/django-rest-framework#6803]
Steps:
* Go to almost any page in docs e.g. https://www.django-rest-framework.org/tutorial/quickstart/
* Click on almost any link in navbar e.g. API Guide / Requests
* Result: end on 404: https://www.django-rest-framework.org/tutorial/quickstart/api-guide/requests/

It seems to be using relative links instead of absolute ones. Also 'Next' and 'Previous' buttons,

Some links within pages seem to be broken too e.g. at the bottom of https://www.django-rest-framework.org/tutorial/quickstart/ the "API guide" link is broken, but most seem OK.

Also, the 404 page looks quite wonky, seems to be missing CSS.

**Comment by rpkilby** [comment]
Hm. I assume this is due to the update to mkdocs. Thanks for the report

**Comment by tomchristie** [comment]
Blergh. I rebuilt with the pinned version of MkDocs following you tweet on this, but evidently that didn’t resolve the issue.

To check: what version did we build with on the previous release.

Anyone else on the maintenance team want to try rebuilding the docs?

**Comment by rpkilby** [comment]
I rebuilt locally and just noticed it. I think this is related to https://github.com/mkdocs/mkdocs/pull/1526

**Comment by rpkilby** [comment]
This might be as simple as appending `|url` to the links in the templates, not sure about the markdown pages.

**Comment by tomchristie** [comment]
I think we're sorted now. Thanks folks!
