### ISSUE TITLE
ValueError when import APIClient

### ISSUE THREAD

**Issue by Marpop** [encode/django-rest-framework#6804]
## Steps to reproduce

`from rest_framework.test import APIClient`

## Expected behavior

nothing, just import and use it ;)

## Actual behavior

![image](https://user-images.githubusercontent.com/15074433/61219677-02860480-a715-11e9-8db0-d9178176f101.png)

**Comment by xordoquy** [comment]
```
python manage.py shell
Python 3.6.8 (default, Dec 30 2018, 13:01:27) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from rest_framework.test import APIClient
>>> 
```

**Comment by xordoquy** [comment]
Closing as I can not reproduce.
From the traceback, you should double check your renderers are correctly set.

**Comment by Marpop** [comment]
Thanks. 

`REST_FRAMEWORK["TEST_REQUEST_RENDERER_CLASSES"] = "json"` was problem in test settings.
