### ISSUE TITLE
Documentation - Left bar links redirect to root url

### ISSUE THREAD

**Issue by lilfolr** [encode/django-rest-framework#6806]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
1. View the docs site (eg, https://www.django-rest-framework.org/api-guide/relations/)
2. Click one of the links on the left nav-bar

## Expected behaviour
- Page is scrolled to the clicked location

## Actual behaviour
- Page is redirected to the root url (https://www.django-rest-framework.org/)

The documentation generator seems to be appending `../` to the relative tag-href
eg: `<a href="../../#reversing-action-urls">Reversing action URLs</a>`

**Comment by tomchristie** [comment]
Now resolved - thanks for raising this!
