### ISSUE TITLE
Search doesn't work in the documentation, require.js not found

### ISSUE THREAD

**Issue by Alexgmin** [encode/django-rest-framework#6807]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Search in the documentation website.

## Expected behavior
It works.

## Actual behavior
It doesn't. 
https://www.django-rest-framework.org/mkdocs/js/require.js is not found, so a JS error is logged in the console.

**Comment by rpkilby** [comment]
@tomchristie I'm not sure what you might want to do here. We either need to embed our own copy of require and leave it as-is, or we could update the search feature based off of https://github.com/mkdocs/mkdocs/pull/1418.

**Comment by tomchristie** [comment]
Can we link to a CDN version?
I’m okay with us including it if not.

**Comment by rpkilby** [comment]
We should probably include it, given that we don't rely on CDNs for other assets.

**Comment by rpkilby** [comment]
Hm. It doesn't look like it's as simple as just adding require.js to the static assets. We're depending on additional files (e.g., search.js) provided by the old mkdocs theme. However, these files are no longer there.
