### ISSUE TITLE
OpenAPI AutoSchema does not handle ListField correctly

### ISSUE THREAD

**Issue by khj809** [encode/django-rest-framework#6815]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
djangorestframework==3.10.0

```python
# serializers.py
class MySerializer(serializers.Serializer):
    my_values = serializers.ListField(child=serializers.FloatField())

# views.py
class MyAPIView(GenericAPIView):
    serializer_class = MySerializer
```
`urls.py` and `templates/swagger-ui.html` are same as described in [documentation](https://www.django-rest-framework.org/topics/documenting-your-api/).

## Expected behavior
Swagger should render schema without any problems.

## Actual behavior
swagger
![swagger](https://i.imgur.com/t4Eaylp.png)
console
![console](https://i.imgur.com/P0BlLAF.png)

I think the latest version of drf does not handle `ListField` correctly. The `array` type in OpenAPI should come with corresponding `items`, but `AutoSchema` in `rest_framework.schemas.openapi` does not provide `items` for `ListField` in `_map_field` method.
https://github.com/encode/django-rest-framework/blob/master/rest_framework/schemas/openapi.py#L257-L261

**Comment by carltongibson** [comment]
OK, looks like a good addition. Do you think you could make a PR adding the correct mapping for ListField?
