### ISSUE TITLE
Drop Django 2.0 support 

### ISSUE THREAD

**Issue by johnthagen** [encode/django-rest-framework#6821]
[Django 2.0 went EOL April 1, 2019](https://www.djangoproject.com/download/#supported-versions), so I suggest that it is dropped from the supported versions and from `tox`/Travis.

**Comment by rpkilby** [comment]
When Django 3.0 is released in December, we'll drop support for anything below Django 2.2

**Comment by carltongibson** [comment]
Yeah, we tend to hang on just a little while longer unless there’s a reason not to. (For example, we probably wouldn’t introduce a new shim for an EOL version.)

**Comment by rpkilby** [comment]
Yeah, I don't think there's a reason we need to drop 2.0 support before 1.11

**Comment by n2ygk** [comment]
1.11 is LTS. 2.0 is not and expires sooner. See the chart at
https://www.djangoproject.com/download/

**Comment by carltongibson** [comment]
Yes, we understand. It’s just that there’s nothing pushing us to drop 2.0, so we’re happy to keep it for a while.
