### ISSUE TITLE
v3.10.1 PyPI release lost description

### ISSUE THREAD

**Issue by johnthagen** [encode/django-rest-framework#6822]
Compare: https://pypi.org/project/djangorestframework/3.10.1/
To: https://pypi.org/project/djangorestframework/3.10.0/

Did something break in the project description for the packaged egg?

**Comment by johnthagen** [comment]
I found a comment where this was already discussed: https://github.com/encode/django-rest-framework/pull/6817#issuecomment-512272606

**Comment by tomchristie** [comment]
Yup. Will have another look into on the next deploy.
