### ISSUE TITLE
Am I right that DRF applies OrderingFilter before SearchFilter?

### ISSUE THREAD

**Issue by variable** [encode/django-rest-framework#6829]
# Steps to reproduce
Added print statements within OrderingFilter and added print statements to SearchFilter

## Expected behavior
Expected SearchFilter to be applied first before applying Ordering Filter

## Actual behavior
Applying OrderingFilter before SearchFilter

**Comment by xordoquy** [comment]
Depends on the order which you declared them.
Note that the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
