### ISSUE TITLE
OpenAPI AutoSchema does not handle lazy strings / ugettext properly

### ISSUE THREAD

**Issue by chrisv2** [encode/django-rest-framework#6831]
## Steps to reproduce

1. create a `UserSerializer` as instance of `ModelSerializer` and use it in a viewset (just like in quickstart tutorial)
2. run `manage.py  generateschema`

## Expected behavior

`generateschema` returns a valid OpenAPI schema

## Actual behavior

The generated schema's description fields contains unserialized lazy strings

```yaml
openapi: 3.0.2
info:
  title: ''
  version: TODO
paths:
  /users/:
    get:
      operationId: ListUsers
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                required:
                - username
                properties:
                  url:
                    type: string
                    readOnly: true
                  username:
                    type: string
                    description: &id003 !!python/object/apply:django.utils.functional._lazy_proxy_unpickle
                    - &id001 !!python/name:django.utils.translation.ugettext ''
                    - !!python/tuple
                      - Required. 150 characters or fewer. Letters, digits and @/./+/-/_
                        only.
                    - {}
                    - &id002 !!python/name:builtins.str ''
```

# Suggested solution
Force description to text in [`schemas.openapi.AutoSchema._map_serializer()`](https://github.com/encode/django-rest-framework/blob/master/rest_framework/schemas/openapi.py#L372)

# Workaround

This problem can be worked around with a custom schema generator:

```python
from django.utils.encoding import force_text
from rest_framework.schemas.openapi import AutoSchema

class FixedAutoSchema(AutoSchema):
    def _map_serializer(self, serializer):
        result = super()._map_serializer(serializer)
        for prop, value in result['properties'].items():
            if 'description' in value:
                value['description'] = force_text(value['description'])
        return result

# in settings.py
DEFAULT_SCHEMA_CLASS = 'myapp.FixedAutoSchema'
```

**Comment by carltongibson** [comment]
Hi @chrisv2. Thanks. (The `force_text()` does the business yes?)

**Comment by chrisv2** [comment]
`django.utils.encoding.force_text` solves this, yes. That's what I use as workaround.

I'd do a PR but I'm not really familiar with DRFs unittests so that may take a while.

**Comment by carltongibson** [comment]
Hey @chrisv2. 

Look at https://github.com/encode/django-rest-framework/commit/2138f558cee33db9dbcff393517173a42a363421

If you added a case in `TestFieldMapping` which passed _map_field a `CharField` instance with a lazy `help_text` that asserted that we got a `str` there back, I think it would be enough.

If you'd like to have a go at that it would be super to have you onboard! 🙂

**Comment by chrisv2** [comment]
Thank's, I'll try.

**Comment by carltongibson** [comment]
Awesome. If you open a PR early, I'm happy to assist if you get stuck somewhere.
