### ISSUE TITLE
OpenAPI: 'description' is a mandatory field on Response.StatusCode

### ISSUE THREAD

**Issue by chrisv2** [encode/django-rest-framework#6833]
As per [OpenAPI Spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#responseObject), the `response` object must have a `description` property.

## Steps to reproduce

Generate a schema with `manage.py generateschema` and paste it into https://editor.swagger.org/

## Expected behavior

There should be no error message

## Actual behavior

We get an error message 
```
Structural error at paths.[path].get.responses.200
should have required property 'description'
missingProperty: description'
```

Note: The description should be added in `schemas.openapi.AutoSchema._get_responses()`, however I'm not sure what to put in there. An empty string does satisfy editor.swagger.io, but of course doesn't help much.

Should we put the serializer's docstring into the description? Would that make sense?

**Comment by tomchristie** [comment]
Let's start by including it but leaving it as an empty string.
Putting something meaningful in there could then be left as a follow up.
Pull requests resolving this would be most welcome.

Thanks! 😃
