### ISSUE TITLE
OpenAPI: Schema.required must not be an empty list

### ISSUE THREAD

**Issue by chrisv2** [encode/django-rest-framework#6834]
Note: I don't know where (or whether) the [spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#schema-object) actually says so, but editor.swagger.io complains about empty `Schema.required` properties. 

`AutoSchema._get_responses` and `AutoSchema._get_request_body` happily create such empty lists and therefore it should be fixed there.

**Comment by tomchristie** [comment]
I assume it's just following the spec badly there, but we should resolve it anyways.
Presumably we should just pop `required` out if it's an empty list?
Want to take a crack at a pull request for this?

**Comment by chrisv2** [comment]
Assign both tickets to me, I'll have a go at this tomorrow, today it's just too hot for work ;)

**Comment by carltongibson** [comment]
Hey @chrisv2. Super thanks. (Again if you want/need input open the PR early and I'm happy to comment.) Champion.

**Comment by tomchristie** [comment]
I'll roll another minor release once this one is in.

(Worth ironing out the various niggles here quickly.)
