### ISSUE TITLE
TypeError: '>' not supported between instances of 'float' and 'NoneType'

### ISSUE THREAD

**Issue by EnTeQuAk** [encode/django-rest-framework#6836]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

On Python 3.

This is a regression from https://github.com/encode/django-rest-framework/commit/afb678433b7dc068213e6e8a359ad1f6fff05b0d, when running a config-change scenario as described in https://github.com/encode/django-rest-framework/issues/1438

## Expected behavior

Not raise an exception

## Actual behavior

Raising `TypeError: '>' not supported between instances of 'float' and 'NoneType'`

**Comment by rpkilby** [comment]
Hi @EnTeQuAk. Could you possibly provide a failing test case? Thanks!

**Comment by EnTeQuAk** [comment]
See my pull request, or do you need anything in addition to that?

**Comment by rpkilby** [comment]
Yeah - I saw it just after commenting. Thanks!
