### ISSUE TITLE
Duplicate OpenAPI operation IDs when there are multiple generic view sets for the same model

### ISSUE THREAD

**Issue by reupen** [encode/django-rest-framework#6844]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

1. Define two generic view sets for the same model. E.g.:
    
    ```python
    class PersonV1(ModelViewSet):
        queryset = Person.objects.all()
        serializer_class = PersonV1Serializer

    class PersonV2(ModelViewSet):
        queryset = Person.objects.all()
        serializer_class = PersonV2Serializer
    ```
    
    (There are multiple reasons why you might do this e.g. old and new versions, different filtering, different audiences...)
    
1. Enable OpenAPI schema generation

## Expected behavior

The `operationID` values generated are unique [as required per the OpenAPI spec](https://swagger.io/specification/#operationObject).

## Actual behavior

The operation IDs are the same for both sets of views. (One problem this causes is that clicking on the operation in Swagger UI causes both operations to expand together.)

## Discussion and possible solutions

The operation IDs generated are in the form of `<action><model name>` i.e. `ListPerson` etc. (The logic is in [`AutoSchema._get_operation_id`](https://github.com/encode/django-rest-framework/blob/0e1c5d313232a131bb4a1a414abf921744ab40e0/rest_framework/schemas/openapi.py#L108).)

I think it is going to be difficult to come up with a pattern for generating meaningful unique names in all cases. However, there should be some effort to make sure that the generated operation IDs are unique.

One possible solution would be to:

1. Detect duplicates.
2. Append an automatically-generated suffix in such cases.
    
    This could, perhaps, be the first 8-characters of a [hash](https://docs.python.org/3/library/hashlib.html) of the view's dotted module path (i.e. `{view.__module__}.{view.__name__}`).
    
    (The reason for the suggestion of a hash is so that it is, at least, reasonably stable.)

**Comment by carltongibson** [comment]
Ok, happy to look at any PRs here, but my initial thought is that you can/should provide an AutoSchema subclass, for at least one of the ViewSets.

(Tricky one...)

**Comment by n2ygk** [comment]
My workaround -- in this
<https://github.com/django-json-api/django-rest-framework-json-api/blob/ab25fb96911d293491245b7024996536e100c345/rest_framework_json_api/schemas/openapi.py#L479-L490>
DJA PR (still WIP) -- was to just name the operationIds based on path.
These IDs are rarely if ever actually used for anything anyway, so their
value just needs to be unique and not necessarily descriptive.

Per your direction, I would eventually expect to move this code out of DJA
and into DRF as a PR, although I look forward to any other way to generate
unique operationIds.

**Comment by Jufik** [comment]
I think we should at least raise an error, and give the possibility to declare part of `operationId`

Couldn't we add some class attributes to handle make help out with `_get_operation_id`?
On my side, I have some models like "Address" ending up with operationId like "listAddresss"... 

I'm think about declaring  "operation_name" and "operation_name_plural" in Views to make things explicit, and to add some errors [around here](https://github.com/encode/django-rest-framework/blob/master/rest_framework/schemas/openapi.py#L47) to ask for specific declaration?

**Comment by carltongibson** [comment]
> Couldn't we add some class attributes to handle make help out with _get_operation_id?

You could easily do that in an AutoSchema subclass. 

Whether it's worth the extra noise in the API for the default case, I'm not sure. 

Best approach is to implement it, post your example here for others, and then we can discuss.

**Comment by gnuletik** [comment]
This issue should be resolved in the 3.12 release thanks to the following PRs:
- [Customize the operation_id_base (see docs in the PR)](https://github.com/encode/django-rest-framework/pull/7190)
- [Harmonize operationId with camelCase](https://github.com/encode/django-rest-framework/pull/7208)
- [Warns users about duplicated operationId](https://github.com/encode/django-rest-framework/pull/7207)

Feel free to try the master branch before release!
I'd be glad to get some feedback!

**Comment by gabn88** [comment]
Using Django 3.12.4 having multiple different actions on a viewset, with the same method (a.k. 'POST') will still raise this error. Would it be an idea to include the action name in the operationID?

**Comment by gnuletik** [comment]
@gabn88 You can set a custom schema in your viewset which overrides the `get_operation_id` method to workaround your issue.
However, that would be a nice addition to use the action name in the AutoSchema class (the default one). Feel free to open a PR :)
