### ISSUE TITLE
Pagination properties missing in list responses in OpenAPI schemas

### ISSUE THREAD

**Issue by reupen** [encode/django-rest-framework#6846]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

1. Create a generic view set using a pagination class e.g. `LimitOffsetPagination`
2. Generate an OpenAPI schema

## Expected behavior

1. The keys that the pagination class wrap the results in appear in the list operation response schema e.g. `count`, `next`, `previous` and `results` for [LimitOffsetPagination](https://github.com/encode/django-rest-framework/blob/0e1c5d313232a131bb4a1a414abf921744ab40e0/rest_framework/pagination.py#L364-L370)

## Actual behavior

1. These properties aren't present. (There doesn't seem to a way for a pagination class to tell `AutoSchema` about what its responses look like.)

(Additionally, if no pagination class is specified, the response schema should be an array rather than an object.)

**Comment by carltongibson** [comment]
Yes, good. 

AutoSchema could check if a pagination class was defined. (Then we can see what might need adding to the pagination classes.)

Fancy working on a PR?

In the meantime I think a subclass (that Just Knows) will be required.

**Comment by reupen** [comment]
Yes, why not.

I'd probably do it in these steps:

1. Make `_get_responses()` detect if it's a list operation and make the response an array if so.
2. Give pagination classes a way to tell `AutoSchema` about their responses (possibly just let them wrap response schemas like they do for the responses themselves).

**Comment by carltongibson** [comment]
This is now resolved. Thanks @reupen!
