### ISSUE TITLE
Getting FilterSetMetaclass' object is not iterable error with FIlters

### ISSUE THREAD

**Issue by ghost** [encode/django-rest-framework#685]
When i try using the filters i get this error

`Error when calling the metaclass bases
    'FilterSetMetaclass' object is not iterable`

My code is

`class StudentFilter(django_filters.FilterSet):
    class Meta:
        model = models.Student
        fields = ['status','agency']`

**Comment by vipul1994** [comment]
how did you solve it?

**Comment by rpkilby** [comment]
Hi @vipul1994 - this issues is pretty old (over 4 years ago) and both DRF and django-filter have changed significantly during this time. If you're getting this exception, I'd recommend opening a new issue over at https://github.com/carltongibson/django-filter/issues.

**Comment by fwip** [comment]
For any future readers who stumble on this issue - we ran into this because we were setting `filter_fields = MyFilterClass` instead of `filter_class = MyFilterClass`.

**Comment by joshuajtaylor** [comment]
Similar to what @fwip said, this error can also happen when incorrectly setting `filter_backends` instead of `filter_class`
Example (incorrect):
`filter_backends = MyFilterClass`
