### ISSUE TITLE
How can we see changes between versions?

### ISSUE THREAD

**Issue by flaugher** [encode/django-rest-framework#6853]
Sorry if this is a stupid question but is there a page where one can go to see what changes have been made to the codebase for each new version of this framework?  Thanks.

**Comment by rpkilby** [comment]
Hi @flaugher. There are few locations:
- For major releases, there is an [announcement](https://www.django-rest-framework.org/community/3.10-announcement/) that highlights the most significant changes. 
- The general [release notes](https://www.django-rest-framework.org/community/release-notes/#3100) contain a list of changes. 
- Releases may also have a [milestone](https://github.com/encode/django-rest-framework/milestone/69?closed=1).
- And you can always [compare](https://github.com/encode/django-rest-framework/compare/3.9.4...3.10.0) branches/tags on GitHub.
