### ISSUE TITLE
DRF generates incorrect OpenAPI schema for generic views' delete method 

### ISSUE THREAD

**Issue by knivets** [encode/django-rest-framework#6856]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
```
# view.py
from rest_framework import generics
from rest_framework import serializers
from django.db import models

class Book(models.Model):
  title = models.CharField(max_length=200)

class BookSerializer(serializers.ModelSerializer):
  class Meta:
    model = Book
    fields = '__all__'

class BookDetail(generics.RetrieveUpdateDestroyAPIView):
  queryset = Book.objects.all()   
  serializer_class = BookSerializer

# urls.py
urlpatterns = [
...
path('api/books/<int:pk>/', views.BookDetail.as_view()),
...
]
```

## Expected behavior
```
$ ./manage.py generateschema

openapi: 3.0.2
info:
  title: ''
  version: TODO
paths:
  /api/books/{id}/:
    delete:
      operationId: DestroyBook
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this book.
        schema:
          type: string
      responses:
        '204':
          description: ''
```

## Actual behavior
```
$ ./manage.py generateschema

openapi: 3.0.2
info:
  title: ''
  version: TODO
paths:
  /api/books/{id}/:
    delete:
      operationId: DestroyBook
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this book.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                required:
                - title
                properties:
                  id:
                    type: integer
                    readOnly: true
                  title:
                    type: string
                    maxLength: 200
```

**Comment by carltongibson** [comment]
Yes, this is valid. `DestroyModelMixin` returns `Response(status=status.HTTP_204_NO_CONTENT)`.

Fix here should be a test case plus an adjustment to _get_responses to sensibly handle the `DELETE` method case. 

https://github.com/encode/django-rest-framework/blob/b45ff072947d01917132ef6993bf1b7f46d9f2c8/rest_framework/schemas/openapi.py#L462

Thanks for the report @knivets. Fancy working on a PR for this?

**Comment by knivets** [comment]
Sure I can work on this. Will submit a PR this week.

**Comment by carltongibson** [comment]
Awesome. Welcome aboard! 🎉

If you need any assistance open a PR early and @carltongibson me, so I'll get a message.

**Comment by knivets** [comment]
Thanks Carlton! :)

**Comment by knivets** [comment]
Hey @carltongibson, I've opened a PR https://github.com/encode/django-rest-framework/pull/6860. Let me know if you have any feedback.
