### ISSUE TITLE
DRF generates incorrect attributes for serializers.ListField

### ISSUE THREAD

**Issue by knivets** [encode/django-rest-framework#6862]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

```
# view.py
from rest_framework import generics
from rest_framework import serializers
from django.db import models

class Book(models.Model):
  title = models.CharField(max_length=200)

class BookSerializer(serializers.ModelSerializer):
  tags = serializers.ListField(min_length=2, max_length=5)
  class Meta:
    model = Book
    fields = ('tags',)

class BooksView(generics.ListAPIView):
  queryset = Book.objects.all()   
  serializer_class = BookSerializer

# urls.py
urlpatterns = [
...
path('api/books/', views.BooksView.as_view()),
...
]
```

## Expected behavior

```
$ ./manage.py generateschema

openapi: 3.0.2
info:
  title: ''
  version: TODO
paths:
  /api/books/:
    get:
      operationId: ListBooks
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                required:
                - tags
                properties:
                  tags:
                    type: array
                    items: {}
                    maxItems: 5
                    minItems: 2
```

## Actual behavior

```
$ ./manage.py generateschema

openapi: 3.0.2
info:
  title: ''
  version: TODO
paths:
  /api/books/:
    get:
      operationId: ListBooks
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                required:
                - tags
                properties:
                  tags:
                    type: array
                    items: {}
                    maxLength: 5
                    minLength: 2
```

https://swagger.io/docs/specification/data-models/data-types/#array-length

**Comment by knivets** [comment]
@carltongibson please confirm whether this is something you'd like me to work on 🙂

**Comment by carltongibson** [comment]
Hi @knivets I’m struggling to spot the difference between the actual and expected here. Could you ping it out for me please? (Sorry)

**Comment by carltongibson** [comment]
Oh, items vs length. Right.

**Comment by carltongibson** [comment]
Yes, I guess we need an adjustment here, after mapping validators. (Grrrr. Messy spec. Grrrr. 🙂)
