### ISSUE TITLE
Error is CoreAPI is installed with generating OpenAPI schema for auth view. 

### ISSUE THREAD

**Issue by chrr** [encode/django-rest-framework#6868]
I am using the `rest_framework.authtoken` app and have it included in my project's urls:

```
import rest_framework.authtoken.views as authtoken_views

urlpatterns = [ ...
 path('api/token-auth', authtoken_views.obtain_auth_token),
]
```

Now, when I run `python manage.py generateschema`, an AttributeError is raised:

```rest_framework/schemas/openapi.py", line 47, in get_paths
    operation = view.schema.get_operation(path, method)
AttributeError: 'ManualSchema' object has no attribute 'get_operation'
```

Commenting out the `token-auth` path resolves the problem.

**Comment by carltongibson** [comment]
Right, yes. 

https://github.com/encode/django-rest-framework/blob/5a8736ae450c14ab1236386c5b6065b355541d5e/rest_framework/authtoken/views.py#L16-L40

Uninstall `coreapi`. 

Then this'll need updating for OpenAPI.

**Comment by chrr** [comment]
Confirming: Uninstalling `coreapi` resolves the problem in my case. 
Thank you!

**Comment by oliviermartin** [comment]
Adding `DEFAULT_SCHEMA_CLASS` to `REST_FRAMEWORK` solve the issue:

```
REST_FRAMEWORK = {
    # Require to continue to use deprecated CoreAPI. OpenAPI will replace CoreAPI but both API
    # are not compatible with each other
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
}
```

See: https://www.django-rest-framework.org/community/3.10-announcement/#continuing-to-use-coreapi
