### ISSUE TITLE
Update to Boostrap 3.4.1

### ISSUE THREAD

**Issue by rpkilby** [encode/django-rest-framework#6871]
Bootstrap 3.4.1 fixes another xss vulnerability

https://github.com/twbs/bootstrap/releases/tag/v3.4.1

**Comment by dgarros** [comment]
We are also interested in this patch. Our security team is blocking the approval of some projects based on DRF because of this vulnerability.

Also any chance to get this fix in a 3.9.x release as well ? not sure if 3.9.5 is planned or not

Thanks

**Comment by rpkilby** [comment]
> Also any chance to get this fix in a 3.9.x release as well ?

3.9.x is no longer supported, but this could land in a 3.10.x release.
