### ISSUE TITLE
OpenAPI Schema inconsistent operationId casing

### ISSUE THREAD

**Issue by peterfarrell** [encode/django-rest-framework#6875]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

There is inconsistent casing of titles in the the OpenAPI `operationId` naming.

## Expected behavior

Expected behavior is that the method names are consistent in case between them. I.e.

```
RetrieveRegistrant
ListRegistrant
```

or 

```
retrieveRegistrant
listRegistrant
```

Given that the rest of the method names are lowercase, I would opt for `listRegistrant` (initial lower camel case) over CamelCase.

## Actual behavior

 It lowercases all methods names accept for List which is hardcoded.

```
retrieveRegistrant
ListRegistrants
```

Problem area:

[https://github.com/encode/django-rest-framework/blob/master/rest_framework/schemas/openapi.py#L112](https://github.com/encode/django-rest-framework/blob/master/rest_framework/schemas/openapi.py#L112

**Comment by carltongibson** [comment]
Hi @peterfarrell. Want to make a PR correcting that `L`?

**Comment by domingues** [comment]
We still have inconsistency when using APIView:
![imagem](https://user-images.githubusercontent.com/5983487/73078394-fe078900-3eb9-11ea-92d7-692801dd3449.png)
![imagem](https://user-images.githubusercontent.com/5983487/73078471-21323880-3eba-11ea-88b1-e022fe160a96.png)
one option is to lower case in this line: https://github.com/encode/django-rest-framework/blob/8a5bcf97b62bc68d20eef6867ecc42b53f1ad26e/rest_framework/schemas/openapi.py#L112
