### ISSUE TITLE
ImportError: cannot import name 'unicode_to_repr'

### ISSUE THREAD

**Issue by abhay-kum** [encode/django-rest-framework#6879]
## Checklist

- [ ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [ ] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Actual behavior
ImportError: cannot import name 'unicode_to_repr' from 'rest_framework.compat'

**Comment by rpkilby** [comment]
Hi @abhay-kum. `unicode_to_repr` was removed in the 3.10 release. My guess here is that some 3rd party code is relying on it. To debug this you'll need to look at/provide the full traceback.

**Comment by jttttttttttttt** [comment]
Hi:
python           3.10.8
Django                    4.0.8
djangorestframework       3.14.0

will cause ImportError: cannot import name 'unicode_to_repr' from 'rest_framework.compat'，any change?
