### ISSUE TITLE
Inconsistent handling of allowed_methods casing when generating OpenAPI schema

### ISSUE THREAD

**Issue by knivets** [encode/django-rest-framework#6881]
When I try to set `allowed_methods ` to a lower case HTTP verb, it results in:
- not including a request body
- breaking schema for an operation completely if I set it to `operation`, or arbitrary value 

## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

```
class Book(models.Model):  
    title = models.CharField(max_length=200)

class BookSerializer(serializers.ModelSerializer):
    class Meta:
        model = Book
        fields = ['__all__']

class BookDetail(generics.UpdateAPIView):
    queryset = Book.objects.all()   
    serializer_class = BookSerializer
    allowed_methods = ['put'] # results in request body not being included
    # allowed_methods = ['test'] # results in a single operation with the `test` verb (shouldn't generate anything)
```

## Expected behavior

```
./manage.py generateschema 
openapi: 3.0.2
info:
  title: ''
  version: TODO
paths:
  /api/books/{id}/:
    put:
      operationId: UpdateBook
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this book.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              required:
              - title
              properties:
                title:
                  type: string
                  maxLength: 200
      responses:
        '200':
          content:
            application/json:
              schema:
                required:
                - title
                properties:
                  title:
                    type: string
                    maxLength: 200
```

## Actual behavior

```
./manage.py generateschema 
openapi: 3.0.2
info:
  title: ''
  version: TODO
paths:
  /api/books/{id}/:
    put:
      operationId: UpdateBook
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this book.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                required:
                - title
                properties:
                  title:
                    type: string
                    maxLength: 200
```

here's another case with `allowed_methods = ['test']`

```
./manage.py generateschema 
openapi: 3.0.2
info:
  title: ''
  version: TODO
paths:
  /api/books/{id}/:
    test:
      operationId: testBook
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this book.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                required:
                - title
                properties:
                  title:
                    type: string
                    maxLength: 200
```

**Comment by carltongibson** [comment]
OK, a couple of little tweaks needed here... 

I suppose 'PUT' works right, so not too bad™, but an `upper()` added somewhere wouldn't hurt... 

Not instantly sure what's going on with the `test` case. (Are custom verbs dis-alllowed?)

**Comment by knivets** [comment]
To begin with, `test` is not a valid HTTP verb. Also OA spec shouldn't include non-existent endpoints (there is no `test` method on a view). Finally, OA code tries to filter verbs that it doesn't support (IIRC those are `options` and `trace`) but I can bypass those checks by using arbitrary lowercased strings.

**Comment by carltongibson** [comment]
“OA”?

**Comment by knivets** [comment]
Sorry OpenAPI 😄

**Comment by carltongibson** [comment]
But when you say “tries to filter” do you mean us, or some other bit of software? 

> I can bypass those checks...

Okay, so we can normalise but this isn’t an adversarial environment so we’re expecting sensible values here to a certain extent.

**Comment by knivets** [comment]
https://github.com/encode/django-rest-framework/blob/master/rest_framework/schemas/generators.py#L143
https://github.com/encode/django-rest-framework/blob/master/rest_framework/schemas/openapi.py#L442

Yeah I didn't mean that it is vulnerable or something, just that it might result in incorrect results for end user.

**Comment by carltongibson** [comment]
OK, no problem. Just trying to get clear myself. 👍

**Comment by carltongibson** [comment]
TBH, I think setting `allowed_methods` directly isn't the intended usage. Rather use [`http_method_names`](https://docs.djangoproject.com/en/2.2/ref/class-based-views/base/#django.views.generic.base.View.http_method_names), which are then normalised to uppercase. 

Setting a method name the view doesn't support strikes me as an error. 

Maybe there's a system check on `View` to be added, but I'm not (as yet) convinced this is stuff the schema generation needs to work around. (???)

**Comment by knivets** [comment]
Yes I’m also not sure where this should be handled. I just stumbled upon this issue while doing OpenAPI testing.

**Comment by fergyfresh** [comment]
@knivets I added a workaround in #6983 for the casing, but I wasn't comfortable handling invalid method names. I feel like that should be a quicker check upfront and maybe throw an exception. Any ideas? Also should I ditch my PR? I added a test for the original intention of this issue, but am not sure how we want to move forward with this.

**Comment by carltongibson** [comment]
Sorry for the silence here. Will be swinging back shortly.

**Comment by fergyfresh** [comment]
No rush, curious to hear your ideas either way.

**Comment by carltongibson** [comment]
OK, I'm going to say no to this one... `http_method_names` is the documented attribute here. (As per the link above.) I don't want to add another blessed path. (That way lies madness.) 

For invalid method names I'm happy with, Don't do that. (At least for now.) 

Thanks both for the input!
