### ISSUE TITLE
There's no support for versioning when it comes to OpenAPI 3 spec generation

### ISSUE THREAD

**Issue by knivets** [encode/django-rest-framework#6882]
Only `URLPathVersioning` works since it requires specifying the parameter manually in a url and inspector knows how to handle these. `NamespaceVersioning` is not relevant since you hardcode the version in the url so there are no parameters here.

I won't include examples for other schemes since it's lot of text to copy paste, but basically we should include appropriate parameters for `QueryParameterVersioning`, `AcceptHeaderVersioning`. Probably generate something in OpenAPI `servers` section for `HostNameVersioning`. 
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Actual behavior

**Comment by carltongibson** [comment]
Yes. Super. This would be a good addition.

**Comment by tomchristie** [comment]
Unlikely we'll be adding further OpenAPI functionality beyond what we've currently got in core.
