### ISSUE TITLE
Model serializer when many=true and the validation fail on one object the whole list not being saved

### ISSUE THREAD

**Issue by Moshikol** [encode/django-rest-framework#6883]
## Checklist

- [* ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [* ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [* ] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [* ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [* ] I have reduced the issue to the simplest possible case.
- [* ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
1. use a model with required fields like:
```
class MyModel(django_models.Model):  
        timestamp = django_models.DateTimeField(unique=True)  
        name = django_models.CharField(max_length=255)
```
2.Add a serializer that supports many instaces like so:  
```
class MyModelSerializer(ModelSerializer):  
    def __init__(self, *args, **kwargs):  
        many = kwargs.pop('many', True)  
        super(MyModelSerializer, self).__init__(many=many, *args, **kwargs)
```  
3.Add an API view and url:
```
class MyModelViewSet(TimeseriesDataModelViewSet):
    serializer_class = MDIInjectionSerializer
    def get_serializer(self, *args, **kwargs):
        data = None
        if "data" in kwargs:
            data = kwargs["data"]
        if isinstance(data, list):
            kwargs["many"] = True

        return super(MyModelViewSet, self).get_serializer(*args, **kwargs)
```
4.Send to the url you added for the view a HTTP POST request with several models like so:
```
{"name": "Test"},
{"timestamp": "2019-08-09T19:53:00","name": "Test"},
{"timestamp": "2019-08-09T19:54:00","name": "Test"},
{"timestamp": "2019-08-09T19:55:00","name": "Test"},
{"timestamp": "2019-08-09T19:56:00","name": "Test"},
{"timestamp": "2019-08-09T19:57:00","name": "Test"}
```
**notice there is no timestamp field in the first object and that would fail the serializer validation.**

## Actual behavior
you would get in the response somthing like:  
```
[
    {
        "timestamp": [
            "This field is required."
        ]
    },
    {},
    {},
    {},
    {},
    {}
]
```
**None of the objects above (even the valid ones) wont be saved to the DataBase**
## Expected behavior
All valid values would get saved to the DataBase, The invalid values would not.

**Comment by carltongibson** [comment]
This is long-standing, expected behaviour. You would be free to implement the behaviour you describe, but that would be out of scope for the issue tracker here. The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!

**Comment by gquittet** [comment]
For those who read this issue, you can use something like this:

```python
class PartialListSerializer(serializers.ListSerializer):
    """
    PartialListSerializer is here to insert only valid data and store invalid ones on
    invalid_data property.
    When you receive 9 valid items and one invalid item, the serializer will insert the
    valid ones and skip the one which is invalid.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.invalid_data = []

    def to_internal_value(self, data):
        try:
            return super().to_internal_value(data)
        except ValidationError as error:
            # ListSerializer raises errors with object and use only the list type for
            # detail when the error is related to the data
            if not isinstance(error.detail, list):
                raise ValidationError from error
        to_return = []
        invalid_data = []
        for index, item in enumerate(data):
            try:
                validated = self.child.run_validation(item)
            except ValidationError as error:
                invalid_data.append(
                    {**error.detail, "extra": {"initial_data": item, "list_index": index}}
                )
            else:
                to_return.append(validated)
        self.invalid_data = invalid_data
        return to_return
```

And use it in your serializer like this:
```python
class MyModelSerializer(ModelSerializer):  
    class Meta:
        list_serializer_class = PartialListSerializer
```
