### ISSUE TITLE
Versioning docs kind of outdated

### ISSUE THREAD

**Issue by knivets** [encode/django-rest-framework#6885]
https://www.django-rest-framework.org/api-guide/versioning/#urlpathversioning 

`URLPathVersioning` and `NamespaceVersioning` examples use [`django.conf.urls`](https://docs.djangoproject.com/en/2.2/ref/urls/#url) implicitly and this function is likely to be deprecated (based on the description in the docs).

I'm opening this issue because I tried copy pasting the code and got an error and spend a couple minutes googling where to import the old style `url` function from. If we can't replace it with `path` we can at least replace it with `re_path`. Let me know which one should I use and I'll open a PR.

**Comment by carltongibson** [comment]
Simplest fix here is just to use `re_path()`. Using `path()` is fine too, but then the URLs will need adjustment/thought. 

(Aside: TBH, I don't think `url()` is going anywhere anytime fast...)
