### ISSUE TITLE
schemas.EndpointEnumerator.get_path_from_regex() doesn't correctly replace kw

### ISSUE THREAD

**Issue by n2ygk** [encode/django-rest-framework#6888]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

```
from rest_framework.schemas.generators import EndpointEnumerator

def test_get_path_from_regex():
    """
    Test that path from regex is correctly formatted.
    """
    path_regex = r'^entries/(?P<pk>[^/.]+)/relationships/(?P<related_field>\w+)'
    expected_path = '/entries/{pk}/relationships/{related_field}'
    enumerator = EndpointEnumerator(patterns={})
    path = enumerator.get_path_from_regex(path_regex)
    assert path == expected_path
```
## Expected behavior

`path == '/entries/{pk}/relationships/{related_field}`

## Actual behavior

`path == 'entries/{pk}/relationships/(P{related_field}\\w+)'`

**Comment by n2ygk** [comment]
Ugh, lack of trailing slash causing this upstream in `django.contrib.admindocs.utils.replace_named_groups`:
```
    path_regex_trailing = path_regex + '/'
    expected_path_trailing = expected_path + '/'
    path_trailing = enumerator.get_path_from_regex(path_regex_trailing)
    assert path_trailing == expected_path_trailing  # succeeds
    assert path == expected_path  # fails
```

**Comment by n2ygk** [comment]
Workaround is to make sure urlpatterns are well-formed with a trailing `/`

**Comment by carltongibson** [comment]
Just before this drops off the radar... Is this something we want to address? (Trailing slashes are conventional in Django-land, but not compulsory...)

**Comment by n2ygk** [comment]
Might be worth submitting upstream. I can do that.

**Comment by carltongibson** [comment]
Super.

**Comment by n2ygk** [comment]
@carltongibson https://github.com/django/django/pull/11728 merged

**Comment by carltongibson** [comment]
Super. Good follow-up @n2ygk. (That’ll be part of Django 3.0)
