### ISSUE TITLE
Bug: RequestsClient always responds 500

### ISSUE THREAD

**Issue by valmack** [encode/django-rest-framework#6900]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

1. Create a RequestsClient object
2. Call the get method on the client object with any url passed in as an argument

```python
from rest_framework.test import APISimpleTestCase, RequestsClient

class LiveTests(APISimpleTestCase):
    
    def test_get_base(self):
        client = RequestsClient()
        response = client.get('http://google.com')
        import pdb; pdb.set_trace()
        assert response.status_code == 200
```

3. Run the test `python manage.py test`

## Expected behavior

An appropriate response status code based on the request, for example, http://google.com should produce something in the 200 range.

## Actual behavior

The response status code is always 500.

<img width="307" alt="pdb_500" src="https://user-images.githubusercontent.com/8445610/63984581-f3c39900-ca99-11e9-8beb-5660d0a2f421.png">

Note that this occurs with or without the pdb debugger. It also occurs whether I use SimpleTestCase from django.test or APISimpleTestCase from rest_framework.test

**Comment by xordoquy** [comment]
I can not reproduce, the test passes.

**Comment by pckrishnadas88** [comment]
still facing the same issue for me as well.
