### ISSUE TITLE
read_only causes hyperlinkedrelatedfield.get_attributes to fail

### ISSUE THREAD

**Issue by GammaSQ** [encode/django-rest-framework#6902]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
create model referencing user, models.py:

    class Case(models.Model):
        usr=models.ForeignKey(User, on_delete=models.CASCADE)

create user serializer referencing model-set, serializers.py:

    class UserSerializer(serializers.HyperlinkedModelSerializer):
        cases = serializers.HyperlinkedRelatedField(view_name='case-detail', many=True, source='case_set.all', read_only=True)

        class Meta:
            model=User
            fields=['id', 'username', 'email', 'cases']
create viewset from serializer, views.py:

    class UserViewset(viewsets.ModelViewSet):
        queryset=User.objects.all()
        serializer_class=UserSerializer

create router from viewset, register urls, ./managepy makemigrations, migrate, runserver, visit user-serializer. Create user. Fails with 

 AttributeError at /users/
 'User' object has no attribute 'case_set'

Problem doesn't exist with read_only=False in serializers for cases-field.

## Expected behavior
independent of read_only, get_attributes should be passed the same object (i.e. model-object). Since the read_only=False option works, I expect the serializer to work in read_only mode as well.

## Actual behavior
field.get_attributes is passed an OrderedDict instance (which seems to be a deserialized object of bound serializer) instead of a model instance when read_only=True.

(I reproduced this bug in a clean django-project with pulled master-branch, but am unsure how to morph this into a testcase, since it requires a lot of setup. Can supply any remaining files as well, if required.)

**Comment by belongwqz** [comment]
same error, what's happend?

**Comment by belongwqz** [comment]
Oh, it's here:[markdown](https://stackoverflow.com/questions/57479412/attributeerror-at-ordereddict-object-has-no-attribute-register-in-django-r)
