### ISSUE TITLE
if get_queryset has side effect, can not use DjangoModelPermissions 

### ISSUE THREAD

**Issue by jun0jang** [encode/django-rest-framework#6905]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Use DjangoModelPermissions on a ViewSet, and execute api call or  pop cache in get_queryset. 

## Expected behavior
if ViewSet has queryset and get_queryset, DjangoModelPermissions use queyset instead call get_queryset.

## Actual behavior
even if Viewset has queryset and get_queryset, DangoModelPermissions call get_queryset.
so that get_queryset is called twice.

**Comment by xordoquy** [comment]
Actually, the behaviour you're seeing is the one expected.
`get_queryset` will be called as it can have much more control of the `queryset` than the property.
Explained in the documentation [here](https://www.django-rest-framework.org/api-guide/generic-views/#get_querysetself)
