### ISSUE TITLE
UniqueTogetherValidator does not handle if attributes with None values are given

### ISSUE THREAD

**Issue by bedilbek** [encode/django-rest-framework#6906]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Let's say we are using UniqueTogetherValidator for Tree-based model:

```python
class Tree(models.Model):
      parent = models.ForeignKey('self', null=True)
      name = models.CharField(max_length=255)


class TreeSerializer(serializers.ModelSerializer):
      class Meta:
            model = Tree
            fields = '__all__'
            validators = [
                 UniqueTogetherValidator(
                        queryset=Tree.objects.all(),
                        fields=('name', 'parent')
                 (
            ]
            extra_kwargs = dict(
                 parent=dict(required=True, allow_null=True)
             )
```
## Expected behavior

As we see, `parent` field is required but can be null, but when serializer is being validated with existing `name` in the database and `parent=None`, validation error should be raised.

## Actual behavior
However, validation error is ignored even if queryset exists according to this code snippet in UniqueTogetherValidator class:
```python
def __call__(self, attrs):
      ...    
     # Ignore validation if any field is None
        checked_values = [
            value for field, value in attrs.items() if field in self.fields
        ]
        if None not in checked_values and qs_exists(queryset):
        ...
```
Thus, in my case, there is `None` value in `checked_values` list and validation error is not being raised.

**Comment by carltongibson** [comment]
This is expected behaviour. Two DB `NULL` values do not equate as equal, so unique_togetherness checks do not work with `None`. 

See also https://code.djangoproject.com/ticket/28545
