### ISSUE TITLE
CharField silently casts input floats to strings, which may change the value representation

### ISSUE THREAD

**Issue by alexgmin** [encode/django-rest-framework#6910]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
```python 
CharField().to_internal_value(0.00001)
```

## Expected behavior
Either a validation error or the returned value being exactly '0.00001'.

## Actual behavior
The returned value is '1e-05' due to float formatting in the cast.

Something similar would also happen with floats with a lot of decimals, since python will not cast into a string with more than 16 decimals.

Being lenient and accepting integers as a valid input for a CharField is fine, but accepting floats causes this problem. 
This is a corner case, but I think it should be a configurable behavior.

I also couldn't find anything documenting this behavior other than the pull request that added it. https://github.com/encode/django-rest-framework/pull/4380

**Comment by tomchristie** [comment]
That's really tricky.

* I don't think there *is* any general way to get "the returned value being exactly '0.00001'", right?
* We've had this behavior in for 3 years now, so starting to treat it as a validation error could easily break existing APIs.

**Comment by Alexgmin** [comment]
> I don't think there _is_ any general way to get "the returned value being exactly '0.00001'", right?

Not to my knowledge. Also, I just thought of another case, what should 10.00 be transformed to? '10.00', '10.0' or '10'?


> We've had this behavior in for 3 years now, so starting to treat it as a validation error could easily break existing APIs.

Maybe, but the solution to this shouldn't be to override the CharField if they want a more sane behavior.
I think casting floats should be deprecated and removed at some point in the future. Adding some new arguments like `accepted_types`, or `allow_integers` and `allow_floats` would allow people to keep the old behavior and ease the transition.

**Comment by carltongibson** [comment]
I kind of think _Meh_ here. This is just computers right? Just _The Perils of Floating Point_, and why the [Python Tutorial](https://docs.python.org/3/tutorial/floatingpoint.html) basically says _Use Decimals!_. 

> ...the solution to this shouldn't be to override the CharField if they want a more sane behavior.

Why not? It would amount to this: 

```
    def to_internal_value(self, data):
        if isinstance(data, float):
            self.fail('invalid')
        return super().to_internal_value(data)
```

Which is pretty minimal compared to adding a kwarg, which whilst fine, exposes API to everyone, that's only relevant to a small number of cases. (How many `CharFields` are accepting `floats` really?)

(That last might be an argument to just _correct™_ the behaviour...)

**Comment by LordGordonQ** [comment]
I found the behaviour of `CharField.to_internal_value` very puzzling to me, especially if the input is a JSON where I don't want to have a number, or other type, automatically casted to `str`. If the Model is expecting a CharField, then the corresponding JSON must be a string. A different type should be considered an error. Or, at least, if you want to silently be more forgiving, this is a decision to be explicitly made by the developer well considering the security impact.

Nevertheless, changing this behaviour will break a lot of endpoints. So, I second @alexgmin proposal to add a parameter to `CharField` to control this behaviour. This allow to make explicit the behaviour in DRF documentation! It took me some headache to find this tricky line of code, since is  not documented anywhere.

@carltongibson Indeed it is very simple to override, but at least it should be documented.

**Comment by tomchristie** [comment]
We could *possibly* support any `allow_cast=True|False`, if someone’s keen and cake up with a decent PR for it.

Otherwise I think we’ve got a pretty reasonable set of behaviour here.
