### ISSUE TITLE
TokenAuthentication provides wrong request.user when multiple users send requests in the meanwhile.

### ISSUE THREAD

**Issue by Mwlm** [encode/django-rest-framework#6911]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
In Django with Gunicorn which has four workers, I use TokenAuthentication. Multiple users send requests to the server in the meanwhile.

## Expected behavior
Users only get data belonging themselves.

## Actual behavior
TokenAuthentication may provide the wrong request.user and request.META, causing some users may get data belonging to one of the users who send requests in the meanwhile. However, I try to send a token to the server with POST, then get the user object by the token instead of request.user. All users can get correct data.

**Comment by xordoquy** [comment]
If the provided `request.META` is incorrect, it is more likely an issue with your stack configuration.
DRF Token and basic auth are using the [HTTP authorisation header](https://github.com/encode/django-rest-framework/blob/master/rest_framework/authentication.py#L20) to authenticate the user.
Unless we have a reproducible use case  on which we can work, there is little we can do.
Closing the issue as it is not actionnable in its current form.
