### ISSUE TITLE
Misleading italian translation

### ISSUE THREAD

**Issue by xrmx** [encode/django-rest-framework#6919]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

~2 months ago I've asked access to the italian team on transifex to fix a couple of wrong translation but I've not been accepted.
The issue is "may not" translated as "could be" and not as "must not" as the code intend. Can someone get me access to transifex / fix it? You can find the correct strings in the diff below.

```
diff --git a/rest_framework/locale/it/LC_MESSAGES/django.po b/rest_framework/locale/it/LC_MESSAGES/django.po
index a48f8645..fc5f3b99 100644
--- a/rest_framework/locale/it/LC_MESSAGES/django.po
+++ b/rest_framework/locale/it/LC_MESSAGES/django.po
@@ -266,7 +266,7 @@ msgstr "Attesa una lista di oggetti ma l'oggetto ricevuto è di tipo \"{input_ty
 
 #: fields.py:1302
 msgid "This selection may not be empty."
-msgstr "Questa selezione potrebbe non essere vuota."
+msgstr "Questa selezione non può essere vuota."
 
 #: fields.py:1339
 msgid "\"{input}\" is not a valid path choice."
@@ -302,7 +302,7 @@ msgstr "Invia un'immagine valida. Il file che hai inviato non era un'immagine o
 
 #: fields.py:1449 relations.py:438 serializers.py:525
 msgid "This list may not be empty."
-msgstr "Questa lista potrebbe non essere vuota."
+msgstr "Questa lista non può essere vuota."
 
 #: fields.py:1502
 msgid "Expected a dictionary of items but got type \"{input_type}\"."
```

**Comment by xrmx** [comment]
Friendly ping :)

**Comment by rpkilby** [comment]
Thanks for the ping @xrmx. I think either @tomchristie or @carltongibson need to give you access, but I'm not entirely sure.

**Comment by xrmx** [comment]
I've just been accepted to the team and updated the italian translation on transifex. This can be closed once translations are updated from transifex again. Thanks!

**Comment by xordoquy** [comment]
Actually, I'm going to close it as it now is on transifex side. Translations should be updated when the next minor release is out.

**Comment by xrmx** [comment]
It looks like translations have not been updated for 3.11. Any chance you can update them now so at least they will be available on the next minor please?

**Comment by tomchristie** [comment]
Ah, my fault sorry. Yup we can make sure to do that.
