### ISSUE TITLE
Data processing in JSONField().to_internal_value()

### ISSUE THREAD

**Issue by bklppr** [encode/django-rest-framework#6932]
Sorry this might be a noob question but it seems to me that the referenced line does not really do anything:

https://github.com/encode/django-rest-framework/blob/89ac0a1c7ef6153312890376ac142674b28b04f1/rest_framework/fields.py#L1781

I would have expected `data = json.dumps(data, cls=self.encoder)`.
Am I missing something here?

**Comment by xordoquy** [comment]
It does validate that `data` is a valid JSON.
This is required because it may come from sources other than JSON.

**Comment by bklppr** [comment]
Thanks for clarifying.
I stumbled upon this because I had a POST request with a dict using single quotes for the keys, e.g. {‘a‘: 3}.
The request works fine but what is stored is not valid JSON because the single quotes are not replaced by double quotes.

**Comment by xordoquy** [comment]
If it doesn't fail here, you probably have a double string encoding meaning you post something like `"{‘a‘: 3}"` instead of an actual `{"a": 3}`
