### ISSUE TITLE
Can we add include_choices to RelatedField?

### ISSUE THREAD

**Issue by arthur-s** [encode/django-rest-framework#6934]
Currently, if I want choices to appear in output, I need to use custom metadata class, overrading `get_field_info`. Can you add `include_choices` option in [RelatedField](https://github.com/encode/django-rest-framework/blob/master/rest_framework/relations.py#L89)?
[related issue](https://github.com/encode/django-rest-framework/issues/3751)

**Comment by rpkilby** [comment]
Hi @arthur-s. Overriding the metadata class is the recommended path here.
