### ISSUE TITLE
Improve docs on many-to-many with through models

### ISSUE THREAD

**Issue by anudeepsamaiya** [encode/django-rest-framework#6936]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

I am interested in improving the doc for many-many fields provided [here](https://www.django-rest-framework.org/api-guide/relations/#manytomanyfields-with-a-through-model), may be make it more detailed and add some example code.

**Comment by rpkilby** [comment]
Hi @anudeepsamaiya. We'd be happy to consider PRs that expand upon the existing docs. Thanks.
