### ISSUE TITLE
Queryset argument is ignored on reverse related fields

### ISSUE THREAD

**Issue by pawelad** [encode/django-rest-framework#6938]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
I believe that the queryset argument on reverse relationships is ignored.

```python
class Competition(models.Model):
    active = models.BooleanField(verbose_name="active")

class Season(models.Model):
    competition = models.ForeignKey(
        verbose_name="competition",
        to=Competition,
        related_name="seasons",
        on_delete=models.PROTECT,
    )


class CompetitionSerializer(serializers.ModelSerializer):
    seasons = serializers.PrimaryKeyRelatedField(
        queryset=Season.objects.filter(active=True),
        many=True,
    )

    class Meta:
        model = Competition
        fields = ["id", "seasons"]
```

## Expected behavior
I'd expect the `CompetitionSerializer.seasons` to only include linked seasons that have `active` set to `True`.

## Actual behavior
I get all the linked seasons.

More importantly, using something like `queryset="foobar"` _doesn't_  result in an error and _still_ returns all linked seasons.

**Comment by pawelad** [comment]
I'm using this as a workaround:

```python
    seasons = serializers.SerializerMethodField()

    def get_seasons(self, obj):
        return Season.objects.filter(competition_id=obj.id, active=True).values_list("id", flat=True)
```

**Comment by pawelad** [comment]
After more debugging and digging in, this is probably (and unfortunately) a duplicate of #1228

**Comment by no-dap** [comment]
Guess this is an usage question.

**Comment by pawelad** [comment]
And the actual long term solution I found that ticks all the boxes:

```python
class CompetitionViewSet(viewsets.ModelViewSet):
    queryset = Competition.objects.prefetch_related(
        Prefetch('seasons', queryset=Season.objects.filter(active=True))
    )
```

Source: https://stackoverflow.com/a/55315566/3023841

Do you guys think it would be worth it to update the docs to say:
- `queryset` argument is ignored on reverse relationships
- the above is the suggested way of filtering reverse relationships

I can try and do the PR.

**Comment by no-dap** [comment]
As docs said, [queryset argument](https://www.django-rest-framework.org/api-guide/relations/#primarykeyrelatedfield) used for model instance lookups when validating the field input, not for filtering.  
Wouldn't this change makes people confused?  
I think this is just a good stackoverflow answer, not a good documentation :)

**Comment by pawelad** [comment]
I think this kinda of question [comes][1] [up][2] [quite][3] [often][4] so could be touched on in the docs more, but I absolutely understand your point.

Thanks for chiming in, I appreciate it a lot!

[1]: https://stackoverflow.com/questions/18625805/djangorestframework-filtering-in-a-related-field
[2]: https://stackoverflow.com/questions/28309507/django-rest-framework-filtering-for-serializer-field
[3]: https://stackoverflow.com/questions/28688275/how-to-expose-a-filtered-reverse-relationship-in-django-rest-api-framework
[4]: https://stackoverflow.com/questions/42202945/filtering-a-reverse-relationship-by-user-and-returning-only-one-object-in-djang
