### ISSUE TITLE
KeyError: 'required' in openapi.py

### ISSUE THREAD

**Issue by FeroxTL** [encode/django-rest-framework#6941]
## Checklist

- [yes] I have verified that that issue exists against the `master` branch of Django REST framework.
- [yes] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [yes] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [yes] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [yes] I have reduced the issue to the simplest possible case.
- [no] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

* Create serializer that has no required fields
* Try to generate openapi docs for it

## Expected behavior

Docs are generated

## Actual behavior
KeyError: 'required'

`rest_framework.schemas.openapi.AutoSchema._get_request_body` has code:

```
        # No required fields for PATCH
        if method == 'PATCH':
            del content['required']
```

But key `required` is generated by `rest_framework.schemas.openapi.AutoSchema._map_serializer`:

```
        if len(required) > 0:
            result['required'] = required
```

So if there is no required fields in serializer KeyError will be raised. I think _get_request_body should handle deletion in this way:

```
        # No required fields for PATCH
        if method == 'PATCH and 'required' in content:
            del content['required']
```

**Comment by carltongibson** [comment]
Yep, looks vaild at first glance. 

If you could put a test case together show how it comes up, that would be super. Very happy to accept a PR! 

Thanks for the report! 👍

**Comment by ron8mcr** [comment]
Looks like there are related PRs already: #6944  and #6920

**Comment by guimunarolo** [comment]
> Yep, looks vaild at first glance.
> 
> If you could put a test case together show how it comes up, that would be super. Very happy to accept a PR!
> 
> Thanks for the report! 👍

hey @carltongibson! my PR has the test case and solve the issue 😉

**Comment by rnegron** [comment]
Am having this issue as well!

**Comment by DataGreed** [comment]
@helrond is this included in any of the releases?

**Comment by DataGreed** [comment]
i still have this issue on 3.10.3

**Comment by guimunarolo** [comment]
> i still have this issue on 3.10.3

you can fix this specifying the schema `"DEFAULT_SCHEMA_CLASS": "rest_framework.schemas.coreapi.AutoSchema"`

**Comment by DataGreed** [comment]
@guimunarolo thanks!

Is there a reason it's not fixed in the default autoschema generator? 
And is there a reason for `openapi.AutoSchema` to exist? Is it different from `coreapi.AutoSchema`?

**Comment by DataGreed** [comment]
The problem is that I've already subclassed `openapi.AutoSchema` as the docs suggested and provided my implementations for some of the methods. I really don't understand why both of these classes exist and whichever should be used in what case

**Comment by DataGreed** [comment]
@guimunarolo nope, changing the schema class and even specifying it on per-class bases for ViewSets didn't fix the problem.

I get `type object 'AutoSchema' has no attribute 'get_operation'`  at `.env/lib/python3.7/site-packages/rest_framework/schemas/openapi.py in get_paths, line 47`

I guess DRF still uses openapi somewhere in its internals

**Comment by DataGreed** [comment]
Okay, it got even more confusing as [v3.10](https://www.django-rest-framework.org/community/3.10-announcement/) says that `coreapi` is basically deprecated and we should use `openapi` that still has a bug. Is it scheduled to be fixed and released?
