### ISSUE TITLE
Debug=True causes DRF to try to honor "Accept" header

### ISSUE THREAD

**Issue by lapinvert** [encode/django-rest-framework#6943]
In very short, when an API endpoint is requested from some frontend that happens to include header such as `Accept  text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8` (which is the case of firefox 48 for example), then the DRF endpoint answers by HTML instead of JSON. This `Accept` header is ignored when Debug=False, but this happens when set to True)

I am not sure it's actually an issue or is it intended behavior. One thing for sure is that it breaks everything during the time you forgot to set debug to False again. I don't see a reason why it should take this `Accept` header into account anyway. What do you think?

**Comment by rpkilby** [comment]
Hi @lapinvert. I would recommend reading [how the renderer is determined](https://www.django-rest-framework.org/api-guide/renderers/#how-the-renderer-is-determined) and then checking your settings. My guess here is that when `DEBUG` is enabled, the `BrowsableAPIRenderer` is inserted into the default list of renderers, and is left out when `DEBUG` is disabled.

**Comment by lapinvert** [comment]
Thanks @rpkilby for you reply. Actually `BrowsableAPIRenderer` is always included regardless of `DEBUG` settings. Another thing I noticed is that it was happening only on file upload (multiform data) endpoints. But I have `swagger_rest_framework` installed so maybe thats also related, as the HTML page that was showing instead of JSON was swagger doc.
