### ISSUE TITLE
Generic Viewset overrides passed serializer's context with the default value 

### ISSUE THREAD

**Issue by Olerdrive** [encode/django-rest-framework#6955]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Imagine any simple ModelVieset with a Serializer like the following which somehow uses provided context to enrich data:

```
class SimpleSerializer(serializers.Serializer):
    value = serializer.CharField()

    def validate(self, attrs):
        if not attrs.get("value"):
            attrs["value"] = self.context["context_key"]
        return attrs


class SimpleViewSet(ModelViewSet):
    queryset = Model.objects.all()
    serializer_class = SimpleSerializer

    @action(methods=['POST'], detail=False)
    def simple_action(self, request):
        serializer = self.get_serializer(data=request.data, context={"context_key": "value"}
        serializer.is_valid(raise_exception=True)
        return Response(data=serializer.validated_data, status=status.HTTP_200_OK)


```
## Expected behavior
Accessing `simple_action` handler works correctly and passed `context_key` key exists in the serializer's context

## Actual behavior
The code will fail with a `KeyError` as follows:
```
...
...
...
    attrs["value"] = self.context["context_key"]
KeyError: 'context_key'
```

That happens because of generic Viewset's `get_serializer` method which simply overrides any provided `context` kwarg with the default context from `get_serializer_context`.

**Comment by rpkilby** [comment]
Closing per #6956
