### ISSUE TITLE
latest documentation for offline use 

### ISSUE THREAD

**Issue by NegassaB** [encode/django-rest-framework#6962]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] I have reduced the issue to the simplest possible case.

**Comment by xordoquy** [comment]
The generation of documentation is explained [here](https://www.django-rest-framework.org/community/contributing/#building-the-documentation).
You should be able to generate it from a tag checkout.
