### ISSUE TITLE
Serializers: Unexpected behaviour of serializers.BooleanField with django's QueryDict

### ISSUE THREAD

**Issue by Ivo-Donchev** [encode/django-rest-framework#6969]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

1. Implement serializer with a Boolean non required field
2. Pass empty `django.http.QueryDict` (request.GET, request.POST, request.query_params, ...)
3. Validate the serializer
4. Get `serializer.validated_data`

```
from rest_framework.serializers import Serializer, BooleanField
from django.http import QueryDict

class SomeSerializer(Serializer):
    some_boolean = BooleanField(required=False)

empty_data = QueryDict()
serializer = SomeSerializer(data=empty_data)
serializer.is_valid()


assert 'some_boolean' not in serializer.validated_data  # Should not be part of the validated_data
```

## Expected behavior
The `serializers.validated_data` should NOT include fields that are not passed in the data (and don't have default values).

From the example above: `serializer.validated_data` should be empty

## Actual behavior
`serializer.validated_data` contains key that's not part of the data (non-required BooleanField without default) 

From the example above: `serializer.validated_data` contains non-provided `some_boolean`

**Comment by xordoquy** [comment]
This is a side effect of the specification of the checkbox. From the html specification:

> Checkboxes (and radio buttons) are on/off switches that may be toggled by the user. A switch is "on" when the control element's checked attribute is set. When a form is submitted, only "on" checkbox controls can become successful.

Therefore, missing values for checkbox are equivalent to a False value which makes it an implicit default.
Since you are using a `QueryDict` - as opposed as a regular dict - it conveys the meaning that comes from an HTML form and thus apply the implicit default.
This should not happen with a regular dictionary.

**Comment by Ivo-Donchev** [comment]
Hi @xordoquy

What about passing boolean GET parameters to a plain rest framework APIView and validating it into a serializer :thinking: 

Is there another way to define non-required BooleanField without getting `False` default value  ?

**Comment by xordoquy** [comment]
As far as I can tell it'll be the same.

- `/myurl/?test` -> `test=True`
- `/myurl/?` -> `test=False`

**Comment by Ivo-Donchev** [comment]
Hmm :( 

We tried using the `NullBooleanField` and it actually solves the problem.

But the the problem is that `null` is a valid choice for this field (which is the proper behaviour or the NullBooleanField... :smile: )

It was an interesting experience to debug a List API with filters (get parameters) that filter by falsy boolean instead of just skipping the filter if it's not provided :confused: 

Anyway..
@xordoquy Thank you for the quick response. :slightly_smiling_face:

**Comment by Ivo-Donchev** [comment]
@xordoquy Please can we add this somewhere in the documentation? (I looked there but I couldn't find it)

**Comment by xordoquy** [comment]
Not sure what you want to add.
The [BooleanField](https://www.django-rest-framework.org/api-guide/fields/#booleanfield) documentation should be enough.
