### ISSUE TITLE
Inheriting serializer fields

### ISSUE THREAD

**Issue by aryabartar** [encode/django-rest-framework#6970]
I came up with the exact same problem in #2418 issue
My DRF version is 3.9.4 but I can't inherit serializer fields in subclass and I have to redefine that field in each subclass.
I think this problem was fixed in #2388 issue but now I'm facing it.

**Comment by xordoquy** [comment]
As I understand #2388 it was not fixed but waiting for a PR with a failing test case to understand the issue.
I'm closing this issue for the same reason. The next step is to come with a failing test case pull request.
