### ISSUE TITLE
ASGI compatibiity

### ISSUE THREAD

**Issue by auvipy** [encode/django-rest-framework#6971]
As Django 3.0 supports basic async capabilities maybe it is time for drf as well?

**Comment by carltongibson** [comment]
Django’s ASGIHandler allows serving any Django application from an ASGI server. That already includes DRF. (There’s nothing really async about it at this stage.) 

As async views appear in Django, looking at 3.1, generic async view would be an appropriate addition. But let’s not jump the gun.
