### ISSUE TITLE
OpenAPI 3.0 should generate and reference #/components/schemas/

### ISSUE THREAD

**Issue by partimer** [encode/django-rest-framework#6984]
## Checklist

- [X ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X ] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [X ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [ X] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Swagger 2.0 supports the concept of a definition #/definitions/{ModelName}.  This is superseded in OpenAPI 3.0 with #/components/schemas/{ModelName}

## Expected behavior
1. OpenAPI 3.0 output should contain  #/components/schemas/{ModelName}
2. Each schemas should minimally contain the same type of information found in Swagger 2.0 definitions.
3. Optionally, #/paths/... can reference #/components/schemas/{ModelName} rather than a full definition
4. #/components/schemas/{ModelName} should include "title" and format="uri"

## Actual behavior
1. #/components/schemas is not generated.
2. Information has to be scoured from the #/paths/...
3. Some Information found in Swagger 2.0 definitions such as string format information is not present in any equivalent form.
4. Information in i.e. #/paths.../properties/schemas is often duplicated (bigger schema file)

**Comment by carltongibson** [comment]
Yes. This would be a great a addition. A super contributing opportunity!

**Comment by partimer** [comment]
Is the following considered a supported DRF use case?
Use Case:  Javascript client using drf-yasg generated Swagger 2.0, utilizing #/definitions to define client side object, migrates to drf generated OpenAPI3.0.

**Comment by carltongibson** [comment]
Not "supported" no. 🙂 We'd need logic to go from serializers/models to component definitions, and then operations would need to reference those.

**Comment by n2ygk** [comment]
I started implementing this over here: https://github.com/django-json-api/django-rest-framework-json-api/pull/689. I've been sort of on hold with this, with feedback being some of the stuff I did would best be implemented upstream here. However, I've been busy with other stuff at work lately. Feel free to use anything useful you see there. Most of the relevant code is in [openapi.py](https://github.com/django-json-api/django-rest-framework-json-api/blob/18c677b012595c07a23cf1376a54e2db086c4977/rest_framework_json_api/schemas/openapi.py)

**Comment by carltongibson** [comment]
Super. Good stuff @n2ygk! Thanks for your efforts.

**Comment by bo0tzz** [comment]
I'd love to have this feature. @n2ygk you mentioned that you were working on an implementation for this over in another project. Do you have an idea of the efforts needed to get that code back into drf? Hopefully I'd be able to dedicate some time to this.

**Comment by gnuletik** [comment]
I just made a PR for this issue. It's working without issue on our large codebase. Feel free to give it a try ;)
