### ISSUE TITLE
For create() fields should be ommittable

### ISSUE THREAD

**Issue by raphet** [encode/django-rest-framework#6985]
There is a case to make, that the DB is responsible for writing current timestamps and not the API.
It is common to see DB fields like:
creation TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP

DRF doesn't appear to provide any way to avoid sending a NULL field in such a POST (INSERT) call using its serializer with create().
Consequently the DB ruleset (NOT NULL) is violated. 

Clearly, auto_now_add=True can be used but it defeats the purpose of letting the DB set the TIMESTAMP upon real record creation time, not at DRF API sending time.

In essence this request asks for a way to alter creation requests from
INSERT INTO t (name, creation) VALUES ("name", NULL) to
INSERT INTO t (name) VALUES ("name").
This way, the DB can take care of setting the correct timestamp.

**Comment by rpkilby** [comment]
Hi @raphet. It's not really possible to give specific advice without knowing how your serializer is setup. That said, it sounds like what you want to do is make the field readonly. 

I know this isn't a `ModelSerializer`, but it's a quick example to show you that readonly fields aren't included in the `validated_data`.

```python
>>> class S(serializers.Serializer): 
>>>     d = serializers.DateTimeField(read_only=True) 
>>>     f = serializers.CharField() 
>>>
>>> s = S(data={'d': '2019-10-11T03:08:03.201326', 'f': 'foo'})                
>>> s.is_valid()                                                               
True
>>> s.validated_data                                                           
OrderedDict([('f', 'foo')])
```

And here, you can see that the `create` method only writes validated data.
https://github.com/encode/django-rest-framework/blob/0fd72f17ee18506c02b4c0f0e4af368e3bedac3e/rest_framework/serializers.py#L944

----

If you need further [help](http://www.django-rest-framework.org/#support), I'd recommend asking in the discussion group.

**Comment by xordoquy** [comment]
If this is linked with the chat we had on IRC, one needs to check if Django is able to create a model while omitting some field. Asking on the Django user mailing list would be a good start t point

**Comment by rpkilby** [comment]
Either way, DRF is capable of omitting the field from the `validated_data`, so this is more a question of what the ORM can do. iirc, there is no trivial builtin way to leverage the database to generate timestamps, but there should be 3rd party packages out there that will generate the proper schema.
