### ISSUE TITLE
DeprecationWarning generated from importing APIClient

### ISSUE THREAD

**Issue by johnthagen** [encode/django-rest-framework#6991]
Python 3.8 releases today but this warning is still triggered from `djangorestframework` 3.10.3:

https://github.com/tomchristie/itypes/issues/11

This makes causes users who run their testing with `-Werror` fail the build.

From: https://docs.python.org/3/library/collections.html#module-collections

> Deprecated since version 3.3, will be removed in version 3.9: Moved Collections Abstract Base Classes to the collections.abc module.

##  Steps to reproduce

```py
from rest_framework.test import APIClient
```

Run `pytest` tests with`-Werror` under Python 3.7.

```
$ python3 -Werror -m pytest
```

```
During handling of the above exception, another exception occurred:
.tox/docker/lib/python3.7/site-packages/_pytest/config/__init__.py:462: in _importconftest
    mod = conftestpath.pyimport()
.tox/docker/lib/python3.7/site-packages/py/_path/local.py:701: in pyimport
    __import__(modname)
<frozen importlib._bootstrap>:983: in _find_and_load
    ???
<frozen importlib._bootstrap>:967: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:677: in _load_unlocked
    ???
.tox/docker/lib/python3.7/site-packages/_pytest/assertion/rewrite.py:142: in exec_module
    exec(co, module.__dict__)
rest_api/tests/conftest.py:2: in <module>
    from rest_framework.test import APIClient
.tox/docker/lib/python3.7/site-packages/rest_framework/test.py:16: in <module>
    from rest_framework.compat import coreapi, requests
.tox/docker/lib/python3.7/site-packages/rest_framework/compat.py:98: in <module>
    import coreapi
.tox/docker/lib/python3.7/site-packages/coreapi/__init__.py:2: in <module>
    from coreapi import auth, codecs, exceptions, transports, utils
.tox/docker/lib/python3.7/site-packages/coreapi/codecs/__init__.py:2: in <module>
    from coreapi.codecs.base import BaseCodec
.tox/docker/lib/python3.7/site-packages/coreapi/codecs/base.py:1: in <module>
    import itypes
.tox/docker/lib/python3.7/site-packages/itypes.py:2: in <module>
    from collections import Mapping, Sequence
<frozen importlib._bootstrap>:1032: in _handle_fromlist
    ???
.tox/docker/lib/python3.7/collections/__init__.py:52: in __getattr__
    DeprecationWarning, stacklevel=2)
E   DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
````

**Comment by johnthagen** [comment]
Stack trace links from GitHub:

https://github.com/encode/django-rest-framework/blob/3aa1089a6af6774c1e0b12977b85062f837998ca/rest_framework/compat.py#L98

- https://github.com/core-api/python-client/blob/master/coreapi/codecs/base.py#L1
- https://github.com/tomchristie/itypes/blob/master/itypes.py#L2

**Comment by rpkilby** [comment]
Hm. I'm not really sure what should be done here. On the one hand, coreapi and itypes have been archived and are no longer supported. Any kind of compat issue will not be able to be fixed. However, the 3.10 announcement states:

> You'll still be able to keep using CoreAPI schemas, API docs, and client for the foreseeable future. We'll aim to ensure that the CoreAPI schema generator remains available as a third party package, even once it has eventually been removed from REST framework, scheduled for version 3.12.

Continuing to support this as a third party package seems non-viable, unless it's limited to older versions of DRF & Python. 

Also, worth noting that coreapi schemas don't raise `RemovedInDRF312Warning`. cc @carltongibson

**Comment by carltongibson** [comment]
Yes, the warning should be in place. 

We’ll not fix this. But it’ll continue to work for the now. Ultimately we don’t want to break it but we don’t have the capacity to keep it maintained for future versions.

**Comment by johnthagen** [comment]
So the plan would be that DRF 3.12 will release [before Python 3.9](https://www.python.org/dev/peps/pep-0596/) (since it will break DRF on Python 3.9)?

This does mean that DRF will no longer work on Python master (https://docs.python.org/3.9/whatsnew/changelog.html#id4). I don't know how many people try to test their code on master with CI, but I do know that is not an uncommon occurrence.

Since this change is trivial (one line):

```py
from collections.abc import Mapping, Sequence
```

Would the DRF team consider fixing this one line in an `itypes` release so that DRF works on Python master?

**Comment by carltongibson** [comment]
> Would the DRF team consider fixing this one line ....

I'd say not. (Since one fix leads to another.) 

> ...since it will break DRF ...

DRF will continue to work, since you're not obliged to install CoreAPI. 

Alas, CoreAPI is no longer supported, but I'm afraid that means it's no longer supported. 

If you **must** be using both CoreAPI and Python 3.9 the day it's released, I suggest forking itypes  and adding the fix there, using pip's VCS support to install your fork. 

I can't see how this is anything other than wontfix. (I appreciate that's suboptimal for you.)

**Comment by johnthagen** [comment]
@carltongibson 

> since you're not obliged to install CoreAPI.

Thanks for pointing this out. I did some digging and it is required by [`drf-yasg`](https://github.com/axnsan12/drf-yasg/blob/master/requirements/base.txt#L1), so in my case I can't opt out of it.

I'll try to open an issue over there to see what it would take for them to drop `coreapi`.

**Comment by johnthagen** [comment]
For anyone else that hits this, a temporary work-around is:

```bash
$ python3 -Werror -Wignore:::itypes -m pytest
```

**Comment by johnthagen** [comment]
For anyone else tracking this, it looks like [`itypes` has a new maintainer](https://github.com/PavanTatikonda/itypes) (@PavanTatikonda) and this particular issue has been fixed and released onto PyPI.

https://github.com/PavanTatikonda/itypes/commit/e9b32979d1eaefc3c08780de496a20520fa677cd

@PavanTatikonda, if you happen to see this, if you could set the repo to non-archived that would allow people to open issues and PRs to it again.
