### ISSUE TITLE
OpenAPI AutoSchema manual_fields

### ISSUE THREAD

**Issue by illing2005** [encode/django-rest-framework#6992]
The `AutoSchema` class for OpenAPI does not have a `get_manual_fields` method like coreapi implementation used to have it. 
What is the best practive of adding manual fields to a schema?

**Comment by carltongibson** [comment]
When you say "manual fields", what do you want to add?

**Comment by illing2005** [comment]
Let's say I have a `APIView` that does not use any serializer or filters, but requires a parameter `foo`.
`AutoSchema` can't discover this parameter and I want to add it manually to the schema:

```
class MyView(APIView):
    def get(self, request):
        # how can I tell AutoSchema to add foo to the schema?
        foo = request.query_params.get("foo")
        ...

```

**Comment by carltongibson** [comment]
Define an AutoSchema subclass and add the parameter in `get_operation()`. 

Something like:

```python
from rest_framework.schemas.openapi import AutoSchema

class CustomeSchema(AutoSchema):
    def get_operation(self, path, method):
        op = super().get_operation(path, method)
        operation['parameters'].append({
            "name": "foo",
            "in": "query",
            "required": True,
            "description": "What foo does...",
            'schema': {'type': 'string'}
        )
        return op
```

Should do you.

**Comment by illing2005** [comment]
Thanks!
Is there any reason why this feature is not available in `AutoSchema`?
It seems like very common use case to me

**Comment by carltongibson** [comment]
More or less, the two lines saved aren't, on balance worth the extra API surface area. Just subclass.
