### ISSUE TITLE
Use the same HTTP method with two different actions in DRF

### ISSUE THREAD

**Issue by oussama-he** [encode/django-rest-framework#6994]
I'm building an app using VueJS and Django with Django Rest Framework. I would like to ask how can I use the same HTTP method with two different functions (methods) in a viewset.

Thank you in advance.

**Comment by xordoquy** [comment]
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
