### ISSUE TITLE
Coreapi slow performance

### ISSUE THREAD

**Issue by chinochao** [encode/django-rest-framework#6998]
I currently have Coreapi in DRF 3.10.1 and it seems to be having some performance issues. 

django-auth-ldap==2.0.0
django-crispy-forms==1.7.2
django-dbbackup==3.2.0
django-extensions==2.0.7
django-filter==2.2.0
django-queryset-csv==1.0.1
djangorestframework==3.10.1
djangorestframework-filters==1.0.0.dev0
django-redis
dnspython
gevent
gunicorn[gevent]
requests
pyaml
python-ldap
py-dateutil
psycopg2
coreapi

When I include the API documentation it seems to take over 15 seconds for the page to load.

    url(r'^api/docs/', include_docs_urls(title='API Documentation', schema_url='/', public=False)),

Are there any other performance issues that others have noticed?

**Comment by carltongibson** [comment]
HI @chinochao. Almost certainly you've some model with a foreign key (giving choices) with **a lot™** of values. You need to work out what that is, and then adjust the serializer (?) to not generate every choice. 

I'm going to close, as this is more a support channel thing, than an issue per se.
