### ISSUE TITLE
drf.Request.content_type does not match django.Request.content_type

### ISSUE THREAD

**Issue by apollo13** [encode/django-rest-framework#7000]
## Steps to reproduce

Add this to any DRF view:
```
        print(
            type(request),
            type(request._request),
            repr(request.content_type),
            repr(request._request.content_type),
        )
```

## Expected behavior

```
<class 'rest_framework.request.Request'>
<class 'django.core.handlers.wsgi.WSGIRequest'>
'application/xml'
'application/xml'
```

## Actual behavior

```
<class 'rest_framework.request.Request'>
<class 'django.core.handlers.wsgi.WSGIRequest'>
'application/xml; charset=iso-8859-1'
'application/xml'
```

I'd argue that the content-type handling in DRF should follow Django, especially since `content_params` provides the rest of the information.

**Comment by xordoquy** [comment]
Fair enough.
Seems this is old code prior to Django handling `content_type` (https://github.com/django/django/commit/6f1318734f0f3b6e62b782b0251a4e676e542e0b#diff-0eb6c5000a61126731553169fddb306eR64)

**Comment by apollo13** [comment]
Mhm, if the code is that old, it might make changing hard. I guess there are quite a few locations in drf relying on the `content-type` to be as is.

**Comment by tomchristie** [comment]
Since this hasn't been bumped in over a year, let's close it off as insufficient priority for now.
