### ISSUE TITLE
DecimalField.to_internal_value raises InvalidOperation for 'sNaN' value

### ISSUE THREAD

**Issue by bizywizy** [encode/django-rest-framework#7001]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
```python
from rest_framework import serializers
serializers.DecimalField(1, 1).to_internal_value('snan')
```
## Expected behavior
Raises `rest_framework.serializers.ValidationError` with message `A valid number is required.` like for a 'nan' value.
## Actual behavior
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/rest_framework/fields.py", line 1067, in to_internal_value
    if value != value:
decimal.InvalidOperation: [<class 'decimal.InvalidOperation'>]
```

**Comment by rpkilby** [comment]
Closed by #7002.
