### ISSUE TITLE
CoreAPI schemas not raising RemovedInDRF317Warning

### ISSUE THREAD

**Issue by rpkilby** [encode/django-rest-framework#7007]
From #6991, CoreAPI schemas should raise `RemovedInDRF312Warning`s. Currently, the deprecation is only documented in the 3.10 release notes.

**Comment by carltongibson** [comment]
Yep, I never added the warnings. Wanted to give folks more time. I think I'll add for 3.12. (So `RemovedInDRF314Warning`)

**Comment by auvipy** [comment]
this should be now raising removed in 317 warning?
