### ISSUE TITLE
authentication_classes don't work

### ISSUE THREAD

**Issue by dongwenda** [encode/django-rest-framework#7011]
## Steps to reproduce
Django 2.2.6
drf 3.10.3
```
class UserViewSet(mixins.RetrieveModelMixin, mixins.ListModelMixin, viewsets.GenericViewSet):
    authentication_classes = [BasicAuthentication, SessionAuthentication]
    queryset = user_model.objects.all()
    serializer_class = UserUpdateSerializer
```
## Expected behavior
no login, no access the api
## Actual behavior
but why no login,  I can also access the api

**Comment by xordoquy** [comment]
Authentication will not deny you access. That's the permissions' goal.
