### ISSUE TITLE
OpenApi AutoSchema inspection produces invalid type `null` on ArrayField(base_field=ChoicesField())

### ISSUE THREAD

**Issue by meteozond** [encode/django-rest-framework#7023]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

Create array field with base_field provided choices:

```python
class A(Model):
	field = ArrayField(base_field=CharField(max_length=256, choices=(1,2,3)))
```

## Expected behavior

```js
properties: {field: {
	type: array
	items: {
		enum: [1, 2, 3]
		type: "string"
	}
}}
```

or

```js
properties: {field: {
	type: array
	items: {
		enum: [1, 2, 3]
	}
}}
```

## Actual behavior

```js
properties: {
field: {
	type: array
	items: {
		type: null
	}
}}
```

## Note

Looks like choice field processing produces `{enum}`
https://github.com/encode/django-rest-framework/blob/master/rest_framework/schemas/openapi.py#L256

But list field expects `type` (`self._map_field(field.child).get('type')`)
https://github.com/encode/django-rest-framework/blob/master/rest_framework/schemas/openapi.py#L269

**Comment by luchiago** [comment]
Can I work on this issue?

**Comment by dhaval-mehta** [comment]
I have same issue. I would like to fix this issue.
