### ISSUE TITLE
Problematic greek translation

### ISSUE THREAD

**Issue by panpavlidis** [encode/django-rest-framework#7031]
https://github.com/encode/django-rest-framework/blob/ab40b80fa64d0448cdfbe9125a77bae39085d3f5/rest_framework/locale/el/LC_MESSAGES/django.po#L128

this should be like `msgstr "Η μέθοδος \"{method}\" δεν επιτρέπεται." `

**Comment by rpkilby** [comment]
Hi @panpavlidis. We manage translations with [transifex](https://www.django-rest-framework.org/topics/internationalization/#adding-new-translations). You'll need to submit the translations there. Thanks!

**Comment by panpavlidis** [comment]
> Hi @panpavlidis. We manage translations with [transifex](https://www.django-rest-framework.org/topics/internationalization/#adding-new-translations). You'll need to submit the translations there. Thanks!

hello @rpkilby , i've submitted the translation fix in transifex, so i guess this issue can be closed when you re-integrate translations

**Comment by rpkilby** [comment]
Thanks!
