### ISSUE TITLE
when custom a pagenation class: UnorderedObjectListWarning

### ISSUE THREAD

**Issue by HiveMe** [encode/django-rest-framework#7035]
i am confused,when using 
`   'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 2,`
in settings,there is not warning.however,when i change to my custom pagination class,this warning shows.here is my custom warning class
`class StandardResultsSetPagination(PageNumberPagination):
    page_size = 10
    page_query_param = 'pageNo'
    page_size_query_param = 'pageSize'
    max_page_size = 100`

**Comment by xordoquy** [comment]
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
