### ISSUE TITLE
Permission also need code property

### ISSUE THREAD

**Issue by jun0jang** [encode/django-rest-framework#7038]
## Checklist

- [v ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [ v] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [v] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [v] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [v] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

as you know, each permission_denied is not the same.
and maybe each permission_denied require different behavior.
so, DRF enables override the message of Permission.
but, when communicating with clients that are independent of Django. 
(like SPA, Android, IOS)
i think code is better than a message.   
because error handling is the client's responsibility.
so, Permission also needs to override code property.

**Comment by tomchristie** [comment]
I think we'd probably consider a pull request adding support for an optional `code` associated with permissions, yup.

**Comment by diox** [comment]
Hi,

I needed this to distinguish between different 403 responses returned from permission failures, so I came up with this patch: https://github.com/encode/django-rest-framework/pull/7306 (includes docs & tests)
