### ISSUE TITLE
can the field name  of ModelSerializers's  foreign key  be consistent with Django Model's Practice

### ISSUE THREAD

**Issue by wyh** [encode/django-rest-framework#7044]
### **Models:**
```

class Word(models.Model):
       word = models.CharField(max_legnth=128)

Class Example(serializers.ModelSerialzer):
       word = models.ForeignKey(Word, related_name='examples', on_delete=models.CASCADE)
       example = models.CharField(max_length=2049, default='')

```

### **Serializers:**

```

class ExampleSerializer(serializers.ModelSerializer):                                 
       class Meta:                                                                    
            model = Example                                                              
            fields = ( 'id', 'word',  'sentence', 'translation')

class WordSerializer(serializers.ModelSerializer):                                 
           examples  = ExampleSerializer(many=True)                                        
                                                                                   
       class Meta:                                                                    
            model = Word                                                               
            fields = ( 'id', 'word',  'examples')

```

Usually, we call `example.word_id` in Django, but in DRF，serialized json (both input and output) should be named as  `{"word": 123}` , which is not consistent with Django practice. 

The field name `word` should be reserved for django  `word` instance, and `word_id` could be used as the primary key indicator. 

Thanks.

**Comment by tomchristie** [comment]
There's no way we'd be able to change this as it'd break the API for all existing deployments.
It's also not at all clear cut - API representations shouldn't overly reflect the underlying framework with which they're built, and this style also allows *either* PK or URL styles of representation to be used without different key naming styles for each case. (Would we expect `word: <URL>`, or `word_url: <URL>` or something else?)

If you need to customize things you'll want to define the serializer fields explicitly.
I think the following example is probably about right for what you want.

`word_id = serializers.PrimaryKeyRelatedField(source="word")`
