### ISSUE TITLE
Persian Tralslation

### ISSUE THREAD

**Issue by zarinpy** [encode/django-rest-framework#7048]
Hi I just want to add Persian translation on Transifex but it takes time to approve my commits.

may I send my translation on merge request ?

I really need it on a project and I dont want install it from my fork

**Comment by xordoquy** [comment]
Hi,

We don't accept translations pull requests.
I just accepted your requests on Transifex.

**Comment by zarinpy** [comment]
@xordoquy thanks.

**Comment by altostratous** [comment]
> Hi I just want to add Persian translation on Transifex but it takes time to approve my commits.
> 
> may I send my translation on merge request ?
> 
> I really need it on a project and I dont want install it from my fork

Hey, I know that you can add your translations like it is described [here](https://www.django-rest-framework.org/topics/internationalization/#adding-new-translations) locally for your own project.

Can you share your translations in a django project or a repo or at least a zip somewhere for the sake of Persian speakers all around the world? @zarinpy
