### ISSUE TITLE
serializer field `read_only` and `default` bug

### ISSUE THREAD

**Issue by xuxinwen** [encode/django-rest-framework#7055]
In `ModelSerializer` i have this config
```
extra_kwargs = {
            'update_by': {'default': CurrentUserNameDefault()}
}
read_only_fields = ('update_by',)
```
`update_by` is my model field, I want it to be set by backend, so i set it to `read_ony` and `default` .
But `default` do not work.
So , i read the source code
In `djangorestframework==3.6.2`  rest_framework/serializers.py  I find 
```
@cached_property
def _writable_fields(self):
    return [
        field for field in self.fields.values()
        if (not field.read_only) or (field.default is not empty)
    ]
```

But in `djangorestframework==3.10.3`   rest_framework/serializers.py  I find 

```
    @property
    def _writable_fields(self):
        for field in self.fields.values():
            if not field.read_only:
                yield field
```

**Comment by tomchristie** [comment]
Closing as per #7054

**Comment by carltongibson** [comment]
I think you probably want to read [Altered the behaviour of `read_only` plus `default` on Field.](https://www.django-rest-framework.org/community/3.8-announcement/#altered-the-behaviour-of-read_only-plus-default-on-field) from the 3.8 release announcement. 

There's a long history here, that you can follow from the linked issue but, tl;dr the old behaviour cloaked a very tricky bug when using dotted values as a field `source` and it was necessary to alter it. 

As per the notice in the release announcement there, you need to pass the field default you want to `save()`, such as: 

```
def perform_create(self, serializer):
    serializer.save(owner=self.request.user)
```

I hope that clears it up.

**Comment by xuxinwen** [comment]
Thank you very much ! ! !



coderWen@126.com
 
From: Carlton Gibson
Date: 2019-11-13 22:02
To: encode/django-rest-framework
CC: xinwen; Author
Subject: Re: [encode/django-rest-framework] serializer field `read_only` and `default` bug (#7055)
I think you probably want to read Altered the behaviour of read_only plus default on Field. from the 3.8 release announcement.
There's a long history here, that you can follow from the linked issue but, tl;dr the old behaviour cloaked a very tricky bug when using dotted values as a field source and it was necessary to alter it.
As per the notice in the release announcement there, you need to pass the field default you want to save(), such as:
def perform_create(self, serializer):
    serializer.save(owner=self.request.user)

I hope that clears it up.

**Comment by prokaktus** [comment]
Maybe remove these line from docs?

https://www.django-rest-framework.org/api-guide/validators/#advanced-field-defaults

> Using a standard field with `read_only=True`, but that also includes a `default=…` argument. This field will be used in the serializer output representation, but cannot be set directly by the user.

Because looks like this behavior changed since 3.8
