### ISSUE TITLE
Rate Limiting URLS

### ISSUE THREAD

**Issue by steverecio** [encode/django-rest-framework#7068]
I'm using a third party django app (https://github.com/Tivix/django-rest-auth/) and I'd like to apply rate limiting to specific URLS. I've seen the decorator docs to add to a view but I'd rather not have to subclass each view and instead just pass an array of URLS in my settings.py for DRF. Is that a possibility?

**Comment by tomchristie** [comment]
We don't support that style, no.

You'll need to use a decorator on any function based view that you want to override the defaults for, or a `throttle_classes` attribute on class based views.

If that's not sufficient you could also have a look into adding throttling in a middleware layer.
