### ISSUE TITLE
Relation does not exist in Nested Serialization

### ISSUE THREAD

**Issue by yerycs** [encode/django-rest-framework#7082]
I am using Django Rest Framework and PostgreSQL Multi schemas.

```python
# serializers.py

from accounts.models import User
from myData.models import Private_ID_Info

class PrivateIDInfoSerializer(serializers.ModelSerializer):

    class Meta:
        model = Private_ID_Info
        fields = ('first_name', 'last_name', )

class UserInfoSerializer(serializers.ModelSerializer):
    privateIdInfo = PrivateIDInfoSerializer(many=True, read_only=True, source='private_id_info_set')

    class Meta:
        model = User
        fields = ('id', 'username', 'email', 'role', 'privateIdInfo', )
```
Above code, there are two relation tables, one is user table and the other one is private_id_info table.
These two tables are in different schemas. The problem is DRF cannot find relation between two models.
If two tables are in same schema, the relation between two tables is recoginzed and runs well.
I am using multi schemas in PostgreSQL and in setting.py, following code is placed about multi schemas settings.

```python
# settings.py

'default': {
    'ENGINE': 'django.db.backends.postgresql_psycopg2',
    'OPTIONS': {
        'options': '-c search_path=django,public'
    },
    'NAME': config('DB_NAME'),
    'USER': config('DB_USER'),
    'PASSWORD': config('DB_PASSWORD'),
    'HOST': config('DB_HOST'),   # Or an IP Address that your DB is hosted on
},

'myData': {
    'ENGINE': 'django.db.backends.postgresql_psycopg2',
    'OPTIONS': {
        'options': '-c search_path=myData,public'
    },
    'NAME': config('DB_NAME'),
    'USER': config('DB_USER'),
    'PASSWORD': config('DB_PASSWORD'),
    'HOST': config('DB_HOST'),   # Or an IP Address that your DB is hosted on
}
```
I searched but I didn't find answer.
DRF does not support relation between two tables in different schemas?

**Comment by auvipy** [comment]
I think Django doesn't support that yet

**Comment by rpkilby** [comment]
If you're getting a `ProgrammingError` that a relation does not exist, then that's an underlying ORM issue with your models/database configuration and isn't likely related to DRF serializers. 

I haven't used multiple schemas, but I'm assuming the ORM is balking at fetching a relation via a different database connection. I assume you don't need the separate connection, so you might be able to drop that in favor of specifying the schema with [`db_table`](https://dba.stackexchange.com/a/215761).

**Comment by yerycs** [comment]
This means, DRF support such relation on different schemas?

**Comment by yerycs** [comment]
```
psycopg2.errors.UndefinedTable: relation "private_id_info" does not exist
```
This is error message.

**Comment by yerycs** [comment]
Hello. @rpkilby. I solved the problem.
I followed you and changed the method of using multischemas. Not routing, using schema.db_table.
Thank you.
