### ISSUE TITLE
While patching, some data needed can't access.

### ISSUE THREAD

**Issue by ShoorDay** [encode/django-rest-framework#7091]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
when i use patch method, some fields are not present in validated_data while validation of other fields depend on them. 
For example, i need to make sure that tag associated with a post are the same owner. While patching, there is a exception and i notice that there isn't owner data. 
How i process this case? Can i get the data when validating data. Or i must use put method.

**Comment by rpkilby** [comment]
It depends on what you're trying to accomplish. If the user should supply that field, then you should validate that. However, if you can get the field value from the initial `.instance`, then you can use `.partial` to modify the validation behavior. 

If you have any more specific questions, I'd recommend asking them in one of the [support](http://www.django-rest-framework.org/#support) channels.
