### ISSUE TITLE
CursorPagination | Hook for encoded cursor string, not just the URL

### ISSUE THREAD

**Issue by shivanshs9** [encode/django-rest-framework#7095]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
My API uses **CursorPagination** and has a need to separately provide the **next** and **previous** cursor value to be passed as a query parameter. Having a complete URL isn't useful for several API clients since they call endpoint via an interface method, annotated with details about endpoint URL, parameters and request method.
Following is the schema for the paginated response of my API:

```json
{
	"metadata": {
		"next": "http://myapi.com/endpoint/?cursor=....",
		"previous": null,
		"page_size": 20,
		"next_cursor": "....",
		"previous_cursor": null
	},
	"data": [
		...
	]
}
```

## Expected behavior
Able to provide the encoded value of next and previous cursor in my response body of custom pagination class using `self.encode_cursor`

## Actual behavior
`encode_cursor` both encodes the cursor value and returns the complete URL on replacing the cursor query param value. There's no way to add a hook just to get the encoded string, not the complete URL. Right now, I copied the encode_cursor to my subclass to just return the encoded string, not the URL. But it's an approach that sounds stinky. Is it possible the `encode_cursor` can be reduced and getting complete URL can be handled by a new `encode_cursor_url` method maybe?

Related PR: #3067

**Comment by tomchristie** [comment]
Now closed: #3067
