### ISSUE TITLE
use list_route add multiple decorate => 405 error

### ISSUE THREAD

**Issue by felixglow** [encode/django-rest-framework#7097]
## Steps to reproduce
I use list_route, add multiple decorate
```
def audit_log():
    def _log_record(func):
        def record(self, request, *args, **kwargs):
            print("enter$$$$$$$$$")
            res = func(self, request, *args, **kwargs)
            return res
        return record
    return _log_record


class HostInfoViewSet(ModelViewSet):

    @list_route(methods=['post'], url_path='valid')
    @audit_log()
    def get_valid_snooze(self, request, *args, **kwargs):
        print('@@@@@@@TEST')
        return Response("@@@@@@@TEST")

```
## Expected behavior
old version:
django==2.0.4
djangorestframework==3.7.*

![image](https://user-images.githubusercontent.com/8147810/71225389-74d9c100-2313-11ea-8974-7f7a77cff3e7.png)
![image](https://user-images.githubusercontent.com/8147810/71225405-86bb6400-2313-11ea-99ae-84774cd35e80.png)

## Actual behavior
new version:
Django==2.2.5
djangorestframework==3.9.4

occur 405 error
![image](https://user-images.githubusercontent.com/8147810/71225511-d568fe00-2313-11ea-8dde-b1a4b6cd271c.png)

**Comment by rpkilby** [comment]
Thanks for the report @felixglow. Verified that this is an issue on master. 

In the mean time, a quick workaround is to modify the decorator function's `.__name__`. e.g., 

```python
def audit_log():
    def _log_record(func):
        def record(self, request, *args, **kwargs):
            print("enter$$$$$$$$$")
            res = func(self, request, *args, **kwargs)
            return res
        record.__name__ = func.__name__
        return record
    return _log_record
```

**Comment by felixglow** [comment]
@rpkilby It's work, thank you very much.
