### ISSUE TITLE
SkipError issue

### ISSUE THREAD

**Issue by anjanikumar496** [encode/django-rest-framework#7099]
I am using the django== 2.2.6 and  python==3.7
but After installation of the djangorestframework it Installed and after  installation 

![Screenshot 2019-12-21 at 4 43 10 PM](https://user-images.githubusercontent.com/43503509/71307209-08dd8280-2411-11ea-92c7-09d6290dd877.png)

After registering in the installed App i got the Error

![Screenshot 2019-12-21 at 4 45 11 PM](https://user-images.githubusercontent.com/43503509/71307231-4b9f5a80-2411-11ea-8794-0f6bfaaf9678.png)

**Comment by rpkilby** [comment]
Hi @anjanikumar496. Typically, `rest_framework` and other third party apps should follow the builtin Django apps. Also, I don't know why you're getting that error. DRF's template tags don't try to import `SkipError` from `rest_framework.exceptions`.
