### ISSUE TITLE
Router for Routers

### ISSUE THREAD

**Issue by mbrahimi617** [encode/django-rest-framework#7106]
The way the routers are currently designed they currently only really accommodate a flat toplevel API. However, I'd like to have an API per app in my project such that the name of the app is a prefix in the path. The toplevel API would list all the registered sub-routers and their corresponding paths:

```
/api/app1/
/api/app2/
/app/app3/
```

Once clicking on a link for a given app, you should get the list of all registered viewsets for that router:

```
/api/app1/viewset1/
/api/app1/viewset2/
/api/app1/viewset3/
```

I've seen solutions in which people use the extend method of the router class to extend the toplevel router with the urls of sub-routers, however, that still lists all of the APIs on the toplevel render nor does it isolate the apps such that viewsets of the same name in different apps don't conflict. Can I suggest a router for routers if that makes sense? Or any means of isolate app routes while providing customization as to how to render the toplevel API?

**Comment by auvipy** [comment]
did you mean drf nested router?

**Comment by mbrahimi617** [comment]
No I'm talking about app isolation not routes for related models.

**Comment by sevdog** [comment]
IMHO this can be easily implemented with standards django [include](https://docs.djangoproject.com/en/3.0/topics/http/urls/#including-other-urlconfs), there is no need to extra implementation.

Example:
```
urlpatterns = [
   path('api/app1/', include('app1.urls'),
   path('api/app2/', include('app2.urls'),
   ...
]
```

**Comment by mbrahimi617** [comment]
I've actually done just that but the problem is rendering the API root such that I can see the apps listed.

**Comment by mbrahimi617** [comment]
Instead of having one API root each app has it's own API root in this scenario.

**Comment by sevdog** [comment]
So you want something like [`APIRootView`](https://github.com/encode/django-rest-framework/blob/3.11.0/rest_framework/routers.py#L273) which handles **every** API that you have registered through your project?

**Comment by mbrahimi617** [comment]
More or less, or rather all routes beginning with `api/`

**Comment by onegreyonewhite** [comment]
It would be better if some of [this](https://github.com/vstconsulting/vstutils/blob/master/vstutils/api/routers.py) functionality will be in the main library. If I do a PR for this functionality, would you consider it? Or is this functionality not interesting for this project?

**Comment by mbrahimi617** [comment]
@onegreyonewhite To be honest, I can't really parse through the docs right now but I would definitely like the idea of chaining routers in terms outlining the rendered UI from a toplevel router to sub-routers at any depth in the main DRF library.

**Comment by mbrahimi617** [comment]
Well it looks like I could subclass `APIRootView` but honestly this functionality to isolate apps and have a router to each separate app router should definitely be a default included feature.

**Comment by tomchristie** [comment]
Routers and ViewSets are already complicated enough, so it’s unlikely we’d adopt something like this. If we did want to we’d probably want to see a third party package approach first to demonstrate the functionality and help gauge how widely it’s wanted by the community.

**Comment by mbrahimi617** [comment]
Well to be completely honest it makes no sense that each app should have it's own API root. A single API root at a toplevel route should merge multiple routers and have a tree like structure. The routers should be extended to register either a viewset or another router and the implementation should type check.
