### ISSUE TITLE
international document

### ISSUE THREAD

**Issue by ZhaoQi99** [encode/django-rest-framework#7107]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Actual behavior

Hello，When is there an international document?And do you consider doing this?

**Comment by xordoquy** [comment]
Hi,

I have no idea what international document you are referring to.

**Comment by ZhaoQi99** [comment]
> Hi,
> 
> I have no idea what international document you are referring to.

What I mean is django-rest-framework docs in https://www.django-rest-framework.org/

**Comment by xordoquy** [comment]
It might be nice to have at some point but the current documentation generation does not support translated documentation.
Before jumping to an implementation I - probably the others too - would like to get a general plan about how to deal with translated documentation, its generation and so on.
