### ISSUE TITLE
Issue template doesn

### ISSUE THREAD

**Issue by helbash** [encode/django-rest-framework#7109]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

Issue template doesn't have security question check point to make sure that issue is not a security bug/issue.  

I suggest adding an extra checkpoint to make sure that the contributor isn't raising a security concern publicly but should use email instead, just like the policy instructions in the README.md

**Comment by carltongibson** [comment]
Hi @helbash. Want to make a PR for this? 🙂
