### ISSUE TITLE
Upload image on json

### ISSUE THREAD

**Issue by yerycs** [encode/django-rest-framework#7112]
I am going to upload image on json.

e.g Postman request.
```
{
    "username": "is690002",
    "password": "is690002",
    "first_name": "andres ",
    "last_name": "Barragan",
    "email": "zaturoz.marco@gmail.com",
    "userprofile": {
        "gender": "F",
        "phone_number": "3315854644",
        "photo": "/media/image.png"
    }
}
```
I noticed DRF doesn't support uploading file on json.
Is there anyway to implement it?

**Comment by eshikvtumane** [comment]
@yerycs 

You can use `form-data` in postman for send files to backend.

For example https://stackoverflow.com/a/49210637

**Comment by tomchristie** [comment]
Hi there & thanks for your question.

The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions.

Thanks! 😀
