### ISSUE TITLE
RelatedField's many_init ignores allow_null

### ISSUE THREAD

**Issue by balinabbb** [encode/django-rest-framework#7119]
## Steps to reproduce
- Declare a field with `allow_null=True` and `many=True`, e.g. `PrimaryKeyRelatedField`
- try to submit/validate null value for that field
- validation error (field can not be null)

## Expected behavior
- If stated directly with `allow_null=True` the `ManyField` should allow null values

## Actual behavior
- `allow_null` is not copied to `ManyField` class, because [MANY_RELATION_KWARGS](https://github.com/encode/django-rest-framework/blob/master/rest_framework/relations.py#L82) does not include it.

## Summary
I understand very well, that a many field should eventually result in an empty list, however it opposes my API behavior to disallow null values. I would handle nulls myself while creating/updating data. Is there a reason why allow_null is not included here? 

After quite some struggle I came up with this workaround:

```python
class MyCustomFieldThatAllowsNull(serializers.ManyRelatedField):
    def __init__(self, **kwargs):
        super().__init__(
            child_relation=serializers.PrimaryKeyRelatedField(**kwargs),
        )

    def validate_empty_values(self, data):
        if data is None:
            return True, []

        return super().validate_empty_values(data)

class MySerializer(serializers.ModelSerializer):
    class Meta:
        ...
    my_field = MyCustomFieldThatAllowsNull(queryset=models.MyModel.objects.all())
```
Originally:
```python
class MySerializer(serializers.ModelSerializer):
    class Meta:
        ...
    field = serializers.PrimaryKeyRelatedField(
        queryset=models.MyModel.objects.all(),
        many=True,
        allow_null=True,  # does not work        
    )
```

**Comment by belkka** [comment]
It worth noting that [LIST_SERIALIZER_KWARGS](https://github.com/encode/django-rest-framework/blob/56ff382b174c98fbe8a8dde74e32d32ab4e0f303/rest_framework/serializers.py#L74) do contain the `'allow_null'`

**Comment by belkka** [comment]
@balinabbb Consider another workaround:
```
class MySerializer(serializers.Serializer):
    field = serializers.ManyRelatedField(
        child_relation=serializers.PrimaryKeyRelatedField(
            queryset=models.MyModel.objects.all(),
            many=True,
            allow_null=True,  # could be set to False if needed
        ),
        allow_null=True,
    )
```
I did not test it, but this approach resolved my own similar issue right now. I had a problem with the fact that `default=[]` is applied to both `ManyRelatedField` and `child_relation`, although it's meaningful only for `ManyRelatedField`. The [drf_yasg](https://github.com/axnsan12/drf-yasg) (OpenAPI generation tool) get an exception because of PrimaryKeyRelatedField not being able to call `.to_representation()` with default value (which is `[]`), because lists don't have an attribute `.pk`.

It looks quite weird that MANY_RELATION_KWARGS and LIST_SERIALIZER_KWARGS are only **copied** to "parent object", not **moved**. I do not see any advantages of latter compared to former.

**Comment by tomchristie** [comment]
I don't see us changing this, no. `allow_null` isn't meaningful in the context of a `many=True` relationship, it only make sense for the "instance or None" case.

What behaviour are you expecting here - for `None` values in the list to be silently discarded, or something else?

**Comment by balinabbb** [comment]
No, i do not mean to change the behaviour of the values in the list, but the list itself. I would suggest that `allow_null ` should allow the whole list to be null:

```
class MySerializer(serializers.ModelSerializer):
    class Meta:
        ...
    field = serializers.PrimaryKeyRelatedField(
        queryset=models.MyModel.objects.all(),
        many=True,
        allow_null=True,  # does not work        
    )
```
->
```
{ "field": null } # should be accepted if specified
{ "field": [] } # should be accepted if not specified
```

**Comment by belkka** [comment]
@tomchristie Then why does LIST_SERIALIZER_KWARGS contain `allow_null` (as I mentioned above)?

**Comment by szuliq** [comment]
@tomchristie I don't agree `allow_null` is meaningless in this context.

Example:

Permissions system where by default all users have access to a resource. It is also possible to specify a list of people with access as `allowed_users_whitelist`.

Possible values for `allowed_users_whitelist`:

- `null` -- everyone has access; benefit: new users don't need to be added to this list
- `[user_1, user_2]` -- when only those users are supposed to have access to a resource
- `[]` -- when no one should have access to a resource
