### ISSUE TITLE
Wrong translation for pt_BR

### ISSUE THREAD

**Issue by Cloves23** [encode/django-rest-framework#7128]
I'm Brazilian and the correct translation is **Filtros de campo**. The phrase *Filtra de campo* does not exists.

https://github.com/encode/django-rest-framework/blob/373e521f3685c48eb22e6fbb1d7079f161a4a67b/rest_framework/locale/pt_BR/LC_MESSAGES/django.po#L380

**Comment by Cloves23** [comment]
This translation is not right too. The correct is **Filtros**.

https://github.com/encode/django-rest-framework/blob/373e521f3685c48eb22e6fbb1d7079f161a4a67b/rest_framework/locale/pt_BR/LC_MESSAGES/django.po#L375

**Comment by xordoquy** [comment]
Translations are managed through [transifex](https://www.transifex.com/django-rest-framework-1/django-rest-framework/dashboard/). I suggest you subscribe there and correct the translations.
