### ISSUE TITLE
405_METHOD_NOT_ALLOWED should be returned instead of 403_FORBIDDEN

### ISSUE THREAD

**Issue by WisdomPill** [encode/django-rest-framework#7129]
Requests to an authenticated api on a not allowed method by not authenticated user returns 403 instead of a 405 status code.

As seen here:
https://github.com/encode/django-rest-framework/blob/373e521f3685c48eb22e6fbb1d7079f161a4a67b/rest_framework/views.py#L493

My question is, is this the correct behavior of an api?

I would expect to get a 405 status code, no authentication needed.

Frankly, I would expect a 401, not authorized instead of a 403

As described in http decision diagram repository.

https://github.com/for-GET/http-decision-diagram

## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Just a basic request to an api without a handler for a method and with authentication

## Expected behavior

Getting a 405 status code instead of 403

## Actual behavior

I'm getting a 403 instead of a 405

**Comment by tomchristie** [comment]
A 403 is preferable here in order to avoid exposing unintended information.

**Comment by rpkilby** [comment]
For additional context, https://github.com/encode/django-rest-framework/issues/5968#issuecomment-386519574 explains why a 403 is returned instead of a 401.

**Comment by kurtwheeler** [comment]
What about exposing intended information? If a client is trying to PUT to a route that doesn't accept PUTs, I'd like to inform them that they shouldn't be trying to PUT. I don't want to hide the fact that you can't PUT to that route, I want to make it obvious so they stop trying to PUT rather than trying to figure out how to authenticate or fix their permissions.

Is there any way to force DRF to prefer 405's over 403s?
