### ISSUE TITLE
DjangoTestAdapter cannot deal with certain start_response invocations

### ISSUE THREAD

**Issue by untitaker** [encode/django-rest-framework#7132]
The [`start_response`](https://github.com/encode/django-rest-framework/blob/f9cc190177e0ad7bd3d747b0852747aa3819ae77/rest_framework/test.py#L82) definition of rest-framework's test utilities does not conform to the signature presented in the [WSGI PEP](https://www.python.org/dev/peps/pep-0333/#the-start-response-callable):

    start_response(status, headers)   # wrong
    start_response(status, headers, exc_info=None)  # right

This makes a difference for the following invocation, which is valid according to the WSGI PEP but will break the TestAdapter:

    start_response(status, headers, sys.exc_info())
    start_response(status, headers, None)

It is unclear to me whether the second invocation is actually valid, but a lot of implementations accept it regardless.

**Comment by rpkilby** [comment]
It's easy enough to fix the signature, but is it expected that `exc_info` is handled in a particular way?

**Comment by untitaker** [comment]
I don't know if this is ever used by Django. Werkzeug's test client always just re-raises from within start_response and I don't think anybody has had a problem with that.
