### ISSUE TITLE
AssertionError at /api/  Using OpenAPIRenderer, but `pyyaml` is not installed.

### ISSUE THREAD

**Issue by habeeb555-q** [encode/django-rest-framework#7136]
Request Method: | GET
-- | --
http://127.0.0.1:8000/api/
3.0.2
AssertionError
Using OpenAPIRenderer, but `pyyaml` is not installed.
/home/admin/DEV/PYTHON/Frameworks/django/HighEndSalesEnv/lib/python3.7/site-packages/rest_framework/renderers.py  in __init__, line 1053
/home/admin/DEV/PYTHON/Frameworks/django/HighEndSalesEnv/bin/python
3.7.5
['/home/admin/DEV/PYTHON/Frameworks/django/HighEndSalesEnv/backend',  '/usr/lib/python37.zip',  '/usr/lib/python3.7',  '/usr/lib/python3.7/lib-dynload',  '/home/admin/DEV/PYTHON/Frameworks/django/HighEndSalesEnv/lib/python3.7/site-packages']
Fri, 10 Jan 2020 01:39:39 +0000

Why this error again when this issue is already resolved in #6366

**Comment by carltongibson** [comment]
Hi @HabeebUllah555. #6366 pertained to the `generateschema` command. Presumably you're using the APIView. 

Can you paste the full traceback? 

In the meantime, installing pyyaml will workaround this issue.

**Comment by carltongibson** [comment]
This should be easy enough to resolve: as per #6366, defer instantiating the yaml renderer until it's actually needed.

**Comment by karranb** [comment]
Hi, can I work on this?

**Comment by carltongibson** [comment]
The only way I can see this coming up is if a SchemaView is configured to use the OpenAPIRenderer, but then, yes, `pyyaml` is required. 

Closing on that basis. Happy to review a full traceback.
