### ISSUE TITLE
How to set a field type on SerializerMethodField for OpenAPI schema generation?

### ISSUE THREAD

**Issue by Lucidiot** [encode/django-rest-framework#7140]
Consider this useless serializer:

``` python
class MySerializer(serializers.Serializer):

    random_number = serializers.SerializerMethodField()

    def get_random_number(self):
        # Chosen by fair dice roll.
        # Guaranteed to be random.
        return 4
```

Assuming you added this serializer in an endpoint and generated the OpenAPI schema, the serializer would look like this:

``` yaml
properties:
  random_number:
    type: string
  required:
  - random_number
```

The issue here is there is no way to tell DRF to use `type: number` here. I thought of a few possibilities:

* An `output_field` attribute, like `serializers.SerializerMethodField(output_field=serializers.IntegerField())`, similarly to Django's [Query Expressions](https://docs.djangoproject.com/en/2.2/ref/models/expressions/#expressionwrapper-expressions)
* A decorator, like `openapi_type(serializers.SerializerMethodField(), serializers.IntegerField())`
* An attribute, similarly to setting descriptions on [admin actions](https://docs.djangoproject.com/en/3.0/ref/contrib/admin/actions/#writing-action-functions):

  ``` python
  random_number = serializers.SerializerMethodField()

  def get_random_number(self):
      return 4

  get_random_number.output_field = serializers.IntegerField()
  ```
* Simply something DRF does not support, which probably should be documented somewhere as a possible caveat.

**Comment by carltongibson** [comment]
Hi @Lucidiot. 

I guess the immediate way to do this would be to override [`AutoSchema._map_field()`](https://github.com/encode/django-rest-framework/blob/496947be3a8ac6e21b862dc7697d96f403b18ad6/rest_framework/schemas/openapi.py#L212). 

You can either do that per-serializer/view to expect the field in question, or add an attribute like you say. 

We'll come round to something in this way eventually, but currently I'm not sure about the best option, in terms of API.

**Comment by knyghty** [comment]
For me, I think the API I'd prefer is something using type hinting like:

```python
def get_foo(self, obj) -> int:
    return 1
```

It works in every Python version currently supported.  This idea was used in https://github.com/encode/django-rest-framework/pull/7089 but it wasn't separated out into another PR. Looking at that implementation, it seems like it doesn't handle collections. At some point you'd be better using a nested serializer, but I think simple cases like `List[int]`, `List[str]`, `Dict[str, int]` etc. should be supported.

@carlfarrington what do you think? Is it worth trying this approach or are there problems with it? If it's worth trying, is it also worth getting something basic in that can handle basic types and ignore nested fields for now or would we want (nested or not) arrays and objects from the start?

**Comment by carltongibson** [comment]
We'll promote and document `map_field()` for 3.12. That's the right way to go here.

**Comment by collinscangarella** [comment]
https://www.django-rest-framework.org/api-guide/schemas/#map_field

**Comment by kmmbvnr** [comment]
Any suggestions how to return different schema, for different SerializerMethodFields ?

At the `map_field` we have only field instance, without field name or method been called. So it's hard to distinguish different fields from a serializer class
