### ISSUE TITLE
django-rest-auth on "pause"/unmaintained. Remove from docs/mention maintenance status?

### ISSUE THREAD

**Issue by Busteren** [encode/django-rest-framework#7147]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
[link to issue explaining "pause" on maintenance](https://github.com/Tivix/django-rest-auth/issues/568#issuecomment-529569881)

## Actual behavior
Discussion:
Should the [DRF documentation](https://www.django-rest-framework.org/api-guide/authentication/#django-rest-auth) point to projects no longer maintained/"on pause".
Given the critical nature of authentication, I think it would be good to either remove the project from the documentation or display its maintenance status. Especially as it is just mentioned in an issue.

**Comment by tomchristie** [comment]
I've taken a quick look over there.
For *right now* I think we should keep linking to it - if there's a fork or if there's an update on the status perhaps we can rethink.

**Comment by iMerica** [comment]
The company behind that project preferred to have someone fork it instead of changing ownership, so I'm now maintaining [Dj-Rest-Auth](https://github.com/jazzband/dj-rest-auth). Same API as before. Just a different name.

**Comment by tomchristie** [comment]
@iMerica Ok. You'd be welcome to submit a pull request to add that in the docs. At the moment I'd suggest that we link to both, noting the second as a fork.
