### ISSUE TITLE
incorrect image url

### ISSUE THREAD

**Issue by dsal3389** [encode/django-rest-framework#7149]
https://github.com/encode/django-rest-framework/blob/7bd730124c93f9309c6603ccfb56316d3f6934f0/rest_framework/fields.py#L1590

I am trying to show the image URL but the `serializers.ImageField()` showing me a wrong path to the image because of the following line that I marked.

`serializers.ImageField(use_url=False)` is not giving me the correct URL as well.

what is showing me:
`"image": "http://127.0.0.1:8000/api/tutorials/46f54de4-5306-4714-b943-8c2f55d81c56/api/media/defaults/images/tutorial-images/random1.png"`

the correct link:
`"image": "http://127.0.0.1:8000/api/media/defaults/images/tutorial-images/random1.png"`

currently I am using a `SerializerMethodField` to fix the problem with the function:
```py
def get_image(self, obj):
        return obj.image.url
```

**Comment by rpkilby** [comment]
Hi @dsal3389 - the issue tracker is intended for bug reports & feature requests. If you're looking for [support](http://www.django-rest-framework.org/#support), I'd recommend either the IRC channel or discussion group.
