### ISSUE TITLE
Mutable data structures for argument defaults

### ISSUE THREAD

**Issue by Mogost** [encode/django-rest-framework#7151]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [ ] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

Overriding OrderingFilter for my custom filter, I noticed the following error with flake8-bugbear installed:

> B006 Do not use mutable data structures for argument defaults.  They are created during function definition time. All calls to the function reuse this one instance of that data structure, persisting changes between them.

https://github.com/encode/django-rest-framework/blob/7bd730124c93f9309c6603ccfb56316d3f6934f0/rest_framework/filters.py#L233

I understand that probably this does not lead to anything bad. I just want to clearly make sure that everything is in order here.

**Comment by tomchristie** [comment]
> I just want to clearly make sure that everything is in order here.

It is, yup. 😃

**Comment by FermiParadox** [comment]
This issue still exists here: https://github.com/encode/django-rest-framework/blob/acf6582de474ad7f0c5f97d59208691c09c049c0/rest_framework/filters.py#L208 
and here: 
https://github.com/encode/django-rest-framework/blob/acf6582de474ad7f0c5f97d59208691c09c049c0/rest_framework/filters.py#L245

Hopefully it causes no problems. 
Sometimes though, default mutable arguments can cause bugs or even memory leaks.
