### ISSUE TITLE
[Question] Why RequestsClient is very very slow? with test runner as pytest?

### ISSUE THREAD

**Issue by imkaka** [encode/django-rest-framework#7153]
## Checklist

- [ ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [ ] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
My Pytest.ini file: 
```
[pytest]
DJANGO_SETTINGS_MODULE = api.settings
addopts = --reuse-db
keepdb = true
```

I am trying to hit the staging server, with the complete URL. 

Code snippet:
```py
@pytest.mark.integration
class TestX(APITestCase):

    base_url = HOST + "/api/v1/"
    client_class = RequestsClient

    def test_x_flow(self):
        self.base_url = self.base_url + "xyz/"
        access_token = self.login_helper()
        self.client.headers.update({'Authorization': 'Token ' + access_token})

        url = self.base_url
        params = {'station_id': INVALID_STATION_ID}
        response = self.client.get(url, params=params)
        self.assertEqual(response.status_code, 400)
        data = get_data(response.content)
        self.assertEqual(data['error_code'], STATION_NOT_FOUND)
```

Q - `response.data` is also not available!!

It runs very slow almost take 5-10 minutes, what can be the possible reason?

**Comment by tomchristie** [comment]
> It runs very slow almost take 5-10 minutes, what can be the possible reason?

We're not able to help with issues that aren't narrowed down to a reproducible example.
You'd need to do some more digging into the issue yourself first, and properly isolate what the issue might be - there's no particular indication here that there's any problem with the `RequestsClient`, rather than with the code that it's calling into.
