### ISSUE TITLE
RemoteUserAuthentication.authenticate calls django.contrib.auth.authenticate without request argument

### ISSUE THREAD

**Issue by puittenbroek** [encode/django-rest-framework#7157]
## Checklist

- [X] I have verified that that issue exists against the `master` branch of Django REST framework.
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [X] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [X] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Expected behavior
`user = authenticate(request=request, remote_user=request.META.get(self.header))`

## Actual behavior
`user = authenticate(remote_user=request.META.get(self.header))`

**Comment by xordoquy** [comment]
Feel free to open a PR about that. It looks like wee didn't notice that one when moving to Django 1.11
