### ISSUE TITLE
Browsable API no longer usable with Django Debug Toolbar (for POST, PUT and PATCH)

### ISSUE THREAD

**Issue by barseghyanartur** [encode/django-rest-framework#7167]
## Checklist

- [ ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Found solution

Sorry for the buzz. It turns out there is a third-party library which deals nicely with the issue:

https://github.com/djsutho/django-debug-toolbar-request-history

Simply adding the following in the dev settings (after ``pip install``), does the job:
```python
DEBUG_TOOLBAR_PANELS = [
    'ddt_request_history.panels.request_history.RequestHistoryPanel',  # Here it is
    # ... the rest
]
```

Thus, issue is solved for me and might be closed. However, it might be worth documenting it (debugging the API section). If you point me where, I could come up with a documentation PR.

## Steps to reproduce

In past it was possible to use DRF browsable API with Django Debug Toolbar (POST, PUT, PATCH, DELETE, GET). Currently (DRF 3.10.3) Debug Toolbar appears in GET only. As far as I understand, introduction of AJAX is the cause of this.

## Expected behavior

This is not a bug, but I would want an option to choose whether I do or not not want AJAX functionality in my browsable API.

The question is, could it be considered? This might be valid for lots of devs out there.

## Actual behavior

Debug Toolbar does not show up on POST, PUT and PATCH.

**Comment by auvipy** [comment]
let's close it then?

**Comment by tomchristie** [comment]
Happy to accept any docs PRs for this.
It might? be more discoverable as something highlights in the Django Debug Toolbar docs rather than here.
