### ISSUE TITLE
Bug: openapi 3.0 schema generation fails to add the type property to schemas

### ISSUE THREAD

**Issue by Kentalot** [encode/django-rest-framework#7168]
## Checklist

- [X] I have verified that that issue exists against the `master` branch of Django REST framework.
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [X] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [X] I have reduced the issue to the simplest possible case.
- [X] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Use the django rest framework to generate a json or yaml openapi 3.0 schema. Then run openapi codegen on it.  Try to compile the generated C# code.

## Expected behavior
C# SDK generation should not result in UNKNOWN_BASE_TYPE and C# compiling should work.

## Actual behavior
It'll fail for C# SDK compilation because of UNKNOWN_BASE_TYPE being inserted into the generated code.

**Comment by Kentalot** [comment]
PR to fix this is #7169

**Comment by Kentalot** [comment]
More info: [OpenApi Spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md) Though it doesn't state that this is required (it doesn't say what's required), every example has the `type` property for objects.

Also, I tested this change locally and confirmed that it fixes the openapi spec and the codegen/compilation of C# sdk.

**Comment by carltongibson** [comment]
Closed by #7169
