### ISSUE TITLE
"api guide" link broken in "Quickstart" documentation with broken 404 page

### ISSUE THREAD

**Issue by WoLpH** [encode/django-rest-framework#7180]
I've seen similar issues but I believe this one is new.

In the [quickstart](https://www.django-rest-framework.org/tutorial/quickstart/) documentation the link to the API guide at the bottom is broken. It links to "https://www.django-rest-framework.org/tutorial/#api-guide" which not only results in a 404, but a 404 where all styling is broken as well:

![image](https://user-images.githubusercontent.com/270571/73926329-be846800-48cf-11ea-8c56-ed12fb676c43.png)

**Comment by rpkilby** [comment]
Thanks @WoLpH. Opened the above PR.
