### ISSUE TITLE
500 thrown when AcceptHeaderVersioning is utilized and version isn't in accept header

### ISSUE THREAD

**Issue by MJBrune** [encode/django-rest-framework#7181]
## Checklist

- [X] I have verified that that issue exists against the `master` branch of Django REST framework.
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [X] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [X] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

1) setup a quick API with AcceptHeaderVersioning.

2) Only have 1 allowed_version

3) Make a call to the api without an accept header

## Expected behavior

406 is returned saying you don't have the right version.

## Actual behavior

500 is returned: 
  File "/rest_framework/versioning.py", line 31, in is_allowed_version
    (version in self.allowed_versions))
TypeError: 'in <string>' requires string as left operand, not NoneType

### Addition Notes:

An accept-header with an empty version returns a 200. Essentially by passing the version check.

e.g. Accept: application/json; version=

Lastly note that this odd behavior goes away when you have 2 or more allowed versions.

**Comment by ihategoto** [comment]
Hi, how have you configured the `ALLOWED_VERSIONS` key?
I tried to reproduce the issue against the master and I got the expected behavior.
I'm using this configuration:
`REST_FRAMEWORK = {
    'DEFAULT_VERSIONING_CLASS' : 'rest_framework.versioning.AcceptHeaderVersioning',
    'ALLOWED_VERSIONS' : ['1.0', ],
}`
and this is my simple API:
`from django.http import JsonResponse
from rest_framework.views import APIView
from rest_framework import status

class test_versioning(APIView):

    def get(self, request, format = None):
        return JsonResponse({'version' : request.version}, status = status.HTTP_200_OK)
    
    def post(self, request, format = None):
        return JsonResponse({'version' : request.version}, status = status.HTTP_200_OK)`

**Comment by MJBrune** [comment]
'ALLOWED_VERSIONS': ('v1'), is what I was using. Perhaps the fact that I am using a tuple? I don't know why it seemed like using a tuple was a good idea. I thought this was automatically generated as
    # When you enable API versioning, the request.version attribute will contain a string
    # that corresponds to the version requested in the incoming client request.
    #'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.NamespaceVersioning',
    #'ALLOWED_VERSIONS': ('v1', 'v2'),
when I created the rest project but I can't see where that would have been generated from.

**Comment by xordoquy** [comment]
nice catch @ihategoto 
`('v1')` is not a tuple, it's a string. `('v1',)` would be a tuple - not the added comma.
