### ISSUE TITLE
DATETIME_FORMAT

### ISSUE THREAD

**Issue by joff13** [encode/django-rest-framework#7194]
## Steps to reproduce

add in settings.py

REST_FRAMEWORK = {
    'DATETIME_FORMAT': ['%Y-%m-%d %H:%M'],
}

or any format string e.g. iso-8610

## Actual behavior

end with error

 File "/......../env/lib/python3.6/site-packages/rest_framework/fields.py", line 1257, in to_representation
    if output_format.lower() == ISO_8601:
AttributeError: 'list' object has no attribute 'lower'

**Comment by xordoquy** [comment]
[Documentation](https://www.django-rest-framework.org/api-guide/settings/#datetime_format) says it should be a string, not a list.

**Comment by lappanchappan43** [comment]
The documentation clearly states list of strings. 

A list of format strings that should be used by default for parsing inputs to DateTimeField serializer fields.

May be a list including the string 'iso-8601' or Python [strftime format](https://docs.python.org/3/library/time.html#time.strftime) strings.

Default: ['iso-8601']
