### ISSUE TITLE
How to specify query string parameters in Docstring

### ISSUE THREAD

**Issue by rpaknahad** [encode/django-rest-framework#7212]
Hi everybody,
I want to use Docstring to document request query strings for a specific route. Is it possible?

Here is an example I have tried but not worked:

@action(detail=False, methods=['post'])
    def add(self, request):
        """
        Adds a new account
        parameters:
            - in: query
              name: service_id
              schema:
                type: string
              required: true
              description: Identifier of the service
        """
Thanks in advance.

**Comment by tomchristie** [comment]
Hi there & thanks for your question.

The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions.

Thanks! 😀
