### ISSUE TITLE
Any good practice to caching ModelViewSet?

### ISSUE THREAD

**Issue by marefati110** [encode/django-rest-framework#7221]
## Checklist

- [ ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [ ] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

**Comment by marefati110** [comment]
i try to cache ModelViewSet:

my view is :

class CommentsViewSet(ModelViewSet):
    queryset = CommentsModel.objects.all()
    serializer_class = CommentsALLSerializer
    http_method_names = ['get']
    permission_classes = (AllowAny,)


i try this but not work:
    @method_decorator(cache_page(60*60))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

how to deal with it ?

**Comment by tomchristie** [comment]
Hi there & thanks for your question.

The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions.

Thanks! 😀
