### ISSUE TITLE
Broken link in translation documentation

### ISSUE THREAD

**Issue by knasti** [encode/django-rest-framework#7226]
In https://www.django-rest-framework.org/topics/internationalization/ there are links to Django's translation documentation that are broke, specifically at the following paragraphs:

> REST framework ships with translatable error messages. You can make these appear in your language enabling Django's standard translation mechanisms.

> You can find more information on how the language preference is determined in the Django documentation. For reference, the method is:

I believe the broken links are caused by Django removing documentation for Django 1.7, see screenshot. Both of the links referenced above uses the Django 1.7 documentation. This also means that there might be other links from the documentation that uses links for 1.7 and thus are broken. 

![image](https://user-images.githubusercontent.com/21027620/76296727-f0b22c80-62b6-11ea-9f2d-42bae56abaf9.png)

This is a similar issue to  #6928

**Comment by tomchristie** [comment]
Closed via #7628
