### ISSUE TITLE
Request class ignores AttributeError raised by parser class

### ISSUE THREAD

**Issue by Xelia** [encode/django-rest-framework#7228]
## Steps to reproduce
- Write custom parser, that raises AttributeError 
- Use that parser in an ApiView
- Make a post request to that view with some request data
## Expected behavior
- I get error 500 making a request as with any other Exception raised by parser
## Actual behavior
- i get 200 ok with request.data = empty QueryDict

## Example code
```
from rest_framework import parsers
from rest_framework.views import APIView
from rest_framework.response import Response


class MyParser(parsers.BaseParser):
    media_type = 'application/json'

    def parse(self, stream, media_type=None, parser_context=None):
        raise AttributeError()


class MyView(APIView):
    parser_classes = (MyParser, )

    def post(self, request):
        return Response(str(request.data))
```

**Comment by sks444** [comment]
Hi @Xelia, So I did some debugging and found out that `AttributeError` is getting catched internally while parsing the request. [See](https://github.com/encode/django-rest-framework/blob/86aa549832b9468d14a9f66370cf15d6dbcb4bfa/rest_framework/request.py#L410). That's why you are not getting 500.

**Comment by elonzh** [comment]
Why closing this issue
