### ISSUE TITLE
Allow fields to get source from the method on the serializer

### ISSUE THREAD

**Issue by lokhman** [encode/django-rest-framework#7230]
**N.B.:** I'm not sure if this feature was discussed before, but the search in issues and pull requests didn't give me anything related.

As we know, the `source` argument in the `Field` class allows us to specify the original property or method on the instance to return the data for the field. If we want to return custom data, we may use `SerializerMethodField`. Very often we need to do the following:

```python
class MySerializer(serializers.Serializer):
    some_field = serializers.SerializerMethodField()

    def get_some_field(self, instance):
        some_value = instance.get_some_value(by=self.context['some_condition'])
        return serializers.DecimalField(5, 2).to_representation(some_value)
```

It would be better to allow fields to accept methods from serializers, instead of using `SerializerMethodField`. This will make the code shorter, more readable and help auto-documentation scripts to determine the types of the serialized fields.

I see two possible solutions:

1. Using the `source` parameter to check the serializer method (as it's done in Django admin).

```python
class MySerializer(serializers.Serializer):
    some_field = serializers.DecimalField(5, 2)

    def get_some_field(self, instance):
        return instance.get_some_value(by=self.context['some_condition'])
```

In this case, to be backwards compatible we need first to check for source on the model and then for the method in the serializer.

2. Using a new custom parameter (e.g. `method_field`) that will explicitly tell us that the source is taken from the serializer method.

```python
class MySerializer(serializers.Serializer):
    some_field = serializers.DecimalField(5, 2, method_field=True)

    def get_some_field(self, instance):
        return instance.get_some_value(by=self.context['some_condition'])
```

I personally like the 2nd approach, as more explicit for the reader and fast for serialization. It is backwards compatible as well. One of the downsides of the 1st approach I see the fact that data flow may be hard to trace and debug, as model instances may be patched, e.g. via reversed relations.

What is your opinion on that? If you feel it's worth including in DRF sources, we may choose the design of the feature and I will provide a pull request.

**Comment by DanielGnzlzVll** [comment]
We use serializer as a "contract" but the problem we are facing is that we have a lot of "SerializerMethodField" so there is no contract, I really would like to see this or something similar.

**Comment by auvipy** [comment]
I'm not 100% sure about the design decision to take here. But if the change is too big without much gain it won't be acceptable.
