### ISSUE TITLE
Implement `Request.__repr__` to show useful information about the request

### ISSUE THREAD

**Issue by cool-RR** [encode/django-rest-framework#7231]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

The path, for starters, would be useful.

**Comment by tomchristie** [comment]
The first thing to do on this issue would be to confirm:

* What the `__repr__` behavior of a standard Django request instance is.
* What the `__repr__` behavior of our Request instances currently is.
* Talk through what exact changes would be suggested.

**Comment by rpkilby** [comment]
> What the `__repr__` behavior of a standard Django request instance is.

`<WSGIRequest: GET '/foo'>`

> What the `__repr__` behavior of our Request instances currently is.

`<rest_framework.request.Request at 0x10f43dcd0>`
