### ISSUE TITLE
Serializer MultiPartParser allow_null IntegerField not working

### ISSUE THREAD

**Issue by jamalroger** [encode/django-rest-framework#7236]
Hi developers i used IntegerField(allow_null=True) to validate Integer but  allow_null=True did not work
with MultiPartParser  
```
   cost = serializers.IntegerField(allow_null=True)
```
and data of  comming request is 
```
    <QueryDict: {'cost': ['null']}>
```
notice that is worked with JSONParser

**Comment by rpkilby** [comment]
Hi @jamalroger. Unlike JSON, form data does not convey types. So, when you submit `?cost=null`, this is interpreted as a `"null"` string, not a `null` value. However, while you cannot explicitly send a null value, you can send nothing `?cost=`, which is interpreted by the serializer as a null.
