### ISSUE TITLE
Documentation: Show how throttling can be used with viewsets

### ISSUE THREAD

**Issue by ram-bv** [encode/django-rest-framework#7241]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## The issue

[The throttling documentation](https://www.django-rest-framework.org/api-guide/throttling/) shows how to define throttling for specific views, but we use viewsets, and it doesn't say how to use throttling with viewsets.

**Comment by xordoquy** [comment]
The [documentation states](https://www.django-rest-framework.org/api-guide/viewsets/):

> A ViewSet class is simply a type of class-based View, that does not provide any method handlers such as .get() or .post(), and instead provides actions such as .list() and .create().

That means that whatever applies to views - including throttling - applies to Viewsets.
No need to be specific here.

**Comment by xordoquy** [comment]
Also written explicit later on the same page:

> The ViewSet class inherits from APIView. You can use any of the standard attributes such as permission_classes, authentication_classes in order to control the API policy on the viewset.

**Comment by ram-bv** [comment]
So if I put a `throttle_classes` class attribute on a viewset, it automatically applies to all views in that viewset, including custom actions defined as method? The answer to this question isn't clear to me from the documentation.

**Comment by xordoquy** [comment]
> Django REST framework allows you to combine the logic for a set of related views in a single class, called a ViewSet.

so unless you say otherwise, it'll be applied everywhere for that viewset.

**Comment by ram-bv** [comment]
Thanks! I'd personally add that one sentence to the documentation, but I accept that it's just my opinion.
