### ISSUE TITLE
coreapi is abandoned

### ISSUE THREAD

**Issue by Rotzbua** [encode/django-rest-framework#7242]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [ ] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

`coreapi` and `coreschema` has been abandoned.

Most repositories are archived and just read only.
https://github.com/core-api/python-client
https://github.com/core-api/python-coreschema

## Expected behavior

Alternative libraries which are maintained? (security fixes?)

**Comment by carltongibson** [comment]
The CoreAPI based schema generation is no longer under active development. The default now is to generate OpenAPI schemas. The existing CoreAPI integration is deprecated, but continues to work for those who are using it. That deprecation is likely to be hardened for 3.12, with likely removal in 3.14.
