### ISSUE TITLE
Incomplete documentation for using mixins with generics

### ISSUE THREAD

**Issue by siowyisheng** [encode/django-rest-framework#7245]
#5640 is a similar issue, but I have a more glaring example of this problem.

I encountered this when using `DestroyModelMixin` with `CreateAPIView`. `.destroy()` gets added, but this doesn't actually add the ability to accept delete requests. It must be manually hooked up to the created `.destroy()` method. The only case where it gets mapped automatically is when a router is used or when a generic is used without a mixin. 

So I had to dive into the module code to fix this, while I think this can be and should be made much clearer in the docs.

The [given examples in the docs](https://www.django-rest-framework.org/api-guide/generic-views/#examples) do not cover this.

I'm happy to help to make a PR to update the docs if this is considered an issue worth fixing.

**Comment by xordoquy** [comment]
Routers are not meant to be used for generic views therefore I'm not really getting your point.

I'm curious, what would you add to the documentation ?

**Comment by siowyisheng** [comment]
That's my point. Only routers and generic views themselves provide the out of the box mapping from `retrieve` to `get`, from `create` to `post`. Mixins do not. So when you add a `DestroyModelMixin` to a `CreateAPIView`, you need to manually map `destroy` to `delete`.

There should be mention of this, when using mixins with generics.

**Comment by siowyisheng** [comment]
I have clarified the original post. It was unclear originally, thanks!

**Comment by xordoquy** [comment]
> There should be mention of this, when using mixins with generics.

This is already done:

> The mixin classes provide the actions that are used to provide the basic view behavior. Note that the mixin classes provide action methods rather than defining the handler methods, such as .get() and .post(), directly. This allows for more flexible composition of behavior.

**Comment by xordoquy** [comment]
By the way, I will still consider a PR with a differently phrasing.
I'm closing it as I consider it's already documented.
