### ISSUE TITLE
Is there a timeline on DRF 3.12.0?

### ISSUE THREAD

**Issue by synic** [encode/django-rest-framework#7248]
I saw that the documentation for DRF 3.12.0 was posted for a while, and then reversed.

We started using some of the new OpenAPI additions from master, figuring that if the documentation was posted, the release was not too far behind, but now that it's been reversed, I'm wondering if 3.12.0 has been pushed, or the changes that were documented were not complete?

Thanks!

**Comment by tomchristie** [comment]
We had been planning a release this month, but the universe kind of got in the way a bit.
We'll likely get it back on track soon enough.

I don't *think* we posted any 3.12.0 documentation.

**Comment by synic** [comment]
Hope you and yours are ok. Stay safe. <3

**Comment by synic** [comment]
@tomchristie Just as an FYI, the 3.12.0 documentation is back up.

https://www.django-rest-framework.org/api-guide/schemas/

![schema docs screenshot](http://synic.world/s/4d15573a.png)

```python
Python 3.8.2 (default, Jul 16 2020, 14:00:26) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.18.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from rest_framework.schemas.openapi import AutoSchema

In [2]: AutoSchema(tags=["test"])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-ceb2955bd3a2> in <module>
----> 1 AutoSchema(tags=["test"])

TypeError: __init__() got an unexpected keyword argument 'tags'

In [3]: import rest_framework

In [4]: rest_framework.__version__
Out[4]: '3.11.1'

In [5]: 
```
