### ISSUE TITLE
[Feature request] writable nested serializers via list_serializer_class

### ISSUE THREAD

**Issue by JEphron** [encode/django-rest-framework#7249]
The [docs](https://www.django-rest-framework.org/api-guide/serializers/#customizing-multiple-update) describe the difficulties of implementing "writable nested serializers" in a fully generic way, and instead recommend that you write a custom `ListSerializer` to capture the intended behavior. This works well enough:
```py
class BookListSerializer(ListSerializer):
    def update(self, instance, validated_data):
        ...

class BookSerializer(ModelSerializer):
    class Meta:
        list_serializer_class = BookListSerializer
        ...
```

however, consider the following (which fails):
```py
class LibrarySerializer(ModelSerializer):
    books = BookSerializer(many=True)
    ...

def update_library(library, books):
    s = LibrarySerializer(instance=library, data={'books': books}, partial=True)
    s.is_valid()
    s.save() # AssertionError: Write an explicit `.update()` method for serializer ...
```

I've already told DRF how I want `BookSerializer` to behave when asked to update a list, yet it doesn't use my implementation. Instead I must write the following boilerplate:

```py
class LibrarySerializer(ModelSerializer):
    books = BookSerializer(many=True)

    def update(self, instance, validated_data):
        books = validated_data.pop("books")

        ser = BookSerializer(
            instance=instance.books,
            data=books,
            many=True,
            partial=True,
        )
        ser.is_valid()
        ser.save()

        return instance

```

I'd like to propose that, if asked to perform a nested bulk update on a serializer with a `list_serializer_class` which contains an overridden `update`, DRF ought to use the `ListSerializer`'s update method by default. This would result in a significant reduction in boilerplate for projects that make heavy use of nested serializers.

**Comment by xordoquy** [comment]
When a serializer (`Library`) has a nested serializer (`Book`), you need to add an `update` method to `Library`, whether or not `Book` has one. The fact that `Book` has a `ListSerializer` and a valid `update` method is irrelevant here. See [this part of the doc](https://www.django-rest-framework.org/api-guide/serializers/#writing-update-methods-for-nested-representations) for a longer explanation.

**Comment by JEphron** [comment]
@xordoquy I've read the docs, and if I understand your explanation correctly the need to implement `update` on `Library` comes from the ambiguity of the list update operation in the general case. My point here is that in my example, the ambiguity is resolved (isn't it?) by the `ListSerializer`. Doesn't DRF have enough information to implement a sane `update` method in this case?

**Comment by JEphron** [comment]
I brought up this issue because I was considering trying to implement the described behavior, and I wanted to get a little discussion going.

**Comment by xordoquy** [comment]
@JEphron your use case does not cover books removed from the library for example. What you described is a subset of use cases which can be covered by an automagic method. Covering all the use cases automatically is much harder. We tried that back en 2.x and failed because there are too many use cases.

**Comment by JEphron** [comment]
@xordoquy Sure, I'm not suggesting that we cover everything automatically. I know that's hard, and I respect that DRF refuses to do something that might catch users by surprise. What I'm suggesting is that we allow the user to resolve the ambiguity in a way that makes sense for their use case.

If I write an `update` method for a `ListSerializer` I'm saying *"here is how I want you to update this list. This is how I want to handle removal, duplicates, reordering, etc"*. 

The fact that I've overridden the `update` method means I've (hopefully) thought about how I want to handle the edge cases. I'm asserting to the framework that I know what I'm doing. 

My main gripe is that the following boilerplate becomes exhausting when there are multiple nested serializers:
```py
class LibrarySerializer(ModelSerializer):
    books = BookSerializer(many=True)

    def update(self, instance, validated_data):
        books = validated_data.pop("books")

        ser = BookSerializer(
            instance=instance.books,
            data=books,
            many=True,
            partial=True,
        )
        ser.is_valid()
        ser.save()
```

Do you think it would be safe to automatically do something like that when the user has explicitly decided on a strategy for handling nested updates?

**Comment by rpkilby** [comment]
> Do you think it would be safe to automatically do something like that when the user has explicitly decided on a strategy for handling nested updates?

The framework wouldn't be able to know that the serializer has a strategy for handling nested updates specifically.

**Comment by JEphron** [comment]
> The framework wouldn't be able to know that the serializer has a strategy for handling nested updates specifically.

Isn’t that one of the two primary reasons why you’d write your own ListSerializer? The docs sort of push people towards just using `many=True` unless you either need nested updates or custom validation. The fact that when you follow the recommendations you still have to write potentially hundreds of lines of boilerplate seems a little awkward. 

If you’ve set `list_serializer_class` on the child model then it seems very likely indeed that you intend to use it with `many=True`, and if you’ve implemented `update` on the `ListSerializer` then either you’re handling the edge cases or you’ve got a broken `update`, right? I’m trying to think of a case where it wouldn’t be a clear signal to opt-in to nested updates. 

Just feels like I’m fighting the framework when it should be able to help me out.

**Comment by xordoquy** [comment]
> Isn’t that one of the two primary reasons why you’d write your own ListSerializer?

not at all. `ListSerializer` are meant to deal with multiple 1st level updates. Multiple nested updates are handle through overriding the 1st level serialiser's update.

**Comment by benzkji** [comment]
I'm with @JEphron - stumbling over the exact same things. Using a list serializer would make my code so much more readable and re-usable. Maybe at least clearing things up in the docs would be nice, then?

**Comment by benzkji** [comment]
using drf-writable-nested now. works ok!
