### ISSUE TITLE
Upcoming OpenAPI improvements are missing schema generation for custom fields

### ISSUE THREAD

**Issue by synic** [encode/django-rest-framework#7252]
Maybe I'm jumping the gun here.

We've been using the new changes for a bit now, and everything works great. The only thing that we're missing is the ability to generate a proper schema for custom serializer fields.

For now, we've been doing this:

```python

class AutoSchema(openapi.AutoSchema):
    """Extension of ``AutoSchema`` to add support for custom field schemas."""

    def _map_field(self, field):
        if hasattr(field, "get_schema") and callable(field.get_schema):
            return field.get_schema()

        return super()._map_field(field)
```

Hoping to bring it to your attention before the official release.

**Comment by carltongibson** [comment]
Hi @synic. 

You're welcome to inject API into fields this way if you like, but it's not what I'd recommend. The `Field` API is already very large. Adding extra hooks (just) for schema generation isn't the way we want to go. 

Rather we try to encapsulate everything schema related inside AutoSchema (or SchemaGenerator, depending on the level, but AutoSchema here...) 

So, yes, override `_map_field()` — we'll make that public for 3.12, so `map_field()` without the `_` — but teach your subclass about your custom field types, and set that as the global default if you're using those everywhere. 

I'm working on the docs for this now, so I'll leave this open to see if I can add an example for this.

**Comment by carltongibson** [comment]
OK, docs drafted. Will close to keep my TODO functioning.

**Comment by synic** [comment]
Thanks! That commit has a typo, I commented on it.
