### ISSUE TITLE
OpenAPI schema invalid for re_path

### ISSUE THREAD

**Issue by clintonb** [encode/django-rest-framework#7255]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
1. Create an app with `urls.py` like this:

```python
urlpatterns = router.urls
urlpatterns += [
    # TODO Use some other ViewSet. The path is what is most important here.
    re_path(r'^email-hmac/(?P<key>[-:\w]+)', views.EmailHmacView.as_view(), name='email_hmac'),
]
```

2. Render the OpenAPI schema.

## Expected behavior
The schema should render the path as `/api/v1/email-hmac/{key}:`.

## Actual behavior
The schema renders the path as `/api/v1/email-hmac/(P{key}[-:\w]+):`.

The rendered path is completely invalid. My current workaround is to ditch the `re_path`, and return a 404 from the view if the value does not match the regex.

**Comment by smithdc1** [comment]
Hi @clintonb 

I've tried to replicate this issue. I've written the following test; however, as it passes I must not be understanding your issue correctly. Are you in a position to help develop this test so it demonstrates the reported issue? 

``` python
---
 tests/schemas/test_openapi.py | 14 +++++++++++++-
 1 file changed, 13 insertions(+), 1 deletion(-)

diff --git a/tests/schemas/test_openapi.py b/tests/schemas/test_openapi.py
index d483f3d4..2f8aa2bd 100644
--- a/tests/schemas/test_openapi.py
+++ b/tests/schemas/test_openapi.py
@@ -2,7 +2,7 @@ import uuid
 import warnings
 
 import pytest
-from django.conf.urls import url
+from django.conf.urls import re_path, url
 from django.test import RequestFactory, TestCase, override_settings
 from django.utils.translation import gettext_lazy as _
 
@@ -1110,3 +1110,15 @@ class TestGenerator(TestCase):
         schema = generator.get_schema(request=create_request('/'))
         assert 'components' not in schema
         assert 'content' not in schema['paths']['/example/']['delete']['responses']['204']
+
+    def test_schema_re_path(self):
+        router = routers.SimpleRouter()
+        router.register('account', views.ExampleGenericViewSet, basename="account")
+        urlpatterns = router.urls
+        urlpatterns += [
+            re_path(r'^email-hmac/(?P<key>[-:\w]+)', views.ExampleDetailView.as_view(), name='email_hmac'),
+        ]
+        generator = SchemaGenerator(patterns=urlpatterns)
+        schema = generator.get_schema()
+        schema_str = str(schema)
+        assert schema_str.count("email-hmac/{key}") == 1
-- 
```

Note: This patch is also is committed to this [branch](https://github.com/smithdc1/django-rest-framework/tree/7255)

**Comment by peterthomassen** [comment]
A similar thing happens with [this code](https://github.com/desec-io/desec-stack/blob/main/api/desecapi/urls/version_1.py#L34-L35)

```python
re_path(r'^domains/(?P<name>[^/]+)/rrsets/(?P<subname>[^/]*)\.\.\./(?P<type>[^/]+)/$', views.RRsetDetail.as_view(), name='rrset'),
```

which renders as `domains/{name}/rrsets/{subname}\.\.\./{type}/` in the schema. The backslashes `\` are incorrect.

Related: https://github.com/desec-io/desec-stack/issues/359#issuecomment-865365725

**Comment by peterthomassen** [comment]
@smithdc1 David, are you able to reproduce what I described in https://github.com/encode/django-rest-framework/issues/7255#issuecomment-870606086?

**Comment by smithdc1** [comment]
Hi @peterthomassen  apologies, it's unlikely I'm going to get time to look at this again any time soon.

**Comment by abhinavsingh** [comment]
For posterity, here is another example where regular expressions fail to pass the validator.  This is an issue I noticed when using `apistar`.   Seems to pass validation when using `openapi` python library.

<img width="1205" alt="Screen Shot 2022-05-30 at 9 45 20 AM" src="https://user-images.githubusercontent.com/126065/170916440-8a155695-83db-4f2d-9592-11c505ea2aad.png">

**Comment by peterthomassen** [comment]
I think this is stilt current.
