### ISSUE TITLE
Functionality to add more fields to the models

### ISSUE THREAD

**Issue by Philipotieno** [encode/django-rest-framework#7256]
## Checklist

- [ ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [ ] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

Assuming I have a model **User** with fields _first_name_, _last_name_, and _contact_ 
I want to have a system where if at any point the admin user will want to add other fields that were not captured he/she should be able to add them at will
assuming he wants to add _age_ or _email_

how can I achieve this

**Comment by tomchristie** [comment]
Hi there & thanks for your question.

The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions.

Thanks! 😀
