### ISSUE TITLE
put not allowed

### ISSUE THREAD

**Issue by hian18** [encode/django-rest-framework#7261]
## Checklist

- [ ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [ ] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Actual behavior

@api_view(["PUT"])
@parser_classes([MultiPartParser])
def update_user(request, pk):

    serializer = CreateCustomUserSeralizer(data=request.data)
    serializer.is_valid(raise_exception=True)

    user = CustomUser.objects.filter(id=int(pk)).first()
    if not user:
        user = CustomUser()

    user.roles = serializer.validated_data.get("roles", "")
    user.email = serializer.validated_data["email"]
    foto = serializer.validated_data.get("foto", None)

    file = Files.objects.filter(guid=user.foto).first()

    if foto and file:
        file.file = foto.read()
        file.tipo = foto.content_type
        file.save()

    elif foto:
        file = Files()
        file.file = foto.read()
        file.guid = str(uuid.uuid4())
        file.tipo = foto.content_type
        user.foto = file.guid
        file.save()

    else:
        file.delete()
        user.foto = None

    user.set_password(serializer.validated_data["password"])
    user.username = serializer.validated_data["username"]
    user.save()

    return Response(CustomUserSeralizer(user).data, status=status.HTTP_200_OK)

the method put is ever not allowed

**Comment by tomchristie** [comment]
Hi there. I'd suggest starting out on the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) as the best place to take this question.

It's not sufficiently clear from the issue here exactly what behaviour you're actually seeing, or if there's a bug that we ought to spend our time trying to replicate.
