### ISSUE TITLE
JSONFiled to_internal_value

### ISSUE THREAD

**Issue by zsh1995** [encode/django-rest-framework#7267]
https://github.com/encode/django-rest-framework/blob/b2497fc2456c607a3c639ed2355c28dac672a70f/rest_framework/fields.py#L1815

I think it should be 
`data = json.dumps(data, cls=self.encoder)`
Otherwise, what does the current code do?

**Comment by rpkilby** [comment]
In some cases, the given data is a decoded JSON object. This check is ensuring that the data is valid. We don't need the dumped result - we want to return the existing object if it validates.
