### ISSUE TITLE
Update to jQuery 3.5.0

### ISSUE THREAD

**Issue by shrew4u2do** [encode/django-rest-framework#7270]
jQuery 3.5.0 has been released and fixes a security issue that some security scanners complain about:
https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/

**Comment by auvipy** [comment]
related to jQuery and bootstrap https://github.com/twbs/bootstrap/issues/30553

**Comment by rpkilby** [comment]
We'll need to verify if that's a concern, given that we're still on bootstrap 3.4.x

**Comment by auvipy** [comment]
https://github.com/twbs/bootstrap/pull/30709

**Comment by pauloxnet** [comment]
In the meantime jQuery 3.5.1 was released yesterday
https://blog.jquery.com/2020/05/04/jquery-3-5-1-released-fixing-a-regression/

**Comment by auvipy** [comment]
and we should also wait for bootstrap 4.4.2 release

**Comment by auvipy** [comment]
i opened a PR

**Comment by auvipy** [comment]
this can be closed now!

**Comment by auvipy** [comment]
https://blog.getbootstrap.com/2020/05/12/bootstrap-4-5-0/
