### ISSUE TITLE
Documentation Allow Empty is not correct

### ISSUE THREAD

**Issue by rvanlaar** [encode/django-rest-framework#7274]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
The documentation specifies that `allow_empty` is `True` by default.

See the following code. It's default is `False` for a Postgres ArrayField:
https://github.com/encode/django-rest-framework/blob/master/rest_framework/utils/field_mapping.py#L113-L114

## Expected behavior

Either `allow_empty` to be `True` or updated documentation.

## Actual behavior

`allow_empty` is `False`

**Comment by xordoquy** [comment]
The default is `True` except when specified otherwise.
In the current case, it does not make sense to allow an empty list if the associated model says the field can not be blank.

**Comment by xordoquy** [comment]
To make it clearer, the [source](https://github.com/encode/django-rest-framework/blob/master/rest_framework/utils/field_mapping.py#L113-L114) says `allow_empty` will be `False` if it is mapped on a Postgres ArrayField *and* the mapped field blank value is `False`.

**Comment by rvanlaar** [comment]
@xordoquy  Please show me then where the documentation mentions this.

**Comment by xordoquy** [comment]
I don't think the documentation mentions how the mapping is performed between a model and the serializer at all.
Likely a good addition that should cover the various options (`required`, `allow_null`, `read_only`and so on).
