### ISSUE TITLE
Please change default None value behaviour in to_representation

### ISSUE THREAD

**Issue by velis74** [encode/django-rest-framework#7277]
## Checklist

- [ X ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [ X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ X ] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ X ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [ n/a ] I have reduced the issue to the simplest possible case.
- [ n/a ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

I would like to ask for consideration of changing processing of None values from serailizer's to_representation to Field's to_representation.

A quick search turned up three issues that seem to have been caused by current implementation / design decision: #3451, #5124, #5635

The problem lies in [lines 505 - 513](https://github.com/encode/django-rest-framework/blob/8cba4f87ca8e785d1a8c022a7a8ea9649e049c11/rest_framework/serializers.py#L505-L513) of serializers.py. (I just took the latest commit right now to link to)

The serializer decides here to handle None value for the fields, forcing fields to override any or all of  get_attribute, to_internal_value and to_representation - if they need to handle it themselves.

I would ask for a change where this particular check was moved to Field.to_representation so that fields can choose freely how to handle None values.

I realise the danger of existing implementations not taking this into account, so I propose adding a property / method to fields that would tell the serializer NOT TO process None value. Also, current design decision is a bit imperialistic towards the poor fields, don't you think? :wink: 

Thanks for your consideration.

Edit: P.S.: I am willing to make the PR myself, but will only start on it if proposal is accepted.

**Comment by tomchristie** [comment]
I think it's *unlikely* that we'd accept a change here. If we *did* it'd need to be driven by a demonstration that of an alternate implementation that continues to pass the existing test cases, and a clear example use-case that it'd help improve.

If there's a demonstration along those lines then perhaps it's something we'd be able to consider.

**Comment by velis74** [comment]
Thank you very much for considering it at least. My particular use case was same as for #5124 - we were converting a timestamp into boolean where a null meant False. We were doing it within a serializermethodfield.

However current implementation requires us to override serializer's to_implementation, as that seems to be the cheapest.
I'd really hate to use some NotReallyNoneButStillNone class-type solutions to transport around the framework between get_attribute and to_representation of the field itself, so I opted against it. Right now, the original function is basically just these two items: handling none and serializing if it is not none.

The passing of existing tests requirement is easy and I could take care of it. Finding a good & clear use case that will appeal to core developers isn't so easy, so I'll just let our own unit tests tell us when a breaking change has been introduced into either of the projects.
