### ISSUE TITLE
Using and, or, not in DjangoModelPermissions perms_map

### ISSUE THREAD

**Issue by aminst** [encode/django-rest-framework#7280]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)
## Description
In DjangoModelPermissions we can use perms_map to include django permissions
as following:
https://github.com/encode/django-rest-framework/blob/8cba4f87ca8e785d1a8c022a7a8ea9649e049c11/rest_framework/permissions.py#L177-L185
but the problem is there is no AND, OR, NOT provided in this part
because of this, you have to define lots of inherited classes from DjangoModelPermissions and use and, or, not in permission_classes

## Example
let assume that we have following django permissions:
_django_permission_A_, _django_permission_B_
I would like to have a permission on GET method like this:
```
perms_map = {
GET: ["django_permission_A" | "django_permission_B"]
}
```

this is not supported right now and I have to do sth like this:
I must define two individual classes inherited from DjangoModelPermissions
```
class CustomPermA(DjangoModelPermissions):
    perms_map = {
        GET: ["django_permission_A"]
    }

class CustomPermB(DjangoModelPermissions):
    perms_map = {
        GET: ["django_permission_B"]
    }
```
this must be used like this in a view:
```
class TestView(APIView):
    permission_classes = [CustomPermA|CustomPermB]
```
I would like to use AND, OR, NOT in perms_map so I don't have to define lots of unneccassery inherited classes in my codebase and make the permission_classes part complicated

THANKS FOR READING

**Comment by tomchristie** [comment]
If anything I think the more constrained scope of `DjangoModelPermissions` here is more fit for purpose.

If you'd like to do something more complex here, you'll need to implement a custom permission class.
