### ISSUE TITLE
run_validation for RelatedField or ChoiceField failed with 'does_not_exist' when value is 0

### ISSUE THREAD

**Issue by eshxcmhk** [encode/django-rest-framework#7282]
When the field type of RelatedField or ChoiceField is int, you can provide an argument to treat the value 0 as None, because variables of type int in advanced programming languages default to 0 and cannot be null, but in the database 0 and null have different meanings

**Comment by tomchristie** [comment]
> "provide an argument to treat the value 0 as None"

Not totally sure I understand the request correctly, but I think this is a fairly niche. You'd need to create a custom field type to deal with this.
