### ISSUE TITLE
Api Root is wrong

### ISSUE THREAD

**Issue by xiaopanggege** [encode/django-rest-framework#7296]
My project install in docker

Browser access http://139.9.115.10:8000/ return Api Root page

content is as follows:

HTTP 200 OK
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
"dashboard": "http://139.9.115.10/dashboard/",
"userinfo": "http://139.9.115.10/userinfo/",
"saltstack/salt-key": "http://139.9.115.10/saltstack/salt-key/",
"saltstack/salt-key-opt/accept": "http://139.9.115.10/saltstack/salt-key-opt/accept/",
"saltstack/salt-key-opt/delete": "http://139.9.115.10/saltstack/salt-key-opt/delete/",
"saltstack/salt-key-opt/reject": "http://139.9.115.10/saltstack/salt-key-opt/reject/",
"saltstack/salt-key-opt/del-denied": "http://139.9.115.10/saltstack/salt-key-opt/del-denied/",
"saltstack/salt-minion": "http://139.9.115.10/saltstack/salt-minion/",
"saltstack/salt-minion-opt/status-update": "http://139.9.115.10/saltstack/salt-minion-opt/status-update/",
"saltstack/salt-minion-opt/update": "http://139.9.115.10/saltstack/salt-minion-opt/update/",
"saltstack/salt-cmd": "http://139.9.115.10/saltstack/salt-cmd/"}

This is wrong , The url is missing port 8000,What's going on here?

**Comment by tomchristie** [comment]
Hi there & thanks for your question.

The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions.

Thanks! 😀
