### ISSUE TITLE
Avoid inlined responses in schema for paginated results in AutoSchema

### ISSUE THREAD

**Issue by l0rn** [encode/django-rest-framework#7299]
## Checklist

- [X] I have verified that that issue exists against the `master` branch of Django REST framework.
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [X] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [X] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Context

Currently `AutoSchema` will call `get_paginated_response_schema` from any configured Paginator. Not having access to the components section of the schema the behavior of the included paginators is just to create an inline response like so: https://github.com/encode/django-rest-framework/blob/05a59095cef36f672eaa630881ce5c2175f3eeaa/rest_framework/pagination.py#L228-L252

Inlined responses cause bad developer experiences if you plan to use automatic client type generators like [this](https://github.com/OpenAPITools/openapi-generator). It'd create types like `InlinedResponse000`. So a better solution would be to a new component of your new paginated component response and reference that. 

I have a local solution for this below, generating the paginated component in `AutoSchema.get_components` and referencing it in `AutoSchema.get_responses`, but i am not sure whether this holds as a generalized solution. I'd like to hear a word from maintainers if this is something they'd accept as PR before I will make the effort.

My solution:
https://github.com/l0rn/django-minutes/blob/9cf2b85bb48f7f4af7d7f9a07753dc4bde95b8d3/minutes/schema.py#L6-L61

## Steps to reproduce

* Create a paginated ListView
* generate schema using AutoSchema

## Expected behavior

Paginated responses are also references to components:
```
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/MeetingSeriesResponse"
                }
              }
            },
            "description": ""
          }
        },
[...]
	"components": {
		"schemas": {

			"MeetingSeriesResponse": {
				"type": "object",
				"properties": {
					"count": {
						"type": "integer",
						"example": 123
					},
					"next": {
						"type": "string",
						"nullable": true,
						"format": "uri",
						"example": "http://api.example.org/accounts/?offset=400&limit=100"
					},
					"previous": {
						"type": "string",
						"nullable": true,
						"format": "uri",
						"example": "http://api.example.org/accounts/?offset=200&limit=100"
					},
					"results": {
						"type": "array",
						"items": {
							"$ref": "#/components/schemas/MeetingSeries"
						}
					}
				}
			}
		}
	}

```

## Actual behavior

Paginated responses look like this (inlined):
```
"responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "count": {
                      "type": "integer",
                      "example": 123
                    },
                    "next": {
                      "type": "string",
                      "nullable": true,
                      "format": "uri",
                      "example": "http://api.example.org/accounts/?offset=400&limit=100"
                    },
                    "previous": {
                      "type": "string",
                      "nullable": true,
                      "format": "uri",
                      "example": "http://api.example.org/accounts/?offset=200&limit=100"
                    },
                    "results": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/User"
                      }
                    }
                  }
                }
              }
            },
            "description": ""
          }
        },
```

**Comment by carltongibson** [comment]
Hi @l0rn. Interesting. 

Not initially sure what to say here. 

We started with everything inline. We're moving the body elements (the obvious candidates) to components. That's expected. 

Having the response structures as components seems a little like overkill. Q: Why is OpenAPIGenerator so keen on having them there?

**Comment by l0rn** [comment]
When generating the interfaces you need to name it, best case meaningful. If the response is a component  you naturally can take the component name, in inlined responses there is no way to reliably deduct a  meaningful name, therefore the fallback to "InlineResponse#####"

**Comment by carltongibson** [comment]
> When generating the interfaces...

You mean like for Java classes? Is this not purely internal? I'm expecting the user facing parts to be OperationIDs...

**Comment by l0rn** [comment]
> > When generating the interfaces...
> 
> You mean like for Java classes? Is this not purely internal? I'm expecting the user facing parts to be OperationIDs...

Whatever output language you chose, could be java, could be typescript or any other supported language.
It creates types from the openAPI specification, and if it's missing a component name the fallback takes place.

Look at this output generated by a inlined response from openAPI specs:

```

**Comment by carltongibson** [comment]
OK, good. That is much clearer to read. 

Is there a benefit to making all responses components (or just where their are additional fields, i.e. when we paginate)?

**Comment by l0rn** [comment]
Apart from naming consistency i think not as in case of an unpaginated response equals the item schema...

But I can imagine that creating a component from a response as a general rule would avoid this issue with potential other fields that become part of the response (i.e. enveloping, HATEOAS or whatever). So in many cases we'd get duplicates like `User == UserDetailResponse` but in other cases those might not be the same therefore benitfiting

**Comment by carltongibson** [comment]
OK... so, yes, happy to think about this. If you'd like to work on a PR, that would be great. 

Thanks for the report!

**Comment by carltongibson** [comment]
> So in many cases we'd get duplicates like User == UserDetailResponse but in other cases those might not be the same therefore benitfiting

Not sure I followed you 100% but using operationID and part of the component name might be sufficient, so operationIDResponse and such. Anyhow... to the codes. :)

**Comment by l0rn** [comment]
> > So in many cases we'd get duplicates like User == UserDetailResponse but in other cases those might not be the same therefore benitfiting
> 
> Not sure I followed you 100% but using operationID and part of the component name might be sufficient, so operationIDResponse and such. Anyhow... to the codes. :)

Ye sure, it's straight forward to just use the operationID - I can look into making a PR later this day
