### ISSUE TITLE
Schema : override auto-generated tags 

### ISSUE THREAD

**Issue by ajlif** [encode/django-rest-framework#7300]
## Checklist

- [ *] I have verified that that issue exists against the `master` branch of Django REST framework.
- [ *] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [* ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [ *] I have reduced the issue to the simplest possible case.
- [* ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

DRF schema , i would like to override auto generated tags in yaml file

## Expected behavior
override auto-generated tags by passing tags argument to the constructor of AutoSchema. tags argument must be a list or tuple of string.

My example :
```
class ExampleViewSet(viewsets.ViewSet):
    schema = AutoSchema(tags = ['tag1', 'tag2'])
    permission_classes = (IsAuthenticated,)
    ...
```
## Actual behavior
AutoSchema: AutoSchema
Unexpected keyword argument 'tags' in constructor call

**Comment by carltongibson** [comment]
This will be part of 3.12, which we're preparing now. You can install the `master` branch if you'd like to use it already.
