### ISSUE TITLE
Missing "HTTP_AUTHORIZATION" header in META if the permission class is AllowAny

### ISSUE THREAD

**Issue by jasonjiang8866** [encode/django-rest-framework#7301]
When my permission class is AllowAny, the "HTTP_AUTHORIZATION" key doesnt exist in the request.META dictionary when the request is using basic auth.
Is this expected behavior? Thank you!

**Comment by xordoquy** [comment]
DRF doesn't pop that header from `request.META`. I suggest you try the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) which is the best place to take this discussion and other usage questions. Thanks!
