### ISSUE TITLE
UserPassesTestMixin with ModelViewSet not working

### ISSUE THREAD

**Issue by tasawar-hussain** [encode/django-rest-framework#7304]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
This does not work, the `test_func` is never called,
```
class OrganizationViewSet( viewsets.ModelViewSet, UserPassesTestMixin,): 
    def test_func(self):
        return self.request.user.is_admin
```

Declare a class and override` test_func`
```
class OrganizationViewSet(UserPassesTestMixin, viewsets.ModelViewSet,): 
    def test_func(self):
        return self.request.user.is_admin
```
This works, While accessing the user, I `get the SimpleLazyObject` instead of auth user.

**Comment by rpkilby** [comment]
Hi @tasawar-hussain. Ordering of base classes is important, and mixins should typically precede base implementations. `UserPassesTestMixin` works by overriding `dispatch`, however `APIView.dispatch` does not call up it's mro chain, so it makes sense that `(viewsets.ModelViewSet, UserPassesTestMixin)`  works while `(UserPassesTestMixin, viewsets.ModelViewSet)` does not.
