### ISSUE TITLE
Format kwarg not set in APIView using URL parameter

### ISSUE THREAD

**Issue by camuthig** [encode/django-rest-framework#7308]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

1. Create a APIView class, checking the `self.format_kwarg` value in the `get` method
1. Send a request to the route as `/my-route?format=json`

## Expected behavior

When sending the `?format=json` parameter, the `format_kwarg` value should be set based on that value, which will also then be applied to any serializers.

## Actual behavior

When sending the `?format=json` parameter, the renderer is correctly set to a JSON renderer, but the `format_kwarg` and therefore the `context['format']` in the serializers is `None`. The only way to set this value is using the format suffix.

**Comment by xordoquy** [comment]
`format_kwarg` contains the `format` extracted from the urls `kwargs` - ie for urls such as `/my-route.json`. Since it is a "private" attribute, I don't see any reason to use it.
Beside, the documentation advises the use of a `format` keyword argument for the view methods and does not mention `format_kwargs`.
What use case would require  `format_kwargs` to be filled for url parameters ?

**Comment by camuthig** [comment]
The place I attempted to use this value was in my serializer. I ran into a case where I wanted to know the expected format in the serializer to alter behavior (in this case in the `to_representation` function). I based this logic on how the `HyperlinkedRelatedField` determines the format, using the `context`. However, the default `get_serializer_context` for the `GenericAPIView` passes this context to serializers as `self.format_kwarg`. For this same reason, I can understand why this could be problematic, because the `HyperlinkedRelatedField` is both preserving the URL params and adding the context format as a suffix if provided.

So in theory, this could be solved by overwriting the `get_serializer_context` function in my own classes and passing in either `format` or my own key or using the context's request to check for it, but it felt like something that could possibly work by default instead.

As for using the `format` kwarg, it is only available when using the suffix pattern. And while the documentation mostly suggests using the suffix pattern, it does mention support for the query param. Moreover, the URLs generated by the API documentation build the request with the query param instead of the suffix.

**Comment by tomchristie** [comment]
You'll need to take some other tack onto this.

The format_kwarg is populated with any URL path keyword arguments, and is used in order to ensure that any reverse URL lookups on hyperlinked URLs can also include the suffix if appropriate. Changing it to also indicate the value of a `format` query parameter would break that behavior.

**Comment by camuthig** [comment]
Thanks for providing your feedback @xordoquy and @tomchristie . I really appreciate it. Based on that, I believe the correct way to determine the expected format inside of a serializer would look something like this. Mostly documenting this for myself and anyone else who might run across this concept.

```python
    # Inside of a Serializer
    def _format(self) -> Optional[str]:
        format = self.context.get('format', None)

        if format is None and settings.URL_FORMAT_OVERRIDE is not None:
            request = self.context['request']
            format = request.query_params.get(settings.URL_FORMAT_OVERRIDE)

        return format
```

**Comment by xordoquy** [comment]
The format is told by the content negotiation and set as parser/renderer.
What you are trying to do here is adapt the way the format was provided. As such, `format_kwarg` will indicate it's been set as `.<format>` while `request.query_params.get('format')` will indicated it's been set as `?format=<format>`.

**Comment by camuthig** [comment]
@xordoquy I'm just trying to figure out what the requested "format" is within my serializer. I'm not entirely sure the best way to do that, though. 

From the sounds of it, you suggest using the `renderer` for that purpose, and, if I am reading the code correctly, that renderer is set as a property on the DRF `request`? So within my serializer I would be able to do a `self.context['request'].renderer.format`?
