### ISSUE TITLE
Improve get_path_parameters()

### ISSUE THREAD

**Issue by Mopsan** [encode/django-rest-framework#7311]
Hi, if use Class-based Views

```
def get(self, request: object, tax_number: int):
    """
    Return a client full name.

    :param (object) request: Request
    :param (int) tax_number: Tax Number
    """
```

is it possible for parameters, description and type to be generated using fuction description, e.g.

```:param (int) tax_number: Tax Number```

generated to

```
"parameters": [
    {
        "name": "tax_number",
        "in": "path",
        "required": true,
        "description": "Tax Number",
        "schema": {
          "type": "int"
        }
    }
],
```

and not include to generated schema if __doc__ line is ```:param (object) request: Request```

**Comment by tomchristie** [comment]
Hi there & thanks for your question.

The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions.

Thanks! 😀
