### ISSUE TITLE
Documentation for the action decorator

### ISSUE THREAD

**Issue by regzon** [encode/django-rest-framework#7316]
Hello there. Sorry for not using the issue template, but I think it is not suitable in this situation.

I want to ask if there exists detailed documentation about the `@action` decorator. It wasn't easy to find out which arguments I can pass in it. For example, I needed to pass a `serializer_class` inside but found out that I can do it only after searching for issues on Github.

**Comment by xordoquy** [comment]
The documentation isn't very explicit about that:

> The decorator can additionally take extra arguments that will be set for the routed view only. 

Mostly, it'll take any generic view class argument but that should be stated explicitly.

**Comment by PawelMorawian** [comment]
I agree that the documentation isn't very explicit about that.
You can check the method  docstring which provides more information : https://github.com/encode/django-rest-framework/blob/master/rest_framework/decorators.py#L123

**Comment by PawelMorawian** [comment]
@carltongibson I can take care of this

**Comment by jhabarsingh** [comment]
can I work on this issue ?

**Comment by regzon** [comment]
Thank you for your work. I think that there still exists a problem with `serializer_class` - the description says that all `*_classes` parameters are acceptable, but the parameter `serializer_class` doesn't fit this regular expression :)

**Comment by xordoquy** [comment]
Following your comment, I added a suggestion on #7380

**Comment by xordoquy** [comment]
Closed by #7380
