### ISSUE TITLE
OpenAPI action endpoints doesn't follow name convetion

### ISSUE THREAD

**Issue by C0DK** [encode/django-rest-framework#7318]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Create a `action` endpoint on a ApiView:
```python
class CustomViewSet(viewsets.ModelViewSet):

    @action(detail=True, schema=None)
    def extra_action(self, request, pk=None):
        pass
```
This will generate the following operationId:
`extra_actionCustomViewSet` - which should be `extraActionCustomViewSet`.

## Expected behavior
The name should follow the openApi naming convention (camalCase)

## Version
3.11.0
Django 3.0.5

**Comment by C0DK** [comment]
Hmm this is weird. using the inspect package it seems that i have an older version loaded into my interpreter, however it says to be running 3.11... the `get_operation_id` function doesn't exist locally on `AutoScheme`, instead i have `_get_operation_id`, which doesn't call `_camal_case`.

**Comment by C0DK** [comment]
This should fix it, https://github.com/encode/django-rest-framework/blob/b2497fc2456c607a3c639ed2355c28dac672a70f/rest_framework/schemas/openapi.py#L256

However i don't have this line locally. I just purged my venv and reinstalled DRF, but still don't have that line. Not sure what is going on here.

**Comment by C0DK** [comment]
https://github.com/encode/django-rest-framework/commit/6a23fa06495c6010239dda926f55f2d6baa79cf3 fixed by this - so never mind.

And I realize that my inability to use it, is that these new features hasn't been released. Would love for them to be released though. :P

**Comment by carltongibson** [comment]
Hi @C0DK. It's coming. We've been a bit delayed by the pandemic. [You can install master with pip if you're keen](https://pip.pypa.io/en/stable/reference/pip_install/#git). 🙂

**Comment by C0DK** [comment]
Thanks :) Pandemic is a good reason to be delayed :P
