### ISSUE TITLE
dirty architecture for your framework sham on your developers

### ISSUE THREAD

**Issue by lusicsmusics** [encode/django-rest-framework#7322]
your platform is not seems good in first look ,and the person not intersted even test it first time ,
you wrote very dirty and bad-place config and starting project and sharp and intelligent developers not attracted to it

**Comment by tomchristie** [comment]
Love you too. 😘

**Comment by auvipy** [comment]
I strongly disagree with you. it's the best thing on python API area :) thanks tom <3
