### ISSUE TITLE
the most shit web framework in the word if you don't accept  i can prove it for you

### ISSUE THREAD

**Issue by lusicsmusics** [encode/django-rest-framework#7323]
the most shit web framework in the word if you don't accept  i can prove it for you

**Comment by tomchristie** [comment]
Aw, you’re such a charmer.
Thanks, hon. 💚

**Comment by tomchristie** [comment]
@lusicsmusics Okay, I kinda wanted to keep enjoying this, but seemed a little mean, so I’ve blocked you for your own sake. 👍

**Comment by agktogether** [comment]
@tomchristie if you close the door i will get in on window

**Comment by agktogether** [comment]
any way your platform is not sttractive when  we see it first time and hence there are many reliable web framworks we love them when we look at them first time and for always, if you want to be alive in the world just learn from them

**Comment by tomchristie** [comment]
![giphy](https://user-images.githubusercontent.com/647359/81538028-05b64500-9366-11ea-9316-3851bdea996a.gif)
