### ISSUE TITLE
How create a tab that will open after payments is done

### ISSUE THREAD

**Issue by alladinlebrone** [encode/django-rest-framework#7339]
Hello
I request for assistance
I am new in python and I have a project with django.
How can someone create a tab which after payment of the desired thing it gets open
Example I cant view this house unless I make a payment.
When I make a payment the tab allows me to view the house
Kindly help

**Comment by tomchristie** [comment]
Hi there & thanks for your question.

The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions.

Thanks! 😀

**Comment by alladinlebrone** [comment]
Hello,
Kindly share with me any discussion groups.

Regards
