### ISSUE TITLE
Make Charset Configurable For application/json

### ISSUE THREAD

**Issue by rotherfuchs** [encode/django-rest-framework#7340]
As declared in `renderers.py`, line `64-67`, DRF will always set `charset=None` for Content-Type `application/json` for the given reasons:
```
# We don't set a charset because JSON is a binary encoding,
# that can be encoded as utf-8, utf-16 or utf-32.
# See: https://www.ietf.org/rfc/rfc4627.txt
# Also: http://lucumr.pocoo.org/2013/7/19/application-mimetypes-and-encodings/
charset = None
```

However, people might be dealing with the situation that certain clients (a mobile app in my case) *require* a charset statement in order to properly work. IMHO this is a typical _do-things-right vs make-things-work_ conflict. 

This could easily be fixed by allowing to somehow (statically) configure the charset either in `settings.py` or by just echoing a charset stated in the `Accept` Header.

**Comment by tomchristie** [comment]
I’m going to recommend you use a custom renderer class if you need different behaviour.
