### ISSUE TITLE
Validate specific field on query_params

### ISSUE THREAD

**Issue by tuanden0** [encode/django-rest-framework#7342]
I wonder if I could validate specific field by using method POST something such as: 
http://myapi/app.?validate_specific_field=value

eg: http://myapi/app/?validate_username=some_name

To validate each field when user input on frontend from instead of validate all field to be filled and submit?

**Comment by carlosdamazio** [comment]
Using POST without body params seems that you're asking for trouble. Why don't you validate on both front-end for some params and back-end for all params using serialization?

**Comment by tomchristie** [comment]
Hi there & thanks for your question.

The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions.

Thanks! 😀
