### ISSUE TITLE
Not showing latest records unless i restart the server

### ISSUE THREAD

**Issue by Simouche** [encode/django-rest-framework#7343]
I'm using django rest framework, to create and retrieve records, but I noticed that when I create a new record and then try to fetch the list of records it doesn't show in the list of records even after 24h, unless I restart the gunicorn server.

I think it has something to do with caching, but I didn't find anything intresting in the documentation about caching.

I want to keep the caching as it is good for performance... but I want the new records to show, is there anyway to refresh the cache after a record is added? or anything similar?

**Comment by xordoquy** [comment]
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!

**Comment by Simouche** [comment]
> The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
> Most likely your code is missing a lazy evaluation somewhere.

here is the code, i didn't change so much:

  `     class RecipeViewSet(ModelViewSet):

            serializer_class = RecipeSerializer
            queryset = Recipe.objects.all().order_by('-created_at')
            permission_classes = [permissions.IsAuthenticatedOrReadOnly]

        def create(self, request, *args, **kwargs):
            request.data['published_by'] = Participant.objects.get(profile__owner__id=request.data['published_by']).pk
            return super(RecipeViewSet, self).create(request, *args, **kwargs)

        def get_queryset(self):
            if self.request.query_params.get('user', None):
                user_id = self.request.query_params.get('user', None)
                try:
                    participant = Participant.objects.get(profile__owner_id=user_id)
                except Participant.DoesNotExist:
                    participant = None
                return self.queryset.filter(published_by=participant)
            return self.queryset
`

**Comment by rpkilby** [comment]
I assume that `get_queryset()` needs to return `self.queryset.all()` to force reevaluation.
