### ISSUE TITLE
Does order of parsers matter for file uploading?

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [encode/django-rest-framework#7346]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

Uploading an image with my test case was an absolute nightmare. When testing on an iOS client, I used a `parser_class = (FileUploadParser,)` and it worked just fine. But for the test case, the FileUploadParser CANNOT be first.

Here is the test case:
```python
class PictureTestCase(APITestCase):
    def test_upload_picture(self):
        view = views.ServerUploadPicView.as_view()
        arf = APIRequestFactory()
        from pathlib import Path
        from django.core.files.uploadedfile import SimpleUploadedFile
        with (Path().cwd().parent / "server/public/female.jpg").open("rb") as fp:
            file = SimpleUploadedFile("hi.jpg", fp.read(), content_type="image/jpg")
            request = arf.post(
                "/api/v1/profile/picture/",
                data={"file": file},
                format="multipart"
            )
            request.META["HTTP_CONTENT_DISPOSITION"] = "attachment; filename=hi.jpg"
            response = view(request)
        assert response.status_code == 200, f"Response {response.data}"
```

View A:
```python
class ServerUploadPicView(APIView):
    # The default parsers plus the FileUploadParser to represent an uploaded image
    parser_classes = (FileUploadParser, MultiPartParser)
    def post(self, request):
        serializer = ProfilePictureSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        return Response()
```

View B:
```python
class ServerUploadPicView(APIView):
    # The default parsers plus the FileUploadParser to represent an uploaded image
    parser_classes = (MultiPartParser, FileUploadParser)
    def post(self, request):
        serializer = ProfilePictureSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        return Response()
```

Notice where FileUploadParser is.

## Expected behavior

Both views SHOULD work, unless order of parser classes matter. In fact, the FileUploadParser MUST be the last parser in the tuple. Otherwise, the test will not pass.

## Actual behavior

View A will work, but View B will not **during tests**. HOWEVER, **with the iOS client**, View B will work but View A will not. You can check out my repository at https://github.com/Andrew-Chen-Wang/ios-django-picture-upload for the iOS client and the Django server ready-to-go so that you can quickly add that test.

Unfortunately, when you get the error, you will always only see: 

```{'file': [ErrorDetail(string='Upload a valid image. The file you uploaded was either not an image or a corrupted image.', code='invalid_image')]}```

Again, I'm not sure if this is actually what DRF is supposed to do with multiple parser classes... but this has been draining my soul for the last few days... So thank you!

Edit: Just to clarify, it's simple enough to pass the test and in production mode, like so:
```python
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        if settings.IN_TEST:
            self.parser_classes = (MultiPartParser,)
        else:
            self.parser_classes = (FileUploadParser,)
```
But this seems more like a bug to me.

**Comment by rpkilby** [comment]
> Does order of parsers matter for file uploading?

Hi @Andrew-Chen-Wang. Yes, the `parser_classes` are processed in order, and the first compatible parser will be selected. As `FileUploadParser` matches *any* content type, it will always be selected over subsequent parsers. In effect, view B's `[MultiPartParser, FileUploadParser]` will happily parse multipart content, and other content types are handled as a file upload. In comparison, view A's `[FileUploadParser, MultiPartParser]` will always parse the request as a file upload, the `MultiPartParser` is never called.

The issue with view A, is that it most likely isn't receiving the raw image data in the request body - it's receiving the image as part of a multipart form data request. The serializer then fails, as it's expecting image data, but received the multipart request body.
