### ISSUE TITLE
Docs are based on master and not latest released version

### ISSUE THREAD

**Issue by krukas** [encode/django-rest-framework#7350]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [X] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

_Issue was made for latest  release (3.11.0)_

## Steps to reproduce

Read the documentation about Schemas and want to use the tags described in the documentation.

`AutoSchema(tags=['tag1', 'tag2'])`

## Expected behavior

For the described documentation to work. I checked the code if the documentation is not outdated. The documentation is not outdated, but it looks like it uses the latest version from master:

**Docs**
Master: https://github.com/encode/django-rest-framework/blob/master/docs/api-guide/schemas.md#grouping-operations-with-tags
3.11.0: https://github.com/encode/django-rest-framework/blob/3.11.0/docs/api-guide/schemas.md

**Code**
Master: https://github.com/encode/django-rest-framework/blob/master/rest_framework/schemas/openapi.py#L121
3.11.0: https://github.com/encode/django-rest-framework/blob/3.11.0/rest_framework/schemas/openapi.py#L79

## Actual behavior

Get error message: `TypeError: __init__() got an unexpected keyword argument 'tags'`

## Solutions

Best solution would be to have the ability to switch version of the docs you want to see and default to latest stable release.

I think the easiest solution is to have `master` only have stable released version and separate branch for `development`. Or create a `stable` branch that has the latest release version and use documentation generation based on `stable` branch.

**Comment by tomchristie** [comment]
Latest docs are built from 3.11.

**Comment by tomchristie** [comment]
Thanks for having reported this.
