### ISSUE TITLE
Document and add test for SearchFilter m2m behavior 

### ISSUE THREAD

**Issue by Pomax** [encode/django-rest-framework#7351]
Refiled as issue from PR https://github.com/encode/django-rest-framework/pull/7094

"A change to rest_framework's filters.py, introduced in https://github.com/encode/django-rest-framework/pull/5264 and pushed out as part of v3.6.4, appears to have changed how searching with multiple filter conditions works when the fields involved are `ManyToMany` relations rather than plain model fields or `ForeignKey` relations."

This PR got closed but then reopened to track outstanding work, which should really be an issue, so as per @rpkilby notes:

- [ ] v3.6.4 Release notes need to more clearly point out the breaking change
- [ ] Expected m2m behavior should have a test (see closed PR)
- [ ] We might also want to add that vague note pointing users to Django's to-many queries docs.

**Comment by auvipy** [comment]
would be great if you can revisit the issue.

**Comment by auvipy** [comment]
I'm new in the team. thanks for your old efforts. we will pass this to others.
