### ISSUE TITLE
URLField makes Browsable API hides endpoints from openapi schema view

### ISSUE THREAD

**Issue by fao89** [encode/django-rest-framework#7354]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Have an `openapi` schema view, with some view using `URLField`

## Expected behavior
See all endpoints on the browsable API
## Actual behavior
Endpoints are missing due to HTML comment on regex patterns.

## Workflow
Autoschema when mapping [URLField](https://github.com/encode/django-rest-framework/blob/603aac7db10671dea1975ea3023b5488815aa1ca/rest_framework/fields.py#L885-L893)s: https://github.com/encode/django-rest-framework/blob/master/rest_framework/schemas/openapi.py#L545-L581 gets the regex pattern from [URLValidator](https://github.com/django/django/blob/d6aff369ad33457ae2355b5b210faf1c4890ff35/django/core/validators.py#L63-L92) which contains `<!` commenting the HTML from the Browsable API, hiding the following endpoints

**Comment by carltongibson** [comment]
This is probably #7204. There's an open ticket there to work out exactly how we should map the URL from a URLValidator. Would be great if you wanted to have a think about that.
