### ISSUE TITLE
Website is hacked!

### ISSUE THREAD

**Issue by mabuelhagag** [encode/django-rest-framework#7355]
The website is hacked. Anyone have any idea when it will be back or were to access documentation temporarily?

**Comment by daredevil82** [comment]
when curling through redirects, I get this:

```curl -IL django-rest-framework.org
HTTP/1.1 301 Moved Permanently
Server: GitHub.com
Date: Sat, 30 May 2020 17:08:22 GMT
Content-Type: text/html
Content-Length: 162
Location: https://www.django-rest-framework.org/
X-GitHub-Request-Id: C686:1B15:987E2:BED0F:5ED29306

HTTP/2 200
server: GitHub.com
content-type: text/html; charset=utf-8
last-modified: Sat, 30 May 2020 16:08:02 GMT
etag: "5ed284e2-1172"
access-control-allow-origin: *
expires: Sat, 30 May 2020 16:40:39 GMT
cache-control: max-age=600
x-proxy-cache: MISS
x-github-request-id: EB7C:1DEB:221B69:29BB84:5ED28A2D
accept-ranges: bytes
date: Sat, 30 May 2020 17:08:22 GMT
via: 1.1 varnish
age: 0
x-served-by: cache-pwk4955-PWK
x-cache: MISS
x-cache-hits: 0
x-timer: S1590858503.923222,VS0,VE28
vary: Accept-Encoding
x-fastly-request-id: c5e98bb22364ea1ad39c68dc6ca864c34d9339b3
content-length: 4466```

**Comment by daredevil82** [comment]
oh, and this is indeed not a hack and done deliberately by @tomchristie 

https://github.com/encode/django-rest-framework/tree/gh-pages

github pages static site

**Comment by harbi** [comment]
While it's good to raise awareness about such a humanitarian issue, I'm not sure if this is the right way to do it. At least I hope his Github account isn't hacked!

Anyway, in case you're looking for the documentation you can find it in the repo:
[django-rest-framework/docs/](https://github.com/encode/django-rest-framework/tree/master/docs)

**Comment by daredevil82** [comment]
also, a mirror for the docs is up at https://imerica.github.io/django-rest-framework/

**Comment by marcelo225** [comment]
Thank for helping us, @daredevil82
