### ISSUE TITLE
Please make the docs usable again

### ISSUE THREAD

**Issue by WoLpH** [encode/django-rest-framework#7358]
I noticed the website is currently down due to the issue with George Floyd. While I have full sympathy for the current issues in the US, disabling the site entirely is a bit much which could also kill the google search ranking.

Would an overlay or a banner perhaps be a useful alternative?

Additionally, the vast majority of the world (myself included) doesn't live in the US so a little bit of context would be useful. A list of names alone is confusing to say the least if you don't know the context.

**Comment by tomchristie** [comment]
Hi.

This one is a personal decision, so I’m not particularly open to group discussion on this. I expect the site will be offline for a few days, and then back.

It’s not my country either, but racism *isn’t* a local issue, and the moment is so stark and so grotesque that I feel it’s a time to voice solidarity.

**Comment by aero31aero** [comment]
Hey, for those that do not know the context, a link to a news site/wikipedia would actually be helpful. I know someone who at first glance thought these must have been the contributors' names.

**Comment by WoLpH** [comment]
> It’s not my country either, but racism isn’t a local issue, and the moment is so stark and so grotesque that I feel it’s a time to voice solidarity

I’m not saying racism is a local issue. But some information about what the message is trying to say would be good.

**Comment by iMerica** [comment]
Mirror: https://imerica.github.io/django-rest-framework/

**Comment by Alkalit** [comment]
Sure, if it happend in a first world country - everybody should care!

**Comment by tomchristie** [comment]
Locking this one now - it's a personal voice, not an opportunity for group discussion - plenty of other spaces for that.
