### ISSUE TITLE
Suggestion for future site closures

### ISSUE THREAD

**Issue by josh-stableprice** [encode/django-rest-framework#7363]
I appreciate your decision to take a stand and do what you believe is correct. I also support you doing so.

I would ask that in future, you do provide an alternative source for the rendered documentation, maybe behind a click through acknowledgement or something? 

We had an incident as we deployed a new feature to dev about 20 minutes ago, I needed the documentation and I discovered that you had replaced the site. 

Luckily there was https://imerica.github.io/django-rest-framework/ as a mirror, but that isn't official. I resolved my issue. 

I worry what would have happened if this hadn't shown up until prod, or worse, we didn't have staging environments. 

I worry about the people who may lose their jobs being unable to find what they've done incorrectly in code because of some people a world away being despicable people.

Please in future, try to get your point across without the potential to cause actual harm to those who have integrated with your code and have nothing to do with what is going on in America or the racism across the world.

**Comment by kbuilds** [comment]
@josh-stableprice Thank you for posting a link to the mirror.

It's disturbing to me that the maintainers of such an important piece of software would intentionally disrupt their users like this, for any reason, politics aside.
