### ISSUE TITLE
The world burns but where's the documentation?

### ISSUE THREAD

**Issue by spascou** [encode/django-rest-framework#7365]
Our thirst for documentation has no bounds in this burning world !

A shame that this is the way respect and solidarity tries to manifest itself, by needlessly bothering lots of people. Feels like I'm walking down the street and someone shoves me a signature board about injustice on the other side of the globe in the face; doesn't exactly passes the right message I think.

Ain't gonna change your thoughts, but would've appreciated a better separation of your societal views and the service quality that was previously. At least I'm gratefully using this excellent project for free, but boy really feels bad for your actual sponsors who cannot comfortably read documentation until injustice is no more in this world.

**Comment by Catelemmon** [comment]
I my opinion, this is not a  good appproach to remember George Floyd, in contrast, it's also a extrame case like burnintg supermarket or hurting innecent man, I couldn't agree more about this is a great   project, but this is not appropriate. Maybe it's not a  good idea if you can add url to jump to the true document in remember page for users.

**Comment by spascou** [comment]
Good idea @Catelemmon , a link to the original documentation from the memorial page would give a better experience while still passing the message in a respectful way.

**Comment by xuyangkang** [comment]
It is not too much work to find the doc under [here](https://github.com/encode/django-rest-framework/blob/master/docs/index.md) and access the original MD file via GitHub's UI. The document is still pretty readable. But I agree that to remember George Floyd by closing the documentation site is not a good approach. It's OK to promote good in software, like vim does: "Help poor children in Uganda!". But A few line on top of the page should be good enough.

**Comment by rpkilby** [comment]
Hi all. Tom has stated his thoughts elsewhere in related issues. 

The docs are available via a mirror, can be read here via GitHub's rendered markdown, or can be served locally with `mkdocs`.

**Comment by samuelcolvin** [comment]
Could you provide a link to where tom has stated his thoughts?

There are no related issues to this issue, and there's nothing on Tom's personal website or twitter that I could find.

**Comment by spascou** [comment]
I got https://github.com/encode/django-rest-framework/issues/7358#issuecomment-636449969 and https://github.com/encode/django-rest-framework/issues/7357#issuecomment-636443245 .

**Comment by samuelcolvin** [comment]
yes, sorry - just seen all the other issues.
