### ISSUE TITLE
link to unstyled API-guide page

### ISSUE THREAD

**Issue by sm7515** [encode/django-rest-framework#7367]
## Checklist

- [ ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

[On quickstart page](https://www.django-rest-framework.org/tutorial/quickstart/), scroll all the way down to the bottom, and click on **API guide** link.
![image](https://user-images.githubusercontent.com/36653440/83551085-b5418b80-a4bc-11ea-9cfc-226ae028db9b.png)

## Actual behavior

[the page](https://www.django-rest-framework.org/tutorial/#api-guide) is pure html, with no styling.
![image](https://user-images.githubusercontent.com/36653440/83551253-f5a10980-a4bc-11ea-8fc6-7c1cc266e92e.png)

**Comment by rpkilby** [comment]
Hi @sm7515. This has already been fixed on master. Thanks!
