### ISSUE TITLE
Error when traversing relation as field source in extra_kwargs

### ISSUE THREAD

**Issue by alexgmin** [encode/django-rest-framework#7368]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [X] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
```python
from rest_framework import serializers
from django.db import models

class Bar(models.Model):
    id = models.IntegerField()
    class Meta:
        app_label = 'test'
        
class Foo(models.Model):
    bar = models.ForeignKey(
        Bar,
        on_delete=models.PROTECT,
    )
    class Meta:
        app_label = 'test'
    
class FooSerializer(serializers.ModelSerializer):
    class Meta:
        model = Foo
        fields = (
            'bar',
        )
        extra_kwargs = {
            'bar': {
                'source': 'bar.id'
            }              
        }
FooSerializer()
```
## Expected behavior
The serializer is initialized correctly.
## Actual behavior
The serializer errors with this message:
`django.core.exceptions.ImproperlyConfigured: Field name \`bar.id\` is not valid for model \`Foo\``

If the field is defined explicitly it works.
```python
class FooSerializer(serializers.ModelSerializer):
    bar = serializers.IntegerField(source='bar.id')
    class Meta:
        model = Foo
        fields = (
            'bar',
        )
```

**Comment by tsyplakou** [comment]
Serializer try to build field in `get_fields()` method, but nested field (via `source` with long path) is not provided in `build_field()`. 
`build_field()` does not support retrieving field using list of attributes from source. This method try to define type of field before adding to serializer fields. Class `Field`, on the other hand, just use method `bind` to build path to attribute without field type check.
Question is - how to define type of the field (with list of attributes) in `build_field()`?
Or use `build_property_field()` for any uncertain field?

**Comment by tomchristie** [comment]
I'd be okay with reviewing any PR tackling this, but otherwise I think you're just going to need to treat that an unintended usage.

**Comment by nattyg93** [comment]
@tomchristie If we are treating this as unintended, would it be possible to have it documented?
