### ISSUE TITLE
HTML doc for Schema not up-to-date with the md file

### ISSUE THREAD

**Issue by SlowFlo** [encode/django-rest-framework#7370]
## Checklist

- [X] I have verified that that issue exists against the `master` branch of Django REST framework.
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [X] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [X] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

Go to https://www.django-rest-framework.org/api-guide/schemas/#install-pyyaml

## Expected behavior

The [install-pyyaml](https://www.django-rest-framework.org/api-guide/schemas/#install-pyyaml) section of the Schema Guide should be the same as the [install-dependencies](https://github.com/encode/django-rest-framework/blob/master/docs/api-guide/schemas.md#install-dependencies) section of the .md file.

EDIT : to clarify, It should say to also install **uritemplate**

## Actual behavior

The Html version is outdated of 4 months (seems to be like before 39dd34f161792146b7d33bf062366f54c2bde3f1).

Hope it helped :)

**Comment by tomchristie** [comment]
The docs are in line with the latest release, rather than with master.

**Comment by SlowFlo** [comment]
Ok, my bad. Sorry.
