### ISSUE TITLE
BaseAuthentication should be an Abstract Base Class

### ISSUE THREAD

**Issue by mentix02** [encode/django-rest-framework#7376]
In [`rest_framework/authentication.py`](https://github.com/encode/django-rest-framework/blob/master/rest_framework/authentication.py), the docstring for `BaseAuthentication` reads that "*ALL* authentication classes should extend `BaseAuthentication`" and the `authenticate` method even raises a `NotImplementedError` stating that it should be overridden. 

Seems to be the perfect use for using the [ABC](https://docs.python.org/3/library/abc.html#abc.ABC) class from the standard library. Is there any particular reason why this wasn't done so?

**Comment by tomchristie** [comment]
> Is there any particular reason why this wasn't done so?

Our BaseAuthentication class probably pre-dated the stdlib's ABC class.

I'm not *necessarily* against PRs adding usage of there wherever appropriate, but not going to consider it an issue otherwise, since we've got sensible behaviour here anyways.

**Comment by rpkilby** [comment]
@tomchristie. Just to clarify, are you considering #7377, or are you not interested in using an ABC in this case.
