### ISSUE TITLE
Provide a way to avoid circular import of serializers

### ISSUE THREAD

**Issue by mrodal** [encode/django-rest-framework#7381]
Its a common case where you have modules where both refer to each other.

For example, modules users and posts. On users you have User and on posts you have Post and Attachment

```python
# users
class UserSerializer:
    posts = PostSerializer()
    profile_attachments = AttachmentSerializer()


#posts
class PostSerializer:
    user = StringSerializer()
    attachments = AttachmentSerializer()

class AttachmentSerializer:
    name = CharField()
    size = IntegerField()
```

In Django there's a way to declare [Foreign Keys](https://docs.djangoproject.com/en/3.0/ref/models/fields/#foreignkey) that avoids circular dependencies, declaring the referenced model by a string:

`profile_attachment = models.ForeignKey('posts.Attachment', on_delete=models.CASCADE)`

Could DRF offer something like that for serializers? Something like 

`profile_attachment = ModelSerializer(serializer='posts.AttachmentSerializer')`

**Comment by jvhellemondt** [comment]
Hi mrodal!

I managed to achieve the same by implementing the following in one of the "circular" serializers: [DRF: Reverse relations](https://www.django-rest-framework.org/api-guide/relations/#reverse-relations) 
[Django: Following relationships “backward”](https://docs.djangoproject.com/en/3.0/topics/db/queries/#following-relationships-backward)

Though I do think it's quite complex.

**Comment by C0DK** [comment]
So i actually have the same case in a project i work on, but you really shouldn't. best practice, from a software engineering and architecture course is to have a one way dependency. If possible atleast. If there is a very close coupling between the two apps they should maybe be one app, alternatively they should have a common parent. You could also move your serializer into a sub-app if applicable.

I might be wrong, but AFAIK that is best practice.

**Comment by xordoquy** [comment]
I'm surprised this does not end up in infinite loop.
