### ISSUE TITLE
Implement ModelSerializer.__class_getitem__

### ISSUE THREAD

**Issue by antonagestam** [encode/django-rest-framework#7384]
To allow type checking efforts to properly type the methods of `ModelSerializer` it needs to be made generic with regards to the model it serializes. Since django-rest-framework has chosen to not own any annotations themselves the only way to achieve that will be to implement `__class_getitem__`. Stub implementors can then make the class generic and calling `ModelSerializer[Author]` will not yield subscriptability errors at runtime.

Note that this is the unfortunate direction [Django has chosen as well](https://github.com/django/django/commit/578c03b276e435bcd3ce9eb17b81e85135c2d3f3).

[This is the relevant issue in djangorestframework-stubs](https://github.com/typeddjango/djangorestframework-stubs/issues/71) for reference.

[This is the relevant Python docs on generic classes.](https://docs.python.org/3/library/typing.html#user-defined-generic-types)

**Comment by sobolevn** [comment]
@antonagestam thanks a lot! This will make development of `djangoresframework-stubs` easier! 👍
