### ISSUE TITLE
TypeError while Importing Token from rest_framework.authtoken.models

### ISSUE THREAD

**Issue by hash3liZer** [encode/django-rest-framework#7386]
I've been trying to import `Token` fom `rest_framework.authtokens.models` to create new Tokens from the user. But it throws back following Type Error: 
```
from rest_framework.authtoken.models import Token
```
```
TypeError                                 Traceback (most recent call last)
/usr/lib/python3.8/codeop.py in __call__(self, source, filename, symbol)
    134 
    135     def __call__(self, source, fiename, symbol):
--> 136         codeob = compile(source, filename, symbol, self.flags, 1)
    137         for feature in _features:
    138             if codeob.co_flags & feature.compiler_flag:

TypeError: required field "type_ignores" missing from Module

```
**Steps to Recreate::**
```
$ python3 manage.py shell
$ from rest_framework.authtoken.models import Token
```

**Note::**
Installed Apps Settings includes the following: 
```
INSTALLED_APPS = [
    # Third Party
    'rest_framework',
    'rest_framework.authtoken',
]
```

**Comment by xordoquy** [comment]
This is unrelated to Django REST framework as the build matrix works well with Python 3.8.
Make sure your dependencies are working with your Python version, mostly Werkzeug.

**Comment by hash3liZer** [comment]
I checked the dependencies. Everything's fine. Strange tough, when i imported in views.py, it worked. But not in shell.

**Comment by xordoquy** [comment]
As I said, most likely your Werkzeug version is less than 0.15.5 and does not work with Python 3.8
