### ISSUE TITLE
Overriding retrieve with different serializer tries to user class serializer on response

### ISSUE THREAD

**Issue by lianulloa** [encode/django-rest-framework#7390]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

```python
class CustomUserViewSet(viewsets.ModelViewSet):
  queryset = CustomUser.objects.all()
  serializer_class = CustomUserSerializer

  def retrieve(self, request, pk=None):
    try:
      user = CustomUser.objects.get(pk=pk)
    except CustomUser.DoesNotExist:
      user = get_object_or_404(User, pk=pk)
      user_serializer = UserSerializer(instance=user)
      response = Response(user_serializer.data, status=status.HTTP_200_OK)
      return response

    serializer = CustomUserSerializer(user)
    return Response(serializer.data, status=status.HTTP_200_OK)

```
## Expected behavior
response OK
## Actual behavior
When it goes through the `except` way, it throws this error:

Got AttributeError when attempting to get a value for field `user` on serializer `CustomUserSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `User` instance.
Original exception text was: 'User' object has no attribute 'user'.

**Comment by lianulloa** [comment]
Probably due to ReturnDict

**Comment by lianulloa** [comment]
Had to do this to get it to work

```python
      data = UserSerializer(instance=user).data
      response_data = {}
      for key,value in data.items():
        response_data[key]= value
      return Response(response_data, status=status.HTTP_200_OK)

```

**Comment by jerinpetergeorge** [comment]
> Got AttributeError when attempting to get a value for field `user` on serializer `CustomUserSerializer`.
> The serializer field might be named incorrectly and not match any attribute or key on the `User` instance.
> Original exception text was: 'User' object has no attribute 'user'.

BTW, this error is usually raised when you add invalid fields to the serializer class.

**Comment by tomchristie** [comment]
Hi there.

This looks like it'd probably be better suited to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework).
