### ISSUE TITLE
{"detail":"Authentication credentials were not provided."} - format=json

### ISSUE THREAD

**Issue by ManPython** [encode/django-rest-framework#7392]
## Checklist

- [x ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x ] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
1. Ger some data as ?format=json (there are visible in browser) and save as .json (eg. FF) file - are 2 option:
- by browser save as 
- by json plugin when we see data (exit aditional btn for this under url input field, etc.)

## Expected behavior
1. Save file with data
https://stackoverflow.com/questions/26906630/django-rest-framework-authentication-credentials-were-not-provided
## Actual behavior
1. Saved file have just only this data, not this same as I see normaly by ?format=api (I'm logged)
```
{"detail":"Authentication credentials were not provided."}
```
There are some issues around uwsgi WSGIPassAuthorization . But I'm using uWSGI2
The ?format=xml and ?format=csv working ok.

**Comment by jvhellemondt** [comment]
Hi ManPython!

I have read your issue and I wish to clarify something before proceeding..

Do I understand correctly that when you are browsing your browser and you go to (EXAMPLE) localhost:8000/api/data?format=json, you can see the data?

Is the json plugin an external application? Or an extension in your browser?

Let me know!

Cheers.

**Comment by tomchristie** [comment]
Hi there & thanks for your question.

The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions.

Thanks! 😀

**Comment by ManPython** [comment]
@jvhellemondt In both options saved .json is empty on browser is visible by ?format=json.
