### ISSUE TITLE
Custom Validation errors aren't returned if field-level ValidationErrors are raised

### ISSUE THREAD

**Issue by epicserve** [encode/django-rest-framework#7394]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

Check out the master branch of this [example project](https://github.com/epicserve/drf-validation-issue) and run tests to see the failing test.

## Expected behavior

The expected behavior is when you have field-level validation on a serializer that raises a ValidationError that it will still run any custom validation on the serializer so that all errors are returned instead of just the field-level validation errors. This current behavior causes a bad user experience because when the user fixes the field-level validation errors, they can end up getting errors returned again if the custom validation raises a ValidationError.

## Actual behavior

Field-level validation errors are returned and custom validation is ignored or not run at all.

## Possible Solution

If you check out the branch `fix-validation` in my [example project](https://github.com/epicserve/drf-validation-issue/tree/fix-validation), you can see that the tests all pass. The solution was to override two Django Rest Framework methods in the Serializer class (`to_internal_value` and `run_validation`). The `to_internal_value` method was overwritten in order to not raise validation errors in this method and instead return the errors and the cleaned data, so that all errors can be combined and returned in the `run_validation` method.

**Comment by hercip** [comment]
I don't know if this is the same problem, but I think I did a similar fix: https://github.com/encode/django-rest-framework/pull/7487

**Comment by tomchristie** [comment]
> The expected behavior is when you have field-level validation on a serializer that raises a ValidationError that it will still run any custom validation on the serializer

I mean, that's not *necessarily* the behaviour I'd expect no. Typically you only want to run whole-serializer validation once you know you've got valid data for each field.

I'd be up for discussing this further, but it'd need to start with a clear simple example use-case in order to discuss it from a real-life POV rather than in the abstract. But it looks decidedly non-obvious to me from a first pass.
