### ISSUE TITLE
format_suffix_patterns conflict with swagger (issue and feature)

### ISSUE THREAD

**Issue by ManPython** [encode/django-rest-framework#7397]
DJ.2.2.6
## Checklist
- [x ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x ] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Django REST Swagger: deprecated (2019-06-04), so we using **drf-yasg**
https://github.com/axnsan12/drf-yasg
This lib have this implementation ways
```
   url(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
   url(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
   url(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
```
1st line of url as active giving us errors
```
resolvers.py", line 185, in _compile
    '"%s" is not a valid regular expression: %s' % (regex, e)
django.core.exceptions.ImproperlyConfigured: "^swagger(?P<format>\.json|\.yaml)\.(?P<format>(json|html|xml|csv))/?$" is not a valid regular
expression: redefinition of group name 'format' as group 2; was group 1 at position 39
```
It's related when we have:
`urlpatterns = format_suffix_patterns(urlpatterns, allowed=['json', 'html', 'xml', 'csv'])`

## Expected behavior
Allow good cooperation betwen DRF and drf-yasg to get output with .json and .yaml together with rest as 'json', 'html', 'xml', 'csv'

## Actual behavior
Need turn off the 1st example line of drf-yasg that touching formats json/yaml

Comments: 
Format in Python36 is {}.format to join parts, and format maybe should be as `extension` or `ext`
drf-yasg not well working in automation of url discovering like old swagger

**Comment by carltongibson** [comment]
This is an issue with drf-yasg no? 

> It's related when we have:
> urlpatterns = format_suffix_patterns(urlpatterns, allowed=['json', 'html', 'xml', 'csv'])

Looks like the simplest solution is just to route the `drf-yasg` urls outside of the `format_suffix_patterns` group. 
The suggested fix would be to add that to the `drf-yasg` docs I think.
