### ISSUE TITLE
url() is deprecated in Django 3.1 

### ISSUE THREAD

**Issue by smithdc1** [encode/django-rest-framework#7406]
CI is raising warnings as `url()` is deprecated in the upcoming release of Django.

https://travis-ci.org/github/encode/django-rest-framework/jobs/707134589

**Comment by auvipy** [comment]
check https://github.com/encode/django-rest-framework/pull/7325

**Comment by sanjusci** [comment]
Please see:
#[7420](https://github.com/encode/django-rest-framework/pull/7420)

**Comment by adamchainz** [comment]
I re-did #7420 in #7512, with some fixes (see commits).
