### ISSUE TITLE
Multi Tenancy Support

### ISSUE THREAD

**Issue by lakshaytalkstocomputer** [encode/django-rest-framework#7410]
## Checklist
- [ ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [ ] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Expected behavior
 How to incorporate multi site usage for single django project. I know Djnago has support for Multi Site by using multi site framework. But How would I use that to create apis in DRF?

**Comment by MattShirley** [comment]
You are free to create your own multi tenant app by defining a tenant_id on all of your models and adapting middleware, views, serializers, permissions, etc. to insure data isolation.

For a more advanced treatment of this topic, I would recommend looking at the django-tenants project. It is completely independent of DRF and seems to work reasonably well with DRF. It provides Postgres database management functionality to isolate an individual tenant's data on its own Postgres schema. https://django-tenants.readthedocs.io/en/latest/

**Comment by auvipy** [comment]
I think it's out of the scope of drf core and deserves a separate package as multi-tenancy has multiple options to choose from!

**Comment by xordoquy** [comment]
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
