### ISSUE TITLE
Misunderstanding in docs

### ISSUE THREAD

**Issue by Gr3Kidd3r** [encode/django-rest-framework#7412]
[Serializers documentation](https://www.django-rest-framework.org/api-guide/serializers/#serializer_field_mapping):

> A mapping of **Django model classes** to REST framework serializer classes. You can override this mapping to alter the default serializer classes that should be used for each model class.

I think it should be replaced with: **Django model fields** as it's mapping model fields to serializer fields.

**Comment by tomchristie** [comment]
Yup, looks like it could be worded better. Pull requests here are most welcome.

**Comment by Gr3Kidd3r** [comment]
Hello there, I've fixed the issue and proposed a PR (#7418).
I'll be happy if you merge it.
:+1:

**Comment by rpkilby** [comment]
Thanks! PR merged.

**Comment by Gr3Kidd3r** [comment]
You're welcome, glad to help.

**Comment by rpkilby** [comment]
Docs are not automatically deployed, as they might contain new and unreleased features.

**Comment by Gr3Kidd3r** [comment]
Tnx and happy coding :smile:
