### ISSUE TITLE
Translation missing for part of throttle warning

### ISSUE THREAD

**Issue by demmojo** [encode/django-rest-framework#7419]
This issue was first referenced in [6177](https://github.com/encode/django-rest-framework/issues/6177) and then an attempted fix was made in [#6771](https://github.com/encode/django-rest-framework/pull/6771). 

## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Trigger a throttle warning and set an 'Accept-Language' to 'de' (German). This issue also appears for the Turkish language.
## Expected behavior
Both parts of the throttle message should be translated.
## Actual behavior
The throttle message returns a partially translated warning. ("Die Anfrage wurde gedrosselt. Expected available in 5 seconds.")

See the image below:
![image](https://user-images.githubusercontent.com/30584067/87711677-468c6900-c7b0-11ea-817b-922187f4b0b0.png)

**Comment by comeuplater** [comment]
That is easy to patch. Could you write the correct message? I`m not sure that it is correct translate: `Voraussichtlich in 5 Sekunden verfügbar.`. I used Google Translate to got it.

**Comment by demmojo** [comment]
I don't speak German so I had to ask my German  co-founder. I also shared the Turkish translation of the same sentence. Thank you for the help!

**German:**

**One second case:**
Voraussichtlich in einer Sekunde verfügbar.

**0 or more than one second case:**
Voraussichtlich in 5 Sekunden verfügbar.

**Turkish**

**Both cases are same in Turkish:**

Kısıtlamanın 1(or 5) saniye içinde kaldırılması bekleniyor.

**Comment by tomchristie** [comment]
Going to close this off as stale. Hopefully these have both been updated in Transifex by now.
