### ISSUE TITLE
Why are field attributes removed from serializer object

### ISSUE THREAD

**Issue by lafrech** [encode/django-rest-framework#7428]
Hi.

In `_get_declared_fields`, fields are popped from the serializer object attributes:

https://github.com/encode/django-rest-framework/blob/599e2b183db846a632b1efd148e6bc97d926ee5c/rest_framework/serializers.py#L284-L287

They are only available from the `_declared_fields` dict.

This behaviour was copied in marshmallow and before removing it there, we thought we should ask here for the rationale.

Related PR: https://github.com/marshmallow-code/marshmallow/pull/1631

The reasons we'd like to change this are
- we don't understand why it was done in the first place
- we see no reason to prevent direct field access as `serializer.field_name`

I've patched DRF code locally to remove the `pop` and all tests pass.

```py
    @classmethod
    def _get_declared_fields(cls, bases, attrs):
        fields = [(field_name, attrs[field_name])  # <- here
                  for field_name, obj in list(attrs.items())
                  if isinstance(obj, Field)]
        fields.sort(key=lambda x: x[1]._creation_counter)
```

What is the rationale for removing the fields attributes?

Thanks.

**Comment by rpkilby** [comment]
> They are only available from the `_declared_fields` dict.

They are also present in the `fields` dict,  as returned by `get_fields()`.

> This behaviour was copied in marshmallow and before removing it there, we thought we should ask here for the rationale.

Similarly, this behavior was copied from the Django [form metaclass](https://github.com/django/django/blob/ee1ddcbab9f2453ae4959a8556b6cadeb4bb0867/django/forms/forms.py#L27-L30).

> we see no reason to prevent direct field access as `serializer.field_name`

My assumption is that it's to prevent user error. If a user does the following, they might reasonably expect to operate on the validated `bar` field data, not the underlying field instance. 

```python
class Foo(serializers.Serializer):
    bar = serializers.CharField()

s = Foo(data={'bar': 'baz'})
s.is_valid()
if s.bar == "somevalue":
   ...
```

In addition to preventing this kind of error, requiring fields to be accessed via the `fields` dict is more clear to those  reading the code in the future.

**Comment by lafrech** [comment]
Thanks @rpkilby for taking the time to answer.

I don't know django and django-rest-framework, but clearly you're right. If you can do `Foo(data={'bar': 'baz'})` then you need to "hide" the fields to avoid name clashes when accessing object values.

The marshmallow case is a bit different as the object class is separated from the schema class so there's no clash between accessing the field in the schema and the attribute in the object.
