### ISSUE TITLE
test_empty_not_allowed_if_allow_empty_is_set_to_false emits deprecation warning in Python 3.9

### ISSUE THREAD

**Issue by tirkarthi** [encode/django-rest-framework#7433]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

test_empty_not_allowed_if_allow_empty_is_set_to_false emits deprecation warning in Python 3.9 due to NotImplemented being used in boolean context which always evaluates to True

```
tests/test_serializer_nested.py::TestNestedSerializerWithMany::test_empty_not_allowed_if_allow_empty_is_set_to_false
  /root/django-rest-framework/rest_framework/exceptions.py:77: DeprecationWarning: NotImplemented should not be used in a boolean context
    return r and self.code == other.code
```

**Comment by tomchristie** [comment]
Believe this to be closed via #7531

**Comment by allanlewis** [comment]
I'm getting a similar error from `__ne__` on 3.12.4, which includes the fix from #7531:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/unittest/mock.py", line 1336, in patched
    return func(*newargs, **newkeywargs)
  File "<my-code>", line <redacted>, in <redacted>
    assert_that(exc.exception.detail).is_equal_to(
  File "<redacted>/assertpy/base.py", line 125, in is_equal_to
    if self.val != other:
  File "<redacted>/rest_framework/exceptions.py", line 84, in __ne__
    return not self.__eq__(other)
DeprecationWarning: NotImplemented should not be used in a boolean context
```

So does the fix applied to `__eq__` need to be applied to `__ne__` as well? If we could backport any change to 3.12.x that would be very helpful 🙂

**Comment by tomchristie** [comment]
Seems valid to me.

Looks like we need to change from this…

```python
    def __ne__(self, other):
        return not self.__eq__(other)
```

to this…


```python
    def __ne__(self, other):
        r =  self.__eq__(other)
        if r is NotImplemented:
            return NotImplemented
        return not r
```

Would you be interested in submitting a pull request for this change?

**Comment by allanlewis** [comment]
@tomchristie sure, see #8538. I'm not sure how best to add a test to cover that case but I'd be happy to do so given some guidance.
