### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by tasn** [encode/django-rest-framework#7441]
Please make a new release. There have been numerous fixes and improvements since the last release (over 8 months ago).

## Checklist

- [X] I have verified that that issue exists against the `master` branch of Django REST framework.
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [X] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [X] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

N/A

## Expected behavior

N/A

## Actual behavior

N/A

**Comment by carltongibson** [comment]
Yes, it's coming. 2020. 

In the meantime, [pip's VCS support is first rate](https://pip.pypa.io/en/stable/reference/pip_install/#vcs-support).

**Comment by tasn** [comment]
Yeah, I'm doing that, though running code in production directly from VCS feels iffy. Even if only because you're probably one of the only ones using a specific commit.

**Comment by carltongibson** [comment]
Hi @tasn — Thanks. For me, as long as you pick a specific commit, rather than a branch head, which can change under you there's no harm. (You've got tests right? 🙂)

As I say, it's coming.

**Comment by tasn** [comment]
I have pinned it to a specific commit, sure, not going willy-nilly. :)
Also, I have tests, and the suite seems to pass, though it's still a very different thing to use code directly from VCS that could introduce bugs and has many less testers than released code...

Anyhow, great, looking forward!
