### ISSUE TITLE
Add Support to configure used django template engine

### ISSUE THREAD

**Issue by jesusch** [encode/django-rest-framework#7444]
Currently used HTML templates do not support choosing a specific template engine.
While having various (incompatible e.g. django_jinja) template engines configured, this causes DRF templates to throw TemplateSyntaxErrors

I'll attach a working PR

**Comment by jesusch** [comment]
relates to: #4084

**Comment by jesusch** [comment]
just double checked: the `using=None` keyword exists in affected django.template.loader functions at least since django:1.11

**Comment by rpkilby** [comment]
Closing per #7445.
