### ISSUE TITLE
OverflowError: Python int too large to convert to SQLite INTEGER

### ISSUE THREAD

**Issue by jayvdb** [encode/django-rest-framework#7448]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

Similar to https://github.com/encode/django-rest-framework/issues/7134 , using schemathesis on the sample at of django-oscar-api , there are lots of varied errors, some seen at https://github.com/django-oscar/django-oscar-api/issues/227

## Expected behavior

DRF generics should respond with 404 

## Actual behavior

DRF generics currently responds with 500

**Comment by jayvdb** [comment]
In addition to #7449 , I also have another less obviously 'correct' patch that I need to get past some of these `OverflowError`

```patch
diff --git a/rest_framework/serializers.py b/rest_framework/serializers.py
index 916f8bec..d2a4b75b 100644
--- a/rest_framework/serializers.py
+++ b/rest_framework/serializers.py
@@ -746,7 +746,11 @@ class ListSerializer(BaseSerializer):
 
     @property
     def data(self):
-        ret = super().data
+        try:
+            ret = super().data
+        except OverflowError as e:
+            raise ValidationError(str(e))
+
         return ReturnList(ret, serializer=self)
 
     @property
```

**Comment by rpkilby** [comment]
Hi @jayvdb. This is something that should be fixed in the sqlite backend. There is already a ticket tracking this issue.

https://code.djangoproject.com/ticket/27397
