### ISSUE TITLE
[OAS3] OpenAPI v3 schema validation

### ISSUE THREAD

**Issue by peppelinux** [encode/django-rest-framework#7452]
Hi guys,
Thank you for this wonderful project, it's really awesome and I always use it as it is, it always gave me more then what I would ever ask. But (!) something changed in my context and I have to face an important schema validation that, at this moment, drave my loved DRF out. I would like to get these features working and I'm ready to give an hand.

Here the specification:
https://teamdigitale.github.io/api-oas-checker/spectral.yml

And here and example of a failed validation:
https://teamdigitale.github.io/api-oas-checker/?url=https://raw.githubusercontent.com/UniversitaDellaCalabria/Ricerca/master/schema.yml

I have to fix every elements exposed by [api-oas-checker](https://github.com/teamdigitale/api-oas-checker) and I would have a little brain storming do deal with the mainstream developer line. I would start from here:
https://www.django-rest-framework.org/api-guide/schemas/#customizing-schema-generation

Then, probably and if everything will goes fine, I would put a PR with a `openapi-v3-schema` specialization.
My validator is that `spectral.yml`, don't know if this would be good for everyone so here I am to start the discussion.

regards

## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

**Comment by carltongibson** [comment]
Hi @peppelinux -- you've checked the master branch yes? There's a lot of new stuff there due for the next release. 

Then check open issues and PRs with the Schema Generation label. There are a few older ones there from the old CoreAPI based generation, but the newer ones are related to OpenAPI. 

From there, concrete issues, and help fixing them is appreciated! 

I'm not sure how actionable this issue is: happy to discuss, but it's a bit general?

**Comment by peppelinux** [comment]
Thank Carlton for the reply,
Yes it's generic and that's my starting point 😎
I've seen the stabile release, now I'll see the master branch and then I'll post here if something interesting could be discussed!

**Comment by peppelinux** [comment]
And finally, there's not so much there regarding my goals:
https://github.com/encode/django-rest-framework/issues?q=is%3Aissue+is%3Aopen+Schema+Generation

Also tried openapi as label, pas and some other. Going to dig the sources 👍

**Comment by carltongibson** [comment]
OK, thanks @peppelinux — I'm going to close this issue now, as it's not actionable really. If you can pin down tighter suggestions, happy to take those on. Thanks 👍
