### ISSUE TITLE
DRF 3.11 incompatible with Django 3.1

### ISSUE THREAD

**Issue by hodossy** [encode/django-rest-framework#7456]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Use the `rest_framework.filters.SearchFilter` as a filter backend with Django 3.1

## Expected behavior
Works.

## Actual behavior

ImportError: Could not import 'rest_framework.filters.SearchFilter' for API setting 'DEFAULT_FILTER_BACKENDS'. ImportError: cannot import name 'ORDER_PATTERN' from 'django.db.models.sql.constants' (/usr/local/lib/python3.8/site-packages/django/db/models/sql/constants.py)

**Comment by xordoquy** [comment]
As per https://www.django-rest-framework.org/#requirements, it is expected not to be working.
Next release will be supporting Django 3.1

**Comment by SamMorrowDrums** [comment]
@xordoquy - given the specific compatibility issue, is there any plan to do a small release, just for the Django current version bump?

**Comment by tomchristie** [comment]
Not sure. Welcome any other input on this, otherwise I'm back on things tomorrow, til the end of the week.

**Comment by owurman** [comment]
Seems fixed in 3.11.1, thanks for doing that so quickly.

**Comment by hodossy** [comment]
Thanks for the quick fix!
