### ISSUE TITLE
filters package broken since Django 3.1

### ISSUE THREAD

**Issue by Bel-Shazzar** [encode/django-rest-framework#7458]
## Checklist
- [X] I have verified that that issue exists against the `master` branch of Django REST framework.
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [X] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [X] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
import rest_framework.filters
## Expected behavior
It gets imported

## Actual behavior
```
File "/usr/local/lib/python3.8/site-packages/rest_framework/filters.py", line 11, in <module>
    from django.db.models.sql.constants import ORDER_PATTERN
ImportError: cannot import name 'ORDER_PATTERN' from 'django.db.models.sql.constants' (/usr/local/lib/python3.8/site-packages/django/db/models/sql/constants.py)
```

The ORDER_PATTERN has been removed in Django 3.1, see https://github.com/django/django/commit/513948735b799239f3ef8c89397592445e1a0cd5

**Comment by SamMorrowDrums** [comment]
Already fixed in master and this is dupe issue. https://github.com/encode/django-rest-framework/pull/7259

https://github.com/encode/django-rest-framework/issues/7456

https://github.com/encode/django-rest-framework/issues/7455

**Comment by quimey** [comment]
I think this was fixed a while ago in master but there hasn't been any release since last December:

https://github.com/encode/django-rest-framework/commit/e6c1afbcf97e7080c0632ac9e2d60a6d10bd1a5c#diff-01f357e474dd8fd702e4951b9227bffc
