### ISSUE TITLE
Could we release a version for django 3.1 ?

### ISSUE THREAD

**Issue by dcalsky** [encode/django-rest-framework#7459]
## Checklist

- [ ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Django 3.1
importing django rest framework and using filter, it will report `not found ORDER_PATTERN in django.db.models.sql.constants`

## Expected behavior
Work correctly
## Actual behavior
When I look up commits, I found it had been fixed with #7259. But the latest version of django rest framework was released at Dec. 2019 so that this commit is not included.

I have to install django rest framework by git rather than pip, which is not very good to developers who are using python package version control.

Could we release a new version? It has not been updated for more than half a year after all.

**Comment by xordoquy** [comment]
I'm locking the issue and keeping it open to prevent the spam.

**Comment by tomchristie** [comment]
Now released as 3.11.1.

A major release version also to follow in due course.
