### ISSUE TITLE
ModelSerializer Missing support for Django 3.1 JSONField

### ISSUE THREAD

**Issue by youngbob** [encode/django-rest-framework#7466]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

Django 3.1 includes a new generic JSONField to replace the PostgreSQL-specific one:
https://docs.djangoproject.com/en/3.1/releases/3.1/#jsonfield-for-all-supported-database-backends

This is missing in ModelSerializer's field mapping, so a `django.db.models.JSONField` does not get mapped to a JSONField in the serializer.

## Expected behavior

The serializer behaves the same as when using the postgresql version of the field.

## Actual behavior

The new field type is treated as a text field (including schema generation, etc)

**Comment by carltongibson** [comment]
Yes, this will need updating (but it should be straightforward I'm thinking 🤔) 

Would be a good PR.
