### ISSUE TITLE
Custom list actions are not included in default router API root response

### ISSUE THREAD

**Issue by merwok** [encode/django-rest-framework#7468]
## Checklist

- [ ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [ ] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

Version used: 3.11.1

## Steps to reproduce

- define a viewset with list, create, read
- add a custom list action named list2
- use DefaultRouter
- open API root

## Expected behavior
Should see URLs for `model-list` and `model-list2` 

## Actual behavior
Only see `model-list`

**Comment by rpkilby** [comment]
Hi @merwok. I don't think list actions should be in the API root, as list `action`s are children of the endpoint, not siblings. e.g., 

```python

class ThingViewSet(ViewSet):
    def list(self, request, *args, **kwargs):
        ...

    @action(detail=False)
    def blah(self, request, *args, **kwargs):
        ...
```

Your routes would  look something  like

```
/api/things
/api/things/blah
```

not

```
/api/things
/api/things-blah
```

**Comment by merwok** [comment]
Yes, I wrote `things-blah` as the route name, but the URL itself would be `/things/blah/`.

I want them in the API root because they are entry points to the app :slightly_smiling_face:
Clients can use the URL indexed by the key `things` for a regular GET, or the URL for `thing-blah` to do the blah action.  Otherwise they have to hard-code it, or I need a custom router and root API view to add useful links to the root response (which I already have to do for non-viewsets views, but that’s a different debate).

**Comment by merwok** [comment]
I discovered that the method `get_api_root_view` takes a parameter `api_urls` but doesn’t do anything with it, so maybe a change was intended there but never completed.

**Comment by merwok** [comment]
Issue still valid

**Comment by merwok** [comment]
Still want this

**Comment by merwok** [comment]
@auvipy what do you think about this request?

**Comment by auvipy** [comment]
> Hi @merwok. I don't think list actions should be in the API root, as list `action`s are children of the endpoint, not siblings. e.g.,
> 
> ```python
> class ThingViewSet(ViewSet):
>     def list(self, request, *args, **kwargs):
>         ...
> 
>     @action(detail=False)
>     def blah(self, request, *args, **kwargs):
>         ...
> ```
> 
> Your routes would look something like
> 
> ```
> /api/things
> /api/things/blah
> ```
> 
> not
> 
> ```
> /api/things
> /api/things-blah
> ```
> 
> Why do you expect them to be in the API root?

what about this?

**Comment by merwok** [comment]
What about it?  I replied to the question on the same day!

`/api/things/` and `/api/things/blah/` are two entry points into the API, which clients could use without having to hard-code them.
There is no conflict with `/api/things/<thing-ig>/` because the path parts have different formats (verb vs short UUID).

**Comment by auvipy** [comment]
I would refer to more experienced maintainers for a better answer. cc @carltongibson

**Comment by carltongibson** [comment]
I'd close it as wontfix based on Ryan's initial response. 

Roughly, yeah, maybe you want that but it's not how it works — you're welcome to customise the router; possibly a concrete change could be looked at, but it's not something that we're going to address as an active issue. (Sorry)

**Comment by merwok** [comment]
> possibly a concrete change could be looked at

Do you mean a PR would have a chance to be looked at?

**Comment by carltongibson** [comment]
I have to say that it's not likely, but a compelling PR with tests and docs and all the rest of it may be viable. 

I'd very much recommend you make the changes you want in your project and then write up what you did, with your proposal, before going to too
much effort though.

**Comment by merwok** [comment]
I made the changes before opening this ticket, and have copied them from project to project since.

```python

    def get_api_root_view(self, api_urls=None):
        root_dict = {}
        list_name = self.routes[0].name
        action_name = self.routes[1].name

        for prefix, viewset, basename in self.registry:
            # list view
            root_dict[prefix] = list_name.format(basename=basename)
            # extra list action views
            for action in viewset.get_extra_actions():
                if not action.detail:
                    # should probably be {prefix}_{url_name} but this is backward compatible
                    root_dict[f"{action.url_name}_{prefix}"] = action_name.format(
                        basename=basename, url_name=action.url_name,
                    )

        return self.APIRootView.as_view(api_root_dict=root_dict)
```
