### ISSUE TITLE
Unable to validate when many=True

### ISSUE THREAD

**Issue by tuanden0** [encode/django-rest-framework#7471]
## Checklist

- [* ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [* ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [*] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [*] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [ ] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Serilaizer
```
class FloorSerializer(CustomModelSerializer):
    
    def validate(self, data):
        # Count all floor and add current floor instance
        # limit_object_in_floor current is 9
        limit_object_in_floor = Floor.objects.all().count() + 1
        
        if limit_object_in_floor > 10:
            raise serializers.ValidationError('This Floor is Full!')
    
        return data
    
    class Meta:
        model = Floor
        fields = '__all__'
```

Input data:
```
[
   {
      "name": "Floor 10"
   },
   {
      "name": "Floor 11"
   }
]
```

## Expected behavior
Raise exception because the number of floor is larger than 10
`raise serializers.ValidationError('This Floor is Full!')`

## Actual behavior
Create success because limit_object_in_floor = Floor.objects.all().count() always equal 9 even after create "Floor 10" success

**Comment by rpkilby** [comment]
Hi @tuanden0. Validation occurs before data is saved. For each instance, the total count during validation would still be 10, not 10 then 11. You'll probably want to provide a [`list_serializer_class`](https://www.django-rest-framework.org/api-guide/serializers/#customizing-listserializer-behavior) that validates the number of items in the input.
