### ISSUE TITLE
_cached_attrs is not used 

### ISSUE THREAD

**Issue by damonchen** [encode/django-rest-framework#7472]
the code below:

https://github.com/encode/django-rest-framework/blob/1e383f103a1a84461e949e59b001ee61a2e0f7c4/rest_framework/settings.py#L228

 not used by any other place. 

I think it may have some error.

**Comment by rpkilby** [comment]
Hi @damonchen. The `_cached_attrs` stores the set of attrs that have been loaded/cached by the `APISettings` instance. When `reload` is called, it iterates that set and deletes them, clearing the cache.

https://github.com/encode/django-rest-framework/blob/1e383f103a1a84461e949e59b001ee61a2e0f7c4/rest_framework/settings.py#L239-L244
