### ISSUE TITLE
'Category' object is not iterable 

### ISSUE THREAD

**Issue by Ravindrakumara** [encode/django-rest-framework#7475]
#serializers.py

class ItemSerializer(serializers.ModelSerializer):
    brand = serializers.StringRelatedField(many=True)
    category = serializers.StringRelatedField(many=True)
    class Meta:
        model = Item
        fields = ('id','title','image','price','discount','slug','brand',
                  'category','colour','size','weight','discription','modify_date','expiry_date','create_date')

**Comment by tomchristie** [comment]
This isn't an actionable issue in its current state.

**Comment by Ravindrakumara** [comment]
i want show those foriegnkey field data

**Comment by tomchristie** [comment]
Hi there & thanks for your question.

The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions.

Thanks! 😀
