### ISSUE TITLE
Subclasses of BrowsableAPIRenderer should not be output in schema

### ISSUE THREAD

**Issue by jordmantheman** [encode/django-rest-framework#7477]
https://github.com/encode/django-rest-framework/blob/5ce237e00471d885f05e6d979ec777552809b3b1/rest_framework/schemas/openapi.py#L598

A popular library djangorestframework-camel-case defines a subclass of BrowsableAPIRenderer called CamelCaseBrowsableAPIRenderer. This equality check should use issubclass() to determine type hierarchy as opposed to a strict equality comparison of types.

**Comment by carltongibson** [comment]
Hi @jordmantheman. Thanks for the report. Yes, that sounds reasonable. A PR would be very timely there. 

There's a `test_renderer_mapping` that could be fleshed out. I'd suggest ensure that neither the base class, nor any subclasses are included. :+1:
