### ISSUE TITLE
Houston: I have a problem:  ImproperlyConfigured

### ISSUE THREAD

**Issue by josetucuman** [encode/django-rest-framework#7482]
## Help me Please
I'm developing an API example, and when I try to deploy it, I get this message: 
" File "/Users/ereyes/Desktop/PythonDev/RestDjangoApi/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 598, in url_patterns
    raise ImproperlyConfigured(msg.format(name=self.urlconf_name)) from e
django.core.exceptions.ImproperlyConfigured: The included URLconf '<module 'book.urls' from '/Users/ereyes/Desktop/PythonDev/RestDjangoApi/projectfacilito/book/urls.py'>' does not appear to have any patterns in it. If you see valid patterns in the file then the issue is probably caused by a circular import."
 
This is my code: 

from rest_framework import routers
from .viewsets import BookViewSets

rutas = routers.SimpleRouter()

rutas.register('books', BookViewSets)

urlpattern = rutas.urls

Can you help me please? 

Thanks a lot

**Comment by xordoquy** [comment]
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
