### ISSUE TITLE
When will file upload be available in the APIs buitl-in documentation ?

### ISSUE THREAD

**Issue by SamyMe** [encode/django-rest-framework#7486]
I just found in [ release 3.6 announcements](https://www.django-rest-framework.org/community/3.6-announcement/)   that  "File upload and download support in the JavaScript client & API docs." was in the "What's next" session. I was wondering if it was planned on a next release or not ?

And if not , is there a way around it ?
Thank you,

**Comment by carltongibson** [comment]
Hi @SamyMe — I'm afraid that's no longer on the roadmap. With the move to OpenAPI, the CoreAPI based documentation was deprecated. I can't point to a current alternative. You'll need to build something yourself.

**Comment by SamyMe** [comment]
So will there be a new built-in documentation or should we use something like [drf-yasg](https://github.com/axnsan12/drf-yasg/) ?

**Comment by carltongibson** [comment]
https://www.django-rest-framework.org/topics/documenting-your-api/
