### ISSUE TITLE
Force static files routes to go through cors middleware

### ISSUE THREAD

**Issue by lijunhaoabroad** [encode/django-rest-framework#7495]
Hi, I wonder whether there is any way to serve static files cross origin?
I use drf with django-cors-header, but it seems that django skip middleware to serve the static files.
And I don't have access to edit the apache config file to add the cors header.
Thanks in advance!

**Comment by xordoquy** [comment]
This seems to be an issue with your apache config. Static files shouldn't be served by Django.
Please note that this is a Django specific question and the Django User mailing list is the best place to take this discussion.
