### ISSUE TITLE
URLs with escaped parameters are not doubly-escaped by urlize_quoted_links()

### ISSUE THREAD

**Issue by vshih** [encode/django-rest-framework#7498]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
```python
from rest_framework.templatetags.rest_framework import urlize_quoted_links

url = 'http://api/urls/http%3A%2F%2Fabc/'
print(urlize_quoted_links(url))
```

## Expected behavior
```
<a href="http://api/urls/http%3A%2F%2Fabc/" rel="nofollow">http://api/urls/http%253A%252F%252Fabc/</a>
```
## Actual behavior
```
<a href="http://api/urls/http://abc/" rel="nofollow">http://api/urls/http%3A%2F%2Fabc/</a>
```

Note that specifying `autoescape=False` results in the exact same output.

The end result is that such URLs rendered by the browsable API look okay but when clicked populate the address bar with incorrectly escaped URLs.

**Comment by tomchristie** [comment]
Given that this behaviour changed in https://github.com/encode/django-rest-framework/pull/7548/files to use Django's built-in `urllize` I'm going to close this off on the assumption that it's now resolved.
