### ISSUE TITLE
Token.generate_key should be a classmethod for cases when automatic generation is not possible

### ISSUE THREAD

**Issue by Checkroth** [encode/django-rest-framework#7501]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

This isn't a bug but the issue can be seen in the following use case:

I want to bulk insert tokens related to a set of users to avoid costly queries per-user when doing large batch operations. Django's `bulk_insert` does not call the model's `save` method, so I have to manually generate the `key` attribute for each token. To do this, I want to call `Token.generate_key`.

`generate_key` is not a class method, so in order to generate a key for the bulk-insertable objects I must first create a throw-away instance of `Token`. You end up with something like:

```
throwaway_token = Token()
tokens = [Token(user=user, key=throwaway_token.generate_key()) for user in users_list]
Token.bulk_create(tokens)
```

Since `generate_key` doesn't actually operate on the model at all, it makes more sense for it to be a classmethod (or a utility method separate from the model entirely).

## Expected behavior

I would expect to be able to call `Token.generate_key()` to get a key generated the way rest_framework's authtoken model generally automatically generates keys.

## Actual behavior

I have to create throw-away instance of Token in order to use the generate_key functionality.

**Comment by Checkroth** [comment]
Change implemented here: https://github.com/encode/django-rest-framework/pull/7502

**Comment by Eshaan7** [comment]
This is indeed better. Considering the PR has been merged, @Checkroth you should probably close this issue.

**Comment by Checkroth** [comment]
Closing since the change has been implemented
