### ISSUE TITLE
Customized openapi generation by thirdparty-library

### ISSUE THREAD

**Issue by tibnor** [encode/django-rest-framework#7505]
I would like to implement openapi generation for django-rest-polymorphic. The problem is that the current implementation of the open api generation assumes that the nested serializer is not polymorphic. As it is now it is not possible for a third-party to implement a custom method for openapi generation without making a new autoschema (as far as I know :-) )

I have made three branches which in total solves this problem:
[A new method in serializer class which can be implemented for third-party serializers](https://github.com/tibnor/django-rest-framework/tree/third-party-api-for-schema-generation)
[New openapi generation of components, one for each serializer.](https://github.com/encode/django-rest-framework/pull/7504)
[Implementation of openapi generation for django-rest-polymorphic using the suggested API](https://github.com/tibnor/django-rest-polymorphic/tree/Autoschema)

## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

**Comment by carltongibson** [comment]
Hi @tibnor. This looks promising. (Just need some bandwidth to get to it... 😅)

**Comment by tomchristie** [comment]
Closing as stale. (?)
