### ISSUE TITLE
`APIException` ignores `code` passed to it's parameter 

### ISSUE THREAD

**Issue by doomleika** [encode/django-rest-framework#7514]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

1. raise APIException in `APIView`, pass non `500` code in it's constructor

## Expected behavior

Return code should be the same as code passed

## Actual behavior

HTTP code is always 500

## Supplementary
When `APIException` is constructed, the code is never stored as member
https://github.com/encode/django-rest-framework/blob/master/rest_framework/exceptions.py#L107

When `APIView` handles `APIException`, it expects attribute `status_code`, which is never set in `APIException`, as such it refers to the default `APIException.status_code` class member
https://github.com/encode/django-rest-framework/blob/master/rest_framework/views.py#L99

**Comment by doomleika** [comment]
Right, after reviewing the code and the documentation I realized I am not supposed to call `APIException` directly.

Still, I think naming of constructor and `APIException` not a `ABC` really surprising.

**Comment by alxvallejo** [comment]
If you're not suppose to raise an APIException directly, what are you suppose to raise to handle generic exceptions?
