### ISSUE TITLE
Django 3.1 not shown as supported in the docs, pypi

### ISSUE THREAD

**Issue by n2ygk** [encode/django-rest-framework#7518]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

1. Search the issues, tox.ini, setup.py, etc. and see Django 3.1 is present and apparently supported as of 3.11.1.
2. Search the docs, pypi, etc. and see that Django 3.1 is not yet listed.

## Expected behavior

Django 3.1 shows as supported in the documentation, pypi, etc.

## Actual behavior

README.md Requirements says `* Django (2.2, 3.0)`
[pypi.org for 3.11.1](https://pypi.org/project/djangorestframework/3.11.1/) Framework/Django shows: 
```
Framework
Django
Django :: 1.11
Django :: 2.0
Django :: 2.1
Django :: 2.2
```
docs/community/release-notes.md is missing 3.11.1 (ends at 3.11.0)

Perhaps this will be in the forthcoming 3.12.0 release?

I'm happy to submit a PR to bring the various documentation up to date if you like. I'm not quite sure though why pypi.org has it wrong as setup.py has it right.

**Comment by johnthagen** [comment]
This seems to be fixed in the latest release: https://pypi.org/project/djangorestframework/#data

**Comment by xordoquy** [comment]
thanks for the update @johnthagen
