### ISSUE TITLE
Serializer: Introduce a field that allows creation via the PK and serialises the nested representation?

### ISSUE THREAD

**Issue by florianmartens** [encode/django-rest-framework#7520]
I'm not sure if this feature exists and I'm simply unable to find it, but it is a real problem for me. 

I'm using a model serializer that needs different fields for creation than for retrieval. Here is an example for the way I want to retrieve instances of Book:

```
class BookCreateSerializer(serializers.ModelSerializer):
    author = AuthorSerializer(read_only=False)      # <- Note the nested instance

    class Meta:
        model = Book
        fields = (
            'author',
        )
```

On creation, however, I want to assign an author from a list of existing authors by passing the primary key to the serializer. For this, I would need a serializer like this.

```
class BookRetrieveSerializer(serializers.ModelSerializer):

    class Meta:
        model = Book
        fields = (
            'author',     # <- uses the ID by default
        )
```

**Current solutions are:**

- Creating two different serializers (see example)
- Return the nested instance with a serializer.Methodfield

**Why is this a problem?**

It increases the amount of code that I need to write. Also, I can't work with the data that I receive back from a post / put / patch request since it violates the shape I expect (nested instance). Thus, I have to refetch.

If this feature doesn't exist yet, I'd love to discuss a field that would be able to achieve the described behavior?

**Comment by carltongibson** [comment]
Hi. This is been discussed previously (you can search for the issue.) 

Conclusion was (IIRC) that you should subclass PrimaryKeyRelatedField and override to_representation to return the nested representation. (Use a serializer here I guess.)

We decided this wasn't something we'd include in the core framework. If you come up with something suitably generic you could post it here for consideration, or release it in a third-party package. 

Thanks.
