### ISSUE TITLE
Cross Origin not working

### ISSUE THREAD

**Issue by sachintyagi** [encode/django-rest-framework#7528]
Cross Origin is not working.. 

1. Installed module by pip command 

python -m pip install django-cors-headers
![image](https://user-images.githubusercontent.com/763368/92688811-9e33f480-f35b-11ea-95c0-5419637005de.png)

2. Added module in setting file 
![image](https://user-images.githubusercontent.com/763368/92688920-ccb1cf80-f35b-11ea-9d1d-0a993e61e3ec.png)

3. Added Middle ware 
![image](https://user-images.githubusercontent.com/763368/92688980-e0f5cc80-f35b-11ea-9ada-64461054383d.png)

4. Allowed all origins 
![image](https://user-images.githubusercontent.com/763368/92689251-52ce1600-f35c-11ea-8249-0131d3eed67d.png)

5. Still getting error
![image](https://user-images.githubusercontent.com/763368/92689400-945ec100-f35c-11ea-9ad0-a1b2ae1ed2fb.png)

6. HTML Code
![image](https://user-images.githubusercontent.com/763368/92689647-fe776600-f35c-11ea-8c07-eb274c1982a3.png)

Please help

**Comment by xordoquy** [comment]
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
