### ISSUE TITLE
BrowsableAPIRenderer will not render response if has_permission raises Http404

### ISSUE THREAD

**Issue by StefanCardnell** [encode/django-rest-framework#7529]
## Steps to reproduce

1. Subclass `BasePermission` and within `has_permission`, use get_object_or_404 on a non-existent object:

```py

from django.shortcuts import get_object_or_404

class Permission(BasePermission):
    def has_permission(self, request, view):
        # Replace "User" with any other model
        get_object_or_404(User, id=9999999)
```

2. Add permission class to `DEFAULT_PERMISSION_CLASSES` in `settings.py`.

3. Ensure `BrowsableAPIRenderer` is used in `DEFAULT_RENDERER_CLASSES` of `settings.py`

4. Go to an API endpoint in the browser which would utilise `BrowsableAPIRenderer`

## Expected behavior

An API browser should appear with a response of "detail: Not found"

![image](https://user-images.githubusercontent.com/11324477/92771177-9479b380-f392-11ea-8f69-36a715145f56.png)

## Actual behavior

A standard Django error page is returned.

## Workarounds

1. Do not use get_object_or_404 and raise `rest_framework.exceptions.NotFound` directly.

Note: This is only a Browsable API renderer issue, and not an issue when asking for the data in JSON format (with `?format=json`).

## Explanation

As the [DRF Exception Documentations](https://www.django-rest-framework.org/api-guide/exceptions/) explains it can handle Django's `Http404` class, I was surprised by this. After rooting around the DRF code, I saw that in `BrowsableAPIRenderer.show_form_for_method`, the permissions are checked a second time while rendering the response - this time the exception list only includes `exceptions.APIException` and not `Http404` - so the raised 404 inside the permission code bypasses this catch.

```py
 def show_form_for_method(self, view, method, request, obj):
        """
        Returns True if a form should be shown for this method.
        """
        if method not in view.allowed_methods:
            return  # Not a valid method

        try:
            view.check_permissions(request)
            if obj is not None:
                view.check_object_permissions(request, obj)
        except exceptions.APIException:
            return False  # Doesn't have permissions
        return True
```

I certainly can't see anything saying Permission classes should not raise `Http404` exceptions. 

## Use Case

In my use case, the check for an object existence happens in `has_permission` - the client will specify an ID for an object in the request URL GET parameter (**this is not necessarily the same object that is being fetched via the API request path**). This object controls other external behaviour.

Before checking the user has permission to access to the object, I first must ensure it exists with `get_object_or_404`. In the case it doesn't exist, it is natural to respond to the client with 404 instead of 403.

Again, all behaviour is as normal when specifying `format=json`, it is only the API Browser.

**Comment by goldstar611** [comment]
I think you're doing it wrong. https://www.django-rest-framework.org/api-guide/permissions/#custom-permissions
```
To implement a custom permission, override BasePermission and implement either, or both, of the following methods:

.has_permission(self, request, view)
.has_object_permission(self, request, view, obj)

The methods should return True if the request should be granted access, and False otherwise.
```

The last line is the part that is not being followed here. I don't think it's appropriate to raise 404 in a permissions check.

**Comment by goldstar611** [comment]
I think you should do your check by overriding `get_object()` and calling `has_object_permissions()` in there. You get the chance to `raise Http404` in `get_object()` and then in `has_object_permissions()` you either return `True` or `False` to let DRF handle the permission denied message to the requester. :)

```
If you're writing your own views and want to enforce object level permissions, or if you override the get_object method on a generic view, then you'll need to explicitly call the .check_object_permissions(request, obj) method on the view at the point at which you've retrieved the object.```

**Comment by StefanCardnell** [comment]
My reproduction steps might've been misleading but I was hoping to clear it up with the use case. I am using `has_permission` because **the access of the object being checked is not the same object that is being fetched via the API request path**. So `has_object_permission` will never pass for the object which is raising 404. 

Without going in too much in to the nitty gritty details of my work. Front-end users are assigned a "project" and every read of an object instance must be valid for the project they are allocated (the project ID is placed in all request GET parameters - `?project=93248` in my screenshot). 

To check the users actually have access to this project, a Django permission backend checks the user's access to the project ID in `has_permission`. The project ID could be invalid though and while **has_permission** COULD return False this results in a 403 error - but really it is more natural to raise 404.

The normal JSON response with `?format=json` returns the correct 404 error message. It is only BrowsableAPIRenderer which is not returning this message and instead produces a traceback.

**Comment by xordoquy** [comment]
The [documentation](https://www.django-rest-framework.org/api-guide/permissions/#custom-permissions) says:
> The methods should return True if the request should be granted access, and False otherwise.

It does not mention raising an exception and as such your use case is out of the boundaries.
The issue happens in `BrowsableAPI` because it checks permissions on what the user is allowed to see/do and expects a `True`/`False` return, not an exception, hence the global crash.

Closing it as a misuse of the permissions system.

**Comment by StefanCardnell** [comment]
This is not outside of the boundaries, as the case of raising an exception within a REST framework view is very clearly defined with the following [DRF documentation](https://www.django-rest-framework.org/api-guide/exceptions/#exception-handling-in-rest-framework-views):

> REST framework's views handle various exceptions, and deal with returning appropriate error responses.
> The handled exceptions are:
> 
> Subclasses of APIException raised inside REST framework.
> **Django's Http404 exception**.
> Django's PermissionDenied exception.
> In each case, REST framework will return a response with an appropriate status code and content-type. The body of the response will include any additional details regarding the nature of the error.
> 
> Most error responses will include a key detail in the body of the response.

The permission documents don't mention what happen in the case of Exceptions, it doesn't need to - the overarching documentation on Exceptions implicitly handles these cases. The DRF documentation shouldn't be expected to have to keep indicating what happens in the case of Exceptions, because this documentation is in place. 

As permission checks happen within the View, this is very much defined behaviour. 

It can even be seen in the [DRF source code for APIView](https://github.com/encode/django-rest-framework/blob/5828d8f7ca167b11296733a2b54f9d6fca29b7b0/rest_framework/views.py#L492):

`py...        
    def dispatch(self, request, *args, **kwargs):
        """
        `.dispatch()` is pretty much the same as Django's regular dispatch,
        but with extra hooks for startup, finalize, and exception handling.
        """
        self.args = args
        self.kwargs = kwargs
        request = self.initialize_request(request, *args, **kwargs)
        self.request = request
        self.headers = self.default_response_headers  # deprecate?

        try:
            self.initial(request, *args, **kwargs)

            # Get the appropriate handler method
            if request.method.lower() in self.http_method_names:
                handler = getattr(self, request.method.lower(),
                                  self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            response = handler(request, *args, **kwargs)

        except Exception as exc:
            response = self.handle_exception(exc)

        self.response = self.finalize_response(request, response, *args, **kwargs)
        return self.response`

`self.initial` of `APIView` calls `check_permissions`. The whole thing is wrapped in an exception handler and passed through to `handle_exception`, where `APIException`, `PermissionDenied` and `Http404` are handled as the documentation say.

I stand by that as the `?format=json` JSON response produces the correct 404 error but the BrowsableAPIRenderer is not able to render that response and instead tracebacks, this is ultimately an issue with BrowsableAPIRenderer.

**Comment by xordoquy** [comment]
Permissions are something different than the views.
The fact that it works with some renderer does not mean it must work with all.
