### ISSUE TITLE
Related foreign keys serialization is 10 times slower since Django 3.x

### ISSUE THREAD

**Issue by nipmarsh** [encode/django-rest-framework#7534]
## Checklist

- [ ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Write a serializer serializing foreign keys or many to many

## Expected behavior
Same speed or faster as Django 2.x

## Actual behavior
10 times slower than Django 2.x

**Comment by xordoquy** [comment]
This issue is hardly actionnable in its current form.
Do you have reproductible benchmark that we could run to confirm or not the issue ?
Do you have some analysis about that difference ?
Did you run a git bissect on Django to figure what could have cause this issue ?

**Comment by nipmarsh** [comment]
I've tested many things before pointing this out.
First i bench django queries and they are still fast but getting the response was really slow.
Secondly i suspected pagination_class so i commented this on a queryset and it was still slow.
Finally, i commented the serialization_class and the response on the client side was fast.

On a serializer, i commented the serialization of all foreign keys and it was still fast.
After reenabling the serialization of foreign keys, everythings became really slow.

When i say 10 times it is just to say that the speed difference is really visible

**Comment by xordoquy** [comment]
@nipmarsh is that bench available ?

**Comment by carltongibson** [comment]
> On a serializer, i commented the serialization of all foreign keys and it was still fast.
After reenabling the serialization of foreign keys, everythings became really slow.

Are you talking about with the BrowsableAPI? Is the response faster with a plain JSON response?

**Comment by xordoquy** [comment]
> > On a serializer, i commented the serialization of all foreign keys and it was still fast.
> > After reenabling the serialization of foreign keys, everythings became really slow.
> 
> Are you talking about with the BrowsableAPI? Is the response faster with a plain JSON response?

I don't think that would change in between the two Django version.
Unless I do have an issue with my projects, I will be waiting for a showcase first to understand what's happening.

**Comment by tomchristie** [comment]
Inclined to agree with @xordoquy here - Django 3.0 has been out for 9 months now. We'd *strongly* expect to have multiple reports if there was an issue as clear-cut as reported here.

That's not to say that there isn't an issue, but it's pretty hard to do anything useful unless we've got a clearer indication that something performance related really has changed in the interaction between REST framework and Django, that's occurred between different versions of Django.

(Also: https://github.com/encode/django-rest-framework/pull/7142 came to mind here, but I can't see how it'd be related)

**Comment by nipmarsh** [comment]
> @nipmarsh is that bench available ?

I'll do that as soon as i can.

**Comment by nipmarsh** [comment]
Here is a bench with Django==2.2.7, djangorestframework==3.10.3

![Capture d’écran 2021-01-10 à 16 30 31](https://user-images.githubusercontent.com/19568990/104127278-8ac48480-5361-11eb-879f-261d2ea8da7a.png)

and with the last django and djangorestframework versions

![Capture d’écran 2021-01-10 à 16 25 05](https://user-images.githubusercontent.com/19568990/104127296-a62f8f80-5361-11eb-8bb0-7fa260a888d9.png)

This two captures show that the last versions of django and djangorestframework is 3 times slower
I only updated those two packages

**Comment by xordoquy** [comment]
This is not something I can test on my side :(
I'm going to close that issue for now and will reconsider when we have something we can also run and associated source code that we can analyse.

**Comment by nipmarsh** [comment]
@xordoquy Thanks a lot
