### ISSUE TITLE
Specifying `read_only_fields` option does NOT work on NESTED serializers

### ISSUE THREAD

**Issue by DrJfrost** [encode/django-rest-framework#7537]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
when you have a nested representation to serialize, it will ask you to send that field on the request data unless you explicitly specify that on the field, instead of taking the `read_only_fields` option, for example:

nonworking code:
```python

class UserSerializer(serializers.ModelSerializer):

    groups = GroupSerializer(many=True)

    class Meta:
        model = User
        fields = ['id', 'username', 'password', 'first_name', 'last_name', 'email', 'phone', 'image', 'last_login', 'date_joined', 'is_active', 'groups']
        read_only_fields = ['last_login', 'date_joined', 'groups']
        extra_kwargs = {'password': {'write_only':True}}
```
## Expected behavior
the library should be able to add the `read_only = True` option to the field based on the configuration set on the `read_only_fields` however it does not work and you have to instead specify that explicitly on the field (making code a little bit too verbose since you would have some sort of mixture between read_only_fields and read_only options)
```python

class UserSerializer(serializers.ModelSerializer):

    groups = GroupSerializer(many=True, read_only=True)

    class Meta:
        model = User
        fields = ['id', 'username', 'password', 'first_name', 'last_name', 'email', 'phone', 'image', 'last_login', 'date_joined', 'is_active', 'groups']
        read_only_fields = ['last_login', 'date_joined']
        extra_kwargs = {'password': {'write_only':True}}
```
## Actual behavior
the `read_only_fields` option completely ignores the setting for the nested field and makes it a "required field" unless you explicitly specify that on the field, making the code a lil too much verbose.

**Comment by xordoquy** [comment]
`read_only_fields` will not override an explicitly defined field - nested or not.
The documentation says:

> Instead of adding each field explicitly with the read_only=True attribute

It does not say `Instead of adding explicitly the read_only=True attribute to each field`.

**Comment by DrJfrost** [comment]
ok I think that was clear although I think it should be more straightforward on the documentation, specially on nested scenarios since there is not so much documentation about nested cases.

**Comment by xordoquy** [comment]
@DrJfrost feel free to open a PR to add a few words about `read_only_fields` not being applied on explicitly defined fields. Such wording already exists for [additional keyword arguments](https://www.django-rest-framework.org/api-guide/serializers/#additional-keyword-arguments)
