### ISSUE TITLE
[Tutorial] UserViewSet Docstring - 'retrieve' action instead of 'detail' action. 

### ISSUE THREAD

**Issue by anilkam** [encode/django-rest-framework#7538]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Docstring of UserViewSet in DRF Tutorial (https://raw.githubusercontent.com/encode/django-rest-framework/master/docs/tutorial/6-viewsets-and-routers.md)

## Expected behavior
Docstring should be:
This viewset automatically provides `list` and `retrieve` actions.

## Actual behavior
Docstring currently is:
This viewset automatically provides `list` and `detail` actions.

**Comment by C0DK** [comment]
IIRC the action is called retrieve, however the view they previously had in the documentation was called "detail" - maybe that view should be changed to `SnippetRetrieve`

**Comment by xordoquy** [comment]
`retrieve` is the action as you can see a few lines below:

```
'get': 'retrieve',
```

**Comment by anilkam** [comment]
> IIRC the action is called retrieve, however the view they previously had in the documentation was called "detail" - maybe that view should be changed to `SnippetRetrieve`

I was referring to the DocString for UserViewSet

**Comment by anilkam** [comment]
> `retrieve` is the action as you can see a few lines below:
> 
> ```
> 'get': 'retrieve',
> ```

I agree, that's why I suggested that the Docstring of `UserViewSet` class also say the same, currently it says that the action is `detail`

**Comment by xordoquy** [comment]
Got it, thanks. Fixed in a849627.

**Comment by C0DK** [comment]
Sorry i misunderstood - i thought you made the opposite point.
