### ISSUE TITLE
Pagination as option in deafult turned on and other problems

### ISSUE THREAD

**Issue by ManPython** [encode/django-rest-framework#7541]
## Checklist

- [v] I have verified that that issue exists against the `master` branch of Django REST framework.
- [v] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [v] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [v] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
I tested most examples and type of pagination and they not working on Python38 (amd64) and DJ 3.1.1 - don't know why.

## Expected behavior
Limited data in format=api to 10 elements and pages for next/prev with web controls as icons

## Actual behavior
There is no any errors that can show. Just no exist any controls as next prev, etc.
And not working any urls to operater on sizepage, etc.

In my opinion should exist option in default turned on pagination for format=api in case that long data hanging browser due to rendering css colours. 
In fact whole description is soo not intuitive that made for users problems how to turn on paginations. Looks simple but not in pratice. 
Eg. is not clear in which class type of ViewAPI pagination working or not working or should be used for any option.

**Comment by tomchristie** [comment]
Hi there & thanks for your question.

The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions.

Thanks! 😀
