### ISSUE TITLE
[BUG] `PrimaryKeyRelatedField` Serializer Converts `True` Value Into ID and Succeeds

### ISSUE THREAD

**Issue by loganknecht** [encode/django-rest-framework#7542]
## Gratitude

Hey all - Thank you for the wonderful library, and thank you for maintaining it! It has REALLY simplified a lot of my API's creation.

## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

```python
from django.db.models import Model
from django.db.models import CASCADE
from django.db.models import CharField
from django.db.models import ForeignKey
from rest_framework.serializers import PrimaryKeyRelatedField
from rest_framework.serializers import Serializer


class FooModel(Model):
    name = CharField("Name", max_length=100)


class BarModel(Model):
    foo = ForeignKey(FooModel, on_delete=CASCADE)


class BarSerializer(Serializer):
    foo_id = PrimaryKeyRelatedField(queryset=FooModel.objects.all())

    class Meta:
        fields = ("foo_id",)


foo_one = FooModel.objects.create(name="example_one")

correct_example_bar_data = {"foo_id": foo_one.id}
correct_bar_serializer = BarSerializer(data=correct_example_bar_data)
is_correct_bar_data_valid = correct_bar_serializer.is_valid()

incorrect_example_bar_data = {"foo_id": True}
incorrect_bar_serializer = BarSerializer(data=incorrect_example_bar_data)
is_incorrect_bar_data_valid = incorrect_bar_serializer.is_valid()
```

## Expected behavior

This should fail. My understanding is that a `PrimaryKeyRelatedField` should point to a `Primary Key` and then use the `queryset` that is assigned in the serializer to work correctly.

## Actual behavior

What happens is this

```python
>>> correct_example_bar_data = {"foo_id": foo_one.id}
>>> correct_bar_serializer = BarSerializer(data=correct_example_bar_data)
>>> is_correct_bar_data_valid = correct_bar_serializer.is_valid()
>>>
>>> is_correct_bar_data_valid
True
>>> incorrect_example_bar_data = {"foo_id": True}
>>> incorrect_bar_serializer = BarSerializer(data=incorrect_example_bar_data)
>>> is_incorrect_bar_data_valid = incorrect_bar_serializer.is_valid()
>>>
>>> is_incorrect_bar_data_valid
True
```

## Addendum

I only found this because I was creating tests to fuzz data and found that it would convert a `True` value and then it kept returning the first `model` of the query set.

## Requested Solution

Please make it so that the serializer will fail on validation when a string of `True` is provided. It doesn't make sense why that is working.

Also acceptable, please provide a work around for what I should be doing.

**Comment by loganknecht** [comment]
Shameless bump

**Comment by amikrop** [comment]
It seems this has to do with Django's QuerySet API treating `.get(pk=True)` as `.get(pk=1)`.
If you try `FooModel.objects.get(pk=True)` after running your snippet you should get the first FooModel object in the database.
