### ISSUE TITLE
JSONEncoder goes into infinite recursion trying to serialize a mock object

### ISSUE THREAD

**Issue by MattFisher** [encode/django-rest-framework#7546]
## Checklist

- [X] I have verified that that issue exists against the `master` branch of Django REST framework.
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [X] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [X] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
During testing, if a dict returned from an API view function contains a mock object (eg from a patched function), the process will enter an infinite loop during `response.render`.
Using the debugger to check what's going on, you can find mocks being created of the form `<MagicMock name='my_mock_object.tolist().tolist()...{100+}...tolist().tolist' id='5008861448'>`.
I think what's happening is in `JSONEncoder.default`, this clause is causing an infinite recursion:
```
    elif hasattr(obj, 'tolist'):
        # Numpy arrays and array scalars.
        return obj.tolist()
```

## Expected behavior
Knowing how to serialize a Mock in the general case seems like a hard problem. Throwing an exception like the default json encoder seems reasonable:
```
> from unittest import mock
> from rest_framework.utils import json
> json.dumps(mock.Mock())
Traceback (most recent call last):
  File "/{...}/python3.6/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-11-5739853f0191>", line 1, in <module>
    dumps(mock_object)
  File "/{...}/djangorestframework/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Mock' is not JSON serializable
```

## Actual behavior
```
> from unittest import mock
> from rest_framework.utils import json
> from rest_framework.utils.encoders import JSONEncoder
> json.dumps(mock.Mock(), cls=JSONEncoder)
# => infinite loop
```

Note the same behaviour occurs with both encoders whether the mock is the top-level object like `json.dumps(mock.Mock())`, or a field within the dict like `json.dumps({'thing': mock.Mock()})`. The behaviour is also the same whether `json` or `rest_framework.utils.json` is used.

**Comment by tomchristie** [comment]
Okay, I think we might have to treat this as an unactionable edge-case, unless someone has a specific suggestion here.
