### ISSUE TITLE
Typographical error in serializers.py

### ISSUE THREAD

**Issue by esiebomaj** [encode/django-rest-framework#7552]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Expected behavior
There is a typographical error in serializers.py line 118  wish to fix
**automatically** is spelled as **automagically**

**Comment by xordoquy** [comment]
that's on purpose because it isn't something expected that creating a `Serializer` creates a `ListSerializer`.
