### ISSUE TITLE
Changes in compat.py in DRF 3.12.0 causes error in drf-yasg library.

### ISSUE THREAD

**Issue by rozacek** [encode/django-rest-framework#7555]
## Checklist

- [v] I have verified that that issue exists against the `master` branch of Django REST framework.
- [v ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [v] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [v] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [v] I have reduced the issue to the simplest possible case.
- [ x] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Install Third-Party library https://github.com/axnsan12/drf-yasg tow which docs encourages in some way: https://www.django-rest-framework.org/topics/documenting-your-api/#third-party-packages

## Expected behavior
It works as in docs:

## Actual behavior
Best described here: https://github.com/axnsan12/drf-yasg/issues/641

## What caused?

Probably removing these lines in copat.py

```
try:
    from django.urls import (  # noqa
        URLPattern,
        URLResolver,
    )
except ImportError:
    # Will be removed in Django 2.0
    from django.urls import (  # noqa
        RegexURLPattern as URLPattern,
        RegexURLResolver as URLResolver,
    )
```

I don't know what was the purpose of removal these lines but from me as use, this is a bug.

**Comment by carltongibson** [comment]
You need to update Django. All versions less than 2.2 are end of life.
