### ISSUE TITLE
How to identify the action in ViewSets

### ISSUE THREAD

**Issue by DeeKristo** [encode/django-rest-framework#7562]
Hi All,

I am trying to restrict TokenAuthentication to some methods( in this case to my_method in the below snippet) in the ViewSets. Below is the snippet of code,

```
class MyViewSet(ViewSet):
    def get_authenticators(self):
        if self.action == 'my_method':
            return [TokenAuthentication()]
        return []

    def my_method(self, request, *args, **kwargs):
          < rest of logic goes here >
```

But I get the error saying , **MyViewSet has no attribute action**.

Am I doing it in a wrong way? or this is not available in the ViewSet.

Please let me know the correct way to achieve this.

**Comment by xordoquy** [comment]
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions.
The `get_authenticators` is called way ahead of the action selection and thus will not work at this point.

**Comment by DeeKristo** [comment]
But could you let me know how to get the action attribute in my case.

**Comment by EXG1O** [comment]
@DeeKristo, my proposed [fix](https://github.com/encode/django-rest-framework/discussions/9614#discussion-7792227).
