### ISSUE TITLE
LimitOffsetPagination's max_limit not taken into account when no limit parameter in the request

### ISSUE THREAD

**Issue by MaxLarue** [encode/django-rest-framework#7575]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

Create a ModelViewSet with a pagination_class which specifies a max_limit:
```
class Max10LimitOffsetPagination(pagination.LimitOffsetPagination):
    max_limit = 10

class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer
    pagination_class = Max10LimitOffsetPagination
```
Then (assuming you have more than 10 users in the database), perform a GET request against the list endpoint without specifying either limit or offset parameters

```
GET localhost:8000/api/users/
```
 
## Expected behavior

Only the first 10 users are returned

## Actual behavior

Up to `default_limit` users are returned

Not sure if this is by design, but if it is i feel it should be documented in the LimitOffsetPagination's `max_limit` section.

The documentation states that indeed `default_limit` will be used if no limit parameter is provided, but max_limit gives the impression that client won't be able to pull more data at once, event though this is not the case when omitting the limit param.

**Comment by metalerk** [comment]
@MaxLarue I'm not sure if this is what you are looking for but check [this out](pagination).

**Comment by kevin-brown** [comment]
Wouldn't it make sense for this to enforce that the default limit must be less than or equal to the max limit if the max limit is set?

**Comment by tomchristie** [comment]
Closing as per #7940

Could we change this? Yes.
Would it result it marginally more complexity, and slightly less obvious code yes?
