### ISSUE TITLE
Add OpenTracing/OpenTelemetry instrumentation

### ISSUE THREAD

**Issue by albertteoh** [encode/django-rest-framework#7592]
It appears that the Django Rest Framework (DRF) is currently not instrumented for tracing.

Based on observations from local tests, if tracing is enabled in the `settings.py` file I can see traces and spans from DRF; however, only single span traces are visible.

I don't have a strong understanding of ViewSets (and forgive my ignorance), but would have expected `Group.objects.all()` to result in another child span.

I also could not find evidence of tracing instrumentation within the code.

A specific sample use case is to have visibility on latency of backend services handling the request, or latency of database calls.

## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

1. Follow [Quickstart tutorial](https://www.django-rest-framework.org/tutorial/quickstart/).

2. Instrument example using [OpenTracing for Python Django (with Jaeger)](https://github.com/opentracing-contrib/python-django).

3. Resulting `settings.py` file below.
4. Start up Jaeger all-in-one:
```
docker run -d --name jaeger \
  -e COLLECTOR_ZIPKIN_HTTP_PORT=9411 \
  -p 5775:5775/udp \
  -p 6831:6831/udp \
  -p 6832:6832/udp \
  -p 5778:5778 \
  -p 16686:16686 \
  -p 14268:14268 \
  -p 14250:14250 \
  -p 9411:9411 \
  jaegertracing/all-in-one:1.20
```

5. Run the web server: `python manage.py runserver 8000`

6. Hit the groups endpoint: http://127.0.0.1:8000/groups/

7. Search for the trace in Jaeger: http://localhost:16686/

**settings.py**
``` 
"""
Django settings for tutorial project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import django_opentracing
from jaeger_client import Config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'xgb(jxbs@*+p#u&^$*)ir$_#%0i3$r+8b-6rrgj7&&%_qt+2kl'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
]

MIDDLEWARE = [
    'django_opentracing.OpenTracingMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tutorial.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tutorial.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}

# Opentracing & Jaeger
SERVICE_NAME = "backend"

def tracer():
    config = Config(
        config={
            'sampler': {
                'type': 'const',
                'param': 1,
            },
            'logging': True,
        },
        service_name=SERVICE_NAME,
        validate=True
    )
    return config.initialize_tracer()
OPENTRACING_TRACING = django_opentracing.DjangoTracing(tracer())
OPENTRACING_TRACE_ALL = True
OPENTRACING_TRACED_ATTRIBUTES = ['META', 'path', 'method', 'status_code']
```

## Expected behavior
Traces with nested spans like so:
![Screen Shot 2020-10-13 at 8 50 52 pm](https://user-images.githubusercontent.com/26584478/95856676-20be3280-0da6-11eb-8769-8b40588d9994.png)

## Actual behavior
Single span of the initial handling of the API call, but no child spans:
![Screen Shot 2020-10-13 at 10 49 17 pm](https://user-images.githubusercontent.com/26584478/95856840-6b3faf00-0da6-11eb-8e8f-75f72ab89a38.png)
![Screen Shot 2020-10-13 at 9 39 29 pm](https://user-images.githubusercontent.com/26584478/95856851-709cf980-0da6-11eb-9ad5-a74d326eb993.png)

**Comment by xordoquy** [comment]
I don't see any reason to have a child span here as the request is a single span. Please check again the multiple span example from open tracing. It's a fake child span so nothing that is expected to happen in an out-of-the-box DRF view.

**Comment by albertteoh** [comment]
@xordoquy, `Group.objects.all()` is a database call and this is the reason why this should be a child span. Why would it be fake? I thought it's making a real database call into, in my case, sqlite, to retrieve the list of auth_groups.

When I query sqlite, I can see the updated auth_users and auth_groups, which is consistent with what I see in the forms.

**Comment by xordoquy** [comment]
@albertteoh can you point me where your expected behaviour is documented ?

**Comment by albertteoh** [comment]
@xordoquy please refer to the [Jaeger documentation](https://www.jaegertracing.io/docs/1.20/).

Here's a screenshot from the Jaeger documentation that shows an example trace with a database call to MySQL as one of the child spans of the initial HTTP GET request handling span (near the top of the image): https://www.jaegertracing.io/img/trace-detail-ss.png.

This is what I would be expecting to see in Jaeger when hitting the http://127.0.0.1:8000/users/ or http://127.0.0.1:8000/groups/ endpoints.

**Comment by xordoquy** [comment]
@albertteoh this not what I asked for. I know Jaeger can do it, the question is, does `django_opentracing` do it ?
My feeling is it doesn't and it's not an issue for DRF.

**Comment by albertteoh** [comment]
@xordoquy  If you're asking if `django_opentracing` is able to instrument django, then the answer is yes. The screenshot I gave under the "Expected behavior" title is the result and what I would expect to see in DRF.

I've taken the liberty of pushing a full working example of a correctly instrument Django website: https://github.com/albertteoh/python-django/tree/simple-example-tracing.

If you would like to see it working:


1. Startup Jaeger
```
docker run -d --name jaeger \
  -e COLLECTOR_ZIPKIN_HTTP_PORT=9411 \
  -p 5775:5775/udp \
  -p 6831:6831/udp \
  -p 6832:6832/udp \
  -p 5778:5778 \
  -p 16686:16686 \
  -p 14268:14268 \
  -p 14250:14250 \
  -p 9411:9411 \
  jaegertracing/all-in-one:1.20
```
2. `pip install django_opentracing`
3. `git clone git@github.com:albertteoh/python-django.git`
4. `git checkout simple-example-tracing`
5. `cd example`
6. `python manage.py runserver 8000`
7. Go to http://127.0.0.1:8000/client/log in your browser.
8. Check for the trace in http://localhost:16686/

**Comment by xordoquy** [comment]
The screenshot you provided in the expected section [explicitly starts child spans](https://github.com/albertteoh/python-django/blob/simple-example-tracing/example/server/views.py#L25).
So unless you did override a viewset with that explicit child spanning, I don't see any reason any child span should appear.
By default, the behaviour would be the same as the [simple example](https://github.com/albertteoh/python-django/tree/simple-example-tracing/example#trace-a-request-and-response) which is similar to your screenshots

**Comment by albertteoh** [comment]
I did not explicitly start a span, but that's what I'm trying to communicate in this issue; the need for tracing instrumentation and improved observabiility (starting spans) for downstream calls, say, to a DB so users of the DRF can accurately measure the DB latency.

However, if you feel it's not useful to have tracing enabled in DRF, then we can leave it at that.

Thanks for your responses in any case, @xordoquy :)

**Comment by xordoquy** [comment]
> I did not explicitly start a span

I'm lost.
The screenshot you provided under `expected behaviour` in the issue matches the `server_child_span` call in the example, right ?

**Comment by albertteoh** [comment]
Yes, that's correct. I explicitly start a span for https://github.com/encode/django-rest-framework/issues/7592#issuecomment-708329206, which is an example of instrumenting Django which uses django_opentracing and this is what I would expect.

However, for DRF, I did not explicitly start a span (because I don't know how/where I should do this) and although I see a single span for a trace, I expect to see downstream calls (child spans) because it is making database queries. 

What I'm getting at is I believe DRF middleware may need explicit instrumentation (like https://github.com/albertteoh/python-django/blob/simple-example-tracing/example/server/views.py#L25) in order to see traces, unless if there's a better way of instrumenting DRF that I'm not aware of.
