### ISSUE TITLE
AnonRateThrottle does not handle cache connection errors

### ISSUE THREAD

**Issue by tucosaurus** [encode/django-rest-framework#7594]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

- Add [django_redis](https://github.com/jazzband/django-redis) as the default cache backend.
- Configure with an invalid redis url or bring down the redis service.

Django redis configuration for reference:

```
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": env("REDIS_URL", default="redis://localhost:6379/0"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "PARSER_CLASS": "redis.connection.HiredisParser",
            "CONNECTION_POOL_CLASS": "redis.BlockingConnectionPool",
            "CONNECTION_POOL_CLASS_KWARGS": {
                "max_connections": env.int("REDIS_MAX_CONNECTIONS", default=1),
                "timeout": 1,
            },
            "SOCKET_CONNECT_TIMEOUT": 1,  # seconds
            "SOCKET_TIMEOUT": 1,  # seconds
        },
    }
}
```

## Expected behavior

- A connection error must be raised by the throttle class

## Actual behavior

- No connection error is raised. The error is bubbled to django's exception handler which is not able to recognize the connection error and the thread hangs for some reason.

As an alternative, we can disable throttle classes on a view (example: health check views for the app) or configure `LocMem` as the throttle cache backend.

**Comment by tucosaurus** [comment]
I would be happy to send in a pull request if the maintainers think that this would be a worthwhile addition.

**Comment by cosmosgenius** [comment]
Does `django_redis` raise that exception anywhere else? like during a manual cache call?

**Comment by xordoquy** [comment]
Note: I'm closing this because I can not reproduce. All I get is a connection exception that is risen.
If the issue was about silently discarding the connection to Redis, I'm not sure we'll want that because that would mean the throttling can break without the administrator knowing.
