### ISSUE TITLE
request.user fails to return User when using TokenAuthentication

### ISSUE THREAD

**Issue by riensen** [encode/django-rest-framework#760]
The function request.user does not return the a user object when TokenAuthentication is used.

**Comment by belegnar** [comment]
request.user is still returns AnonymousUser when accessed from dispatch(), but it is defined as authenticated user in post() and other methods.

This is not common for django, request.user is defined as authenticated user in dispatch()

**Comment by xordoquy** [comment]
@belegnar DRF differs from Django here. The authentication is done through the DRF's Request when getting the user. This allows to have a single site with regular django views playing nice DRF API and still have specific auth scheme for DRF (token, oauth...)

**Comment by OrangeDog** [comment]
This continues to be a problem, as middleware cannot see the user that authenticated via token.
The `request.user` always appears as `AnonymousUser`.

**Comment by xordoquy** [comment]
Incoming requests will be authenticated by DRF after the middleware stack is passed.
If you need a different behavior, you'll have to write authentication middlewares.
