### ISSUE TITLE
PROPOSAL: Custom HTTP header for token auth

### ISSUE THREAD

**Issue by snowman2** [encode/django-rest-framework#7605]
Would the ability to provide a custom header for token auth be something y'all would be interested in.

Currently it is statically set at `HTTP_AUTHORIZATION`.

In `settings.py` could add something like:
```python
REST_FRAMEWORK = {
    ...
    "TOKEN_HTTP_HEADER": "HTTP_X_API_KEY"
}
```

Thoughts?

**Comment by Eshaan7** [comment]
The inbuilt auth mechanism in DRF is quite limited so you'd better off using third party auth libs for DRF which allow this functionality. https://www.django-rest-framework.org/api-guide/authentication/#third-party-packages

**Comment by xordoquy** [comment]
Beside, the `AUTHORIZATION` is defined in RFC, I don't see a good enough reason why the core should allow to customize it.

**Comment by valentijnscholten** [comment]
There situations where you can have multiple proxies all "doing something" with the authorization header. Multiple values in the authorization header are not always supported properly by all proxies. For example Google Identity Aware Proxy currently has a problem with multiple applications using the Authorization header: https://stackoverflow.com/questions/59297161/using-nested-authentication-with-google-iap/59297859#59297859
