### ISSUE TITLE
[BUG] Ordering filter with Model property serializer field

### ISSUE THREAD

**Issue by omerfarukabaci** [encode/django-rest-framework#7608]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

Create the following:

#### `models.py`

```python
class OrderingFilterModel(models.Model):
    title = models.CharField(max_length=20, verbose_name='verbose title')
    text = models.CharField(max_length=100)

    @property
    def description(self):
        return self.title + ": " + self.text
```

#### `serializers.py`

```python
class OrderingFilterSerializerWithModelProperty(serializers.ModelSerializer):
    class Meta:
        model = OrderingFilterModel
        fields = (
            "id",
            "title",
            "text",
            "description"
        )
```

#### `views.py`

```python
class OrderingListView(generics.ListAPIView):
    queryset = OrderingFilterModel.objects.all()
    serializer_class = OrderingFilterSerializerWithModelProperty
    filter_backends = (filters.OrderingFilter,)
    ordering = ('title',)
```

#### `test.py`

```python
from rest_framework.test import APIRequestFactory

factory = APIRequestFactory()

view = OrderingListView.as_view()
request = factory.get('/', {'ordering': 'description'})
```

## Expected behavior

Ignoring the `description` field since it is not a model field.

## Actual behavior

It is trying to use `order_by` on the `queryset` using `description` field, which results in the following error and return a `500 InternalServerError` :

```
FieldError
Cannot resolve keyword 'description' into field. Choices are: id, title, text
```

## Description

First, thanks for creating/maintaining this great library! I have opened a [PR](https://github.com/encode/django-rest-framework/pull/7609) which includes both a failing test and a solution. I would be glad to discuss about the problem and the solution.

**Comment by serg472** [comment]
Not sure if it's the same issue, but it also fails to order by an annotated field with a similar error.

```
queryset = MyModel.objects.all().annotate(total=models.Sum('field'))
ordering_fields = ['total']
```

It says it couldn't resolve "total" into a field. I narrowed it down to django 3.1 release, with 3.0.12 it was still working fine. I'm using DRF 3.12.2.

Thanks.

**Comment by tomchristie** [comment]
@serg472 No that doesn't seem like the same case as this. You're welcome to raise a Q&A discussion on that if you're still seeing it as a problem.
