### ISSUE TITLE
Nested serializer not returning full image url for ImageField but only relative path

### ISSUE THREAD

**Issue by benzgrant** [encode/django-rest-framework#7611]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
I have the following models
```
class User(models.Model):
    items = models.ForeingKey(...)

class Item(models.Model):
    image = models.ImageField(...)
```

and the following serializers
```
class UserSerializer(serializers.ModelSerializer):
    items = ItemSerializer(many=True, read_only=True)

    class Meta:
        model = User
        fields = '__all__'
        depth = 1

class ItemSerializer(serializers.ModelSerializer):
     class Meta:
        model = Item
        fields = '__all__'
```

UserSerializer returns only the image path
```
...
"image": "/media/items/image.png",
...
```

while ItemSerializer returns the full image urls
```
...
"image": "http://localhost:8000/media/items/image.png",
...
```

## Expected behavior
The nested serializer should return the full image url for an ImageField

## Actual behavior
The nested serializer returns the image path

**Comment by benzgrant** [comment]
Solved. In the view:

```
serializer = self.serializer_class(self.request.user, context={
    'request': request
})
```

This seams a bit strange, maybe DRF should do it by itself (?)

**Comment by xordoquy** [comment]
> This seams a bit strange, maybe DRF should do it by itself

DRF already does it. You may have some unpasted code that overrides DRF's defaults.
