### ISSUE TITLE
Documentation: `data` should be `validated_data`

### ISSUE THREAD

**Issue by jblachly** [encode/django-rest-framework#7612]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [NA] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

Documentation here:
https://www.django-rest-framework.org/api-guide/viewsets/#marking-extra-actions-for-routing
(confirmed on master: https://github.com/encode/django-rest-framework/blob/master/docs/api-guide/viewsets.md)

gives example code:
```
    @action(detail=True, methods=['post'])
    def set_password(self, request, pk=None):
        user = self.get_object()
        serializer = PasswordSerializer(data=request.data)
        if serializer.is_valid():
            user.set_password(serializer.data['password'])
            user.save()
            return Response({'status': 'password set'})
        else:
            return Response(serializer.errors,
                            status=status.HTTP_400_BAD_REQUEST)
```

after the call to `is_valid`, `serializer.data` is empty. The call should be to `validated_data`

## Expected behavior
`request.data` in the serializer

## Actual behavior
`{}`

**Comment by xordoquy** [comment]
looks valid to me. Want to submit the PR to fix it ?

**Comment by jblachly** [comment]
@xordoquy Thanks for confirming. PR submitted
