### ISSUE TITLE
select_related() FieldError ignored in View

### ISSUE THREAD

**Issue by qu3vipon** [encode/django-rest-framework#7613]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
```python
class City(models.Model): 
    pass 

class Person(models.Model): 
    name = models.CharField(max_length=30)
    hometown = models.ForeignKey(City, on_delete=models.SET_NULL, blank=True, null=True) 

class Book(models.Model): 
    author = models.ForeignKey(Person, on_delete=models.CASCADE)
```

`Book.objects.selected_related('auther__name')` raises `django.core.exceptions.FieldError: Non-relational field given in select_related` in Django shell as I expected.

But same code in DRF View doesn't raise any errors. select_related() is ignored and view works well.

**Comment by xristosbarko** [comment]
Hey @qu3vipon. The `select_related` as the documentation says returns a QuerySet that will “follow” foreign-key relationships, selecting additional related-object data when it executes its query. The name field is not a foreign key, and thus, it breaks. If you want to get the name of the person you should do the following:

```
book = Book.objects.select_related("author")
print(book.name) # this will not hit the database again
```

If you want to get the object from the City model:

`book = Book.objects.select_related("author__hometown")`

Check the documantation for more information here:
[https://docs.djangoproject.com/en/3.0/ref/models/querysets/#select-related](https://docs.djangoproject.com/en/3.0/ref/models/querysets/#select-related)

**Comment by qu3vipon** [comment]
Thanks @xristosbarko. My question was why `Book.objects.selected_related('auther__name')` works without raising errors in DRF although `name` is not a foreign key.

**Comment by SafaAlfulaij** [comment]
How are you writing `Book.objects.selected_related('auther__name')`?
Can you provide a full minimal working example?

**Comment by qu3vipon** [comment]
Hey, @SafaAlfulaij. These two return same without any errors in views and even in Django shell.
`CompatFriend.objects.select_related('friend').values_list('id', flat=True)  # return <QuerySet [1]>`
`CompatFriend.objects.select_related('friend__name').values_list('id', flat=True)  # return <QuerySet [1]>`

**Comment by tomchristie** [comment]
Closing as stale
