### ISSUE TITLE
AnonRateThrottle need  authenticated

### ISSUE THREAD

**Issue by while-it** [encode/django-rest-framework#7618]
when chose AnonRateThrottle,the rest will report bug about AttributeError: 'NoneType' object has no attribute 'is_authenticated'
![image](https://user-images.githubusercontent.com/12811322/97376748-1f8a1b00-18f9-11eb-80aa-23a0f6621a17.png)
I think the  function (AnonRateThrottle) in throttiong.py should delete  is_authenticated check

**Comment by dalvtor** [comment]
How are you using this?

The exception shows that `request.user` is None

**Comment by while-it** [comment]
yes，i can catch the bug in rest-source，



发自我的iPhone


------------------ Original ------------------

**Comment by while-it** [comment]
set throtting about anoymous rate，the bug will appear，thank you



发自我的iPhone


------------------ Original ------------------

**Comment by xordoquy** [comment]
@while-it do you have an example so we can reproduce ?
