### ISSUE TITLE
Test client POSTs unset booleans as False

### ISSUE THREAD

**Issue by amikrop** [encode/django-rest-framework#7620]
Let's say we have a model with a single field `foo = models.BooleanField(default=True)`. In a test case, calling `self.client.post(url)` (no `data` argument) incorrectly creates an instance with a `False` value of `foo` in the database. POSTing at the same url with an external tool, like httpie, without passing any POST data, correctly creates a db row with a `True` value of `foo`.

**Comment by xordoquy** [comment]
This issue is not actionnable in its current state.
Please note that there has been some similar issues most of them being an misunderstanding of how the boolean field works in HTML forms.
