### ISSUE TITLE
I need Multiple lines explain

### ISSUE THREAD

**Issue by jinji-hanbin** [encode/django-rest-framework#7637]
`class WalletWithdrawOrderDetailAPIView(generics.RetrieveAPIView):
    '''
    钱包提现记录详情
     - 返回值说明
     - status 状态 (0 提现发起 1提现成功 2提现失败)
     - order_no 提现单号
     - amount 金额
     - created 创建时间
     - pay_time 支付时间
     - payment_no 微信付款单号
     - mobile 提现人手机
    '''
    serializer_class = WalletWithdrawOrderDetailSerializer

    def get_object(self):
        obj = WithdrawOrder.obs.filter(user=self.request.user, id=self.kwargs['pk']).first()
        return obj`
![image](https://user-images.githubusercontent.com/18417846/99370732-045b6b80-28f9-11eb-9340-5dcd4036e47b.png)

**Comment by jinji-hanbin** [comment]
i need multiple explain

**Comment by tomchristie** [comment]
Hi there & thanks for your question.

The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions.

Thanks! 😀
