### ISSUE TITLE
handler500

### ISSUE THREAD

**Issue by marcstreeter** [encode/django-rest-framework#7651]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

I've been trying to get `handler500` to work with `@api_view` decorator.

## Steps to reproduce
Using: 
 - django 3.1.3
 - djangorestframework  3.12.2

populate file core/util/response.py

```
from rest_framework.decorators import api_view
from rest_framework.response import Response 

@api_view(["GET"])
def handler500(request):
    payload = {"message": "system error", "success": False, "data": None }
    return Response(data=payload, status=500, exception=True)
```
populate file app/urls.py
```
handler500 = "core.util.response.handler500"
```

and then starting Django with 

```
python manage.py runserver 0.0.0.0:8888
```

## Expected behavior

starts Django successfully (with handler500 able to be used)

## Actual behavior

Django crashes on start up with the following error

```
ERRORS:
?: (urls.E007) The custom handler500 view 'core.util.response.WrappedAPIView' does not take the correct number of arguments (request).

System check identified 1 issue (0 Silenced).
```

## Additional notes:
I am able to use the above with `handler404` without issue (and it works as expected), for `handler500` I have to use `django.http.HttpResponse` instead and not use the decorator.

**Comment by jerinpetergeorge** [comment]
Not sure why, but you can use `JsonResponse` to get the JSON response on HTTP 500

```
def handler500(request, *args, **kwargs):
    return JsonResponse({"foo": "bar"}, status=500)
```

**Comment by xordoquy** [comment]
As noted in the [Django documentation](https://docs.djangoproject.com/en/3.1/ref/urls/#django.conf.urls.handler500), `handler500` hass to return `HttpResponseServerError` so can't be a DRF view
