### ISSUE TITLE
Docs: DjangoModelPermissions do not require sentinel queryset.

### ISSUE THREAD

**Issue by alex-cots** [encode/django-rest-framework#7659]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Documentation Issue
The DjangoModelPermissions permissions class docs are out of date: [website](https://www.django-rest-framework.org/api-guide/permissions/#djangomodelpermissions) | [repo](https://github.com/encode/django-rest-framework/blob/master/docs/api-guide/permissions.md#djangomodelpermissions)
Specifically the subsection about views without a `queryset` attribute:
> If you're using this permission with a view that uses an overridden get_queryset() method there may not be a queryset attribute on the view. In this case we suggest also marking the view with a sentinel queryset, so that this class can determine the required permissions. 

Unless I'm misunderstanding, as of 3.1.2 this is no longer the case, as DjangoModelPermissions will check the `get_queryset()` method to determine the permissions. In fact, `get_queryset()` takes priority, meaning sentinel querysets will be ignored, so if they use a different model for `queryset` than `get_queryset()` method, that could lead developers to mistakenly believe that their view is protected by a certain model permission when it isn't.

I think that subsection can just be deleted. Additionally, one sentence at the top should be rephrased:

>This permission must only be applied to views that have a `.queryset` property set.

should become something like:

>This permission must only be applied to views that have a `.queryset` property or `get_queryset()` method.

[Relevant PR that changed DjangoModelPermissions](https://github.com/encode/django-rest-framework/pull/2863) 
[DjangoModelPermissions in current master branch](https://github.com/encode/django-rest-framework/blob/bb133522efaf6ce3ae8fdf1dec6cd79566cfd166/rest_framework/permissions.py#L162)

**Comment by xordoquy** [comment]
That's correct, want to go ahead and make that change ?
