### ISSUE TITLE
More details on View Schema Decorator - please

### ISSUE THREAD

**Issue by MkLHX** [encode/django-rest-framework#7664]
I open an issue because i break my brain and loose/waste to much time to manage using Schema Decorator in DRF.

I follow https://www.django-rest-framework.org/topics/documenting-your-api/ and manage it but on sagger-ui and redoc-ui.
But GET method query parameters or POST body json string payload aren't documented.

So i'm trying to deal with AutoSchema, ManualSchema and Custom classes to generate api documentation.
https://www.django-rest-framework.org/api-guide/views/#view-schema-decorator

But i never manage anything good. and yes i looking through [django-rest-framework] tag on stackoverflow too and yes i open a discussion on DRF google community (but no answers yet).

So what i tried.

Try to deal:
```
import coreapi
import coreschema
from rest_framework.schemas import AutoSchema, ManualSchema

log_file_delete_schema = AutoSchema(
    manual_fields=[
        coreapi.Field(
            "file_path",
            required=True,
            location="query",
            type="string",
            description="path of the log to be delete",
        )
    ]
)
```
But it returns "AutoShema as no get_operation" error

Try next:
```
import coreapi
import coreschema
from rest_framework.schemas import AutoSchema, ManualSchema

class CustomLogFileDeleteSchema(AutoSchema):
    def __init__(self):
        super(CustomLogFileDeleteSchema, self).__init__

    def get_manual_fields(self, path, method):
        extra_fields = [
            coreapi.Field(
                "file_path",
                required=True,
                location="query",
                description="log file path",
                type="string",
                example="/path/to/file/logfile.log",
            )
        ]
        manual_fields = super().get_manual_fields(path, method)
        return manual_fields + extra_fields
```
It returns to me 'CustomLogFileDeleteSchema' object has no attribute 'instance_schemas'

I tried to use Django Rest Swagger but it's unmaintened project now so ==> next

I'm using function based views for non ORM api endpoint like this:
```
@api_view(["GET", "POST"])
# @schema(log_file_delete_schema)
#@schema(CustomLogFileDeleteSchema())
@permission_classes((permissions.AllowAny,))
def log_file_delete(request):
    """
    @brief
    Delete the current log file from the device
    @param file_path => this is the log file path to delete
    POST and GET requests only
    e.g. uri looks like <root>/logs/delete/?file_path=/var/log/gpk/core.log
    """
    api_logger.info("access to delete log view")
    method = request.method
    if "GET" == method:
        _arg_file_path = request.GET.get("file_path", None)
    if "POST" == method:
        body_unicode = request.body.decode("utf-8")
        body = json.loads(body_unicode)
        _arg_file_path = body["file_path"]
    if None is _arg_file_path or not _arg_file_path:
        return JsonResponse({"error": "file_path arg is missing or empty"}, status=400)
    try:
        os.remove(Path(_arg_file_path))
        open(_arg_file_path, "w")  # need recreate empty file after delete
        r = {"code": 202, "status_message": "job done! file deleted"}
    except Exception as e:
        r = {
            "code": 400,
            "status_message": "Ooops! there is an error when try to delete logs file %s, {}".format(
                e
            )
            % _arg_file_path,
        }
    return JsonResponse(r, status=r["code"])
```
The View Schema Decorator example is too light for me, i don't understand what i can do with CustomClass Based on AutoSchema.

Please provide just a better example in documentation about GET query and POST body payload doc in OpenAPI format to manage it un swagger-ui.

![image](https://user-images.githubusercontent.com/17542841/102241515-5b089500-3ef9-11eb-9071-94b16fcb53fa.png)

**Comment by carltongibson** [comment]
HI @MkLHX. 

The `coreapi` stuff is no longer supported at all. You're better off using the native OpenAPI support from the latest versions. That does OK out of the box (whilst the ever deeper edge cases OpenAPI need manual adjustment). I believe folks who aren't using that go for DRF-yasg, but I can't vouch for that.

**Comment by MkLHX** [comment]
Hi @carlfarrington, thanks for you for the reply.

I'm going to test DRF-yasg, it's so painfull to make well API documentation by using DRF.
We always need to use third party library with inconvenients (deprecated, not maintained, no support, bad documented etc...)

Id just change tastypie to DRF because the API documentation and now i have to experiment an other third party library.

If DRF can include this parts in the future it will be a great thing! Of course if i can help i do!

**Comment by carltongibson** [comment]
@MkLHX — The inbuilt stuff is OK, if it were me I'd use that (because whatever edges there are, it's more likely to move forward than the others) — I don't know the status of DRF-yasg — though I believe it's not dormant.

**Comment by MkLHX** [comment]
Yep DRF doc stuff is good but missing something about clear doc from FBV or i missed something.

**Comment by MkLHX** [comment]
Hello again!
Finally i found a solution by parsing docstring yaml formatted ▶ https://www.igeorgiev.eu/python/misc/python-django-rest-framework-openapi-documentation/

I wrote my own answer on stackoverflow
https://stackoverflow.com/questions/65309754/drf-function-based-view-custom-schema-decorator-for-query-parameters-in-swagger/65339808#65339808

I think this part is missing in DRF documentation. So i'm going to submit a PR about documentation for FBV with OpenAPI

**Comment by carltongibson** [comment]
Hey @MkLHX. Super yes, please do. The docs are always a work in progress l, so your experience is valuable! 

(Glad you got it working!)
