### ISSUE TITLE
format='json' has no effect in APITestCase.client.get()

### ISSUE THREAD

**Issue by pierremonico** [encode/django-rest-framework#7673]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.

## Steps to reproduce
Write a test:
```
from rest_framework.test import APITestCase

class DemoTests(APITestCase):
    def setUp(self):
        self.projects_url = f"/{settings.API_ROOT}/demos/"
        self.user = baker.make(User)
        self.client.force_authenticate(user=self.user)

    def test_can_only_see_projects_you_are_in(self):
        response = self.client.get(self.projects_url,  format="json")
```
Run tests with `./manage.py test`

## Expected behavior
`response.data` is a dictionary or list (deserialized from the raw JSON).

## Actual behavior
`response.data` is a list containing `OrderedDict` instances.

## Further comments
I set `format="json"` in the function call, but I actually have it in the settings already: `'TEST_REQUEST_DEFAULT_FORMAT': 'json'`. 

I also tried with the `content_type='application/json'` argument, but that didn't work either. 

Weirdly enough, `response.accepted_renderer` is a `rest_framework.renderers.JSONRenderer` instance.

I am confused by the documentation, which states that  "Methods which create a request body, such as post, put and patch, include a format argument". I guess that this excludes get requests, but this argument is used in a `get` call [in one of the examples](https://www.django-rest-framework.org/api-guide/testing/#example_1).

I tried reading through the source code, and the `get` method indeed seems implemented differently from the others (not having the `format` parameter in the signature), but I couldn't follow through all the abstraction layers. 

I am using `django==3.1.4` and `djangorestframework=3.12.2`.

Am I missing something here?

**Comment by xordoquy** [comment]
I don't get the issue. `OrderedDict` are comparable to dicts so everything should be work. Beside, others methods such as `POST` should return `OrderedDict` as well, don't they ?

**Comment by pierremonico** [comment]
That's correct, I somehow got confused. 

I still find the bit on documentation I mentioned confusing. Is that something you feel could be improved? Happy to contribute if so. Otherwise this issue can be closed. 

Merry Christmas.

**Comment by chris-erickson** [comment]
Did something change here recently?  We have a pretty large and old test base that has started failing in recent versions (possible it was related to the recent Django update?) because OrderedDicts don't `assert ==` using py.test when they're returned in a list like:

```python
[
    {'first': 'thing'}.
    {'second': 'thing'}
]
```
In our case, comparing this when it's full of OrderedDicts vs regular dict doesn't pass equality.  We use GET extensively to return data so I'm a bit confused why it wouldn't get similar treatment as a POST response?  Perhaps I'm just really misunderstanding what's going on, though.

**Comment by tomchristie** [comment]
@chris-erickson Not that I know of. Closing this given that...

> Is that something you feel could be improved? Happy to contribute if so. Otherwise this issue can be closed.
