### ISSUE TITLE
Pagination not enabled for view despite DEFAULT_PAGINATION_CLASS being set

### ISSUE THREAD

**Issue by paulschreiber** [encode/django-rest-framework#7676]
Per [pagination docs](https://www.django-rest-framework.org/api-guide/pagination/#modifying-the-pagination-style):
> Pagination is only performed automatically if you're using the generic views or viewsets

and per [viewset docs](https://www.django-rest-framework.org/api-guide/viewsets/):
>The `ModelViewSet` class inherits from `GenericAPIView`

I would expect pagination to be enabled for me by default:

## Steps to reproduce

1. Enable pagination in settings:
```
# Rest Framework
REST_FRAMEWORK = {
	'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
	'PAGE_SIZE': 10,
}
```

2. In `views.py` create a class like so:
```
class POViewSet(viewsets.ModelViewSet):
	queryset = PO.objects.all()
	serializer_class = POSerializer
	page_size = 10
	filter_backends = [filters.SearchFilter]
	search_fields = ['name_last', 'name_first', 'employee_id']
```

3. Register a route
```
router.register(r'pos', views.POViewSet)
```
4. Go to http://127.0.0.1:8000/api/pos/?format=json

## Expected behavior
10 results

## Actual behavior
full result set

## Workaround
Define this pagination class:
```
from rest_framework.pagination import PageNumberPagination

class StandardResultsSetPagination(PageNumberPagination):
	page_size = 10
	page_size_query_param = 'page_size'
	ordering = ['name_last', 'name_first', 'employee_id']
```

Add it to the view from step (2)
```
class POViewSet(viewsets.ModelViewSet):
	queryset = PO.objects.all()
	serializer_class = POSerializer
	page_size = 10
	filter_backends = [filters.SearchFilter]
	search_fields = ['name_last', 'name_first', 'employee_id']
	pagination_class = StandardResultsSetPagination
```

Then you get 10 results, as expected.

**Comment by xordoquy** [comment]
Could not reproduce with the [DRF tutorial](https://github.com/encode/rest-framework-tutorial) even with adding the `filter_backends` on the `snippet` view.

**Comment by paulschreiber** [comment]
@xordoquy any interest in debugging my app with me to understand what's causing this? I have a workaround, so it's not a blocker, but I'd like to understand what's going on here.

**Comment by xordoquy** [comment]
Unfortunately no time to investigate that.
