### ISSUE TITLE
No source distribution on PyPI

### ISSUE THREAD

**Issue by seppeljordan** [encode/django-rest-framework#7680]
## Checklist

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)

# Source release
Currently `djangorestframework` is lacking a source release on pypi.  This means that effectvily `djangorestframework` cannot be installed from source and neither can any packages that depend on `djangorestframework`.

**Comment by tomchristie** [comment]
How would I go about verifying which of our PyPI releases do or don't have an sdist, and confirming if we've had an unintentional change in our packaging?

**Comment by xordoquy** [comment]
It's likely an issue on my side. I remember twine complained I had older packages that he couldn't upload and stoped before uploading the source one.

**Comment by xordoquy** [comment]
And that should be fixed now. Sorry for the delay.

**Comment by tomchristie** [comment]
We could have a look at using GitHub actions to roll the releases sometime.
Working very nicely with other encode packages, and does a good job of keeping things consistent. OTOH there is some extra complexity with translations, so. (?)

**Comment by xordoquy** [comment]
We could still have the translation done manually and yet automate the other parts. Changelog is also manual. The release process can't be "just git tag" anyway.

**Comment by xordoquy** [comment]
Speaking of which, DRF needs to move out of travis.org which is mostly discontinued.
