### ISSUE TITLE
read_only=True and required=True should be allowed

### ISSUE THREAD

**Issue by rvinzent** [encode/django-rest-framework#7681]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

Add a field to a serializer with `read_only=True` and `required=True`.

## Expected behavior

It is possible to exclude a field from the serialization representation if `required=False` and the attribute is not present on the object being serialized. This feature is described [here](https://www.django-rest-framework.org/api-guide/fields/#required):

> Setting this to False also allows the object attribute or dictionary key to be omitted from output when serializing the instance. If the key is not present it will simply not be included in the output representation.

Why am I not allowed to mark this field as `required=True`? It's correct that it doesn't make sense to require a `read_only` field when _deserializing_, but when serializing the object I should still be able to indicate whether the field is required or not. This is currently impossible. I can't have DRF validate that the field is present because `required=True` is not allowed on a read only field.

 The values of `read_only` and `write_only` should take precedence over everything. Even if `read_only=True` and `required=True` it is still obvious to the programmer that the field is not required in the "write path" (deserialization). If someone adds these options together, it is unlikely to be a mistake.

This unnecessary assertion causes ambiguity in OpenAPI schema generators. It is possible to declare a field as `readOnly` and have it also appear in the `required` properties, but this is currently impossible to correctly introspect schema from DRF serializers because `read_only` fields are implicitly not `required` when this is unlikely to be the case.

> `readOnly`: Relevant only for Schema "properties" definitions. Declares the property as "read only". This means that it MAY be sent as part of a response but SHOULD NOT be sent as part of the request. If the property is marked as readOnly being true and is in the required list, the required will take effect on the response only. A property MUST NOT be marked as both readOnly and writeOnly being true. Default value is false.

## Actual behavior

`AssertionError` is raised when setting `read_only=True` and `required=True`, and there is a comment explaining that these options don't make sense with each other.

I understand this would technically be a breaking change because the implicit value of `required` would change from `False` to `True`(the global default) when setting `read_only=True`

**Comment by ramwin** [comment]
Would you give me a scenario in which you should set both `required=True` and `required=False`.

**Comment by rvinzent** [comment]
> Would you give me a realistic scenario in which you should set both `required=True` and `required=False`.

I have related objects to the base queryset that can be expensive to to lookup. A client can pass in query parameters to toggle showing the related objects. The fields are not writeable so `read_only=True`, and they may or may not be present based on the query parameters passed in so `required=False`. 

This is implicitly the default behavior already,   but now an OpenAPI schema generation tool cannot reliably tell whether a `read_only` field is required and they need to make a blanket assumption that either all read only fields are required (the most common use case, and the default kwargs), or that none of the read only fields are required (the actual behavior of the serializer). 

Neither assumption is always going to be correct.

**Comment by xordoquy** [comment]
`required` was initially designed as a write argument. It changed over time to also affect read operations though some cases may not be handled as you've noticed.
I still don't think `required` should be used for both read and write operation and would rather welcome two different flag to be more clear about what each flag affects.

**Comment by ramwin** [comment]
@rvinzent As @xordoquy said, I think `required=True` is used for write only. In your case, you should consider using [drf-flex-fields](https://github.com/rsinger86/drf-flex-fields). You can pass different query parameters to tell the server what fields you need.

**Comment by CelestialGuru** [comment]
I've just encountered a bug which this exposed. Say you have a model with some property you'd like to include on the serializer:
```python
# models.py
class SomeModel(models.Model):
   @property
   def some_property(self):
       return ...  # What if there's a bug? Like self.relationship.whoops_typo
```
and in your serializer:
```python
# serializers.py
class SomeModelSerialzier(serializers.ModelSerializer):
   class Meta:
      model = SomeModel
      fields = "__all__"
   some_property = serializers.FloatField(read_only=True)
```
if, unbeknownst to you, there's a bug in `some_property` which were to raise an error, the field is removed from the response body.

Where fields get removed:
```python
# rest_framework/serializers.py(500)to_representation():
def to_representation(self, instance):
   ...
   for field in fields:
      try:
         attribute = field.get_attribute(instance)
      except SkipField:
         continue  # Right here
```

why it was removed:
```python
# rest_framework/fields.py(440)get_attribute()
def get_attribute(self, instance):
   try:
      return get_attribute(instance, self.source_attrs)
   except (KeyKerror, AttributeError) as exc:
      ...
      if not self.required:
          raise SkipField()  # Original exception is lost :(
```

If only there was a way to say this `read_only` field were required 🤔?

**Comment by auvipy** [comment]
what benefit will that provide by not breaking any existing features?

**Comment by rvinzent** [comment]
> what benefit will that provide by not breaking any existing features?

It's pretty much impossible to enforce a read-only, required property in DRF. Is that not benefit enough?

**Comment by tomchristie** [comment]
> AssertionError is raised when setting read_only=True and required=True, and there is a comment explaining that these options don't make sense with each other.
