### ISSUE TITLE
blank=False in model not working while executing serializer.is_valid() while null=True

### ISSUE THREAD

**Issue by gotounix** [encode/django-rest-framework#7685]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

```
class Test(models.Model):
    field_1 = models.DecimalField('Field_1', max_digits=10, decimal_places=2, null=True, blank=False)
    field_2 = models.DateTimeField('Field_2', null=True, blank=False)


class TestSerializer(serializers.ModelSerializer):
    # field_1 = serializers.DateTimeField(required=True)
    # field_2 = serializers.DecimalField(required=True, max_digits=10, decimal_places=2)

    class Meta:
        model = Payment
        fields = ['field_1', 'field_2']

class TestViewSet(viewsets.ModelViewSet):
    queryset = Test.objects.all()
    serializer_class = TestSerializer

    @action(methods=['patch'], detail=True, url_name='test')
    def test(self, request, pk=None):
        test= get_object_or_404(Test, pk=pk)
        serializer = self.get_serializer(test, data=request.data, partial=True)

        if serializer.is_valid(raise_exception=True):  # Passed
            serializer.save()
            return Response(status=status.HTTP_200_OK)
```

## Expected behavior && Actual behavior

``serializer.is_valid()`` return ``True`` while ``field_1`` and ``field_2`` is ``None``, I think it shoud be ``False``.

But while removing ``null=True`` or adding field in ``TestSerializer`` will be working OK.

**Comment by CosmicReindeer** [comment]
I recommend you check [this](https://stackoverflow.com/questions/8609192/what-is-the-difference-between-null-true-and-blank-true-in-django) answer. It differentiates between the null and blank constructors well.

> null=True sets NULL (versus NOT NULL) on the column in your DB. Blank values for Django field types such as DateTimeField or ForeignKey will be stored as NULL in the DB.
blank determines whether the field will be required in forms. This includes the admin and your custom forms. If blank=True then the field will not be required, whereas if it's False the field cannot be blank.

**Comment by xordoquy** [comment]
`null=True` on the model has the effect of allowing a field set to None to be valid.
