### ISSUE TITLE
Changing "results" key in paginated response causes the Browsable API to no longer render the "Filters" button

### ISSUE THREAD

**Issue by genomics-geek** [encode/django-rest-framework#7687]
When creating a custom Pagination class, I realized if I changed the key "results" in the paginated response, the Browsable API no longer rendered the "filters" button.  However, the filters still work and they show up in the core api schema - so not a big issue since everything still works.  It is just a behavior I noticed that seemed unexpected.

## Steps to reproduce

1. Create a custom PaginationClass

```python
class TestPagination(PageNumberPagination):
    def get_paginated_response(self, data):
        return Response(
            OrderedDict(
                [
                    ("count", self.page.paginator.count),
                    ("next", self.get_next_link()),
                    ("previous", self.get_previous_link()),
                    ("data", data),
                ]
            )
        )
```

Use this pagination class in a ViewSet:

```python
class TestViewSet(ReadOnlyModelViewSet):
    queryset = models.PipelineRun.objects.optimized_all().order_by("-pk")
    pagination_class = pagination.TestPagination
    search_fields = (
        "pipeline__pipeline_name",
    )
```

## Expected behavior

When visiting the browsable API, I would expect to still see the filter button and the HTML form to submit filters.

## Actual behavior

Browsable API no longer renders the filter button.

**Comment by kevin-brown** [comment]
I believe this has to do with the key for the results being changed but the `get_results()` method not being updated to match. By default it picks up the results using the `results` key, so if you change the key where results are returned but don't update that method, we have no way to know what results you have and if they are filterable.

**Comment by genomics-geek** [comment]
@kevin-brown - oh nice. I figured it was something I left out.  Thank you, that works.
