### ISSUE TITLE
Code attribute on  custom permission not working

### ISSUE THREAD

**Issue by julesxoxzo** [encode/django-rest-framework#7694]
According to the DRF docs on [Permissions](https://www.django-rest-framework.org/api-guide/permissions/#custom-permissions)

` Similarly, to change the code identifier associated with the exception, implement a code attribute directly on your custom permission - otherwise the default_code attribute from PermissionDenied will be used.`

## Steps to reproduce
Create custom permission class:
```
from rest_framework import permissions
from rest_framework import status

class MyCustomPermission(permissions.BasePermission):
    message = "My Custom Message"
    code = status.HTTP_401_UNAUTHORIZED

    def has_permission(self, request, view):
           ......

    def has_object_permission(self, request, view, obj):
           .......
```
## Expected behavior
When getting the result in my API client (postman), I should be getting code `401`.

## Actual behavior
But what I'm getting is still `403 Forbidden`

The custom message works tho, only the `code` is not being updated.

My workaround now is instead of returning a boolean a raise an exception instead.
i.e `raise NotAuthenticated(self.message, code=status.HTTP_401_UNAUTHORIZED)`

**Comment by xordoquy** [comment]
The documentation is not clear about what `code` means here. It refers to the exception's `code` which is different from the `status_code`: https://www.django-rest-framework.org/api-guide/exceptions/#apiexception.
Happy to review a PR to enhance the documentation.
