### ISSUE TITLE
Missing breaking change notice in 3.10.X release notes

### ISSUE THREAD

**Issue by Syntaf** [encode/django-rest-framework#7703]
While upgrading my team's DRF version from 3.9.X to 3.10.X, I noticed that the release notes did not list any breaking changes even though `detail_route` and `list_route` were removed as part of the deprecation notice in db37512a6e4fa5ba793b7e401d7014dfd0984995

To bring some visibility to this deprecation, I could open a PR updating the release-notes doc with this information. Is this something the DRF team would be receptive to?

Apologies in advance if this was not the right place to submit a documentation issue on.

**Comment by xordoquy** [comment]
That's the perfect place for it. Sorry we missed that change in the release note and feel free to open on PR about it.

**Comment by nathanglover** [comment]
PR for this: https://github.com/encode/django-rest-framework/pull/7716
