### ISSUE TITLE
ObtainAuthTokenView and custom default parsers

### ISSUE THREAD

**Issue by niccolomineo** [encode/django-rest-framework#7710]
## Steps to reproduce
- Add a custom default parser and / or renderer (I tested it with `djangorestframework-camel-case`'s)
- Write a custom view subclassing `ObtainAuthTokenView`

## Expected behavior
The custom view's `parsers` and `renderers` attributes should return the custom defined ones.

## Actual behavior
The hardcoded `parsers` and `renderers` are returned, instead.

**Comment by xordoquy** [comment]
You should get that result by overriding the view's `parser_classes` / `renderer_classes`. `parsers` / `renderers` are not hardcoded.

**Comment by niccolomineo** [comment]
Yes, I could, but that should be unnecessary, since I specified those renderers and parsers as default in the django settings.

**Comment by niccolomineo** [comment]
> ## Steps to reproduce
> * Add a custom default parser and / or renderer (I tested it with `djangorestframework-camel-case`'s) in Django settings
> * Write a custom view subclassing `ObtainAuthTokenView`
> 
> ## Expected behavior
> The custom view's parsers and renderers should be custom defined ones.
> 
> ## Actual behavior
> The hardcoded parsers and renderers have been set, instead.

**Comment by xordoquy** [comment]
It is mandatory because it is not a generic view and accepts only some specific content types on purpose.
