### ISSUE TITLE
DecimalField errors on serialization of `None`, even when `allow_null=True`

### ISSUE THREAD

**Issue by kerkeslager** [encode/django-rest-framework#7721]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Try to serialize `None` with a `DecimalField` where `allow_null = True`.

## Expected behavior
What to expect here is a bit subjective... I'm expecting `''` if `coerce_to_string=True`, otherwise `None`, but that's just my subjective opinion.

However, I think we can agree that the actual behavior isn't the expected behavior. :)

## Actual behavior
Throws `InvalidOperation: [<class 'decimal.ConversionSyntax'>]`

**Comment by kerkeslager** [comment]
I have a PR that demonstrates and fixes this issue according to my expectations of the behavior, but as I said, I'm open to changing it if there's disagreement on the expected behavior: https://github.com/encode/django-rest-framework/pull/7718

**Comment by tomchristie** [comment]
That's interesting. I wonder if it's linked to having been introduced in a particular Django version?

**Comment by kerkeslager** [comment]
I'm not sure. I found this at client who is running Django 2.2, but reproduced the issue on Django 3.1.7.
