### ISSUE TITLE
DateTimeField returns an aware datetime even with default_timezone=None

### ISSUE THREAD

**Issue by kovaacs** [encode/django-rest-framework#7725]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
```
class ExampleSerializer(serializers.Serializer):
    dt = serializers.DateTimeField(default_timezone=None)
```

## Expected behavior
https://github.com/encode/django-rest-framework/blob/d635bc9c71b6cf84d137a68610ae2e628f8b62b3/rest_framework/fields.py#L1166

therefore `serializer.validated_data.get('dt', None)` should return a naive datetime

## Actual behavior
`serializer.validated_data.get('dt', None)` returns an aware datetime

**Comment by xordoquy** [comment]
Most likely you have `USE_TZ` set and are confusing the init argument `default_timezone` with the actual `self.default_timezone()`.

Reminder from [the documentation](https://www.django-rest-framework.org/api-guide/fields/#datetimefield):
> default_timezone - A pytz.timezone representing the timezone. If not specified and the USE_TZ setting is enabled, this defaults to the current timezone. If USE_TZ is disabled, then datetime objects will be naive.
