### ISSUE TITLE
Can't access AllowAny view with bad JWT token

### ISSUE THREAD

**Issue by Carlosted** [encode/django-rest-framework#7736]
## Steps to reproduce
- JWT authentication with simplejwt,
- Send request to a view that has allowAny permission with bad JWT token

## Expected behavior

Can access the view even with a bad token

## Actual behavior

If you make a request without authorization header you can access the view but if you request with a bad token it returns HTTP 401 (unauthorized)

**Comment by tomchristie** [comment]
Honestly, the existing behaviour seems reasonable enough to me. It's at least more explicit.
