### ISSUE TITLE
JSONRenderer.render(serializer.data) not working

### ISSUE THREAD

**Issue by ibnshayed** [encode/django-rest-framework#7779]
json_data = JSONRenderer.render(serializer.data) not working; 

Error: TypeError at /student/1/
render() missing 1 required positional argument: 'data'

**Comment by carltongibson** [comment]
Sorry, this is a usage question not an issue report. I suggest you review the documentation for serializers to see the correct usage. 

The issue tracker is for bugs. Thanks.
