### ISSUE TITLE
Bypass Throttling based on source ip address  

### ISSUE THREAD

**Issue by paradiseisbeautiful** [encode/django-rest-framework#7813]
The Main Problem is the rate limit based on the source IP address 

Summary
A rate-limiting algorithm is used to check if the user session (or IP address) has to be limited based on the information in the session cache. In case a client made too many requests within a given time frame, HTTP servers can respond with status code 429: Too Many Requests. (Wikipedia)

I Would Like To Report A Vulnerability This vulnerability The Impact Is Bypass The Throttling in login or reset password area if the developer
use these classes

'rest_framework.throttling.AnonRateThrottle',
#     'rest_framework.throttling.UserRateThrottle',
#     'rest_framework.throttling.ScopedRateThrottle'
well be able to bypass by attackers if they are using and change the IP address every 5 requests this feature will bypass the Django throttling

steps to reproduce :
1-First You Need To install Tor to Used as Proxy
https://brezular.com/2020/01/02/how-to-configure-burpsuite-to-use-tor-as-proxy/
2- intercept The Reset Password(https://exampledjangoapp.com/reset-password) and in 2-factor-authentication OTP PIN the developer uses to prevent brute force the pin via throttling will be bypass also and everywhere will bypass also
3- send to intruder With Null Payload
4- configure Tor Proxy in burp suite in user options

the remediation
is to implement a strong token and validate in the backend if the token sent multiple time with different IPs should be given 404 or provide captcha
to used in reset password

References :
https://www.django-rest-framework.org/api-guide/throttling/
https://cheatsheetseries.owasp.org/cheatsheets/Multifactor_Authentication_Cheat_Sheet.html
https://cheatsheetseries.owasp.org/cheatsheets/Credential_Stuffing_Prevention_Cheat_Sheet.html

Impact
the attackers will be bypass any kind of throttling in a critical location like 2 Factor Authentication OTP pin Bruteforce in this case will bypass 2-factor authentication or reset password and more

**Comment by tomchristie** [comment]
Application-level throttling is not intended to be a security measure against DDOS or brute force attacks.

It looks like there's interesting work that could potentially be done in this area, but it'd likely need to start as a third party package.
