### ISSUE TITLE
Request does not raise UnsupportedMediaType exception

### ISSUE THREAD

**Issue by Feverfew** [encode/django-rest-framework#7818]
## Checklist
- [x] I have reduced the issue to the simplest possible case.

With the following view:
```python
@api_view(['POST'])
@parser_classes([JSONParser])
def my_view(request):
    request.data['change_me'] = 'MyValue'
```
By sending a request with `Content-Type: multipart/form-data` (with at least one key/value pair, if it's empty it still goes through but doesn't trip up weirdly enough) one will observe the following behaviour:
`AttributeError at $myViewsURL This QueryDict instance is immutable`

What surprises me is that as I've specified the use of only the `JSONParser`, I should expect `request.data` to be a `dict`. I've tried other content-types and they are correctly rejected before parsing, but this one goes through.

**Comment by tomchristie** [comment]
Guiding you kindly towards discussions... :)

<img width="743" alt="Screenshot 2021-03-10 at 09 22 38" src="https://user-images.githubusercontent.com/647359/110606647-4cd9b600-8182-11eb-91e2-43787a5f279e.png">

I'm not able to replicate this...

**urls.py**

```python
from django.urls import path
from rest_framework.decorators import api_view, parser_classes
from rest_framework.parsers import JSONParser


@api_view(['POST'])
@parser_classes([JSONParser])
def homepage(request):
    request.data['change_me'] = 'MyValue'


urlpatterns = [
    path('', homepage),
]
```

**client.py**:

```
import httpx

r = httpx.post("http://127.0.0.1:8000", data={"a":"b"})
print(r)
```

**shell**:

```
$ python client.py 
<Response [415 Unsupported Media Type]>
```
