### ISSUE TITLE
ListField return different default value

### ISSUE THREAD

**Issue by zhu** [encode/django-rest-framework#7829]
https://github.com/encode/django-rest-framework/blob/c05cbe2da213ae6fef5ea66dbafb050b76923117/rest_framework/fields.py#L1639-L1652

When `is_html_input`, `ListField` return `[]` as default.
It returns `empty` in other situations.

**Comment by tomchristie** [comment]
This issue does not meet our contribution guidelines.

<img width="785" alt="Screenshot 2021-03-10 at 12 07 55" src="https://user-images.githubusercontent.com/647359/110627038-64706900-8199-11eb-9eec-dfae9f8f04f5.png">
