### ISSUE TITLE
Support for Django 3.2 LTS

### ISSUE THREAD

**Issue by FinnGu** [encode/django-rest-framework#7941]
I probably missed it somewhere, but I cannot find an issue where support for the [new version of django](https://docs.djangoproject.com/en/3.2/releases/3.2/), released on 6.4.21, is tracked.

Has anyone successfully upgraded their project yet?

**Comment by carltongibson** [comment]
It all works, pending an update for django-guardian, which I'm not sure is yet compatible. See #7927 and CI runs there.
