### ISSUE TITLE
DRF-nest path parameter not support value contain dot

### ISSUE THREAD

**Issue by hcheng2002cn** [encode/django-rest-framework#7957]
When pk contain dot will cause NoReverseMatch exception. The reason is DRF routers.py:

```
def get_lookup_regex(self, viewset, lookup_prefix=''):
        """
        Given a viewset, return the portion of URL regex that is used
        to match against a single instance.

        Note that lookup_prefix is not used directly inside REST rest_framework
        itself, but is required in order to nicely support nested router
        implementations, such as drf-nested-routers.

        https://github.com/alanjds/drf-nested-routers
        """
        base_regex = '(?P<{lookup_prefix}{lookup_url_kwarg}>{lookup_value})'
        # Use `pk` as default field, unset set.  Default regex should not
        # consume `.json` style suffixes and should break at '/' boundaries.
        lookup_field = getattr(viewset, 'lookup_field', 'pk')
        lookup_url_kwarg = getattr(viewset, 'lookup_url_kwarg', None) or lookup_field
        lookup_value = getattr(viewset, 'lookup_value_regex', '[^/.]+')
        return base_regex.format(
            lookup_prefix=lookup_prefix,
            lookup_url_kwarg=lookup_url_kwarg,
            lookup_value=lookup_value
        )
```

 getattr(viewset, 'lookup_value_regex', '[^/.]+') won't accept any value contain '.'.

Anyway we can pass pk value contain dot as path parameter ?

Thanks
hong

## Checklist

- [ ] Raised initially as discussion #...
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.

**Comment by tomchristie** [comment]
Hiya Hong,

So, if you want to allow regex patterns *including* dots, you'll want to set a class attribute on your viewsets in order to allow this...

```python
class MyViewSet(...):
    ...

    lookup_value_regex = ".+"
```

**Comment by hcheng2002cn** [comment]
> Hiya Hong,
> 
> So, if you want to allow regex patterns _including_ dots, you'll want to set a class attribute on your viewsets in order to allow this...
> 
> ```python
> class MyViewSet(...):
>     ...
> 
>     lookup_value_regex = ".+"
> ```

@tomchristie thanks for help, appreciated !

**Comment by jiaulislam** [comment]
ayyy I was pulling my hair out for 2 days for this issue ! I'm really dumb
