### ISSUE TITLE
Bug: setting reverse OtO is not persisted

### ISSUE THREAD

**Issue by pierremonico** [encode/django-rest-framework#7994]
Hi 

I have an issue where I have two models `A` and `B`. `B` has a `OneToOne` field called `a` pointing to the `A` model, with `related_name` set to `b`. 

Whenever I create `A` objects through the API and set the JSON `b` field to the ID of an existing `B` object, I get a `201` response (with the `b` key correctly set in the response body), **but this relationship is actually not persisted in the database** .

[I have created a repo with a minimal implementation where this can be reproduced](https://github.com/pierremonico/drf-oto-bug). It also includes a failing test.

I believe following issues/MRs reference the same problem, but I can't tell for sure:
- #5996 
- [PR7554](https://github.com/encode/django-rest-framework/pull/7544)
- #7547

_Originally posted by @pierremonico in https://github.com/encode/django-rest-framework/discussions/7987_

**Comment by tomchristie** [comment]
Closing this in favour of the existing discussion ticket.
