### ISSUE TITLE
API tokens shouldn't be visible in the admin portal

### ISSUE THREAD

**Issue by valentijnscholten** [encode/django-rest-framework#8000]
**Problem**
I think the API tokens shouldn't visible in the `/admin` site by default. 
Currently any staff/superuser can see and use all the API tokens from all users;

**Solution**
option a) Hide the auth token field from the `TokenAdmin` model;
option b) Do not register the `Token` model to the `/admin` site by default;
option c) Don't store api tokens in plaintext, but hash them like passwords;
option d) ...

**Workaround**
As a workaround I have now removed the `Token` model completely from the `/admin` portal in my `models.py`:

```
from rest_framework.authtoken.admin import TokenAdmin
from rest_framework.authtoken.models import TokenProxy
admin.site.unregister(TokenProxy)
```

Relevant issues/prs: #5205

**Comment by coderanger** [comment]
As a bonus, the token ends up in the URL which means its in lots of access logs. If there is a detail view, the URL parameter shouldn't be the token itself.

**Comment by kevin-brown** [comment]
I thought the TokenAdmin makes it so the access token doesn't appear in logs, and instead it's just the matching user ID?

**Comment by coderanger** [comment]
I mean in the detail view of the token itself, `/admin/authtoken/token/ff8c[redacted]fca/change/`. And if you have server-level or proxy-level access logs, that URL would be in it now with the full token.

**Comment by coderanger** [comment]
Ahh I think I see that was changed in 3.12 and I just need to upgrade :)
