### ISSUE TITLE
has_object_permission not called when using function-based views

### ISSUE THREAD

**Issue by codyhatch** [encode/django-rest-framework#801]
I'm running into an issue with trying to use object permissions.  As per the [documentation](http://django-rest-framework.org/api-guide/permissions.html) I have the following code:

```
class IsOwnerPermission(permissions.BasePermission):
    def has_object_permission(self, request, view, obj):
        import pdb; pdb.set_trace()
        return obj.owner == request.user
```

Elsewhere I have the following code:

```
@api_view(['GET', 'PUT', 'PATCH', 'DELETE'])
@permission_classes((IsOwnerPermission, ))
def scene_detail(request, pk):
  # ......
```

has_object_permission() is never called, and digging through the source code it seems that the only way it gets called is if I'm using generic views.  Am I missing something?  Is there an easy-ish way to use object permissions with the function based api_view style code?  Is this a bug or by design?

**Comment by EngAhmedElkady** [comment]
Thank you for that, but when I used the viewset ok and tested the permission on the browser it worked, 
how does that happen?
does that in frontend the don't show the button only or what?
