### ISSUE TITLE
ApiException raise HttpResponse 500 ,however it is got `code` parameter in its constructor 

### ISSUE THREAD

**Issue by moghadas76** [encode/django-rest-framework#8030]
version: 3.10.3

ApiException raise HttpResponse 500 ,however it is got `code` parameter in its constructor

**Comment by saadmk11** [comment]
The initializer for `APIException` takes the value for `default_code` (e.g: `invalid`, `error`, `service_unavailable`) as keyword argument `code`, to set a different status code you need to subclass it and provide value for `status_code` in the subclass.

From the docs:
> To provide a custom exception, subclass `APIException` and set the `.status_code`, `.default_detail`, and `default_code` attributes on the class.

Ref: https://www.django-rest-framework.org/api-guide/exceptions/#apiexception
