### ISSUE TITLE
Schema Generator: "flattening" not taken into account

### ISSUE THREAD

**Issue by peterthomassen** [encode/django-rest-framework#8065]
Given the following serializers:

```python
class RRSerializer(serializers.ModelSerializer):

    class Meta:
        model = models.RR
        fields = ('content',)  # RR.content is a string (models.TextField)

    def to_internal_value(self, data):
        if not isinstance(data, str):
            raise serializers.ValidationError('Must be a string.', code='must-be-a-string')
        return super().to_internal_value({'content': data})

    def to_representation(self, instance):
        return instance.content


class RRsetSerializer(ConditionalExistenceModelSerializer):
    domain = serializers.SlugRelatedField(read_only=True, slug_field='name')
    records = RRSerializer(many=True)
```

`RRsetSerializer` outputs JSON objects like `{"domain": "example.com", "records": ["value1", "value2", ...]}`, with the `records` field being a list (JSON array) of strings.

When a schema is generated, it says that the `records` field is a list of objects, with a `content` field. The flattening done by `RRSerializer.to_representation` (and the inverse done by `.to_internal_value`) is not taken into account.

**Comment by hnykda** [comment]
Eh, just a random lurker here, but how do you think the schema generator could know? It doesn't somehow magically parse arbitrary python code. If you are overwriting to_internal_value/`to_representation`, you likely have to provide your own AutoSchema subclass (see the docs)
