### ISSUE TITLE
Make serializers.ValidationError compatible with Django ValidationError

### ISSUE THREAD

**Issue by dgasparri** [encode/django-rest-framework#8077]
Django Rest Framework ValidationError in rest_framework.exceptions has the following constructor:

    def __init__(self, detail=None, code=None)

Django original ValidationError in django.core.exceptions has the following constructor:

    def __init__(self, message, code=None, params=None)

The difference is subtle and obscure, especially for  a beginner that read the Django documentation on how to properly write a ValidationError exception https://docs.djangoproject.com/en/3.2/ref/forms/validation/#raising-validationerror
 . I spent an hour trying to figure out why Django "proper way" of writing a validation exception was  not working for me

**Comment by auvipy** [comment]
@Ehsan200 should we close this? or you have something more to work on this issue?

**Comment by Ehsan200** [comment]
@auvipy i think we're good; we can close this issue for now.
