### ISSUE TITLE
Openapi schema for PATCH has all fields required

### ISSUE THREAD

**Issue by mrginglymus** [encode/django-rest-framework#8103]
I have been using the openapi schema generated by DRF with [openapi-generator](https://github.com/OpenAPITools/openapi-generator) to generate a typescript api client.

Unfortunately, I can't use it for `PATCH` updates as the generated types show all fields required for the serializer - which they are for `PUT` and `POST`, but not for `PATCH`.

By way of example, and as a (horrible) workaround I'm using, I've created the following schema implementation:

```python
class PatchSchema(AutoSchema):

    @contextmanager
    def with_method_context(self, method):
        self._method = method
        yield
        self._method = None

    def get_request_body(self, path: str, method: str) -> Dict[str, Any]:
        with self.with_method_context(method):
            return super().get_request_body(path, method)

    def get_component_name(self, serializer: BaseSerializer) -> str:
        name = super().get_component_name(serializer)
        if self._method == 'PATCH':
            return f'Partial{name}'
        return name

    def get_components(self, path: str, method: str) -> Dict[str, Any]:
        with self.with_method_context(method):
            ctx = super().get_components(path, method)
            if method == 'PATCH':
                for props in ctx.values():
                    props['required'] = []
        return ctx
```

This generates a separate schema for the model being serialized for `PATCH` requests only that has no required fields.

I couldn't see any issues like this before, so I've raised this to check if this has come up before. I'd be willing to work on a slightly more robust solution if this acknowledged as an issue worth fixing.

**Comment by hnykda** [comment]
We have hit as well actually. :+1:
