### ISSUE TITLE
Union types and drf permission_classes 

### ISSUE THREAD

**Issue by ahaydarli** [encode/django-rest-framework#8104]
After the update, Pycharm shows permission_classes | as union type and gives an error like this.
Python version 3.7 does not allow writing union types as X | Y

my code block

![Screen Shot 2021-07-29 at 17 36 59](https://user-images.githubusercontent.com/5868653/127501732-584f3625-7581-41ce-a1ed-55fa07c55b5e.png)

**Comment by kevin-brown** [comment]
The only thing I'm seeing referencing this error is a PyCharm bug report at:

* https://youtrack.jetbrains.com/issue/PY-49982
* https://youtrack.jetbrains.com/issue/PY-49697

Which suggests they have a faulty implementation of PEP 604 type checking. As such, this appears to be out of scope for DRF.
