### ISSUE TITLE
DRF Errors Formatting Package

### ISSUE THREAD

**Issue by thomas545** [encode/django-rest-framework#8119]
Hello,
The current format gets invalid serializer errors, uses DRF standard for code and messaging, and then parses it to the following format:

```
    {
        "errors": [
            {
                "message": "Error message",
                "code": "Some code",
                "field": "field_name"
            },
            {
                "message": "Error message",
                "code": "Some code",
                "field": "nested.field_name"
            },
            ...
        ]
    }
```
I want to share and put the package in DRF third-party packages list to help them and save their time

Package link: https://github.com/thomas545/drf-errors-formatter

Cheers

**Comment by auvipy** [comment]
you should send a PR

**Comment by tomchristie** [comment]
Indeed you're very welcome to send a pull request adding it to the third party packages - that'd be great. If you need any help in how to do that let us know and we'll guide ya through it.
