### ISSUE TITLE
update_wrapper copies extra / unwanted attributes in the .as_view method of a Viewset

### ISSUE THREAD

**Issue by abbasidaniyal** [encode/django-rest-framework#8139]
The class based views were updated to manually copy only the required attributes from the `View` class. 

https://github.com/django/django/blob/main/django/views/generic/base.py#L73-L83

A similar approach can be followed in the `Viewset` mixin class.

https://github.com/encode/django-rest-framework/blob/c5d9144aef1144825942ddffe0a6af23102ef44a/rest_framework/viewsets.py#L128

More discussion about this [here](https://code.djangoproject.com/ticket/32260#comment:10)

I'd like to work on this issue if it is accepted!

**Comment by tomchristie** [comment]
I don't think this was sufficiently clear in describing the *issue*, rather than describing the *code*.

Closing it off as stale for now.
