### ISSUE TITLE
Tutorial 4 page refers to serializer meta class, but that meta class was never mentioned before

### ISSUE THREAD

**Issue by jbrendel** [encode/django-rest-framework#815]
On the page "Tutorial 4: Authentication & Permissions" in the "Updating our serializer" chapter: Right after instructing the student to add an "owner" field to the serializer, it says:

```
Note: Make sure you also add 'owner', to the list of fields in the inner Meta class.
```

However, in the previous tutorial pages, a meta class for the serializer was never defined and the code for the serializer on the 1st page of the tutorial does not contain a meta class either.

I assume that this meta class here should be added to the serializer (and explained) on the 1st tutorial page:

```
class Meta:
    model = Snippet
    fields = ('pk', 'title', 'code', 'linenos', 'language', 'style')
```

Then, on page 4, we can say that the 'owner' field should be added "to the Serializer's meta class".

**Comment by lelandlam** [comment]
I am new to this and I am also stuck at the same section on page 4.  I do not know where to add 'owner', to the list of fields in the inner Meta class.  The link you provide has a 404 error.  Thanks

**Comment by jpadilla** [comment]
@lelandlam this is the correct [link](http://www.django-rest-framework.org/tutorial/1-serialization/#using-modelserializers).

```python
class SnippetSerializer(serializers.ModelSerializer):
    class Meta:  # This is the inner Meta class
        model = Snippet
        fields = ('id', 'title', 'code', 'linenos', 'language', 'style')
```

**Comment by lelandlam** [comment]
Thanks for the quick reply.  I added users to fields but am getting this error in the browser "ImproperlyConfigured at /snippets/    Field name `owner` is not valid for model `Snippet`."  I went through everything again up to section 4 and I don't think I missed anything.

```
class SnippetSerializer(serializers.ModelSerializer):
    class Meta:
        model = Snippet
        fields = ('id', 'title', 'code', 'linenos', 'language', 'style', 'owner')
        owner = serializers.ReadOnlyField(source='owner.username')
```

**Comment by Jokz6** [comment]
Thanks Ielandlam, 

Spent 2 hours trying to figure out why I was getting a "NotImplementedError: Field.to_internal_value() must be implemented." error, it's because I put the owner = ... in above the meta class
