### ISSUE TITLE
Paginators repeat the query

### ISSUE THREAD

**Issue by farid-hussain-qbatch** [encode/django-rest-framework#8209]
## Checklist

- [x] Raised initially as discussion #...
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.

<img width="1439" alt="Screenshot 2021-10-15 at 1 16 33 PM" src="https://user-images.githubusercontent.com/87980789/137455302-f30de63b-c015-47f2-88ab-88a7da8949a6.png">

It is repeating the same query two time .
1. First time without pagination limit
2. Second time with pagination limit

I am implementing this query:
Product.objects.filter(account__in=account_ids)

It should implement just a single query with pagination limit.

**Comment by tomchristie** [comment]
I'd be happy to consider this as an issue if anyone wants to dig more and can point more precisely to an issue here.
I realise that might sound a bit abrupt, but I need clearer identification of an issue before putting my time in.

I'd normally be up for this kind of issue, but it's such a core bit of the framework and has been the same way for quite a long time now, with quite a lot of eyeballs on it. I think if there was an obvious and obviously addressable issue here, I'd normally have expected it to have already been raised (and seconded), so I have a relatively high threshold for "okay show me the issue" before wanting to commit time to it.
