### ISSUE TITLE
License type is not set under project

### ISSUE THREAD

**Issue by rimvislt** [encode/django-rest-framework#8235]
Hi team, can use this project with custom license without knowing in which category it fall under for business usage. Can you select appropriate license type for this project to be able to see if it is under Mit, GPL etc..

At the moment it is not clear if it can be used for commercial purpose.

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#disclaimer

**Comment by tomchristie** [comment]
It's here in our docs... https://www.django-rest-framework.org/#license and here in our repo... https://github.com/encode/django-rest-framework/blob/master/LICENSE.md

**Comment by rimvislt** [comment]
This does not tell under which legal category this license go to ->  MIT, GPL etc..  you can read about license categories here: [](https://opensource.org/licenses/category )

I was hoping to get answer about category not were license are located. 

Without correct category license can not be used or required custom investigation by lawyer to be able to use this code. I am not sure if this is done on purpose for this project or because that someone did not understand categories and did not specify it.

**Comment by discover59** [comment]
@rimvislt I think it's BSD-3.

https://github.com/encode/django-rest-framework/blob/master/rest_framework/__init__.py#L13
