### ISSUE TITLE
Tutorial:  'DELETE' and 'PUT' actions still appear on Browsable API without permission

### ISSUE THREAD

**Issue by jsummerfield** [encode/django-rest-framework#825]
Hi,

Just working through the tutorial, and can't seem to reproduce this section: https://github.com/tomchristie/django-rest-framework/blob/master/docs/tutorial/4-authentication-and-permissions.md#object-level-permissions

"Now, if you open a browser again, you find that the 'DELETE' and 'PUT' actions only appear on a snippet instance endpoint if you're logged in as the same user that created the code snippet."

The UI shows the actions, however when clicking you do get a 403 / "You do not have permission to perform this action." message.

Highly likely I've missed something!

Thanks very much,

James

$ pip freeze
Django==1.5.1
Pygments==1.6
djangorestframework==2.3.2
wsgiref==0.1.2

**Comment by xordoquy** [comment]
@lonewolf911 the browsable API also checks the permissions before displaying the DELETE / PUT buttons. The OPTIONS will tell you DELETE / PUT are possible (ie you won't get a 405) but won't tell if you have the permission to not (403).

**Comment by lonewolf911** [comment]
@xordoquy Thank you for your reply, actually because I used FBV to test, so the browsable API still can DELETE/PUT without permission, I have to change it to CBV to run .check_obj_permission.
