### ISSUE TITLE
BrowsableAPIRenderer.get_raw_data_form should exclude read-only fields, too

### ISSUE THREAD

**Issue by pbav** [encode/django-rest-framework#8250]
renderers.py:
```python
    # strip HiddenField from output
    data = serializer.data.copy()
    for name, field in serializer.fields.items():
        if isinstance(field, serializers.HiddenField):  # <--- or field.read_only
            data.pop(name, None)

```

**Comment by pbav** [comment]
@tomchristie - closed why?

**Comment by tomchristie** [comment]
Okay, so this issue could do with being driven from a user-perspective, rather than "change this bit of code here".

If you can show a screenshot of "Here's what the Browsable API looks like, in situation X, here's how I'd expect it to behave differently" then that'd be a much better starting point for an issue.

**Comment by pbav** [comment]
It's all about read-only fields that appear in POST/PUT/PATCH forms while you can't really change them.

To be specific, let's consider an example: Products organized by Category. A product has a name, a price and a tax. Let's say  the tax is not a product property, but depends on a category.

Browsable API page for a product could look like this:
`GET /api/products/123`

```jsonc
{
  "id": 123,
  "category_id": 10,
  "name": "Laptop",
  "price": "999.00",
  "tax": "89.00"  // read-only `category.tax`
}
```

In the PUT/PATCH form below, we will have the same object, including the tax field. The form looks misleading as if we can change this field.

Moreover, if we add something like UnknownFieldsMixin for ProductViewSet, which raises ValidationError for unknown and read-only fields, it becomes a hassle for the user: they need to remove read-only fields every time they update something in the Browsable API.

Normally customizations like this can be easily done by overriding some method in a subclass.
However in this particular case I had to copy the whole `get_raw_data_form` implementation with only that small tweak to workaround this.
```python
class CustomBrowsableAPIRenderer(BrowsableAPIRenderer):
    # This function is copied and patched to exclude read-only fields from BrowsableAPIRenderer forms.
    # See https://github.com/encode/django-rest-framework/issues/8250
    def get_raw_data_form(self, data, view, method, request):
        ...
```
