### ISSUE TITLE
3.13.0 Broke API Docs

### ISSUE THREAD

**Issue by brianwawok** [encode/django-rest-framework#8298]
DRF 3.12.4 = API Docs are great
DRF 3.13.0 = API docs are flawed.

A very simple title and body such as:
https://www.django-rest-framework.org/topics/documenting-your-api/#setting-the-title

` def some_api_method(request)   
  """
    Test

    ### Example request:
        {
          'bacon': 'yes
        }
    """`

The title and example both fail to render

**Comment by tomchristie** [comment]
Should be fixed by 3.13.1 - See #8297
