### ISSUE TITLE
ReturnDict fails with union operator (PEP 584)

### ISSUE THREAD

**Issue by spookylukey** [encode/django-rest-framework#8301]
Simplest case. Under Python 3.9:

```python
>>> from rest_framework.serializers import Serializer
>>> Serializer().data | {}
```

Expected output:
```python
{}
```

Actual behaviour:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/luke/devel/django-rest-framework/rest_framework/utils/serializer_helpers.py", line 17, in __init__
    self.serializer = kwargs.pop('serializer')
KeyError: 'serializer'
```

I will provide a PR soon.

## Checklist

- [ ] I did not raise a discussion, as this is obviously a bug
- [X] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [X] I have reduced the issue to the simplest possible case.

**Comment by tomchristie** [comment]
Closed via 8302
