### ISSUE TITLE
Can not use plus(+) symbol in url

### ISSUE THREAD

**Issue by HendricksRichard** [encode/django-rest-framework#8312]
I create a query language and pass this syntax to backend like this:
`filter=elemtnts=+C,Li|O AND nelements>3
`
and I get parameter with
` request.query_params.get('filter', None)`

but I can get correct + symbol, because DRF use + to replace space symbol in url.
So how can I use + symbol in url!
thank you!

**Comment by EduardoJM** [comment]
You must encode/decode the URL characters, se this at w3c:

https://www.w3schools.com/tags/ref_urlencode.ASP

And see it at urllib:
https://docs.python.org/3/library/urllib.parse.html#urllib.parse.quote
https://docs.python.org/3/library/urllib.parse.html#urllib.parse.unquote
