### ISSUE TITLE
Pagination OpenAPI schemas should mark fields as required

### ISSUE THREAD

**Issue by rvinzent** [encode/django-rest-framework#8337]
## Checklist

- [ ] Raised initially as discussion #...
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.

### Description

The schema for paginated responses should mark fields as `required` as there are no cases where an Ok response omits any of the fields. They are correctly marked `nullable: true`, but they should also be set to `required`. This causes OpenAPI client generators to generate nullable properties for `count` and `results` on the `LimitOffsetPagination` response.

[Example](https://github.com/encode/django-rest-framework/blob/master/rest_framework/pagination.py#L405-L429) of schema without `required` fields. The OpenAPI schema for these paginators should set fields to be `required` so clients can assume they are always present to match the actual behavior of paginated responses.

**Comment by rvinzent** [comment]
Is there any chance this ticket will ever be addressed?

**Comment by auvipy** [comment]
if anyone contribute, then might be yes, but if not, DRF now suggest using [drf-spectacular ](https://drf-spectacular.readthedocs.io/en/latest/) as default schema tool
