### ISSUE TITLE
Field labels not processed in Serializer.to_representation()

### ISSUE THREAD

**Issue by lueho** [encode/django-rest-framework#8339]
Serializer fields take the keyword _label_ and the corresponding text in the API guide it says: 

> "A short text string that may be used as the name of the field in HTML form fields or other descriptive elements.". 

From this I would also expect that given labels are reflected in the output dictionary. However, a look in the function Serializer.to_representation() reveals that the dictionary keys are taken from the _field_name_ attribute. Is there a reason why the _label_ attribute is not considered in the representation? And if so, what is the point of setting field labels in the first place?

**Comment by tomchristie** [comment]
> if so, what is the point of setting field labels in the first place

They're used in HTML form fields in the browsable API.
