### ISSUE TITLE
Create the best 

### ISSUE THREAD

**Issue by Nimesh989851** [encode/django-rest-framework#8383]
## Checklist

- [ ] Raised initially as discussion #...
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [ ] I have reduced the issue to the simplest possible case.

**Comment by tomchristie** [comment]
I've blocked this user as (it is/they are) showing similar behaviours as a spam account.

**Comment by tomchristie** [comment]
For any on-lookers - I'll tend to do this sort of thing proactively, since it's more likely to give GitHub a good shot at booting off spammy accounts.

If I'm wrong, well get in contact, and try not to waste folks' time like this in the future.
