### ISSUE TITLE
If a property throws AttributeError/KeyError, error is caught and field is omitted

### ISSUE THREAD

**Issue by Kangaroux** [encode/django-rest-framework#8385]
## Checklist

- [X] Raised initially as discussion #7745
- [X] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [X] I have reduced the issue to the simplest possible case.

## Issue

Consider a Django model which contains a property, and that property could throw an `AttributeError` or `KeyError`.

When serializing the model, if the property throws either error, the error is silently caught. Additionally, the field is NOT included in the serialized data.

```python
class SomeModel(models.Model):
  # ...

  @property
  def some_prop(self):
    print("one")
    raise AttributeError("foo")
    print("two")
```

This prints `one`, no error traceback, and `some_prop` is not included in the serialized data.

## Expected

The exception should be raised and the serializer should return a 500.

If you change the type from `AttributeError` to `Exception` (or any other error type) it works as expected.

**Comment by tomchristie** [comment]
The thing that's preventing any progress here is that we don't have any proposal for how the behaviour should be different.
We *do* want to ignore attributes (or keys) that don't exist, but we *can't* distinguish those error cases from "An attribute/key error was thrown from within the property itself".

For now I'm going to close this, but will happily reopen if there's a workable proposal for an improvement here.

**Comment by Kangaroux** [comment]
@tomchristie Is using `hasattr` not an option?

**Comment by tomchristie** [comment]
I don't *think* that'd change anything, no... https://hynek.me/articles/hasattr/

**Comment by Kangaroux** [comment]
@tomchristie Interesting, good to know. One other thing that comes to mind is that you can check if the attr key exists in `dir(obj)`.

```python
class Foo:
  @property
  def a(self):
    raise Exception("bad")
 
f = Foo()


hasattr(f, "a")
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
#   File "<stdin>", line 4, in a
# Exception: bad


print("a" in dir(f))
# True
```

**Comment by tomchristie** [comment]
> Isn't `required` relevant for deserializing and validating only?

That *would* make more sense to me as well, tho... history.

I don't disagree with you here, tho we're a long way into this particular project lifespan and I would expect a change here to be significant disruptive, and lacking sufficient upside to justify the change.

**Comment by foucdeg** [comment]
fair enough, maybe something to consider for the next major version?
