### ISSUE TITLE
CursorPagination Documentation Invalid Link

### ISSUE THREAD

**Issue by mkmoisen** [encode/django-rest-framework#8401]
The link provided by the CursorPagination documentation regarding the implementation is no longer working:

```
class CursorPagination(BasePagination):
    """
    The cursor pagination implementation is necessarily complex.
    For an overview of the position/offset style we use, see this post:
    https://cra.mr/2011/03/08/building-cursors-for-the-disqus-api
    """
```

This https://cra.mr/2011/03/08/building-cursors-for-the-disqus-api link results in a 404 now.

![image](https://user-images.githubusercontent.com/2534631/157367419-aaf22d9b-2e4a-43e4-9922-2bf9cc936b6b.png)

**Comment by kevin-brown** [comment]
Looks like within the past 6 months, all of the older blog posts got archived and taken down.

Here's the Web Archive link: https://web.archive.org/web/20210812082751/https://cra.mr/2011/03/08/building-cursors-for-the-disqus-api/

**Comment by weslord** [comment]
I reached out to the blog author, and (despite the archiving) this doesn't seem to be intentional.

His response:
> for some reason i thought i restored that one [...]

> Trying to figure out what GH did with domains, but post is here:
> https://dcramer.github.io/2011/03/08/building-cursors-for-the-disqus-api/

**Comment by mkmoisen** [comment]
Should the Django documentation be updated to this new link, or are we waiting for the Author to restore the original link?

**Comment by weslord** [comment]
There's also a broken link on his homepage, so I expect he'll sort this out eventually. Looks like he's at the mercy of a weird GitHub bug https://twitter.com/zeeg/status/1502747983154069507.

(I mention this only for info. I have no opinion on changing the link.)

**Comment by weslord** [comment]
Looks like the post is back online at the original URL now

**Comment by mkmoisen** [comment]
@weslord Sounds good, thanks.
