### ISSUE TITLE
Missing is_dst option to be set to True/False on DateTimeField at make_aware

### ISSUE THREAD

**Issue by tabaktoni** [encode/django-rest-framework#8413]
https://github.com/encode/django-rest-framework/blob/380ac8e79dd85e6798eb00a730b7d4c4c4a86ebd/rest_framework/fields.py#L1189

implemented here:
https://github.com/django/django/commit/143255c8bbefe03ff755d7859f029f0bc7a552aa

**Comment by tomchristie** [comment]
Looks like we can just leave it as None.
