### ISSUE TITLE
Unknown tag on redered schema when using Django's SafeString as help_text

### ISSUE THREAD

**Issue by hashlash** [encode/django-rest-framework#8428]
### Discussed in https://github.com/encode/django-rest-framework/discussions/8402

Since:

- there's no response from the discussion thread,
- I think this is a valid issue, and
- I've found a possibly proper solution

I'll just put this as an issue and create a PR.

<div type='discussions-op-text'>

<sup>Originally posted by **hashlash** March 11, 2022</sup>
## The Issue

I have a model with SafeString as its help_text (inspired from [Django's password validation help text](https://github.com/django/django/blob/d90e34c61b27fba2527834806639eebbcfab9631/django/contrib/auth/password_validation.py#L84-L93)):

```py
from django.db import models
from django.utils.html import format_html, format_html_join


def list_help_text_html(help_texts):
    help_items = format_html_join(
        "", "<li>{}</li>", ((help_text,) for help_text in help_texts)
    )
    return format_html("<ul>{}</ul>", help_items) if help_items else ""


class ExampleModel(models.Model):
    field = models.TextField(
        help_text=list_help_text_html([
            'info a',
            'info b',
        ]),
    )
```

I followed the DRF's doc about [Generating a dynamic schema with SchemaView](https://www.django-rest-framework.org/api-guide/schemas/#generating-a-dynamic-schema-with-schemaview) and [A minimal example with Swagger UI](https://www.django-rest-framework.org/topics/documenting-your-api/#a-minimal-example-with-swagger-ui), but the Swagger UI fails to render the generated schema.

```
Parser error on line 59
unknown tag !<tag:yaml.org,2002:python/object/new:django.utils.safestring.SafeString>
```

The generated schema ([full version](https://gist.github.com/hashlash/b7bc1b91b42625c6ac5ce7344299d8c7)):

```yaml
openapi: 3.0.2
info:
  # redacted
paths:
  # redacted
components:
  schemas:
    Example:
      type: object
      properties:
        id:
          # redacted
        field:
          type: string
          description: !!python/object/new:django.utils.safestring.SafeString
          - <ul><li>info a</li><li>info b</li></ul>
      required:
      - field
```

Here's [a repo](https://github.com/hashlash/django-demo/tree/drf/safestring-schema/bug) for demonstrating the bug. The Swagger UI can be accessed on `/swagger-ui/`.

Package versions:

```
django==3.2.12
djangorestframework==3.13.1
pyyaml==6.0
uritemplate==4.1.1
```

## Findings

I found that the schema generation for the help_text lies on:

https://github.com/encode/django-rest-framework/blob/a53e523f939332189b4ba8db7f99758b7d63e59b/rest_framework/schemas/openapi.py#L289-L290

and:

https://github.com/encode/django-rest-framework/blob/a53e523f939332189b4ba8db7f99758b7d63e59b/rest_framework/schemas/openapi.py#L537-L538

But since `SafeString` is a subclass of `str` and it override the `__str__()` method to return itself, those DRF's method will still return a `SafeString` object.

```py
class SafeString(str, SafeData):
    ...

    def __str__(self):
        return self
```

## Workaround

I've with 3 possible workarounds, and so far I think the third is the best:

- Adding the `SafeString` with an empty string ([implementation](https://github.com/hashlash/django-rest-framework/tree/str-add-fix), [demo](https://github.com/hashlash/django-demo/tree/drf/safestring-schema/str-add-fix))

  ```
  >>> from django.utils.safestring import SafeString
  >>> s = SafeString('abc')
  >>> s + ''
  'abc'
  >>> type(s + '')
  <class 'str'>
  ```

- Use `str.__str__()` ([implementation](https://github.com/hashlash/django-rest-framework/tree/str-str-fix), [demo](https://github.com/hashlash/django-demo/tree/drf/safestring-schema/str-str-fix))

  ```
  >>> from django.utils.safestring import SafeString
  >>> s = SafeString('abc')
  >>> str.__str__(s)
  'abc'
  >>> type(str.__str__(s))
  <class 'str'>
  ```

- Use `represent_str()` to represent `SafeString` as `str` ([implementation](https://github.com/hashlash/django-rest-framework/tree/yaml-representer-fix), [demo](https://github.com/hashlash/django-demo/tree/drf/safestring-schema/yaml-representation-fix))

  ```py
  class OpenAPIRenderer(BaseRenderer):
      ...
      def render(self, data, media_type=None, renderer_context=None):
          class Dumper(yaml.Dumper):
              ...
          Dumper.add_representer(SafeString, Dumper.represent_str)
          return yaml.dump(data, default_flow_style=False, sort_keys=False, Dumper=Dumper).encode('utf-8')
  ```

PS: I also asked about the "string conversion"  on [Django's forum](https://forum.djangoproject.com/t/convert-safestring-to-str/12549).</div>

**Comment by youngbob** [comment]
I ran into the same issue, but with the description text for a custom filter. This breaks standard OpenAPI tools (I would assume any YAML parser that is not Python and doesn't have the SafeString class available).

**Comment by hashlash** [comment]
Haven't checked yet for the latest commit. Will do around around next 3 weeks

**Comment by auvipy** [comment]
> I ran into the same issue, but with the description text for a custom filter. This breaks standard OpenAPI tools (I would assume any YAML parser that is not Python and doesn't have the SafeString class available).

so is the issue valid one? I am confused, can you elaborate please? also the issue also has an open PR

**Comment by hashlash** [comment]
@auvipy 

> so is the issue valid one?

Yes, you could try it on https://github.com/hashlash/django-demo/tree/drf/safestring-schema/bug and access the `/swagger-ui/` endpoint which will show you the error
![image](https://user-images.githubusercontent.com/23237214/203559655-d1ce0ac5-e392-4925-8d33-b01c2289f6eb.png)

This is because DRF will render SafeString as `!!python/object/new:django.utils.safestring.SafeString`, which couldn't be parsed by Swagger (or other standard OpenAPI tools). The problematic schema contains something like this:

```yamlcomponents:
  schemas:
    Example:
      ...
      properties:
        ...
        field:
          type: string
          description: !!python/object/new:django.utils.safestring.SafeString
          - <ul><li>info a</li><li>info b</li></ul>
```

**Comment by hashlash** [comment]
> Haven't checked yet for the latest commit. Will do around around next 3 weeks

Sorry for not confirming it sooner. I've checked that the bug still exists on DRF 3.14.0

**Comment by auvipy** [comment]
ok
