### ISSUE TITLE
"CSRF Failed: CSRF cookie not set." error

### ISSUE THREAD

**Issue by naissa12** [encode/django-rest-framework#845]
I am using the django rest framework to perform API calls via IOS
and I get the following error
"CSRF Failed: CSRF cookie not set."

Here's my django API code:

```
class LoginView(APIView):
    """
    List all snippets, or create a new snippet.
    """
    @csrf_exempt
    def get(self, request, format=None):
        startups = Startup.objects.all()
        serializer = StartupSerializer(startups, many=True)
        return Response(serializer.data)

    @csrf_exempt
    def post(self, request, format=None):
        profile = request.POST
```

   ....

What can I do?

**Comment by MirzaBaig715** [comment]
I had the same error but then i just add the _class_name.as_view()_ and it works fine ! Perhaps that would be the issue.

**Comment by muhalitas** [comment]
> You need to decorate the `dispatch` method on the class with a [`method_decorator`](https://docs.djangoproject.com/en/1.5/topics/class-based-views/intro/#decorating-the-class) or decorate the [URLconf](https://docs.djangoproject.com/en/1.5/topics/class-based-views/intro/#decorating-in-urlconf). e.g.
> 
> ```python
>     @method_decorator(csrf_exempt)
>     def dispatch(self, *args, **kwargs):
>         return super(LoginView, self).dispatch(*args, **kwargs)
> ```

this disables the csrf protection.

**Comment by xordoquy** [comment]
Except that doesn't apply for DRF as the views are already csrf exempted but the CSRF protection is enforced by the session auth, no matter how you decorate the view.

**Comment by AbhishekDeshpande02** [comment]
Hey ! I had the same error I solved it using @apiview decorator of the rest_framework 
from rest_framework.decorators import api_view, renderer_classes
@api_view(['POST'])
@csrf_exempt
@ensure_csrf_cookie

**Comment by AbhishekDeshpande02** [comment]
Hey ! I had the same error I solved it using @apiview decorator of the rest_framework
from rest_framework.decorators import api_view, renderer_classes
@api_view(['POST'])
@csrf_exempt
@ensure_csrf_cookie
