### ISSUE TITLE
Easier access to query_params, data and POST in Field class and subclasses

### ISSUE THREAD

**Issue by LLyaudet** [encode/django-rest-framework#8457]
### Discussed in https://github.com/encode/django-rest-framework/discussions/8386

<div type='discussions-op-text'>

<sup>Originally posted by **LLyaudet** March  3, 2022</sup>
Hello,
I have a very simple feature request: 
create the following 3 helper methods in class Field:

```
def get_request_query_params(self):
    request = self.context.get('request', None)
    if request is None:
         return {}
    return request.query_params

def get_request_data(self):
    request = self.context.get('request', None)
    if request is None:
         return {}
    return request.data

def get_request_POST(self):
    request = self.context.get('request', None)
    if request is None:
         return {}
    return request.POST
```

and maybe also these 3 methods : 
```
def get_one_request_query_param(self, key, default=None):
    return self.get_request_query_params.get(key, default=default)

def get_one_request_query_datum(self, key, default=None):
    return self.get_request_data.get(key, default=default)

def get_one_request_POST_datum(self, key, default=None):
    return self.get_request_POST.get(key, default=default)
```
(These last 3 methods are not necessary, but it exemplifies some use cases.)

Adding these methods in Field class where context property is defined would make it easy to have shorter and simpler code in some use cases.
Mainly in Serializers where we use data from query_params, mainly in SerializerMethodField get_...() method ;
for example when the SerializerMethodField makes an expensive calculus that must be explicitely required by the client of the API with a query_param or something else.

I would be happy to have your opinions about this feature request and to make a pull request if you accept it :)

Best regards,
     Laurent Lyaudet

PS : Since the request is not available, I have not proposed the default value used in class Request : 
`QueryDict('', encoding=self._request._encoding)` for data/POST
Moreover, in some cases data may return simply {}.
For query_params/GET it defaults to QueryDict(mutable=True) in Django.
I have no problem with more clever default value if you have any suggestion.</div>

**Comment by LLyaudet** [comment]
Hello,

Since I got no feedback apart 3 upvotes, I thought that maybe I should open an issue.
But I also saw that the project is considered "feature-complete".
Let me know if you are open to this improvement or not, please.

Best regards,
     Laurent Lyaudet

**Comment by tomchristie** [comment]
> But I also saw that the project is considered "feature-complete".
> Let me know if you are open to this improvement or not, please.

Indeed, yup. We'll continue tracking Django releases, but we're not looking at introducing new functionality at this point.
