### ISSUE TITLE
forgot to add the app into the project

### ISSUE THREAD

**Issue by Edgar3g** [encode/django-rest-framework#8477]
### Forgot to add the app to the project

In the quick start tutorial, the app was not added to the project, thus making it impossible for the application to work...
in the tutorial, only the rest_framework was added!

[REST FRAMEWORK quickStart tutorial](https://www.django-rest-framework.org/tutorial/quickstart/)

_demo image:_
![imagem](https://user-images.githubusercontent.com/56559291/166086359-20f85396-c822-4e6f-884e-aa1000889881.png)

**Comment by tomchristie** [comment]
I've just run through the QuickStart and verified to myself that I don't see any error here.
You shouldn't need to add "tutorial" to `INSTALLED_APPS` here because it doesn't contain any models.

Can you show what error you were seeing?
