### ISSUE TITLE
quickstart get /users/ 404

### ISSUE THREAD

**Issue by ylmcr7** [encode/django-rest-framework#8482]
![image](https://user-images.githubusercontent.com/63889450/166226739-bf897c82-5fda-4f19-b8e9-d329b13c9a8f.png)

**Comment by shywn-mrk** [comment]
This is not an issue here and you did not provide enough information about your problem but it may be a bug in your code and it's not related.

**Comment by ylmcr7** [comment]
> This is not an issue here and you did not provide enough information about your problem but it may be a bug in your code and it's not related.

sloved
