### ISSUE TITLE
ModuleNotFoundError: No module named 'rest_framework'

### ISSUE THREAD

**Issue by ARIEnergy** [encode/django-rest-framework#8500]
## Checklist

- [x] Raised initially as discussion #...
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
I used Django rest framework to develop my api and then installed successfully, but then I ran the project, it always showed the error no module named rest_framework(based on your readme, I did same as you).

I used Python 3.8

**Comment by OmerFI** [comment]
Suggestions:
- Use a virtualenv
- Check your path and if rest_framework is in the path

**Comment by nmescv** [comment]
@ARIEnergy Did you solve this problem? These suggestions can't help me. >.<

**Comment by ARIEnergy** [comment]
@nmescv  Cannot fix, but I reinstall it again, all was disappeared, weird issue!!! Thank for your tips and advices
