### ISSUE TITLE
dj-rest-auth

### ISSUE THREAD

**Issue by 1alirezahashemi1** [encode/django-rest-framework#8508]
## Checklist

in urls.py of dj-rest-auth  we have a url  which named rest_password_reset_confirm and it should be same with what template wants

it should rename to password_reset_confirm and it's path should be 
( password/reset/confirm/uidb64/token ) but at the moment it doesnt have uidb and token at the end of the route

thanks !

**Comment by tomchristie** [comment]
Sorry, it\s not clear enough to me what the suggestion is here.
