### ISSUE TITLE
'list' object is not callable

### ISSUE THREAD

**Issue by goophps** [encode/django-rest-framework#8516]
linux deepin 20.5
python 3.10.4
django version 4.0.5
rest-framework version 3.13.1

this is error
![image](https://user-images.githubusercontent.com/49714224/172019512-81480b12-84b0-4672-abb4-7d5ad89d0dd7.png)

this is urls.py
![image](https://user-images.githubusercontent.com/49714224/172019520-b10c80ec-2b23-4247-b5ff-429772350c63.png)

this is views.py
![image](https://user-images.githubusercontent.com/49714224/172019536-42d1bb2c-712d-4761-b54f-750879cf8773.png)

**Comment by goophps** [comment]
no one cares about me

**Comment by tomchristie** [comment]
I'm pretty sure you've some folks that care about you.

**Comment by goophps** [comment]
Can anyone help me answer this question? I tried for hours and also deleted and reinstalled it.

**Comment by huzaifa-salih** [comment]
router.register(r'banner', BannerViewSet)


your mistake registers 
the true register

**Comment by goophps** [comment]
> copy this:
> 
> > > > > > router.register(r'banner', BannerViewSet)
> 
> your mistake registry the true register

Oh my god, I spelled it wrong. thanks.

**Comment by huzaifa-salih** [comment]
💚
