### ISSUE TITLE
TokenProxy verbose_name is not translated in django admin site

### ISSUE THREAD

**Issue by macolszewski** [encode/django-rest-framework#8537]
The problem is TokenProxy model is registered in admin site
```python
admin.site.register(TokenProxy, TokenAdmin)
```
but there is lack of translation for `verbose_name` in `TokenProxy`'s meta class

```python
class TokenProxy(Token):
    """
    Proxy mapping pk to user pk for use in admin.
    """
    @property
    def pk(self):
        return self.user_id

    class Meta:
        proxy = 'rest_framework.authtoken' in settings.INSTALLED_APPS
        abstract = 'rest_framework.authtoken' not in settings.INSTALLED_APPS
        verbose_name = "token"
```

so translation looks like 
![image](https://user-images.githubusercontent.com/41488459/176402874-dc33b437-cbad-40b6-be1a-8a2ca54a7ca6.png)
instead of
![image](https://user-images.githubusercontent.com/41488459/176403046-8f7e01ee-d85b-448f-949a-0f8bbe01c8e4.png)

**Comment by Giebisch** [comment]
I've created a PR: [Link](https://github.com/encode/django-rest-framework/pull/8713)
