### ISSUE TITLE
DateTimeField `to_internal_representation` checks the value for the wrong type

### ISSUE THREAD

**Issue by alexsavio** [encode/django-rest-framework#8559]
## Checklist

From `fields.py` (~line 1199) in the DateTimeField class:

```   
def to_internal_value(self, value):
        input_formats = getattr(self, 'input_formats', api_settings.DATETIME_INPUT_FORMATS)

        if isinstance(value, datetime.date) and not isinstance(value, datetime.datetime):
            self.fail('date')

        if isinstance(value, datetime.datetime):
            return self.enforce_timezone(value)
```

If we used this Field serializer in from a ModelSerializer connected in a generic.APIView, these 2 `ifs` will never evaluate to `True` because `value` come directly from the request and it is a `str`. Am I doing anything wrong or is this true?

**Comment by slyapustin** [comment]
@alexsavio the easiest way to check that is to look at the result of the code coverage tool. 
And from that I can see that part of the code is triggered in the latest version:
https://app.codecov.io/gh/encode/django-rest-framework/blob/c59e8cc275776ef428462ccdd61a99f0d5ab2820/rest_framework/fields.py
<img width="1142" alt="Screen Shot 2022-07-20 at 22 52 51" src="https://user-images.githubusercontent.com/370774/180080053-ee603e58-0352-4698-8023-bc16d0cee0f0.png">


It would be great if you can provide more specific example for your issue.

**Comment by alexsavio** [comment]
I guess the only way to enforce datetimes and reject dates is with `input_formats`. Thank you! Got it

**Comment by alexsavio** [comment]
The issue was that the [documentation](https://www.django-rest-framework.org/api-guide/fields/#datetimefield-format-strings) led me to think that the ISO8601 format would only allow datetimes however the serializer was accepting dates as well and filling up the time with 0s.
