### ISSUE TITLE
Documentation tutorial mistake

### ISSUE THREAD

**Issue by pppppppan** [encode/django-rest-framework#8579]
https://www.django-rest-framework.org/tutorial/6-viewsets-and-routers/
at [Using Routers](https://www.django-rest-framework.org/tutorial/6-viewsets-and-routers/#using-routers) chapter
`router.register(r'snippets', views.SnippetViewSet,basename="snippets")`
shoud be
`router.register(r'snippets', views.SnippetViewSet,basename="snippet")`
beause in [[Hyperlinking our API](https://www.django-rest-framework.org/tutorial/5-relationships-and-hyperlinked-apis/#hyperlinking-our-api)]the view_name is "snippet-highlight"

**Comment by tomchristie** [comment]
Resolved in https://github.com/encode/django-rest-framework/pull/8517 - docs will be updated in the next release.
