### ISSUE TITLE
OpenAPI schema for FileField/ImageField is always string/binary

### ISSUE THREAD

**Issue by denisorehovsky** [encode/django-rest-framework#8625]
## Checklist

- [x] Raised initially as discussion https://github.com/encode/django-rest-framework/issues/6863
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.

Request and response schemas have the same format for FileField and ImageField:
```
"some_field": {
    "type": "string",
    "format": "binary"
}
```

However, it's not correct. If you look at implementation of FileField, you will see that `to_representation` always returns string:
![image](https://user-images.githubusercontent.com/9641784/187060605-14fd10de-32f1-4bc0-8a9c-484e54696ec3.png)

Response format should be `url` or no format at all if `UPLOADED_FILES_USE_URL` is false.

This was initially mentioned in https://github.com/encode/django-rest-framework/issues/6863

**Comment by auvipy** [comment]
closing not planned anymore

**Comment by syabro** [comment]
@auvipy why? It's a problem for me right now...
