### ISSUE TITLE
Release 3.13.2 version, stating explicitly that it does not work with Django 4.1

### ISSUE THREAD

**Issue by dilyanpalauzov** [encode/django-rest-framework#8647]
According to https://github.com/encode/django-rest-framework/pull/8599 and https://github.com/encode/django-rest-framework/pull/8591 DRF 3.13 does not work with Django 4.1.  But https://github.com/encode/django-rest-framework/blob/master/setup.py#L85 says the opposite.

Hyperkitty (Mailman 3) is a Django project which uses DRF and can work with Django 4.1. It uses DRF 3.13.1 as it is the last released version.  This leads to a situation, where DRF 3.13 is used with Django 4.1, which is incompatible, but no warning hints on this incompatibility.

By releasing a version 3.13.2, which states explicitly that it does not work with Django 4.1, indirect users of Django 4.1 will get a hint, when they try to combine incompatible versions.

**Comment by tomchristie** [comment]
Closing in favour of https://github.com/encode/django-rest-framework/pull/8599
