### ISSUE TITLE
BookListSerializer example for create case is flawed

### ISSUE THREAD

**Issue by mangelozzi** [encode/django-rest-framework#8658]
This example at <https://www.django-rest-framework.org/api-guide/serializers/#customizing-multiple-update>

```
class BookListSerializer(serializers.ListSerializer):
    def update(self, instance, validated_data):
        # Maps for id->instance and id->data item.
        book_mapping = {book.id: book for book in instance}
        data_mapping = {item['id']: item for item in validated_data}

        # Perform creations and updates.
        ret = []
        for book_id, data in data_mapping.items():
            book = book_mapping.get(book_id, None)
            if book is None:
                ret.append(self.child.create(data))
            else:
                ret.append(self.child.update(book, data))
```

Is flawed in the create case, because an `id` key value pair will not exist in validated data, so this line:

```
 data_mapping = {item['id']: item for item in validated_data}
```

Will fail at `item['id']`, maybe it should be `item.get('id')`, but then maybe the rest of it might have to change too, e.g.:

```
         for book_id, data in data_mapping.items():
            if not book_id:
                ret.append(self.child.create(data))
            else:
                object = object_mapping.get(book_id, None)
                ret.append(self.child.update(object, data))
```

**Comment by tomchristie** [comment]
> Is flawed in the create case

This is the `update` method.

**Comment by mangelozzi** [comment]
> > Is flawed in the create case
> 
> This is the `update` method.

To quote the example:

> How should insertions be handled? Are they invalid, or do they create new objects?

And the code handles updates and creates:
```
            if book is None:
                ret.append(self.child.create(data))  # <--- this line is for creates
            else:
                ret.append(self.child.update(book, data))
```

So although it is the update method, it handles create, update, and delete.

**Comment by mangelozzi** [comment]
Anyone else want to give this a thought? It still does not work. Yes it is called `update`, but it also performs delete and create functionality. Applying your logic, if there was an issue with the delete part, you would say "this is update method" and stop thinking past that.
