### ISSUE TITLE
AttributeError: module 'rest_framework.serializers' has no attribute 'NullBooleanField'. Did you mean: 'BooleanField'?

### ISSUE THREAD

**Issue by AminBidad1** [encode/django-rest-framework#8668]
in the latest version of djangorestframework (3.14.0) NullBooleanField was removed.
but <a href="https://pypi.org/project/drf-yasg/">drf-yasg</a> library uses from NullBooleanField 
so it will raise the error:
<code>AttributeError: module 'rest_framework.serializers' has no attribute 'NullBooleanField'. Did you mean: 'BooleanField'?</code>
how can I solve it ?

**Comment by miko13** [comment]
this is addressed in the latest release of [drf-spectacular](https://github.com/tfranzel/drf-spectacular/issues/816) so you just need to update to `0.24.1

**Comment by AminBidad1** [comment]
> this is addressed in the latest release of [drf-spectacular](https://github.com/tfranzel/drf-spectacular/issues/816) so you just need to update to `0.24.1`

thank you for suggestion.
but I wanna use the main djangorestframework and drf-yasg library.
not any other way?

**Comment by Viicos** [comment]
You'll have to wait for https://github.com/axnsan12/drf-yasg/pull/811 to get merged.

**Comment by AminBidad1** [comment]
> You'll have to wait for [axnsan12/drf-yasg#811](https://github.com/axnsan12/drf-yasg/pull/811) to get merged.

thank you for your guidance.
