### ISSUE TITLE
Serializing a dict using "source" does not work

### ISSUE THREAD

**Issue by mcosti** [encode/django-rest-framework#8673]
## Checklist

- [ x] Raised initially as discussion #...
- [ x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x ] I have reduced the issue to the simplest possible case.

```python
class CourseSerializer(serializers.Serializer):
    id = serializers.IntegerField()
    key = serializers.CharField(source="courseKey")

data = {'id': 1, 'courseKey': 'abc'}

serializer = CourseSerializer(data=data)
serializer.is_valid(raise_exception=True)

>>> rest_framework.exceptions.ValidationError: {'key': [ErrorDetail(string='This field is required.', code='required')
```

I've spent around 2 hours browing the documentation and google for a fix, but meanwhile I will just end up using a different serializing library. 

Thanks for the assistance

**Comment by tomchristie** [comment]
I think you've got the arguments the wrong way around. (Yes it's easily confused)

```python
class CourseSerializer(serializers.Serializer):
    id = serializers.IntegerField()
    courseKey = serializers.CharField(source="key")
```

**Comment by mcosti** [comment]
Yeah it still doesn't work. @tomchristie marked it as complete, but I didn't bother and just used pydantic instead

**Comment by michalnik** [comment]
Additionaly even workaround or another way does not work for me. According to https://www.django-rest-framework.org/api-guide/fields/#source , the method could be used as source value.
```
The name of the attribute that will be used to populate the field. May be a method that only takes a self argument, such as URLField(source='get_absolute_url'), or may use dotted notation to traverse attributes, such as EmailField(source='user.email').
```
But my academic purpose code to prove that it is ok is below and does not work either.
```python
from rest_framework import serializers
class My(serializers.Serializer):
     id = serializers.IntegerField()
     key = serializers.CharField(source="get_key")
     def get_key(self):
         print("no call")
         return self.data["courseKey"]
data = {"id": 1, "courseKey": "asd"}
ser.is_valid()  # False
ser.errors  # {'key': [ErrorDetail(string='Toto pole je třeba vyplnit.', code='required')]}
```
I also tried the dotted notation, for that purpose I tried to use dataclass ...
```python
from dataclasses import dataclass, field
@dataclass
class Row:
     id: int = field()
     courseKey: str = field()
class My(serializers.Serializer):
    id = serializers.IntegerField()
    key = serializers.CharField(source="courseKey")
data = Row(id=1, courseKey="ads")
ser = My(data=data)
ser.is_valid()  # False
ser.errors  # {'non_field_errors': [ErrorDetail(string='Invalid data. Expected a dictionary, but got Row.', code='invalid')]}
```
So nothing from documentation works for me.

*notice: it seems that not all the things form internal django or drf is translated into czech, but it is ok, please focus on the "source" does not work according to doc.*

**Comment by michalnik** [comment]
Ok, I find that I was wrong when I want to serialized internally computed data and put it into the response it is wrong to do it this way. The right way is.
```python
from rest_framework import serializers
class My(serializers.Serializer):
     id = serializers.IntegerField()
     key = serializers.CharField(source="courseKey")
data = {"id": 1, "courseKey": "asd"}
ser = My(data)
# you cannot call this, because the data are supposed already be validated - ser.is_valid()
# IMHO, the source kwarg is intended to use with trusted source data, from database model of django...
return Response(data=ser.data)  # I am not sure with this Response, but ser.data is ok
