### ISSUE TITLE
Unlcear documentation `permission_classes`

### ISSUE THREAD

**Issue by mangelozzi** [encode/django-rest-framework#8677]
Documented in :
https://www.django-rest-framework.org/api-guide/permissions/#setting-the-permission-policy

it describes `permission_classes`. It is a list of permissions. Are the permissions by default 'ADD'ed or 'OR'ed together? Will the user be allowed if they pass one or all of the permissions?

I know towards the end it says you can use bitwise operators, but it is unclear if you don't use bitwise operators, what is the result of a 
list of permissions?

**Comment by tomchristie** [comment]
https://www.django-rest-framework.org/api-guide/permissions/#how-permissions-are-determined

> Permissions in REST framework are always defined as a list of permission classes.
>
> Before running the main body of the view each permission in the list is checked. If any permission check fails, an `exceptions.PermissionDenied` or `exceptions.NotAuthenticated` exception will be raised, and the main body of the view will not run.

**Comment by mangelozzi** [comment]
Sorry, I missed that.
