### ISSUE TITLE
Nasty warning using CursorPagination with drf-spectacular

### ISSUE THREAD

**Issue by norbertschuler** [encode/django-rest-framework#8686]
Creating an OpenAPI for a project using https://github.com/tfranzel/drf-spectacular together with `rest_framework.pagination.CursorPagination` raises the following warning:

> OpenApiExample could not be paginated because <class 'rest_framework.pagination.CursorPagination'> either has an unknown schema structure or the individual pagination fields did not provide example values themselves. Using the plain example value as fallback.

It would be nice if some examples could be added to this code if it is possible to avoid this nasty warning:

https://github.com/encode/django-rest-framework/blob/d507cd851c4b1185e3dc720de9ba6a642459d738/rest_framework/pagination.py#L894-L908

**Comment by tomchristie** [comment]
I've no idea what needs to change here.
Does this issue need to start out as a conversation with the `drf-spectacular` maintainers first?

**Comment by norbertschuler** [comment]
> I've no idea what needs to change here. 

Just do it similar to other pager classes for the `next` and `previous` properties, e.g. 

https://github.com/encode/django-rest-framework/blob/d507cd851c4b1185e3dc720de9ba6a642459d738/rest_framework/pagination.py#L242-L248

**Comment by tomchristie** [comment]
Okay, would you like to submit a pull request for that?
