### ISSUE TITLE
Django v5 deprecation warning of utc library

### ISSUE THREAD

**Issue by mj-v** [encode/django-rest-framework#8693]
## Checklist

- [ ] Raised initially as discussion #...
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [ ] I have reduced the issue to the simplest possible case.

There is an upgrade warning to django 5, as the usage of utc library changed a bit as following:

.venv/lib/python3.10/site-packages/rest_framework/fields.py:30: RemovedInDjango50Warning: The django.utils.timezone.utc alias is deprecated. Please update your code to use datetime.timezone.utc instead.
  from django.utils.timezone import utc

**Comment by tomchristie** [comment]
Hiya. Could you include a complete traceback please?
This looks like it might be against an older version of REST framework.

**Comment by mj-v** [comment]
There is no traceback. This is a Djnago warning when you test your app and the mentioned rest_framework field.py should change, so please drop utils library from the line 22 field.py:

from django.utils import timezone

so timezone is directly under datetime and not djnago anymore.

**Comment by tomchristie** [comment]
Thanks.

Yup, you'll need to test against the latest REST framework release.
Believe this was resolved by #8498

**Comment by mj-v** [comment]
I seee.. the latest available release here is 3.12 but I saw in 3.14 in pypi and it is working as expected without error.
Thank you very much for your help!

**Comment by tomchristie** [comment]
Good stuff.
Have yourself a grand day.
