### ISSUE TITLE
DurationField missing in SimpleMetadata.label_lookup

### ISSUE THREAD

**Issue by smt-insens** [encode/django-rest-framework#8700]
### Discussed in https://github.com/encode/django-rest-framework/discussions/8696

<div type='discussions-op-text'>

<sup>Originally posted by **smt-insens** October 13, 2022</sup>
### Context: 

I made an HTTP OPTIONS request. In the response I have the type of each field. I have a duration field so I expected to see something like "duration" as type but instead I have "field".

### Solution:

After investigation I found that `DurationField` is missing in `SimpleMetadata.label_lookup`

This is probably due to the fact `DurationField` was added to Django after the other fields. The person who added `DurationField` probably forgot to add it to the label_lookup.

The following line should be added to `label_lookup`: `serializers.DurationField: 'duration',`

https://github.com/encode/django-rest-framework/blob/20d347a806baa0dd481b31a7f847386574882d5b/rest_framework/metadata.py#L36-L58

https://github.com/encode/django-rest-framework/blob/20d347a806baa0dd481b31a7f847386574882d5b/rest_framework/fields.py#L1320-L1349</div>

**Comment by auvipy** [comment]
merged. thanks a lot
