### ISSUE TITLE
ImageField does not automatically delete the files after the records was deleted

### ISSUE THREAD

**Issue by fq-zhaang** [encode/django-rest-framework#8709]
model definition:
```python
class Items(models.Model):
    item_name = models.CharField(max_length=100)
    item_img = models.ImageField(null=True, blank=True, max_length=1024, upload_to='homeorganizer/')
    storage_unit = models.ForeignKey(to='StorageUnits', on_delete=models.SET_NULL, null=True)
    
    class Meta:
        db_table = f'"{SCHEMA}"."items"'
```
Serializer definition:
```python
class ItemsSerializer(serializers.ModelSerializer):
    class Meta:
        model = Items
        fields = '__all__'
```
View definition:
```python
class ItemsViewSet(viewsets.ModelViewSet):
    queryset = Items.objects.all()
    serializer_class = ItemsSerializer
```
After HTTP `DELETE` requests deleted the records, the files still exist. Is there any way can automatically delete the files after the records are deleted?

**Comment by md-sahil-11** [comment]
For deleting the files you can override the delete function in the models.
```python
class Items(models.Model):
    item_name = models.CharField(max_length=100)
    item_img = models.ImageField(null=True, blank=True, max_length=1024, upload_to='homeorganizer/')
    storage_unit = models.ForeignKey(to='StorageUnits', on_delete=models.SET_NULL, null=True)
    
    class Meta:
        db_table = f'"{SCHEMA}"."items"'

    def delete(self, *args, **kwargs):
        self.item_img.delete()
        super().delete(*args, **kwargs)

```

**Comment by fq-zhaang** [comment]
> For deleting the files you can override the delete function in the models.
> 
> ```python
> class Items(models.Model):
>     item_name = models.CharField(max_length=100)
>     item_img = models.ImageField(null=True, blank=True, max_length=1024, upload_to='homeorganizer/')
>     storage_unit = models.ForeignKey(to='StorageUnits', on_delete=models.SET_NULL, null=True)
>     
>     class Meta:
>         db_table = f'"{SCHEMA}"."items"'
> 
>     def delete(self, *args, **kwargs):
>         self.item_img.delete()
>         super().delete(*args, **kwargs)
> ```

Thanks a lot!
