### ISSUE TITLE
'RelatedManager' object is not iterable

### ISSUE THREAD

**Issue by 954-Ivory** [encode/django-rest-framework#8726]
These days, I create a custom manager repr for django:

https://github.com/954-Ivory/django_bulk_hook_manager

But I get the error when I use it with DRF:

```shell
rest_framework/serializers.py", line 686, in to_representation
    return [
TypeError: 'RelatedManager' object is not iterable
```

So, I check it, and found the reason.

---

[Error line:](https://github.com/encode/django-rest-framework/blob/2510456817d9d2840a4080e69a0efb8a4da423ac/rest_framework/serializers.py#L686)
```python
iterable = data.all() if isinstance(data, models.Manager) else data
```

This line should change to:
```python
iterable = data.all() if isinstance(data, (
            models.manager.Manager, models.manager.BaseManager
        )) else data
```

We need to check whether `data` is a `BaseManager` instance.

I will PR later.

**Comment by auvipy** [comment]
good catch, lets continue on the PR

**Comment by 954-Ivory** [comment]
> thanks a lot for your contribution

I should thank you more to the teach and help 😀

**Comment by auvipy** [comment]
and thank you for collaborating :)
