### ISSUE TITLE
Releases past 3.12.4 are missing from GitHub

### ISSUE THREAD

**Issue by jaap3** [encode/django-rest-framework#8750]
[The releases page on GitHub ](https://github.com/encode/django-rest-framework/releases) makes it appear as if 3.12.4 is the most current release. It is also the version mentioned prominently in the repository sidebar. I *almost* pinned a project to this version until I realised that I should probably check PyPI.

**Comment by tomchristie** [comment]
Well observed @jaap3.
Can see some inconsistencies there.
I can backfill the last few missing releases if that'd help?

**Comment by tomchristie** [comment]
Okay, I've filled in the latest releases.
Should do the job for now(?)... https://github.com/encode/django-rest-framework/releases

**Comment by s4ke** [comment]
I would vote for keeping the GitHub releases as that's usually where we check what was changed in a given release. Or should this be done via the homepage?

**Comment by tomchristie** [comment]
> I would vote for keeping the GitHub releases as that's usually where we check what was changed in a given release.

Let's keep them displayed yes.

There's still some *older* releases that are not consistent with the tags, but at least the latest ones are now correct.
I'm going to treat this as good enough for now unless nudged otherwise.
