### ISSUE TITLE
http_method_names should be in same format

### ISSUE THREAD

**Issue by GoelJatin** [encode/django-rest-framework#8753]
We've the check for http_method_names for a ViewSets -- https://github.com/encode/django-rest-framework/blob/56946fac8f29aa44ce84391f138d63c4c8a2a285/rest_framework/views.py#L500

But for the `api_view` decorator we're setting the method names in upper case -- https://github.com/encode/django-rest-framework/blob/56946fac8f29aa44ce84391f138d63c4c8a2a285/rest_framework/decorators.py#L21

This creates confusion to users and especially binds them to use them in a particular format

Proposed solution:

if request.method.lower() in map(lambda x: x.lower(), self.http_method_names):

This would ensure the check works for all cases of the method name

**Comment by GoelJatin** [comment]
Got it, It seems this has been added for 3.14, we're currently on 3.12.4 and came across this while trying to find the root cause

**Comment by tomchristie** [comment]
Can we close this and #8754?

**Comment by GoelJatin** [comment]
I did not try with latest but if you feel this isn't required we can go ahead and close both

**Comment by zenodallavalle** [comment]
I find a bit confusing that the [W3C convention and django itself](https://stackoverflow.com/questions/27423615/http-method-names-upper-or-lower-case) handles method in uppercase and DRF API handles http methods in lowercase. Couldn't be implemented at least as case-insensitive (for backwards compability)?
