### ISSUE TITLE
Problem implement custom status_code BasePermission

### ISSUE THREAD

**Issue by AdrianPardo99** [encode/django-rest-framework#8768]
## Checklist

- [ ] Raised initially as discussion #...
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.

I have trouble with add a custom code in my base permission class, my code is:
```python
class IsActiveTenantUserAuthenticated(permissions.BasePermission):

    code = 443

    def has_permission(self, request, view):
        return (
            request.user
            and isinstance(request.user, TenantUser)
            and request.user.is_active
        )
```

When implement in my APIVIEW:

```python
class TokenVerifyView(APIView):

    permission_classes = [IsActiveTenantUserAuthenticated]
    
    def post(self, request, *args, **kwargs):
          # All code here
```

When I test I have 403 always

Is something wrong with the module?

I have the next version: 3.13.1

**Comment by implicitdefcncdragneel** [comment]
Your Code is Globally Returning "403" when permission is granted or denied and for better define GenericAPIException with the status_code 403.
