### ISSUE TITLE
Versioning doesn't work with Custom middleware

### ISSUE THREAD

**Issue by johnugeorge** [encode/django-rest-framework#8823]
I have enabled `AcceptHeaderVersioning` as the `DEFAULT_VERSIONING_CLASS`.  I have added a custom middleware(added at the last of the MIDDLEWARE list)  which looks at `request.version` value and take actions based on the custom logic.  However, I see that `request.version` is not populated in the middleware and returns the error. 

```
  File "/Users/test/opt/miniconda3/envs/test/lib/python3.9/site-packages/django/core/handlers/base.py", line 171, in _get_response
    response = middleware_method(request, callback, callback_args, callback_kwargs)
  File "/Users/test/work/test1/versioncheck/middleware.py", line 35, in process_view
    print(request.version)
AttributeError: 'WSGIRequest' object has no attribute 'version'
```

## Checklist

- [ ] Raised initially as discussion #...
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.

**Comment by tfranzel** [comment]
Pretty sure this is expected behavior. The middleware stack runs prior to view initialization and the view is actually the entity that carries the versioning class. It is imho expected to be missing on the way down the middleware stack. It should be available on the way up (after view was rendered) though.
