### ISSUE TITLE
Request parser params error

### ISSUE THREAD

**Issue by lau-jay** [encode/django-rest-framework#8875]
## Checklist

- [x] Raised initially as discussion #...
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.

for my request:
curl --data 'xx=30&id=100' localhost:8000/api/v1/xxx

using rest_framework.request.Request in middleware extract request data: 
req = Request(request, parsers=[FormParser, MultiPartParser]) 

debuging by ipdb, i see this:

<img width="1147" alt="Screenshot 2023-02-15 at 18 11 24" src="https://user-images.githubusercontent.com/6316150/219000669-df963ef9-7827-44ad-afab-75a2baa4212a.png">

I think this function call is not a problem, but his result I have no idea why

**Comment by auvipy** [comment]
can you link to the discussion and contribute a failing test case please?

**Comment by lau-jay** [comment]
sure

**Comment by lau-jay** [comment]
> can you link to the discussion and contribute a failing test case please?

https://github.com/encode/django-rest-framework/discussions/8876

**Comment by lau-jay** [comment]
The APIView class or @api_view decorator will ensure that this property is automatically set to a list of Parser instances, so above example code incorrect
