### ISSUE TITLE
The live example API website is broken

### ISSUE THREAD

**Issue by svcosmghtest** [encode/django-rest-framework#8887]
## Checklist

- [ ] Raised initially as discussion #...
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [ ] I have reduced the issue to the simplest possible case.

https://restframework.herokuapp.com/
![image](https://user-images.githubusercontent.com/86942276/221531551-4e926382-f72b-44d9-92b9-982cbad33bad.png)

**Comment by auvipy** [comment]
@tomchristie is there anything we can do here?

**Comment by ARezaK** [comment]
still broken

**Comment by svcosmghtest** [comment]
Pls, any updates on this?

**Comment by baseplate-admin** [comment]
This is due to Heroku shutting down their free services.

@auvipy , I think redeploying to something like [`railway`](https://railway.app/template/GB6Eki)/[`render`](https://render.com/docs/deploy-django) is the best approach here

**Comment by ashupednekar** [comment]
Hi, I would like to take this up as a first issue if possible...

Been working with DRF for the past three years, affluent with deployment to any providers.

**Comment by auvipy** [comment]
yeah changing provider should fix this

**Comment by suspiciousRaccoon** [comment]
[pythonanywhere](https://www.pythonanywhere.com/) also offers free hosting. Alternatively maybe it could be shared with a docker image?

**Comment by auvipy** [comment]
we can consider that. btw how is that now a days? performing better then old times?

**Comment by codespearhead** [comment]
I believe [Digital Ocean's Credits for (Open Source) Projects](https://www.digitalocean.com/open-source/credits-for-projects#faqs) would be a good call.
