### ISSUE TITLE
cannot import name 'SkipError' from 'rest_framework.exceptions'

### ISSUE THREAD

**Issue by OmniaOsman** [encode/django-rest-framework#8893]
I installed DRF, put 'rest_framework' in installed apps, and add path('api-auth/', include('rest_framework.urls')) in URLs

put raises this error:
```
raise InvalidTemplateLibrary(
django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'rest_framework.templatetags.rest_framework': cannot import name 'SkipError' from 'rest_framework.exceptions' (C:\Users\C.M\.virtualenvs\src-Hn7NFGL7\lib\site-packages\rest_framework\exceptions.py)
```

I use Django 4.1 and DRF 3.14

**Comment by iameo** [comment]
I am running same versions of Django and DRF on a virtual environment and getting no issues with it.

POST and PUT working just fine. When do you get an error on it?

![](https://ibb.co/6tt38RY)
![PutWorks](https://i.ibb.co/n11HBsr/Screenshot-220.png)

**Comment by Igonato** [comment]
It seems there might be an issue with your Django templates setup and not DRF.
Do you have `TEMPLATES` defined in your `settings.py`? Can you post it here?

**Comment by auvipy** [comment]
I am going to close this as not a DRF bug
