### ISSUE TITLE
Validators do not implement `__eq__` method

### ISSUE THREAD

**Issue by michaelurban** [encode/django-rest-framework#8905]
Rest Framework validators do not implement the `__eq__` method like many of their Django counterparts.

The expression `ProhibitSurrogateCharactersValidator() == ProhibitSurrogateCharactersValidator()` evaluates to `False` when it would be useful to have it evaluate to `True`, especially in tests.

**Comment by auvipy** [comment]
would you mind come with at least one draft implementation of this? I need to see what we can actually achieve with it. I can recall something like this in django core but can't remember exact usecases

**Comment by auvipy** [comment]
as it is a django compat stuff, I am open to contribution in this regard

**Comment by auvipy** [comment]
yes
