### ISSUE TITLE
Does DRF support Content-Type:multipart/form-data with nested object

### ISSUE THREAD

**Issue by mhadhbimouwahed** [encode/django-rest-framework#8910]
## Checklist

- [ x ] Raised initially as discussion #7262
- [ x ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [ x ] I have reduced the issue to the simplest possible case.

**Comment by codeofmagma** [comment]
@mhadhbimouwahed you can try this one
https://github.com/remigermain/nested-multipart-parser

**Comment by tomchristie** [comment]
`multipart/form-data` doesn't support nested data, so any attempts to do this are always going to be somewhat ad-hoc.

**Comment by sanchaz** [comment]
this seems to work quite well
while digging through the source code
I found

https://github.com/encode/django-rest-framework/blob/3.15.1/rest_framework/serializers.py#L614
and following that
https://github.com/encode/django-rest-framework/blob/3.15.1/rest_framework/utils/html.py

```
    regex = re.compile(r'^%s\[([0-9]+)\](.*)$' % re.escape(prefix))
```
So I tried doing 

```
class TwoSerializer(serializers.Serializer):
    something_else = serializers.DateTimeField(required=False) 
    mytext = serializers.CharField(required=True, max_length=255)

class OneSerializer(serializers.Serializer):
    nested = TwoSerializer(required=False, write_only=True)
    file = serializers.FileField()
```

```
data = {
    'nested.mytext': 'hello',
    file...
}
 request = self.factory.post(f'api/endpoint/, data, format='multipart')
```

something like this.
basically dot notation works in this case.

then searching for `django rest nested fields multipart dot notation` gave me this

which seems to suggest someone else stumbled upon the same

https://b0uh.github.io/drf-how-to-handle-arrays-and-nested-objects-in-a-multipartform-data-request.html

is this supported behaviour or can we expect it to break?
