### ISSUE TITLE
URL path is displayed incorrectly after the router has registered

### ISSUE THREAD

**Issue by boziyoung** [encode/django-rest-framework#8939]
description:

today i have just added a new "viewsets" and i want to register it to the router; when i successfully registered it afterwards, i noticed it wasn't displayed correctly;

there are two same paths on the ApiRoot's pagee;

screenshot:
<img width="1226" alt="image" src="https://user-images.githubusercontent.com/50167927/230567480-380fc040-8abd-4dd5-85e2-da032594c516.png">

code url.py
`
from django.db import router
from .Viewset import ArticleViewSet, UserViewSet, ArticleSort, MainArticlesViewSet
from django.urls import  path, include
from rest_framework.routers import DefaultRouter
from rest_framework.urlpatterns import format_suffix_patterns

router = DefaultRouter()
router.register(r'articles', ArticleViewSet)
router.register(r'main', MainArticlesViewSet)
router.register(r'users', UserViewSet)
urlpatterns = [
    path("", include(router.urls)),
]

`
code viewset.py
`
class ArticleViewSet(viewsets.ModelViewSet):
    """
    A viewset that provides default `create()`, `retrieve()`, `update()`,
    `partial_update()`, `destroy()` and `list()` actions.
    """
    queryset = Articlemodel.objects.all()
    serializer_class = ArticleSerializer
    permission_classes = [IsOwnerOrReadOnly]
    authentication_classes = [authentication.TokenAuthentication]

    # Cache requested url for each user for 2 hours
    @method_decorator(cache_page(60*60*2))
    # @vary_on_headers("")
    def list(self, request, *args, **kwargs):
        return super().list(request, *args, **kwargs)

class MainArticlesViewSet(viewsets.ModelViewSet):
    queryset = Articlemodel.objects.all().values("id",  "title", "outline", "date")
    serializer_class = MainArticleSerializer
    permission_classes = [IsOwnerOrReadOnly]
    authentication_classes = [authentication.TokenAuthentication]

    # Cache requested url for each user for 2 hours
    @method_decorator(cache_page(60*60*2))
    # @vary_on_headers("")
    def list(self, request, *args, **kwargs):
        return super().list(request, *args, **kwargs)

`

**Comment by auvipy** [comment]
https://github.com/encode/django-rest-framework/pull/8438 should have fix this issue. besides you should use basename in your router
