### ISSUE TITLE
Python 3.11, support new http.HTTPMethod enum in action and view

### ISSUE THREAD

**Issue by sshishov** [encode/django-rest-framework#8995]
# Bug report

When using python 3.11, instead of hardcoding HTTP verbs, now we can use official enum: `HTTPMethod` as well as `HTTPStatus` for statuses

## What's wrong

We would like to use it in `decorators.action(methods=[HTTPMethod.POST])` for instance.
Currently it does not work and produce the following error (with `djangorestframework-stubs` package):
```python
error: List item 0 has incompatible type "Literal[HTTPMethod.POST]"; expected "Literal['GET', 'POST', 'DELETE', 'PUT', 'PATCH', 'TRACE', 'HEAD', 'OPTIONS', 'get', 'post', 'delete', 'put', 'patch', 'trace', 'head', 'options']"  [list-item]
```

## How is that should be

No `mypy` error should be reported

## System information

- OS: MacOS / Debian (docker)
- `python` version: 3.11
- `django` version: 3.2.18
- `mypy` version: 1.2.0
- `django-stubs` version: 1.16.0
- `djangorestframework-stubs` version: 1.10.0

## Original issue:
The issue was originally reported against the stub project, but recommended to move the issue/discussion over here: https://github.com/typeddjango/djangorestframework-stubs/issues/396

**Comment by kevin-brown** [comment]
If you're able to add tests which confirm that DRF doesn't experience unexpected behavior when the enums are used instead of the strings (so new tests, don't just change existing tests) then I would be willing to review those. At that point we should be able to update the type stubs to reflect that as supported behavior.

**Comment by auvipy** [comment]
that would be a good  start

**Comment by pavelkraleu** [comment]
@auvipy Do you think some other changes are needed?   

Code below passes which I think proofs that everything below line 146 on image above behaves same for `methods` as `str` or `HTTPMethod`.

```python
from http import HTTPMethod

assert isinstance(HTTPMethod.POST.lower(), str)
```

**Comment by sshishov** [comment]
Just a heads-up, we are using this `HTTPMethod.POST` approach in production already for a long time, and there were no issues so far.

Side note: for `requests` library we are using `HTTPStatus.OK` and others to identify the statuses and `HTTPMethod.GET` and others to identify HTTP method used.

Thanks for looking into it @pavelkraleu

**Comment by pavelkraleu** [comment]
Thank you for the confirmation @sshishov, I will make this change into final PR 💪

**Comment by pavelkraleu** [comment]
@auvipy Could you look into it please? 👆

**Comment by auvipy** [comment]
thanks for the test and documentation update.
