### ISSUE TITLE
`min_length` validation should works while using `many=True` with `SlugRelatedField`

### ISSUE THREAD

**Issue by KerberosMorphy** [encode/django-rest-framework#9000]
Base on DRF Documentations and Tests, it should be possible to pass `min_length` when using `many=True` as shown here:

https://github.com/encode/django-rest-framework/blob/376a5cbbba3f8df9c9db8c03a7c8fa2a6e6c05f4/tests/test_serializer_lists.py#L637

Considering this, I was expecting this mechanic to works with `SlugRelatedField` since it can be use with `many=True`:

```python
from django.contrib.auth.models import Group
from django.contrib.auth import get_user_model
from rest_framework import serializers

User = get_user_model()


class GroupSerializer(serializers.ModelSerializer):
    users = serializers.SlugRelatedField(
        many=True,
        min_length=3,
        queryset=User.objects.all(),
        slug_field="id",
    )

    class Meta:
        model = Group
        fields = ["users"]
```

But this raise `TypeError: Field.__init__() got an unexpected keyword argument 'min_length'`:

```python
Traceback (most recent call last):
  File "my_file.py", line 10, in GroupSerializer
  File ".../lib/python3.10/site-packages/rest_framework/relations.py", line 123, in __new__
    return cls.many_init(*args, **kwargs)
  File ".../lib/python3.10/site-packages/rest_framework/relations.py", line 143, in many_init
    list_kwargs = {'child_relation': cls(*args, **kwargs)}
  File ".../lib/python3.10/site-packages/rest_framework/relations.py", line 457, in __init__
    super().__init__(**kwargs)
  File ".../lib/python3.10/site-packages/rest_framework/relations.py", line 117, in __init__
    super().__init__(**kwargs)
TypeError: Field.__init__() got an unexpected keyword argument 'min_length'
```

- `djangorestframework`: 3.14.0
- `django`: 3.2.18
- `python`: 3.10.11

**Comment by auvipy** [comment]
that is possible in IntergerField. not in slug

**Comment by KerberosMorphy** [comment]
> that is possible in IntergerField. not in slug

No, `IntergerField` does not accept `many` argument. It did have `min_value` but it refer to the value of the data not the number of value inside à list of integer.

```python
class GroupSerializer(serializers.ModelSerializer):
    nb_users = serializers.IntegerField(
        many=True,
        min_length=3,
    )

    class Meta:
        model = Group
        fields = ["users"]
```

```python
TypeError: Field.__init__() got an unexpected keyword argument 'many'
```

**Comment by auvipy** [comment]
why should we use many inside integerfield btw?

**Comment by auvipy** [comment]
you are facing intending behaviour. it is not a bug

**Comment by KerberosMorphy** [comment]
> you are facing intending behaviour. it is not a bug

Thanks for the confirmation.
