### ISSUE TITLE
Link to bootstrap theme not works anymore

### ISSUE THREAD

**Issue by salicius** [encode/django-rest-framework#9020]
I'm reading official documentation to customize drf templates but seems that the url (https://bootswatch.com/flatly/bootstrap.min.css) written into the docs at https://www.django-rest-framework.org/topics/browsable-api/ not works anymore and seems not possible to customize pages

**Comment by denisSurkov** [comment]
Seems like this was fixed in https://github.com/encode/django-rest-framework/pull/8678

But the site was not rebuilt since

**Comment by AnshMittal12** [comment]
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>

try this

**Comment by tomchristie** [comment]
Thanks for identifying this @denisSurkov. (Yep, docs update pending new release)
