### ISSUE TITLE
Make responsive base.html template

### ISSUE THREAD

**Issue by salicius** [encode/django-rest-framework#9025]
https://github.com/encode/django-rest-framework/blob/master/rest_framework/templates/rest_framework/base.html

i'd like to have a responsive base template, how is it possible has never made? the responsiveness must be chosen from the start, seems like this project is not mantained!

**Comment by auvipy** [comment]
are you sure?

**Comment by auvipy** [comment]
here is a partially related PR for upgrading the bootstrap version https://github.com/encode/django-rest-framework/pull/7411 , you can take over that and introduce missing responsive parts

**Comment by Naman-12911** [comment]
Can I fix this issue.?

**Comment by auvipy** [comment]
if you can, give it a try

**Comment by Naman-12911** [comment]
ohk

**Comment by vicheanath** [comment]
This issue currenly have someone slove or not, if dosn't i want to solve it

**Comment by tomchristie** [comment]
Not interested in accepting issues that are presented with this level of un-civic behavior.

An acceptable issue would present screenshots, suggested changes, and demonstrate willingness to be part of improving the project.
