### ISSUE TITLE
reverse() for urls behind an API Gateway

### ISSUE THREAD

**Issue by gribok** [encode/django-rest-framework#9027]
Our DRF API is reachable through an API Gateway ([Kong](https://github.com/Kong/kong)).  
I recognized that `reverse()` is not working correctly for URLs behind the API gateway.
Therefore, the browsable API feature is not usable.  

I found out that the absolute url resolving relies on `django.http.request.build_absolute_uri` ([Link])(https://github.com/django/django/blob/main/django/http/request.py#L201)     

In generell, the API gateway sends two HTTP header values:  
`X_FORWARDED_HOST` (with `USE_X_FORWARDED_HOST=True`)  and `X_FORWARDED_PATH` (seems not to be standardized).  

**Example:**  
Source-path on DRF: `/api/v1/status`

Converted URL by API gateway (set by X_FORWARDED_PATH):
`/api-gateway-basepath/status`

`reverse()` returns `{{URL_OF_X_FORWARDED_HOST}}/api/v1/status` 

Instead it should return `{{URL_OF_X_FORWARDED_HOST}}/api-gateway-basepath/status`.  

I found a workound with monkeypatching. See here:   
https://stackoverflow.com/questions/76576882/django-reverse-behind-api-gateway-proxy/76591761#76591761

But I would like to start discussion to introduce an option inject an own function to modify URLs during `reverse()`.

**Comment by kevin-brown** [comment]
> Is it really a problem with `django-rest-framework` or with `django` itself?

My understanding is that this is a problem in Django, not specific Django REST framework. As such, I'm going to close this off and [would recommend making a ticket in Django about this](https://code.djangoproject.com/newticket) after checking if one does not already exist.
