### ISSUE TITLE
Option to have default router accept URLs without trailing slash

### ISSUE THREAD

**Issue by bobobo1618** [encode/django-rest-framework#905]
It'd just be nice to be able to create a default router which, when included in a URL configuration file, will accept URLs without a trailing slash.

This is entirely the fault of Angular.js which strips the slashes off its URLs and doesn't show any sign of changing. There are other developers who have had the [same problem](https://github.com/angular/angular.js/issues/992). The main issue is that Angular will POST without the slash and Django can't redirect that.

I know that it's possible to have this by building a router from scratch and using custom URLs for everything but it seems like a very bad way of doing things.

Ideally, I'd like to be able to initialize my router with something like 

```
router = routers.DefaultRouter(trailing_slash='optional')
router.register(r'Place', PlaceViewSet)
```

which would accept URLs of the form `Place/?$` instead of `Place/$`

**Comment by diosney** [comment]
I've been testing with the `trailing_slash=False` option and is working smoothly until now.

**Comment by psychok7** [comment]
Based on the comments here i ended up doing something like this:

```python
class OptionalSlashDefaultRouter(DefaultRouter):
    def __init__(self, *args, **kwargs):
        self.trailing_slash = '/?'

        if 'root_renderers' in kwargs:
            self.root_renderers = kwargs.pop('root_renderers')
        else:
            self.root_renderers = list(api_settings.DEFAULT_RENDERER_CLASSES)

        super(SimpleRouter, self).__init__()


router = OptionalSlashDefaultRouter()
```

**Comment by adeelyounas** [comment]
@psychok7 does follow class cause any problems?
```
class OptionalTrailingSlashRouter(routers.DefaultRouter):
    def __init__(self, *args, **kwargs):
        super(OptionalTrailingSlashRouter, self).__init__(*args, **kwargs)
        self.trailing_slash = '/?'
```

**Comment by psychok7** [comment]
@adeelyounas i don't think i have tried that one, but i guess it shouldn't. Please let us know if it works properly.

**Comment by adeelyounas** [comment]
@psychok7 I did not find any issues so far but share if I find one.

**Comment by awaisdar001** [comment]
Complete solution with Django 1.11
```
from django.conf.urls import include, url
from rest_framework.routers import DefaultRouter

from api.v1.views import BookViewSet

router = DefaultRouter()
slashless_router = DefaultRouter(trailing_slash=False)
slashless_router.registry = router.registry[:]
router.register(r'^books', BookViewSet, base_name='books')

urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^', include(slashless_router.urls)),
]

```
