### ISSUE TITLE
TokenAuthentication reference in docs

### ISSUE THREAD

**Issue by grumpyp** [encode/django-rest-framework#9062]
Is the TokenAuthentication reference in the docs still up to date?
https://www.django-rest-framework.org/api-guide/authentication/

If I check the repo and head to their documentation I run into a 404.

**Comment by NebulaAnish** [comment]
Hey, am I missing something? The link is working fine and the TokenAuthentication reference in docs seems fine too.

**Comment by grumpyp** [comment]
If you click on `Django REST Knox` and from that repo on `Documentation` you'll get a 404.

That's why I was wondering if this project is still the recommended one to use with `django-rest-framework`.

I just saw an answer in the issue here:
https://github.com/jazzband/django-rest-knox/issues/306

All good, it'll be fixed in the next version.

Thx
