### ISSUE TITLE
input type="date" validation message incorrect

### ISSUE THREAD

**Issue by mangelozzi** [encode/django-rest-framework#9200]
If one has a date, that is blank and gets posted to the server, the server responds with:

`Date has wrong format. Use one of these formats instead: YYYY-MM-DD.`

This used to be correct when all date's where in the format `YYYY-MM-DD`. But with chrome 116 and locale set to South African English, my browser shows it in the format `DD-MM-YYYY`. This is confusing to the user, because the way its shown to the user is not the way the `<input type="date">` reports it.

Here's an example:
![image](https://github.com/encode/django-rest-framework/assets/19764314/197d3877-51c4-46ff-a315-4928af8776b6)

This means unless your countries locale is in the format of `YYYY-MM-DD`, i.e. almost everyone except Swedan, then the error message is misleading to the user. Maybe The error message should just be: ``Date has wrong format`, which does sound like great english to me... how about `Date format is invalid`

PS this can't be fixed on the backend, because it's does not know what the front end locale is.

**Comment by Tyeion** [comment]
So, exactly what you want with it ?

**Comment by mangelozzi** [comment]
An error message that is not misleading/incorrect. 
Maybe to just shorten the error message to "Date has the wrong format".

**Comment by tomchristie** [comment]
> this can't be fixed on the backend

There's an unavoidable trade-off between what's typically the most sensible behaviour for us here.
I'd we treat this as out of scope, and suggest using custom error messages.
