### ISSUE TITLE
rest_framework.urls doesn't work with LogoutView in Django 5.0

### ISSUE THREAD

**Issue by gaurovsoni** [encode/django-rest-framework#9206]
In Django 5.0, GET request for logout was removed (only POST supported now) and it seems like in DRF we still do GET request to the endpoint. 

# https://docs.djangoproject.com/en/5.0/releases/5.0/
- Support for logging out via GET requests in the django.contrib.auth.views.LogoutView and django.contrib.auth.views.logout_then_login() is removed.

**Comment by auvipy** [comment]
can you share the traceback as well please?

**Comment by meaniebeanie22** [comment]
Is there any way to bypass this in the mean time? I updated my django version to 5.0 and as such can't find a way to logout

**Comment by Scorpil** [comment]
@meaniebeanie22 

As a workaround until this gets fixed, I added logout view manually:

```python
class LogoutView(APIView):
    """
    Djano 5 does not have GET logout route anymore, so Django Rest Framework UI can't log out.
    This is a workaround until Django Rest Framework implements POST logout.
    Details: https://github.com/encode/django-rest-framework/issues/9206
    """
    permission_classes = [permissions.IsAuthenticated]

    def get(self, request):
        print("GET", request)
        logout(request)
        return redirect('/')
```

then in `urls.py` add it to urlpatterns:
```
path('api-auth/logout/', LogoutView.as_view(), name='logout'),
```

**Comment by MichaelGatesDev** [comment]
> @meaniebeanie22
> 
> As a workaround until this gets fixed, I added logout view manually:
> 
> ```python
> class LogoutView(APIView):
>     """
>     Djano 5 does not have GET logout route anymore, so Django Rest Framework UI can't log out.
>     This is a workaround until Django Rest Framework implements POST logout.
>     Details: https://github.com/encode/django-rest-framework/issues/9206
>     """
>     permission_classes = [permissions.IsAuthenticated]
> 
>     def get(self, request):
>         logout(request)
>         return redirect('/')
> ```
> 
> then in `urls.py` add it to urlpatterns:
> 
> ```
> path('api-auth/logout/', LogoutView.as_view(), name='logout'),
> ```

As a side-note to this fix, make sure you put the url pattern *before* you include `rest_framework.urls` (if you are doing so) otherwise it will not work.


e.g.
```
urlpatterns = [
    # path('api/', views.ApiView.as_view()),
    path('api/', include(router.urls)),
    path('api/auth/logout/', LogoutView.as_view(), name='logout'), 
    path('api/auth/', include('rest_framework.urls')),
```

**Comment by auvipy** [comment]
should we need some documentation updated?

**Comment by gaurovsoni** [comment]
Workaround:
```python
from django.contrib.auth.views import LogoutView

class PatchLogoutView(LogoutView):
    http_method_names = ["get", "post", "options"]

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)
```

Then on urls

```python
path("api-auth/logout/", PatchLogoutView.as_view(), name="logout"),
path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
```

**Comment by TGoddessana** [comment]
hello. What can I do? I'd like to contribute.

**Comment by auvipy** [comment]
If it is already implemented in main branch then what should we need to change actually?

**Comment by gaurovsoni** [comment]
> If it is already implemented in main branch then what should we need to change actually?

I don't think there is a need to change anything now. since it's already [merged #9208 ](https://github.com/encode/django-rest-framework/pull/9208). Just waiting for official [djangorestframework](https://pypi.org/project/djangorestframework/) package update.

**Comment by auvipy** [comment]
thanks.

**Comment by joeisone** [comment]
Hi can someone please help? Logout page is still not working

url:
from django.contrib import admin
from django.urls import path,include
from .views import Index,SignUpView,PatchLogoutView
from django.contrib.auth import views as auth_views
from rest_framework import routers, serializers, viewsets

urlpatterns = [
    path('',Index.as_view(),name='index'),
    path('signup/',SignUpView.as_view(),name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='inventory/login.html'),name='login'),
    path("api-auth/logout/", PatchLogoutView.as_view(), name='logout'),
    path('api-auth/', include('rest_framework.urls',namespace="rest_framework")),


views:
class PatchLogoutView(LogoutView):
    http_method_names = ["get", "post", "options"]
    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)
