### ISSUE TITLE
bug: Serializer can't constrain field uniqueness

### ISSUE THREAD

**Issue by Birddle** [encode/django-rest-framework#9268]
## Checklist

- [x] Raised initially as discussion #...
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
Here's my code. When I configure the uniqueness check in the sequencer, it doesn't work.
For example when I add 'category' and 'Category' it will both be successfully inserted into the database
```

class CategoryView(generics.ListCreateAPIView, generics.RetrieveUpdateDestroyAPIView):
    authentication_classes = [OAuth2Authentication]
    permission_classes = [AllowAny]

    queryset = Category.objects.all()
    serializer_class = CategorySerializer

    def get(self, request, *args, **kwargs):
        if 'pk' in kwargs:
            return self.retrieve(request, *args, **kwargs)
        else:
            return self.list(request, *args, **kwargs)


class CategorySerializer(serializers.ModelSerializer):
    name = serializers.CharField(min_length=2, validators=[
        validators.UniqueValidator(queryset=Category.objects.all(), message='Category with this name already exists.')
        ])
    class Meta:
        model=Category
        fields=['id', 'name']
        
class Category(models.Model):
    name = models.CharField(max_length=32, unique=True)
    update_on = models.DateField(auto_now=True)

    def __str__(self) -> str:
        return self.name
```

**Comment by auvipy** [comment]
there are changes in the main branch, change you try it please?

**Comment by codespearhead** [comment]
Reminder for @Birddle

**Comment by Birddle** [comment]
Im not trying this change, i just custom `def to_internal_value()`

**Comment by tomchristie** [comment]
> Raised initially as discussion #...
