### ISSUE TITLE
_delegate_text was removed in Django 5.

### ISSUE THREAD

**Issue by jayden-arrai** [encode/django-rest-framework#9274]
## Checklist

- [ ] Raised initially as discussion #...
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [ ] I have reduced the issue to the simplest possible case.

https://github.com/encode/django-rest-framework/blob/4c7c693f1555689cda88eb59a4353db69aa6f5b1/rest_framework/utils/representation.py#L30-L31

force_str has a built in parameter called `strings_only`.  So the version number should be checked, and then if it is django 5, it should do the following instead of using delegate_text.

```python
        value = force_str(value, strings_only=True)
```

**Comment by jayden-arrai** [comment]
I'd make a pull request, if I had time, but you might get to this before I can, since it is relatively simple.

**Comment by auvipy** [comment]
would be helpful If you could come with a PR
