### ISSUE TITLE
3.15.0 - bug in rendering `%` characters from `ValidationError`

### ISSUE THREAD

**Issue by smallwat3r** [encode/django-rest-framework#9295]
The new `3.15.0` release introduced a bug in rendering errors from the `ValidationError` exception class.

Given a serializer:
```python
class MySerializer(Serializer):
    departure_datetime = serializers.DateTimeField(
        required=True,
        format="%Y-%m-%d %H:%M:%S",
        error_messages={"invalid": "Expects format %Y-%m-%d %H:%M:%S"},
    )
```

Calling `ValidationError` would raise the exception:
```
  File "/.../.venv/lib/python3.11/site-packages/rest_framework/fields.py", line 603, in fail
    raise ValidationError(message_string, code=key)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../.venv/lib/python3.11/site-packages/rest_framework/exceptions.py", line 160, in __init__
    detail = [detail % params]
              ~~~~~~~^~~~~~~~
ValueError: unsupported format character 'Y' (0x59) at index 27
```

As expected, this can easily be reproduced in the console:
```python
>>> ValidationError("Expects format %Y-%m-%d %H:%M:%S")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../.venv/lib/python3.11/site-packages/rest_framework/exceptions.py", line 160, in __init__
    detail = [detail % params]
              ~~~~~~~^~~~~~~~
ValueError: unsupported format character 'Y' (0x59) at index 16
```
or
```python
>>> ["Expects format %Y-%m-%d %H:%M:%S" % {}]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: unsupported format character 'Y' (0x59) at index 16
```

A solution would be to escape with double `%` characters any occurrence of `%` in the error messages.

```python
class MySerializer(Serializer):
    departure_datetime = serializers.DateTimeField(
        required=True,
        format="%Y-%m-%d %H:%M:%S",
        error_messages={"invalid": "Expects format %%Y-%%m-%%d %%H:%%M:%%S"},
    )
```

Unsure this is a choice by design or not, as this wouldn't be the case on `3.14.x`?

**Comment by AlanCoding** [comment]
This is coming from https://github.com/encode/django-rest-framework/pull/8863, which is very difficult to live with. The original motivation of that, from https://github.com/encode/django-rest-framework/issues/8077, had a reason of using more standard Django / python exception argument. But if you look at the Django error behavior:

```python
from django.core.exceptions import ValidationError as dValidationError

dValidationError("Expects format %Y-%m-%d %H:%M:%S")
dValidationError("Expects format %Y-%m-%d %H:%M:%S").error_list
```

It does no similar formatting when given such a string.

**Comment by auvipy** [comment]
related fix https://github.com/encode/django-rest-framework/pull/9313

**Comment by tomchristie** [comment]
Suggested for 3.15.1... revert https://github.com/encode/django-rest-framework/pull/8863

**Comment by dadamfon** [comment]
With this change we have an issue: *** TypeError: not enough arguments for format string

Example:
```python
raise ValidationError('%22safe')
*** rest_framework.exceptions.ValidationError: [ErrorDetail(string='                    {}afe', code='invalid')]
```

Take in count that the string really doesn't have a format string, is part of an URL so we need to print the value properly for the error message, but it takes it as a format string.
