### ISSUE TITLE
Error: An admin for model "User" has to be registered to be referenced by TokenAdmin.autocomplete_fields.

### ISSUE THREAD

**Issue by tomchristie** [encode/django-rest-framework#9300]
### Discussed in https://github.com/encode/django-rest-framework/discussions/9296

<div type='discussions-op-text'>

<sup>Originally posted by **kevinrenskers** March 18, 2024</sup>
After updating to DRF 3.15.0 I am now getting the following error when starting my Django server:

`<class 'rest_framework.authtoken.admin.TokenAdmin'>: (admin.E039) An admin for model "User" has to be registered to be referenced by TokenAdmin.autocomplete_fields.`

I am using a custom AdminSite instance where only the ModelAdmins that I specifically register to it are shown in my admin site. I have not registered TokenAdmin to my AdminSite, because it's not something we want to see in our admin site. I also have a custom User model, but its ModelAdmin is registered with my custom AdminSite.

It seems that DRF can't handle this situation. I guess that it only looks through the default AdminSite for what is registered there? How can I make DRF just ignore the TokenAdmin? I don't want it in our admin site, as we don't use tokens (only sessions).</div>

**Comment by alexdlaird** [comment]
I am also now seeing this error after bumping from 3.14.0 to 3.15.0. From Google, it appears this is coming from Django's command validation, not DRF specifically, but I believe it was introduced to DRF via [this pull request](https://github.com/encode/django-rest-framework/pull/8534/files), and it's unclear how to resolve the issue in DRF. The error suggests registering an admin model for "User", but [I already have been](https://github.com/HeliumEdu/platform/blob/1b5560eef0c90c29ae601804165266e113a54e09/helium/auth/admin.py#L123), and doing so before registering the `TokenAdmin`:

```python
from django.contrib import admin

admin.site.register(get_user_model(), UserAdmin)
admin.site.register(Token, TokenAdmin)
```

So what has changed with this release, and what do we need to change? Do we need to register something elsewhere?

**Comment by browniebroke** [comment]
I noticed that you have a custom `User` model, right? So I _think_ what happens is:

- Django register the default User model with the default admin
- DRF register the TokenProxy model with the default admin. But this model references your custom User model: https://github.com/encode/django-rest-framework/blob/337ba211e82628c0a0bfc7340c45b22e725f8162/rest_framework/authtoken/admin.py#L11

However, Django checks that the `autocomplete_fields` matches a model which is registered in the admin, but the user model registered in the default admin is the default one, not the custom one.

The simplest thing might be to revert the PR that caused it (I was waiting for this specific fix, but it doesn't work in all cases) and perhaps expand the documentation, [which already explains how to patch the `TokenAdmin`](https://www.django-rest-framework.org/api-guide/authentication/#with-django-admin). If folks want auto-complete fields, they can fix it in user land.

**Comment by alexdlaird** [comment]
Agreed I think that PR should be reverted. DRF can either set `autocomplete_fields` on the `TokenAdmin` as it does [here](https://github.com/encode/django-rest-framework/blob/337ba211e82628c0a0bfc7340c45b22e725f8162/rest_framework/authtoken/admin.py#L31), or call `admin.site.register(TokenProxy, TokenAdmin)`, as it does [here](https://github.com/encode/django-rest-framework/blob/337ba211e82628c0a0bfc7340c45b22e725f8162/rest_framework/authtoken/admin.py#L55).

It can't do both, making this decision is too implementation-specific and thus won't work in all cases (as we are finding here).

**Comment by alexdlaird** [comment]
Created a PR to revert. For those looking to apply the same logic and enable auto-complete once the revert PR is merged, here is the code:

```python
from rest_framework.authtoken.admin import TokenAdmin

TokenAdmin.autocomplete_fields = ("user",)
```

**Comment by Mehourka** [comment]
I've got the same issue, reverted back to 3.14.0.

**Comment by hosamhamdy258** [comment]
temporary solution 

added search_fields in my custom admin class

`search_fields = ("USERNAME_FIELD",)
`
