### ISSUE TITLE
3.15 backward compatibility issue with 3.14 - `rest_framework.filters.SearchFilter.get_search_terms` returns `str` instead of `list`

### ISSUE THREAD

**Issue by tomchristie** [encode/django-rest-framework#9308]
### Discussed in https://github.com/encode/django-rest-framework/discussions/9307

<div type='discussions-op-text'>

<sup>Originally posted by **freenoth** March 19, 2024</sup>
in 3.14 the `get_search_terms` method of `rest_framework.filters.SearchFilter` class was returning a **list** of terms
![image](https://github.com/encode/django-rest-framework/assets/2629328/05f7b36c-1d06-461e-b7e6-5737b7c03e93)

so we were able to iterate the search terms directly
![image](https://github.com/encode/django-rest-framework/assets/2629328/5cc38777-058d-4be5-a237-fa04924f7b49)

in 3.15 the same method `get_search_terms` is returning a **string** representation
![image](https://github.com/encode/django-rest-framework/assets/2629328/6c27762a-64eb-42ef-80cc-a80cfcb8ea99)

and to convert the `str` to a `list` an additional function was introduced `rest_framework.filters.search_smart_split`:
![image](https://github.com/encode/django-rest-framework/assets/2629328/c6bbb17a-1463-421d-97bd-f41b3cdf7c16)

and now we have to use this function to iterate the terms explicitly
![image](https://github.com/encode/django-rest-framework/assets/2629328/f317bd30-948c-4f90-af8e-a73d6390c4f2)

So the changing of return value type (and the result itself, actually) can break some custom classes, that are using the basic functionality. Moreover it's hard to figure out what is wrong, because both `list` and `str` are iterable, so the implementation works, but with the wrong results.

Example:

I had a custom Search filter class based on `rest_framework.filters.SearchFilter` with overrided `filter_queryset` method, so I used the basic method to get the list of search terms
```python
        search_terms = self.get_search_terms(request)
```
and a simple iteration by search terms works well

```python
        for search_term in search_terms:
```

but after upgrading to 3.15, my iteration started working differently, because now `get_search_terms` is returning a string -> so it works as iteration by string, it's adding every symbol of this string as independent query, instead of one query

for input `?search=asd` it builds a query like that
```sql
WHERE ((UPPER("resource"."id"::text) LIKE UPPER(%a%) OR UPPER("resource"."name"::text) LIKE UPPER(%a%))
	AND (UPPER("resource"."id"::text) LIKE UPPER(%s%) OR UPPER("resource"."name"::text) LIKE UPPER(%s%)) 
	AND (UPPER("resource"."id"::text) LIKE UPPER(%d%) OR UPPER("resource"."name"::text) LIKE UPPER(%d%)))
```

instead of a single search query
```sql
WHERE (UPPER("resource"."id"::text) LIKE UPPER(%asd%) OR UPPER("resource"."name"::text) LIKE UPPER(%asd%))
```

so we have to add using a `rest_framework.filters.search_smart_split` function explicitly everywhere to iterate search terms in an old way
```python
        for search_term in search_smart_split(search_terms):
```

is there a chance to use `search_smart_split` inside the `rest_framework.filters.SearchFilter.get_search_terms` to not to break backward compatibility and method behavior?</div>

**Comment by tomchristie** [comment]
Suggest reverting #9017.

**Comment by tomchristie** [comment]
Okay, I can't automatically revert #9017 through the GH interface.
If anyone's up for creating the revert PR for that, would be appreciated.

**Comment by auvipy** [comment]
I have to look into it
