### ISSUE TITLE
3.15 regression: UpdateModelMixin breaks views using Manager objects as queryset

### ISSUE THREAD

**Issue by peterthomassen** [encode/django-rest-framework#9319]
- Since #8043, `UpdateModelMixin.update()` accesses the queryset's `_prefetch_related_lookups` attribute.
- Manager objects don't have this attribute.
- This causes an exception when the queryset is, e.g., a `RelatedManager`:
  ```python
   def get_queryset(self):
       return self.user.somerelated_set
   ```

Notes:
- `get_queryset()` is **not** expected to return a `QuerySet`. [This is explicitly stated in `get_queryset()`'s docstring.](https://github.com/encode/django-rest-framework/blob/77ef27f18fc7c11e1d2e5fd4aaa8acc51cda6792/rest_framework/generics.py#L55)
- In fact, that docstring implies that there is no expectation that there is a `_prefetch_related_lookups` attribute.
- My particular instance of the problem could be fixed on the application side by adding `.all()`. However, that would cause early evaluation of the queryset *before filtering*. That's not an option; SQL queries should run only once all WHERE conditions have been applied.

This is a regression that simply breaks stuff that has been working with the stable API. The change should be reverted.

(This is similar to #9306, but not the same.)

**Comment by browniebroke** [comment]
I think that explains that error which was reported in a discussion https://github.com/encode/django-rest-framework/discussions/9304

I was wondering what use case would trigger it, that makes sense now.

**Comment by browniebroke** [comment]
I think that might be covered in my fix https://github.com/encode/django-rest-framework/pull/9314

Do you have a minimal example that I could use in the tests?

**Comment by tomchristie** [comment]
@browniebroke Okay thanks, so would a sensible course of action be to start by reverting #8043 for a 3.15.1, so we can later consider re-issuing a non-breaking fix without the additional time-pressure?

**Comment by browniebroke** [comment]
Sounds sensible yes 👍🏻  I don't even understand what #8043 was trying to achieve in the first place...
