### ISSUE TITLE
Version 3.15.1

### ISSUE THREAD

**Issue by tomchristie** [encode/django-rest-framework#9331]
This is a patch release dealing with a number of unforeseen issues in 3.15.0.

Please see https://github.com/encode/django-rest-framework/discussions/9270 for discussion on the project management, and ensuring we're able to get into a much more carefully considered release process for future releases.

(In brief: The project should broadly just be tracking Django versions, and dealing with required security fixes. We need a much higher bar to accepting contributions, and need some clear guidelines to help us manage that process with as little noise and churn as possible.)

---

*The following change has been fixed*...

- [x] #9308 

---

*The following changes have all been reverted, for the time being*...

- [x] #9319 - Resolved via #9327
- [x] #9317 - Resolved via #9326
- [x] #9310 - Resolved via #9333
- [x] #9306 - Resolved via #9327
- [x] #9299 - Resolved via #9332
- [x] #9295 - Resolved via #9330
- [x] #9300 - Resolved via #9301
- [x] #9334 - Resolved via #9335

**Comment by peterthomassen** [comment]
Consider adding #9334
