### ISSUE TITLE
3.15 regression: Unset default namespace version suddenly raises 404

### ISSUE THREAD

**Issue by peterthomassen** [encode/django-rest-framework#9334]
- The intention of #7278 seems to be to deal with situations where `DEFAULT_VERSION` is ignored. The description of the fix relates to non-`None` values of `DEFAULT_VERSION`.
- When `DEFAULT_VERSION` is `None` and `ALLOWED_VERSIONS` is non-empty, [the new code now raises 404](https://github.com/Kostia-K/django-rest-framework/blob/7050b4d36ecc3ce395bc097798af6bf9c99a28f0/rest_framework/versioning.py#L130).
- In 3.14, `None` would be returned in this case. This suddenly raises 404 where previously the view was properly run.

This is a regression that significantly changes the API. The change should be reverted.

**Comment by auvipy** [comment]
https://github.com/encode/django-rest-framework/pull/9335

**Comment by peterthomassen** [comment]
Fair enough, it's actually not a big deal to make that change. The issue is more about the unexpected breakage, instead of going through the usual deprecation stages.
