### ISSUE TITLE
Writing null or empty string to FileField does not empty the reference

### ISSUE THREAD

**Issue by wbbradley** [encode/django-rest-framework#937]
It does not seem possible to use PATCH on a FileField to null out the field. Is this by design?

**Comment by litchfield** [comment]
We're using PATCH with FileFields/ImageFields etc, and on the frontend they're objects, so more natural to express empty as null than an empty string. Here's our hack, applied to our base serializer --

```
    def get_extra_kwargs(self):
        extra_kwargs = super().get_extra_kwargs()
        for f in self.Meta.model._meta.get_fields():
            # Hack to always allow_null on FileFields
            if isinstance(f, FileField):
                kwargs = extra_kwargs.get(f.name, {})
                kwargs['allow_null'] = True
                extra_kwargs[f.name] = kwargs
        return extra_kwargs```

**Comment by johncpang** [comment]
> We're using PATCH with FileFields/ImageFields etc, so need a way of clearing the individual field. On our frontend the files are objects, so more natural to express empty state as null rather than an empty string.
> 
> Here's our hack, applied to our base serializer --
> 
> ```
>     def get_extra_kwargs(self):
>         extra_kwargs = super().get_extra_kwargs()
>         for f in self.Meta.model._meta.get_fields():
>             # Hack to always allow_null on FileFields
>             if isinstance(f, FileField):
>                 kwargs = extra_kwargs.get(f.name, {})
>                 kwargs['allow_null'] = True
>                 extra_kwargs[f.name] = kwargs
>         return extra_kwargs```
> ```

I verified, this works.  However, I also found that another [solution](https://stackoverflow.com/a/48678529/3731039) which might be a bit better.

Copy from the source, in serializers add "allow_null=True" to the ImageField / FileField:

```django 
class PartSerializer(serializers.ModelSerializer):
    image = serializers.ImageField(max_length=None, allow_empty_file=True, allow_null=True, required=False)

    class Meta:
        model = Part
        fields = ('id', 'image')
```
