### ISSUE TITLE
3.15 is raising required error on model nullable fields

### ISSUE THREAD

**Issue by Enorio** [encode/django-rest-framework#9378]
I have a model with nullable fields. Upgrading from 3.14 to 3.15 I'm getting this error:
`AssertionError: You cannot call .save() on a serializer with invalid data.`

When I print the `serializer.errors` after `serializer.is_valid()`, it says those fields are required. Is it possible that this is a bug, or do I have to manually override the field in the serializer to have the `required=False` kwarg?

**Comment by sevdog** [comment]
Could you provide a code sample of your model, serializer and data for checking?

**Comment by Enorio** [comment]
```python
class Foo(...):
    ...
    value = models.IntegerField(null=True)

class FooSerializer(serializers.ModelSerializer):
    class Meta:
        model = Foo
        fields = '__all__'


serializer = FooSerializer(data=data) # This data does not have the "value" field
serializer.is_valid()
saved_data = serializer.save()
```
Raises this error `AssertionError: You cannot call `.save()` on a serializer with invalid data.`

**Comment by sevdog** [comment]
The `value` field does not provide any [`default`](https://docs.djangoproject.com/en/5.0/ref/models/fields/#default), so it is expected to fail if no value for that field is provided.

The real issue would be how did that ever worked without a default in the first place?
It should have worked if you had `default=None` or [`blank=True`](https://docs.djangoproject.com/en/5.0/ref/models/fields/#blank) on your model's field (but I am not confident in the latter).

Usually a nullable field which is not required in forms is defined as: 

```python
class Foo(...):
    ...
    value = models.IntegerField(null=True, default=None, blank=True)
```

**Comment by sevdog** [comment]
> My guess is if you have only `null`, this counts as `default=None`?

It is not documented nor in the codebase of django such behaviour for [null](https://docs.djangoproject.com/en/3.2/ref/models/fields/#null) or [default](https://docs.djangoproject.com/en/3.2/ref/models/fields/#default). Django and the majority of DBMS does not suppose the default based on the assumption that a field is nullable.

I can only guess that there is something else which is providing a value for those fields in your project (a middleware? the frontend? custom views? custom serializers? custom base models?).

**Comment by Enorio** [comment]
I don't think so, what I have it's pretty standard.
I'll look better into it and check the differences between these 2 DRF versions.

**Comment by BPC-AnonymousBeast** [comment]
> I don't think so, what I have it's pretty standard. I'll look better into it and check the differences between these 2 DRF versions.

I tried to reproduce the error you are getting.
I have pretty much done what you have done. Infact, inspired by another similar issue, I have also added a foreign key constraint. I'm able to get back null even if I don't add that field in the body of the post request.
  
```
 class Color(models.Model):
      color_name = models.CharField(max_length=100)
  
      def __str__(self) -> str:
          return self.color_name

  class Person(models.Model):
      name = models.CharField(max_length=100)
      lastname = models.CharField(max_length=100,null=True)
      age = models.IntegerField(null=True)
      color = models.ForeignKey(Color, on_delete=models.CASCADE,related_name= 'color', null=True)
```


```
  class PeopleSerialiser(serializers.ModelSerializer):
      # my_id = serializers.PrimaryKeyRelatedField()
  
      class Meta:
          model = Person
          fields = "__all__"
```

 ```
 @api_view(['GET','POST'])
  def person(request):
      if request.method == 'GET':
          objs = Person.objects.all()
          serializer = PeopleSerialiser(objs, many = True)
          
          return Response(serializer.data)
```


<img width="625" alt="image" src="https://github.com/encode/django-rest-framework/assets/138981476/1334155b-bb55-42b6-b59b-ecf9318d674f">

If you want to make some changes to my code and try again to reproduce the error. Please let me know.
Note : I'm using djangorestframework 3.15.1 : -

<img width="464" alt="image" src="https://github.com/encode/django-rest-framework/assets/138981476/79374b86-6b10-45ea-bd53-524e6a4244f1">

**Comment by Enorio** [comment]
Can you try your view with the `is_valid()`, like this? Didn't try your code, but my error comes from the `is_valid()` method, that adds info to the `self._errors`
```python
@api_view(['GET','POST'])
 def person(request):
     if request.method == 'GET':
         objs = Person.objects.all()
         serializer = PeopleSerialiser(objs, many = True)
         serializer.is_valid(raise_exception=True)
         
         return Response(serializer.data)
```

**Comment by BPC-AnonymousBeast** [comment]
> ```python
> serializer.is_valid(raise_exception=True)
> ```

Adding this line to my code would not make any difference but I added that line to the POST view. There is no change in the output.
Following is the view and output : 
```
@api_view(['GET','POST'])
def person(request):
    if request.method == 'GET':
        objs = Person.objects.all()
        serializer = PeopleSerialiser(objs, many = True)

        return Response(serializer.data)
    
    else:
        data = request.data
        serializer = PeopleSerialiser(data=data)
        if serializer.is_valid(raise_exception=True):
            serializer.save()
            return Response(serializer.data)
        
        return Response(serializer.errors)
```

<img width="476" alt="image" src="https://github.com/encode/django-rest-framework/assets/138981476/3fee2f9c-8331-4172-864d-96594dd4d391">

Postman output : 
<img width="627" alt="image" src="https://github.com/encode/django-rest-framework/assets/138981476/28bf9286-451c-4e0b-b614-2df28a123ced">


Feel free to let me know if anything!!

**Comment by Enorio** [comment]
Ok, I apologize because the example that I posted was not complete, it was missing the a uniqueConstraint :sweat_smile:, I think its the same case as https://github.com/encode/django-rest-framework/issues/9410

I've created a new project with your example to validate this.

## Models
```python
class Color(models.Model):
    color_name = models.CharField(max_length=100)

    class Meta:
        verbose_name = "Color"
        verbose_name_plural = "Colors"
        ordering = ('id',)

class Person(models.Model):
    name = models.CharField(max_length=100)
    lastname = models.CharField(max_length=100, null=True)
    age = models.IntegerField(null=True)
    color = models.ForeignKey(Color, on_delete=models.CASCADE, related_name='color', null=True)

    class Meta:
        verbose_name = "Person"
        verbose_name_plural = "Persons"
        ordering = ('id',)
        constraints = [models.UniqueConstraint(name='unique_constraint', fields=('color', 'age'), )]
```

## Serializer
```python
class ColorSerializer(serializers.ModelSerializer):
    class Meta:
        model = Color
        fields = '__all__'

class PersonSerializer(serializers.ModelSerializer):
    class Meta:
        model = Person
        fields = "__all__"
```

## Viewset
```python
class DRFBugViewset(viewsets.ModelViewSet):
    serializer_class = PersonSerializer
```


## With DRF 3.14.0
![image](https://github.com/encode/django-rest-framework/assets/14897383/f4106c73-5cef-44b7-832b-5c5c419cc8b2)


## With DRF 3.15.1
![image](https://github.com/encode/django-rest-framework/assets/14897383/217d5058-58f2-4fce-836d-49c73b79ed92)

**Comment by rohanahata** [comment]
I am facing the same issue as @Enorio

**Comment by sevdog** [comment]
If everyone here is having this issue when there are `UniqueConstraint`s this may be a side effect of #7438 because the constraint adds a `UniqueTogetherValidator` for given fields and thus the validator is forcing those fields to be required.

**Comment by Enorio** [comment]
> If everyone here is having this issue when there are `UniqueConstraint`s this may be a side effect of #7438 because the constraint adds a `UniqueTogetherValidator` for given fields and thus the validator is forcing those fields to be required.

So basically I have to set a `default` value in the given fields to "bypass" the constraint added?

**Comment by browniebroke** [comment]
I tried to take the example from @Enorio [earlier](https://github.com/encode/django-rest-framework/issues/9378#issuecomment-2213536266) and I can reporduce the problem.

However, if I change it as follows (which I think means the same thing, from Django perspective):

```diff
  class Color(models.Model):
      color_name = models.CharField(max_length=100)
  
  class Person(models.Model):
      name = models.CharField(max_length=100)
      lastname = models.CharField(max_length=100, null=True)
      age = models.IntegerField(null=True)
      color = models.ForeignKey(Color, on_delete=models.CASCADE, related_name='color', null=True)
  
      class Meta:
-         constraints = [models.UniqueConstraint(name='unique_constraint', fields=('color', 'age'))]
+         unique_together = ('color', 'age')
```

Then it fails on both 3.14 and 3.15: https://github.com/encode/django-rest-framework/pull/9532. This is because `Meta.contraints` were completely ignored by DRF 3.14 and are now treated by 3.15+ as `unique_together`. 

From what I can tell, it's a change of behaviour due to adding support for a newer Django syntax.

**Comment by znotdead** [comment]
> I tried to take the example from @Enorio [earlier](https://github.com/encode/django-rest-framework/issues/9378#issuecomment-2213536266) and I can reporduce the problem.
> 
> However, if I change it as follows (which I think [means the same thing](https://docs.djangoproject.com/en/5.0/ref/models/options/#unique-together), from Django perspective):
> 
> ```diff
>   class Color(models.Model):
>       color_name = models.CharField(max_length=100)
>   
>   class Person(models.Model):
>       name = models.CharField(max_length=100)
>       lastname = models.CharField(max_length=100, null=True)
>       age = models.IntegerField(null=True)
>       color = models.ForeignKey(Color, on_delete=models.CASCADE, related_name='color', null=True)
>   
>       class Meta:
> -         constraints = [models.UniqueConstraint(name='unique_constraint', fields=('color', 'age'))]
> +         unique_together = ('color', 'age')
> ```
> 
> Then it fails on both 3.14 and 3.15: #9532. This is because `Meta.contraints` were completely ignored by DRF 3.14 and are now treated by 3.15+ as `unique_together`.
> 
> From what I can tell, it's a change of behaviour due to adding support for a newer Django syntax.

According to docs unique_together can be deprecated later and it is recommended to use constraints:

> Use [UniqueConstraint](https://docs.djangoproject.com/en/5.0/ref/models/constraints/#django.db.models.UniqueConstraint) with the [constraints](https://docs.djangoproject.com/en/5.0/ref/models/options/#django.db.models.Options.constraints) option instead.
> 
> [UniqueConstraint](https://docs.djangoproject.com/en/5.0/ref/models/constraints/#django.db.models.UniqueConstraint) provides more functionality than unique_together. unique_together may be deprecated in the future.

**Comment by browniebroke** [comment]
> According to docs unique_together can be deprecated later and it is recommended to use constraints

Yes, preceisely. They were designed as a more powerful replacement, and DRF handles constraints the same way as unique_together.

**Comment by znotdead** [comment]
> > According to docs unique_together can be deprecated later and it is recommended to use constraints
> 
> Yes, preceisely. They were designed as a more powerful replacement, and DRF handles constraints the same way as unique_together.

Except it doesn't support conditional constraints + cases where field is set just before save or based on other data not in request (i.e. defined in `pre_save` signal).

Workaround for this now is to add in `Meta` of serializer next:
```
        extra_kwargs = {
            # By default "unique together" validation enforces that all fields be required=True
            # field1 is conditional unique
            # field2 can be set in pre_save
            'field1': {'required': False},
            'field2': {'required': False},
        }
        validators = []  # Remove a default "unique together" constraint
```

So had to turn off as DRF does NOT handles constraints the same way.

**Comment by browniebroke** [comment]
Yes I agree conditional contraints aren't well supported, and I think there is another more appropriate issue for that case (#9358). 

The cases reported so far in here aren't making use of conditional constraints however, and without conditions I was only saying that the behaviour is consistent with DRF 3.14 `unique_together`.
