### ISSUE TITLE
a question about BooleanField

### ISSUE THREAD

**Issue by fanmaoyu0871** [encode/django-rest-framework#9407]
mysql table struct，the column is bit type:
![微信图片_20240517102212](https://github.com/encode/django-rest-framework/assets/11706426/74b8feb6-d485-490b-877e-8677008f35a0)

mysql data:
![image](https://github.com/encode/django-rest-framework/assets/11706426/8fea89d9-6091-4868-9d87-d4e636ea0027)

django model :
![image](https://github.com/encode/django-rest-framework/assets/11706426/d0b32241-c524-45b0-a19c-4a5fa7430592)

drf serializer:
![image](https://github.com/encode/django-rest-framework/assets/11706426/5ec89757-b1fd-4952-98ad-93e741ab62d6)

http response:
![image](https://github.com/encode/django-rest-framework/assets/11706426/89803b9e-262a-4fff-b966-a25bebd54c32)

my database value is 0，but it always return ”true“，i don't know why.

**Comment by angusholder** [comment]
MySQL doesn't have a dedicated bool type, so Django has to store bools as an integer. But `models.BooleanField` automatically converts the integer back to a bool after loading from the database; this is expected behaviour

**Comment by fanmaoyu0871** [comment]
> MySQL doesn't have a dedicated bool type, so Django has to store bools as an integer. But `models.BooleanField` automatically converts the integer back to a bool after loading from the database; this is expected behaviour

you see my value is 0, it's alway return true

**Comment by auvipy** [comment]
Any questions should be ask here instead https://github.com/encode/django-rest-framework/discussions
