### ISSUE TITLE
Incorrect serializer field in quickstart documentation

### ISSUE THREAD

**Issue by schajee** [encode/django-rest-framework#9415]
This is a small change, probably just a typo. 

In `docs/tutorial/quickstart.md`, under Serializers, the User and Group serializers both mention 'url' in the fields list. 

None of them have 'url' as a field.

**Comment by ajay09** [comment]
Please refer 
https://www.django-rest-framework.org/api-guide/serializers/#hyperlinkedmodelserializer

**Comment by auvipy** [comment]
I think it is OK. also please open discussions first in this kind of scenario.
