### ISSUE TITLE
Browsable API performance when very large number of instances to choose for relationship

### ISSUE THREAD

**Issue by pikeas** [encode/django-rest-framework#948]
**Edit by @tomchristie**: Updated title

API requests made with curl or ?format=json return immediately.

The same request made in the browser (eg, returning an unmodified Browsable API template) takes 2-3 minutes.

I've been trying to trace this for an hour and haven't had any luck. Known issue?

**Comment by debnet** [comment]
Since 3.x series deprecated the widget on Serializer field, is there a way to do it now?
