### ISSUE TITLE
Need for multi field 'slugs'

### ISSUE THREAD

**Issue by alexf101** [encode/django-rest-framework#952]
Hi guys,

I love the framework, but it seems that there are a lot of issues that are encountered when trying to define Related Fields.

I think the issue is that there is missing functionality for something that represents a unique set of parameters in the foreign object, i.e. a UNIQUE TOGETHER constraint.

The problem is that we often want to simplify API calls by allowing a single POST request to create an object and its related fields, but to separate these objects as entities in the backend. 

For example, I want this to be one request:

POST contact
{
  'name' : 'Alex',
  'address': {
    'number': 111,
    'street_name': 'Example Rd',
    'postcode': 4321
  },
}

But at the moment I either need to write custom code to unpack this request or separate it into two requests - one to create the address and get its id or url, the second to create the contact referencing it. (If I'm wrong and this can be done easily, please let me know!)

However, this shouldn't be necessary as since the three fields of address (number, street_name and postcode) are unique together, and any other fields that may be associated with address are nullable, there is no danger in 'writing-through' in this case.

We already have SlugRelatedField's which support this functionality for a single field, but AFAIK it can't at the moment be extended to several fields.

I propose that this is added as a parameter to the SlugRelatedField in serializer... there are a lot of people posting in forum's on Google Code whom this would help!

**Comment by sassanh** [comment]
@tomchristie  I think things has changed since 2013, maybe now you like to add this to core.

**Comment by tomchristie** [comment]
@sassanh This still falls into the "better as a third party package" category.
