### ISSUE TITLE
Warning with Django 5.1: "Converter 'drf_format_suffix' is already registered."

### ISSUE THREAD

**Issue by bblanchon** [encode/django-rest-framework#9523]
After upgrading to Django 5.1.1, I get the following warning:

```text
rest_framework\urlpatterns.py:108: RemovedInDjango60Warning: Converter 'drf_format_suffix' is already registered. Support for overriding registered converters is deprecated and will be removed in Django 6.0.
  register_converter(suffix_converter, converter_name)
```

I had no warning with Django 5.0.9.
I'm using version 3.15.2 of djangorestframework.

**Comment by browniebroke** [comment]
That was reported in https://github.com/encode/django-rest-framework/discussions/9495 and fixed in https://github.com/encode/django-rest-framework/pull/9512. It will be part of the next release.

**Comment by bblanchon** [comment]
Sorry. I searched the issues but forgot about the discussions.
Thank you very much for the quick reply.
