### ISSUE TITLE
SearchFilter incorrectly split value with istartswith filter

### ISSUE THREAD

**Issue by Arti3DPlayer** [encode/django-rest-framework#9530]
## Checklist

- [x] Raised initially as discussion https://github.com/encode/django-rest-framework/discussions/9271
- [x] This is not a feature request suitable for implementation outside this project. Please elaborate what it is:
  - [x] other type of bug fix
- [x] I have reduced the issue to the simplest possible case.

**Comment by tomchristie** [comment]
Closing unless/until there’s a resolution on the discussion.

**Comment by Arti3DPlayer** [comment]
@tomchristie I created discussion 3 months ago :(
