### ISSUE TITLE
restriction for using the word "objects" in API URL

### ISSUE THREAD

**Issue by KYPHI-HQ** [encode/django-rest-framework#9565]
it seems there is a bug or restriction using the word **objects** in the URL configuration of API as following

<img width="521" alt="Screenshot 2024-10-19 at 06 44 57" src="https://github.com/user-attachments/assets/67329f62-7be5-43b0-9ee5-7c19396eb2ee">

<img width="797" alt="Screenshot 2024-10-19 at 06 41 12" src="https://github.com/user-attachments/assets/0b260b18-1958-435d-a0d4-96ffad5b9dec">

### updating the code to following: changing the case from **objects** to **Objects** will not cause any error longer

<img width="500" alt="Screenshot 2024-10-19 at 06 40 31" src="https://github.com/user-attachments/assets/00bdf39d-9000-45a0-a919-7d96137847cd">

<img width="843" alt="Screenshot 2024-10-19 at 06 40 02" src="https://github.com/user-attachments/assets/be71f6b4-a5c3-4884-ad01-b2e8314d3b9d">

**Comment by tomchristie** [comment]
Seems infeasible. Perhaps try double checking may be some other config issue.

**Comment by Webinator2129** [comment]
> Seems infeasible. Perhaps try double checking may be some other config issue.

Took the time to reproduce the bug, report it with screenshots ...what is "infeasible" ? 

Did you had a look at the screenshots? It's just a case difference ..upper to lowercase 

Did you try to use the lowercase word "object" in a URL configuration as shown ?

**Comment by ulgens** [comment]
@KYPHI-HQ Did you try this without DRF? `objects` is not a keyword afaik I know but its special meaning is assigned at Django layer, not DRF.

**Comment by tomchristie** [comment]
> Did you Try to reproduce it ?

Nope. It falls into the category of "doesn't pass a sniff test". 

Perfectly possible I'm wrong & you're welcome to make a more compelling case here, perhaps isolate the issue yourself.

I don't know you and I don't owe you my time.

**Comment by browniebroke** [comment]
> Did you Try to reproduce it ?

I tried and was unable to reproduce on a minimal Django project: https://github.com/browniebroke/drf-object-viewset

Works perfectly fine:

![image](https://github.com/user-attachments/assets/3becd8a5-eb37-4e96-9f04-a78219a4ece6)

**Comment by TGoddessana** [comment]
I don't know if safari browser has secret tabs, but have you tried it? Browsers can also cache internally for things like trailing slashes.
