### ISSUE TITLE
Allow specifying fields to be serialized when instantiating Serializer

### ISSUE THREAD

**Issue by johtso** [encode/django-rest-framework#958]
It would be very useful to be able to specify `fields` or `exclude` at the point of instantiating a Serializer, and have that override Meta. Am I right in thinking there's no way of doing this at the moment?

**Comment by csarcom** [comment]
In case someone is looking for it, the docs url changed to:

http://www.django-rest-framework.org/api-guide/serializers/#dynamically-modifying-fields
