### ISSUE TITLE
`source` not working as expected

### ISSUE THREAD

**Issue by don-chalktalk** [encode/django-rest-framework#9586]
DRF version 3.14.0

```python
class Sample(serializers.Serializer):
    reference = serializers.CharField(required=False, source='response_id')

serializer = Sample(data={
    "response_id": '04__c5f8d1d0-87a3-4b9d-87f1-2a087ad6e4c7',
})
print(serializer.initial_data)

try:
    serializer.is_valid(raise_exception=True)
except Exception as e:
    print(e.detail)

print(serializer.validated_data)
```

Output:
```
initial data: {'response_id': '04__c5f8d1d0-87a3-4b9d-87f1-2a087ad6e4c7'}
validated data: OrderedDict()
```

## Checklist

- [ ] Raised initially as discussion #...
- [x] This is not a feature request suitable for implementation outside this project. Please elaborate what it is:
  - [ ] compatibility fix for new Django/Python version ...
  - [ ] other type of bug fix
  - [ ] other type of improvement that does not touch existing code or change existing behavior (e.g. wrapper for new Django field)
- [x] I have reduced the issue to the simplest possible case.

**Comment by browniebroke** [comment]
The serializer field is the key in the dictionary for the data, while the source maps to the underlying Python model/structure. 

This should work:

```python
serializer = Sample(data={
    "reference": '04__c5f8d1d0-87a3-4b9d-87f1-2a087ad6e4c7',
})
```

**Comment by don-chalktalk** [comment]
So you're saying there's no way to map a different key name from the input data without changing it in the dict?

**Comment by ulgens** [comment]
> The name of the attribute that will be used to populate the field. May be a method that only takes a self argument, such as URLField(source='get_absolute_url'), or may use dotted notation to traverse attributes, such as EmailField(source='user.email').

https://www.django-rest-framework.org/api-guide/fields/#source

I think it's fair to expect a dictionary key also works in the same way, and I believe that it should. @don-chalktalk I think your initial expectation from that argument makes sense, which at some point I, too, expected the same and then realized the implementation is not perfect. If the project was still alive, this could a bug fix - improvement but with the current state of things, I'll guess it will stay as annoyance that require a workaround.

**Comment by don-chalktalk** [comment]
Yeah i thought so after reading the docs as well. Even chatgpt thinks so as well 😅.
I did not know drf was not in active development. Thanks for the clarifications.
