### ISSUE TITLE
Remapping data keys to serializer attributes

### ISSUE THREAD

**Issue by flashingpumpkin** [encode/django-rest-framework#967]
Hi

I've run into the use case that some data can not be efficiently validated because of name clashes with Python's reserved words or naming rules. 

One example is the [Instagram API](http://instagram.com/developer/endpoints/users/): When validating a caption one cannot use `from` as a field name without running into Python syntax errors.

``` json
{
  "created_time": "1296710352",
  "text": "Inside le truc #foodtruck",
  "from": {
    "username": "kevin",
    "full_name": "Kevin Systrom",
    "type": "user",
    "id": "3"
  },
  "id": "26621408"
}
```

Another example is the [Mailgun API](http://documentation.mailgun.com/user_manual.html#parsed-messages-parameters): Python naming prevents creating variables with hyphens.

I've added an additional argument to fields to handle remapping data keys to field names and vica versa. The commit is available at:

flashingpumpkin/django-rest-framework@b2c54dc391ffcd36f2bcfc2efbf5966aad5504f8

I find it quite useful as this allows to validate the above JSON via:

``` python
class CaptionSerializer(serializers.Serializer):
    id = serializers.IntegerField()
    user = UserField(data_key = "from")
    text = serializers.CharField()
    created_time = TimestampField()
```

Same with Mailgun:

``` python
class MailgunSerializer(serializers.Serializer):
    body_plain = serializers.CharField(data_key = "body-plain")
    body_html  = serializers.CharField(data_key = "body-html")
    # etc
```

Happy to rename `data_key` into `data_source` or whatever would fit better.

Cheers, Alen

**Comment by alfetopito** [comment]
I just found myself in the need to use the problematic `from` field.

Has anything changed since last comment? Is there a more elegant solution?

I like @flashingpumpkin 's `data_key` approach, seems painless enough.

Cheers!

**Comment by g-cassie** [comment]
Hi, Also interested if this has changed in 3.x.  I can't find anything in the docs.  `from` is also the issue for me.

**Comment by AlJohri** [comment]
@tomchristie also running into this issue. any chance we can add something like a `data_key` to rename fields explicitly on deserialization?

**Comment by tomchristie** [comment]
@AlJohri - We won't be adding extra API for this case. Either third party packages, or better documentation of available workarounds for renaming keys would be preferable.

**Comment by AlJohri** [comment]
@tomchristie sure, can you explain briefly how dynamically modifying the fields would work? The fields I define would be the name I want it to persist as and I need to just rename upon deserialization.

**Comment by tomchristie** [comment]
There's some documentation on dynamically modifying fields available here: http://www.django-rest-framework.org/api-guide/serializers/#dynamically-modifying-fields

**Comment by ajbeach2** [comment]
I would like to see the data_key. The google recapcha form sends a field in the form of ''g-recaptcha-response'. If i was able to remap that to under scores, i would just do validata_g_recpatcha_response and validate it.

**Comment by sdeprez** [comment]
Same issue here. I receive a field `user_id` from Slack API that I need to rename to my model field `slack_user_id` because I have already have my own user on this model. Dynamically modifying the fields is quite a *not* straightforward way to do it, feels hackish and is not documented (for that precise purpose I mean). I think it's a pretty common use case that can appear every time you use an API whose output you don't control.

Also I'd say the existence of `source` parameter is more an argument *in favor* of supporting `data_key` (or any more appropriate name) since it's really the same operation the other way around. 

At the very least, would it possible to provide a small code snippet in the docs to show how it could be done?

**Comment by xordoquy** [comment]
@sdeprez the link provided by @tomchristie seems enough to me. Playing with self.fields should give you enough flexibility to work this around.

> Also I'd say the existence of source parameter is more an argument in favor of supporting data_key (or any more appropriate name) since it's really the same operation the other way around.

The other way around is the reason why it's counter intuitive. You don't ignore the field's name by using `source` while it's duplicated with `data_key` or whatever name that is.

**Comment by alexanderschulze** [comment]
Basically, I followed @tomchristie approach and wanted to share the result since I stumbled over this topic on Google and there's no copy'n'paste solution yet:

```python
class CustomSerializer(serializers.Serializer):
    from_ = serializers.CharField()
    for_ = serializers.IntegerField()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, field in list(self.fields.items()):
            if name.endswith("_"):
                self.fields.pop(name)
                self.fields[name[:-1]] = field
```

**Comment by sahrmann** [comment]
I would support introducing a `data_key` property (or similar). Changing self.fields can prevent to use the `validate_fieldname` shortcut (e.g., if the field name is `g-recaptcha-response`).

**Comment by fjsj** [comment]
Is there any third-party package that supports the `data_key` behavior and keeps `validate_{field_name}` working?

**Comment by scuerda** [comment]
Another option here is to implement a custom `to_internal_value`

Here is a sample.

Let's say we have incoming data in the form of 

`{'author_slug': 'some_author', 'title': 'A Fancy Book'}`

but our book and author models are in the form of

```
class Book(models.Model):
    title = models.CharField(...)
    author = models.ForeignKey(Author) 

class Author(models.Model):
    first_name = models.CharField(...)
    last_name = models.CharField(...)
    slug = models.CharField(...)
```

The `data_key` approach would be 

```
class BookSerializer(serializer.ModelSerializer):
    author = serializers.SlugRelatedField(
        many=False, 
        slug_field='slug', 
        queryset=Author.objects.all(),
        data_key='author_slug'
    )
    title = serializers.CharField()
```

Here is how to get this same behavior w/ `to_internal_value`:

```
class BookSerializer(serializer.ModelSerializer):
    author = serializers.SlugRelatedField(
        many=False, 
        slug_field='slug',
        queryset=Author.objects.all()
    )
    title = serializers.CharField()
    
    def to_internal_value(self, data):
        try:
            slug = data.pop('author_slug')
        except KeyError:
            raise serializers.ValidationError('author_slug is a required field or w/e you want to say')
        data['author'] = slug
        return super().to_initial_value(data)
```

If you had a custom `validate_author` method, this would get correctly called AFTER the data remapping took place.

**Comment by devmitrandir** [comment]
```python
from rest_framework import serializers

class RemapperSerializer(serializers.Serializer):

    mapping_fields = {}

    def to_internal_value(self, data):
        internal_data = {}

        for k, v in data.items():
            if new_key := self.mapping_fields.get(k):
                internal_data[new_key] = v
            else:
                internal_data[k] = v

        return super().to_internal_value(internal_data)


class MySerializer(RemapperSerializer):

    name = serializers.CharField()
    source = serializers.IntegerField()
    target = serializers.IntegerField(allow_null=True)

    mapping_fields = {
        'from': 'source',
        'to': 'target'
    }

    def validate_target(self, value):
        if value == -1:
           return None
        return value

data = {
   'name': 'abc',
   'from': 3,
   'to': -1
}
serializer = MySerializer(data=data)
serializer.is_valid(raise_exception=True)
print(serializer.validated_data)
# {'name': 'abc', 'source': 3, 'target': None}
```
