### ISSUE TITLE
Initial syncdb doesn't work if authtoken is installed and tokens are auto-generated via a signal

### ISSUE THREAD

**Issue by hxu** [encode/django-rest-framework#987]
In the docs, there [is a snippet](http://django-rest-framework.org/api-guide/authentication.html#tokenauthentication) that describes a signal to create tokens automatically for users.  However, this causes syncdb to fail in a new deployment of the application immediately after creating the first superuser, with the error:

```
DatabaseError: relation "authtoken_token" does not exist
LINE 1: ...oken"."user_id", "authtoken_token"."created" FROM "authtoken...
```

The reason is because the authtoken table has not been created yet, so the signal is triggered, but cannot find the relation.  In order to create the table, you need to run migrate.  However, you can't migrate because the south migration history table hasn't been created.

I guess there is no "fix," but maybe the docs should more strongly recommend an alternative method of generating the tokens, such as upon first request.

**Comment by FlavioAlexander** [comment]
It has been 2 years already since your question. However, I run into the same problem. The solution is simple : python manage.py migrate

**Comment by ibsenriou** [comment]
Hi! Nearly ten years after your question I had a similar issue when doing a tutorial. I forgot to drop my container so when using docker-compose up it would run the python manage.py
